wso2/docs-apim

en/docs/develop/product-apis/devportal-apis/devportal-v1/devportal-v1.yaml

Fixes https://github.com/wso2/docs-apim/issues/2507
APIM 3.2.0

[3.2.0] Fix REST API issues

---

en/docs/learn/api-gateway/handlers/writing-custom-handlers.md

https://github.com/wso2/docs-apim/issues/1826
> Link(s) to product documentation that addresses the changes of this PR. If no …

Fixes missing log4j2 configs from custom handler docs

---

en/docs/develop/extending-api-manager/extending-gateway/writing-custom-handlers.md

Resolves the issue: https://github.com/wso2/docs-apim/issues/1826
https://github.com/wso2/docs-apim/issues/2291
> Link(s) to …

[APIM 3.1.0] Fixes log4j2 issue in custom handler 

---

en/docs/develop/extending-api-manager/extending-gateway/writing-custom-handlers.md

Resolves the issue: https://github.com/wso2/docs-apim/issues/1826
> Link(s) to product documentation that addresses the changes …

[APIM 3.2.0] Fixes log4j2 issue in custom handler 

---

en/docs/learn/api-controller/getting-started-with-wso2-api-controller.md

Fix https://github.com/wso2/docs-apim/issues/2513 …

Fix https://github.com/wso2/docs-apim/issues/2513

---

en/docs/reference/customize-product/extending-api-manager/extending-gateway/writing-custom-handlers.md

Fixes https://github.com/wso2/docs-apim/issues/1826 …

[4.0.0] Fixes log4j2 issue in custom handler 

---

en/docs/administer/managing-users-and-roles/managing-user-roles.md
en/docs/administer/managing-users-and-roles/managing-user-stores/configure-primary-user-store/configuring-a-jdbc-user-store.md
en/docs/administer/managing-users-and-roles/managing-user-stores/configure-primary-user-store/configuring-the-primary-user-store.md
en/docs/install-and-setup/setup/setting-up-databases/overview.md

Fix https://github.com/wso2/docs-apim/issues/1311
Fix https://github.com/wso2/docs-apim/issues/2277
Fix https://github.com/wso2/docs-apim/issues/1620

Fix doc issues

---

en/docs/administer/managing-users-and-roles/managing-user-stores/configuring-secondary-user-stores.md

Fixes issue https://github.com/wso2/docs-apim/issues/1343

Fixes issue #1343

---

en/tools/config-catalog-generator/data/configs.json
en/tools/config-catalog-generator/data/indexing.toml

Fix https://github.com/wso2/docs-apim/issues/1893

Add reindexing configs

---

en/docs/reference/customize-product/extending-api-manager/extending-workflows/configuring-workflows-for-tenants.md

[4.0.0] Fix issues in workflow extension doc

---

en/docs/develop/extending-api-manager/extending-workflows/configuring-workflows-for-tenants.md

- This PR fixes #1567
- Fixes alignment issues in workflow extension documentation.

[3.2.0] Fix issues in workflow extension doc

---

en/docs/develop/extending-api-manager/extending-workflows/configuring-workflows-for-tenants.md

[3.1.0] Fix issues in workflow extension doc

---

en/docs/install-and-setup/setup/api-controller/getting-started-with-wso2-api-controller.md
en/docs/install-and-setup/setup/api-controller/importing-apis-via-dev-first-approach.md

Fixes: https://github.com/wso2/docs-apim/issues/1886
Reducing the confusions that may arise due to https://github.com/wso2/docs-apim/pull/1891
- Made the description of change-status API command to make it less verbose
- Simplified the description on --definition flag on apictl init command with the relevant example for api.yaml
https://github.com/wso2/docs-apim/pull/1891

Simplify the description of the sample API definition in APICTL docs

---

en/docs/learn/extensions/managing-workflow-extension/configuring-workflows-for-tenants.md

[3.0.0] Fix issues in workflow extension doc

---

en/docs/administer/managing-users-and-roles/managing-user-roles.md
en/docs/administer/managing-users-and-roles/managing-user-stores/configure-primary-user-store/configuring-a-jdbc-user-store.md
en/docs/administer/managing-users-and-roles/managing-user-stores/configure-primary-user-store/configuring-the-primary-user-store.md
en/docs/install-and-setup/setup/setting-up-databases/changing-default-databases/changing-to-ibm-db2.md
en/docs/install-and-setup/setup/setting-up-databases/changing-default-databases/changing-to-mssql.md
en/docs/install-and-setup/setup/setting-up-databases/changing-default-databases/changing-to-mysql.md
en/docs/install-and-setup/setup/setting-up-databases/changing-default-databases/changing-to-oracle-rac.md
en/docs/install-and-setup/setup/setting-up-databases/changing-default-databases/changing-to-oracle.md
en/docs/install-and-setup/setup/setting-up-databases/changing-default-databases/changing-to-postgresql.md
en/docs/install-and-setup/setup/setting-up-databases/overview.md

Fix following issues
- https://github.com/wso2/docs-apim/issues/1311
- https://github.com/wso2/docs-apim/issues/2277
- https://github.com/wso2/docs-apim/issues/1327
- https://github.com/wso2/docs-apim/issues/1620

[3.1.0] Fix doc issues

---

en/docs/install-and-setup/setup/security/logins-and-passwords/maintaining-logins-and-passwords.md

Fix https://github.com/wso2/docs-apim/issues/2099

[3.2.0] Fix doc issue

---

en/docs/install-and-setup/setup/security/logins-and-passwords/maintaining-logins-and-passwords.md

Fix https://github.com/wso2/docs-apim/issues/2099

[3.1.0] Fix doc issue

---

en/docs/install-and-setup/setup/security/logins-and-passwords/maintaining-logins-and-passwords.md

Fix https://github.com/wso2/docs-apim/issues/2099

[4.0.0] Fix doc issue

---

en/docs/design/api-versioning/enabling-notifications.md
en/docs/install-and-setup/setup/security/user-account-management.md
en/docs/reference/config-catalog.md
en/tools/config-catalog-generator/data/configs.json
en/tools/config-catalog-generator/data/output_adapter.email.toml
en/tools/config-catalog-generator/dist/config-catalog.md

- Fixes https://github.com/wso2/docs-apim/issues/1843
- Add description for configuration elements in Password recovery Doc.
- Update configuration catalog for **Enable notifications** config element.
- Add configuration catalog for **Enable password recovery** Config element.
APIM 4.0.0

[4.0.0] Adding Signature property to configurations

---

en/docs/install-and-setup/setup/security/user-account-management.md
en/docs/learn/design-api/api-versioning/enabling-notifications.md
en/docs/reference/config-catalog.md
en/tools/config-catalog-generator/data/configs.json
en/tools/config-catalog-generator/data/output_adapter.email.toml
en/tools/config-catalog-generator/dist/config-catalog.md

- Fixes https://github.com/wso2/docs-apim/issues/1843
- Add description for configuration elements in Password recovery Doc.
- Update configuration catalog for **Enable notifications** config element.
- Add configuration catalog for **Enable password recovery** Config element.
APIM 3.2.0

[3.2.0] Adding Signature property to configurations

---

en/docs/reference/customize-product/product-apis/devportal-apis/devportal-v1/devportal-v1.yaml

Fixes https://github.com/wso2/docs-apim/issues/2507
APIM 4.0.0

[4.0.0] Fix REST API issues

---

en/docs/administer/managing-users-and-roles/managing-user-stores/configuring-secondary-user-stores.md
en/docs/learn/api-gateway/mutual-ssl-between-api-gateway-and-backend.md

Added both old and new userstore manager class names for issue https://github.com/wso2/docs-apim/issues/1343
Fix issue https://github.com/wso2/docs-apim/issues/2382

Added both old and new userstore manager class names for issue #1343

---

en/docs/administer/managing-users-and-roles/managing-user-stores/configuring-secondary-user-stores.md
en/docs/publish/api-gateway/mutual-ssl-between-api-gateway-and-backend.md

Fix issue https://github.com/wso2/docs-apim/issues/1343
Fix issue https://github.com/wso2/docs-apim/issues/2382

Fix issue #1343 and #2382

---

en/tools/config-catalog-generator/data/configs.json
en/tools/config-catalog-generator/data/indexing.toml
en/tools/config-catalog-generator/data/server.toml

fix https://github.com/wso2/docs-apim/issues/1821
https://github.com/wso2/docs-apim/issues/1893

Fix config catalog issues

---

en/tools/config-catalog-generator/data/configs.json
en/tools/config-catalog-generator/data/indexing.toml
en/tools/config-catalog-generator/data/server.toml

Fix https://github.com/wso2/docs-apim/issues/1821
Fix https://github.com/wso2/docs-apim/issues/1893

Fix config catalog issues related to registry indexing and server configs

---

en/docs/install-and-setup/upgrading-wso2-api-manager/upgrading-from-200-to-310.md
en/docs/install-and-setup/upgrading-wso2-api-manager/upgrading-from-210-to-310.md
en/docs/install-and-setup/upgrading-wso2-api-manager/upgrading-from-220-to-310.md
en/docs/install-and-setup/upgrading-wso2-api-manager/upgrading-from-250-to-310.md
en/docs/install-and-setup/upgrading-wso2-api-manager/upgrading-from-260-to-310.md
en/docs/install-and-setup/upgrading-wso2-api-manager/upgrading-from-300-to-310.md

Fixes for 
- https://github.com/wso2/docs-apim/issues/1898
- https://github.com/wso2/docs-apim/issues/1723
> Link to the PR for …

[310] Fix Migration related issues

---

en/docs/install-and-setup/upgrading-wso2-api-manager/upgrading-from-200-to-320.md
en/docs/install-and-setup/upgrading-wso2-api-manager/upgrading-from-210-to-320.md
en/docs/install-and-setup/upgrading-wso2-api-manager/upgrading-from-220-to-320.md
en/docs/install-and-setup/upgrading-wso2-api-manager/upgrading-from-250-to-320.md
en/docs/install-and-setup/upgrading-wso2-api-manager/upgrading-from-260-to-320.md
en/docs/install-and-setup/upgrading-wso2-api-manager/upgrading-from-300-to-320.md
en/docs/install-and-setup/upgrading-wso2-api-manager/upgrading-from-310-to-320.md

Fixes for 
- https://github.com/wso2/docs-apim/issues/1723 …

[Master] Fix Migration related issues

---

en/docs/install-and-setup/upgrading-wso2-api-manager/upgrading-from-200-to-320.md
en/docs/install-and-setup/upgrading-wso2-api-manager/upgrading-from-210-to-320.md
en/docs/install-and-setup/upgrading-wso2-api-manager/upgrading-from-220-to-320.md
en/docs/install-and-setup/upgrading-wso2-api-manager/upgrading-from-250-to-320.md
en/docs/install-and-setup/upgrading-wso2-api-manager/upgrading-from-260-to-320.md
en/docs/install-and-setup/upgrading-wso2-api-manager/upgrading-from-300-to-320.md
en/docs/install-and-setup/upgrading-wso2-api-manager/upgrading-from-310-to-320.md

Fixes for 
- https://github.com/wso2/docs-apim/issues/1723 …

[320] Fix Migration related issues

---

en/docs/develop/product-apis/publisher-apis/publisher-v1/publisher-v1.yaml

[3.1.0] Fix client-registration api version in publisher v1 doc

---

en/docs/develop/customizations/customizing-the-developer-portal/enabling-or-disabling-self-signup.md
en/docs/install-and-setup/setup/distributed-deployment/deploying-wso2-api-m-in-a-distributed-setup.md

> Update the User store type
> Correct the confusing statement in enabling self-signup
https://github.com/wso2/docs-apim/issues/2214
https://github.com/wso2/docs-apim/issues/2224

Update user store type and Correct the confusing statement

---

en/docs/install-and-setup/setup/distributed-deployment/deploying-wso2-api-m-in-a-distributed-setup.md
en/docs/reference/customize-product/customizations/customizing-the-developer-portal/enabling-or-disabling-self-signup.md

> Update the User store type
> Correct the confusing statement in enabling self-signup
https://github.com/wso2/docs-apim/issues/2214
https://github.com/wso2/docs-apim/issues/2224

Update user store type and Correct the confusing statement 

---

en/docs/learn/consume-api/customizations/customizing-the-developer-portal/enabling-or-disabling-self-signup.md

> Correct the conflicting information in enabling Self - signup
Issue : https://github.com/wso2/docs-apim/issues/2214

Correct the confusing statement in enabling self-signup

---

en/docs/develop/product-apis/publisher-apis/publisher-v1/publisher-v1.yaml

[3.1.0] Add sample curl for wsdl archive upload

---

en/docs/develop/product-apis/publisher-apis/publisher-v1/publisher-v1.yaml

[3.2.0] Add sample curl for wsdl archive upload

---

en/docs/learn/consume-api/discover-apis/search.md

Fixes https://github.com/wso2/docs-apim/issues/2282
APIM 3.2.0

 [3.2.0] Add API Category based search details 

---

en/docs/learn/consume-api/discover-apis/search.md

Fixes https://github.com/wso2/docs-apim/issues/2282
APIM 3.1.0

[3.1.0] Add API Category based search details

---

en/docs/consume/discover-apis/search.md

Fixes https://github.com/wso2/docs-apim/issues/2282
APIM 4.0.0

[4.0.0] Add API Category based search details 

---

en/docs/reference/customize-product/product-apis/publisher-apis/publisher-v1/publisher-v1.yaml

[4.0.0] Fix HTTP response status descriptions of /documents/validate endpoint

---

en/docs/develop/product-apis/publisher-apis/publisher-v1/publisher-v1.yaml

[3.0.0] Fix HTTP response status descriptions of /documents/validate endpoint

---

en/docs/reference/customize-product/product-apis/admin-apis/admin-v0.17/admin-v0.17.md
en/docs/reference/customize-product/product-apis/admin-apis/admin-v1/admin-v1.md
en/docs/reference/customize-product/product-apis/devportal-apis/devportal-v1/devportal-v1.md
en/docs/reference/customize-product/product-apis/gateway-apis/gateway-v1/gateway-v1.md
en/docs/reference/customize-product/product-apis/publisher-apis/publisher-v1/publisher-v1.md

[4.0.0] Fix broken REST API links

---

en/docs/reference/customize-product/product-apis/publisher-apis/publisher-v1/publisher-v1.yaml

[4.0.0] Update Rest API docs on wsdl file upload

---

en/docs/develop/customizations/adding-a-user-signup-workflow.md

- This PR fixes #2130
- Add a note providing steps that need to be performed when there are multiple tenants.

[3.2.0] Add required steps when enabling user signup workflow for multi tenants

---

en/docs/develop/product-apis/publisher-apis/publisher-v1/publisher-v1.yaml

[3.2.0] Fix HTTP response status descriptions of /documents/validate endpoint

---

en/docs/develop/product-apis/publisher-apis/publisher-v1/publisher-v1.yaml

Fixes https://github.com/wso2/docs-apim/issues/1536 …

[3.1.0] Fix HTTP response status descriptions of /documents/validate endpoint

---

en/docs/reference/config-catalog.md
en/docs/reference/configs.json

Fixes https://github.com/wso2/docs-apim/issues/1082 …

Remove duplicate enable_user_claims entry

---

en/docs/reference/customize-product/customizations/adding-a-user-signup-workflow.md

- This PR fixes #2130
- Add a note providing steps that need to be performed when there are multiple tenants.

[4.0.0] Add required steps when enabling user signup workflow for multi tenants

---

en/docs/consume/invoke-apis/invoke-apis-using-tools/invoke-an-api-using-the-integrated-api-console.md

Fixes: https://github.com/wso2/docs-apim/issues/2092
Change content with Swagger to OpenAPI specification.

Change referring swagger instead of OAS

---

en/docs/administer/logging-and-monitoring/logging/setting-up-logging.md

fix for https://github.com/wso2/docs-apim/issues/1752

Add per-tenant logs

---

en/docs/administer/logging-and-monitoring/logging/setting-up-logging.md

Add per tenant log

---

en/tools/config-catalog-generator/data/configs.json

Fixes https://github.com/wso2/docs-apim/issues/851 …

Changing store entries to devportal in config-catalog

---

en/docs/reference/config-catalog.md
en/tools/config-catalog-generator/data/configs.json

Fixes https://github.com/wso2/docs-apim/issues/851 …

Changing relevant store entries to devportal in config-catalog

---

en/tools/config-catalog-generator/data/configs.json

Fixes https://github.com/wso2/docs-apim/issues/851 …

Changing store entries to devportal in config catalog

---

en/tools/config-catalog-generator/data/configs.json

Fixes https://github.com/wso2/docs-apim/issues/851 …

Changing term Store to Devportal in config catalog

---

en/docs/install-and-setup/upgrading-wso2-api-manager/upgrading-from-200-to-300.md
en/docs/install-and-setup/upgrading-wso2-api-manager/upgrading-from-210-to-300.md
en/docs/install-and-setup/upgrading-wso2-api-manager/upgrading-from-220-to-300.md
en/docs/install-and-setup/upgrading-wso2-api-manager/upgrading-from-250-to-300.md
en/docs/install-and-setup/upgrading-wso2-api-manager/upgrading-from-260-to-300.md

[3.0.0] Fix trustore configuration

---

en/docs/install-and-setup/upgrading-wso2-api-manager/upgrading-from-200-to-310.md
en/docs/install-and-setup/upgrading-wso2-api-manager/upgrading-from-210-to-310.md
en/docs/install-and-setup/upgrading-wso2-api-manager/upgrading-from-220-to-310.md
en/docs/install-and-setup/upgrading-wso2-api-manager/upgrading-from-250-to-310.md
en/docs/install-and-setup/upgrading-wso2-api-manager/upgrading-from-260-to-310.md
en/docs/install-and-setup/upgrading-wso2-api-manager/upgrading-from-300-to-310.md

[3.1.0] Fix trustore configuration

---

en/docs/install-and-setup/setup/security/configuring-keystores/configuring-keystores-in-wso2-api-manager.md

fix for https://github.com/wso2/docs-apim/issues/1467

Add troubleshoot point

---

en/docs/develop/extending-api-manager/extending-gateway/writing-custom-handlers.md

Fixes: https://github.com/wso2/docs-apim/issues/2497 …

Improving writing custom handler docs.

---

en/docs/develop/customizations/customizing-the-developer-portal/advanced-customization.md
en/docs/install-and-setup/setup/security/logins-and-passwords/maintaining-logins-and-passwords.md

Fix https://github.com/wso2/docs-apim/issues/1839
Fix https://github.com/wso2/docs-apim/issues/1662

[3.2.0] Fix doc issues

---

en/docs/install-and-setup/setup/security/logins-and-passwords/maintaining-logins-and-passwords.md
en/docs/reference/customize-product/customizations/customizing-the-developer-portal/advanced-customization.md

Fix https://github.com/wso2/docs-apim/issues/1662
Fix https://github.com/wso2/docs-apim/issues/1839

[4.0.0] Fix doc issues

---

en/docs/develop/customizations/customizing-the-developer-portal/overriding-developer-portal-theme.md
en/docs/develop/customizations/customizing-the-developer-portal/styling-the-logo-and-header.md

[3.1.0] Update customizing dev portal docs

---

en/docs/reference/customize-product/customizations/customizing-the-developer-portal/overriding-developer-portal-theme.md
en/docs/reference/customize-product/customizations/customizing-the-developer-portal/styling-the-logo-and-header.md

[4.0.0] Update customizing dev portal docs

---

en/docs/learn/consume-api/customizations/customizing-the-developer-portal/styling-the-logo-and-header.md

[3.0.0] Update customizing dev portal docs

---

en/docs/develop/customizations/customizing-the-developer-portal/overriding-developer-portal-theme.md
en/docs/develop/customizations/customizing-the-developer-portal/styling-the-logo-and-header.md

[3.2.0] Update customizing dev portal docs

---

en/docs/develop/customizations/advanced-ui-customization.md
en/docs/develop/customizations/customizing-the-developer-portal/enable-or-disable-home-page.md
en/docs/develop/customizations/customizing-the-developer-portal/styling-api-details-info-section.md
en/docs/develop/customizations/customizing-the-developer-portal/styling-api-details-left-menu.md
en/docs/learn/consume-api/discover-apis/search.md
en/docs/learn/design-api/lifecycle-management/customize-api-life-cycle.md
en/mkdocs.yml

Fixing Default search in publisher and devportal is not the API name search

---

en/docs/consume/discover-apis/search.md
en/docs/design/lifecycle-management/customize-api-life-cycle.md
en/docs/reference/customize-product/customizations/advanced-ui-customization.md
en/docs/reference/customize-product/customizations/customizing-the-developer-portal/enable-or-disable-home-page.md
en/docs/reference/customize-product/customizations/customizing-the-developer-portal/styling-api-details-info-section.md
en/docs/reference/customize-product/customizations/customizing-the-developer-portal/styling-api-details-left-menu.md
en/mkdocs.yml

Fixing: https://github.com/wso2/docs-apim/issues/2288

Fixing - Default search in publisher and devportal is not the API name search

---

en/docs/learn/analytics/viewing-api-statistics/application-analytics-dashboard.md

Improve the earlier fix(#2248) done for 3.2.0 for issue #1935 for master branch by correcting the analytics role name.

[3.2.0][Fix for issue 1935]Correct the analytics role name

---

en/docs/observe/api-manager-analytics/viewing-api-statistics/application-analytics-dashboard.md

Fixes issue #1935 for master branch

[Master][Fix for 1935] Content corrected in Application analytics page

---

en/docs/learn/analytics/analyzing-apim-statistics-with-batch-analytics/viewing-api-statistics.md

Fixes issue #1935 for 3.1.0 branch

[3.1.0][Fix for issue 1935]Content corrected in Developer Portal Statistics Dashboard

---

en/docs/learn/analytics/analyzing-apim-statistics-with-batch-analytics/viewing-api-statistics.md

Fixes issue #1935 for 3.0.0 branch

[3.0.0][Fix for issue 1935]Content corrected in Developer Portal Statistics Dashboard

---

en/docs/reference/config-catalog.md
en/tools/config-catalog-generator/dist/config-catalog.md
en/tools/config-catalog-generator/templates/index.njk

Fixes https://github.com/wso2/docs-apim/issues/1380
Affected Versions
APIM 4.0.0

[4.0.0] Add descriptions about the config model 

---

en/docs/reference/config-catalog.md
en/tools/config-catalog-generator/dist/config-catalog.md
en/tools/config-catalog-generator/templates/index.njk

Fixes https://github.com/wso2/docs-apim/issues/1380
Affected Versions
APIM 3.1.0

[3.1.0]Add descriptions about the config model

---

en/docs/reference/config-catalog.md
en/tools/config-catalog-generator/dist/config-catalog.md
en/tools/config-catalog-generator/templates/index.njk

Fixes https://github.com/wso2/docs-apim/issues/1380
Affected Versions
APIM 3.0.0

[3.0.0] Add descriptions about the config model 

---

en/tools/config-catalog-generator/data/apim.jwt.issuer.claim_mapping.toml
en/tools/config-catalog-generator/data/apim.jwt.issuer.jwks.toml
en/tools/config-catalog-generator/data/apim.jwt.issuer.toml
en/tools/config-catalog-generator/data/configs.json

fix https://github.com/wso2/docs-apim/issues/1315

Add apim.jwt issuer and claim_configurations configs

---

en/tools/config-catalog-generator/data/apim.jwt.issuer.claim_mapping.toml
en/tools/config-catalog-generator/data/apim.jwt.issuer.jwks.toml
en/tools/config-catalog-generator/data/apim.jwt.issuer.toml
en/tools/config-catalog-generator/data/configs.json

Add apim.jwt issuer configs

---

en/docs/develop/product-apis/admin-apis/admin-v0.15/admin-v0.15.md
en/docs/develop/product-apis/devportal-apis/devportal-v0.15/devportal-v0.15.md
en/docs/develop/product-apis/devportal-apis/devportal-v1/devportal-v1.md
en/docs/develop/product-apis/publisher-apis/publisher-v0.15/publisher-v0.15.md
en/docs/develop/product-apis/publisher-apis/publisher-v1/publisher-v1.md

[3.0.0] Add info on REST API token generation

---

en/docs/install-and-setup/setup/distributed-deployment/deploying-wso2-api-m-in-a-distributed-setup.md

Resolves: https://github.com/wso2/docs-apim/issues/1858 …

[3.1.0] Improving distributed deployment document.

---

en/docs/install-and-setup/setup/distributed-deployment/deploying-wso2-api-m-in-a-distributed-setup.md

Resolves: https://github.com/wso2/docs-apim/issues/1858 …

[3.2.0] Improving distributed deployment doc.

---

en/docs/install-and-setup/setup/distributed-deployment/deploying-wso2-api-m-in-a-distributed-setup.md

Resolves: https://github.com/wso2/docs-apim/issues/1858 …

[master] Improving distributed document.

---

en/docs/install-and-setup/deploying-wso2-api-manager/distributed-deployment/deploying-wso2-api-m-in-a-distributed-setup.md

Resolves: https://github.com/wso2/docs-apim/issues/1858 …

[3.0.0] Improving distributed docs.

---

en/mkdocs.yml

Resolves: https://github.com/wso2/docs-apim/issues/2557 …

Fixing broken links for extending API gateway.

---

en/docs/reference/guides/accessing-api-manager-by-multiple-devices-simultaneously.md
en/docs/reference/guides/directory-structure-of-wso2-products.md

- This PR fixes #909
- Fix formatting issues Guide section in Reference

[3.1.0] Fixing formatting in Guide section in Reference

---

en/docs/reference/guides/accessing-api-manager-by-multiple-devices-simultaneously.md
en/docs/reference/guides/directory-structure-of-wso2-products.md

- This PR fixes #909
- Fix formatting issues Guide section in Reference

[3.2.0] Fixing formatting in Guide section in Reference

---

en/docs/reference/guides/accessing-api-manager-by-multiple-devices-simultaneously.md
en/docs/reference/guides/directory-structure-of-wso2-products.md

- This PR fixes #909
- Fix formatting issues Guide section in Reference

[4.0.0] Fixing formatting in Guide section in Reference

---

en/docs/learn/design-api/endpoints/endpoint-types.md

fix https://github.com/wso2/docs-apim/issues/1936

---

en/docs/develop/product-apis/devportal-apis/devportal-v1/devportal-v1.yaml
en/docs/develop/product-apis/publisher-apis/publisher-v1/publisher-v1.yaml

[3.0.0] Update API store to API Developer Portal in REST API docs

---

en/docs/observe/api-manager-analytics/configuring-apim-analytics.md
en/docs/reference/analytics-rest-api.md
en/mkdocs.yml

This PR fixes following issues:
#2273
#2015

[Master]Fix doc issues 2273 and 2015

---

en/docs/develop/analytics-rest-api.md
en/docs/learn/analytics/configuring-apim-analytics.md
en/mkdocs.yml

This PR fixes following issues:
- #2273
- #2015

[3.2.0]Fix doc issues 2273 and 2015

---

en/docs/develop/product-apis/devportal-apis/devportal-v1/devportal-v1.yaml
en/docs/develop/product-apis/publisher-apis/publisher-v1/publisher-v1.yaml

[3.1.0] Update API store to API Developer Portal in REST API docs

---

en/docs/learn/analytics/configuring-apim-analytics.md

This PR fixes following issues:
- #2273
- Properly render a misconfigured info box

[3.0.0]Add minIdle property for sample Analytics related Db configs

---

en/docs/learn/analytics/configuring-apim-analytics.md

This PR fixes following issues:
- #2273

[3.1.0]Add minIdle property for sample Analytics related Db configs

---

en/docs/develop/product-apis/devportal-apis/devportal-v1/devportal-v1.yaml
en/docs/develop/product-apis/publisher-apis/publisher-v1/publisher-v1.yaml

[3.2.0] Update API store to API Developer Portal in REST API docs

---

en/docs/reference/customize-product/product-apis/devportal-apis/devportal-v1/devportal-v1.yaml
en/docs/reference/customize-product/product-apis/publisher-apis/publisher-v1/publisher-v1.yaml

[4.0.0] Update API store to API Developer Portal in REST API docs

---

en/docs/develop/product-apis/getting-started/guide-admin-v0.15.md
en/docs/develop/product-apis/getting-started/guide-devportal-v0.15.md
en/docs/develop/product-apis/getting-started/guide-devportal-v1.md
en/docs/develop/product-apis/getting-started/guide-publisher-v0.15.md
en/docs/develop/product-apis/getting-started/guide-publisher-v1.md

Fixes https://github.com/wso2/docs-apim/issues/1987
APIM 3.0.0

[3.0.0] Fix REST API issues

---

en/docs/reference/config-catalog.md
en/tools/config-catalog-generator/dist/config-catalog.md
en/tools/config-catalog-generator/templates/index.njk

Fixes https://github.com/wso2/docs-apim/issues/1380
Affected Versions
APIM 3.2.0

 [3.2.0] Add descriptions about the config model 

---

en/docs/develop/product-apis/getting-started/guide-admin-v0.15.md
en/docs/develop/product-apis/getting-started/guide-devportal-v0.15.md
en/docs/develop/product-apis/getting-started/guide-devportal-v1.md
en/docs/develop/product-apis/getting-started/guide-publisher-v0.15.md
en/docs/develop/product-apis/getting-started/guide-publisher-v1.md

Fixes https://github.com/wso2/docs-apim/issues/1987
APIM 3.0.0

[3.0.0] Add Scope Overview in REST API Docs

---

en/docs/learn/design-api/endpoints/endpoint-security/oauth-2.0.md

Fix https://github.com/wso2/docs-apim/issues/2175

Fix formatting

---

en/docs/install-and-setup/setup/single-node/configuring-an-active-active-deployment.md

Fixes https://github.com/wso2/docs-apim/issues/1556

Fix issue #1556

---

en/docs/reference/customize-product/customizations/customizing-login-pages-for-dev-portal-and-publisher.md

- This PR fixes #1338
- Adds changes to the section "Customizing different sections of identity server related JSP pages"

[4.0.0] Improving Customizing login pages for dev portal and publisher doc

---

en/docs/develop/customizations/customizing-login-pages-for-dev-portal-and-publisher.md

- This PR fixes #1338
- Adds changes to the section "Customizing different sections of identity server related JSP pages"

[3.2.0] Improving Customizing login pages for dev portal and publisher doc

---

en/docs/design/rate-limiting/graphql-api/overview-query-limits-for-graphql.md
en/docs/design/rate-limiting/graphql-api/query-complexity-limitation.md
en/docs/design/rate-limiting/graphql-api/query-depth-limitation.md

Fixing the capitalization and grammar issues in pages related to the GraphQL rate limiting
Fixes https://github.com/wso2/docs-apim/issues/2483 for master branch
**/rate-limiting/graphql-api/overview-query-limits-for-graphql/ page**
**/rate-limiting/graphql-api/query-complexity-limitation/  page**
**/rate-limiting/graphql-api/query-depth-limitation/  page**

[Docs] [Master] Fixes #2483 (Update graphQL rate limiting pages) 

---

en/docs/publish/api-gateway/mutual-ssl-between-api-gateway-and-backend.md

https://apim.docs.wso2.com/en/next/publish/api-gateway/mutual-ssl-between-api-gateway-and-backend/#mutual-ssl-between-api-gateway-and-backend
The examples attached to step 4 and step 5 have some inconsistencies. This PR will fix them.
Fixes https://github.com/wso2/docs-apim/issues/1336

[Docs] [Master] Remove inconsistency in examples when configuring MutualSSL

---

en/docs/reference/customize-product/customizations/customizing-the-developer-portal/overriding-developer-portal-theme.md
en/docs/reference/customize-product/customizations/overriding-the-publisher-portal-theme.md
en/mkdocs.yml

Fixing https://github.com/wso2/docs-apim/issues/2443
Fixing https://github.com/wso2/docs-apim/issues/1631

Fixing theme related issues

---

en/docs/install-and-setup/install/installing-the-product/installing-the-binary/installing-as-a-windows-service.md

https://github.com/wso2/docs-apim/issues/1188

Fix doc issue in windows as service

---

en/docs/getting-started/quick-start-guide.md
en/docs/install-and-setup/install/installing-the-product/installing-the-binary/installing-on-linux-or-os-x.md
en/docs/install-and-setup/install/installing-the-product/installing-the-binary/installing-on-solaris.md
en/docs/install-and-setup/install/installing-the-product/installing-the-binary/installing-on-windows.md
en/docs/install-and-setup/setup/sso/okta-as-an-external-idp-using-oidc.md
en/docs/install-and-setup/setup/sso/okta-as-an-external-idp-using-saml.md

Fixes: https://github.com/wso2/docs-apim/issues/819 …

[3.2.0] Adding downloading version to the documentation to avoid confusion.

---

en/docs/get-started/quick-start-guide/quick-start-guide.md
en/docs/install-and-setup/install/installing-the-product/installing-the-binary/installing-on-linux-or-os-x.md
en/docs/install-and-setup/install/installing-the-product/installing-the-binary/installing-on-solaris.md
en/docs/install-and-setup/install/installing-the-product/installing-the-binary/installing-on-windows.md
en/docs/install-and-setup/setup/sso/okta-as-an-external-idp-using-oidc.md
en/docs/install-and-setup/setup/sso/okta-as-an-external-idp-using-saml.md

Fixes: https://github.com/wso2/docs-apim/issues/819 …

[master] Specifying the downloading version of the documentation.

---

en/docs/getting-started/quick-start-guide.md
en/docs/install-and-setup/deploying-wso2-api-manager/single-node/deploying-api-manager-using-single-node-instances.md
en/docs/install-and-setup/installation-guide/installing-the-product/installing-the-binary/installing-on-linux-or-os-x.md
en/docs/install-and-setup/installation-guide/installing-the-product/installing-the-binary/installing-on-solaris.md
en/docs/install-and-setup/installation-guide/installing-the-product/installing-the-binary/installing-on-windows.md

Fixes: https://github.com/wso2/docs-apim/issues/819 …

[3.0.0] Changing 3.0.0 product download links to previous releases.

---

en/docs/develop/extending-api-manager/saml2-sso/configuring-identity-server-as-idp-for-sso.md
en/docs/getting-started/quick-start-guide.md
en/docs/install-and-setup/install/installing-the-product/installing-the-binary/installing-on-linux-or-os-x.md
en/docs/install-and-setup/install/installing-the-product/installing-the-binary/installing-on-solaris.md
en/docs/install-and-setup/install/installing-the-product/installing-the-binary/installing-on-windows.md
en/docs/install-and-setup/setup/distributed-deployment/deploying-wso2-api-m-in-a-distributed-setup.md
en/docs/install-and-setup/setup/single-node/deploying-api-manager-using-single-node-instances.md
en/docs/install-and-setup/setup/sso/okta-as-an-external-idp-using-oidc.md
en/docs/install-and-setup/setup/sso/okta-as-an-external-idp-using-saml.md
en/docs/learn/api-security/api-authentication/advanced-topics/federating-oauth-applications.md
en/docs/learn/design-api/publish-api/publish-to-multiple-external-api-stores.md

Fixes: https://github.com/wso2/docs-apim/issues/819 …

[3.1.0] Upgrading download version and links for 3.1.0

---

en/docs/learn/api-security/threat-protection/bot-detection.md

improved the description of the doc
fix for https://github.com/wso2/docs-apim/issues/839

improve bot ditection page 

---

en/docs/design/api-security/oauth2/token-persistence.md

This PR incorporates the fix done with https://github.com/wso2/docs-apim/pull/2116 to the master branch.

fix https://github.com/wso2/docs-apim/issues/1091

---

en/docs/install-and-setup/setup/reference/default-product-ports.md

Fixes https://github.com/wso2/docs-apim/issues/2241
Fixes https://github.com/wso2/docs-apim/issues/2236

Fix issues #2241 and #2236

---

en/tools/config-catalog-generator/data/configs.json

Fixes: https://github.com/wso2/docs-apim/issues/2779
Fixes: https://github.com/wso2/docs-apim/issues/686 …

[3.0.0]  Fixes missing configs in the catalog

---

en/tools/config-catalog-generator/data/configs.json

Fixes: https://github.com/wso2/docs-apim/issues/2779
Fixes: https://github.com/wso2/docs-apim/issues/686 …

[3.1.0] Adding missing configs to the catalog

---

en/tools/config-catalog-generator/data/configs.json

Fixes: https://github.com/wso2/docs-apim/issues/2779
Fixes: https://github.com/wso2/docs-apim/issues/686 …

[3.2.0] Adding missing configs to the catalog

---

en/tools/config-catalog-generator/data/configs.json

Fixes: https://github.com/wso2/docs-apim/issues/2779
Fixes: https://github.com/wso2/docs-apim/issues/686 …

[master] Adding missing configs to the catalog

---

en/docs/learn/api-monetization/monetizing-an-api.md

> Describe the problems, issues, or needs driving this feature/fix and include links to related issues in the following format: Resolves https://github.com/wso2/docs-apim/issues/1518
> Link(s) to product documentation that addresses the changes of this PR. If no doc impact, enter …

[3.1.0] Add note on excluding sandbox api call from getting billed

---

en/docs/learn/api-monetization/monetizing-an-api.md

> Describe the problems, issues, or needs driving this feature/fix and include links to related issues in the following format: Resolves #1518
> Link(s) to product documentation that addresses the changes of this PR. If no doc impact, enter “N/A” plus brief explanation of why there’s …

[3.2.0] Add note on excluding sandbox api call from getting billed

---

en/docs/learn/api-monetization/monetizing-an-api.md

> Describe the problems, issues, or needs driving this feature/fix and include links to related issues in the following format: Resolves #1518
> Link(s) to product documentation that addresses the changes of this PR. If no doc impact, enter “N/A” plus brief explanation of why there’s …

[3.0.0] Add note on excluding sandbox api call from getting billed

---

en/docs/design/api-monetization/monetizing-an-api.md

> Describe the problems, issues, or needs driving this feature/fix and include links to related issues in the following format: Resolves #1518
> Link(s) to product documentation that addresses the changes of this PR. If no doc impact, enter “N/A” plus brief explanation of why there’s …

[4.0.0] Add note on excluding sandbox api call from getting billed

---

en/docs/learn/design-api/endpoints/certificates.md

Fix https://github.com/wso2/docs-apim/issues/1932

update endpoint certificates on custom ssl profiles

---

en/docs/learn/api-security/api-authentication/secure-apis-using-mutual-ssl.md

Fixes https://github.com/wso2/docs-apim/issues/1777
APIM 3.1.0

[3.1.0] Fix issue #1777

---

en/docs/design/endpoints/certificates.md

fix https://github.com/wso2/docs-apim/issues/1932

update endpoint certificates on custom ssl profiles 

---

en/docs/install-and-setup/setup/distributed-deployment/configure-apim-analytics/active-active.md
en/docs/install-and-setup/setup/distributed-deployment/configure-apim-analytics/active-passive.md
en/docs/install-and-setup/upgrading-wso2-api-manager/upgrading-from-250-to-320.md
en/docs/install-and-setup/upgrading-wso2-api-manager/upgrading-from-260-to-320.md
en/docs/install-and-setup/upgrading-wso2-api-manager/upgrading-from-300-to-320.md
en/docs/install-and-setup/upgrading-wso2-api-manager/upgrading-from-310-to-320.md
en/docs/learn/analytics/configuring-apim-analytics.md

This PR fixes the following issues in 3.20 branch
- #1460
- #1461
- #2287

[3.2.0] Fixes for 1460, 1461, 2287 issues

---

en/docs/install-and-setup/setup/distributed-deployment/configure-apim-analytics/active-active.md
en/docs/install-and-setup/setup/distributed-deployment/configure-apim-analytics/active-passive.md
en/docs/install-and-setup/upgrading-wso2-api-manager/upgrading-from-250-to-320.md
en/docs/install-and-setup/upgrading-wso2-api-manager/upgrading-from-260-to-320.md
en/docs/install-and-setup/upgrading-wso2-api-manager/upgrading-from-300-to-320.md
en/docs/install-and-setup/upgrading-wso2-api-manager/upgrading-from-310-to-320.md
en/docs/observe/api-manager-analytics/configuring-apim-analytics.md

This PR fixes the following issues in 3.20 branch
- #1460
- #1461
- #2287

[Master] Fixes for 1460, 1461, 2287 issues

---

en/docs/install-and-setup/setup/distributed-deployment/configure-apim-analytics/active-active.md
en/docs/install-and-setup/setup/distributed-deployment/configure-apim-analytics/active-passive.md
en/docs/install-and-setup/upgrading-wso2-api-manager/upgrading-from-250-to-310.md
en/docs/install-and-setup/upgrading-wso2-api-manager/upgrading-from-260-to-310.md
en/docs/install-and-setup/upgrading-wso2-api-manager/upgrading-from-300-to-310.md
en/docs/learn/analytics/configuring-apim-analytics.md

This PR fixes the following issues in 3.1.0 branch
- #1460
- #1461
- #2287

[3.1.0] Fixes for 1460, 1461, 2287 issues

---

en/docs/install-and-setup/deploying-wso2-api-manager/configure-apim-analytics/configure-worker/active-active.md
en/docs/install-and-setup/deploying-wso2-api-manager/configure-apim-analytics/configure-worker/active-passive.md
en/docs/install-and-setup/upgrading-wso2-api-manager/upgrading-from-250-to-300.md
en/docs/install-and-setup/upgrading-wso2-api-manager/upgrading-from-260-to-300.md
en/docs/learn/analytics/configuring-apim-analytics.md

This PR fixes the following issues in 3.0.0 branch
- #1460
- #1461
- #2287

[3.0.0] Fixes for 1460, 1461, 2287 issues 

---

en/docs/publish/publish-to-multiple-external-api-stores.md

Fixes: https://github.com/wso2/docs-apim/issues/2182
To add code sample for tenant based configuration for external portals when there is no super tenant participation. 
Add separate code sample to demonstrate how will be the external-api-stores.xml file after making changes as Tip that is already showing three Developer Portals' deployment.

Add code sample for tenant based configuration for external portals

---

en/docs/learn/design-api/publish-api/publish-to-multiple-external-api-stores.md

Fixes: https://github.com/wso2/docs-apim/issues/2182
To add code sample for tenant based configuration for external portals when there is no super tenant participation.
Add separate code sample to demonstrate how will be the external-api-stores.xml file after making changes as Tip that is already showing three Developer Portals' deployment.

[3.2.0]Add code sample for tenant based configuration for external portals

---

en/docs/install-and-setup/deploying-wso2-api-manager/distributed-deployment/deploying-wso2-api-m-in-a-distributed-setup.md

Fix https://github.com/wso2/docs-apim/issues/1158

Fix doc issue

---

en/docs/learn/design-api/publish-api/publish-to-multiple-external-api-stores.md

Fixes: https://github.com/wso2/docs-apim/issues/2182
To add code sample for tenant based configuration for external portals when there is no super tenant participation.
Add separate code sample to demonstrate how will be the external-api-stores.xml file after making changes as Tip that is already showing three Developer Portals' deployment.

[3.1.0]Add code sample for tenant based configuration for external portals

---

en/docs/learn/design-api/publish-api/publish-to-multiple-external-api-stores.md

Fixes: https://github.com/wso2/docs-apim/issues/2182
To add code sample for tenant based configuration for external portals when there is no super tenant participation.
Add separate code sample to demonstrate how will be the external-api-stores.xml file after making changes as Tip that is already showing three Developer Portals' deployment.

[3.0.0]Add code sample for tenant based configuration for external portals

---

en/docs/reference/vendor-extensions-catalog.md

Removing unwanted  !!!example keywords in the newly added vendor-extensions file

[Docs][3.2.0] Remove unwanted example words

---

en/docs/learn/api-security/oauth2/grant-types/client-credentials-grant.md

Fix https://github.com/wso2/docs-apim/issues/2828
> Link(s) to product documentation that addresses the changes of this PR. If …

Fix https://github.com/wso2/docs-apim/issues/2828

---

en/docs/learn/design-api/create-api/adding-custom-properties-to-apis.md

Fix WUM doc link

---

en/tools/config-catalog-generator/data/carbon_health_check.toml
en/tools/config-catalog-generator/data/configs.json
en/tools/config-catalog-generator/data/custom_health_checker.toml
en/tools/config-catalog-generator/data/data_source_health_checker.toml
en/tools/config-catalog-generator/data/data_source_health_checker_properties.toml
en/tools/config-catalog-generator/data/governance.toml
en/tools/config-catalog-generator/data/oauth.toml
en/tools/config-catalog-generator/data/oauth_grant_type.toml
en/tools/config-catalog-generator/data/oauth_openid_connect.toml
en/tools/config-catalog-generator/data/oauth_token_cleanup.toml
en/tools/config-catalog-generator/data/oauth_token_validation.toml
en/tools/config-catalog-generator/data/qpid-heartbeat.toml
en/tools/config-catalog-generator/data/session_data_persistence.toml
en/tools/config-catalog-generator/data/super_tenant_health_checker.toml
en/tools/config-catalog-generator/data/super_tenant_health_checker_properties.toml
en/tools/config-catalog-generator/data/token_persistence.toml

fix #1833
Add configuration guide on following config files.
governance.xml.j2
qpid-config.xml.j2
identity.xml.j2

update config catalog

---

en/mkdocs.yml

Fixes https://github.com/wso2/docs-apim/issues/2838
3.0.0

[3.0.0] Add authorization manager doc to mkdocs

---

en/mkdocs.yml

Fixes https://github.com/wso2/docs-apim/issues/2838
3.1.0

[3.1.0] Add authorization manager doc to mkdocs

---

en/docs/learn/api-security/oauth2/token-persistence.md
en/docs/learn/api-security/threat-protection/bot-detection.md

backport fix https://github.com/wso2/docs-apim/issues/1091

fix token persistance doc

---

en/docs/troubleshooting/error-handling.md

Error handle xml file name correction. …

Error handle xml file name correction.

---

en/docs/learn/analytics/configuring-apim-analytics.md

This PR updates 'Adding CA-signed certificates to keystores' link in analytics docs.
Related issue: #1832

[3.1.0] Update links in analytics

---

en/docs/learn/rate-limiting/adding-new-throttling-policies.md

Fixes https://github.com/wso2/docs-apim/issues/1930
APIM 3.2.0

[3.2.0] Fixes issue #1930

---

en/docs/design/rate-limiting/adding-new-throttling-policies.md

Fixes https://github.com/wso2/docs-apim/issues/1930
APIM 4.0.0

[4.0.0] Fixes issue #1930

---

en/docs/learn/analytics/configuring-apim-analytics.md

This PR updates 'Adding CA-signed certificates to keystores' link in analytics docs.
Related issue: https://github.com/wso2/docs-apim/issues/1832

[3.0.0] Update links in analytics

---

en/docs/learn/rate-limiting/adding-new-throttling-policies.md

Fixes https://github.com/wso2/docs-apim/issues/1930
APIM 3.1.0

[3.1.0] Fixes issue #1930

---

en/docs/develop/extending-api-manager/extending-key-management/extending-scope-validation.md
en/docs/install-and-setup/setup/deployment-best-practices/tuning-performance.md

PR-sync for https://github.com/wso2/docs-apim/pull/1167/

[3.2.0] Fix config typos in performance tuning docs

---

en/docs/install-and-setup/setup/deployment-best-practices/tuning-performance.md
en/docs/reference/customize-product/extending-api-manager/extending-key-management/extending-scope-validation.md

[master] Fix config typos in performance tuning docs

---

en/mkdocs.yml

Format the yaml file to remove additional quotation marks and fix some paths.

Format yaml file

---

en/docs/reference/mediators/loopback-mediator.md
en/docs/reference/mediators/oauth-mediator.md
en/docs/reference/mediators/property-group-mediator.md
en/docs/reference/mediators/property-mediator.md
en/docs/reference/mediators/property-reference/accessing-properties-with-xpath.md
en/docs/reference/mediators/property-reference/axis2-properties.md
en/docs/reference/mediators/property-reference/generic-Properties.md
en/docs/reference/mediators/property-reference/http-transport-properties.md
en/docs/reference/mediators/property-reference/message-context-properties.md
en/docs/reference/mediators/property-reference/soap-headers.md
en/docs/reference/mediators/script-mediator.md
en/docs/reference/mediators/sequence-mediator.md
en/docs/reference/mediators/switch-mediator.md
en/docs/reference/mediators/transaction-mediator.md
en/docs/reference/mediators/validate-mediator.md

Fixing broken links (Warnings) - Set 2

---

en/mkdocs.yml

Update the navigator with links to SI Installation documentation

---

en/mkdocs.yml

Correct broken links in the navigator

---

en/docs/integrate/examples/json_examples/json-examples.md
en/docs/reference/mediators/enrich-mediator.md
en/docs/reference/mediators/payloadfactory-mediator.md
en/docs/reference/mediators/property-mediator.md

Merging feature docs from EI-master to APIM-master.

json eval feature docs

---

en/docs/reference/mediators/property-mediator.md

Fixing image that was broken from https://github.com/wso2/docs-apim/pull/2921/files

correcting broken image 

---

en/docs/install-and-setup/setup/si-setup/creating-business-rules-templates.md

Correct broken links in the Business Rules Templates guide

---

en/docs/learn/rate-limiting/adding-new-throttling-policies.md

Fixes https://github.com/wso2/docs-apim/issues/1930
APIM 3.0.0

[3.0.0] Fixes issue #1930

---

en/docs/reference/product-apis/publisher-apis/publisher-v1/publisher-v1.yaml

Adding REST API change for API Product

Adding REST API change for API Product

---

en/docs/learn/consume-api/customizations/customizing-the-developer-portal/advanced-customization.md
en/docs/learn/design-api/advanced-topics/enable-publisher-access-control-in-api-publisher-portal.md

This PR includes changes introduced by,
https://github.com/wso2/docs-apim/pull/1085
https://github.com/wso2/docs-apim/pull/1136
https://github.com/wso2/docs-apim/pull/1458
Fixes https://github.com/wso2/docs-apim/issues/1132

[3.0.0] PR-Sync #1085 and #1136

---

en/docs/reference/synapse-properties/endpoint-properties.md

Fixes https://github.com/wso2/docs-ei/issues/2691

Add OAuth Properties section for HTTP endpoints

---

en/docs/publish/api-microgateway/get-started-with-kubernetes-for-microgateway.md
en/docs/publish/api-microgateway/quick-start-with-kubernetes.md
en/mkdocs.yml

fix https://github.com/wso2/docs-apim/issues/2907

Add Microgateway K8s QSG

---

en/docs/develop/product-apis/admin-apis/admin-v0.16/admin-v0.16.yaml

Adding the missing examples and configuration sample in the set of REST API Resources in Admin v0.16 REST API.
Fixes https://github.com/wso2/docs-apim/issues/2924 for 3.1.0 doc space. 
**POST /throttling/policies/application**
**PUT /throttling/policies/application/{policyId}**
**POST /throttling/blacklist**
**POST /labels**
**POST /api-categories**
**GET /applications**
**POST /throttling/policies/subscription**

[3.1.0] Add requested configs in Admin v0.16 REST API page

---

en/docs/develop/product-apis/admin-apis/admin-v0.17/admin-v0.17.yaml
en/docs/develop/product-apis/admin-apis/admin-v1/admin-v1.yaml

Adding the missing examples and configuration sample in the set of REST API Resources in Admin v0.16 REST API.
Fixes https://github.com/wso2/docs-apim/issues/2924 for 3.1.0 doc space. 
**POST /throttling/policies/application**
**PUT /throttling/policies/application/{policyId}**
**POST /throttling/blacklist**
**POST /labels**
**POST /api-categories**
**GET /applications**
**POST /throttling/policies/subscription**
https://github.com/wso2/docs-apim/pull/2951

[3.2.0] Add requested configs in Admin v0.17 and Admin v1 REST API pages

---

en/docs/integrate/develop/creating-artifacts/creating-endpoints.md
en/docs/integrate/develop/creating-artifacts/creating-scheduled-task.md
en/docs/integrate/examples/jms_examples/consume-produce-jms.md
en/docs/integrate/examples/jms_examples/consuming-jms.md
en/docs/integrate/examples/jms_examples/producing-jms.md
en/docs/integrate/integration-use-case/connectors.md
en/docs/observe/mi-observe/mi-observability-overview.md
en/docs/observe/mi-observe/snmp_monitoring.md
en/docs/reference/synapse-properties/scheduled-task-properties.md
en/docs/reference/synapse-properties/transport-parameters/jms-transport-properties.md
en/mkdocs.yml

Fixing broken links (Warnings) - Set 6

Fixing broken links (Warnings) - Set 7

---

en/docs/install-and-setup/setup/api-controller/advanced-topics/configuring-environment-specific-parameters.md

Changing the *Configuring Environment Specific Parameters* page according to the latest introduction of the deployment directory approach to defining deployment-specific configurations.
Fixes https://github.com/wso2/product-apim-tooling/issues/554

[Docs] [APICTL] Add apictl gen command details and deployment repo introduction

---

en/docs/install-and-setup/setup/distributed-deployment/configuring-wso2-identity-server-as-a-key-manager.md

fixing download link for IS

---

en/docs/integrate/develop/create-data-services-configs.md
en/docs/integrate/develop/create-docker-project.md
en/docs/integrate/develop/create-kubernetes-project.md
en/docs/integrate/develop/creating-artifacts/creating-smooks-artifacts.md
en/docs/integrate/develop/creating-unit-test-suite.md
en/docs/integrate/develop/debugging-mediation.md
en/docs/integrate/develop/deploy-artifacts.md
en/docs/integrate/develop/endpoint-trace-logs.md
en/docs/integrate/develop/export_project.md
en/docs/integrate/develop/exporting-artifacts.md
en/docs/integrate/develop/generate-docker-image.md
en/docs/integrate/develop/hot-deployment.md
en/docs/integrate/develop/injecting-parameters.md
en/docs/integrate/develop/installing-wso2-integration-studio.md
en/docs/integrate/develop/integration-development-kickstart.md
en/docs/integrate/develop/intro-integration-development.md
en/docs/integrate/develop/troubleshooting-wso2-integration-studio.md
en/docs/integrate/develop/using-embedded-micro-integrator.md
en/docs/integrate/develop/using-remote-micro-integrator.md
en/docs/integrate/develop/working-with-wso2-integration-studio.md
en/docs/integrate/develop/wso2-integration-studio.md

Adding basepath to link url + minor fixes (set 2)
- integrate/develop section

Adding basepath to link url + minor fixes (set 2)

---

en/docs/learn/api-controller/advanced-topics/creating-custom-users-to-perform-api-controller-operations.md

Fixes: https://github.com/wso2/docs-apim/pull/994#discussion_r554809914
Changing the title **Using API-M management console** to **Using API-M Admin Portal** in creating-custom-users-to-perform-api-controller-operations.md

[3.1.0] Correcting the title in creating-custom-users-to-perform-api-controller-operations.md 

---

en/docs/learn/api-controller/advanced-topics/creating-custom-users-to-perform-api-controller-operations.md

Fixes: https://github.com/wso2/docs-apim/pull/994#discussion_r554809914
Changing the title **Using API-M management console** to **Using API-M Admin Portal** in creating-custom-users-to-perform-api-controller-operations.md

[3.0.0] Correcting the title in creating-custom-users-to-perform-api-controller-operations.md

---

en/docs/integrate/integration-use-case/asynchronous-message-overview.md
en/docs/integrate/integration-use-case/connectors.md
en/docs/integrate/integration-use-case/data-integration-overview.md
en/docs/integrate/integration-use-case/file-processing-overview.md
en/docs/integrate/integration-use-case/gateway-overview.md
en/docs/integrate/integration-use-case/message-routing-overview.md
en/docs/integrate/integration-use-case/protocol-switching-overview.md
en/docs/integrate/integration-use-case/scheduled-task-overview.md

Adding basepath to link url + minor fixes (set 3)
- Integrate/integration-use-case section

Adding basepath to link url + minor fixes (set 3)

---

en/docs/develop/streaming-apps/business-rules-apis.md

Rewrite file to eliminate formatting issues

---

en/docs/integrate/examples/integrating-mi-with-si.md
en/docs/integrate/examples/rabbitmq_examples/move-msgs-to-dlq-rabbitmq.md
en/docs/integrate/examples/rabbitmq_examples/point-to-point-rabbitmq.md
en/docs/integrate/examples/rabbitmq_examples/pub-sub-rabbitmq.md
en/docs/integrate/examples/rabbitmq_examples/request-response-rabbitmq.md
en/docs/integrate/examples/rabbitmq_examples/requeue-msgs-with-errors-rabbitmq.md
en/docs/integrate/examples/rabbitmq_examples/retry-delay-failed-msgs-rabbitmq.md
en/docs/integrate/examples/rabbitmq_examples/store-forward-rabbitmq.md
en/docs/integrate/examples/registry_examples/local-registry-entries.md
en/docs/integrate/examples/rest_api_examples/configuring-non-http-endpoints.md
en/docs/integrate/examples/rest_api_examples/enabling-rest-to-soap.md
en/docs/integrate/examples/rest_api_examples/handling-non-matching-resources.md
en/docs/integrate/examples/rest_api_examples/introduction-rest-api.md
en/docs/integrate/examples/rest_api_examples/publishing-a-swagger-api.md
en/docs/integrate/examples/rest_api_examples/securing-rest-apis.md
en/docs/integrate/examples/rest_api_examples/setting-https-status-codes.md
en/docs/integrate/examples/rest_api_examples/setting-query-params-outgoing-messages.md
en/docs/integrate/examples/rest_api_examples/transforming-content-type.md
en/docs/integrate/examples/routing_examples/routing_based_on_headers.md
en/docs/integrate/examples/routing_examples/routing_based_on_payloads.md
en/docs/integrate/examples/routing_examples/splitting_aggregating_messages.md
en/docs/integrate/examples/scheduled-tasks/injecting-messages-to-rest-endpoint.md
en/docs/integrate/examples/scheduled-tasks/task-scheduling-simple-trigger.md
en/docs/integrate/examples/sequence_examples/custom-sequences-with-proxy-services.md
en/docs/integrate/examples/sequence_examples/using-fault-sequences.md
en/docs/integrate/examples/sequence_examples/using-multiple-sequences.md
en/docs/integrate/examples/template_examples/using-endpoint-templates.md
en/docs/integrate/examples/template_examples/using-sequence-templates.md
en/docs/integrate/examples/transport_examples/tcp-transport-examples.md
en/docs/integrate/examples/working-with-transactions.md

Adding basepath to link url + minor fixes (set 6)

Adding basepath to link url + minor fixes (set 6)

---

en/docs/design/api-security/threat-protection/gateway-threat-protectors/gateway-threat-protectors-for-api-manager.md
en/docs/reference/customize-product/extending-api-manager/saml2-sso/configuring-external-idp-through-identity-server-for-sso.md

Fixed some links related to APIM content.

Adding basepath to link url + minor fixes (set 8)

---

en/docs/integrate/develop/create-integration-project.md
en/docs/integrate/develop/intro-integration-development.md
en/docs/integrate/learn-overview.md

Adding basepath to link url + minor fixes (set 6)

Adding basepath to link url + minor fixes (set 7)

---

en/docs/observe/api-manager-analytics/integrating-with-google-analytics.md
en/docs/observe/api-manager-analytics/purging-analytics-data.md
en/docs/observe/mi-observe/logs/monitoring_logs.md
en/docs/observe/mi-observe/mi-observability-overview.md
en/docs/observe/mi-observe/tcp/message_monitoring_with_tcpmon.md
en/docs/observe/mi-observe/tcp/other_usages_of_tcpmon.md
en/docs/observe/mi-observe/working-with-management-api.md
en/docs/observe/mi-observe/working-with-monitoring-dashboard.md

Adding basepath to link url + minor fixes (set 9)

Adding basepath to link url + minor fixes (set 9)

---

en/docs/administer/logging-and-monitoring/monitoring/monitoring-with-opentracing.md

This PR addresses https://github.com/wso2/docs-apim/pull/2456#discussion_r552393050

[3.1.0] Fix typos in OpenTracing docs

---

en/docs/learn/api-security/threat-protection/bot-detection.md

PR sync for https://github.com/wso2/docs-apim/pull/2805

[3.1.0] Improve bot detection page

---

en/docs/learn/api-security/threat-protection/bot-detection.md

PR sync for https://github.com/wso2/docs-apim/pull/2805

[3.0.0] Improve bot detection page

---

en/docs/consume/collaboration/use-the-community-features.md
en/docs/consume/generating-sdks/write-a-client-application-using-the-sdk.md
en/docs/consume/manage-subscription/advanced-topics/adding-an-api-subscription-workflow-using-bps.md
en/docs/design/api-security/api-authentication/secure-apis-using-basic-authentication.md
en/docs/design/api-security/api-request-response-schema-validation/json-schema-validator.md
en/docs/design/api-security/oauth2/encrypting-oauth2-tokens.md
en/docs/design/api-security/oauth2/oauth2-scopes/fine-grained-access-control-with-oauth-scopes.md
en/docs/design/api-security/threat-protection/gateway-threat-protectors/gateway-threat-protectors-for-api-manager.md
en/docs/design/rate-limiting/enforce-throttling-and-resource-access-policies.md
en/docs/design/rate-limiting/engaging-a-new-throttling-policy-at-runtime.md
en/docs/design/rate-limiting/setting-maximum-backend-throughput-limits.md
en/docs/get-started/overview.md
en/docs/install-and-setup/install/installing-the-product/installing-the-binary/installing-on-windows.md
en/docs/publish/api-gateway/api-gateways-with-dedicated-backends.md
en/docs/publish/api-gateway/maintaining-separate-production-and-sandbox-gateways.md
en/docs/publish/api-gateway/scaling-the-gateway.md
en/docs/publish/api-gateway/threat-protectors/json-threat-protection-for-api-gateway.md
en/docs/publish/api-gateway/threat-protectors/regular-expression-threat-protection-for-api-gateway.md
en/docs/publish/api-gateway/threat-protectors/xml-threat-protection-for-api-gateway.md
en/docs/reference/connectors/salesforce-connectors/sf-soap-connector-config.md
en/docs/reference/connectors/salesforce-soap-connector/sf-soap-connector-config.md
en/docs/reference/mi-security-reference/security-implementation.md
en/docs/troubleshooting/troubleshooting-invalid-callback-error.md

Adding basepath to link url + minor fixes (set 11)

Adding basepath to link url + minor fixes (set 11)

---

en/docs/administer/managing-users-and-roles/managing-user-stores/configure-primary-user-store/configuring-a-read-write-active-directory-user-store.md
en/docs/administer/managing-users-and-roles/managing-user-stores/configure-primary-user-store/configuring-the-primary-user-store.md

Adding basepath to link url + minor fixes (set 12)

Adding basepath to link url + minor fixes (set 12)

---

en/docs/learn/analytics/configuring-apim-analytics.md

Correcting HA setup configuration by adding notes and config examples based on HA setup type.
Fixes https://github.com/wso2/docs-apim/issues/2975 for 3.0.0

[3.0.0] Fixing HA terminology in APIM Analytics

---

en/tools/config-catalog-generator/data/apim.analytics.url_group.toml
en/tools/config-catalog-generator/data/configs.json

Fix formatting issues in https://github.com/wso2/docs-apim/pull/2439

[3.1.0] Formatting fixes

---

en/docs/assets/css/theme.css

3.0.0 fix for https://github.com/wso2/docs-apim/pull/3002

Fixing the style issue with the title spacing

---

en/docs/develop/customizations/log-in-to-the-dev-portal-using-social-media.md

Fixing formatting issues in the section of Basic Claims Configurations and Role configurations in the following doc [1].
[1]. https://apim.docs.wso2.com/en/3.1.0/develop/customizations/log-in-to-the-dev-portal-using-social-media/#log-in-to-the-developer-portal-using-social-media
Fixes https://github.com/wso2/docs-apim/issues/3006

[3.1.0] Fixing formatting issues

---

en/docs/install-and-setup/setup/api-controller/getting-started-with-wso2-api-controller.md

Docs for https://github.com/wso2/product-apim-tooling/issues/577 …

Add apictl TLS Renegotiation docs

---

en/docs/develop/product-apis/admin-apis/admin-v0.16/admin-v0.16.yaml

This PR will add scope security definitions to Admin REST API 0.17.
The scopes for the API will be listed as,
and the API resource scopes will be listed as,
Fixes #3013 in 3.1.0 docs.
> Link(s) to product documentation that addresses the changes of this PR. If no doc impact, enter …

Add scope security definitions to Admin REST API 0.16

---

en/docs/develop/product-apis/admin-apis/admin-v0.17/admin-v0.17.yaml

This PR will add scope security definitions to Admin  REST API 0.17.
The scopes for the API will be listed as,
and the API resource scopes will be listed as,
Fixes https://github.com/wso2/docs-apim/issues/3013 in 3.2.0 docs.
> Link(s) to product documentation that addresses the …

Add scope security definitions to Admin  REST API 0.17

---

en/docs/reference/config-catalog.md
en/tools/config-catalog-generator/data/configs.json
en/tools/config-catalog-generator/data/synapse_handlers.toml

Update global handler config

---

en/docs/reference/mediators/call-mediator.md

Add call mediator improvements related doc. Related feature PR https://github.com/wso2/wso2-synapse/pull/1662

Add call mediator improvements related doc

---

en/docs/reference/mediators/call-mediator.md

improvements to Call mediator doc

Improvements to Call mediator doc

---

en/docs/reference/mediators/call-mediator.md

copy edit - call mediator doc

---

en/docs/reference/mediators/payloadfactory-mediator.md

Documenting the Freemarker template feature.

freemarker template docs

---

en/docs/install-and-setup/setup/api-controller/getting-started-with-wso2-api-controller.md
en/docs/install-and-setup/setup/api-controller/managing-integrations-with-ctl.md
en/mkdocs.yml

https://github.com/wso2/product-apim-tooling/issues/556
- Update Add environment and Get environments sections in Getting Started with WSO2 API Controller section.
- Add a new section named **Managing Integrations with CTL** under API Controller and add mi related commands.

Revamping the apictl documentation with MI integration

---

en/docs/install-and-setup/setup/deployment-best-practices/tuning-performance.md

This PR fixes https://github.com/wso2/docs-apim/issues/3047 and https://github.com/wso2/docs-apim/issues/3048

Fix tuning parameters

---

en/docs/get-started/quick-start-guide/integration-qsg.md

broken images in the MI qsg

---

en/docs/install-and-setup/setup/api-controller/advanced-topics/configuring-environment-specific-parameters.md

This PR add the the docs related to the new feature of APICTL 4.0.0. https://github.com/wso2/product-apim-tooling/pull/580

Add the bundle command docs of API controller

---

en/docs/learn/api-security/oauth2/grant-types/authorization-code-grant.md
en/docs/learn/api-security/oauth2/grant-types/client-credentials-grant.md
en/docs/learn/api-security/oauth2/grant-types/implicit-grant.md
en/docs/learn/api-security/oauth2/grant-types/jwt-grant.md
en/docs/learn/api-security/oauth2/grant-types/ntlm-grant.md
en/docs/learn/api-security/oauth2/grant-types/password-grant.md
en/docs/learn/api-security/oauth2/grant-types/refresh-token-grant.md
en/docs/learn/api-security/oauth2/grant-types/saml-extension-grant.md

Fixes: https://github.com/wso2/docs-apim/issues/3058
Adding the configs to be set up in the deployment.toml to enable/disable different grant types.
Added a **tip** as shown below to each of the grant type.

[3.2.0] Add the configs to disable the grant types

---

en/docs/design/api-security/oauth2/grant-types/authorization-code-grant.md
en/docs/design/api-security/oauth2/grant-types/client-credentials-grant.md
en/docs/design/api-security/oauth2/grant-types/implicit-grant.md
en/docs/design/api-security/oauth2/grant-types/jwt-grant.md
en/docs/design/api-security/oauth2/grant-types/ntlm-grant.md
en/docs/design/api-security/oauth2/grant-types/password-grant.md
en/docs/design/api-security/oauth2/grant-types/refresh-token-grant.md
en/docs/design/api-security/oauth2/grant-types/saml-extension-grant.md

Fixes: https://github.com/wso2/docs-apim/issues/3058
Adding the configs to be set up in the deployment.toml to enable/disable different grant types.
Added a **tip** as shown below to each of the grant type.

Add the configs to disable the grant types

---

en/docs/learn/api-security/oauth2/grant-types/authorization-code-grant.md
en/docs/learn/api-security/oauth2/grant-types/client-credentials-grant.md
en/docs/learn/api-security/oauth2/grant-types/implicit-grant.md
en/docs/learn/api-security/oauth2/grant-types/jwt-grant.md
en/docs/learn/api-security/oauth2/grant-types/ntlm-grant.md
en/docs/learn/api-security/oauth2/grant-types/password-grant.md
en/docs/learn/api-security/oauth2/grant-types/refresh-token-grant.md
en/docs/learn/api-security/oauth2/grant-types/saml-extension-grant.md

Fixes: https://github.com/wso2/docs-apim/issues/3058
Adding the configs to be set up in the deployment.toml to enable/disable different grant types.
Added a **tip** as shown below to each of the grant type.

[3.1.0] Add the configs to disable the grant types

---

en/docs/learn/api-security/oauth2/grant-types/authorization-code-grant.md
en/docs/learn/api-security/oauth2/grant-types/client-credentials-grant.md
en/docs/learn/api-security/oauth2/grant-types/implicit-grant.md
en/docs/learn/api-security/oauth2/grant-types/jwt-grant.md
en/docs/learn/api-security/oauth2/grant-types/ntlm-grant.md
en/docs/learn/api-security/oauth2/grant-types/password-grant.md
en/docs/learn/api-security/oauth2/grant-types/refresh-token-grant.md
en/docs/learn/api-security/oauth2/grant-types/saml-extension-grant.md

Fixes: https://github.com/wso2/docs-apim/issues/3058
Adding the configs to be set up in the deployment.toml to enable/disable different grant types.
Added a **tip** as shown below to each of the grant type.

[3.0.0] Add the configs to disable the grant types

---

en/docs/install-and-setup/setup/api-controller/advanced-topics/configuring-environment-specific-parameters.md
en/docs/install-and-setup/setup/api-controller/advanced-topics/creating-custom-users-to-perform-api-controller-operations.md
en/docs/install-and-setup/setup/api-controller/ci-cd-with-wso2-api-management.md

Fixes: https://github.com/wso2/docs-apim/pull/1442#discussion_r566558804
Fixes: https://github.com/wso2/docs-apim/pull/1133#discussion_r566562926
Fixes: https://github.com/wso2/docs-apim/pull/1005#discussion_r566559349

Fixing reviewed comments

---

en/docs/learn/api-controller/advanced-topics/configuring-environment-specific-parameters.md
en/docs/learn/api-controller/advanced-topics/creating-custom-users-to-perform-api-controller-operations.md
en/docs/learn/api-controller/ci-cd-with-wso2-api-management.md

Fixes: https://github.com/wso2/docs-apim/pull/1442#discussion_r566558804
Fixes: https://github.com/wso2/docs-apim/pull/1133#discussion_r566562926
Fixes: https://github.com/wso2/docs-apim/pull/1005#discussion_r566559349
Fixes: https://github.com/wso2/docs-apim/pull/1005#discussion_r566559828

[3.2.0] Fixing reviewed comments

---

en/docs/learn/api-controller/advanced-topics/configuring-environment-specific-parameters.md

Fixes: https://github.com/wso2/docs-apim/pull/1005#discussion_r566559349
Fixes: https://github.com/wso2/docs-apim/pull/1005#discussion_r566559828

[3.1.0] Fixing reviewed comments

---

en/docs/learn/api-controller/advanced-topics/configuring-environment-specific-parameters.md

Fixes: https://github.com/wso2/docs-apim/pull/1005#discussion_r566559349

[3.0.0] Fixing reviewed comments

---

en/docs/develop/customizations/customizing-the-developer-portal/enable-or-disable-banner.md
en/docs/develop/customizations/customizing-the-developer-portal/enable-or-disable-footer.md
en/docs/develop/customizations/customizing-the-developer-portal/enable-or-disable-home-page.md
en/docs/develop/customizations/customizing-the-developer-portal/enable-or-disable-rating.md
en/docs/develop/customizations/customizing-the-developer-portal/enable-or-disable-tag-cloud.md
en/docs/develop/customizations/customizing-the-developer-portal/enabling-or-disabling-api-detail-tabs.md
en/docs/develop/customizations/customizing-the-developer-portal/override-api-overview-page-per-api.md
en/docs/develop/customizations/customizing-the-developer-portal/styling-api-details-info-section.md
en/docs/develop/customizations/customizing-the-developer-portal/styling-api-details-left-menu.md
en/docs/develop/customizations/customizing-the-developer-portal/styling-the-logo-and-header.md

Fixes: https://github.com/wso2/docs-apim/issues/2945
Fixing the steps and inconsistencies in the section **Customizing the Developer Portal**.
- Added a sentence on `defaultTheme.js` to almost all the pages under **Customizing the Developer Portal**, so that the user can have an idea of it. (For example, check the second paragraph of the below screenshot.)
- Restructured the steps on some pages.
- Corrected the typos and formatting.

[3.1.0] Improve the consistency of the docs on Developer Portal Customizations

---

en/docs/install-and-setup/setup/mi-setup/performance_tuning/jms_transport_tuning.md

fixes EIINTERNAL-673

---

en/docs/install-and-setup/setup/mi-setup/performance_tuning/jms_transport_tuning.md

fix for EIINTERNAL-673 based on review comments

fix for EIINTERNAL-673 based on review comments

---

en/docs/install-and-setup/setup/mi-setup/performance_tuning/jms_transport_tuning.md

Define connection between max and core values EIINTERNAL-673

Define connection between max and core values EIINTERNAL-673

---

en/docs/install-and-setup/setup/reference/common-runtime-and-configuration-artifacts.md

APIM-Analytics-3.2.0 persistent artifacts

---

en/docs/administer/key-managers/configure-wso2is-connector.md
en/docs/install-and-setup/setup/distributed-deployment/configuring-wso2-identity-server-as-a-key-manager.md

update the doc with wum timestamp up to which the provided connector is valid. …

add relavant wum timestamp

---

en/docs/install-and-setup/setup/setting-up-proxy-server-and-the-load-balancer/configuring-the-proxy-server-and-the-load-balancer.md

Fix codeblock

---

en/docs/publish/api-microgateway/internal-communication-protocol.md
en/mkdocs.yml

Microgateway xds communication overview

Add xds concept doc

---

en/docs/install-and-setup/setup/security/user-account-management.md

Change H2- > **Disabling Anonymous Access to the Developer Portal** to **Disabling anonymous access to the Developer Portal**

Change the Heading 2 of disabling anonymous mode

---

en/docs/install-and-setup/setup/security/user-account-management.md

Change H2- > **Disabling Anonymous Access to the Developer Portal** to **Disabling anonymous access to the Developer Portal**

[3.2.0] Change the Heading 2 of disabling anonymous mode

---

en/docs/administer/product-security/identity-management-for-the-api-dev-portal.md

Change H2- > **Disabling Anonymous Access to the Developer Portal** to **Disabling anonymous access to the Developer Portal**

[3.0.0] Change the Heading 2 of disabling anonymous mode

---

en/docs/install-and-setup/setup/reference/product-compatibility.md

Added WSO2 API-M Analytics to compatibility section.

Added WSO2 API-M Analytics to compatibility

---

en/docs/install-and-setup/setup/reference/common-runtime-and-configuration-artifacts.md

Additional update for APIMINTERNAL-339

---

en/docs/install-and-setup/setup/reference/common-runtime-and-configuration-artifacts.md

Sync PR for #3138

---

en/docs/develop/extending-api-manager/extending-workflows/configuring-workflows-for-tenants.md

Fixes: https://github.com/wso2/docs-apim/issues/3122
Including a step with **ApplicationCallbackService-Tenant.epr**.
The newly added step is shown below.

[3.1.0] Adding a new step when configuring workflow for tenants

---

en/docs/develop/extending-api-manager/extending-workflows/configuring-workflows-for-tenants.md

Fixes: https://github.com/wso2/docs-apim/issues/3122
Including a step with **ApplicationCallbackService-Tenant.epr**.
The newly added step is shown below.

[3.2.0] Adding a new step when configuring workflow for tenants

---

en/docs/reference/customize-product/extending-api-manager/extending-workflows/configuring-workflows-for-tenants.md

Fixes: https://github.com/wso2/docs-apim/issues/3122
Including a step with **ApplicationCallbackService-Tenant.epr**.
The newly added step is shown below.

Adding a new step when configuring workflow for tenants

---

en/docs/learn/extensions/managing-workflow-extension/configuring-workflows-for-tenants.md

Fixes: https://github.com/wso2/docs-apim/issues/3122
Including a step with **ApplicationCallbackService-Tenant.epr**.
The newly added step is shown below.

[3.0.0] Adding a new step when configuring workflow for tenants

---

en/docs/get-started/about-this-release.md

Improving the description on removing the implicit grant from APIM 4.0.0 docs.

Improving the description on removing Implicit Grant

---

en/docs/administer/key-managers/configure-wso2is-connector.md
en/docs/install-and-setup/setup/distributed-deployment/configuring-wso2-identity-server-as-a-key-manager.md
en/docs/install-and-setup/upgrading-wso2-is-as-key-manager/upgrading-from-is-km-5100-to-is-5100.md
en/docs/install-and-setup/upgrading-wso2-is-as-key-manager/upgrading-from-is-km-520-to-5100.md
en/docs/install-and-setup/upgrading-wso2-is-as-key-manager/upgrading-from-is-km-530-to-5100.md
en/docs/install-and-setup/upgrading-wso2-is-as-key-manager/upgrading-from-is-km-550-to-5100.md
en/docs/install-and-setup/upgrading-wso2-is-as-key-manager/upgrading-from-is-km-560-to-5100.md
en/docs/install-and-setup/upgrading-wso2-is-as-key-manager/upgrading-from-is-km-570-to-5100.md
en/docs/install-and-setup/upgrading-wso2-is-as-key-manager/upgrading-from-is-km-590-to-5100.md

fixes APIMINTERNAL-305

---

en/docs/getting-started/about-this-release.md
en/docs/learn/api-security/oauth2/grant-types/implicit-grant.md
en/mkdocs.yml

Improving deprecated Implicit Grant description and redirection of anonymous access to Developer Portal
1. Improving the deprecated Implicit Grant description 
2. Adding redirection of anonymous access to Developer Portal

[3.2.0] Improving the deprecated Implicit Grant description and adding redirection of anonymous access to Developer Portal

---

en/mkdocs.yml

Adding redirection of anonymous access to Developer Portal

[3.0.0] Adding redirection of anonymous access to Developer Portal

---

en/docs/learn/api-gateway/message-mediation/passing-a-custom-authorization-token-to-the-backend.md

fixes https://github.com/wso2/docs-apim/issues/3159

fixes https://github.com/wso2/docs-apim/issues/3159

---

en/docs/install-and-setup/setup/reference/product-compatibility.md

RHEL compatibility of APIM 3.2.0.

RHEL compatibility for 3.2.0

---

en/mkdocs.yml

This updates the yaml file with the latest API Controller structure.

Update mkdocs.yml with missing API Controller topics

---

en/mkdocs.yml

fixes https://github.com/wso2/docs-apim/issues/3182

fixes https://github.com/wso2/docs-apim/issues/3182

---

en/docs/learn/consume-api/invoke-apis/invoke-apis-using-tools/invoke-an-graphql-api-using-the-integrated-graphql-console.md

fixes https://github.com/wso2/docs-apim/issues/3187

fixes issue 2 in docs-apim/issues/3187

---

en/docs/learn/tutorials/create-and-publish-a-graphql-api.md

fixes issue 2 in https://github.com/wso2/docs-apim/issues/3187

fixes issue 2 docs-apim/issues/3187

---

en/docs/install-and-setup/install/installation-prerequisites.md

fix for APIMINTERNAL-344 and https://github.com/wso2/docs-apim/issues/3148

Fixes https://github.com/wso2/docs-apim/issues/3148

---

en/docs/install-and-setup/setup/distributed-deployment/product-profiles.md

Fix for APIMINTERNAL-359

---

en/docs/observe/si-observe/viewing-overall-statistics.md

Add more information in SI Observability documentation

---

en/docs/reference/config-catalog-mi.md
en/docs/reference/config-catalog.md
en/mkdocs.yml

Committing the config catalog for the micro integrator.

mi config catalog

---

en/docs/install-and-setup/setup/distributed-deployment/understanding-the-distributed-deployment-of-wso2-api-m.md

fixes https://github.com/wso2/docs-apim/issues/3207

fixes #3207

---

en/docs/install-and-setup/upgrading-wso2-api-manager/upgrading-from-1100-to-320.md
en/docs/install-and-setup/upgrading-wso2-api-manager/upgrading-from-200-to-320.md
en/docs/install-and-setup/upgrading-wso2-api-manager/upgrading-from-210-to-320.md
en/docs/install-and-setup/upgrading-wso2-api-manager/upgrading-from-220-to-320.md
en/docs/install-and-setup/upgrading-wso2-api-manager/upgrading-from-250-to-320.md
en/docs/install-and-setup/upgrading-wso2-api-manager/upgrading-from-260-to-320.md
en/docs/install-and-setup/upgrading-wso2-api-manager/upgrading-from-300-to-320.md
en/docs/install-and-setup/upgrading-wso2-api-manager/upgrading-from-310-to-320.md
en/docs/install-and-setup/upgrading-wso2-api-manager/upgrading-process.md
en/docs/reference/understanding-the-new-configuration-model.md

Fixes https://github.com/wso2/docs-apim/issues/3063 review comments

fixes https://github.com/wso2/docs-apim/issues/3063 review comments

---

en/docs/deploy/api-microgateway/security/api-authentication/api-authentication.md
en/docs/deploy/api-microgateway/security/api-authentication/secure-apis-using-oauth2.0-access-tokens/secure-apis-using-jwt-self-contained-jwt.md
en/docs/deploy/api-microgateway/security/api-authorization/scope-validation.md
en/mkdocs.yml

> Adds the microgateway 4.0.0 scope validation docs

Update microgateway scope validation docs

---

en/docs/assets/css/theme.css
en/mkdocs.yml
en/theme/material/partials/tabs-item.html

Fix navigation seperation
> Link to the PR for changes to the training content in https://github.com/wso2/WSO2-Training, if …

Fix navigation seperation

---

en/docs/deploy/api-microgateway/getting-started/quick-start-guide/quick-start-guide-kubernetes.md

$ subject - 2.0.0-alpha
corrected to apply from alpha
```
kubectl apply -f https://raw.githubusercontent.com/wso2/k8s-api-operator/v2.0.0-m3/scenarios/scenario-2/petstore-api.yaml
```

Update operator version

---

en/docs/observe/mi-observe/working-with-monitoring-dashboard.md

Updates to the MI dashboard documentation.

Dashboard docs

---

en/docs/install-and-setup/setup/distributed-deployment/deploying-wso2-api-m-in-a-distributed-setup.md

File mounting instructions for distributed deployments

---

en/docs/install-and-setup/setup/sso/configuring-identity-server-as-external-idp-using-oidc.md

Update Configuring API Manager section with Assert identity using mapped local subject identifier parameter 

---

en/docs/design/advanced-topics/control-api-visibility-and-subscription-availability-in-developer-portal.md

Cross tenant subscription

---

en/theme/material/customizations.md

Update nav separation customizations

---

en/docs/get-started/quick-start-guide/quick-start-guide.md
en/docs/install-and-setup/setup/api-controller/advanced-topics/configuring-environment-specific-parameters.md
en/docs/install-and-setup/setup/api-controller/advanced-topics/using-dynamic-data-in-api-controller-projects.md
en/docs/install-and-setup/setup/api-controller/building-jenkins-ci-cd-pipeline-for-dev-first-approach.md
en/docs/install-and-setup/setup/api-controller/ci-cd-with-wso2-api-management.md
en/docs/install-and-setup/setup/api-controller/getting-started-with-wso2-api-controller.md
en/docs/install-and-setup/setup/api-controller/managing-apis-api-products/importing-apis-via-dev-first-approach.md
en/docs/install-and-setup/setup/api-controller/managing-apis-api-products/managing-apis-and-api-products.md
en/docs/install-and-setup/setup/api-controller/managing-apis-api-products/migrating-api-products-to-different-environments.md
en/docs/install-and-setup/setup/api-controller/managing-apis-api-products/migrating-apis-to-different-environments.md
en/docs/install-and-setup/setup/api-controller/managing-applications/managing-applications.md
en/docs/install-and-setup/setup/api-controller/managing-applications/migrating-applications-to-different-environments.md

Update the API Controller docs with the revision support. 
Updated, 
- import api/api-product
- export api/api-product
- undeploy api/api-product
- get api/api-product revisions
Updated the existing flags after the code revamp in https://github.com/wso2/product-apim-tooling/issues/613

Controller documentation changes after revision feature

---

en/docs/integrate/integration-overview.md
en/docs/tutorials/tutorials-overview.md

Overview of the Tutorials section

Tutorials section - overview

---

README.md
en/docs/install-and-setup/setup/api-controller/managing-microgateways/managing-microgateways-with-ctl.md
en/mkdocs.yml

- This PR was created after rebasing the Original PR: https://github.com/wso2/docs-apim/pull/3223
- Docs related to wso2/product-apim-tooling#625

Add 'manage microgateways with apictl' docs

---

en/docs/tutorials/tutorials-overview.md

Minor copy edit

---

en/docs/install-and-setup/upgrading-wso2-api-manager/upgrading-from-200-to-320.md
en/docs/install-and-setup/upgrading-wso2-api-manager/upgrading-from-210-to-320.md
en/docs/install-and-setup/upgrading-wso2-api-manager/upgrading-from-220-to-320.md
en/docs/install-and-setup/upgrading-wso2-api-manager/upgrading-from-250-to-320.md
en/docs/install-and-setup/upgrading-wso2-api-manager/upgrading-from-260-to-320.md
en/docs/install-and-setup/upgrading-wso2-api-manager/upgrading-from-300-to-320.md
en/docs/install-and-setup/upgrading-wso2-api-manager/upgrading-from-310-to-320.md

Fixes below issue when running H2 migration scripts for APIM DB.
```
UPDATE IDN_OAUTH_CONSUMER_APPS SET CALLBACK_URL="" WHERE CALLBACK_URL IS NULL;
Column  not found; SQL statement:
UPDATE IDN_OAUTH_CONSUMER_APPS SET CALLBACK_URL="" WHERE CALLBACK_URL IS NULL [42122-175] 42S22/42122 (Help)
```
> Brief description of the new feature or bug fix as it will appear in the …

Fix h2 migration scripts

---

en/docs/administer/logging-and-monitoring/logging/monitoring-http-access-logs.md

https://github.com/wso2/docs-apim/issues/3258

fixes wrong link #3258

---

en/docs/install-and-setup/deploying-wso2-api-manager/distributed-deployment/product-profiles.md

Sync PR for #3199 
Fixes #3198

Updating docs to support in-place updates on profile optimized packs

---

en/docs/install-and-setup/setup/distributed-deployment/configuring-wso2-identity-server-as-a-key-manager.md

Add missing hyphen in code sample

---

en/docs/reference/product-apis/overview.md
en/docs/reference/product-apis/service-catalog-apis/service-catalog-v1/service-catalog-v1.md
en/docs/reference/product-apis/service-catalog-apis/service-catalog-v1/service-catalog-v1.yaml
en/mkdocs.yml

> Add service catalog REST API docs

Add service catalog REST API docs

---

en/docs/develop/product-apis/devportal-apis/devportal-v1/devportal-v1.yaml

[APIM-3.2.0] Change note to convey correct message about Retrieve/Search APIs

---

en/docs/develop/product-apis/devportal-apis/devportal-v1/devportal-v1.yaml

Fixes broken page in [1]
[1] https://apim.docs.wso2.com/en/latest/develop/product-apis/devportal-apis/devportal-v1/devportal-v1/

Fixed error in YAML file

---

en/mkdocs.yml

YAML updated with tutorials overview page.

tutorials overview - yaml

---

en/docs/install-and-setup/upgrading-wso2-api-manager/upgrading-from-200-to-320.md
en/docs/install-and-setup/upgrading-wso2-api-manager/upgrading-from-210-to-320.md
en/docs/install-and-setup/upgrading-wso2-api-manager/upgrading-from-220-to-320.md
en/docs/install-and-setup/upgrading-wso2-api-manager/upgrading-from-250-to-320.md
en/docs/install-and-setup/upgrading-wso2-api-manager/upgrading-from-260-to-320.md
en/docs/install-and-setup/upgrading-wso2-api-manager/upgrading-from-300-to-320.md

As $subject, this PR will add the 3rd config which needs to remove from the IS migration-config.yaml.
After adding the missing step, the doc is like below.
Fixes https://github.com/wso2/docs-apim/issues/3282.

Add missing step in the IS migration client

---

en/docs/learn/design-api/advanced-topics/control-api-visibility-and-subscription-availability-in-developer-portal.md

Subscription Availability toml config

---

en/docs/tutorials/integration-tutorials/service-catalog-tutorial.md

MI service catalog tutorial revamped

MI service catalog tutorial revamped

---

en/docs/develop/extending-api-manager/saml2-sso/configuring-identity-server-as-idp-for-sso.md
en/docs/install-and-setup/setup/sso/configuring-identity-server-as-external-idp-using-saml.md

Update API Manager Configurations with 'Assert identity using mapped local subject identifier'

---

en/docs/learn/api-controller/importing-apis-via-dev-first-approach.md

Point to the correct location in APICTL 3.2.x branch

Update the sample-api.yaml link in APICTL docs

---

en/docs/get-started/about-this-release.md
en/docs/install-and-setup/setup/api-controller/advanced-topics/configuring-different-endpoint-types.md
en/docs/install-and-setup/setup/api-controller/advanced-topics/configuring-environment-specific-parameters.md
en/docs/install-and-setup/setup/api-controller/advanced-topics/configuring-git-integration.md
en/docs/install-and-setup/setup/api-controller/advanced-topics/creating-custom-users-to-perform-api-controller-operations.md
en/docs/install-and-setup/setup/api-controller/advanced-topics/formatting-the-output-of-get-command.md
en/docs/install-and-setup/setup/api-controller/advanced-topics/using-dynamic-data-in-api-controller-projects.md
en/docs/install-and-setup/setup/api-controller/building-jenkins-ci-cd-pipeline-for-dev-first-approach.md
en/docs/install-and-setup/setup/api-controller/ci-cd-with-wso2-api-management.md
en/docs/install-and-setup/setup/api-controller/encrypting-secrets-with-ctl.md
en/docs/install-and-setup/setup/api-controller/getting-started-with-wso2-api-controller.md
en/docs/install-and-setup/setup/api-controller/managing-apis-api-products/importing-apis-via-dev-first-approach.md
en/docs/install-and-setup/setup/api-controller/managing-apis-api-products/managing-apis-and-api-products.md
en/docs/install-and-setup/setup/api-controller/managing-apis-api-products/migrating-api-products-to-different-environments.md
en/docs/install-and-setup/setup/api-controller/managing-apis-api-products/migrating-apis-to-different-environments.md
en/docs/install-and-setup/setup/api-controller/managing-applications/managing-applications.md
en/docs/install-and-setup/setup/api-controller/managing-applications/migrating-applications-to-different-environments.md
en/docs/install-and-setup/setup/api-controller/managing-integrations/managing-integrations-with-ctl.md
en/docs/install-and-setup/setup/api-controller/managing-microgateways/managing-microgateways-with-ctl.md
en/mkdocs.yml

Add documentation for [1] and [2].
Fixes: https://github.com/wso2/docs-apim/issues/3156 for APIM 4.0.0
[1] https://github.com/wso2/product-apim-tooling/issues/650
[2] https://github.com/wso2/product-apim-tooling/issues/541

Add documentation for API Product params file and introduce/use "apictl" abbreviation in APICTL docs

---

en/docs/develop/product-apis/gateway-apis/gateway-v1/gateway-v1.yaml

Fixed the issues in gateway rest API swagger definition
1. Removed OAuth2 related steps from the description.
2. Updated the sample curl with basic auth
3. Removed unimplemented response and error codes.

Fixed the doc issues in gateway rest API

---

en/docs/integrate/develop/create-integration-project.md
en/docs/integrate/develop/create-kubernetes-project.md
en/docs/integrate/develop/customizations/creating-custom-task-scheduling.md
en/docs/integrate/develop/intro-integration-development.md
en/docs/integrate/develop/using-remote-micro-integrator.md
en/docs/integrate/develop/wso2-integration-studio.md
en/docs/integrate/examples/hl7-examples/file_transfer_using_hl7.md
en/docs/integrate/examples/protocol-switching/switching_from_http_to_fix.md
en/docs/integrate/integration-use-case/connectors.md

removed WSO2 EI, EI, and WSO2 Enterprise Integrator from descriptions in the 'Integrate' section

Fixing the tone - Integrate section

---

en/docs/administer/key-managers/configure-forgerock-connector.md

fixes https://github.com/wso2/docs-apim/issues/3318

fixes https://github.com/wso2/docs-apim/issues/3318

---

en/docs/deploy/deploy-api/exposing-apis-via-custom-hostnames.md
en/docs/includes/deploy/assign-custom-hostname.md

fixes https://github.com/wso2/docs-apim/issues/3344

fixes https://github.com/wso2/docs-apim/issues/3344

---

en/docs/install-and-setup/setup/mi-setup/transport_configurations/configuring-transports.md
en/docs/streaming/connectors/connectors-overview.md
en/mkdocs.yml

Correct Broken Links in MI Transport Configuration docs

---

en/docs/install-and-setup/setup/security/configuring-keystores/configuring-keystores-in-wso2-api-manager.md
en/docs/install-and-setup/setup/security/configuring-keystores/keystore-basics/about-asymetric-cryptography.md
en/docs/install-and-setup/setup/security/configuring-keystores/keystore-basics/creating-new-keystores.md

Correct Broken Links in Security documentation

---

en/docs/install-and-setup/setup/mi-setup/security/about_forgetme_tool.md
en/docs/install-and-setup/setup/mi-setup/security/configuring_keystores.md
en/docs/install-and-setup/setup/mi-setup/security/creating_keystores.md
en/docs/install-and-setup/setup/mi-setup/security/encrypting_plain_text.md
en/docs/install-and-setup/setup/mi-setup/security/gdpr_ei.md
en/docs/install-and-setup/setup/mi-setup/security/importing_ssl_certificate.md
en/docs/install-and-setup/setup/mi-setup/security/renewing_ca_signed_certificate_in_keystore.md
en/docs/install-and-setup/setup/mi-setup/security/securing_management_api.md
en/docs/install-and-setup/setup/mi-setup/security/single_key_encryption.md
en/docs/install-and-setup/setup/mi-setup/security/using-hashicorp-secrets.md

Correct Broken Links in MI Security documentation

---

en/docs/install-and-setup/setup/api-controller/managing-integrations/managing-integrations-with-ctl.md
en/docs/install-and-setup/setup/mi-setup/security/using-hashicorp-secrets.md

Change Update HashiCorp configurations title

---

en/docs/install-and-setup/setup/mi-setup/observability/observability-deployment-strategy.md
en/docs/install-and-setup/setup/mi-setup/observability/setting-up-classic-observability-deployment.md
en/docs/install-and-setup/setup/mi-setup/observability/setting-up-cloud-native-observability-in-kubernetes.md
en/docs/install-and-setup/setup/mi-setup/observability/setting-up-minimum-basic-observability-deployment.md
en/docs/install-and-setup/setup/mi-setup/performance_tuning/http_transport_tuning.md
en/docs/install-and-setup/setup/mi-setup/performance_tuning/jdbc_tuning.md

Correct broken links in MI Observability Setup documentation

---

en/docs/install-and-setup/setup/mi-setup/changing_default_ports.md
en/docs/install-and-setup/setup/mi-setup/dynamic_server_configurations.md

Correct broken links in MI User Stores documentation

---

en/docs/install-and-setup/setup/mi-setup/databases/setting-up-IBM-DB2.md
en/docs/install-and-setup/setup/mi-setup/databases/setting-up-MSSQL.md
en/docs/install-and-setup/setup/mi-setup/databases/setting-up-MySQL.md
en/docs/install-and-setup/setup/mi-setup/databases/setting-up-Oracle.md
en/docs/install-and-setup/setup/mi-setup/databases/setting-up-PostgreSQL.md

Correct broken links in MI Databases documentation

---

en/docs/administer/key-managers/configure-wso2is-connector.md
en/docs/install-and-setup/setup/reference/product-compatibility.md

Update doc with WSO2 IS version and download link
Fixes https://github.com/wso2/docs-apim/issues/3334

Include the compatible IS product version for External-KM documentation - A400

---

en/docs/assets/css/theme.css

Fixed responsive issues with the right-hand side menu.
and porting https://github.com/wso2/docs-apim/pull/3016 to master

Fixing styling issues with the right hand navigation

---

en/docs/reference/mediators/about-mediators.md
en/docs/reference/mediators/class-mediator.md
en/docs/reference/mediators/data-mapper-mediator.md
en/docs/reference/mediators/db-report-mediator.md
en/docs/reference/mediators/dblookup-mediator.md
en/docs/reference/mediators/enrich-mediator.md
en/docs/reference/mediators/fault-mediator.md
en/docs/reference/mediators/foreach-mediator.md
en/docs/reference/mediators/iterate-mediator.md
en/docs/reference/mediators/script-mediator.md
en/docs/reference/mediators/send-mediator.md
en/docs/reference/mediators/smooks-mediator.md
en/docs/reference/mediators/urlrewrite-mediator.md
en/docs/reference/mediators/xslt-mediator.md

removed WSO2 EI, EI, and WSO2 Enterprise Integrator from descriptions in the 'Synapse Parameters' and 'Mediators' sections.

Fixing the tone - Synapse Parameters/Mediators sections

---

en/docs/integrate/integration-overview.md

Minor copy edits.
Added icons for the Get Started section.

integration overview - minor updates

---

en/docs/consume/consume-api-overview.md

First draft of Consume overview

consume overview draft

---

en/docs/install-and-setup/setup/mi-setup/deployment/deployment_synchronization.md
en/docs/install-and-setup/setup/mi-setup/deployment/kubernetes_deployment.md
en/docs/install-and-setup/setup/mi-setup/deployment/kubernetes_deployment_patterns.md
en/docs/install-and-setup/setup/mi-setup/deployment/migrating-from-ei-6.x.x.md

Remove files with formatting issues

---

en/docs/install-and-setup/setup/mi-setup/deployment/deployment_synchronization.md
en/docs/install-and-setup/setup/mi-setup/deployment/kubernetes_deployment.md
en/docs/install-and-setup/setup/mi-setup/deployment/kubernetes_deployment_patterns.md
en/docs/install-and-setup/setup/mi-setup/deployment/migrating-from-ei-6.x.x.md

Revert "Remove files with formatting issues"

---

en/docs/install-and-setup/setup/mi-setup/deployment/migrating-from-esb-5.x.x.md
en/docs/install-and-setup/setup/mi-setup/deployment/setting_up_lb.md
en/docs/install-and-setup/setup/mi-setup/deployment/troubleshooting_deployment.md

Correct broken links in Migration documentation

---

en/docs/deploy-and-publish/deploy-on-gateway/api-microgateway/getting-started/quick-start-guide/quick-start-guide-docker.md
en/docs/deploy-and-publish/deploy-on-gateway/api-microgateway/security/generate-a-test-jwt.md
en/mkdocs.yml

Add documentation related to https://github.com/wso2/product-microgateway/issues/1671

Add test jwt generation docs for mgw

---

en/docs/reference/connectors/amazons3-connector/1.x/amazons3-connector-1.x-example.md
en/docs/reference/connectors/deploy-capp.md
en/docs/reference/connectors/file-connector/3.x/file-connector-3.x-example.md

Change section title

---

en/docs/install-and-setup/setup/mi-setup/brokers/configure-with-IBM-websphereMQ.md
en/docs/install-and-setup/setup/mi-setup/message_builders_formatters/message-builders-and-formatters.md
en/docs/install-and-setup/setup/mi-setup/message_builders_formatters/message-relay.md
en/mkdocs.yml

Add missing Image text and update navigator

---

en/docs/install-and-setup/upgrading-wso2-is-as-key-manager/upgrading-from-is-5100-to-is-5110.md
en/docs/install-and-setup/upgrading-wso2-is-as-key-manager/upgrading-from-is-km-500-to-is-5110.md
en/docs/install-and-setup/upgrading-wso2-is-as-key-manager/upgrading-from-is-km-510-to-is-5110.md
en/docs/install-and-setup/upgrading-wso2-is-as-key-manager/upgrading-from-is-km-5100-to-is-5110.md
en/docs/install-and-setup/upgrading-wso2-is-as-key-manager/upgrading-from-is-km-520-to-is-5110.md
en/docs/install-and-setup/upgrading-wso2-is-as-key-manager/upgrading-from-is-km-530-to-is-5110.md
en/docs/install-and-setup/upgrading-wso2-is-as-key-manager/upgrading-from-is-km-550-to-is-5110.md
en/docs/install-and-setup/upgrading-wso2-is-as-key-manager/upgrading-from-is-km-560-to-is-5110.md
en/docs/install-and-setup/upgrading-wso2-is-as-key-manager/upgrading-from-is-km-570-to-is-5110.md
en/docs/install-and-setup/upgrading-wso2-is-as-key-manager/upgrading-from-is-km-590-to-is-5110.md

Adding deployment architecture note for iskm.

Added deployment architecture note for is km docs.

---

en/docs/develop/product-apis/devportal-apis/devportal-v1/devportal-v1.yaml

Remove dev-portal self-signup api related details from apim 3.0.0 documentatio

---

en/docs/install-and-setup/setup/kubernetes-operators/k8s-api-operator/manage-integration/integration-deployments.md
en/docs/install-and-setup/setup/kubernetes-operators/k8s-api-operator/manage-integration/integration-samples/content-based-routing.md
en/docs/install-and-setup/setup/kubernetes-operators/k8s-api-operator/manage-integration/integration-samples/hello-world.md
en/docs/install-and-setup/setup/kubernetes-operators/k8s-api-operator/manage-integration/integration-samples/jms-sender-receiver.md
en/docs/install-and-setup/setup/mi-setup/brokers/configure-with-rabbitmq.md
en/docs/install-and-setup/setup/mi-setup/deployment/deployment_checklist.md
en/docs/install-and-setup/setup/mi-setup/deployment/kubernetes_deployment.md
en/docs/install-and-setup/setup/mi-setup/deployment/migrating-from-ei-6.x.x.md
en/docs/install-and-setup/setup/mi-setup/performance_tuning/jms_transport_tuning.md
en/docs/install-and-setup/setup/mi-setup/performance_tuning/tuning-inbound-endpoints.md
en/docs/install-and-setup/setup/mi-setup/performance_tuning/tuning-the-VFS-Transport.md
en/docs/install-and-setup/setup/mi-setup/pull/PULL-CONTENT-migration-esb-mi.md
en/docs/install-and-setup/setup/mi-setup/user_stores/setting_up_a_userstore.md
en/docs/integrate/develop/create-integration-project.md
en/docs/integrate/develop/intro-integration-development.md
en/docs/reference/config-catalog-mi.md
en/docs/reference/mi-security-reference/using_keystores.md
en/tools/config-catalog-generator-mi/data/configs.json
en/tools/config-catalog-generator-mi/dist/config-catalog-mi.md

Correct broken links in Performance Tuning and Kubernetes Operator documentation

---

en/docs/deploy-and-publish/deploy-on-gateway/api-gateway/passing-enduser-attributes-to-the-backend-via-api-gateway.md
en/docs/deploy-and-publish/deploy-on-gateway/api-microgateway/passing-enduser-attributes-to-the-backend-via-api-microgateway.md
en/mkdocs.yml

fixes https://github.com/wso2/docs-apim/issues/3395

fixes https://github.com/wso2/docs-apim/issues/3395

---

en/docs/deploy-and-publish/deploy-on-gateway/deploy-api/exposing-apis-via-custom-hostnames.md
en/docs/get-started/about-this-release.md

fixes https://github.com/wso2/docs-apim/issues/3397
Adding this feature doc back as is has been deleted by someone accidently.
https://github.com/wso2/docs-apim/pull/3245

fixes https://github.com/wso2/docs-apim/issues/3397

---

en/docs/reference/mediators/payloadfactory-mediator.md

Adding handle missing values example to FreeMarker PayloadFactory
https://github.com/wso2/micro-integrator/issues/2124
https://github.com/wso2/micro-integrator/issues/2122

Adding handle missing values example to FreeMarker PayloadFactory

---

en/docs/deploy-and-publish/deploy-on-gateway/deploy-api/exposing-apis-via-custom-hostnames.md
en/docs/includes/deploy/assign-custom-hostname.md

fixing broken links exposing-apis-via-custom-hostnames.md as warning messages appear in this regard
https://github.com/wso2/docs-apim/pull/3245

fixing broken links exposing-apis-via-custom-hostnames.md

---

en/docs/install-and-setup/setup/kubernetes-operators/k8s-api-operator/manage-integration/integration-deployments.md

Update the documentation and instructions with the new features added to K8s operator by PR [1]. 
[1]. https://github.com/wso2/k8s-api-operator/pull/575

Update K8s operator doc with new features

---

en/docs/install-and-setup/setup/api-controller/managing-apis-in-kubernetes/managing-apis-in-kubernetes.md
en/docs/install-and-setup/setup/api-controller/managing-apis-in-kubernetes/resources/kustomization.yaml
en/docs/install-and-setup/setup/api-controller/managing-apis-in-kubernetes/resources/kustomize-config.yaml
en/mkdocs.yml

- This PR introduces the commands for API add, delete, update and generate deployment directory for Kubernetes.
- This PR is related to:
1. https://github.com/wso2/k8s-api-operator/pull/561
2. https://github.com/wso2/k8s-api-operator/pull/503
3. https://github.com/wso2/product-apim-tooling/pull/622

Introduce the commands for API add, delete, update and generate deployment directory for Kubernetes

---

en/docs/deploy-and-publish/deploy-on-gateway/api-microgateway/support-custom-claims-mapping.md

> This PR will add documantation for custom claim mapping in microgateway.
Related issue: wso2/product-microgateway#1627

Add doumnetation for custom claim mapping in microgateway.

---

en/docs/assets/css/theme.css
en/docs/index.md
en/docs/integrate/integration-overview.md

Resolves https://github.com/wso2/docs-apim/issues/3414 …

Fixes https://github.com/wso2/docs-apim/issues/3414

---

en/docs/integrate/integration-overview.md

Updating the 'Integration Overview' after the UX update in https://github.com/wso2/docs-apim/pull/3415.

integrate overview UI update

---

en/docs/consume/consume-api-overview.md
en/mkdocs.yml

Updated overview page for the Consume API section.

Consume APIs overview

---

en/theme/material/base.html

remove google indexng temporarily

---

en/mkdocs.yml

fixing base path

---

en/docs/install-and-setup/upgrading-wso2-api-manager/upgrading-from-200-to-400.md
en/docs/install-and-setup/upgrading-wso2-api-manager/upgrading-from-210-to-400.md
en/docs/install-and-setup/upgrading-wso2-api-manager/upgrading-from-220-to-400.md
en/docs/install-and-setup/upgrading-wso2-api-manager/upgrading-from-250-to-400.md
en/docs/install-and-setup/upgrading-wso2-api-manager/upgrading-from-260-to-400.md
en/docs/install-and-setup/upgrading-wso2-api-manager/upgrading-from-300-to-400.md
en/docs/install-and-setup/upgrading-wso2-api-manager/upgrading-from-310-to-400.md
en/docs/install-and-setup/upgrading-wso2-api-manager/upgrading-from-320-to-400.md

> Fix db scripts with the latest fixes.
Add special notes/steps.

migration document improvements

---

en/mkdocs.yml

fixed site_url

---

en/docs/assets/versions.json

change next to 4.0.0-dev

---

en/docs/assets/css/theme.css

Fix card width
> Link(s) to product documentation that addresses the changes of this PR. If no doc impact, enter “N/A” plus …

Fix card width

---

en/docs/install-and-setup/setup/mi-setup/brokers/configure-with-hornetq.md
en/docs/install-and-setup/setup/mi-setup/brokers/configure-with-jbossmq.md
en/docs/install-and-setup/setup/mi-setup/brokers/configure-with-rabbitmq.md
en/docs/install-and-setup/setup/mi-setup/brokers/configure-with-swiftmq.md
en/docs/install-and-setup/setup/mi-setup/deployment/deployment_checklist.md
en/docs/install-and-setup/setup/mi-setup/deployment/deployment_synchronization.md
en/docs/install-and-setup/setup/mi-setup/deployment/kubernetes_deployment.md
en/docs/install-and-setup/setup/mi-setup/deployment/kubernetes_deployment_patterns.md
en/docs/install-and-setup/setup/mi-setup/deployment/migrating-from-ei-6.x.x.md

Correct links in Message Broker documentation

---

en/docs/integrate/examples/endpoint_examples/using-websocket-endpoints.md
en/docs/integrate/examples/file-processing/accessing_windows_share_using_vfs_transport.md
en/docs/integrate/examples/file-processing/mailto-transport-examples.md
en/docs/integrate/examples/hl7-examples/acknowledge_hl7_messages.md
en/docs/integrate/examples/hl7-examples/file_transfer_using_hl7.md
en/docs/integrate/examples/hl7-examples/hl7_proxy_service.md
en/docs/integrate/examples/protocol-switching/switching_from_fix_to_amqp.md
en/docs/integrate/examples/protocol-switching/switching_from_fix_to_http.md
en/docs/integrate/examples/protocol-switching/switching_from_ftp_listener_to_mail_sender.md
en/docs/integrate/examples/protocol-switching/switching_from_http_to_fix.md
en/docs/integrate/examples/protocol-switching/switching_from_https_to_jms.md
en/docs/integrate/examples/protocol-switching/switching_from_tcp_to_https.md
en/docs/integrate/examples/protocol-switching/switching_from_udp_to_https.md
en/docs/integrate/examples/proxy_service_examples/securing-proxy-services.md
en/docs/integrate/examples/transport_examples/fix-transport-examples.md
en/docs/integrate/examples/transport_examples/tcp-transport-examples.md
en/docs/reference/config-catalog-mi.md
en/docs/tutorials/integration-tutorials/file-processing.md
en/tools/config-catalog-generator-mi/dist/config-catalog-mi.md

Correct links in MI Example documentation

---

en/docs/install-and-setup/setup/security/logins-and-passwords/working-with-encrypted-passwords.md

fixes https://github.com/wso2/docs-apim/issues/3451

fixes https://github.com/wso2/docs-apim/issues/3451

---

en/docs/design/create-api/create-streaming-api/create-a-sse-streaming-api.md
en/docs/design/create-api/create-streaming-api/create-a-websocket-streaming-api.md
en/docs/design/create-api/create-streaming-api/create-a-websub-streaming-api.md
en/docs/tutorials/create-and-publish-websocket-api.md
en/docs/tutorials/streaming-api/create-and-publish-sse-api.md
en/docs/tutorials/streaming-api/create-and-publish-websocket-api.md
en/docs/tutorials/streaming-api/create-and-publish-websub-api.md

Add introduction for streaming apis

---

en/docs/reference/connectors/kafka-connector/setting-up-kafka.md

$subject
Fixes https://github.com/wso2/docs-apim/issues/3403

Update kafka versions and links

---

en/docs/integrate/integration-overview.md
en/docs/streaming/streaming-overview.md

intagration and streaming overview icons

---

en/docs/reference/product-apis/devportal-apis/devportal-v2/devportal-v2.yaml

This PR updates devportal REST API docs. …

Update Devportal REST API Docs

---

en/docs/install-and-setup/setup/mi-setup/observability/observability.md
en/docs/integrate/examples/json_examples/json-examples.md
en/docs/integrate/examples/rest_api_examples/securing-rest-apis.md
en/docs/reference/customize-product/customizations/customizing-login-pages-for-dev-portal-and-publisher.md
en/docs/reference/customize-product/customizations/customizing-the-developer-portal/enabling-or-disabling-self-signup.md
en/docs/reference/customize-product/customizations/customizing-user-signup-in-developer-portal.md
en/docs/reference/mi-security-reference/using_keystores.md
en/tools/config-catalog-generator-mi/dist/config-catalog-mi.md

Correct broken links in Reference documentation and MI samples

---

en/docs/install-and-setup/setup/security/logins-and-passwords/working-with-encrypted-passwords.md

fixes https://github.com/wso2/docs-apim/pull/3457

fixes https://github.com/wso2/docs-apim/pull/3457

---

en/docs/administer/key-managers/configure-wso2is-connector.md
en/docs/install-and-setup/setup/reference/product-compatibility.md

Sync PR for https://github.com/wso2/docs-apim/pull/3364

Include the compatible IS product version for External-KM documentation

---

en/docs/design/rate-limiting/adding-new-throttling-policies.md

fixes https://github.com/wso2/docs-apim/issues/3467

fixes https://github.com/wso2/docs-apim/issues/3467

---

en/docs/reference/product-apis/publisher-apis/publisher-v2/publisher-v2.yaml

This PR updates publisher REST API docs

Update Publisher Rest API docs

---

en/docs/reference/connectors/ldap-connector/ldap-server-configuration.md

Fix syntax error

---

en/docs/reference/connectors/ISO8583-connector/ISO8583-inbound-endpoint-example.md

Fix syntax issue

---

en/docs/assets/css/theme.css

Fixes: https://github.com/wso2/docs-apim/issues/3471 …

Fix link and navigation issue

---

en/docs/reference/guides/message-flow-in-the-api-manager-gateway.md

Correct link by moving incorrectly placed bracket

---

en/docs/reference/product-apis/gateway-apis/gateway-v1/gateway-v1.md
en/docs/reference/product-apis/overview.md

Fix Gateway REST APIs

---

en/docs/reference/product-apis/admin-apis/admin-v2/admin-v2.yaml

Updated the admin REST API to the latest in the master.

Updated the admin REST API to latest

---

en/docs/reference/product-apis/gateway-apis/gateway-v1/gateway-v1.yaml

Updated the swagger of gateway rest API to the latest.

Updated the gateway api

---

en/docs/install-and-setup/setup/security/logins-and-passwords/maintaining-logins-and-passwords.md

Docs for Issue : https://github.com/wso2/product-apim/issues/10153

Adding reserved user docs for email login

---

en/docs/design/create-api/test-a-rest-api.md

fixes a formatting issue
https://github.com/wso2/docs-apim/pull/3461

fixes a formatting issue

---

en/docs/deploy-and-publish/deploy-on-gateway/api-microgateway/security/api-authentication/secure-apis-using-oauth2.0-access-tokens/secure-apis-using-jwt-self-contained-jwt.md

Update jwt validation doc

---

en/docs/deploy-and-publish/deploy-on-gateway/api-microgateway/getting-started/quick-start-guide/quick-start-guide-kubernetes.md

$subject
fix https://github.com/wso2/k8s-api-operator/issues/565
https://github.com/wso2/docs-apim/pull/3240

Update API Operator version as 200-beta in QSG

---

en/docs/install-and-setup/setup/mi-setup/observability/observability-with-grafana-overview.md
en/docs/install-and-setup/setup/mi-setup/observability/setting-up-cloud-native-observability-in-kubernetes.md
en/docs/install-and-setup/upgrading-wso2-si/migrating-from-stream-processor.md
en/docs/integrate/develop/using-remote-micro-integrator.md
en/docs/observe/mi-observe/cloud-native-observability-dashboards.md
en/docs/observe/mi-observe/mi-observability-overview.md
en/docs/observe/mi-observe/using-the-analytics-dashboard.md
en/docs/reference/connectors/mongodb-connector/mongodb-connector-example.md
en/docs/reference/connectors/salesforce-soap-connector/sf-soap-connector-config.md
en/docs/reference/wso2-admin-services.md
en/docs/troubleshooting/error-handling.md

Updating instances of Enterprise Integrator/WSO2 EI

Update tone integration docs - 3

---

en/docs/install-and-setup/setup/reference/common-runtime-and-configuration-artifacts.md

This PR adds userstores directory as an optional artifact to share.
Related to https://github.com/wso2/docs-apim/issues/1556

Add userstores directory as an optional artifact to share

---

en/docs/install-and-setup/setup/reference/common-runtime-and-configuration-artifacts.md

This PR adds userstores directory as an optional artifact to share.
Related to https://github.com/wso2/docs-apim/issues/1556

[3.2.0] Add userstores directory as an optional artifact to share

---

en/docs/deploy-and-publish/deploy-on-gateway/api-microgateway/concepts/apim-as-control-plane.md
en/docs/deploy-and-publish/deploy-on-gateway/api-microgateway/concepts/event-hub-subscription-validation.md
en/docs/deploy-and-publish/deploy-on-gateway/api-microgateway/configurations/adapter-configurations.md
en/docs/deploy-and-publish/deploy-on-gateway/api-microgateway/configurations/configuration-overview.md
en/docs/deploy-and-publish/deploy-on-gateway/api-microgateway/configurations/configure-log4j.md
en/docs/deploy-and-publish/deploy-on-gateway/api-microgateway/configurations/control-plane-configurations.md
en/docs/deploy-and-publish/deploy-on-gateway/api-microgateway/configurations/enforcer-configurations.md
en/docs/deploy-and-publish/deploy-on-gateway/api-microgateway/configurations/router-configurations.md
en/docs/deploy-and-publish/deploy-on-gateway/api-microgateway/configurations/security-configurations.md
en/mkdocs.yml

Add docs for Adapter, Enforcer, Router, Security configuration in Choreo Connect

Adding configuration docs

---

en/docs/design/rate-limiting/adding-new-throttling-policies.md
en/docs/includes/design/create-streaming-api/create-a-streaming-api-from-an-asyncapi-definition.md
en/docs/includes/design/create-streaming-api/create-a-websocket-streaming-api.md
en/docs/includes/design/create-streaming-api/test-a-websub-api.md
en/docs/tutorials/streaming-api/create-and-publish-websub-api.md

fixes https://github.com/wso2/docs-apim/issues/3510
fixed broken links

fixes https://github.com/wso2/docs-apim/issues/3510

---

en/docs/administer/logging-and-monitoring/monitoring/monitoring-with-opentracing.md

Jaeger tracing documentation updates

---

en/docs/install-and-setup/upgrading-wso2-api-manager/upgrading-from-200-to-400.md
en/docs/install-and-setup/upgrading-wso2-api-manager/upgrading-from-210-to-400.md
en/docs/install-and-setup/upgrading-wso2-api-manager/upgrading-from-220-to-400.md
en/docs/install-and-setup/upgrading-wso2-api-manager/upgrading-from-250-to-400.md
en/docs/install-and-setup/upgrading-wso2-api-manager/upgrading-from-260-to-400.md
en/docs/install-and-setup/upgrading-wso2-api-manager/upgrading-from-300-to-400.md
en/docs/install-and-setup/upgrading-wso2-api-manager/upgrading-from-310-to-400.md
en/docs/install-and-setup/upgrading-wso2-api-manager/upgrading-from-320-to-400.md
en/mkdocs.yml

migration script fixes and content improvements

Migration docs improvements

---

en/docs/deploy-and-publish/deploy-on-gateway/choreo-connect/deploy-api/deploy-api-to-choreo-connect.md
en/docs/deploy-and-publish/deploy-on-gateway/choreo-connect/getting-started/quick-start-guide/quick-start-guide-docker-with-apim.md
en/docs/deploy-and-publish/deploy-on-gateway/choreo-connect/getting-started/quick-start-guide/quick-start-guide-docker.md
en/docs/deploy-and-publish/deploy-on-gateway/choreo-connect/getting-started/quick-start-guide/quick-start-guide-kubernetes.md

Update the documentation with new directory structure

---

en/docs/deploy-and-publish/deploy-on-gateway/choreo-connect/configurations/adapter-configurations.md
en/docs/deploy-and-publish/deploy-on-gateway/choreo-connect/configurations/configuration-overview.md
en/docs/deploy-and-publish/deploy-on-gateway/choreo-connect/configurations/configure-log4j.md
en/docs/deploy-and-publish/deploy-on-gateway/choreo-connect/configurations/control-plane-configurations.md
en/docs/deploy-and-publish/deploy-on-gateway/choreo-connect/configurations/enforcer-configurations.md
en/docs/deploy-and-publish/deploy-on-gateway/choreo-connect/configurations/router-configurations.md
en/docs/deploy-and-publish/deploy-on-gateway/choreo-connect/configurations/security-configurations.md
en/docs/deploy-and-publish/deploy-on-gateway/choreo-connect/passing-enduser-attributes-to-the-backend-via-choreo-connect.md
en/docs/deploy-and-publish/deploy-on-gateway/choreo-connect/security/api-authentication/secure-apis-using-oauth2.0-access-tokens/secure-apis-using-jwt-self-contained-jwt.md

* Update the new directory structure …

Update the Choreo Connect configuration docs

---

en/docs/includes/design/create-streaming-api/test-a-websub-api.md

fixing a broken link

---

en/mkdocs.yml

adding test content

---

en/docs/includes/design/create-streaming-api/create-a-websocket-streaming-api.md
en/docs/includes/design/create-streaming-api/test-a-websub-api.md

fixing links

---

en/docs/install-and-setup/upgrading-wso2-api-manager/upgrading-from-200-to-400.md
en/docs/install-and-setup/upgrading-wso2-api-manager/upgrading-from-210-to-400.md
en/docs/install-and-setup/upgrading-wso2-api-manager/upgrading-from-220-to-400.md
en/docs/install-and-setup/upgrading-wso2-api-manager/upgrading-from-250-to-400.md
en/docs/install-and-setup/upgrading-wso2-api-manager/upgrading-from-260-to-400.md
en/docs/install-and-setup/upgrading-wso2-api-manager/upgrading-from-300-to-400.md
en/docs/install-and-setup/upgrading-wso2-api-manager/upgrading-from-310-to-400.md
en/docs/install-and-setup/upgrading-wso2-api-manager/upgrading-from-320-to-400.md

Add newly added table into db scripts

migration doc fixes

---

en/docs/deploy-and-publish/deploy-on-gateway/choreo-connect/passing-enduser-attributes-to-the-backend-via-choreo-connect.md
en/docs/deploy-and-publish/deploy-on-gateway/choreo-connect/support-custom-claims-mapping.md

Fix broken links and custom claims documentation

---

en/mkdocs.yml

fixing base path link

---

en/docs/use-cases/streaming-tutorials/receiving-events-via-kafka-and-publishing-to-websocket.md

Added Receiving events via Kafka and Publishing to WebSocket tutorial

Receiving events via Kafka and Publishing to WebSocket

---

en/docs/reference/config-catalog.md
en/tools/config-catalog-generator/data/configs.json
en/tools/config-catalog-generator/dist/config-catalog.md

Adds the missing throttling configs to the config catalog.
Fixes https://github.com/wso2/docs-apim/issues/3540

[3.1.0] Add throttling configs to the config catalog

---

en/docs/includes/integration/PULL-CONTENT-migration-esb-mi.md
en/docs/includes/integration/PULL-CONTENT-registry-migration.md
en/docs/install-and-setup/setup/mi-setup/databases/setting-up-ibm-db2.md
en/docs/install-and-setup/setup/mi-setup/databases/setting-up-mssql.md
en/docs/install-and-setup/setup/mi-setup/databases/setting-up-mysql.md
en/docs/install-and-setup/setup/mi-setup/databases/setting-up-oracle.md
en/docs/install-and-setup/setup/mi-setup/databases/setting-up-postgresql.md
en/docs/install-and-setup/upgrading-from-wso2-ei/upgrading-from-ei-6.1.0.md
en/docs/install-and-setup/upgrading-from-wso2-ei/upgrading-from-ei-6.1.1.md
en/docs/install-and-setup/upgrading-from-wso2-ei/upgrading-from-ei-6.2.x.md
en/docs/install-and-setup/upgrading-from-wso2-ei/upgrading-from-ei-6.3.x.md
en/docs/install-and-setup/upgrading-from-wso2-ei/upgrading-from-ei-6.4.x.md
en/docs/install-and-setup/upgrading-from-wso2-ei/upgrading-from-ei-6.5.x.md
en/docs/install-and-setup/upgrading-from-wso2-ei/upgrading-from-ei-6.6.x.md
en/docs/install-and-setup/upgrading-from-wso2-ei/upgrading-from-esb-5.x.x.md

broken links from pulled pages.

broken links in pulled pages

---

en/docs/get-started/overview.md
en/docs/get-started/quick-start-guide/integration-qsg.md
en/docs/get-started/quick-start-guide/quick-start-guide.md
en/docs/get-started/quick-start-guide/streaming-qsg.md
en/docs/includes/design/create-streaming-api/streaming-api-overview.md
en/docs/includes/design/stream-more-links.md
en/docs/install-and-setup/install/installing-the-product/installing-si-in-vm.md
en/mkdocs.yml

- changed the order of links
- updated the installer command
- redirect for streaming test page
- fixed broken links #3556
- fixed broken links

Fixed broken links and updates

---

en/docs/learn/consume-api/discover-apis/search.md

remove unnecessary lne

---

en/docs/design/api-security/api-authentication/secure-apis-using-mutual-ssl.md
en/docs/install-and-setup/install/running-the-product.md

Resolves https://github.com/wso2/product-apim/issues/10067 & https://github.com/wso2/docs-apim/issues/3492
Adding a note related to SSL config reload in windows

Add windows related info for mtls

---

en/docs/tutorials/streaming-api/create-and-publish-sse-api.md

Update instruction to run sse server

---

en/docs/design/design-api-overview.md

Adds new overview for the design section.

Design overview

---

en/docs/get-started/about-this-release.md

Change the structure of the About this Release page based on feedback.

About release

---

en/docs/tutorials/streaming-api/create-and-publish-websocket-api.md

[Streaming API] Improve WebSocket Tutorial

---

en/docs/reference/mediators/property-mediator.md
en/docs/reference/mediators/property-reference/accessing-properties-with-xpath.md

This PR updates the Property Mediator documentation with the file scope support.
Related PR: https://github.com/wso2/wso2-synapse/pull/1746

[Micro Integrator] Update property mediator documentation on file scope support

---

en/docs/get-started/overview.md
en/docs/integrate/develop/working-with-service-catalog.md

copy edit and link update

---

en/docs/install-and-setup/setup/api-controller/advanced-topics/configuring-environment-specific-parameters.md
en/docs/install-and-setup/setup/api-controller/ci-cd-with-wso2-api-management.md
en/docs/install-and-setup/setup/api-controller/managing-apis-api-products/importing-apis-via-dev-first-approach.md
en/docs/install-and-setup/setup/api-controller/managing-apis-api-products/managing-apis-and-api-products.md
en/docs/install-and-setup/setup/api-controller/managing-apis-api-products/migrating-api-products-to-different-environments.md
en/docs/install-and-setup/setup/api-controller/managing-apis-api-products/migrating-apis-to-different-environments.md

Fixes: https://github.com/wso2/product-apim-tooling/issues/679
Adding the examples for **deploymentVhost** for apictl params files and fix other minor issues.
- Added the examples for **deploymentVhost** for both APIs and API Products.
- Renamed **Production and Sandbox** to **Default** in apictl samples and examples.
- Removed unwanted properties from api.yaml examples

Adding examples with deploymentVhost for apictl and fix other minor issues

---

en/docs/observe/api-manager-analytics/overview-of-api-analytics.md

Fix bullet points

---

en/docs/get-started/about-this-release.md
en/docs/install-and-setup/install-and-setup-overview.md
en/docs/install-and-setup/install/installing-the-product/installing-the-product.md
en/docs/install-and-setup/install/running-the-product.md

Enhances About this Release content and Install section content.

Update About this Release and Install sections

---

en/docs/get-started/about-this-release.md

This PR updates the About this Release page with the startup script name change for both Windows and Linux/Mac OS.

Update About this Release page with script name change

---

en/mkdocs.yml

Updating the structure of the deployment docs in the yaml file.

Updating structure of deployment docs

---

en/docs/observe/api-manager-analytics/configure-analytics/configure-synapse-gateway.md

Update configs with prod URL

---

en/docs/install-and-setup/deploying-wso2-api-manager/distributed-deployment/product-profiles.md

Update description for --optimize option

---

en/docs/assets/css/theme.css
en/docs/integrate/integration-overview.md

Fixes: https://github.com/wso2/docs-apim/issues/3635
Fix image size and responsive
> Link(s) to product documentation that …

Fix image size

---

en/docs/assets/attachments/migration/micro-integrator/carbon.properties
en/docs/install-and-setup/upgrading-from-wso2-ei/upgrading-from-ei-6.1.0.md
en/docs/install-and-setup/upgrading-from-wso2-ei/upgrading-from-ei-6.1.1.md
en/docs/install-and-setup/upgrading-from-wso2-ei/upgrading-from-ei-6.2.x.md
en/docs/install-and-setup/upgrading-from-wso2-ei/upgrading-from-ei-6.3.x.md
en/docs/install-and-setup/upgrading-from-wso2-ei/upgrading-from-ei-6.4.x.md
en/docs/install-and-setup/upgrading-from-wso2-ei/upgrading-from-ei-6.5.x.md
en/docs/install-and-setup/upgrading-from-wso2-ei/upgrading-from-ei-6.6.x.md
en/docs/install-and-setup/upgrading-from-wso2-ei/upgrading-from-ei-7.0.x.md
en/docs/install-and-setup/upgrading-from-wso2-ei/upgrading-from-esb-5.x.x.md

Update Migrating Encrypted Passwords docs

---

en/docs/deploy-and-publish/deploy-on-gateway/choreo-connect/concepts/apim-as-control-plane.md
en/docs/deploy-and-publish/deploy-on-gateway/choreo-connect/concepts/event-hub.md
en/docs/deploy-and-publish/deploy-on-gateway/choreo-connect/configurations/adapter-configurations.md
en/docs/deploy-and-publish/deploy-on-gateway/choreo-connect/configurations/configuration-overview.md
en/docs/deploy-and-publish/deploy-on-gateway/choreo-connect/configurations/control-plane-configurations.md
en/docs/deploy-and-publish/deploy-on-gateway/choreo-connect/configurations/router-configurations.md
en/docs/deploy-and-publish/deploy-on-gateway/choreo-connect/security/generate-a-test-jwt.md

This PR to update the docs with new configuration changes in choreo connect
> Link to the PR for changes to the training content …

Update choreo-connect docs with configuration changes.

---

en/docs/reference/guides/message-flow-in-the-api-manager-gateway.md

fixing wrong link

---

en/docs/assets/css/theme.css

Fix hover animation

---

en/docs/administer/product-security/identity-management-for-the-api-dev-portal.md

Add a note on Disabling anonymous access to the Developer Portal Globally across tenants

---

en/docs/integrate/develop/working-with-service-catalog.md

sentence update

---

en/docs/tutorials/user-scenario.md

> Initial commit for the tutorial

Initial commit

---

en/docs/install-and-setup/setup/distributed-deployment/configure-apim-analytics/active-active.md

Fix a typo (copy/paste error from the Stream Processor documentation) to match the other configuration examples for API Analytics on this page.

fix: wrong shardId in example

---

en/docs/design/endpoints/endpoint-security/digest-auth.md
en/docs/design/endpoints/endpoint-security/oauth-2.0.md

Update endpoint security docs

---

en/docs/reference/connectors/file-connector/3.x/file-connector-3.x-config.md

Adding the private key configs

---

en/docs/tutorials/scenarios/scenario-overview.md
en/docs/tutorials/scenarios/scenario1-create-rest-api.md
en/docs/tutorials/scenarios/scenario10-notifications-webhooks.md
en/docs/tutorials/scenarios/scenario11-graphql.md
en/docs/tutorials/scenarios/scenario12- message-delivery.md
en/docs/tutorials/scenarios/scenario13-integrate-with-connectors.md
en/docs/tutorials/scenarios/scenario14-external-key-manager.md
en/docs/tutorials/scenarios/scenario2-access-control.md
en/docs/tutorials/scenarios/scenario3-implementing-an-api.md
en/docs/tutorials/scenarios/scenario4-user-signup-approval-flow.md
en/docs/tutorials/scenarios/scenario5-developer-community-feature.md
en/docs/tutorials/scenarios/scenario6-integrating-with-data-sources.md
en/docs/tutorials/scenarios/scenario7-analytics.md
en/docs/tutorials/scenarios/scenario8-rate-limiting.md
en/docs/tutorials/scenarios/scenario9-realtime-data.md
en/docs/tutorials/user-scenario.md
en/mkdocs.yml

Adding a new structure for tutorials.

Add tutorial structure

---

en/docs/install-and-setup/setup/deployment-best-practices/production-deployment-guidelines.md

Deployment guidelines doc revamped.

deployment guidelines

---

en/docs/design/advanced-topics/enabling-cors-for-apis.md
en/docs/install-and-setup/setup/security/logins-and-passwords/working-with-encrypted-passwords.md
en/docs/reference/customize-product/extending-api-manager/extending-gateway/customizing-api-template-for-gateway.md
en/docs/reference/customize-product/extending-api-manager/extending-gateway/writing-custom-handlers.md
en/mkdocs.yml

this pr fixes the docs to reflect the removal of synapse apis from the FS.
> Link(s) to product documentation that addresses …

fix for https://github.com/wso2/docs-apim/issues/3655 and other improvememts

---

en/docs/consume/invoke-apis/invoke-apis-using-tools/invoke-an-api-using-a-soap-client.md

Finalizing invoke-an-api-using-a-soap-client.md.

Further modifications to invoke-an-api-using-a-soap-client.md

---

en/docs/get-started/quick-start-guide/streaming-qsg.md

This PR fixes issues in content in the Streaming Quick Start Guide.

Fix content in Streaming QSG

---

en/docs/reference/apictl/wso2-api-controller.md

- Reference catalog added for the API controller

apictl command reference doc

---

en/docs/install-and-setup/setup/deployment-best-practices/basic-health-checks.md
en/mkdocs.yml

- Moved MI performance tuning content under best practices
- Minor structural updates

install and setup structure and minor edits

---

en/docs/deploy-and-publish/deploy-on-gateway/choreo-connect/security/api-authentication/secure-apis-using-oauth2.0-access-tokens/secure-apis-using-jwt-self-contained-jwt.md

Update https://apim.docs.wso2.com/en/4.0.0/deploy-and-publish/deploy-on-gateway/choreo-connect/security/api-authentication/secure-apis-using-oauth2.0-access-tokens/secure-apis-using-jwt-self-contained-jwt/
> Link(s) to product documentation that addresses the changes of this PR. If no …

Update CC JWT doc

---

en/docs/install-and-setup/setup/api-controller/getting-started-with-wso2-api-controller.md

Adding the artifacts for apictl 4.0.0 distributions to the 4.0.0 doc space.

Adding apictl 4.0.0 artifacts

---

en/docs/deploy-and-publish/deploy-on-gateway/choreo-connect/security/api-authentication/secure-apis-using-oauth2.0-access-tokens/secure-apis-using-jwt-self-contained-jwt.md
en/docs/deploy-and-publish/deploy-on-gateway/choreo-connect/security/importing-certificates-to-the-choreo-connect-truststore.md

update https://apim.docs.wso2.com/en/4.0.0/deploy-and-publish/deploy-on-gateway/choreo-connect/security/importing-certificates-to-the-choreo-connect-truststore/ …

Add import cert doc

---

en/docs/deploy-and-publish/deploy-on-gateway/choreo-connect/concepts/choreo-connect-with-tenants.md
en/docs/deploy-and-publish/deploy-on-gateway/choreo-connect/getting-started/supported-features.md
en/mkdocs.yml

> Add choreo connect features list and the tenant documentation. …

Add features and tenant docs for choreo connect

---

en/docs/index.md
en/docs/tutorials/scenarios/scenario-overview.md
en/docs/tutorials/scenarios/scenario14-external-key-manager.md
en/docs/tutorials/scenarios/scenario8-rate-limiting.md
en/docs/tutorials/tutorials-overview.md

Updates the landing page and other high-level pages with scenario tutorials.

Update landing page and high level pages

---

en/docs/index.md

Reducing the length of descriptions in the landing page to improve readability.

Shorten descriptions in landing page

---

en/docs/deploy-and-publish/deploy-on-gateway/choreo-connect/deploy-api/deploy-api-to-choreo-connect.md
en/docs/deploy-and-publish/deploy-on-gateway/choreo-connect/support-custom-claims-mapping.md
en/docs/includes/invoke-api-with-api-key.md
en/docs/includes/invoke-api-with-jwt.md
en/docs/includes/obtain-api-key.md
en/docs/includes/obtain-jwt.md

Update choreo connect docs

---

en/docs/design/create-api/create-api-revisions.md

Adds an introduction to the revision docs explaining the usecases and architectural changes.
Address https://github.com/wso2/docs-apim/issues/3755

Add an introduction to revision docs

---

en/docs/install-and-setup/setup/setting-up-databases/managing-data-growth-and-improving-performance.md
en/mkdocs.yml

Add Registry DB clean up scripts

---

en/docs/install-and-setup/setup/mi-setup/observability/setting-up-cloud-native-observability-in-kubernetes.md
en/docs/install-and-setup/setup/mi-setup/observability/setting-up-minimum-basic-observability-deployment.md

Sync PR for https://github.com/wso2/docs-ei/pull/2772

Jaeger tracing related info

---

en/docs/install-and-setup/install-and-setup-overview.md

install and setup overview

---

en/docs/integrate/integration-overview.md
en/docs/streaming/streaming-overview.md

- Updated the overview pages for INtegration and STreaming.

icons or Integration and Streaming landing pages

---

en/docs/tutorials/scenarios/scenario-overview.md
en/docs/tutorials/scenarios/scenario1-create-rest-api.md
en/docs/tutorials/scenarios/scenario10-notifications-webhooks.md
en/docs/tutorials/scenarios/scenario11-graphql.md
en/docs/tutorials/scenarios/scenario12-message-delivery.md
en/docs/tutorials/scenarios/scenario13-integrate-with-connectors.md
en/docs/tutorials/scenarios/scenario14-external-key-manager.md
en/docs/tutorials/scenarios/scenario2-access-control.md
en/docs/tutorials/scenarios/scenario3-implementing-an-api.md
en/docs/tutorials/scenarios/scenario4-user-signup-approval-flow.md
en/docs/tutorials/scenarios/scenario5-developer-community-feature.md
en/docs/tutorials/scenarios/scenario6-integrating-with-data-sources.md
en/docs/tutorials/scenarios/scenario7-analytics.md
en/docs/tutorials/scenarios/scenario8-rate-limiting.md
en/docs/tutorials/scenarios/scenario9-realtime-data.md

Add structural changes to the scenario tutorials and some minor fixes.

Add structure to tutorial pages

---

en/docs/observe/mi-observe/working-with-monitoring-dashboard.md
en/docs/reference/mediators/dss-mediator.md

dashboard doc updated

---

en/docs/deploy-and-publish/deploy-on-gateway/choreo-connect/service-discovery/choreo-connect-and-k8s.md

Updated Service discovery (Consul service discovery) for Choreo Connect - added description for k8s

---

en/docs/deploy-and-publish/deploy-on-gateway/choreo-connect/security/enabling-cors.md

- Remove unused docs for "Enabling CORS"
- Modified the doc for "Enabling CORS" …

Update enabling cors doc for choreo connect

---

en/docs/consume/discover-apis/search.md

This PR will remove info on doc: and subcontext: searches from API documentation.
_**References:**_
**Subcontext search** : https://github.com/wso2/product-apim/issues/10046 
This has been removed with https://github.com/wso2/carbon-apimgt/pull/9961/commits/44b2a6649692ff323e5d8bf607b53b75bf9681ed 
**Document search** : https://github.com/wso2/product-apim/issues/10855 
This has been removed with https://github.com/wso2/carbon-apimgt/pull/10306/files 
> Describe how you are implementing the solutions. Include an animated GIF or screenshot if the change affects the UI (email documentation@wso2.com to review all UI text). Include a link to a Markdown file or Google doc if the feature …

Remove info on doc: and subcontext: searches from API documentation

---

en/docs/install-and-setup/setup/api-controller/managing-apis-api-products/importing-apis-via-dev-first-approach.md
en/docs/install-and-setup/setup/api-controller/managing-apis-api-products/migrating-api-products-to-different-environments.md
en/docs/install-and-setup/setup/api-controller/managing-apis-api-products/migrating-apis-to-different-environments.md

Fixes https://github.com/wso2/docs-apim/issues/3807

Fix the error in command by removing the argument of rotate-revision flag

---

en/docs/get-started/about-this-release.md

About us page improvements.

---

en/docs/get-started/about-this-release.md

Reviewed and updated the About this Release Page

Review and Update the About this Release Page

---

en/docs/get-started/about-this-release.md

- Removed API CTL section based on discussion with Prasanna and Uvindra
- Updated MI and APIM fixed issue links.

Updated about this release page

---

en/docs/index.md

- Broken links and minor fixes in the landing page.

Fixing broken links in the landing page

---

en/docs/install-and-setup/setup/api-controller/advanced-topics/using-dynamic-data-in-api-controller-projects.md

Correcting the values for retryTimeOut and retryDelay for dynamic data in apictl docs

Exchange values for retryTimeOut and retryDelay for dynamic data in apictl docs

---

en/docs/get-started/about-this-release.md

Update about-this-release for API Operator

---

en/docs/install-and-setup/setup/reference/default-product-ports.md

default product ports

---

en/docs/get-started/about-this-release.md

updated APIM fixed issue link

---

en/docs/install-and-setup/setup/kubernetes-operators/k8s-api-operator/manage-apis/api-deployments.md
en/docs/install-and-setup/setup/kubernetes-operators/k8s-api-operator/manage-apis/api-samples/sample-1-target-endpoint.md
en/docs/install-and-setup/setup/kubernetes-operators/k8s-api-operator/manage-apis/api-samples/sample-2-deployment-params-and-certs.md
en/mkdocs.yml

$subject
fix https://github.com/wso2/docs-apim/issues/3800

Add samples for API Operator API deployments

---

en/docs/develop/extending-api-manager/extending-gateway/writing-custom-handlers.md

* Fix log4j config of the APILogMessageHandler in [1]
[1] https://apim.docs.wso2.com/en/latest/develop/extending-api-manager/extending-gateway/writing-custom-handlers/#using-apilogmessagehandler …

correct APILogMessageHandler log level string

---

en/docs/deploy-and-publish/deploy-on-gateway/choreo-connect/security/rejecting-revoked-tokens.md

Revamp docs for rejecting-revoked-tokens in choreo-connect

---

en/docs/install-and-setup/upgrading-wso2-api-manager/upgrading-from-1100-to-400.md
en/docs/install-and-setup/upgrading-wso2-api-manager/upgrading-from-191-to-400.md

- Removed unwanted 3.2.0 references.

Removing unwanted 3.2.0 instances from API-M migration docs

---

en/docs/assets/css/theme.css
en/theme/material/partials/header.html

removing the WIP banner

---

en/mkdocs.yml

changing latest to 3.2.0

---

en/mkdocs.yml

4.0.0 to latest

---

en/theme/material/base.html

Add Google indexing because it was removed temporarily.

Add Google indexing

---

en/theme/material/base.html

updated Angolia search from WSO2 documentation side.

updated Angolia search

---

en/theme/material/base.html

Merge either this or https://github.com/wso2/docs-apim/pull/3843

Quick fix for algolia search index issue

---

en/theme/material/base.html

As per the comment in https://github.com/wso2/docs-apim/pull/3843
>  change only the facet filter from next to 4.0.0

Changing facetFilters to correct version

---

README.md

just a touch

---

en/docs/install-and-setup/setup/reference/product-compatibility.md

remove 3.2.0 instances

---

en/docs/administer/updating-wso2-api-manager.md
en/docs/install-and-setup/setup/mi-setup/updating-mi.md
en/docs/install-and-setup/setup/si-setup/updating-si.md
en/docs/install-and-setup/upgrading-from-wso2-ei/upgrading-from-ei-6.1.0.md
en/docs/install-and-setup/upgrading-from-wso2-ei/upgrading-from-ei-6.1.1.md
en/docs/install-and-setup/upgrading-from-wso2-ei/upgrading-from-ei-6.2.x.md
en/docs/install-and-setup/upgrading-from-wso2-ei/upgrading-from-ei-6.3.x.md
en/docs/install-and-setup/upgrading-from-wso2-ei/upgrading-from-ei-6.4.x.md
en/docs/install-and-setup/upgrading-from-wso2-ei/upgrading-from-ei-6.5.x.md
en/docs/install-and-setup/upgrading-from-wso2-ei/upgrading-from-ei-6.6.x.md
en/docs/install-and-setup/upgrading-from-wso2-ei/upgrading-from-ei-7.0.x.md
en/docs/install-and-setup/upgrading-from-wso2-ei/upgrading-from-ei-7.1.x.md
en/docs/install-and-setup/upgrading-from-wso2-ei/upgrading-from-esb-5.x.x.md
en/docs/reference/customize-product/extending-api-manager/extending-key-management/writing-custom-grant-types.md

Fix for the following :
- #3856 
- #3857 
- #3858 
- #3859 
- #3860 
- #3861

Remove WUM terms and replace with WSO2 Updates

---

en/docs/administer/updating-wso2-api-manager.md
en/docs/install-and-setup/setup/mi-setup/updating-mi.md
en/docs/install-and-setup/setup/si-setup/updating-si.md
en/docs/install-and-setup/upgrading-from-wso2-ei/upgrading-from-ei-6.1.0.md
en/docs/install-and-setup/upgrading-from-wso2-ei/upgrading-from-ei-6.1.1.md
en/docs/install-and-setup/upgrading-from-wso2-ei/upgrading-from-ei-6.2.x.md
en/docs/install-and-setup/upgrading-from-wso2-ei/upgrading-from-ei-6.3.x.md
en/docs/install-and-setup/upgrading-from-wso2-ei/upgrading-from-ei-6.4.x.md
en/docs/install-and-setup/upgrading-from-wso2-ei/upgrading-from-ei-6.5.x.md
en/docs/install-and-setup/upgrading-from-wso2-ei/upgrading-from-ei-6.6.x.md
en/docs/install-and-setup/upgrading-from-wso2-ei/upgrading-from-ei-7.0.x.md
en/docs/install-and-setup/upgrading-from-wso2-ei/upgrading-from-ei-7.1.x.md
en/docs/install-and-setup/upgrading-from-wso2-ei/upgrading-from-esb-5.x.x.md
en/docs/reference/customize-product/extending-api-manager/extending-key-management/writing-custom-grant-types.md

Sync PR for WUM terms and replace with WSO2 Updates

---

en/docs/get-started/about-this-release.md

Add refined content for SI
Add more context

Add improved about release content for SI

---

en/mkdocs.yml

changing 4.0.0 to 4.0.x

---

en/docs/get-started/about-this-release.md

Add new features for SI Tooling.

Add new features for SI Tooling

---

en/docs/install-and-setup/install/deploying-api-manager-with-kubernetes-or-openshift-resources.md

- WIP banner to the API-M to the Helm docs.

(4.0.0) WIP banner to the API-M to the Helm docs.

---

en/docs/install-and-setup/install/deploying-api-manager-with-kubernetes-or-openshift-resources.md

- Merging https://github.com/wso2/docs-apim/pull/3891 to mast branch.

(master branch) WIP banner to the API-M to the Helm docs

---

en/mkdocs.yml

Install and setup section redirects added

---

en/theme/material/partials/tabs.html
en/theme/material/templates/single-column.html

Fix JS error

---

en/docs/administer/key-managers/configure-wso2is-connector.md

Update WSO2 IS toml config 

---

en/mkdocs.yml

redirects for create API

---

en/docs/install-and-setup/upgrading-wso2-api-manager/upgrading-from-1100-to-320.md
en/docs/install-and-setup/upgrading-wso2-api-manager/upgrading-from-200-to-320.md
en/docs/install-and-setup/upgrading-wso2-api-manager/upgrading-from-210-to-320.md
en/docs/install-and-setup/upgrading-wso2-api-manager/upgrading-from-220-to-320.md
en/docs/install-and-setup/upgrading-wso2-api-manager/upgrading-from-250-to-320.md
en/docs/install-and-setup/upgrading-wso2-api-manager/upgrading-from-300-to-320.md
en/docs/install-and-setup/upgrading-wso2-api-manager/upgrading-from-310-to-320.md

Explaining the "re_indexing"config in the migration docs

---

en/mkdocs.yml

- link redirects in the Deploy and Publish section.

Link redirects 4.0.0

---

en/docs/install-and-setup/upgrading-wso2-api-manager/upgrading-from-1100-to-400.md
en/docs/install-and-setup/upgrading-wso2-api-manager/upgrading-from-200-to-400.md
en/docs/install-and-setup/upgrading-wso2-api-manager/upgrading-from-210-to-400.md
en/docs/install-and-setup/upgrading-wso2-api-manager/upgrading-from-220-to-400.md
en/docs/install-and-setup/upgrading-wso2-api-manager/upgrading-from-250-to-400.md
en/docs/install-and-setup/upgrading-wso2-api-manager/upgrading-from-260-to-400.md
en/docs/install-and-setup/upgrading-wso2-api-manager/upgrading-from-300-to-400.md
en/docs/install-and-setup/upgrading-wso2-api-manager/upgrading-from-310-to-400.md
en/docs/install-and-setup/upgrading-wso2-api-manager/upgrading-from-320-to-400.md

Explaining the "re_indexing"config in the migration docs 

---

en/mkdocs.yml

changes for 4.0.0 branch same done for master https://github.com/wso2/docs-apim/pull/3893

[4.0.0] Remove listing K8s AM Operator, without removing content

---

en/mkdocs.yml

Remove listing K8s AM Operator, without removing content

---

en/docs/observe/api-manager-analytics/configure-analytics/register-for-analytics.md
en/docs/tutorials/scenarios/scenario7-analytics.md

Add note regarding Choreo sign-up approval

---

README.md

Revert "just a touch"

---

en/docs/administer/product-configurations/common-runtime-and-configuration-artifacts.md
en/docs/install-and-setup/deploying-wso2-api-manager/distributed-deployment/distributed-deployment-of-the-gateway.md

Back-porting fix for https://github.com/wso2/docs-apim/issues/1453

[3.0.0] Define specific runtime artifact directories for persistence

---

en/mkdocs.yml

Link redirects tutorials 4.0.0

---

en/docs/google186eb945fa6366b0.html
en/theme/material/base.html

Experimental work to get the google indexing corrected

Google site

---

en/docs/integrate/develop/creating-artifacts/creating-an-api.md
en/docs/integrate/develop/working-with-service-catalog.md
en/docs/tutorials/integration-tutorials/service-catalog-tutorial.md

> Change service catalog parameter names.
Related to wso2/integration-studio/issues/785

Change service catalog param names.

---

en/mkdocs.yml

Adds latency page to mkdocs

---

en/docs/install-and-setup/setup/reference/product-compatibility.md

- Added MI and SI compatibility info to the API-M doc.

Compatibility Information Updated

---

en/docs/install-and-setup/install/deploying-api-manager-with-kubernetes-or-openshift-resources.md

This PR updates the docs for [Deploying API-M on Kubernetes using Helm Resources](https://apim.docs.wso2.com/en/4.0.0/install-and-setup/install/deploying-api-manager-with-kubernetes-or-openshift-resources/).

[4.0.0] Update docs for APIM on k8s

---

README.md
en/docs/develop/customizations/adding-a-user-signup-workflow-using-bps.md
en/docs/develop/customizations/customize-the-api-store-and-gateway-urls-for-tenants.md
en/docs/develop/customizations/customizing-login-pages-for-dev-portal-and-publisher.md
en/docs/develop/customizations/log-in-to-the-dev-portal-using-social-media.md
en/docs/install-and-setup/upgrading-wso2-api-manager/upgrading-from-1100-to-320.md
en/docs/install-and-setup/upgrading-wso2-api-manager/upgrading-from-200-to-320.md
en/docs/install-and-setup/upgrading-wso2-api-manager/upgrading-from-210-to-320.md
en/docs/install-and-setup/upgrading-wso2-api-manager/upgrading-from-220-to-320.md
en/docs/install-and-setup/upgrading-wso2-api-manager/upgrading-from-250-to-320.md
en/docs/install-and-setup/upgrading-wso2-api-manager/upgrading-from-260-to-320.md
en/docs/install-and-setup/upgrading-wso2-api-manager/upgrading-from-300-to-320.md
en/docs/learn/analytics/configuring-alerts.md
en/docs/learn/api-gateway/message-mediation/configuring-message-builders-formatters.md
en/docs/learn/api-gateway/message-mediation/transforming-api-message-payload.md
en/docs/learn/api-monetization/monetizing-an-api.md
en/docs/learn/api-security/api-authentication/secure-apis-using-basic-authentication.md
en/docs/learn/api-security/oauth2/grant-types/implicit-grant.md
en/docs/learn/consume-api/generating-sdks/write-a-client-application-using-the-sdk.md
en/docs/learn/design-api/advanced-topics/control-api-visibility-and-subscription-availability-in-developer-portal.md
en/docs/learn/design-api/api-documentation/add-api-documentation.md
en/docs/learn/design-api/create-api/test-a-rest-api.md
en/docs/learn/design-api/publish-api/publish-an-api-to-a-cloud-cluster-in-privatejet-mode.md
en/docs/learn/design-api/publish-api/publish-an-api.md
en/docs/reference/faq.md
en/docs/troubleshooting/error-handling.md

fixes https://github.com/wso2/docs-apim/issues/3952

fixed links

---

en/docs/learn/consume-api/generating-sdks/generate-sdks-in-dev-portal.md

Update the SDK documentation

---

en/docs/install-and-setup/setup/distributed-deployment/configuring-wso2-identity-server-as-a-key-manager.md

Update WSO2-IS key manager type

---

en/docs/assets/attachments/reference/admin-v2_postman_collection.json
en/docs/assets/attachments/reference/devportal-v2_postman_collection.json
en/docs/assets/attachments/reference/publisher-v2_postman_collection.json
en/docs/reference/product-apis/admin-apis/admin-v2/admin-v2.yaml
en/docs/reference/product-apis/devportal-apis/devportal-v2/devportal-v2.yaml
en/docs/reference/product-apis/overview.md
en/docs/reference/product-apis/publisher-apis/publisher-v2/publisher-v2.yaml
en/mkdocs.yml

This PR will,
* Add new REST APIs introduced with API-M 4.0.0 to publisher, devportal and admin redocly docs
* Update postman collections for  publisher, devportal and admin
* Add exported postman collection resources to doc assets
* Remove references to admin api v0.17 which is removed from 4.0.0
> Brief description of the new feature or bug fix as it will appear in the …

[4.0.0] Update 4.0.0 REST APIs

---

en/docs/install-and-setup/install/installing-the-product/running-the-mi-dashboard.md
en/docs/install-and-setup/install/installing-the-product/running-the-mi.md
en/docs/install-and-setup/install/installing-the-product/running-the-si.md
en/docs/observe/mi-observe/working-with-monitoring-dashboard.md

(4.0.0 branch) Dashboard corrections

---

en/docs/install-and-setup/install/installing-the-product/running-the-mi-dashboard.md

(4.0.0 branch) typo

---

en/docs/learn/api-controller/getting-started-with-wso2-api-controller.md

Adding the artifacts for apictl 3.2.2 distributions to the 3.2.0 doc space.

[3.2.0] Adding apictl 3.2.2 artifacts

---

en/docs/reference/connectors/kafka-connector/3.0.x/kafka-connector-config.md
en/docs/reference/connectors/kafka-connector/kafka-connector-avro-producer-example.md
en/docs/reference/connectors/kafka-connector/kafka-connector-overview.md
en/docs/reference/connectors/kafka-connector/setting-up-kafka.md
en/mkdocs.yml

$subject
Related PR: wso2-extensions/esb-connector-kafka#55

[Master] Update kafka-connector doc on Avro message support

---

en/docs/learn/api-controller/advanced-topics/using-dynamic-data-in-api-controller-projects.md
en/docs/learn/api-controller/getting-started-with-wso2-api-controller.md

Fixes related to https://github.com/wso2/product-apim-tooling/issues/503

[3.2.0]Add proxy support related docs for APICTL

---

en/docs/reference/connectors/kafka-connector/3.0.x/kafka-connector-config.md
en/docs/reference/connectors/kafka-connector/kafka-connector-avro-producer-example.md
en/docs/reference/connectors/kafka-connector/kafka-connector-overview.md
en/docs/reference/connectors/kafka-connector/setting-up-kafka.md
en/mkdocs.yml

$subject
Related PR: wso2-extensions/esb-connector-kafka#55

[4.0.0] Update kafka-connector doc on Avro message support

---

en/docs/index.md
en/docs/install-and-setup/install-and-setup-overview.md
en/docs/reference/connectors/kafka-connector/kafka-connector-avro-producer-example.md
en/mkdocs.yml

Merging https://github.com/wso2/docs-apim/pull/4018 to master.

(master branch)  broken links

---

en/docs/install-and-setup/setup/kubernetes-operators/k8s-api-operator/manage-integrations/integration-deployments.md

Broken links in Integration K8s section

(4.0.0 branch) broken links in integration k8s deployment

---

en/docs/observe/api-manager-analytics/analytics-pages/analytics-pages-devices.md
en/docs/observe/api-manager-analytics/analytics-pages/analytics-pages-introduction.md
en/docs/observe/api-manager-analytics/analytics-pages/analytics-pages-overview.md
en/docs/observe/api-manager-analytics/analytics-pages/analytics-pages-traffic.md
en/mkdocs.yml

Adds reports page to mkdocs and resize images

---

en/docs/administer/logging-and-monitoring/logging/setting-up-logging.md

Address https://github.com/wso2/docs-apim/issues/3997. The tenantDomain layout parameter has been added via a wum. 
Related git issue : wso2/product-apim#9498

Add the log layout pattern related docs for 3.2.0

---

en/docs/integrate/develop/creating-artifacts/creating-an-api.md
en/docs/integrate/develop/working-with-service-catalog.md
en/docs/tutorials/integration-tutorials/service-catalog-tutorial.md

Fixes https://github.com/wso2/docs-apim/issues/3945

(4.0.0 branch) Config catalog service catalog

---

en/docs/integrate/develop/creating-artifacts/creating-an-api.md
en/docs/integrate/develop/working-with-service-catalog.md
en/docs/tutorials/integration-tutorials/service-catalog-tutorial.md

Merging https://github.com/wso2/docs-apim/pull/4035 to master.

(master branch) Service catalog docs typos

---

en/docs/install-and-setup/setup/kubernetes-operators/k8s-api-operator/manage-integrations/integration-deployments.md
en/docs/integrate/develop/creating-artifacts/creating-an-api.md
en/docs/integrate/develop/working-with-service-catalog.md
en/docs/tutorials/integration-tutorials/service-catalog-tutorial.md

Merging https://github.com/wso2/docs-apim/pull/4023 to master.

(master branch) broken links in integration k8s deployment

---

en/docs/consume/manage-subscription/advanced-topics/adding-an-api-subscription-workflow.md

fix for https://github.com/wso2/docs-apim/issues/4040

fix for https://github.com/wso2/docs-apim/issues/4040

---

en/docs/install-and-setup/upgrading-wso2-api-manager/upgrading-from-200-to-400.md
en/docs/install-and-setup/upgrading-wso2-api-manager/upgrading-from-210-to-400.md
en/docs/install-and-setup/upgrading-wso2-api-manager/upgrading-from-220-to-400.md
en/docs/install-and-setup/upgrading-wso2-api-manager/upgrading-from-250-to-400.md
en/docs/install-and-setup/upgrading-wso2-api-manager/upgrading-from-260-to-400.md
en/docs/install-and-setup/upgrading-wso2-api-manager/upgrading-from-300-to-400.md
en/docs/install-and-setup/upgrading-wso2-api-manager/upgrading-from-310-to-400.md
en/docs/install-and-setup/upgrading-wso2-api-manager/upgrading-from-320-to-400.md

add analytics migration note for 4.0.0 docs

---

en/docs/install-and-setup/upgrading-wso2-api-manager/upgrading-from-200-to-400.md
en/docs/install-and-setup/upgrading-wso2-api-manager/upgrading-from-210-to-400.md
en/docs/install-and-setup/upgrading-wso2-api-manager/upgrading-from-220-to-400.md
en/docs/install-and-setup/upgrading-wso2-api-manager/upgrading-from-250-to-400.md
en/docs/install-and-setup/upgrading-wso2-api-manager/upgrading-from-260-to-400.md
en/docs/install-and-setup/upgrading-wso2-api-manager/upgrading-from-300-to-400.md
en/docs/install-and-setup/upgrading-wso2-api-manager/upgrading-from-310-to-400.md
en/docs/install-and-setup/upgrading-wso2-api-manager/upgrading-from-320-to-400.md

add analytics migration note

---

en/docs/learn/api-security/api-authentication/secure-apis-using-api-keys.md
en/docs/reference/config-catalog.md
en/tools/config-catalog-generator/data/configs.json
en/tools/config-catalog-generator/data/custom_keystore.toml
en/tools/config-catalog-generator/dist/config-catalog.md

Update Docs with Keystore Configs & API Key Keystore Configs

---

en/docs/google5db3f40334e06fa3.html

add google site verification for 3.2.0

add google site verification

---

en/docs/deploy-and-publish/deploy-on-gateway/choreo-connect/getting-started/choreo-connect-overview.md

fixes https://github.com/wso2/docs-apim/issues/4064

fixes https://github.com/wso2/docs-apim/issues/4064

---

en/docs/deploy-and-publish/deploy-on-gateway/choreo-connect/getting-started/choreo-connect-overview.md

updated based on review comments

updated based on review comments

---

en/docs/integrate/develop/customizations/creating-synapse-handlers.md

fixes https://github.com/wso2/docs-apim/issues/4068

fixes https://github.com/wso2/docs-apim/issues/4068

---

en/docs/install-and-setup/setup/distributed-deployment/understanding-the-distributed-deployment-of-wso2-api-m.md

Merging https://github.com/wso2/docs-apim/pull/3994/commits/30c431995967b4c5855838eb50987406372516ab

Minor update to Gateway profile description

---

en/docs/install-and-setup/setup/deployment-best-practices/security-guidelines-for-production-deployment.md

Created two separate sections for MI and API-M security guidelines [1].
[1] https://apim.docs.wso2.com/en/latest/install-and-setup/setup/deployment-best-practices/security-guidelines-for-production-deployment/

(4.0.0 doc) Updating the Security Guidelines documentation

---

en/docs/install-and-setup/install/installing-the-product/installing-mi-dashboard.md

MI dashboard configuration

---

en/docs/install-and-setup/setup/security/configuring-keystores/keystore-basics/creating-new-keystores.md

Using a certificate with wildcard CN

---

en/docs/install-and-setup/setup/mi-setup/deployment/deploying-micro-integrator-with-helm.md

> $subject for release 4.0.0.1

Adding mi helm resource doc

---

en/docs/tutorials/scenarios/scenario-overview.md
en/docs/tutorials/scenarios/scenario12-message-delivery.md
en/docs/tutorials/scenarios/scenario13-integrate-with-connectors.md
en/docs/tutorials/scenarios/scenario3-implementing-an-api.md

Revert "Add new changes related to scenario tutorial"

---

en/docs/install-and-setup/setup/mi-setup/deployment/kubernetes_deployment.md
en/mkdocs.yml

Improvements to PR: https://github.com/wso2/docs-apim/pull/3896

(4.0.0 branch) Updates to Helm docs for MI 

---

en/docs/install-and-setup/setup/api-controller/ci-cd-with-wso2-api-management.md

Removing the duplicate headings.

(4.0.0 branch) Fixing the heading

---

en/docs/install-and-setup/setup/api-controller/ci-cd-with-wso2-api-management.md

Related issue - https://github.com/wso2/docs-apim/issues/3932

(4.0.0 branch) Broken links 

---

en/docs/install-and-setup/setup/deployment-best-practices/changing-the-default-ports-with-offset.md

Related issue - https://github.com/wso2/docs-apim/issues/3956

(4.0.0 branch) broken links in ports section

---

en/docs/reference/apictl/wso2-api-controller.md

Fixing download link.
Related issue: https://github.com/wso2/docs-apim/issues/3989

(4.0.0 branch) download link of APICTL

---

en/docs/install-and-setup/setup/api-controller/ci-cd-with-wso2-api-management.md

Merging https://github.com/wso2/docs-apim/pull/4089 to Master

(Master branch) Broken links

---

en/docs/design/api-security/threat-protection/gateway-threat-protectors/gateway-threat-protectors-for-api-manager.md

- fixes https://github.com/wso2/docs-apim/issues/4108
- resized the images

fixes #4108

---

en/docs/administer/product-administration/removing-unused-tokens-from-the-database.md

Sync PR for #3771
Fixes https://github.com/wso2/docs-apim/issues/1210

[3.0.0] Add Registry DB clean up scripts

---

en/docs/deploy-and-publish/deploy-on-gateway/choreo-connect/concepts/inter-component-communication.md
en/docs/deploy-and-publish/deploy-on-gateway/choreo-connect/security/importing-certificates-to-the-choreo-connect-truststore.md
en/docs/deploy-and-publish/deploy-on-gateway/choreo-connect/security/transport-security.md
en/docs/get-started/about-this-release.md
en/mkdocs.yml

This PR,
1. Adds Choreo Connect to the About this Release page
2. Fix Choreo Connect Transport Security page
> Link(s) to …

[4.0.0] Add choreo connect to about this release page

---

en/docs/deploy-and-publish/deploy-on-gateway/choreo-connect/concepts/inter-component-communication.md
en/docs/deploy-and-publish/deploy-on-gateway/choreo-connect/security/importing-certificates-to-the-choreo-connect-truststore.md
en/docs/deploy-and-publish/deploy-on-gateway/choreo-connect/security/transport-security.md
en/docs/get-started/about-this-release.md
en/mkdocs.yml

This PR,
1. Adds Choreo Connect to the About this Release page
2. Fix Choreo Connect Transport Security page
> Link(s) to …

Add choreo connect to about this release page

---

en/docs/install-and-setup/setup/deployment-best-practices/changing-the-default-ports-with-offset.md
en/docs/install-and-setup/setup/reference/default-product-ports.md
en/docs/install-and-setup/setup/security/configuring-transport-level-security.md

Merging https://github.com/wso2/docs-apim/pull/4060 to Master.
fixes https://github.com/wso2/docs-apim/issues/3956

(Master branch) Updating the default ports documentation

---

en/docs/install-and-setup/setup/deployment-best-practices/security-guidelines-for-production-deployment.md

Merging https://github.com/wso2/docs-apim/pull/4052 to Master

(Master branch) Updating the Security Guidelines documentation

---

en/docs/install-and-setup/setup/mi-setup/deployment/deploying-micro-integrator-with-helm.md
en/docs/install-and-setup/setup/mi-setup/deployment/kubernetes_deployment.md
en/mkdocs.yml

Merge https://github.com/wso2/docs-apim/pull/4086 to Master.

(Master branch) Updates to Helm docs for MI

---

en/mkdocs.yml

Hide WIP pages 

---

en/docs/reference/apictl/wso2-api-controller.md

Merging https://github.com/wso2/docs-apim/pull/4099 to Master branch.

(Master branch) download link of APICTL

---

en/docs/api-analytics/architecture.md

fixes https://github.com/wso2/docs-apim/issues/4132

fixes https://github.com/wso2/docs-apim/issues/4132

---

en/docs/design/advanced-topics/enabling-cors-for-apis.md
en/docs/design/api-security/threat-protection/bot-detection.md

Fixed in the following :
- https://apim.docs.wso2.com/en/latest/design/api-security/threat-protection/bot-detection/
- https://apim.docs.wso2.com/en/latest/design/advanced-topics/enabling-cors-for-apis/#enabling-cors-for-apis

Image resize

---

en/docs/design/api-security/api-request-response-schema-validation/json-schema-validator.md

This PR fixes image sizes in json-schema-validator.md

Fix image sizes in json-schema-validator.md

---

en/docs/deploy-and-publish/deploy-on-gateway/choreo-connect/concepts/apim-as-control-plane.md

Update choreo connect control plane config

---

en/docs/api-analytics/configure-alerts.md

Apply review suggestions

---

en/docs/use-cases/streaming-usecase/summarizing-data.md

Add documentation for persisted aggregations

Add persisted aggregations document content

---

en/docs/includes/analytics/configure-synapse-gateway.md

fixes https://github.com/wso2/docs-apim/issues/4165

fixes #4165

---

en/docs/includes/analytics/configure-synapse-gateway.md

fixes https://github.com/wso2/docs-apim/issues/4165

fixes https://github.com/wso2/docs-apim/issues/4165

---

en/docs/administer/key-managers/configure-auth0-connector.md

Test purposes

---

en/docs/administer/key-managers/configure-auth0-connector.md

Revert "Test purposes"

---

en/docs/includes/analytics/configure-synapse-gateway.md

fixes https://github.com/wso2/docs-apim/pull/4173

fixes https://github.com/wso2/docs-apim/pull/4173

---

en/docs/includes/analytics/configure-synapse-gateway.md

fix for https://github.com/wso2/docs-apim/issues/4165

fix for https://github.com/wso2/docs-apim/issues/4165

---

en/docs/includes/analytics/configure-synapse-gateway.md

fixing link

---

en/docs/develop/streaming-apps/http-status-codes.md

fixed heading levels

---

en/docs/install-and-setup/setup/single-node/configuring-an-active-active-deployment.md

Changes in Active-Active Deployment Docs

---

en/docs/includes/deploy/assign-custom-hostname.md

Removed relative links in include pages and added absolute links as they were broken.

Fixed broken links

---

en/docs/develop/streaming-apps/installing-siddhi-extensions.md

fixes https://github.com/wso2/docs-apim/issues/4071

fixes https://github.com/wso2/docs-apim/issues/4071

---

en/docs/learn/api-gateway/response-caching.md

fixes https://github.com/wso2/docs-apim/issues/4207

fixes https://github.com/wso2/docs-apim/issues/4207

---

en/docs/deploy-and-publish/deploy-on-gateway/choreo-connect/concepts/event-hub.md
en/docs/deploy-and-publish/deploy-on-gateway/deploy-api/deploy-through-multiple-api-gateways.md
en/docs/deploy-and-publish/deploy-on-gateway/deploy-api/exposing-apis-via-custom-hostnames.md
en/docs/install-and-setup/setup/distributed-deployment/deploying-wso2-api-m-in-a-distributed-setup.md
en/docs/install-and-setup/setup/single-node/configuring-a-single-node.md

fixes https://github.com/wso2/docs-apim/issues/3560 partly

fixes https://github.com/wso2/docs-apim/issues/3560 partly

---

en/docs/design/api-monetization/monetizing-an-api.md

> Refactor monetization docs to improve the configuration experience.

Refactor monetization docs

---

en/docs/learn/api-monetization/monetizing-an-api.md

fixes https://github.com/wso2/docs-apim/issues/4170

fixes https://github.com/wso2/docs-apim/issues/4170

---

en/theme/material/partials/footer.html

4.0.0 - fixing the copyright statement

4.0.0 - fixing the copyright statement

---

en/theme/material/partials/footer.html

fixes https://github.com/wso2/docs-apim/issues/4221

fixes https://github.com/wso2/docs-apim/issues/4221

---

en/theme/material/partials/footer.html

Updating the copyrights in 3.2.0
fixed https://github.com/wso2/docs-apim/issues/4221

Updating the copyrights in 3.2.0

---

en/docs/administer/managing-users-and-roles/managing-users-for-admin-portal.md

fixing broken anchor

---

en/docs/deploy-and-publish/deploy-on-gateway/choreo-connect/troubleshooting/error-handling.md
en/mkdocs.yml

Add Choreo Connect Router error codes doc to troubleshooting guides.

Add CC error codes doc

---

en/docs/deploy-and-publish/deploy-on-gateway/choreo-connect/troubleshooting/adding-debug-logs.md
en/docs/deploy-and-publish/deploy-on-gateway/choreo-connect/troubleshooting/error-handling.md
en/mkdocs.yml

Add Choreo Connect troubleshooting guides.
- error codes are newly added.
- troubleshoot guide is moved from main branch.

Add CC troubleshoot docs

---

en/docs/assets/css/theme.css
en/theme/material/partials/footer.html

Fixing https://github.com/wso2/docs-apim/issues/4231

Fixing footer formating

---

en/tools/config-catalog-generator/data/server.toml

Remove node_ip configuration parameter under the server tag 

---

en/docs/reference/product-apis/admin-apis/admin-v2/admin-v2.yaml
en/docs/reference/product-apis/devportal-apis/devportal-v2/devportal-v2.yaml
en/docs/reference/product-apis/publisher-apis/publisher-v2/publisher-v2.yaml

Related 4.0.0 PR : https://github.com/wso2/docs-apim/pull/3970 …

Update Product API Definitions

---

en/docs/install-and-setup/setup/advance-configurations/configuring-caching.md

fixes https://github.com/wso2/docs-apim/issues/4159

fixes https://github.com/wso2/docs-apim/issues/4159

---

en/docs/api-analytics/architecture.md
en/docs/api-analytics/configure-alerts.md
en/docs/api-analytics/gateways/configure-synapse-gateway.md
en/docs/api-analytics/getting-started-guide.md
en/docs/api-analytics/role-based-access-control.md
en/docs/api-analytics/viewing/analytics-pages-alerts.md
en/docs/api-analytics/viewing/analytics-pages-devices.md
en/docs/api-analytics/viewing/analytics-pages-errors.md
en/docs/api-analytics/viewing/analytics-pages-introduction.md
en/docs/api-analytics/viewing/analytics-pages-latency.md
en/docs/api-analytics/viewing/analytics-pages-overview.md
en/docs/api-analytics/viewing/analytics-pages-report.md
en/docs/api-analytics/viewing/analytics-pages-traffic.md

fixes https://github.com/wso2/docs-apim/issues/4245

fixes https://github.com/wso2/docs-apim/issues/4245

---

en/docs/administer/managing-users-and-roles/introduction-to-user-management.md
en/docs/consume/invoke-apis/invoke-apis-using-tools/invoke-an-graphql-api-using-the-integrated-graphql-console.md
en/docs/deploy-and-publish/deploy-on-gateway/choreo-connect/deploy-api/deploy-api-via-apictl.md
en/docs/deploy-and-publish/deploy-on-gateway/choreo-connect/getting-started/choreo-connect-overview.md
en/docs/deploy-and-publish/deploy-on-gateway/choreo-connect/getting-started/quick-start-guide/quick-start-guide-docker.md
en/docs/install-and-setup/setup/setting-up-databases/changing-default-databases/changing-to-mariadb.md
en/docs/install-and-setup/setup/si-setup/configuring-data-sources.md
en/docs/integrate/examples/rabbitmq_examples/move-msgs-to-dlq-rabbitmq.md
en/docs/integrate/examples/rabbitmq_examples/point-to-point-rabbitmq.md
en/docs/integrate/examples/rabbitmq_examples/pub-sub-rabbitmq.md
en/docs/integrate/examples/rabbitmq_examples/request-response-rabbitmq.md
en/docs/integrate/examples/rabbitmq_examples/requeue-msgs-with-errors-rabbitmq.md
en/docs/integrate/examples/rabbitmq_examples/retry-delay-failed-msgs-rabbitmq.md
en/docs/observe/mi-observe/cloud-native-observability-dashboards.md
en/docs/observe/si-observe/viewing-dashboards.md
en/docs/reference/connectors/db-event-inbound-endpoint/db-event-inbound-endpoint-overview.md
en/docs/reference/connectors/jira-connector/jira-connector-config.md
en/docs/reference/connectors/jira-connector/jira-connector-example.md
en/docs/reference/connectors/jira-connector/jira-connector-overview.md

https://github.com/wso2/docs-apim/issues/4140

part 1 fix for #4140

---

en/docs/reference/mediators/property-reference/accessing-properties-with-xpath.md

Documentation for https://github.com/wso2/micro-integrator/issues/2332

Add documentation on autoreloading of file.properties

---

en/docs/reference/connectors/file-connector/file-connector-config.md

This is related to wso2-extensions/esb-connector-file#154

Add docs on update last modified timestamp config

---

en/docs/reference/connectors/file-connector/file-connector-config.md

Update version info of last timestamp value

---

en/docs/install-and-setup/upgrading-wso2-api-manager/upgrading-from-310-to-400.md

- fixes https://github.com/wso2/docs-apim/issues/4244
- Checked if this issue occurs in the following pages but it didnt 
-- 2.0.0 to 4.0.0
-- 1.9.1 to 4.0.0
-- 2.1.0 to 4.0.0
-- 2.2.0  to 4.0.0
-- 2.5.0  to 4.0.0
-- 2.6.0  to 4.0.0
-- 3.0.0  to 4.0.0
-- 3.2.0 to 4.0.0

fixes https://github.com/wso2/docs-apim/issues/4244

---

en/docs/assets/css/theme.css

Fix for #4267

---

en/docs/develop/product-apis/gateway-apis/gateway-v1/gateway-v1.yaml

> Doc change to fix of https://github.com/wso2/product-apim/issues/11305

Aligned gateway rest api with 4.0.0

---

en/docs/install-and-setup/setup/si-deployment/deploying-si-as-a-single-deployment.md

fixes https://github.com/wso2/docs-apim/issues/4280

fixes https://github.com/wso2/docs-apim/issues/4280

---

en/docs/design/api-security/oauth2/grant-types/authorization-code-grant.md
en/docs/design/api-security/oauth2/grant-types/client-credentials-grant.md
en/docs/design/api-security/oauth2/grant-types/jwt-grant.md
en/docs/design/api-security/oauth2/grant-types/kerberos-oauth2-grant.md
en/docs/design/api-security/oauth2/grant-types/ntlm-grant.md
en/docs/design/api-security/oauth2/grant-types/password-grant.md
en/docs/design/api-security/oauth2/grant-types/refresh-token-grant.md
en/docs/design/api-security/oauth2/grant-types/saml-extension-grant.md

Change IS token endpoint (oauth2/token)

---

en/docs/learn/api-security/api-authentication/secure-apis-using-api-keys.md
en/tools/config-catalog-generator/data/configs.json

Update Keystore Configs & API Key Keystore Configs Descriptions

---

en/docs/assets/css/theme.css
en/theme/material/partials/footer.html

- Fixing https://github.com/wso2/docs-apim/issues/4231

fix footer alignment issue

---

en/docs/install-and-setup/setup/security/configuring-transport-level-security.md

Fixes A726

---

en/docs/develop/product-apis/admin-apis/admin-v0.16/admin-v0.16.yaml

Add new application get resource documentation.

---

en/docs/develop/product-apis/admin-apis/admin-v0.16/admin-v0.16.yaml

Add search by app name

---

en/docs/mi-analytics/using-the-analytics-dashboard.md
en/mkdocs.yml

- Analytics docs related minor changes
- Fixes https://github.com/wso2/docs-apim/issues/3982

Analytics docs related minor changes

---

en/docs/assets/css/theme.css
en/theme/material/partials/footer.html

fixes https://github.com/wso2/docs-apim/issues/4231 in 3.2.0 docs

fixes https://github.com/wso2/docs-apim/issues/4231

---

en/docs/troubleshooting/configuring-xslt-mediation-with-xalan.md
en/mkdocs.yml

Fix A735 in 3.2.0

---

en/docs/reference/customize-product/customizations/customizing-the-developer-portal/overriding-developer-portal-theme.md

fixes https://github.com/wso2/docs-apim/issues/4325
related master PR : https://github.com/wso2/docs-apim/pull/4327
> Link to the …

[4.0.0] Fix tenant custom logo path

---

en/docs/learn/api-controller/getting-started-with-wso2-api-controller.md

Update examples of API controller with more detailed ones.
Fixes https://github.com/wso2/product-apim-tooling/issues/765
> https://github.com/wso2/product-apim-tooling/issues/763

[3.2.0] Update examples of API controller

---

en/docs/install-and-setup/setup/api-controller/managing-apis-api-products/managing-apis-and-api-products.md

Update examples of API controller with more detailed ones.
Fixes https://github.com/wso2/product-apim-tooling/issues/765 for 4.0.0 docs
https://github.com/wso2/docs-apim/pull/4323

[4.0.0] Update examples of API controller

---

en/docs/install-and-setup/setup/api-controller/managing-apis-api-products/managing-apis-and-api-products.md

Update examples of API controller with more detailed ones.
Fixes https://github.com/wso2/product-apim-tooling/issues/765 for Master docs
https://github.com/wso2/docs-apim/pull/4323

[Master] Update examples of API controller

---

en/docs/reference/customize-product/customizations/customizing-the-developer-portal/overriding-developer-portal-theme.md

fixes https://github.com/wso2/docs-apim/issues/4325 …

Fix tenant custom logo path

---

en/docs/install-and-setup/setup/distributed-deployment/product-profiles.md

fixes https://github.com/wso2/docs-apim/issues/4314

fixes https://github.com/wso2/docs-apim/issues/4314

---

en/docs/install-and-setup/setup/distributed-deployment/configure-apim-analytics/active-passive.md

fixes https://github.com/wso2/docs-apim/issues/4275

fixes https://github.com/wso2/docs-apim/issues/4275

---

en/docs/install-and-setup/setup/distributed-deployment/configure-apim-analytics/active-passive.md

fixes https://github.com/wso2/docs-apim/issues/4276

fixes https://github.com/wso2/docs-apim/issues/4276

---

en/mkdocs.yml

fixing incorrect redirection

---

en/docs/install-and-setup/setup/setting-up-databases/overview.md

fixes https://github.com/wso2/docs-apim/issues/4254

fixes https://github.com/wso2/docs-apim/issues/4254

---

en/docs/integrate/develop/integration-development-kickstart.md

fixes https://github.com/wso2/docs-apim/issues/4321

fixes https://github.com/wso2/docs-apim/issues/4321

---

en/docs/get-started/apim-architecture.md

fixes https://github.com/wso2/docs-apim/issues/4304

fixes https://github.com/wso2/docs-apim/issues/4304

---

en/docs/deploy-and-publish/deploy-on-gateway/choreo-connect/concepts/choreo-connect-analytics.md

fixes https://github.com/wso2/docs-apim/issues/4320

fixes https://github.com/wso2/docs-apim/issues/4320

---

en/docs/install-and-setup/setup/setting-up-databases/changing-default-databases/changing-to-mysql.md

fixes https://github.com/wso2/docs-apim/issues/4334

fixes https://github.com/wso2/docs-apim/issues/4334

---

en/docs/install-and-setup/setup/distributed-deployment/deploying-wso2-api-m-in-a-distributed-setup.md

fixes https://github.com/wso2/docs-apim/issues/4335

fixes https://github.com/wso2/docs-apim/issues/4335

---

en/docs/learn/api-controller/getting-started-with-wso2-api-controller.md

Adding the artifacts for apictl 3.2.3 distributions to the 3.2.0 doc space.

[3.2.0] Adding apictl 3.2.3 artifacts

---

en/docs/install-and-setup/setup/setting-up-databases/changing-default-databases/changing-to-mysql.md

fixes https://github.com/wso2/docs-apim/issues/4336

fixes https://github.com/wso2/docs-apim/issues/4336

---

en/docs/install-and-setup/upgrading-wso2-api-manager/upgrading-from-320-to-400.md

fix duplicate content
> Link(s) to product documentation that addresses the changes of this PR. If no doc impact, enter “N/A” …

Update fix upgrading-from-320-to-400.md

---

en/docs/observe/mi-observe/working-with-monitoring-dashboard.md

fixes https://github.com/wso2/docs-apim/issues/4358

fixes https://github.com/wso2/docs-apim/issues/4358

---

en/mkdocs.yml

Fixes https://github.com/wso2/docs-apim/issues/4356
Added a redirection as requested.

Fixes https://github.com/wso2/docs-apim/issues/4356

---

en/docs/deploy-and-publish/deploy-on-gateway/deploy-api/deploy-through-multiple-api-gateways.md

Fixing wso2/docs-apim#4317

---

en/docs/index.md

fixes https://github.com/wso2/docs-apim/issues/4258

fixes https://github.com/wso2/docs-apim/issues/4258

---

en/docs/assets/attachments/learn/analytics/geo-location/linux/update-geolocation-data.sh
en/docs/learn/analytics/analyzing-apim-statistics-with-batch-analytics/using-geo-location-based-statistics/creating-geo-location-data-set.md

Add GeoLocation data population capability for Windows and Fix 'update-geolocation-data.sh' for Linux

---

en/docs/reference/connectors/file-connector/file-connector-config.md

Add missing parameter responseFormat in listFiles operation

---

en/docs/reference/connectors/file-connector/file-connector-config.md

Related to https://github.com/wso2-extensions/esb-connector-file/pull/158
> Link(s) to product documentation that addresses the …

Add new parameter "filePattern" in move operation

---

en/docs/reference/connectors/file-connector/file-connector-config.md

Add missing parameter "responseFormat" in listFiles operation

---

en/docs/install-and-setup/setup/reference/product-compatibility.md

fixes https://github.com/wso2/docs-apim/issues/4384

fixes https://github.com/wso2/docs-apim/issues/4384

---

en/docs/get-started/about-this-release.md

[4.0.0] Add TLS support to release note

---

en/docs/install-and-setup/install/deploying-api-manager-with-kubernetes-or-openshift-resources.md

Remove WIP banner for k8s docs

---

en/docs/tutorials/integration-tutorials/using-inbound-endpoints.md

fixes https://github.com/wso2/docs-apim/issues/4393

fixes https://github.com/wso2/docs-apim/issues/4393

---

en/docs/deploy-and-publish/deploy-on-gateway/choreo-connect/concepts/inter-component-communication.md

Fixed a typo

---

en/docs/install-and-setup/setup/mi-setup/observability/setting-up-cloud-native-observability-in-kubernetes.md

fixes https://github.com/wso2/docs-apim/issues/4375

fixes https://github.com/wso2/docs-apim/issues/4375

---

en/docs/administer/managing-users-and-roles/introduction-to-user-management.md
en/docs/administer/managing-users-and-roles/managing-users.md
en/docs/administer/multitenancy/managing-tenants.md
en/docs/consume/invoke-apis/invoke-apis-using-tools/invoke-an-graphql-api-using-the-integrated-graphql-console.md
en/docs/consume/invoke-apis/invoke-apis-using-tools/try-out-using-postman.md
en/docs/deploy-and-publish/deploy-on-gateway/choreo-connect/deploy-api/deploy-api-via-apictl.md
en/docs/deploy-and-publish/deploy-on-gateway/choreo-connect/deploy-api/deploy-api-via-apim.md
en/docs/deploy-and-publish/deploy-on-gateway/choreo-connect/getting-started/choreo-connect-overview.md
en/docs/deploy-and-publish/deploy-on-gateway/choreo-connect/getting-started/quick-start-guide/quick-start-guide-docker.md
en/docs/deploy-and-publish/publish-on-dev-portal/publish-to-multiple-external-api-stores.md
en/docs/install-and-setup/setup/setting-up-databases/changing-default-databases/changing-to-mariadb.md
en/docs/install-and-setup/setup/si-setup/configuring-data-sources.md
en/docs/integrate/examples/rabbitmq_examples/move-msgs-to-dlq-rabbitmq.md
en/docs/integrate/examples/rabbitmq_examples/point-to-point-rabbitmq.md
en/docs/integrate/examples/rabbitmq_examples/pub-sub-rabbitmq.md
en/docs/integrate/examples/rabbitmq_examples/request-response-rabbitmq.md
en/docs/integrate/examples/rabbitmq_examples/requeue-msgs-with-errors-rabbitmq.md
en/docs/integrate/examples/rabbitmq_examples/retry-delay-failed-msgs-rabbitmq.md
en/docs/observe/mi-observe/cloud-native-observability-dashboards.md
en/docs/observe/si-observe/viewing-dashboards.md
en/docs/reference/connectors/db-event-inbound-endpoint/db-event-inbound-endpoint-overview.md
en/docs/reference/connectors/jira-connector/jira-connector-config.md
en/docs/reference/connectors/jira-connector/jira-connector-example.md
en/docs/reference/connectors/jira-connector/jira-connector-overview.md
en/docs/reference/connectors/kafka-connector/kafka-connector-avro-producer-example.md
en/docs/reference/connectors/kafka-connector/kafka-connector-overview.md

Fixing broken links - Part 2
