wso2/docs-apim

en/docs/index.md

edit home page image path

---

en/docs/index.md
en/docs/page-not-found.html

fix tile links and add page not found html page

---

en/docs/assets/css/theme.css
en/docs/assets/js/theme.js
en/docs/assets/lib/backtotop/img/cd-top-arrow.svg
en/docs/assets/lib/backtotop/js/main.js
en/docs/assets/lib/backtotop/js/util.js
en/mkdocs.yml
en/theme/material/partials/toc.html

Fix TOC, back to top and theme

Fix TOC, back to top and theme

---

en/docs/index.md

Fix broken links from landing page

---

en/mkdocs.yml

remove Rate Limiting-Security Concerns  topic under security

---

en/docs/WIP/README.md

Add WIP progress

---

en/docs/Troubleshooting/error-handling.md

Updated the error message descriptions based on [1]
[1] https://github.com/wso2/docs-apim/issues/17
Fixed a Git issue.

Update the error message descriptions

---

en/docs/Reference/ConfigCatalog.md
en/docs/WIP/config-catalog.md
en/docs/WIP/config_introduction.md

Cleaned up and updated descriptions

---

en/docs/Learn/APIMonetization/monetizing-an-api.md

remove unnecessary step

---

en/docs/Learn/DesignAPI/CreateAPI/create-a-graphql-api.md

Added fixes to the Create GraphQL API page.

fix intra-link paths and missing image

---

en/docs/Learn/DesignAPI/CreateAPI/create-a-graphql-api.md

Fixed minor formatting issues in the create a grapql api page.

fix format in create a grapql api page

---

en/docs/Learn/APIMonetization/monetizing-an-api.md

Did minor changes related to formatting in the monetizing-an-api.md page.

format monetizing-an-api.md

---

en/docs/Learn/APISecurity/ThreatProtection/bot-detection.md

Fixed a broken link in the bot-detection.md page.

Fix broken link

---

en/docs/WIP/json-schema-validator.md

Fixed image links in the json-schema-validator.md file.

Fixed image links json-schema-validator.md

---

en/docs/Learn/APIMonetization/monetizing-an-api.md
en/docs/Learn/DesignAPI/CreateAPI/create-a-graphql-api.md

Fixed image issues for images defined with HTML coding.

Fixed image issues for images defined with HTML coding

---

en/mkdocs.yml

Fixes: https://github.com/wso2/docs-apim/issues/62

Fix search

---

en/mkdocs.yml

Added the "Schema Validation" menu and added the JSON Schema Validator file under it. 
Learn/APISecurity/SchemaValidation/json-schema-validator.md
Fix for https://github.com/wso2/docs-apim/issues/59

Added menu for schema validation

---

en/docs/assets/css/theme.css

Fixes: https://github.com/wso2/docs-apim/issues/71

Fix code sample overflow

---

en/docs/assets/css/theme.css
en/theme/material/partials/header.html

As the APIM 3.0.0 documentation is WIP, I added the WIP label to it.

Added WIP label to docs

---

en/docs/Learn/DesignAPI/CreateAPI/create-a-graphql-api.md

Fixed introduction in GraphQL doc.
Fix for https://github.com/wso2/docs-apim/issues/82

Fixed introduction in GraphQl doc

---

en/docs/Learn/Analytics/AnalyzingAPIMStatisticsWithBatchAnalytics/UsingGeoLocationBasedStatistics/configuring-geolocation-based-statistics.md
en/docs/Learn/Analytics/AnalyzingAPIMStatisticsWithBatchAnalytics/UsingGeoLocationBasedStatistics/updating-geo-location-data-set.md
en/docs/Learn/Analytics/AnalyzingAPIMStatisticsWithBatchAnalytics/UsingGeoLocationBasedStatistics/writing-a-custom-geolocation-provider.md

This PR adds improvements to geo-location-based analytics docs.

Improve geo-location based analytics docs

---

en/docs/Learn/APISecurity/OAuth2/encrypting-oauth-keys.md

This PR adds improvements for Encrypting OAuth Keys doc

Improve Encrypting OAuth Keys doc

---

en/docs/Learn/APIGateway/MessageMediation/disable-message-chunking.md

This PR updates https://apim.docs.wso2.com/en/next/Learn/APIGateway/MessageMediation/disable-message-chunking/ page.

Update 'Disable Message chunking' Page

---

en/docs/Learn/DesignAPI/AdvancedTopics/adding-custom-properties-to-apis.md

Adding doc for custom API properties

Removing doc link

---

en/docs/Learn/APISecurity/OAuth2/token-expiration.md

> This PR adds improvements for token-expiration docs

Improve Token Expiration Doc

---

en/docs/assets/css/theme.css

Fix home page glitch

---

en/docs/GettingStarted/about-this-release.md

Added a blank about-this-release.md page

Added a about-this-release.md page

---

en/docs/Learn/APIGateway/PassingEndUserAttributesToTheBackend/passing-enduser-attributes-to-the-backend-using-jwt.md

Fixes https://github.com/wso2/docs-apim/issues/125

Update docs on passing end user attributes to the backend using JWT

---

en/docs/Learn/DesignAPI/PublishAPI/publish-an-api.md

Fixes https://github.com/wso2/docs-apim/issues/129

Update API publishing docs

---

en/docs/Learn/ConsumeAPI/DiscoverAPIs/search.md

Fixes https://github.com/wso2/docs-apim/issues/131

Update Publisher and Developer Portal API search related docs

---

en/docs/Learn/DesignAPI/PublishAPI/publish-an-api.md

Reverts wso2/docs-apim#130 as it was sent to the wrong branch

Revert "Update API publishing docs"

---

en/docs/assets/versions.json

> Update en/docs/assets/versions.json config file with APIM 3.0.0 doc space info

Updating jenkins build version config with APIM 3.0.0 info

---

en/docs/Learn/APISecurity/OAuth2/AOuth2Scopes/scope-whitelisting.md

This PR adds improvements for scope whitelisting doc

Improve Scope Whitelisting doc

---

en/docs/Learn/DesignAPI/Endpoints/Resiliency/endpoint-suspension.md
en/docs/Learn/DesignAPI/Endpoints/Resiliency/prevent-api-suspension.md

Add relative doc paths and fix image path and add Endpoint suspension doc

---

en/mkdocs.yml

Added the "About this release" link to the en/mkdocs.yml file.

Added about this release link en/mkdocs.yml

---

en/docs/Learn/DesignAPI/AdvancedTopics/control-api-visibility-and-subscription-availability-in-developer-portal.md
en/mkdocs.yml

> Add the skeleton doc for API visibility in developer portal feature

Add the skeleton doc for API visibility in developer portal feature

---

en/docs/Learn/DesignAPI/PublishAPI/publish-an-api.md

Fixes https://github.com/wso2/docs-apim/issues/129

Update API publishing docs -publish-an-api

---

en/docs/Learn/ConsumeAPI/ManageApplication/GenerateKeys/GrantTypes/password-grant.md

This PR adds password grant type doc

Improve Password Grant Doc

---

en/docs/GettingStarted/overview.md

Updated the content in the Key Features section.

Update the overview page

---

en/docs/GettingStarted/about-this-release.md

Updated the about this release page.

Updated the about this release page

---

en/docs/Learn/DesignAPI/Endpoints/endpoint-types.md

Add Endpoint Types docs page.
> Link to the PR for changes to the training content in https://github.com/wso2/WSO2-Training, if …

Add Endpoint Types docs page.

---

en/docs/assets/css/theme.css
en/theme/material/partials/header.html

Removed the WIP label

---

en/docs/index.md

Fixing desing API page redirection

Fixing desing API page redirection

---

en/docs/Learn/DesignAPI/AdvancedTopics/enable-publisher-access-control-in-api-publisher-portal.md
en/mkdocs.yml

Update publisher access control doc

Update publisher access control doc

---

en/theme/material/templates/single-column.html

Fix home page mobile navigation

---

en/docs/Learn/APIGateway/MessageMediation/convert-a-json-message-to-soap-and-soap-to-json.md
en/docs/Learn/Extensions/adding-mediation-extensions.md

fix mkdocs warnning w.r.t images paths.

fix mkdocs warnnings

---

en/docs/Learn/DesignAPI/AdvancedTopics/enable-publisher-access-control-in-api-publisher-portal.md

Removing additional bracket

---

en/docs/GettingStarted/about-this-release.md

Fixed broken links in about-this-release.md file.

Fixed broken links in about-this-release.md

---

en/docs/Learn/APIMonetization/monetizing-an-api.md

> Add a note in the Monetization document space to instruct the readers about updating the payment details of a customer in Stripe.

Add payment details update note

---

en/docs/Learn/Analytics/ManagingAlertsWithRealTimeAnalytics/alert-types.md
en/docs/Learn/Analytics/ManagingAlertsWithRealTimeAnalytics/configuring-alerts.md
en/docs/Learn/Analytics/ManagingAlertsWithRealTimeAnalytics/subscribing-for-alerts.md

Fix redirection for alerts pages

Fix redirection for alerts pages

---

en/docs/Learn/APIGateway/api-gateways-with-dedicated-backends.md
en/docs/Learn/APIGateway/maintaining-separate-production-and-sandbox-gateways.md

Also includes fixes to make images clickable and zoomable

Fix issues found in the Maintaining Separate Production and Sandbox Gateways page

---

en/docs/Learn/APIGateway/api-gateways-with-dedicated-backends.md

Fix the issue where the images are not loaded in the page, API Gateways with Dedicated Backends

Fix issue in image path

---

en/docs/Learn/APIGateway/scaling-the-gateway.md
en/docs/SetupAndInstall/DeployingWSO2APIManager/deployment-patterns.md

Fixes https://github.com/wso2/docs-apim/issues/215

Update docs for APIM Gateway Scaling

---

en/theme/material/main.html

Added SEO tracking for docs

---

en/docs/assets/css/theme.css

Fix text overflow

---

en/docs/Learn/APIGateway/MessageMediation/transforming-api-message-payload.md

Update "Transforming API message payload" page

---

en/docs/Learn/Analytics/configuring-apim-analytics.md

> This PR fixes issues in the standard setup section of the "Configuring APIM Analytics" document.

Add standard setup documents for analytics

---

en/docs/Learn/DesignAPI/APIDocumentation/SearchDocumentation/add-new-search-keyword.md

Fixes https://github.com/wso2/docs-apim/issues/239

Modify adding new search keyword doc page

---

en/CONTRIBUTE.md

Enabling external contributions through doc edits.

Added instructions on contributing to API Manager docs 

---

en/docs/assets/css/theme.css

Fix sidebar scroll

---

en/docs/Learn/Analytics/AnalyzingAPIMStatisticsWithBatchAnalytics/introducing-the-wso2-api-manager-statistics-model.md

This Pr fixes the documentation for `Introducing the WSO2 API Manager Statistics Model` page.

Improve introducing api manager stat page

---

en/docs/Learn/ConsumeAPI/ManageApplication/GenerateKeys/GrantTypes/ntlm-grant.md

This PR adds doc for NTLM Grant type

Improve NTLM grant type doc

---

en/docs/Learn/DesignAPI/APIDocumentation/add-api-documentation.md
en/docs/SetupAndInstall/DeployingWSO2APIManager/SingleNode/configuring-an-active-active-deployment.md
en/docs/SetupAndInstall/DeployingWSO2APIManager/configuring-the-proxy-server-and-the-load-balancer.md

Fixes https://github.com/wso2/docs-apim/issues/268

Add proxy server and load balancer configurations doc page

---

en/docs/Learn/DesignAPI/APIDocumentation/SearchDocumentation/add-new-search-keyword.md

Fixes https://github.com/wso2/docs-apim/issues/239

Modify profiles related configs in Add new search keyword page 

---

en/docs/Develop/ProductAPIs/restful-apis.md
en/mkdocs.yml

Added back the updated overview page for REST API docs

Added overview page

---

en/docs/SetupAndInstall/DeployingWSO2APIManager/configuring-rsync-for-deployment-synchronization.md

Fixes https://github.com/wso2/docs-apim/issues/315

Update rsync documentation

---

en/docs/Learn/APIMonetization/monetizing-an-api.md

> Fix some configuration related issues in monetization doc space

Improve monetization doc space

---

en/docs/SetupAndInstall/DeployingWSO2APIManager/SingleNode/configuring-an-active-active-deployment.md

Fixes https://github.com/wso2/docs-apim/issues/269

Update doc on Configuring an Active-Active Deployment

---

en/docs/assets/css/theme-material.css
en/docs/page-not-found.html
en/docs/page-not-found.md

Temporarily update page-not-found md and html files

Updated 404 pages

---

en/docs/Learn/APISecurity/APIAuthentication/secure-apis-using-api-keys.md

Fix typo in API keys page

---

en/docs/Learn/Analytics/configuring-apim-analytics.md

This PR fixes issues in configuring analytics document.

Fix issues in configuring analytics doc

---

en/docs/Learn/DesignAPI/CreateAPIProduct/api-product-overview.md

Updated the API Product Overview page

Updated the API Product Overview

---

en/docs/page-not-found.md

change 404 not found message

---

en/docs/Learn/Tutorials/create-a-graphql-api.md
en/docs/Learn/Tutorials/create-a-websocket-api.md
en/docs/Learn/Tutorials/edit-and-consume-apis-using-swagger-tools.md
en/docs/Learn/Tutorials/expose-a-soap-service-as-a-rest-api.md

The following fixes are to address the following mkdocs warnings:
```
WARNING -  Documentation file 'Learn/Tutorials/create-a-graphql-api.md' contains a link to '../assets/img/Learn/import-graphQL-schema.png' which is not found in the documentation files. 
WARNING -  Documentation file 'Learn/Tutorials/create-a-graphql-api.md' contains a link to '../assets/attachments/learn/schema_graphql.graphql' which is not found in the documentation files. 
WARNING -  Documentation file 'Learn/Tutorials/create-a-graphql-api.md' contains a link to '../assets/img/Learn/import-graphQL-schema-via-file.png' which is not found in the documentation files. 
WARNING -  Documentation file 'Learn/Tutorials/create-a-graphql-api.md' contains a link to '../assets/img/Learn/add-graphql-API-details.png' which is not …
```

Fixed the mkdocs issues for /Learn/Tutorials/

---

en/docs/index.md
en/mkdocs.yml

Fix broken API Security link on the home page

---

en/docs/SetupAndInstall/InstallationGuide/InstallingTheProduct/installing-on-linux-or-os-x.md
en/docs/SetupAndInstall/InstallationGuide/InstallingTheProduct/installing-on-solaris.md
en/docs/SetupAndInstall/InstallationGuide/InstallingTheProduct/installing-on-windows.md
en/docs/SetupAndInstall/InstallationGuide/installation-prerequisites.md

Fix download link

---

en/docs/Learn/APISecurity/OAuth2DeepDive/token-revocation.md

Token Revocation

---

en/docs/Learn/DesignAPI/CreateAPIProduct/create-api-product.md

Reviewed and updated create-api-product.md

Reviewed and updated create-api-product.md

---

en/docs/SetupAndInstall/DeployingWSO2APIManager/DistributedDeployment/deploying-wso2-api-m-in-a-distributed-setup.md
en/docs/SetupAndInstall/DeployingWSO2APIManager/SingleNode/configuring-a-single-node.md

Updated the docs with distributed setup

---

en/docs/SetupAndInstall/DeployingWSO2APIManager/DistributedDeployment/distributed-deployment-of-the-gateway.md
en/docs/SetupAndInstall/DeployingWSO2APIManager/DistributedDeployment/working-with-hazelcast-clustering.md
en/mkdocs.yml

Fixed GW clustering doc

---

en/docs/SetupAndInstall/DeployingWSO2APIManager/deploying-api-manager-with-kubernetes-or-openshift-resources.md

Fixing formatting issue with the title "Deploy a pattern on Openshift"

---

en/docs/SetupAndInstall/InstallationGuide/InstallingTheProduct/InstallingTheBinary/installing-on-linux-or-os-x.md
en/docs/SetupAndInstall/InstallationGuide/InstallingTheProduct/InstallingTheBinary/installing-on-solaris.md
en/docs/SetupAndInstall/InstallationGuide/InstallingTheProduct/InstallingTheBinary/installing-on-windows.md
en/docs/SetupAndInstall/InstallationGuide/InstallingTheProduct/installing-via-the-installer.md

Changed 2.6.0 to 3.0.0 in installing-via-the-installer.md

Changed 2.6.0 to 3.0.0 in installing-via-the-installer.md

---

en/docs/Learn/APIController/getting-started-with-wso2-api-controller.md
en/docs/Learn/APIController/importing-apis-via-dev-first-approach.md
en/docs/Learn/APIController/migrating-apis-to-different-environments.md

Fix minor issues

---

en/docs/GettingStarted/about-this-release.md
en/docs/SetupAndInstall/InstallationGuide/InstallingTheProduct/InstallingTheBinary/installing-as-a-linux-service.md
en/docs/SetupAndInstall/InstallationGuide/InstallingTheProduct/InstallingTheBinary/installing-as-a-windows-service.md
en/docs/SetupAndInstall/InstallationGuide/InstallingTheProduct/InstallingTheBinary/installing-on-linux-or-os-x.md
en/docs/SetupAndInstall/InstallationGuide/InstallingTheProduct/InstallingTheBinary/installing-on-solaris.md
en/docs/SetupAndInstall/InstallationGuide/InstallingTheProduct/InstallingTheBinary/installing-on-windows.md
en/docs/SetupAndInstall/InstallationGuide/installation-prerequisites.md
en/docs/SetupAndInstall/ProductCompatibility.md
en/mkdocs.yml

Added the product compatibility page for APIM 3.0.0.

Added the product compatibility page

---

en/docs/Learn/DesignAPI/CreateAPI/create-a-rest-api.md
en/docs/SetupAndInstall/InstallationGuide/InstallingTheProduct/InstallingTheBinary/installing-as-a-windows-service.md
en/docs/SetupAndInstall/InstallationGuide/InstallingTheProduct/InstallingTheBinary/installing-on-linux-or-os-x.md
en/docs/SetupAndInstall/InstallationGuide/InstallingTheProduct/InstallingTheBinary/installing-on-solaris.md
en/docs/SetupAndInstall/InstallationGuide/InstallingTheProduct/InstallingTheBinary/installing-on-windows.md
en/docs/SetupAndInstall/InstallationGuide/InstallingTheProduct/installing-via-the-installer.md
en/docs/SetupAndInstall/InstallationGuide/installation-prerequisites.md
en/docs/SetupAndInstall/InstallationGuide/running-the-product.md

- Updated the paths in en/docs/SetupAndInstall/InstallationGuide/
- Reviewed and updated create-a-rest-api.md
- Fixed typos

Reviewed and updated content

---

en/docs/Learn/APISecurity/ThreatProtection/bot-detection.md

Fixes https://github.com/wso2/docs-apim/issues/418

Update Bot detection feature documentation

---

en/docs/Learn/APISecurity/OAuth2DeepDive/token-revocation.md

fix token revocation doc

---

en/mkdocs.yml

Updated the base_path as I had changed it for testing purposes previously.

Updated the base_path

---

en/docs/Learn/ConsumeAPI/Customizations/CustomizingTheAPIStore/overriding-developer-portal-theme.md

Fixed the broken link to theme file

Fixed broken link

---

en/docs/Learn/ConsumeAPI/Customizations/CustomizingTheAPIStore/overriding-developer-portal-theme.md

Fixed the broken link to cloud theme file.

Fixing broken link

---

en/docs/Administer/ProductAdministration/removing-unused-tokens-from-the-database.md
en/docs/SetupAndInstall/UpgradingWSO2APIManager/upgrading-process.md

Fix for https://github.com/wso2/docs-apim/issues/434

Add upgrading-process page

---

en/docs/SetupAndInstall/UpgradingWSO2APIManager/upgrading-from-260-to-300.md

Fixes related to https://github.com/wso2/docs-apim/issues/434

Fix formatting issues in 2.6 to 3.0 migration doc

---

en/docs/SetupAndInstall/DeployingWSO2APIManager/configuring-the-proxy-server-and-the-load-balancer.md
en/docs/SetupAndInstall/UpgradingWSO2APIManager/upgrading-from-260-to-300.md
en/docs/SetupAndInstall/UpgradingWSO2ISAsKeyManager/upgrading-from-is-km-570-to-590.md

Fixes related to https://github.com/wso2/docs-apim/issues/434

Fix issues in migration related docs

---

en/docs/SetupAndInstall/UpgradingWSO2APIManager/upgrading-from-260-to-300.md

Add a note for secure vault in migration doc

---

en/docs/SetupAndInstall/UpgradingWSO2APIManager/upgrading-from-260-to-300.md

Improve 2.6 to 3.0 migration doc

---

en/docs/Administer/ProductAdministration/removing-unused-tokens-from-the-database.md
en/docs/SetupAndInstall/UpgradingWSO2APIManager/upgrading-process.md
en/docs/SetupAndInstall/UpgradingWSO2ISAsKeyManager/upgrading-from-is-km-500-to-590.md
en/docs/SetupAndInstall/UpgradingWSO2ISAsKeyManager/upgrading-from-is-km-510-to-590.md
en/docs/SetupAndInstall/UpgradingWSO2ISAsKeyManager/upgrading-from-is-km-520-to-590.md
en/docs/SetupAndInstall/UpgradingWSO2ISAsKeyManager/upgrading-from-is-km-530-to-590.md
en/docs/SetupAndInstall/UpgradingWSO2ISAsKeyManager/upgrading-from-is-km-550-to-590.md
en/docs/SetupAndInstall/UpgradingWSO2ISAsKeyManager/upgrading-from-is-km-560-to-590.md
en/docs/SetupAndInstall/UpgradingWSO2ISAsKeyManager/upgrading-from-is-km-570-to-590.md
en/mkdocs.yml

Changes related to https://github.com/wso2/docs-apim/issues/434

Add initial doc changes for IS-as-KM pages

---

en/docs/SetupAndInstall/UpgradingWSO2APIManager/upgrading-from-260-to-300.md

Changing the order of steps in 2.6 to 3.0 migration doc

---

en/docs/SetupAndInstall/UpgradingWSO2APIManager/upgrading-from-260-to-300.md

Add troubleshooting steps for IS migration guide

---

en/docs/SetupAndInstall/UpgradingWSO2APIManager/upgrading-from-220-to-300.md
en/docs/SetupAndInstall/UpgradingWSO2APIManager/upgrading-from-260-to-300.md
en/docs/SetupAndInstall/UpgradingWSO2ISAsKeyManager/upgrading-from-is-km-550-to-590.md
en/docs/assets/attachments/SetupAndInstall/apim220_to_apim300_gateway_artifact_migrator.ps1
en/docs/assets/attachments/SetupAndInstall/apim220_to_apim300_gateway_artifact_migrator.sh
en/docs/assets/attachments/SetupAndInstall/apim220_to_apim300_gateway_artifact_migrator_for_tenants.ps1

Add 2.2 to 3.0 migration docs

---

en/docs/Learn/Analytics/configuring-apim-analytics.md

Add documentation for APIM IdP client. …

Add documentation for APIM IdP client

---

en/docs/SetupAndInstall/UpgradingWSO2APIManager/upgrading-from-220-to-300.md
en/docs/SetupAndInstall/UpgradingWSO2APIManager/upgrading-from-260-to-300.md

Fixes related to https://github.com/wso2/docs-apim/issues/434

Add missing steps for 2.2 and 2.6 migration docs

---

en/docs/InstallAndSetup/UpgradingWSO2APIManager/upgrading-from-220-to-300.md
en/docs/InstallAndSetup/UpgradingWSO2APIManager/upgrading-from-260-to-300.md

Fixes related to https://github.com/wso2/docs-apim/issues/434

Fix formatting issues

---

en/docs/GettingStarted/quick-start-guide.md

Updated QSG further based on Nuwan's feedback.

Updated QSG further based on feedback

---

en/docs/Learn/DesignAPI/CreateAPI/expose-a-soap-service-as-a-rest-api.md
en/docs/Learn/Tutorials/expose-a-soap-service-as-a-rest-api.md

Removing unwanted documentation

remove unrequired information

---

en/docs/Administer/ProductAdministration/ManagingUsersAndRoles/introduction-to-user-management.md
en/mkdocs.yml

This PR updates the Introduction to Users Management page.

Update Introduction to Users Management page

---

en/docs/Administer/ProductAdministration/ManagingUsersAndRoles/ManagingUserStores/ConfigurePrimaryUserStore/configuring-a-read-write-ldap-user-store.md

> Update configure a read-write ldap user store page …

Update configure a read-write ldap user store page

---

en/docs/InstallAndSetup/UpgradingWSO2APIManager/upgrading-from-210-to-300.md
en/docs/InstallAndSetup/UpgradingWSO2APIManager/upgrading-from-220-to-300.md
en/docs/InstallAndSetup/UpgradingWSO2APIManager/upgrading-from-250-to-300.md
en/docs/InstallAndSetup/UpgradingWSO2APIManager/upgrading-from-260-to-300.md
en/docs/assets/attachments/InstallAndSetup/apim210_to_apim300_gateway_artifact_migrator.sh

Update 3.0 migration docs

---

en/docs/InstallAndSetup/UpgradingWSO2APIManager/upgrading-from-210-to-300.md

Add missing IS-as-KM step to 2.1 migration doc

---

en/docs/Administer/ProductAdministration/Monitoring/Logging/managing-log-growth.md
en/docs/Administer/ProductAdministration/Monitoring/Logging/monitoring-audit-logs.md
en/docs/Administer/ProductAdministration/Monitoring/Logging/setting-up-logging.md
en/mkdocs.yml

Linking carbon and audit log docs with log growth management doc

Linking carbon and audit log docs with log growth management doc

---

en/docs/Learn/APISecurity/OAuth2DeepDive/token-revocation.md

Fix confusing JWT Revoke option 1 and 2  …

Fix review comments in token revocation doc.

---

en/docs/InstallAndSetup/SettingUpDatabases/ChangingDefaultDatabases/changing-to-mssql.md

- Update  the doc `changing to MSSQL`.
- Tried out using Microsoft SQL Server 2017.
fix wso2/docs-apim#551

update changing to Microsoft SQL server DB

---

en/docs/Learn/ConsumeAPI/Customizations/CustomizingTheAPIStore/overriding-developer-portal-theme.md

The link to testTheme.zip file was broken.

updated testTheme.zip

---

en/docs/InstallAndSetup/SettingUpDatabases/ChangingDefaultDatabases/changing-to-mysql.md

Update MySQL TOML configs

---

en/docs/InstallAndSetup/SettingUpDatabases/ChangingDefaultDatabases/changing-to-mssql.md
en/docs/InstallAndSetup/SettingUpDatabases/ChangingDefaultDatabases/changing-to-mysql.md

- Update MSSQL doc with removing details in `master-datasource.xml`.
- Merge two notes in MySQL doc.
fix https://github.com/wso2/docs-apim/issues/551

Mssql doc update

---

en/docs/Learn/Extensions/SAML2SSO/configuring-identity-server-as-idp-for-sso.md

Fix issues, 
#535 
#534 
#533 
#531  …

Fix issues in sso doc.

---

en/docs/Administer/ProductAdministration/Monitoring/Logging/managing-log-growth.md
en/docs/Administer/ProductAdministration/Monitoring/Logging/monitoring-audit-logs.md
en/docs/Administer/ProductAdministration/Monitoring/Logging/setting-up-logging.md
en/docs/InstallAndSetup/DeployingWSO2APIManager/changing-the-hostname.md
en/docs/Troubleshooting/troubleshooting-invalid-callback-error.md
en/mkdocs.yml

Linking the hostname change doc with invalid callback url troubleshoot doc

Linking the hostname change doc with invalid callback url troubleshoot doc

---

en/docs/InstallAndSetup/SettingUpDatabases/ChangingDefaultDatabases/changing-to-mssql.md
en/docs/InstallAndSetup/SettingUpDatabases/ChangingDefaultDatabases/changing-to-mysql.md

Remove db installation step

---

en/docs/Administer/ProductAdministration/ManagingUsersAndRoles/ManagingUserStores/ConfigurePrimaryUserStore/configuring-a-jdbc-user-store.md
en/docs/Administer/ProductAdministration/ManagingUsersAndRoles/ManagingUserStores/ConfigurePrimaryUserStore/configuring-the-primary-user-store.md
en/docs/Administer/ProductAdministration/ManagingUsersAndRoles/ManagingUserStores/introduction-to-userstores.md

Revamped the documentation for configuring the primary user store. This pull request covers the introduction for user stores, introduction to primary user stores and setting up a JDBC primary user store.

Improve docs for configuring the primary user store

---

en/docs/Administer/ProductConfigurations/common-runtime-and-configuration-artifacts.md
en/docs/Learn/DesignAPI/AdvancedTopics/enabling-cors-for-apis.md
en/docs/Learn/DesignAPI/CreateAPI/adding-custom-properties-to-apis.md

> Adding docs for common runtime and configuration artifacts

Adding docs for common runtime and configuration artifacts

---

en/docs/InstallAndSetup/DeployingWSO2APIManager/changing-the-hostname.md

Fix for https://github.com/wso2/docs-apim/issues/567

Fix for https://github.com/wso2/docs-apim/issues/567

---

en/docs/InstallAndSetup/SettingUpDatabases/ChangingDefaultDatabases/changing-to-mssql.md
en/docs/InstallAndSetup/SettingUpDatabases/ChangingDefaultDatabases/changing-to-mysql.md
en/docs/InstallAndSetup/SettingUpDatabases/ChangingDefaultDatabases/changing-to-oracle.md
en/docs/InstallAndSetup/SettingUpDatabases/ChangingDefaultDatabases/changing-to-postgresql.md

fix https://github.com/wso2/docs-apim/issues/574
- Update "Setting up Oracle" documentation.
- Setup Oracle locally and tested with configurations.

Update "Setting up Oracle" documentation

---

en/docs/InstallAndSetup/UpgradingWSO2APIManager/upgrading-from-250-to-300.md

Add step to move keystores in analytics server

Add step to move keystores in analytics server

---

en/docs/Learn/Analytics/enabling-wso2-api-m-analytics-features.md

> Fixes wso2/docs-apim/issues/506 and wso2/docs-apim/issues/348

Fixed typo error.

---

en/docs/Administer/ProductSecurity/LoginsAndPasswords/maintaining-logins-and-passwords.md

Maintaining login and passwords document. …

Maintaining login and passwords doc.

---

en/docs/Troubleshooting/error-handling.md

Fix issues in the Error Handling document. …

Fix issues in the Error Handling document

---

en/docs/InstallAndSetup/UpgradingWSO2APIManager/upgrading-from-200-to-300.md
en/docs/InstallAndSetup/UpgradingWSO2APIManager/upgrading-from-210-to-300.md

> This note needs to added to 2.1.0 and 2.0.0

Add note when replacing keystores during migration 

---

en/docs/Administer/ProductAdministration/ManagingUsersAndRoles/ManagingUserStores/ConfigurePrimaryUserStore/configuring-a-read-write-active-directory-user-store.md

> Configuring a Read-Write Active Directory User Store.

Configuring a Read-Write Active Directory User Store.

---

en/docs/InstallAndSetup/SettingUpDatabases/ChangingDefaultDatabases/changing-to-ibm-db2.md
en/docs/InstallAndSetup/SettingUpDatabases/ChangingDefaultDatabases/changing-to-oracle.md
en/docs/InstallAndSetup/SettingUpDatabases/ChangingDefaultDatabases/changing-to-postgresql.md

fix wso2/docs-apim#541
- Update "Changing to IMB DB2" documentation

Update "Changing to IBM DB2" documentation

---

en/docs/InstallAndSetup/UpgradingWSO2APIManager/upgrading-from-200-to-300.md
en/docs/InstallAndSetup/UpgradingWSO2APIManager/upgrading-from-210-to-300.md
en/docs/InstallAndSetup/UpgradingWSO2APIManager/upgrading-from-220-to-300.md
en/docs/InstallAndSetup/UpgradingWSO2APIManager/upgrading-from-250-to-300.md
en/docs/InstallAndSetup/UpgradingWSO2APIManager/upgrading-from-260-to-300.md

> Related PR https://github.com/wso2/product-apim/pull/7037

Fix oracle script in migration docs

---

en/docs/InstallAndSetup/ProductCompatibility.md

> Changing MS SQL version to 2017

Changing MS SQL version to 2017

---

en/docs/Administer/ProductConfigurations/common-runtime-and-configuration-artifacts.md

> Fixes wso2/docs-apim/issues/292

Added number list.

---

en/docs/Learn/APISecurity/Authorization/role-based-access-control-using-xacml.md

> Fixes wso2/docs-apim/issues/346

Added portions and corrected Links.

---

en/docs/Learn/ConsumeAPI/ManageApplication/AdvancedTopics/adding-an-application-creation-workflow.md

This PR updates the docs to fix the issue where the Application Creation Approval request is not visible in Admin Portal.

Update Application Creation Workflow Page

---

en/docs/Administer/ProductConfigurations/changing-the-default-transport.md

Fixes Administer > Changing Default Transports doc. …

Fix default transport docs

---

en/docs/Administer/ProductAdministration/updating-wso2-api-manager.md

Update WUM docs

---

en/docs/InstallAndSetup/UpgradingWSO2APIManager/upgrading-from-200-to-300.md
en/docs/InstallAndSetup/UpgradingWSO2APIManager/upgrading-from-210-to-300.md
en/docs/InstallAndSetup/UpgradingWSO2APIManager/upgrading-from-220-to-300.md
en/docs/InstallAndSetup/UpgradingWSO2APIManager/upgrading-from-250-to-300.md
en/docs/InstallAndSetup/UpgradingWSO2APIManager/upgrading-from-260-to-300.md

> Resolves https://github.com/wso2/docs-apim/issues/553

Add note regarding role-scope mapping

---

en/docs/Develop/ProductAPIs/restful-apis.md

Fix for https://github.com/wso2/docs-apim/issues/620

fix for https://github.com/wso2/docs-apim/issues/620

---

en/docs/InstallAndSetup/SettingUpDatabases/ChangingDefaultDatabases/changing-to-oracle-rac.md

Changing to Oracle RAC doc update

---

en/docs/InstallAndSetup/DeployingWSO2APIManager/DistributedDeployment/configuring-wso2-identity-server-as-a-key-manager.md

Fix issues in is-as-km doc page

Fix issues in is-as-km doc page

---

en/docs/InstallAndSetup/SettingUpDatabases/ChangingDefaultDatabases/changing-to-remote-h2.md

fix wso2/docs-apim#624
- Update the documentation

Update "Changing to Remote H2" documentation

---

en/docs/InstallAndSetup/DeployingWSO2APIManager/DistributedDeployment/configuring-wso2-identity-server-as-a-key-manager.md
en/docs/InstallAndSetup/DeployingWSO2APIManager/SingleNode/configuring-an-active-active-deployment.md
en/docs/InstallAndSetup/InstallationGuide/running-the-product.md
en/docs/InstallAndSetup/SettingUpDatabases/overview.md

Fix broken image urls

---

en/docs/InstallAndSetup/SettingUpDatabases/ChangingDefaultDatabases/changing-to-ibm-db2.md
en/docs/InstallAndSetup/SettingUpDatabases/ChangingDefaultDatabases/changing-to-ibm-informix.md
en/docs/InstallAndSetup/SettingUpDatabases/ChangingDefaultDatabases/changing-to-mssql.md
en/docs/InstallAndSetup/SettingUpDatabases/ChangingDefaultDatabases/changing-to-mysql.md
en/docs/InstallAndSetup/SettingUpDatabases/ChangingDefaultDatabases/changing-to-oracle-rac.md
en/docs/InstallAndSetup/SettingUpDatabases/ChangingDefaultDatabases/changing-to-oracle.md
en/docs/InstallAndSetup/SettingUpDatabases/ChangingDefaultDatabases/changing-to-postgresql.md
en/docs/InstallAndSetup/SettingUpDatabases/ChangingDefaultDatabases/changing-to-remote-h2.md

wso2/docs-apim#629
- Update the documentation

update "Changing to IBM Informix" documentation

---

en/docs/InstallAndSetup/UpgradingWSO2APIManager/upgrading-from-200-to-300.md
en/docs/InstallAndSetup/UpgradingWSO2APIManager/upgrading-from-210-to-300.md
en/docs/InstallAndSetup/UpgradingWSO2APIManager/upgrading-from-220-to-300.md
en/docs/InstallAndSetup/UpgradingWSO2APIManager/upgrading-from-250-to-300.md
en/docs/InstallAndSetup/UpgradingWSO2APIManager/upgrading-from-260-to-300.md

Add missing table space creation part for db2 script

Add missing table space creation db2 script

---

en/docs/Administer/ProductSecurity/general-data-protection-regulation-gdpr-for-wso2-api-manager.md

Update GDPR docs

---

en/docs/InstallAndSetup/DeployingWSO2APIManager/deploying-api-manager-with-kubernetes-or-openshift-resources.md

> This document will provide the guidance to use Kubernetes (K8s) and Helm resources for container-based deployments of WSO2 API Manager (API-M).
> Link(s) to product documentation that addresses the changes of this PR. If no doc impact, enter “N/A” plus brief explanation of why …

Modifying the doc "Deploying API Manager with Kubernetes or OpenShift Resources"

---

en/docs/InstallAndSetup/UpgradingWSO2APIManager/upgrading-from-200-to-300.md
en/docs/InstallAndSetup/UpgradingWSO2APIManager/upgrading-from-210-to-300.md
en/docs/InstallAndSetup/UpgradingWSO2APIManager/upgrading-from-220-to-300.md
en/docs/InstallAndSetup/UpgradingWSO2APIManager/upgrading-from-250-to-300.md
en/docs/InstallAndSetup/UpgradingWSO2APIManager/upgrading-from-260-to-300.md

Fix for https://github.com/wso2/docs-apim/issues/634

Update IS migration client jar version matching to data sync location

---

en/docs/Administer/ProductSecurity/configuring-tls-termination.md
en/docs/Administer/ProductSecurity/enabling-java-security-manager.md
en/docs/Learn/Analytics/configuring-apim-analytics.md
en/mkdocs.yml

1. Updated the content for **Java Security Manager** - https://apim.docs.wso2.com/en/latest/Administer/ProductSecurity/enabling-java-security-manager/
2. Hid the **Configuring TLS Termination** as we do not recommend to use it. If someone needs to access it it can be access through the direct link. It is only hidden from the menu. -
https://apim.docs.wso2.com/en/latest/Administer/ProductSecurity/configuring-tls-termination/
This PR also updates the DB2 query used to create the `AM_USAGE_UPLOADED_FILES` table in the Analytics DB.
> Describe how you are implementing the solutions. Include an animated GIF or screenshot if the change affects the UI (email documentation@wso2.com to review all …

Documentation improvements for Java Security Manager and Configuring TLS Termination

---

en/docs/Administer/ProductAdministration/ManagingUsersAndRoles/ManagingUserStores/ConfigurePrimaryUserStore/configuring-a-read-only-ldap-user-store.md
en/docs/Administer/ProductAdministration/ManagingUsersAndRoles/ManagingUserStores/ConfigurePrimaryUserStore/configuring-a-read-write-ldap-user-store.md

> Update configuring a Read-Only LDAP User Store doc.

Update configuring a Read-Only LDAP User Store doc.

---

en/docs/Administer/ProductSecurity/enabling-hostname-verification.md

Enabling Hostname Verification document. …

Enabling Hostname Verification doc.

---

en/docs/Administer/ProductAdministration/ManagingUsersAndRoles/ManagingUserStores/writing-a-custom-user-store-manager.md

Writing a Custom User Store Manager …

Writing a Custom User Store Manager doc.

---

en/docs/InstallAndSetup/SettingUpDatabases/ChangingDefaultDatabases/changing-to-embedded-h2.md

Update H2 docs

---

en/docs/Learn/ConsumeAPI/Customizations/CustomizingTheAPIStore/advanced-customization.md

Added missing information about JSX overriding.

Added missing information about jsx overriding

---

en/docs/Learn/DesignAPI/CreateAPI/expose-a-soap-service-as-a-rest-api.md

Reviewed and updated "Expose a SOAP service as a REST API"

Reviewed and updated

---

en/docs/Learn/Analytics/configuring-apim-analytics.md

Fixing a typo

---

en/docs/Learn/APIController/ci-cd-with-wso2-api-management.md
en/docs/Learn/APIMonetization/monetizing-an-api.md

- Restructured the order of the content and revamped it based on an offline discussion with Dushani.
- Fix for https://github.com/wso2/docs-apim/issues/678

Restructured the content

---

en/docs/Learn/APISecurity/APIAuthentication/secure-apis-using-mutual-ssl.md

Remove redundant info statement

Remove redundant info statement

---

en/docs/GettingStarted/overview.md
en/docs/InstallAndSetup/DeployingWSO2APIManager/DistributedDeployment/configure-a-third-party-key-manager.md
en/mkdocs.yml

Corrected a typo from "Thrid" to "Third" and changes the position of the product profile page.

Corrected a Typo

---

en/docs/Learn/APIGateway/overview-of-the-api-gateway.md
en/docs/Learn/RateLimiting/engaging-a-new-throttling-policy-at-runtime.md

* Fix formatting in throttling docs.
* Remove unnecessary content in gateway docs.
> Link(s) to product documentation that …

Fix throttling and gateway docs

---

en/docs/Learn/DesignAPI/AdvancedTopics/enable-publisher-access-control-in-api-publisher-portal.md
en/mkdocs.yml

Changed the title of a page

---

en/docs/Learn/Analytics/AnalyzingAPIMStatisticsWithBatchAnalytics/viewing-api-statistics.md
en/docs/Learn/DesignAPI/AdvancedTopics/adding-an-api-state-change-workflow.md
en/docs/Learn/DesignAPI/AdvancedTopics/control-api-visibility-and-subscription-availability-in-developer-portal.md
en/docs/Learn/DesignAPI/AdvancedTopics/enabling-cors-for-apis.md
en/docs/Learn/DesignAPI/AdvancedTopics/generating-server-stubs-and-client-sdks-in-the-api-publisher.md
en/docs/Reference/samples/api-security-sample.md
en/docs/WIP/configuring-api-security-audit.md
en/mkdocs.yml

- Reviewed and updated enabling-cors-for-apis.md
- Reviewed and updated generating-server-stubs-and-client-sdks-in-the-a… …
- Reviewed and updated control-api-visibility-and-subscription-availab… …
- Reviewed and updated adding-an-api-state-change-workflow.md
- fix for https://github.com/wso2/docs-apim/issues/683
- fix for https://github.com/wso2/docs-apim/issues/682
- fix for https://github.com/wso2/docs-apim/issues/681

Doc review and bug fixes

---

en/docs/Learn/APIMonetization/monetizing-an-api.md

Fix for https://github.com/wso2/docs-apim/issues/607

fix for https://github.com/wso2/docs-apim/issues/607

---

en/docs/GettingStarted/quick-start-guide.md

Fix for https://github.com/wso2/docs-apim/issues/638

fix for https://github.com/wso2/docs-apim/issues/638

---

en/docs/Develop/using-the-registry-rest-api.md

Fix for https://github.com/wso2/docs-apim/issues/731

fix for https://github.com/wso2/docs-apim/issues/731

---

en/docs/InstallAndSetup/DeployingWSO2APIManager/SingleNode/all-in-one-deployment-overview.md
en/docs/InstallAndSetup/DeployingWSO2APIManager/SingleNode/configuring-a-single-node.md
en/docs/InstallAndSetup/DeployingWSO2APIManager/SingleNode/configuring-an-active-active-deployment.md
en/docs/InstallAndSetup/DeployingWSO2APIManager/deployment-patterns.md

Refactored deployment docs

---

en/docs/Learn/APISecurity/OAuth2/GrantTypes/kerberos-oauth2-grant.md

Fix path issue in Kerberos grant doc page

Fix path issue in Kerberos grant doc page

---

en/docs/assets/versions.json

change next version to master

---

en/docs/install-and-setup/installation-guide/installing-the-product/installing-the-binary/installing-as-a-windows-service.md

re-applying changes from PR #745

---

en/docs/learn/consume-api/customizations/log-in-to-the-dev-portal-using-social-media.md
en/mkdocs.yml

fix broken links

---

en/docs/install-and-setup/setting-up-databases/changing-default-databases/changing-to-ibm-db2.md
en/docs/install-and-setup/setting-up-databases/changing-default-databases/changing-to-ibm-informix.md
en/docs/install-and-setup/setting-up-databases/changing-default-databases/changing-to-mysql.md
en/docs/install-and-setup/setting-up-databases/changing-default-databases/changing-to-oracle-rac.md
en/docs/install-and-setup/setting-up-databases/changing-default-databases/changing-to-oracle.md
en/docs/install-and-setup/setting-up-databases/changing-default-databases/changing-to-postgresql.md
en/docs/install-and-setup/setting-up-databases/changing-default-databases/changing-to-remote-h2.md
en/mkdocs.yml

Reviewed and updated Changing Default Databases related pages

Reviewed and updated 

---

en/docs/learn/tutorials/create-and-publish-awslambda-api.md
en/mkdocs.yml

Move AWS Lambda API to learn section

---

en/docs/install-and-setup/deploying-wso2-api-manager/distributed-deployment/product-profiles.md

> Doc changes related to changes made via https://github.com/wso2/product-apim/pull/7573

Adding info on skipConfigOptimization option in profile optimization

---

en/docs/administer/product-security/logins-and-passwords/working-with-encrypted-passwords.md
en/docs/develop/wso2-admin-services.md
en/docs/learn/consume-api/manage-application/sharing-applications/sharing-applications.md

- Reviewed and updated en/docs/administer/product-security/logins-and-passwords/working-with-encrypted-passwords.md  
-- Fix for https://github.com/wso2/docs-apim/issues/496
- Reviewed and updated en/docs/develop/wso2-admin-services.md 
-- Fix for https://github.com/wso2/docs-apim/issues/432
- Bug fix for https://github.com/wso2/docs-apim/issues/642

Updates based on doc reviews and bug fixes

---

en/docs/learn/api-gateway/passing-end-user-attributes-to-the-backend/passing-enduser-attributes-to-the-backend-using-jwt.md

- Reviewed and updated en/docs/learn/api-gateway/passing-end-user-attributes-to-the-backend/passing-enduser-attributes-to-the-backend-using-jwt.md

Reviewed and Updated passing-enduser-attributes-to-the-backend-using-jwt.md

---

en/docs/develop/using-the-registry-rest-api.md
en/docs/learn/api-gateway/passing-end-user-attributes-to-the-backend/passing-enduser-attributes-to-the-backend-using-jwt.md

Fix for https://github.com/wso2/docs-apim/issues/790

Fix for https://github.com/wso2/docs-apim/issues/790

---

en/docs/learn/api-security/oauth2/grant-types/kerberos-oauth2-grant.md

> Modifying the kerberos oauth2 grant flow with token generation process  …

modifying kerberos oauth2 grant flow

---

en/docs/install-and-setup/upgrading-wso2-api-manager/upgrading-process.md

Reviewed and updated upgrading-process.md

Reviewed and updated upgrading-process.md

---

en/docs/wip/scope-role-mapping.md

This PR adds documentation content for scope mapping and role mapping features. This content should be available in 3.1.0 doc space.

Add documentation for scope, role mapping features

---

en/theme/material/partials/footer.html

Changed the year in the copyrights from 2019 to 2019-2020.

Changed the year in the copyrights

---

en/docs/install-and-setup/upgrading-wso2-api-manager/upgrading-process.md

Reviewed and updated upgrading-process.md in Master

Reviewed and updated upgrading-process.md in Master

---

en/docs/learn/analytics/managing-alerts-with-real-time-analytics/configuring-alerts.md

Update business rules related documentation …

Update business rules related documentation

---

en/docs/getting-started/about-this-release.md
en/docs/install-and-setup/perfromance-tuning-and-test-results/tuning-performance.md
en/docs/learn/api-gateway/passing-end-user-attributes-to-the-backend/passing-enduser-attributes-to-the-backend-using-jwt.md
en/docs/learn/api-security/api-authentication/secure-apis-using-api-keys.md
en/docs/learn/api-security/api-authentication/secure-apis-using-oauth2-tokens.md
en/docs/learn/api-security/oauth2/access-token-types/jwt-tokens.md
en/docs/learn/api-security/oauth2/grant-types/jwt-grant.md
en/docs/learn/api-security/openid-connect/obtaining-user-profile-information-with-openid-connect.md
en/docs/learn/consume-api/generating-sdks/write-a-client-application-using-the-sdk.md
en/docs/learn/consume-api/manage-application/generate-keys/generate-api-keys.md
en/docs/learn/tutorials/expose-a-soap-service-as-a-rest-api.md

Fix for https://github.com/wso2/docs-apim/issues/834

Changed JWT token to JWT access token

---

en/docs/install-and-setup/upgrading-wso2-api-manager/upgrading-from-200-to-300.md
en/docs/install-and-setup/upgrading-wso2-api-manager/upgrading-from-210-to-300.md
en/docs/install-and-setup/upgrading-wso2-api-manager/upgrading-from-220-to-300.md
en/docs/install-and-setup/upgrading-wso2-api-manager/upgrading-from-250-to-300.md
en/docs/install-and-setup/upgrading-wso2-api-manager/upgrading-from-260-to-300.md

Revert "Fix postgres database type in migration guide"

---

en/docs/develop/working-with-the-source-code.md
en/docs/install-and-setup/setting-up-databases/changing-default-databases/changing-to-postgresql.md

- Fix for https://github.com/wso2/docs-apim/issues/840 in 3.0.0
- Fix for https://github.com/wso2/docs-apim/issues/845 in 3.0.0

fix for https://github.com/wso2/docs-apim/issues/840 in 3.0.0

---

en/theme/material/base.html

fix typo in version text

---

en/docs/learn/extensions/managing-workflow-extension/configuring-http-redirection-for-workflows.md

fixing incorrect URL

---

en/docs/install-and-setup/deploying-wso2-api-manager/distributed-deployment/product-profiles.md

>  Add wum update related changes regarding new --skipConfigOptimization option.  …

Add wum update related changes on new skipConfigOptimization option

---

en/docs/learn/consume-api/manage-application/advanced-topics/add-custom-attributes-to-applications.md

This PR documents the use of default attribute in application attributes

Document use of default attribute in application attributes

---

en/docs/learn/api-controller/migrating-apis-to-different-environments.md

Formatting issue

---

en/theme/material/base.html

Fix for https://github.com/wso2/docs-apim/issues/838 , No other dependencies can merge immediately

fix search by verson issue

---

en/mkdocs.yml
en/theme/material/base.html

Add algolia search init parameter to use facet defined for search only docs related to **next** doc space
Fix for https://github.com/wso2/docs-apim/issues/838
Depends on https://github.com/algolia/docsearch-configs/pull/1798

Improvements to Algolia search

---

en/mkdocs.yml
en/theme/material/base.html

Reverts wso2/docs-apim#876
reverting the PR since Algolia has not yet indexed the /next doc space, until then revert the change

Revert "Improvements to Algolia search"

---

en/docs/administer/product-security/enabling-java-security-manager.md

update security manager policy

---

en/docs/learn/extensions/managing-workflow-extension/configuring-http-redirection-for-workflows.md

fixing broken links

---

en/docs/learn/extensions/managing-workflow-extension/configuring-http-redirection-for-workflows.md

fix call back URL + broken links

---

en/docs/administer/product-administration/monitoring/logging/setting-up-logging.md

> Correct wso2carbon.log file location detail under topic: Enable Gateway wire logs

Setting up logs - minor detail correction

---

en/docs/learn/api-controller/building-jenkins-ci-cd-pipeline-for-dev-first-approach.md
en/docs/learn/api-controller/ci-cd-with-wso2-api-management.md
en/docs/learn/api-controller/getting-started-with-wso2-api-controller.md
en/docs/learn/api-controller/migrating-apis-to-different-environments.md

This PR modifies docs for the 3.1.0 release of the apictl

Modify APICTL docs for the 3.1.0 release

---

en/docs/learn/consume-api/manage-application/advanced-topics/add-custom-attributes-to-applications.md

Document use of default attribute in application attributes

 Document use of default attribute in application attributes 

---

en/docs/learn/analytics/default-ports-of-wso2-api-m-analytics.md

This is the PR for 3.0 branch corresponding to https://github.com/wso2/docs-apim/pull/892

Add dashboard portal port info to docs.

---

en/docs/install-and-setup/installation-guide/basic-health-checks.md

Adding health checking information for APIM Analytics profiles.
Adding missing information to the doc.

Adds APIM analytics health check instructions

---

en/docs/assets/attachments/103335136/db2.sql
en/docs/assets/attachments/103335136/mssql.sql
en/docs/assets/attachments/103335136/mysql.sql
en/docs/assets/attachments/103335136/oracle.sql
en/docs/assets/attachments/103335136/postgresql.sql

Add missing database scripts for geo location database setup doc
This PR related to https://github.com/wso2/docs-apim/pull/902
> …

Add missing database scripts for geo location database setup doc

---

en/docs/develop/analytics-rest-api.md
en/mkdocs.yml

Siddhi store rest api guide for 3.0

---

en/docs/learn/analytics/analyzing-apim-statistics-with-batch-analytics/viewing-api-statistics.md

Adds documentation for sync button in the analytics dashboards.
Corrects a typo.
Adding missing information and enhancing the doc.

Adds documentation for sync button in the analytics dashboards.

---

en/docs/learn/extensions/managing-workflow-extension/configuring-workflows-in-a-cluster.md

>https://localhost:9443/store/site/blocks/workflow/workflow-listener/ajax/workflow-listener.jag has moved to an admin REST API in 3.x

fix callback endpoint config

---

en/docs/learn/extensions/managing-workflow-extension/configuring-workflows-in-a-cluster.md

fix config change in workflow cluster doc 3.0.0

---

en/docs/develop/analytics-rest-api.md
en/docs/install-and-setup/deploying-wso2-api-manager/distributed-deployment/configuring-wso2-identity-server-as-a-key-manager.md

- Did the same changes based on https://github.com/wso2/docs-apim/pull/836 for 3.1.0 docs
- Doc review for #910 analytics-rest-api.md

Doc Review

---

en/docs/administer/product-security/enabling-java-security-manager.md

Remove additional lines which caused not properly rendering page
https://github.com/wso2/docs-apim/pull/888

Remove additional lines which caused not properly rendering page

---

en/docs/install-and-setup/deploying-wso2-api-manager/distributed-deployment/product-profiles.md

Update the docs with WSO2-CARBON-UPDATE-4.5.0-0162 re-released date. (The update was not correctly live wum-synced on that previously mentioned date)
> Link(s) to product documentation that addresses the changes of this PR. If no doc impact, enter “N/A” plus brief explanation of why …

Update the docs with WSO2-CARBON-UPDATE-4.5.0-0162 re-released date

---

en/docs/learn/analytics/publishing-custom-data.md
en/mkdocs.yml

This PR 
- restructures the analytics documents.
- adds guide to publish custom attributes to analytics server

Add custom attribute publishing doc

---

en/mkdocs.yml

List the unlisted 'Monthly API Usage Report' documentation …

List the unlisted 'Monthly API Usage Report' documentation

---

en/docs/install-and-setup/installation-guide/basic-health-checks.md

Adds basic health check docs for apim analytics profiles.
Updating 3.0.0 docs.

Adds basic health check docs for apim analytics profiles.

---

en/docs/getting-started/quick-start-guide.md
en/docs/learn/api-controller/ci-cd-with-wso2-api-management.md
en/docs/learn/api-controller/getting-started-with-wso2-api-controller.md

Adding fixes related to https://github.com/wso2/product-apim-tooling/issues/246

Update docs matching to modified add environment commands

---

en/docs/install-and-setup/upgrading-wso2-api-manager/upgrading-from-300-to-310.md

Adding a more descriptive note

Adding a more descriptive note

---

en/docs/learn/api-controller/getting-started-with-wso2-api-controller.md

Fixes related to https://github.com/wso2/product-apim-tooling/issues/246

Modify docs mentioning Windows commands and add-env modifications

---

en/docs/install-and-setup/upgrading-wso2-api-manager/upgrading-from-250-to-310.md

Fixing the formatting issue

---

en/docs/getting-started/about-this-release.md
en/docs/learn/consume-api/customizations/customizing-the-developer-portal/customize-api-listing/categorizing-and-grouping-apis/api-category-based-grouping.md
en/docs/learn/consume-api/customizations/customizing-the-developer-portal/customize-api-listing/categorizing-and-grouping-apis/tagwise-based-grouping.md
en/docs/learn/consume-api/discover-apis/api-recommendations.md

- Updated the About this Release page for 3.1.0
- Changed Tagwise to Tag wise
- Formatted content

Updated for 3.1.0

---

en/mkdocs.yml

Updated based on the content that was moved to the /wip folder.

Updated the mkdoc.yml

---

en/docs/wip/need-to-update/upgrading-wso2-api-manager/upgrading-from-300-to-310.md

Changing the incorrect version

Chaning the incorrect version

---

en/mkdocs.yml

fix build break

---

en/docs/install-and-setup/deploying-wso2-api-manager/security-guidelines-for-production-deployment.md

>  Reviewing and fixing 'Security Guidelines for Production Deployment' doc
> Link to the PR for changes to the training content …

 Reviewing and fixing 'Security Guidelines for Production..' doc

---

en/docs/learn/api-gateway/passing-end-user-attributes-to-the-backend/passing-enduser-attributes-to-the-backend-using-jwt.md

add jwt generation related changes

---

en/docs/assets/versions.json

add 3.1.0 version

---

en/docs/assets/versions.json

fixed syntax issue

---

en/mkdocs.yml
en/theme/material/base.html

change parameters to new 3.1.0 version

---

en/docs/getting-started/about-this-release.md
en/docs/getting-started/quick-start-guide.md
en/mkdocs.yml

remove duplicate sentence + fix broken links

---

en/docs/learn/api-controller/advanced-topics/configuring-environment-specific-parameters.md
en/docs/learn/api-controller/building-jenkins-ci-cd-pipeline-for-dev-first-approach.md
en/docs/learn/api-controller/ci-cd-with-wso2-api-management.md
en/docs/learn/api-controller/importing-apis-via-dev-first-approach.md
en/docs/learn/api-controller/migrating-apis-to-different-environments.md
en/mkdocs.yml

Fixes: https://github.com/wso2/product-apim-tooling/issues/270
Move the content on **Configuring Environment Specific Parameters** under **Advanced Topics**.
- Created a new page titled **Configuring Environment Specific Parameters** under **Advanced Topics** as shown below.
- Removed the repetitive content related to the above topic from other pages and referred to this page using Tips.
- Removed the section named "Configure Environment Specific Details" from the page **Importing APIs Via Dev First Approach**. Updated the reference within the content in the flags to point to the newly created page as shown below.
- Removed the section named "Configuring Environment Specific Parameters" from the page **Migrating APIs to Different Environments** and referred to the new page within a Note. …

Modifying documentation on Configuring Environment Specific Parameters

---

en/docs/learn/api-security/configuring-api-security-audit.md

Fixes [wso2/docs-apim#992](https://github.com/wso2/docs-apim/issues/992)
> Link(s) to product documentation that addresses the …

Fixing issue with bash tabs

---

en/docs/getting-started/quick-start-guide.md
en/docs/learn/api-controller/getting-started-with-wso2-api-controller.md

Fixes related to https://github.com/wso2/product-apim-tooling/issues/246

Modify add-env warning

---

en/docs/learn/api-controller/importing-apis-via-dev-first-approach.md
en/docs/learn/api-controller/migrating-apis-to-different-environments.md
en/docs/learn/api-controller/migrating-applications-to-different-environments.md

Fixes related to https://github.com/wso2/product-apim-tooling/issues/258

Add details on how to add scopes for a resource

---

en/docs/install-and-setup/upgrading-wso2-api-manager/upgrading-from-200-to-300.md
en/docs/install-and-setup/upgrading-wso2-api-manager/upgrading-from-210-to-300.md
en/docs/install-and-setup/upgrading-wso2-api-manager/upgrading-from-220-to-300.md
en/docs/install-and-setup/upgrading-wso2-api-manager/upgrading-from-250-to-300.md
en/docs/install-and-setup/upgrading-wso2-api-manager/upgrading-from-260-to-300.md

> Update oracle migration scrip

Update oracle migration scripts in docs

---

en/mkdocs.yml

Updated the site_url

---

en/docs/learn/analytics/configuring-apim-analytics.md

Update configuring-apim-analytics.md documentation …

Update configuring-apim-analytics.md documentation

---

en/docs/install-and-setup/upgrading-wso2-api-manager/upgrading-from-200-to-300.md
en/docs/install-and-setup/upgrading-wso2-api-manager/upgrading-from-210-to-300.md
en/docs/install-and-setup/upgrading-wso2-api-manager/upgrading-from-220-to-300.md
en/docs/install-and-setup/upgrading-wso2-api-manager/upgrading-from-250-to-300.md
en/docs/install-and-setup/upgrading-wso2-api-manager/upgrading-from-260-to-300.md

This PR modifies registry versioning related note in migration docs

Modify registry versioning related note in migration docs

---

en/docs/learn/api-controller/building-jenkins-ci-cd-pipeline-for-dev-first-approach.md
en/docs/learn/api-controller/ci-cd-with-wso2-api-management.md
en/docs/learn/api-controller/getting-started-with-wso2-api-controller.md

This PR modifies docs mentioning the APIM version to avoid issues

Modify docs mentioning the APIM version to avoid issues

---

en/docs/learn/api-security/threat-protection/bot-detection.md

- Updated the wording to avoid confusion
- Updated the file paths

Updated the wording

---

en/docs/learn/api-security/threat-protection/bot-detection.md

fix for https://github.com/wso2/docs-apim/issues/1059

fix for https://github.com/wso2/docs-apim/issues/1059

---

en/docs/wip/need-to-update/upgrading-wso2-api-manager/upgrading-from-200-to-310.md
en/docs/wip/need-to-update/upgrading-wso2-api-manager/upgrading-from-210-to-310.md
en/docs/wip/need-to-update/upgrading-wso2-api-manager/upgrading-from-220-to-310.md
en/docs/wip/need-to-update/upgrading-wso2-api-manager/upgrading-from-250-to-310.md
en/docs/wip/need-to-update/upgrading-wso2-api-manager/upgrading-from-260-to-310.md

Change AM_MONETIZATION_USAGE_PUBLISHER table name

---

en/docs/wip/need-to-update/upgrading-wso2-api-manager/upgrading-from-200-to-310.md
en/docs/wip/need-to-update/upgrading-wso2-api-manager/upgrading-from-210-to-310.md
en/docs/wip/need-to-update/upgrading-wso2-api-manager/upgrading-from-220-to-310.md
en/docs/wip/need-to-update/upgrading-wso2-api-manager/upgrading-from-260-to-310.md

Remove 'SEQUENCE' key word from Oracle script

---

en/docs/administer/product-configurations/adding-internationalization.md

Doc review for https://github.com/wso2/docs-apim/pull/829 and added for 3.1.0 as well.

Doc review for https://github.com/wso2/docs-apim/pull/829

---

en/docs/learn/design-api/advanced-topics/enable-publisher-access-control-in-api-publisher-portal.md

APIs are visible to users with either API-M Admin permission or admin role. This is mention in the doc clearly.
> Link(s) to …

Fixed the doc with correct permission and role

---

en/docs/learn/design-api/mock-api/create-a-mock-api-with-an-inline-script.md

Reviewed [1], updated and formatted the document.
[1] https://apim.docs.wso2.com/en/latest/learn/design-api/mock-api/create-a-mock-api-with-an-inline-script/

Doc review for https://github.com/wso2/docs-apim/pull/1086

---

en/docs/learn/analytics/configuring-apim-analytics.md

This PR updates APIM IdP client configuration documentation. This also fixes https://github.com/wso2/docs-apim/issues/937.
> Link …

Update APIM IdP client configuration documentation.

---

en/docs/learn/analytics/configuring-apim-analytics.md

Update analytics related database configuration documentation. …

Update analytics related database configuration documentation.

---

en/docs/wip/need-to-update/upgrading-wso2-api-manager/upgrading-from-260-to-310.md

> Cannot create an index when it is already available and so this has to be checked before creating an index. This happens in apim 260-> 310 process, if the existing 210 setup had been migrated to 260 from a prior version earlier.
Below are the errors occurred in mysql.
ERROR 1061 (42000): Duplicate key name 'IDX_RID'
ERROR 1061 (42000): Duplicate key name 'IDX_USER'
ERROR 1061 (42000): Duplicate key name 'IDX_RS'
ERROR 1061 (42000): Duplicate key name 'IDX_PT'
> Describe how you are implementing the solutions. Include an animated GIF or screenshot if the change affects the UI (email documentation@wso2.com to review all UI text). Include a link to a Markdown file or Google doc if the …

Fix issue of index creation when already exists in 260 to 310 migration

---

en/docs/wip/need-to-update/upgrading-wso2-api-manager/upgrading-from-260-to-310.md

Droping procedure after using

---

en/docs/administer/product-security/general-data-protection-regulation-gdpr-for-wso2-api-manager.md
en/docs/learn/analytics/general-data-protection-regulation-gdpr-for-wso2-api-manager-analytics.md
en/mkdocs.yml

Update the outdated GDPR for analytics related documentation.

Update the outdated GDPR for analytics related documentation. 

---

en/docs/administer/product-security/general-data-protection-regulation-gdpr-for-wso2-api-manager.md
en/docs/learn/analytics/general-data-protection-regulation-gdpr-for-wso2-api-manager-analytics.md
en/mkdocs.yml

Update the outdated GDPR for analytics related documentation.

Update the outdated GDPR for analytics related documentation.

---

en/docs/learn/design-api/publish-api/publish-to-multiple-external-api-stores.md

Reference of external devportal  url port number is misleading.
> Link(s) to product documentation that addresses the changes …

External devportal url correction

---

en/docs/wip/need-to-update/upgrading-wso2-api-manager/upgrading-from-200-to-310.md
en/docs/wip/need-to-update/upgrading-wso2-api-manager/upgrading-from-210-to-310.md
en/docs/wip/need-to-update/upgrading-wso2-api-manager/upgrading-from-220-to-310.md
en/docs/wip/need-to-update/upgrading-wso2-api-manager/upgrading-from-250-to-310.md
en/docs/wip/need-to-update/upgrading-wso2-api-manager/upgrading-from-260-to-310.md
en/docs/wip/need-to-update/upgrading-wso2-api-manager/upgrading-from-300-to-310.md

Adding a note to remove the step from migration-config.yaml which affects for migration of versioning APIs.
Related PR:
https://github.com/wso2-extensions/identity-migration-resources/pull/83

Adding note to remove the step from migration-config.yaml which effects for versioning

---

en/docs/learn/api-controller/getting-started-with-wso2-api-controller.md

This PR   
1. Add details on how to query when listing APIs (wso2/product-apim-tooling#282)
2. Add details and example on APIs and apps listing limit support (wso2/product-apim-tooling#281)
3. Add details on --format support for list APIs Apps and Envs (wso2/product-apim-tooling#279)

Updated the doc about new flags,format options and search for APIs

---

en/docs/wip/need-to-update/upgrading-wso2-api-manager/upgrading-from-300-to-310.md

Fix typo in docs

---

en/docs/learn/api-controller/getting-started-with-wso2-api-controller.md

Fixes related to https://github.com/wso2/product-apim-tooling/issues/290

Add changes related to api state change command

---

en/docs/wip/need-to-update/upgrading-wso2-api-manager/upgrading-from-200-to-310.md
en/docs/wip/need-to-update/upgrading-wso2-api-manager/upgrading-from-210-to-310.md
en/docs/wip/need-to-update/upgrading-wso2-api-manager/upgrading-from-220-to-310.md
en/docs/wip/need-to-update/upgrading-wso2-api-manager/upgrading-from-250-to-310.md
en/docs/wip/need-to-update/upgrading-wso2-api-manager/upgrading-from-260-to-310.md
en/docs/wip/need-to-update/upgrading-wso2-api-manager/upgrading-from-300-to-310.md

Adding a note to remove the step from migration-config.yaml which affects for migration of versioning APIs.
Related PR:
wso2-extensions/identity-migration-resources#83

Adding note to remove the step from migration-config.yaml which effects for versioning 

---

en/docs/wip/need-to-update/upgrading-wso2-api-manager/upgrading-from-210-to-310.md
en/docs/wip/need-to-update/upgrading-wso2-api-manager/upgrading-from-220-to-310.md
en/docs/wip/need-to-update/upgrading-wso2-api-manager/upgrading-from-250-to-310.md
en/docs/wip/need-to-update/upgrading-wso2-api-manager/upgrading-from-260-to-310.md
en/docs/wip/need-to-update/upgrading-wso2-api-manager/upgrading-from-300-to-310.md

Fix typo in version number

---

en/docs/wip/need-to-update/upgrading-wso2-api-manager/upgrading-from-200-to-310.md
en/docs/wip/need-to-update/upgrading-wso2-api-manager/upgrading-from-210-to-310.md
en/docs/wip/need-to-update/upgrading-wso2-api-manager/upgrading-from-220-to-310.md
en/docs/wip/need-to-update/upgrading-wso2-api-manager/upgrading-from-250-to-310.md
en/docs/wip/need-to-update/upgrading-wso2-api-manager/upgrading-from-260-to-310.md
en/docs/wip/need-to-update/upgrading-wso2-api-manager/upgrading-from-300-to-310.md

Fix typo in grammar

---

en/docs/develop/product-apis/devportal-apis/devportal-v1/guide.md
en/docs/develop/product-apis/publisher-apis/publisher-v1/guide.md

Sample DCR endpoint had incorrect version (1.0) this was corrected to v0.16

Update 310 DCR versions in guide.md

---

en/docs/wip/need-to-update/upgrading-wso2-api-manager/upgrading-from-1100-to-310.md
en/docs/wip/need-to-update/upgrading-wso2-api-manager/upgrading-from-200-to-310.md

Fix incorrect links

---

en/mkdocs.yml

Fixing the 'nav' issue at mkdocs.yml file

Fixing issue in mkdocs.yml

---

en/mkdocs.yml

converting caps lock file names to lowercase

---

en/docs/install-and-setup/upgrading-wso2-api-manager/upgrading-from-191-to-310.md
en/docs/install-and-setup/upgrading-wso2-api-manager/upgrading-from-200-to-310.md
en/docs/install-and-setup/upgrading-wso2-api-manager/upgrading-from-210-to-310.md
en/docs/install-and-setup/upgrading-wso2-api-manager/upgrading-from-220-to-310.md
en/docs/install-and-setup/upgrading-wso2-api-manager/upgrading-from-250-to-310.md
en/docs/install-and-setup/upgrading-wso2-api-manager/upgrading-from-260-to-310.md
en/docs/install-and-setup/upgrading-wso2-api-manager/upgrading-from-300-to-310.md
en/docs/install-and-setup/upgrading-wso2-is-as-key-manager/upgrading-from-is-km-500-to-5100.md
en/docs/install-and-setup/upgrading-wso2-is-as-key-manager/upgrading-from-is-km-510-to-5100.md
en/docs/install-and-setup/upgrading-wso2-is-as-key-manager/upgrading-from-is-km-520-to-5100.md
en/docs/install-and-setup/upgrading-wso2-is-as-key-manager/upgrading-from-is-km-530-to-5100.md
en/docs/install-and-setup/upgrading-wso2-is-as-key-manager/upgrading-from-is-km-550-to-5100.md
en/docs/install-and-setup/upgrading-wso2-is-as-key-manager/upgrading-from-is-km-560-to-5100.md
en/docs/install-and-setup/upgrading-wso2-is-as-key-manager/upgrading-from-is-km-570-to-5100.md
en/docs/install-and-setup/upgrading-wso2-is-as-key-manager/upgrading-from-is-km-590-to-5100.md

This PR will fix the formatting issues and making content more clearly

Fixing formatting issues and making content clearly

---

en/docs/install-and-setup/upgrading-wso2-api-manager/upgrading-from-300-to-310.md

Fixing doc issues

---

en/docs/wip/need-to-update/upgrading-wso2-api-manager/upgrading-from-200-to-310.md
en/docs/wip/need-to-update/upgrading-wso2-api-manager/upgrading-from-210-to-310.md
en/docs/wip/need-to-update/upgrading-wso2-api-manager/upgrading-from-220-to-310.md
en/docs/wip/need-to-update/upgrading-wso2-api-manager/upgrading-from-250-to-310.md
en/docs/wip/need-to-update/upgrading-wso2-api-manager/upgrading-from-260-to-310.md
en/docs/wip/need-to-update/upgrading-wso2-api-manager/upgrading-from-300-to-310.md

This PR will remove the unwanted step from the migration client.

Adding one step to note which should need to remove from migration-config.yaml file

---

en/docs/install-and-setup/upgrading-wso2-api-manager/upgrading-from-200-to-310.md
en/docs/install-and-setup/upgrading-wso2-api-manager/upgrading-from-250-to-310.md

Fixing ordering issue in analytics migration steps

---

README.md

- fix for https://github.com/wso2/docs-apim/issues/1196

fix for https://github.com/wso2/docs-apim/issues/1196

---

en/docs/learn/api-gateway/message-mediation/adding-dynamic-endpoints.md
en/docs/learn/api-gateway/message-mediation/transforming-api-message-payload.md

- fix for #1147
- replaced base_url with base_path

Bug fixes for 3.0.0

---

en/docs/install-and-setup/setup/distributed-deployment/understanding-the-distributed-deployment-of-wso2-api-m.md

Restructure to match new configs and remove non relevant info …

Restructure to match new configs

---

en/docs/learn/analytics/configuring-keystores-in-apim-analytics.md

Fix for https://github.com/wso2/docs-apim/issues/1129

Fix for https://github.com/wso2/docs-apim/issues/1129 - 3.1.0

---

en/docs/install-and-setup/upgrading-wso2-api-manager/upgrading-from-200-to-310.md
en/docs/install-and-setup/upgrading-wso2-api-manager/upgrading-from-210-to-310.md
en/docs/install-and-setup/upgrading-wso2-api-manager/upgrading-from-220-to-310.md
en/docs/install-and-setup/upgrading-wso2-api-manager/upgrading-from-250-to-310.md
en/docs/install-and-setup/upgrading-wso2-api-manager/upgrading-from-260-to-310.md
en/docs/install-and-setup/upgrading-wso2-api-manager/upgrading-from-300-to-310.md

Fixing typo fixes missed when moving from WIP folder

---

en/docs/learn/analytics/configuring-keystores-in-apim-analytics.md

Fix for https://github.com/wso2/docs-apim/issues/1129

fix for https://github.com/wso2/docs-apim/issues/1129 - master

---

en/docs/learn/design-api/api-versioning/enabling-notifications.md

"Creating Users using the Ask Password Option" this link is not working, updated accordingly
> Link(s) to product documentation …

link not woring

---

en/docs/learn/design-api/api-versioning/enabling-notifications.md

fix for https://github.com/wso2/docs-apim/issues/1238

fix for https://github.com/wso2/docs-apim/issues/1238

---

en/docs/administer/managing-users-and-roles/managing-permissions.md
en/docs/administer/managing-users-and-roles/managing-user-stores/configure-primary-user-store/configuring-a-read-only-ldap-user-store.md
en/docs/administer/managing-users-and-roles/managing-user-stores/configure-primary-user-store/configuring-a-read-write-active-directory-user-store.md
en/docs/administer/managing-users-and-roles/managing-user-stores/configure-primary-user-store/configuring-a-read-write-ldap-user-store.md
en/docs/administer/managing-users-and-roles/managing-users.md
en/docs/develop/customizations/log-in-to-the-dev-portal-using-social-media.md
en/docs/develop/extending-api-manager/saml2-sso/configuring-external-idp-through-identity-server-for-sso.md
en/docs/develop/extending-api-manager/saml2-sso/configuring-identity-server-as-idp-for-sso.md
en/docs/install-and-setup/setup/security/identity-management-for-the-api-dev-portal.md
en/docs/install-and-setup/setup/security/logins-and-passwords/maintaining-logins-and-passwords.md
en/docs/learn/api-security/authorization/role-based-access-control-using-xacml.md
en/docs/learn/api-security/oauth2/grant-types/authorization-code-grant.md
en/docs/learn/api-security/oauth2/grant-types/client-credentials-grant.md
en/docs/learn/api-security/oauth2/grant-types/jwt-grant.md
en/docs/learn/api-security/oauth2/securing-oauth-token-with-hmac-validation.md
en/docs/learn/api-security/openid-connect/obtaining-user-profile-information-with-openid-connect.md
en/docs/learn/design-api/api-versioning/enabling-notifications.md

- fix for https://github.com/wso2/docs-apim/issues/1240

fix for https://github.com/wso2/docs-apim/issues/1240

---

en/docs/install-and-setup/upgrading-wso2-api-manager/upgrading-from-1100-to-300.md
en/docs/install-and-setup/upgrading-wso2-api-manager/upgrading-from-191-to-300.md
en/docs/install-and-setup/upgrading-wso2-api-manager/upgrading-from-200-to-300.md
en/docs/install-and-setup/upgrading-wso2-api-manager/upgrading-from-210-to-300.md
en/docs/install-and-setup/upgrading-wso2-api-manager/upgrading-from-220-to-300.md
en/docs/install-and-setup/upgrading-wso2-api-manager/upgrading-from-250-to-300.md
en/docs/install-and-setup/upgrading-wso2-api-manager/upgrading-from-260-to-300.md

fixing links and fix for https://github.com/wso2/docs-apim/issues/1149

fix for https://github.com/wso2/docs-apim/issues/1149

---

en/docs/assets/attachments/install-and-setup/apim200_to_apim310_gateway_artifact_migrator.sh
en/docs/assets/attachments/install-and-setup/apim210_to_apim310_gateway_artifact_migrator.sh
en/docs/assets/attachments/install-and-setup/apim220_to_apim310_gateway_artifact_migrator.sh

This PR will fix the issue in gateway_artifact_migrator.sh script when it runs in mac os
related issue: https://github.com/wso2/product-apim/issues/8160

Fixing issue in gateway_artifact_migrator.sh script

---

en/docs/install-and-setup/setup/deployment-best-practices/security-guidelines-for-production-deployment.md

- fix for https://github.com/wso2/docs-apim/issues/816

fix for https://github.com/wso2/docs-apim/issues/816 - 3.1.0

---

en/docs/install-and-setup/deploying-wso2-api-manager/security-guidelines-for-production-deployment.md

fix for https://github.com//issues/816

fix for https://github.com//issues/816

---

en/docs/install-and-setup/deploying-wso2-api-manager/security-guidelines-for-production-deployment.md

- fix for https://github.com/wso2/docs-apim/issues/816

fix for https://github.com/wso2/docs-apim/issues/816

---

en/docs/learn/analytics/analyzing-apim-statistics-with-batch-analytics/viewing-api-statistics.md
en/docs/learn/analytics/configuring-apim-analytics.md

Adds instructions on configuring User-Agent parser.
- Ran FindSecurityBugs plugin and verified report? N/A
https://github.com/wso2/analytics-apim/pull/1122

Adds documentation for configuring User-Agent parser.

---

en/docs/install-and-setup/setup/distributed-deployment/deploying-wso2-api-m-in-a-distributed-setup.md
en/docs/install-and-setup/upgrading-wso2-api-manager/upgrading-from-1100-to-310.md
en/docs/install-and-setup/upgrading-wso2-api-manager/upgrading-from-191-to-310.md
en/docs/install-and-setup/upgrading-wso2-api-manager/upgrading-from-200-to-310.md
en/docs/install-and-setup/upgrading-wso2-api-manager/upgrading-from-210-to-310.md
en/docs/install-and-setup/upgrading-wso2-api-manager/upgrading-from-220-to-310.md
en/docs/install-and-setup/upgrading-wso2-api-manager/upgrading-from-250-to-310.md
en/docs/install-and-setup/upgrading-wso2-api-manager/upgrading-from-260-to-310.md
en/docs/install-and-setup/upgrading-wso2-api-manager/upgrading-from-300-to-310.md
en/docs/learn/consume-api/manage-subscription/subscribe-to-an-api.md
en/docs/learn/design-api/mock-api/create-a-mock-api-with-an-inline-script.md
en/docs/learn/design-api/mock-api/deploy-and-test-mock-apis.md
en/docs/learn/tutorials/expose-a-soap-service-as-a-rest-api.md

- fix for https://github.com/wso2/docs-apim/issues/1255

fix for https://github.com/wso2/docs-apim/issues/1255

---

en/docs/learn/api-controller/importing-apis-via-dev-first-approach.md
en/docs/learn/api-gateway/response-caching.md
en/docs/learn/api-security/api-authentication/secure-apis-using-oauth2-tokens.md
en/docs/learn/design-api/advanced-topics/enabling-cors-for-apis.md
en/docs/learn/design-api/create-api/create-a-rest-api-from-a-swagger-definition.md
en/docs/learn/rate-limiting/setting-throttling-limits.md

- Fix for formatting issues in https://github.com/wso2/docs-apim/pull/1157
- Fixed broken links

Fix for formatting issues in https://github.com/wso2/docs-apim/pull/1157

---

en/docs/learn/tutorials/create-and-publish-websocket-api.md

fix for https://github.com/wso2/docs-apim/issues/1254

fix for https://github.com/wso2/docs-apim/issues/1254

---

en/docs/install-and-setup/upgrading-wso2-api-manager/upgrading-from-200-to-310.md
en/docs/install-and-setup/upgrading-wso2-api-manager/upgrading-from-210-to-310.md
en/docs/install-and-setup/upgrading-wso2-api-manager/upgrading-from-220-to-310.md
en/docs/install-and-setup/upgrading-wso2-api-manager/upgrading-from-250-to-310.md
en/docs/install-and-setup/upgrading-wso2-api-manager/upgrading-from-260-to-310.md
en/docs/install-and-setup/upgrading-wso2-api-manager/upgrading-from-300-to-310.md

Fix migration related doc issues

Fix migration related doc issues

---

en/docs/administer/logging-and-monitoring/logging/monitoring-http-access-logs.md

fix for https://github.com/wso2/docs-apim/issues/1278

fix for https://github.com/wso2/docs-apim/issues/1278

---

en/docs/install-and-setup/upgrading-wso2-api-manager/upgrading-from-200-to-310.md
en/docs/install-and-setup/upgrading-wso2-api-manager/upgrading-from-210-to-310.md
en/docs/install-and-setup/upgrading-wso2-api-manager/upgrading-from-220-to-310.md
en/docs/install-and-setup/upgrading-wso2-api-manager/upgrading-from-250-to-310.md
en/docs/install-and-setup/upgrading-wso2-api-manager/upgrading-from-260-to-310.md
en/docs/install-and-setup/upgrading-wso2-api-manager/upgrading-from-300-to-310.md

Fix issues/improvements in migration docs

---

en/docs/learn/consume-api/manage-application/sharing-applications/sharing-applications.md

fix for https://github.com/wso2/docs-apim/issues/1229

fix for https://github.com/wso2/docs-apim/issues/1229

---

en/docs/learn/api-controller/building-jenkins-ci-cd-pipeline-for-dev-first-approach.md
en/docs/learn/api-controller/ci-cd-with-wso2-api-management.md
en/docs/learn/api-controller/getting-started-with-wso2-api-controller.md
en/docs/learn/api-controller/migrating-api-products-to-different-environments.md
en/docs/learn/api-controller/migrating-apis-to-different-environments.md

This PR updates APICTL related docs for 3.2.0 release.

Update APICTL docs for 3.2.0 release

---

en/mkdocs.yml

Reapplying changes that had got missed based on
https://github.com/wso2/docs-apim/pull/1259

Reapplying https://github.com/wso2/docs-apim/pull/1259

---

en/docs/learn/api-security/api-authentication/secure-apis-using-mutual-ssl.md

fix for https://github.com/wso2/docs-apim/issues/1317

fix for https://github.com/wso2/docs-apim/issues/1317

---

en/docs/install-and-setup/setup/distributed-deployment/deploying-wso2-api-m-in-a-distributed-setup.md

Adding a missing statement and fixing the issue in a link in deploying distributed setup

Adding missing statement

---

en/docs/administer/product-security/identity-management-for-the-api-dev-portal.md

Added changes to correct email address to be sync to all WSO2 features and it sholud be dummy. …

Forgot Username-Email ID correction.

---

en/docs/develop/customizations/customizing-the-developer-portal/enabling-or-disabling-self-signup.md

Adding a User Signup Workflow URL is missing 
https://apim.docs.wso2.com/en/latest/develop/customizations/customizing-the-developer-portal/enabling-or-disabling-self-signup/

Adding a User Signup Workflow URL is missing

---

en/docs/getting-started/overview.md

Grammatical corrections to improve readability.
Readability improvements.
Fixed misspelled words
NA
Documentation correction and  improvements
NA
Direct correction
NA
NA
NA
NA
- Ran FindSecurityBugs plugin and verified report? yes/no
NA
NA
NA
NA
NA

Grammatical corrections

---

README.md

Grammar and Lint fix to the `README.md`.

[Improvised][Master] README

---

en/docs/index.md

Grammar & Lint Fixes to the Index Page of `3.1.0` Branch. 
Please find the respective PR for the `master` branch #1300

[Improvised][3.1] Grammar & Lint Fixes to Index Page

---

en/docs/index.md

Grammar & Lint Fixes to the Index Page

[Improvised][Master] Grammar & Lint Fixes to Index Page

---

en/docs/install-and-setup/setup/single-node/configuring-an-active-active-deployment.md

Fix https://github.com/wso2/product-apim/issues/8040
Add missing steps on publishing throttle data events to each other in an active-active deployment. Move step to configuring second node after database configuration step.

Add missing step in active active deployment

---

en/docs/administer/multitenancy/configuring-the-tenant-loading-policy.md

fix for https://github.com/wso2/docs-apim/issues/1361

fix for https://github.com/wso2/docs-apim/issues/1361

---

en/docs/install-and-setup/deploying-wso2-api-manager/single-node/all-in-one-deployment-overview.md

- fix for https://github.com/wso2/docs-apim/issues/1359

fix for https://github.com/wso2/docs-apim/issues/1359

---

en/docs/install-and-setup/setup/distributed-deployment/product-profiles.md

fix for https://github.com/wso2/docs-apim/issues/1252

fix for https://github.com/wso2/docs-apim/issues/1252

---

en/docs/install-and-setup/upgrading-wso2-api-manager/upgrading-from-250-to-300.md

fix for https://github.com/wso2/docs-apim/issues/1367

fix for https://github.com/wso2/docs-apim/issues/1367

---

en/docs/install-and-setup/setup/distributed-deployment/deploying-wso2-api-m-in-a-distributed-setup.md

Resolves https://github.com/wso2/docs-apim/issues/1348

Fix for #1348

---

en/docs/develop/product-apis/publisher-v1.yaml

Resolves https://github.com/wso2/docs-apim/issues/1124 …

Fixing publisher APIs POST: /apis resource's payload.

---

en/docs/develop/product-apis/publisher-apis/publisher-v1/publisher-v1.yaml

Fixing publisher v1 API post /apis request payload. …

Fixing publisher v1 API post /apis request payload.

---

en/docs/install-and-setup/setup/deployment-best-practices/production-deployment-guidelines.md

Resolves https://github.com/wso2/docs-apim/issues/1390

Fix for #1390

---

en/docs/install-and-setup/setup/deployment-best-practices/production-deployment-guidelines.md

Resolves https://github.com/wso2/docs-apim/issues/1394

Fix for #1394

---

en/docs/install-and-setup/setup/setting-up-proxy-server-and-the-load-balancer/configuring-the-proxy-server-and-the-load-balancer.md

Resolves https://github.com/wso2/docs-apim/issues/1409

Fix for #1409

---

en/docs/install-and-setup/upgrading-wso2-api-manager/upgrading-from-200-to-310.md
en/docs/install-and-setup/upgrading-wso2-api-manager/upgrading-from-210-to-310.md
en/docs/install-and-setup/upgrading-wso2-api-manager/upgrading-from-220-to-310.md
en/docs/install-and-setup/upgrading-wso2-api-manager/upgrading-from-250-to-310.md
en/docs/install-and-setup/upgrading-wso2-api-manager/upgrading-from-260-to-310.md
en/docs/install-and-setup/upgrading-wso2-api-manager/upgrading-from-300-to-310.md

Fix reg versioning confusions in migration docs

---

en/docs/install-and-setup/setup/distributed-deployment/product-profiles.md

fix for https://github.com/wso2/docs-apim/issues/1023
Added steps 2,3, and 4

fix for https://github.com/wso2/docs-apim/issues/1023

---

en/docs/learn/design-api/create-api/create-a-rest-api-from-a-swagger-definition.md

Adding details about creating API using open API archive.
Related to https://github.com/wso2/carbon-apimgt/pull/8509

Adding details for API creation using openAPI archive

---

en/docs/develop/extending-api-manager/saml2-sso/configuring-single-sign-on-with-saml2.md
en/mkdocs.yml

fix for https://github.com/wso2/docs-apim/issues/1430

fix for https://github.com/wso2/docs-apim/issues/1430

---

en/docs/reference/faq.md

fix for https://github.com/wso2/docs-apim/issues/1431

fix for https://github.com/wso2/docs-apim/issues/1431

---

en/docs/getting-started/quick-start-guide.md

Update API controller add-env example at Quick start guide.
APIM - 3.2.0 -Alpha

[Docs] Updating Apictl Example in Quick start Guide

---

en/docs/getting-started/quick-start-guide.md

Change info box related to add-env command of apictl.

[Docs][3.1.0]Changing info box related to Apictl "add-env" flags

---

en/docs/reference/faq.md

This partially fixes https://github.com/wso2/docs-apim/issues/1236

fix for https://github.com/wso2/docs-apim/issues/1236

---

en/docs/reference/faq.md

fixes https://github.com/wso2/docs-apim/issues/1431
Partial fix for https://github.com/wso2/docs-apim/issues/1236
This is in place of https://github.com/wso2/docs-apim/pull/1434, because the PR got messed up. However, the fixes are based on the review comments in
[1] https://github.com/wso2/docs-apim/pull/1434

fixes #1431 and partly fixes #1236

---

en/docs/develop/customizations/customizing-the-developer-portal/advanced-customization.md

Reviewed https://github.com/wso2/docs-apim/issues/1132

Add reviewed doc

---

en/docs/install-and-setup/install/installing-the-product/installing-the-binary/installing-on-windows.md

Document Fix -Java Version.
> Link(s) to product documentation that addresses the changes of this PR. If no doc impact, enter …

Document Fix -Java Version

---

en/docs/install-and-setup/install/installing-the-product/installing-the-binary/installing-on-windows.md

fixes https://github.com/wso2/docs-apim/issues/1479

fixes https://github.com/wso2/docs-apim/issues/1479

---

en/docs/learn/analytics/analyzing-apim-statistics-with-batch-analytics/using-geo-location-based-statistics/creating-geo-location-data-set.md

Fix invalid paths

---

en/docs/learn/api-controller/importing-apis-via-dev-first-approach.md

Update the example sample API definition file In apictl documentation in order to keep up with latest versions.
Fixes  https://github.com/wso2/product-apim-tooling/issues/325
Link this URL here: https://github.com/wso2/product-apim-tooling/blob/master/import-export-cli/box/resources/init/sample_api.yaml
Initialize a project with api.yaml definition in dev first approach.
APIM - 3.2.0

[Docs] [3.1.0] Update the example api definition file in Dev first Approach page.

---

en/docs/learn/api-controller/importing-apis-via-dev-first-approach.md

Update the example sample API definition file In apictl documentation in order to keep up with latest versions.
Fixes  https://github.com/wso2/product-apim-tooling/issues/325
Link this URL here: https://github.com/wso2/product-apim-tooling/blob/master/import-export-cli/box/resources/init/sample_api.yaml
Initialize a project with api.yaml definition in dev first approach.
APIM - 3.2.0

[Docs] Update the example api definition file in Dev first Approach page.

---

en/docs/learn/api-controller/getting-started-with-wso2-api-controller.md

Fixes https://github.com/wso2/product-apim-tooling/issues/389

Add changing default wso2apictl directory location details

---

en/docs/learn/analytics/creating-custom-widgets-in-analytics-dashboards.md

Fixes https://github.com/wso2/docs-apim/issues/1502 …

Changing HOME to API_ANALYTICS_HOME

---

en/docs/learn/design-api/publish-api/publish-to-multiple-external-api-stores.md

Document Fix-Port number  fix.
> Link(s) to product documentation that addresses the changes of this PR. If no doc impact, …

Document Fix-Port number  fix.

---

en/docs/install-and-setup/setup/distributed-deployment/deploying-wso2-api-m-in-a-distributed-setup.md

This PR adds the configuration required in the developer portal for the gateway, in order to work the try it console.

Fix issues in distributed deployment doc

---

en/docs/install-and-setup/setup/distributed-deployment/deploying-wso2-api-m-in-a-distributed-setup.md

This PR adds the configuration required in the developer portal for the gateway, in order to work the try it console.

Fix distributed doc configurations of developer portal

---

en/docs/install-and-setup/upgrading-wso2-api-manager/upgrading-from-260-to-310.md

> The PR contains instruction and sql queries to update the analytics DB, if the customer is migrating from 2.6 and does not contain the latest WUM update. This is because of a schema change introduces in one of the WUM update wso2am-analytics-2.6.0 and it is important that the customers do add the above change to the DB prior to migration.

Add instructions and Queries to alter Analytics Database prior to migrations.

---

en/docs/wip/change-developer-portal-password.md

- Add documentation for custom password policy defining and validation sub-feature of the devportal password change.
- Fix styling for example code segments

Password change custom policies

---

en/docs/develop/product-apis/devportal-apis/devportal-v1/devportal-v1.yaml
en/docs/develop/product-apis/publisher-apis/publisher-v1/publisher-v1.yaml

fix for https://github.com/wso2/docs-apim/issues/1139

fix for https://github.com/wso2/docs-apim/issues/1139

---

en/docs/learn/design-api/mock-api/create-a-mock-api-with-an-inline-script.md

Steps 2 and 3 screenshots were misplaced. This PR contains the fix for the issue.

fixed screenshot swap mistake in step 2 and 3

---

en/docs/learn/design-api/mock-api/create-a-mock-api-with-an-inline-script.md

Steps 2 and 3 screenshots were misplaced. This PR contains the fix for the issue.

fixed screenshot swapped mistake for steps 2 and 3

---

en/mkdocs.yml

changing the site_url

---

en/docs/install-and-setup/setup/distributed-deployment/configuring-wso2-identity-server-as-a-key-manager.md

Fix https://github.com/wso2/docs-apim/issues/1332

Add Step 8 missing in APIM 3.0.0 IS as KM doc

---

en/docs/develop/customizations/customizing-the-developer-portal/styling-api-details-info-section.md

Fixes https://github.com/wso2/docs-apim/issues/1440

Language review for page

---

en/docs/learn/api-security/oauth2/access-token-types/jwt-tokens.md

This will add the configurations for the subscription validation from the KM.
https://apim.docs.wso2.com/en/latest/learn/api-security/oauth2/access-token-types/jwt-tokens/#secure-apis-using-jwt-self-contained-access-tokens

Update the apim.jwt_authenitcation configurations

---

en/docs/install-and-setup/upgrading-wso2-api-manager/upgrading-from-260-to-310.md

Replacing the normal queries available for updating the analytics DB with stored procedures so that the procedure can check whether the change is already available in the DB and if not it will update the DB accordingly.

Adding stored procedures to update analytics db.

---

en/docs/develop/customizations/customizing-the-developer-portal/styling-api-details-info-section.md

Fixes https://github.com/wso2/docs-apim/issues/1440 in 3.1.0

Review doc for 3.1.0

---

en/docs/learn/consume-api/customizations/customizing-the-developer-portal/styling-api-details-info-section.md

Fixes https://github.com/wso2/docs-apim/issues/1440 in 3.0.0

Review doc for 3.0.0

---

README.md
en/docs/administer/managing-users-and-roles/managing-user-roles.md
en/docs/administer/managing-users-and-roles/managing-user-stores/writing-a-custom-user-store-manager.md
en/docs/develop/customizations/customizing-the-developer-portal/customize-api-listing/categorizing-and-grouping-apis/api-category-based-grouping.md
en/docs/develop/customizations/customizing-the-developer-portal/customize-api-listing/categorizing-and-grouping-apis/tagwise-based-grouping.md
en/docs/develop/customizations/customizing-the-developer-portal/overriding-developer-portal-theme.md
en/docs/develop/product-apis/admin-apis/admin-v0.16/admin-v0.16.md
en/docs/develop/product-apis/devportal-apis/devportal-v0.16/devportal-v0.16.md
en/docs/develop/product-apis/getting-started/guide-admin-v1.md
en/docs/develop/product-apis/getting-started/guide-devportal-v0.16.md
en/docs/develop/product-apis/getting-started/guide-publisher-v0.16.md
en/docs/develop/product-apis/publisher-apis/publisher-v0.16/publisher-v0.16.md
en/docs/develop/product-apis/restful-apis.md
en/docs/getting-started/about-this-release.md
en/docs/install-and-setup/install/installing-the-product/installing-via-the-installer.md
en/docs/install-and-setup/setup/distributed-deployment/configuring-wso2-identity-server-as-a-key-manager.md
en/docs/install-and-setup/setup/reference/product-compatibility.md
en/docs/install-and-setup/setup/single-node/configuring-apim-analytics.md
en/docs/learn/analytics/configuring-apim-analytics.md
en/docs/troubleshooting/admin-troubleshooting-in-production-environments.md
en/docs/troubleshooting/capturing-system-data-in-error-situations.md
en/docs/wip/scope-role-mapping.md

Fixes https://github.com/wso2/docs-apim/issues/1558

Remove 3.1.0 References from 3.2.0 docs

---

en/docs/learn/api-controller/ci-cd-with-wso2-api-management.md
en/docs/learn/consume-api/invoke-apis/invoke-apis-using-tools/invoke-an-api-using-the-integrated-api-console.md
en/docs/learn/design-api/create-api/create-a-rest-api-from-an-openapi-definition.md
en/docs/wip/apis/devportal-v0.15.yaml
en/docs/wip/apis/devportal-v1.yaml
en/docs/wip/apis/publisher-v0.15.yaml
en/docs/wip/publisher.yaml
en/mkdocs.yml

rephrase/replace section using the word Swagger with OpenAPI

---

en/docs/getting-started/about-this-release.md

Changed analytics new features

Changed analytics new features

---

en/docs/learn/tutorials/create-and-publish-awslambda-api.md

Fixes https://github.com/wso2/docs-apim/issues/1590

Add note about using API-M instance and Lambda function

---

README.md
en/mkdocs.yml

- fixes https://github.com/wso2/docs-apim/issues/1596
- fixes https://github.com/wso2/docs-apim/issues/1597

fixes #1596  and #1597

---

README.md

fixes https://github.com/wso2/docs-apim/issues/1597 in 3.0.0

fixes https://github.com/wso2/docs-apim/issues/1597

---

en/docs/install-and-setup/setup/security/logins-and-passwords/working-with-encrypted-passwords.md

Add note to put secure valult 'secrets' elements to the bottom

---

en/docs/administer/product-security/configuring-transport-level-security.md

fixes https://github.com/wso2/docs-apim/issues/1629

fixes https://github.com/wso2/docs-apim/issues/1629

---

en/docs/install-and-setup/upgrading-wso2-api-manager/upgrading-from-200-to-320.md
en/docs/install-and-setup/upgrading-wso2-api-manager/upgrading-from-210-to-320.md
en/docs/install-and-setup/upgrading-wso2-api-manager/upgrading-from-220-to-320.md
en/docs/install-and-setup/upgrading-wso2-api-manager/upgrading-from-250-to-320.md
en/docs/install-and-setup/upgrading-wso2-api-manager/upgrading-from-260-to-320.md
en/docs/install-and-setup/upgrading-wso2-api-manager/upgrading-from-300-to-320.md

temporary fix till we get the latest migration client fixed

add note to use 1.0.103v as is migration client

---

en/docs/learn/api-security/oauth2/grant-types/kerberos-oauth2-grant.md

fixes: https://github.com/wso2/product-apim/issues/8894

Fix kerberos grant enable config

---

en/docs/install-and-setup/upgrading-wso2-api-manager/upgrading-from-310-to-320.md

corrected the version as 3.1.0

Corrected the version as 3.1.0 on Update upgrading-from-310-to-320.md

---

en/docs/administer/key-managers/how-to-configure-wso2is-connector.md

fix build failure

---

en/docs/administer/key-managers/overview.md

Reviewed en/docs/administer/key-managers/overview.md
Based on https://github.com/wso2/docs-apim/pull/1613

Reviewed key-managers/overview

---

en/docs/install-and-setup/upgrading-wso2-api-manager/upgrading-from-200-to-320.md
en/docs/install-and-setup/upgrading-wso2-api-manager/upgrading-from-210-to-320.md
en/docs/install-and-setup/upgrading-wso2-api-manager/upgrading-from-220-to-320.md
en/docs/install-and-setup/upgrading-wso2-api-manager/upgrading-from-250-to-320.md
en/docs/install-and-setup/upgrading-wso2-api-manager/upgrading-from-260-to-320.md
en/docs/install-and-setup/upgrading-wso2-api-manager/upgrading-from-300-to-320.md
en/docs/install-and-setup/upgrading-wso2-api-manager/upgrading-from-310-to-320.md

Add note on DB2

---

en/docs/install-and-setup/upgrading-wso2-api-manager/upgrading-from-200-to-320.md
en/docs/install-and-setup/upgrading-wso2-api-manager/upgrading-from-210-to-320.md

This PR adds a temporary workaround to fix the issue mentioned in https://github.com/wso2/product-apim/issues/9000.
TODO : Find the cause for the issue and reconstruct docs accordingly.
> Link(s) to product documentation that addresses the changes of this PR. If no doc impact, enter …

Add note on login issue

---

en/docs/install-and-setup/upgrading-wso2-api-manager/upgrading-from-200-to-320.md
en/docs/install-and-setup/upgrading-wso2-api-manager/upgrading-from-210-to-320.md
en/docs/install-and-setup/upgrading-wso2-api-manager/upgrading-from-220-to-320.md
en/docs/install-and-setup/upgrading-wso2-api-manager/upgrading-from-250-to-320.md
en/docs/install-and-setup/upgrading-wso2-api-manager/upgrading-from-260-to-320.md
en/docs/install-and-setup/upgrading-wso2-api-manager/upgrading-from-300-to-320.md

add back note to use latest is migration client

remove note to user specific is migration client

---

en/docs/learn/api-microgateway/deploy-apis-in-privatejet-mode.md

- Add ingress hostname
- Update configs using kubectl patch command
- Remove quotes in replica count field.
APIM 3.2.0

Add ingress hostname config for Private Jet mode

---

en/docs/getting-started/about-this-release.md

Update 'About this Release' with analytics features

Update 'About this Release' with analytics features

---

en/docs/learn/analytics/analyzing-apim-statistics-with-batch-analytics/viewing-api-statistics.md

Remove incorrect info from geo location widget doc

Remove incorrect info from geo location widget doc

---

en/docs/administer/key-managers/how-to-configure-wso2is-connector.md

fix attachment link

---

en/docs/install-and-setup/upgrading-wso2-api-manager/upgrading-from-200-to-320.md
en/docs/install-and-setup/upgrading-wso2-api-manager/upgrading-from-210-to-320.md
en/docs/install-and-setup/upgrading-wso2-api-manager/upgrading-from-220-to-320.md
en/docs/install-and-setup/upgrading-wso2-api-manager/upgrading-from-250-to-320.md
en/docs/install-and-setup/upgrading-wso2-api-manager/upgrading-from-260-to-320.md
en/docs/install-and-setup/upgrading-wso2-api-manager/upgrading-from-300-to-320.md
en/docs/install-and-setup/upgrading-wso2-api-manager/upgrading-from-310-to-320.md

Fix oracle script

---

en/docs/learn/analytics/analyzing-apim-statistics-with-batch-analytics/viewing-api-statistics.md
en/docs/learn/api-security/threat-protection/bot-detection.md
en/mkdocs.yml

fixes build break due to https://github.com/wso2/docs-apim/pull/1669

fixes build break due to https://github.com/wso2/docs-apim/pull/1669

---

en/docs/develop/customizations/customizing-the-developer-portal/customize-api-listing/api-category-based-grouping.md
en/docs/getting-started/about-this-release.md
en/mkdocs.yml

This PR will,
Fix https://github.com/wso2/docs-apim/issues/1701
Remove notes on tag wise grouping
> Link to the PR for changes to …

Fix doc search issue with api category doc

---

en/mkdocs.yml

Fixes api category doc's redirection link …

Fix the category doc link

---

en/mkdocs.yml

Fix paths for alerts

---

en/docs/develop/product-apis/admin-apis/admin-v0.17/admin-v0.17.md
en/docs/develop/product-apis/admin-apis/admin-v1/admin-v1.yaml

This PR updates the swagger definitions for admin v1 and admin v0.17 REST APIs.
1. https://apim.docs.wso2.com/en/next/develop/product-apis/admin-apis/admin-v1/admin-v1/
2. https://apim.docs.wso2.com/en/next/develop/product-apis/admin-apis/admin-v0.17/admin-v0.17/

Update Admin swagger definition

---

en/docs/learn/api-controller/ci-cd-with-wso2-api-management.md

Fixes: https://github.com/wso2/product-apim-tooling/issues/439
Fixes: https://github.com/wso2/product-apim-tooling/issues/422

Adding some missing required changes for APICTL Git Integration

---

en/docs/learn/kubernetes-operators/k8s-api-operator/enabling-privatejet-mode-to-deploy-apis.md
en/docs/learn/kubernetes-operators/k8s-api-operator/k8s-api-operator.md
en/docs/learn/kubernetes-operators/k8s-wso2am-operator.md
en/mkdocs.yml

fixes https://github.com/wso2/docs-apim/issues/1717 and typos

fixes https://github.com/wso2/docs-apim/issues/1717 and typos

---

en/docs/getting-started/overview.md

fix for https://github.com/wso2/docs-apim/issues/1619

fix for https://github.com/wso2/docs-apim/issues/1619

---

en/docs/learn/design-api/create-api/create-a-rest-api-from-an-openapi-definition.md

> Fix https://github.com/wso2/docs-apim/issues/1713

Fix typo error.

---

en/docs/develop/extending-api-manager/saml2-sso/multi-factor-authentication-mfa-for-publisher-and-developer-portals.md

Fixes https://github.com/wso2/docs-apim/issues/1733

Fix link for Configuring Identity Server as IDP for SSO

---

en/docs/learn/api-security/api-authentication/advanced-topics/federating-oauth-applications.md

Fixes https://github.com/wso2/docs-apim/issues/1734

Fix link for Using OKTA As An External IDP With OIDC

---

en/docs/learn/api-security/configuring-api-security-audit.md

Fixes https://github.com/wso2/docs-apim/issues/1736

Add step to restart server to enable Audit API

---

en/docs/develop/customizations/customizing-login-pages-for-dev-portal-and-publisher.md

Fixes https://github.com/wso2/docs-apim/issues/1338

Fixes issue #1338

---

en/docs/learn/design-api/endpoints/resiliency/prevent-api-suspension.md

Fixes https://github.com/wso2/docs-apim/issues/1715

Fix broken link - timeout configurations

---

en/docs/develop/customizations/customizing-login-pages-for-dev-portal-and-publisher.md

Add info with WUM details

---

en/docs/install-and-setup/setup/deployment-best-practices/tuning-performance.md

Fixes https://github.com/wso2/docs-apim/issues/1726

Fix formatting 

---

en/docs/learn/design-api/api-documentation/add-api-documentation.md

> We only support .pdf, .txt and .doc files in publisher doc uploading. …

fixes doc uploading format issue

---

en/docs/install-and-setup/upgrading-wso2-api-manager/upgrading-from-250-to-310.md

This PR will fix the link issue in migration doc

Fixing link issue in analytics migration section 2.5.0 - 3.1.0 

---

en/docs/install-and-setup/setup/distributed-deployment/synchronizing-artifacts-in-a-gateway-cluster.md

fixing heading styles

---

en/docs/install-and-setup/setup/distributed-deployment/synchronizing-artifacts-in-a-gateway-cluster.md

PR review for https://github.com/wso2/docs-apim/pull/1793

PR review for https://github.com/wso2/docs-apim/pull/1793

---

en/docs/install-and-setup/setup/distributed-deployment/synchronizing-artifacts-in-a-gateway-cluster.md

fixed typo in config

---

en/docs/learn/api-controller/advanced-topics/using-dynamic-data-in-api-controller-projects.md

Fixes wso2/product-apim-tooling#472 in APIM 3.1.0

Fixing sequence content in apictl-dynamic data page

---

en/docs/install-and-setup/setup/distributed-deployment/synchronizing-artifacts-in-a-gateway-cluster.md

- fixes https://github.com/wso2/docs-apim/issues/1809
- Related to https://github.com/wso2/docs-apim/pull/1793

Fixes https://github.com/wso2/docs-apim/issues/1809

---

en/docs/learn/consume-api/manage-subscription/advanced-topics/adding-an-api-subscription-workflow.md

Fixes https://github.com/wso2/docs-apim/issues/1522

Remove broken link and update page

---

en/docs/getting-started/about-this-release.md

- Fix broken links
- Update feature descriptions

Update the 'About this release' page

---

en/docs/learn/kubernetes-operators/k8s-api-operator/enabling-privatejet-mode-to-deploy-apis.md

> Correcting the SA name refers in the clusterRoleBinding

Enabling PrivateJet Mode to Deploy APIs: Correcting service account name

---

en/docs/learn/analytics/analytics-event-streams-and-aggregations.md
en/mkdocs.yml

update Analytics event streams and aggregations

update Analytics event streams and aggregations

---

en/docs/develop/extending-api-manager/extending-workflows/configuring-workflows-for-tenants.md

Fix for APIMINTERNAL-190

---

en/docs/reference/config-catalog.md

Fixes https://github.com/wso2/docs-apim/issues/1834

Add config samples for API-M Open tracer and API-M SDK

---

en/docs/install-and-setup/setup/distributed-deployment/configure-apim-analytics/active-passive.md
en/docs/install-and-setup/setup/distributed-deployment/configure-apim-analytics/configuring-database-and-file-system-state-persistence.md
en/mkdocs.yml

- Add doc for 'Configuring Database and File System State Persistence'
- Fixes https://github.com/wso2/docs-apim/issues/1520

Add Configuring Database and File System State Persistence

---

en/docs/develop/customizations/customizing-the-developer-portal/customize-api-listing/api-category-based-grouping.md
en/docs/getting-started/quick-start-guide.md
en/docs/install-and-setup/install/installation-prerequisites.md

fix invalid links

---

en/mkdocs.yml

creating 3.2.0 branch

---

en/docs/assets/versions.json

add new version

---

en/mkdocs.yml

Changing 3.1.0 docs URL from latest to 3.1.0

changing 3.1.0 docs URL from latest to 3.1.0

---

en/docs/learn/analytics/configuring-apim-analytics.md

resized the image

---

en/docs/getting-started/quick-start-guide.md

This PR will modify the apictl add-env example for all in one APIM instance

Modify Apictl adding an environment example in Quick start guide

---

en/docs/getting-started/quick-start-guide.md

This PR will modify the apictl add-env example for all in one APIM instance

[3.2.0] Modify Apictl adding an environment example in Quick start guide

---

en/docs/learn/analytics/alert-types.md
en/mkdocs.yml

remove obselete docs

---

en/docs/learn/analytics/configuring-apim-analytics.md

fixed formatting issues

---

en/docs/install-and-setup/setup/deployment-best-practices/tuning-performance.md
en/docs/learn/analytics/alert-types.md
en/mkdocs.yml

merging from 3.2.0

---

en/docs/install-and-setup/setup/security/logins-and-passwords/set-passwords-using-vars-and-sys-props.md

Fix for incorrect server startup file name under bin folder there is no wso2carbon.sh.
> Link(s) to product documentation that …

Fix for incorrect server startup file name

---

en/docs/reference/faq.md

Update faq.md corrected broken link

---

en/mkdocs.yml

changing the site_url for search to work

---

en/docs/install-and-setup/upgrading-wso2-is-as-key-manager/upgrading-from-is-km-500-to-5100.md
en/docs/install-and-setup/upgrading-wso2-is-as-key-manager/upgrading-from-is-km-510-to-5100.md
en/docs/install-and-setup/upgrading-wso2-is-as-key-manager/upgrading-from-is-km-520-to-5100.md
en/docs/install-and-setup/upgrading-wso2-is-as-key-manager/upgrading-from-is-km-530-to-5100.md
en/docs/install-and-setup/upgrading-wso2-is-as-key-manager/upgrading-from-is-km-550-to-5100.md
en/docs/install-and-setup/upgrading-wso2-is-as-key-manager/upgrading-from-is-km-560-to-5100.md
en/docs/install-and-setup/upgrading-wso2-is-as-key-manager/upgrading-from-is-km-570-to-5100.md
en/docs/install-and-setup/upgrading-wso2-is-as-key-manager/upgrading-from-is-km-590-to-5100.md

fixes #1912

---

en/docs/install-and-setup/setup/distributed-deployment/configuring-wso2-identity-server-as-a-key-manager.md

add missing config

---

en/docs/administer/key-managers/configure-wso2is-connector.md

make scope EP mandatory

---

en/docs/learn/api-gateway/passing-end-user-attributes-to-the-backend/passing-enduser-attributes-to-the-backend-using-jwt.md

Add info about apim.jwt.convert_dialect config

---

en/docs/install-and-setup/setup/distributed-deployment/deploying-wso2-api-m-in-a-distributed-setup.md

Reviewed and updated /install-and-setup/setup/distributed-deployment/deploying-wso2-api-m-in-a-distributed-setup.md

Reviewed and updated deploying-wso2-api-m-in-a-distributed-setup.md

---

en/docs/learn/design-api/advanced-topics/adding-an-api-state-change-workflow.md

> This PR updates the table of properties of workflow extension on the APIM 3.2.0.
Reference: https://apim.docs.wso2.com/en/latest/learn/design-api/advanced-topics/adding-an-api-state-change-workflow/

Workflow executor configurations

---

en/docs/learn/design-api/advanced-topics/adding-an-api-state-change-workflow.md

PR sync for https://github.com/wso2/docs-apim/pull/1699

PR sync for https://github.com/wso2/docs-apim/pull/1699

---

en/mkdocs.yml

Link per API logging page.

---

en/docs/learn/api-controller/importing-apis-via-dev-first-approach.md

This PR will update the table of Extensions related to Micro gateway which is at _importing-apis-via-dev-first-approach_ page under the Api controller topic
APIM 3.1.0
APIM 3.1.0

[3.1.0] [Docs] Update mgw related extensions table in API Controller docs.

---

en/docs/learn/api-controller/importing-apis-via-dev-first-approach.md

This PR will update the table of Extensions related to Micro gateway which is at _importing-apis-via-dev-first-approach_ page under the Api controller topic
APIM 3.2.0
Master branch

[Master] [Docs] Update mgw related extensions table in API Controller docs.

---

en/docs/learn/api-controller/importing-apis-via-dev-first-approach.md

This PR will update the table of Extensions related to Micro gateway which is at _importing-apis-via-dev-first-approach_ page under the Api controller topic
APIM 3.2.0
APIM 3.2.0

[3.2.0] [Docs] Update mgw related extensions table in API Controller docs.

---

en/docs/administer/logging-and-monitoring/logging/gw-api.yaml

Reviewed and updated - https://github.com/wso2/docs-apim/pull/1934

Reviewed and updated - https://github.com/wso2/docs-apim/pull/1934

---

en/docs/learn/tutorials/create-and-publish-websocket-api.md

Fixes https://github.com/wso2/product-apim/issues/9195

Fixing websocket connection issue

---

en/docs/install-and-setup/upgrading-wso2-api-manager/upgrading-from-200-to-310.md

fix incorrect syntax in MSSQL script

---

en/docs/install-and-setup/upgrading-wso2-api-manager/upgrading-from-1100-to-320.md

fix incorrect syntax of MSSQL scrpt

---

en/docs/install-and-setup/upgrading-wso2-api-manager/upgrading-from-1100-to-320.md

fix inccorect syntax of MSSQL scrpt

---

en/docs/develop/product-apis/admin-apis/admin-v1/admin-v1.yaml
en/docs/develop/product-apis/restful-apis.md

This PR,
1. Adds x-code-samples for admin rest API resources.
2. Adds the postman collection for admin rest API
> Link to the PR …

Add redocly integration for admin api v1

---

en/docs/develop/product-apis/devportal-apis/devportal-v1/devportal-v1.yaml

- This PR integrates the DevPortal REST API documenation with redocly. 
- This will also include the DevPortal REST API Postman Collection to the documentation.

Redocly Integration of DevPortal REST API

---

en/docs/install-and-setup/setup/security/general-data-protection-regulation-gdpr-for-wso2-api-manager.md

Fixes https://github.com/wso2/docs-apim/issues/1787
- Upgraded the Versions.
- Refined and modified the command-line options of the Forget-Me tool.
- APIM 3.2.0

Update docs for GDPR 

---

en/docs/install-and-setup/setup/security/general-data-protection-regulation-gdpr-for-wso2-api-manager.md
en/docs/learn/tutorials/create-and-publish-websocket-api.md

PR sync for https://github.com/wso2/docs-apim/pull/1811

PR sync for https://github.com/wso2/docs-apim/pull/1811

---

en/docs/install-and-setup/upgrading-wso2-is-as-key-manager/upgrading-from-is-km-5100-to-is-5100.md
en/docs/install-and-setup/upgrading-wso2-is-as-key-manager/upgrading-from-is-km-520-to-5100.md
en/docs/install-and-setup/upgrading-wso2-is-as-key-manager/upgrading-from-is-km-530-to-5100.md
en/docs/install-and-setup/upgrading-wso2-is-as-key-manager/upgrading-from-is-km-550-to-5100.md
en/docs/install-and-setup/upgrading-wso2-is-as-key-manager/upgrading-from-is-km-560-to-5100.md
en/docs/install-and-setup/upgrading-wso2-is-as-key-manager/upgrading-from-is-km-570-to-5100.md
en/docs/install-and-setup/upgrading-wso2-is-as-key-manager/upgrading-from-is-km-590-to-5100.md

The config template is available in wum updated WSO2 IS 5.10.0

Remove TenantContextsToRewrite template config add notes

---

en/docs/install-and-setup/setup/setting-up-databases/managing-data-growth-and-improving-performance.md

remove steps to take backups

---

en/docs/learn/tutorials/create-and-publish-websocket-api.md

- PR review and PR sync for https://github.com/wso2/docs-apim/pull/1952 
- Reviewed and updated the entire doc - en/docs/learn/tutorials/create-and-publish-websocket-api.md

Reviewed and updated entire doc - create-and-publish-websocket-api.md

---

en/docs/install-and-setup/setup/setting-up-databases/managing-data-growth-and-improving-performance.md
en/docs/learn/tutorials/create-and-publish-websocket-api.md

Reviewed and updated managing-data-growth-and-improving-performance.md

Reviewed and updated managing-data-growth-and-improving-performance.md

---

en/docs/administer/logging-and-monitoring/monitoring/working-with-observability.md

Fixes https://github.com/wso2/docs-apim/issues/1988

Fix incorrect wording for jdbc log filtering

---

en/docs/administer/logging-and-monitoring/monitoring/working-with-observability.md

Fixes https://github.com/wso2/docs-apim/issues/1988

Fix wrong wording in observability log filtering

---

en/docs/install-and-setup/setup/advance-configurations/configuring-caching.md

Fixes https://github.com/wso2/docs-apim/issues/1836

Updating the docs on "Configuring Caching"

---

en/docs/install-and-setup/setup/advance-configurations/configuring-caching.md

PR sync for https://github.com/wso2/docs-apim/pull/1837

PR sync for https://github.com/wso2/docs-apim/pull/1837

---

en/docs/develop/product-apis/admin-apis/admin-v1/admin-v1.yaml
en/docs/develop/product-apis/devportal-apis/devportal-v1/devportal-v1.yaml
en/docs/develop/product-apis/gateway-apis/gateway-v1/gateway-v1.yaml
en/docs/develop/product-apis/overview.md
en/docs/develop/product-apis/publisher-apis/publisher-v1/publisher-v1.yaml

- This PR refactors the Publisher, DevPortal, Admin and Gateway v1 REST API swagger definitions.
- This PR also updates links in the REST API Overview page and lists down the REST APIs as follows.

Refactor REST API Swagger Definitions

---

en/mkdocs.yml

fixing a build break due to https://github.com/wso2/docs-apim/pull/1996

fixing a build break

---

en/mkdocs.yml

updated versions in mkdoc.yml

---

en/docs/develop/product-apis/devportal-apis/devportal-v1/devportal-v1.yaml
en/docs/develop/product-apis/publisher-apis/publisher-v1/publisher-v1.yaml

Remove x-examples to fix docs loading issues.

remove x-examples from 3.2.0

---

en/docs/develop/product-apis/admin-apis/admin-v0.16/admin-v0.16.yaml
en/docs/develop/product-apis/devportal-apis/devportal-v0.16/devportal-v0.16.yaml
en/docs/develop/product-apis/devportal-apis/devportal-v1/devportal-v1.yaml
en/docs/develop/product-apis/publisher-apis/publisher-v0.16/publisher-v0.16.yaml
en/docs/develop/product-apis/publisher-apis/publisher-v1/publisher-v1.yaml

Fix swagger loading issue due to broken x-examples links

remove x-examples

---

en/docs/learn/analytics/customizing-analytics-dashboards.md

> This PR will add a configuration to the documentation which needs for creating analytics dashboards for users.
> Link to the PR …

Add a configuration for creating analytics dashboards for users.

---

en/docs/install-and-setup/setup/single-node/configuring-an-active-active-deployment.md

Fixed the config issue in Active-Active Deployment docs

---

en/docs/install-and-setup/setup/single-node/configuring-an-active-active-deployment.md

Fixed the config error in HA active-active-deployment

---

en/mkdocs.yml

mkdocs.yml entry related to https://github.com/wso2/docs-apim/pull/1219

mkdoc entry related to https://github.com/wso2/docs-apim/pull/1219

---

en/mkdocs.yml

Fix https://github.com/wso2/docs-apim/issues/2020

updated the redirection for /product-apis/restful-apis.md

---

en/docs/develop/extending-api-manager/saml2-sso/configuring-identity-server-as-idp-for-sso.md

add admin portal sso config content

---

en/docs/learn/api-controller/getting-started-with-wso2-api-controller.md
en/docs/learn/api-controller/importing-apis-via-dev-first-approach.md

Fixes https://github.com/wso2/docs-apim/issues/1886

Improve API Controller Docs

---

en/docs/learn/analytics/configuring-apim-analytics.md

Adding system configurations for APIM Analytics as requested by the SI team. Please review, and once this solution is finalised, please apply this change to other branches as relevant.

Add system configurations for APIM Analytics

---

en/docs/learn/api-controller/getting-started-with-wso2-api-controller.md
en/docs/learn/api-controller/importing-apis-via-dev-first-approach.md

PR sync for https://github.com/wso2/docs-apim/pull/1891

PR sync for https://github.com/wso2/docs-apim/pull/1891

---

en/docs/develop/extending-api-manager/extending-key-management/extending-scope-validation.md

PR sync for https://github.com/wso2/docs-apim/pull/1868

PR sync for https://github.com/wso2/docs-apim/pull/1868

---

en/docs/develop/customizations/customizing-the-developer-portal/advanced-customization.md

added new steps for the UI customization

---

en/docs/install-and-setup/setup/advance-configurations/configuring-caching.md

- PR sync for https://github.com/wso2/docs-apim/pull/2037

PR sync for https://github.com/wso2/docs-apim/pull/2037

---

en/docs/getting-started/about-this-release.md
en/docs/getting-started/quick-start-guide.md
en/docs/install-and-setup/setup/advance-configurations/configuring-caching.md

Applied and reviewed changes in 
- https://github.com/wso2/docs-apim/pull/1895
- https://github.com/wso2/docs-apim/pull/1896

Applied and reviewed changes in #1895 #1896

---

en/docs/install-and-setup/upgrading-wso2-api-manager/upgrading-from-1100-to-320.md
en/docs/install-and-setup/upgrading-wso2-api-manager/upgrading-from-200-to-320.md
en/docs/install-and-setup/upgrading-wso2-api-manager/upgrading-from-210-to-320.md
en/docs/install-and-setup/upgrading-wso2-api-manager/upgrading-from-220-to-320.md
en/docs/install-and-setup/upgrading-wso2-api-manager/upgrading-from-250-to-320.md
en/docs/install-and-setup/upgrading-wso2-api-manager/upgrading-from-260-to-320.md
en/docs/install-and-setup/upgrading-wso2-api-manager/upgrading-from-300-to-320.md
en/docs/install-and-setup/upgrading-wso2-api-manager/upgrading-from-310-to-320.md

Fix https://github.com/wso2-extensions/apim-migration-resources/issues/58

Remove null or empty scope bindings

---

en/docs/learn/api-security/api-authentication/api-authentication-overview.md
en/docs/learn/api-security/api-authentication/secure-apis-using-oauth2-tokens.md
en/docs/learn/consume-api/manage-application/generate-keys/generate-api-keys.md

PR sync for https://github.com/wso2/docs-apim/pull/1963

Remove opaque token references

---

en/docs/install-and-setup/setup/setting-up-databases/changing-default-databases/changing-to-mysql.md

Reviewed and updated changing-default-databases/changing-to-mysql.md

Reviewed and updated changing-default-databases/changing-to-mysql.md

---

en/mkdocs.yml

Added redirect for configuring-rest-api.md

Added redirect for configuring-rest-api.md

---

en/mkdocs.yml

PR sync for https://github.com/wso2/docs-apim/pull/1972 missed aspects

PR sync for https://github.com/wso2/docs-apim/pull/1972 missed aspects

---

en/docs/learn/api-security/api-authentication/secure-apis-using-oauth2-tokens.md

Fix https://github.com/wso2/docs-apim/issues/1508

Add doc on passing Authorization header to backend configuration

---

en/docs/develop/product-apis/admin-apis/admin-v1/admin-v1.yaml

This PR will fix the token issue in admin postman collection. …

Fix token issue in postman collection

---

en/docs/develop/product-apis/admin-apis/admin-v1/admin-v1.yaml
en/docs/develop/product-apis/devportal-apis/devportal-v1/devportal-v1.yaml
en/docs/develop/product-apis/gateway-apis/gateway-v1/gateway-v1.yaml
en/docs/develop/product-apis/overview.md
en/docs/develop/product-apis/publisher-apis/publisher-v1/publisher-v1.yaml

- This PR refactors the Publisher, DevPortal, Admin and Gateway v1 REST API swagger definitions.
- This PR also updates links in the REST API Overview page and lists down the REST APIs as follows.

[3.2.0] Refactor REST API Swagger Definitions

---

en/docs/learn/analytics/creating-custom-widgets-in-analytics-dashboards.md

- Fixes https://github.com/wso2/docs-apim/issues/1995
- Reviewed entire doc and updated it.

fixes https://github.com/wso2/docs-apim/issues/1995

---

en/docs/install-and-setup/install/installation-prerequisites.md
en/docs/install-and-setup/setup/setting-up-databases/overview.md

- PR sync for https://github.com/wso2/docs-apim/pull/1999
- Reviewed and updated

[Docs] [3.2.0] Add Missing DB related information in documentation

---

en/docs/install-and-setup/setup/distributed-deployment/configuring-wso2-identity-server-as-a-key-manager.md

fixes https://github.com/wso2/docs-apim/issues/2094

fixes https://github.com/wso2/docs-apim/issues/2094

---

en/docs/learn/api-security/openid-connect/obtaining-user-profile-information-with-openid-connect.md

This PR will add documentation content related to Obtaining the OpenID Provider configuration information
Fixes https://github.com/wso2/docs-apim/issues/1593 for Master branch
Use cases related to OpenID connection related tasks
https://github.com/wso2/product-apim/pull/8739
Ubuntu 20.04 LTS
Java JDK 1.8_241
APIM 3.2.0 Latest WUM pack

[Doc][Master] Docs for Obtaining the OpenID Provider configuration information

---

en/docs/learn/api-security/openid-connect/obtaining-user-profile-information-with-openid-connect.md

PR sync for https://github.com/wso2/docs-apim/pull/1994

PR sync for https://github.com/wso2/docs-apim/pull/1994

---

en/docs/administer/logging-and-monitoring/logging/gw-api.yaml

> Fixing a document issue in the basepath …

Fixing basepath in perlogging API.

---

en/docs/install-and-setup/setup/setting-up-databases/changing-default-databases/changing-to-mysql.md

> Ports the fix added in https://github.com/wso2/docs-apim/pull/1973 and https://github.com/wso2/docs-apim/pull/2074

Update MySQL database configurations

---

en/docs/install-and-setup/setup/setting-up-databases/changing-default-databases/changing-to-mysql.md

> Improves the fix added in https://github.com/wso2/docs-apim/pull/1973.

[3.1.0] Add recommendation on enabling SSL

---

en/docs/learn/api-controller/getting-started-with-wso2-api-controller.md

Fixes related to https://github.com/wso2/product-apim-tooling/issues/503

[Master] Add proxy support related docs for APICTL

---

en/docs/install-and-setup/upgrading-wso2-api-manager/upgrading-from-1100-to-320.md
en/docs/install-and-setup/upgrading-wso2-api-manager/upgrading-from-200-to-320.md
en/docs/install-and-setup/upgrading-wso2-api-manager/upgrading-from-210-to-320.md
en/docs/install-and-setup/upgrading-wso2-api-manager/upgrading-from-220-to-320.md
en/docs/install-and-setup/upgrading-wso2-api-manager/upgrading-from-250-to-320.md
en/docs/install-and-setup/upgrading-wso2-api-manager/upgrading-from-260-to-320.md
en/docs/install-and-setup/upgrading-wso2-api-manager/upgrading-from-300-to-320.md
en/docs/install-and-setup/upgrading-wso2-api-manager/upgrading-from-310-to-320.md
en/docs/install-and-setup/upgrading-wso2-is-as-key-manager/upgrading-from-is-km-5100-to-is-5100.md
en/docs/install-and-setup/upgrading-wso2-is-as-key-manager/upgrading-from-is-km-520-to-5100.md
en/docs/install-and-setup/upgrading-wso2-is-as-key-manager/upgrading-from-is-km-530-to-5100.md
en/docs/install-and-setup/upgrading-wso2-is-as-key-manager/upgrading-from-is-km-550-to-5100.md
en/docs/install-and-setup/upgrading-wso2-is-as-key-manager/upgrading-from-is-km-560-to-5100.md
en/docs/install-and-setup/upgrading-wso2-is-as-key-manager/upgrading-from-is-km-570-to-5100.md
en/docs/install-and-setup/upgrading-wso2-is-as-key-manager/upgrading-from-is-km-590-to-5100.md

Frontport following
https://github.com/wso2/docs-apim/pull/2085
https://github.com/wso2/docs-apim/pull/2053
https://github.com/wso2/docs-apim/pull/2057

Fix migration doc issues.

---

en/docs/install-and-setup/install/deploying-api-manager-with-kubernetes-or-openshift-resources.md

Fix for https://github.com/wso2/docs-apim/issues/2077

Kubernetes Documentation edits

---

en/docs/reference/faq.md

This PR updates FAQ section with toml configurations and remove outdated content. 
Related issue - https://github.com/wso2/docs-apim/issues/907

[3.2.0] Update FAQ section

---

en/docs/reference/faq.md

This PR updates FAQ section with toml configurations and remove outdated content.
Related issue - #907

[3.1.0] Update FAQ section

---

en/docs/reference/faq.md

This PR updates FAQ section with toml configurations and remove outdated content.
Related issue - #907

[3.0.0] Update FAQ section

---

en/docs/install-and-setup/install/deploying-api-manager-with-kubernetes-or-openshift-resources.md

Made change requested in https://github.com/wso2/docs-apim/pull/2123

Reverted file name change

---

en/docs/reference/faq.md

This PR updates FAQ section with toml configurations and remove outdated content.
Related issue - #907

Update FAQ section

---

en/mkdocs.yml

fixes https://github.com/wso2/docs-apim/issues/2133

fixes https://github.com/wso2/docs-apim/issues/2133

---

en/docs/assets/css/theme.css
en/theme/material/partials/header.html

fixes https://github.com/wso2/docs-apim/issues/2135

fixes https://github.com/wso2/docs-apim/issues/2135

---

en/docs/administer/key-managers/configure-auth0-connector.md

Added a few more specific points needed when configuring Auth0 as KM

Added a few comments for Auth0 KM configuration

---

en/docs/reference/samples/api-governance-sample.md

fixes https://github.com/wso2/docs-apim/issues/2144

fixes https://github.com/wso2/docs-apim/issues/2144

---

en/docs/assets/attachments/install-and-setup/apim200_to_apim310_gateway_artifact_migrator_for_tenants.ps1
en/docs/assets/attachments/install-and-setup/apim210_to_apim310_gateway_artifact_migrator.sh

As $subject this pr will update the follwing migration scripts to address the mentined 2 issues.
- apim210_to_apim310_gateway_artifact_migrator.sh
- apim200_to_apim310_gateway_artifact_migrator_for_tenants.ps1
Fixes https://github.com/wso2/product-apim/issues/9378
Fixes https://github.com/wso2/product-apim/issues/9391

[3.1.0] Update 2.x to 3.1 artifacts migration scripts

---

en/docs/learn/analytics/overview-of-api-analytics.md

Fix review comment in https://github.com/wso2/docs-apim/pull/2151

Fix review comment in https://github.com/wso2/docs-apim/pull/2151

---

en/docs/install-and-setup/setup/distributed-deployment/deploying-wso2-api-m-in-a-distributed-setup.md
en/docs/install-and-setup/setup/single-node/configuring-an-active-active-deployment.md

Add JMS based cache invalidation configurations

add jms based cache invalidation configuration

---

en/docs/administer/key-managers/configure-wso2is-connector.md

This is needed when configuring IS as KM

Added in a missing congif to deployment.toml of IS

---

en/docs/learn/api-security/oauth2/token-persistence.md

Fixes https://github.com/wso2/docs-apim/issues/1091 based on the content provided in [1].
[1] https://is.docs.wso2.com/en/5.9.0/setup/token-persistence/

[3.0.0] Update token persistence document

---

en/docs/develop/enabling-authentication-session-persistence.md
en/docs/learn/api-controller/advanced-topics/configuring-git-integration.md
en/mkdocs.yml

Fixes: 
https://github.com/wso2/product-apim-tooling/issues/453

Adding git integration config doc for apictl

---

en/docs/develop/enabling-authentication-session-persistence.md
en/docs/learn/api-controller/advanced-topics/configuring-git-integration.md
en/mkdocs.yml

Adding git integration config doc for apictl 

---

en/docs/learn/design-api/api-versioning/enabling-notifications.md

Modify the configuration to enable notifications

---

en/docs/develop/product-apis/overview.md
en/mkdocs.yml

Fixes : https://github.com/wso2/docs-apim/issues/2185
**After fix**

fix topic for restful apis doc

---

en/docs/administer/key-managers/configure-auth0-connector.md

PR sync for https://github.com/wso2/docs-apim/pull/2139 with reviewer updates

PR sync for https://github.com/wso2/docs-apim/pull/2139

---

en/docs/install-and-setup/setup/distributed-deployment/deploying-wso2-api-m-in-a-distributed-setup.md

Modified the user store config from "database" to "database_unique_id"

Updating deployment.toml configs for Gateway

---

en/docs/assets/attachments/install-and-setup/apim200_to_apim310_gateway_artifact_migrator_for_tenants.ps1
en/docs/assets/attachments/install-and-setup/apim210_to_apim310_gateway_artifact_migrator_for_tenants.ps1
en/docs/assets/attachments/install-and-setup/apim220_to_apim310_gateway_artifact_migrator_for_tenants.ps1
en/docs/install-and-setup/upgrading-wso2-api-manager/upgrading-from-200-to-310.md

As $subject this pr will update the windows tenants migration scripts to address the following issue
Fixes https://github.com/wso2/product-apim/issues/9391

[3.1.0] Update the tenants windows migration scripts

---

en/docs/install-and-setup/setup/distributed-deployment/deploying-wso2-api-m-in-a-distributed-setup.md
en/docs/install-and-setup/setup/single-node/configuring-an-active-active-deployment.md

add jms caching docs to 3.2.0

---

en/docs/install-and-setup/setup/distributed-deployment/deploying-wso2-api-m-in-a-distributed-setup.md
en/docs/install-and-setup/setup/single-node/configuring-an-active-active-deployment.md

PR sync for https://github.com/wso2/docs-apim/pull/2179

PR sync for https://github.com/wso2/docs-apim/pull/2179

---

en/docs/learn/design-api/api-versioning/enabling-notifications.md

Sync PR of - https://github.com/wso2/docs-apim/pull/2115

[3.2.0] Modify the configuration to enable notifications

---

en/docs/getting-started/about-this-release.md

Fixes https://github.com/wso2/docs-apim/issues/2197

Update Keymanager compatibility in Release Notes

---

en/docs/use-cases/integration-use-case/message-routing-overview.md
en/docs/use-cases/integration-use-case/message-transformation-overview.md
en/mkdocs.yml

Updates changes to Integrate section.

Update Integrate section

---

en/docs/streaming/cleansing-data/cleansing-data.md
en/docs/streaming/consuming-data/PublishGooglePubSubMessagesInTextFormat.md
en/docs/streaming/consuming-data/ReceiveTCPinJSONFormat.md
en/docs/streaming/consuming-data/consuming-messages.md
en/docs/streaming/consuming-data/receiving-data-in-transit.md
en/docs/streaming/correlating-events/correlating-events.md
en/docs/streaming/enriching-data/enriching-data.md
en/docs/streaming/extracting-data-from-static-sources-in-real-time/extracting-data-from-static-sources-in-real-time.md
en/docs/streaming/handling-errors/fault-Handling.md
en/docs/streaming/handling-errors/handling-errors.md
en/docs/streaming/handling-errors/processing-data.md
en/docs/streaming/integrating-stores/storage-Integration.md
en/docs/streaming/performing-etl-operations/performing-etl-tasks.md
en/docs/streaming/publishing-data/publishing-data-to-event-stream-consumers.md
en/docs/streaming/publishing-data/publishing-data.md
en/docs/streaming/summarizing-data/summarizing-data.md
en/docs/streaming/transforming-data/transforming-data.md
en/docs/streaming/triggering-integration-flows/triggering-integration-flows.md
en/docs/streaming/use-cases.md
en/mkdocs.yml

incorporate review comment

---

en/docs/getting-started/about-this-release.md

Fixes https://github.com/wso2/docs-apim/issues/2197

Update Keymanager compatibility in Release Notes 

---

en/docs/develop/extending-api-manager/extending-workflows/configuring-http-redirection-for-workflows.md

Fixes https://github.com/wso2/docs-apim/issues/1929

Fix broken link and space issues - Issue #1929

---

en/docs/learn/analytics/securing-sensitive-data-via-the-secure-vault.md
en/mkdocs.yml

Fixes https://github.com/wso2/docs-apim/issues/1531

[3.1.0] Add a documentation for APIM Analytics Encryption with Secure Vault

---

en/docs/learn/analytics/encrypting-sensitive-data-in-apim-analytics.md
en/mkdocs.yml

renaming the encrypting-sensitive-data-in-apim-analytics file

---

en/mkdocs.yml

Add images for Streaming Integrator Documentation

---

en/docs/learn/design-api/endpoints/endpoint-security/oauth-2.0.md

> Resolves issue https://github.com/wso2/docs-apim/issues/2175

Fix Image not rendered in Step5 issue

---

en/mkdocs.yml

Update tutorial links

---

en/docs/install-and-setup/install/installing-the-product/installing-in-containers/installing-si-using-docker.md
en/docs/install-and-setup/install/installing-the-product/installing-in-containers/installing-si-using-kubernetes.md
en/docs/install-and-setup/install/installing-the-product/installing-si-binary.md
en/docs/install-and-setup/install/installing-the-product/installing-si-in-vm.md
en/docs/install-and-setup/install/installing-the-product/installing-the-binary/installing-si-as-windows-service.md
en/mkdocs.yml

Commit and link SI Installation documentation

---

en/docs/use-cases/learn-overview.md

Add content to Integrate section

---

en/mkdocs.yml

Commit and link SI Observability documentation

---

en/docs/streaming/streaming-qsg.md
en/docs/streaming/use-cases.md
en/docs/use-cases/streaming-usecase/use-cases.md
en/mkdocs.yml

Correct Navigator Links

---

en/docs/learn/analytics/managing-alerts-with-real-time-analytics/configuring-alerts.md

- fixes https://github.com/wso2/docs-apim/issues/1146
- Reviewed full doc

fixes https://github.com/wso2/docs-apim/issues/1146

---

en/docs/learn/analytics/configuring-alerts.md

- fixes https://github.com/wso2/docs-apim/issues/1146 
- Reviewed full doc

fix for https://github.com/wso2/docs-apim/issues/1146 

---

en/docs/install-and-setup/upgrading-wso2-api-manager/upgrading-from-250-to-320.md

> Resolves https://github.com/wso2/docs-apim/issues/2233 for 3.2.0

Corrected the content.

---

en/docs/install-and-setup/upgrading-wso2-api-manager/upgrading-from-250-to-320.md

fix for https://github.com/wso2/docs-apim/issues/2233

PR sync for https://github.com/wso2/docs-apim/pull/2262

---

en/docs/install-and-setup/setup/setting-up-databases/changing-default-databases/changing-to-mysql.md

This PR adds notes about the requirement of primary keys when using group replication in MySQL and using NDB engine.
Related to wso2/product-apim#9505
PR sync for https://github.com/wso2/docs-apim/pull/2280

[Master] Add note to support group replication

---

en/docs/develop/product-apis/getting-started/guide-devportal-v1.md
en/docs/develop/product-apis/getting-started/guide-publisher-v1.md

This PR fixes the incorrect REST API versions mentioned in client-registration examples.
Fixes https://github.com/wso2/docs-apim/issues/2279

Fix incorrect REST API versions

---

en/docs/learn/analytics/configuring-apim-analytics.md

Added one note
> Link(s) to product documentation that addresses the changes of this PR. If no doc impact, enter “N/A” plus …

documentation updatation

---

en/docs/learn/analytics/configuring-apim-analytics.md

Revert "documentation updatation"

---

en/docs/administer/logging-and-monitoring/logging/masking-sensitive-information-in-logs.md
en/mkdocs.yml

This PR adds docs for masking logs for master branch
Related doc issue: https://github.com/wso2/docs-apim/issues/1606

[master] Add docs for masking logs

---

en/docs/administer/product-administration/monitoring/logging/masking-sensitive-information-in-logs.md
en/mkdocs.yml

This PR adds docs for masking logs in APIM 3.0.0.
Related doc issue: https://github.com/wso2/docs-apim/issues/1606

[3.0.0 ]Add docs for masking logs

---

en/docs/administer/logging-and-monitoring/logging/masking-sensitive-information-in-logs.md
en/mkdocs.yml

This PR adds docs for masking logs in APIM 3.1.0.
Related doc issue: https://github.com/wso2/docs-apim/issues/1606

[3.1.0] Add docs for masking logs

---

en/docs/learn/analytics/configuring-apim-analytics.md

fix for https://github.com/wso2/docs-apim/issues/2357

fix for https://github.com/wso2/docs-apim/issues/2357

---

en/docs/reference/config-catalog.md

Fixes https://github.com/wso2/docs-apim/issues/2188

[3.2.0] Fix throttle condition group configs Configuration Catalog 

---

en/docs/learn/api-controller/getting-started-with-wso2-api-controller.md

This PR adds binaries to the APICTL download details and removes redirection to the tooling website.

Add binaries to download section in CTL

---

en/docs/administer/managing-users-and-roles/managing-users-for-admin-portal.md

Merge commit https://github.com/wso2/docs-apim/commit/defd3319af83f24ac29476007f3705f1d4e73dee
3.2.0

Refine the Docs of Setting up a user for the Admin Portal 

---

en/docs/install-and-setup/installation-guide/installing-the-product/installing-the-binary/installing-as-a-linux-service.md

fix for https://github.com/wso2/docs-apim/issues/2413

fix for https://github.com/wso2/docs-apim/issues/2413

---

en/docs/learn/design-api/api-versioning/enabling-notifications.md
en/docs/reference/config-catalog.md
en/docs/reference/configs.json
en/tools/config-catalog-generator/data/apim.cache.gateway_token.toml
en/tools/config-catalog-generator/data/apim.notification.toml
en/tools/config-catalog-generator/data/configs.json
en/tools/config-catalog-generator/dist/config-catalog.md

This PR updates the docs related to notification enabling in APIM 3.1.0.
Related doc issue: https://github.com/wso2/docs-apim/issues/2376

[3.1.0] Update docs for notification enabling

---

en/docs/learn/design-api/api-versioning/enabling-notifications.md
en/docs/reference/config-catalog.md
en/docs/reference/configs.json
en/tools/config-catalog-generator/data/apim.cache.gateway_token.toml
en/tools/config-catalog-generator/data/apim.notification.toml
en/tools/config-catalog-generator/data/configs.json
en/tools/config-catalog-generator/dist/config-catalog.md

This PR updates the docs related to notification enabling in APIM 3.0.0.
Related doc issue: https://github.com/wso2/docs-apim/issues/2376

[3.0.0] Update docs for notification enabling

---

en/docs/learn/consume-api/invoke-apis/invoke-apis-using-tools/invoke-an-graphql-api-using-the-integrated-graphql-console.md
en/docs/learn/consume-api/invoke-apis/invoke-apis-using-tools/try-out-using-postman.md

change position of notes

---

en/docs/learn/consume-api/invoke-apis/invoke-apis-using-tools/invoke-an-graphql-api-using-the-integrated-graphql-console.md

Reviewed "Invoke a GraphQL API using the Integrated GraphQL Console" page fully

Reviewed GraphQL Console page

---

en/docs/learn/tutorials/create-and-publish-websocket-api.md

[3.1.0] Fixing `wscat` command

---

en/docs/learn/tutorials/create-and-publish-websocket-api.md

[3.0.0] Fixing `wscat` command

---

en/docs/administer/logging-and-monitoring/monitoring/monitoring-server-health.md
en/mkdocs.yml

- Related to https://github.com/wso2/docs-apim/issues/1778
- Updated and added configs to run monitoring API.

[master]  Update Monitoring Server Health Docs

---

en/docs/administer/logging-and-monitoring/monitoring/monitoring-server-health.md
en/mkdocs.yml

Related to https://github.com/wso2/docs-apim/issues/1778
Updated and added configs to run monitoring API.

[3.2.0] Update Monitoring Server Health Docs

---

en/docs/reference/config-catalog.md
en/docs/reference/configs.json
en/tools/config-catalog-generator/data/apim.analytics.toml
en/tools/config-catalog-generator/data/apim.analytics.url_group.toml
en/tools/config-catalog-generator/data/apim.cache.jwt_claim.toml
en/tools/config-catalog-generator/data/apim.cache.publisher_roles.toml
en/tools/config-catalog-generator/data/apim.cache.scopes.toml
en/tools/config-catalog-generator/data/apim.cache.tags.toml
en/tools/config-catalog-generator/data/apim.cors.toml
en/tools/config-catalog-generator/data/apim.devportal.toml
en/tools/config-catalog-generator/data/apim.key_manager.toml
en/tools/config-catalog-generator/data/apim.oauth_config.toml
en/tools/config-catalog-generator/data/apim.open_tracer.toml
en/tools/config-catalog-generator/data/apim.sdk.toml
en/tools/config-catalog-generator/data/apim.throttling.toml
en/tools/config-catalog-generator/data/apim.throttling.url_group.toml
en/tools/config-catalog-generator/data/apim.token.revocation.toml
en/tools/config-catalog-generator/data/apim.workflow.toml
en/tools/config-catalog-generator/data/configs.json
en/tools/config-catalog-generator/dist/config-catalog.md
en/tools/config-catalog-generator/templates/_configs.njk
en/tools/config-catalog-generator/templates/index.njk

This PR fixes the inconsistencies in the config catalog related files for the master branch.
- Added missing configs
- Synced files in en/docs/reference and en/tools
- Added sample .toml files for all configs
- Updated the script template files
Related doc issue: https://github.com/wso2/docs-apim/issues/2383

[3.1.0] Fix and sync config catalog inconsistencies

---

en/docs/reference/config-catalog.md
en/docs/reference/configs.json
en/tools/config-catalog-generator/data/apim.analytics.toml
en/tools/config-catalog-generator/data/apim.analytics.url_group.toml
en/tools/config-catalog-generator/data/apim.cache.jwt_claim.toml
en/tools/config-catalog-generator/data/apim.cache.publisher_roles.toml
en/tools/config-catalog-generator/data/apim.cache.scopes.toml
en/tools/config-catalog-generator/data/apim.cache.tags.toml
en/tools/config-catalog-generator/data/apim.cors.toml
en/tools/config-catalog-generator/data/apim.devportal.toml
en/tools/config-catalog-generator/data/apim.key_manager.toml
en/tools/config-catalog-generator/data/apim.oauth_config.toml
en/tools/config-catalog-generator/data/apim.open_tracer.toml
en/tools/config-catalog-generator/data/apim.sdk.toml
en/tools/config-catalog-generator/data/apim.throttling.toml
en/tools/config-catalog-generator/data/apim.throttling.url_group.toml
en/tools/config-catalog-generator/data/apim.token.revocation.toml
en/tools/config-catalog-generator/data/apim.workflow.toml
en/tools/config-catalog-generator/data/configs.json
en/tools/config-catalog-generator/dist/config-catalog.md
en/tools/config-catalog-generator/templates/_configs.njk
en/tools/config-catalog-generator/templates/index.njk

This PR fixes the inconsistencies in the config catalog related files for the master branch.
- Added missing configs
- Synced files in en/docs/reference and en/tools
- Added sample .toml files for all configs
- Updated the script template files
Related doc issue: https://github.com/wso2/docs-apim/issues/2383

[3.0.0] Fix and sync config catalog inconsistencies

---

en/docs/develop/customizations/customizing-the-developer-portal/advanced-customization.md

Initial two steps for building the customizations were missing in the documentation
Update the UI customization steps for portal apps
- Doc [link](https://apim.docs.wso2.com/en/latest/develop/customizations/customizing-the-developer-portal/advanced-customization/#advanced-customization)
- Followed secure coding standards in http://wso2.com/technical-reports/wso2-secure-engineering-guidelines? yes/~no~
- Confirmed that this PR doesn't commit any keys, passwords, tokens, usernames, or other secrets? yes/~no~

Add missing initial steps when building customizations

---

en/docs/develop/product-apis/admin-apis/admin-v1/admin-v1.yaml
en/docs/develop/product-apis/devportal-apis/devportal-v1/devportal-v1.yaml
en/docs/develop/product-apis/publisher-apis/publisher-v1/publisher-v1.yaml

This PR updates the latest OAS definitions of Publisher, Store and Admin portals. 
Related PR - https://github.com/wso2/carbon-apimgt/pull/9384
Related GIT issue - https://github.com/wso2/product-apim/issues/9418

Update OAS 3.0 definitions of Portal APIs

---

en/docs/administer/logging-and-monitoring/monitoring/monitoring-with-opentracing.md

This PR adds a sample config for jaeger in open tracing docs.
Related doc issue: https://github.com/wso2/docs-apim/issues/2250

[master] Add sample opentracer configs

---

en/docs/administer/logging-and-monitoring/monitoring/monitoring-with-opentracing.md

This PR adds a sample config for jaeger in open tracing docs.
Related doc issue: https://github.com/wso2/docs-apim/issues/2250

[3.2.0] Add sample opentracer configs

---

en/docs/administer/logging-and-monitoring/monitoring/monitoring-with-opentracing.md

This PR adds a sample config for jaeger in open tracing docs.
Related doc issue: https://github.com/wso2/docs-apim/issues/2250

[3.1.0] Add sample opentracer configs

---

en/docs/administer/logging-and-monitoring/monitoring/monitoring-with-opentracing.md

- Changed the pg title 
- related to https://github.com/wso2/docs-apim/pull/2453

Changed the pg title

---

en/docs/install-and-setup/setup/single-node/configuring-an-active-active-deployment.md

This PR adds a note in artifact synchronisation regarding NFS configurations.
Related doc issue: https://github.com/wso2/docs-apim/issues/1997

[master] Add note for NFS configs

---

en/docs/install-and-setup/setup/deployment-best-practices/security-guidelines-for-production-deployment.md

This PR adds production deployment related security guidelines for admin accounts.
Related doc issue: https://github.com/wso2/docs-apim/issues/2446

[master] Add security guidelines for admin accounts

---

en/docs/install-and-setup/setup/single-node/configuring-an-active-active-deployment.md

This PR adds a note in artifact synchronisation regarding NFS configurations.
Related doc issue: https://github.com/wso2/docs-apim/issues/1997

[3.2.0] Add note for NFS configs

---

en/docs/install-and-setup/setup/single-node/configuring-an-active-active-deployment.md

This PR adds a note in artifact synchronisation regarding NFS configurations.
Related doc issue: https://github.com/wso2/docs-apim/issues/1997

[3.1.0] Add note for NFS configs

---

en/docs/install-and-setup/deploying-wso2-api-manager/single-node/configuring-an-active-active-deployment.md

This PR adds a note in artifact synchronisation regarding NFS configurations.
Related doc issue: https://github.com/wso2/docs-apim/issues/1997

[3.0.0] Add note for NFS configs

---

en/docs/install-and-setup/upgrading-wso2-api-manager/upgrading-from-250-to-310.md
en/docs/install-and-setup/upgrading-wso2-api-manager/upgrading-from-260-to-310.md
en/docs/install-and-setup/upgrading-wso2-api-manager/upgrading-from-300-to-310.md
en/docs/learn/analytics/configuring-apim-analytics.md

This PR adds information regarding adding collation level case sensitive support for databases in MySQL and MSSQL.
Related issue: https://github.com/wso2/streaming-integrator/issues/158
https://github.com/wso2/docs-apim/issues/2447

Add collation info for ANALYTICS_DB on primary key violations

---

en/docs/administer/logging-and-monitoring/monitoring/monitoring-server-health.md
en/mkdocs.yml

This PR updates the docs related to monitoring API.
Related doc issue: https://github.com/wso2/docs-apim/issues/1778

[3.1.0] Update Monitoring Server Health Docs

---

en/docs/administer/product-administration/managing-users-and-roles/managing-user-stores/configure-primary-user-store/configuring-a-jdbc-user-store.md

fixes https://github.com/wso2/docs-apim/issues/2464

fixes https://github.com/wso2/docs-apim/issues/2464

---

en/docs/administer/managing-users-and-roles/managing-user-stores/configure-primary-user-store/configuring-a-jdbc-user-store.md

fix for https://github.com/wso2/docs-apim/issues/2464

fix for https://github.com/wso2/docs-apim/issues/2464

---

en/docs/install-and-setup/setup/setting-up-databases/changing-default-databases/changing-to-mssql.md
en/docs/install-and-setup/setup/setting-up-databases/changing-default-databases/changing-to-mysql.md
en/docs/install-and-setup/setup/setting-up-databases/changing-default-databases/changing-to-oracle-rac.md
en/docs/install-and-setup/setup/setting-up-databases/changing-default-databases/changing-to-oracle.md
en/docs/install-and-setup/setup/setting-up-databases/changing-default-databases/changing-to-postgresql.md

Fixes https://github.com/wso2/docs-apim/issues/2467 …

Fixes https://github.com/wso2/docs-apim/issues/2467

---

en/docs/install-and-setup/setup/setting-up-databases/changing-default-databases/changing-to-mssql.md
en/docs/install-and-setup/setup/setting-up-databases/changing-default-databases/changing-to-mysql.md
en/docs/install-and-setup/setup/setting-up-databases/changing-default-databases/changing-to-oracle-rac.md
en/docs/install-and-setup/setup/setting-up-databases/changing-default-databases/changing-to-oracle.md
en/docs/install-and-setup/setup/setting-up-databases/changing-default-databases/changing-to-postgresql.md

Fixes https://github.com/wso2/docs-apim/issues/2467 in APIM 3.2.0 docs …

Fixes https://github.com/wso2/docs-apim/issues/2467 in APIM 3.2.0 docs

---

en/docs/install-and-setup/setup/setting-up-databases/changing-default-databases/changing-to-mssql.md
en/docs/install-and-setup/setup/setting-up-databases/changing-default-databases/changing-to-mysql.md
en/docs/install-and-setup/setup/setting-up-databases/changing-default-databases/changing-to-oracle-rac.md
en/docs/install-and-setup/setup/setting-up-databases/changing-default-databases/changing-to-oracle.md
en/docs/install-and-setup/setup/setting-up-databases/changing-default-databases/changing-to-postgresql.md

Fixes https://github.com/wso2/docs-apim/issues/2467 in APIM 3.1.0 docs …

Fixes https://github.com/wso2/docs-apim/issues/2467 in APIM 3.1.0 docs

---

en/docs/install-and-setup/setting-up-databases/changing-default-databases/changing-to-mssql.md
en/docs/install-and-setup/setting-up-databases/changing-default-databases/changing-to-mysql.md
en/docs/install-and-setup/setting-up-databases/changing-default-databases/changing-to-oracle-rac.md
en/docs/install-and-setup/setting-up-databases/changing-default-databases/changing-to-oracle.md
en/docs/install-and-setup/setting-up-databases/changing-default-databases/changing-to-postgresql.md

Fixes https://github.com/wso2/docs-apim/issues/2467 in APIM 3.0.0 docs …

Fixes https://github.com/wso2/docs-apim/issues/2467 in APIM 3.0.0 docs

---

en/docs/install-and-setup/upgrading-wso2-api-manager/upgrading-from-250-to-310.md
en/docs/install-and-setup/upgrading-wso2-api-manager/upgrading-from-260-to-310.md
en/docs/install-and-setup/upgrading-wso2-api-manager/upgrading-from-300-to-310.md
en/docs/learn/analytics/configuring-apim-analytics.md

This PR fixes an issue in the description of the note of database collation added in https://github.com/wso2/docs-apim/pull/2276.

[3.1.0] Fix issue in description of database collation for analytics

---

en/docs/install-and-setup/upgrading-wso2-api-manager/upgrading-from-250-to-300.md
en/docs/install-and-setup/upgrading-wso2-api-manager/upgrading-from-260-to-300.md
en/docs/learn/analytics/configuring-apim-analytics.md

This PR adds information regarding adding collation level case sensitive support for databases in MySQL and MSSQL.
Related doc issue: https://github.com/wso2/docs-apim/issues/2447

[3.0.0] Add collation info for ANALYTICS_DB on primary key violations

---

en/docs/getting-started/overview.md
en/docs/learn/api-security/oauth2/grant-types/authorization-code-grant.md

PR sync for https://github.com/wso2/docs-apim/pull/886 for the 3.1.0 branch.

Updating architecture diagrams

---

en/docs/administer/managing-users-and-roles/managing-user-roles.md
en/docs/getting-started/about-this-release.md
en/docs/learn/api-security/oauth2/oauth2-scopes/fine-grained-access-control-with-oauth-scopes.md

Fix https://github.com/wso2/docs-apim/issues/2481

Remove local scopes from deprecated list

---

en/docs/develop/product-apis/devportal-apis/devportal-v1/devportal-v1.yaml

Related to https://github.com/wso2/product-apim/issues/9595
Doc Changes for https://github.com/wso2/carbon-apimgt/pull/9454
APIM 4.0.0

[4.0.0] Displaying comments with User Information in REST APIs

---

en/docs/learn/api-controller/getting-started-with-wso2-api-controller.md

> Fixing 64x download location

Fixing 64x download location

---

en/docs/learn/api-controller/advanced-topics/configuring-different-endpoint-types.md
en/docs/learn/api-controller/advanced-topics/configuring-environment-specific-parameters.md

With the new changes stated in the following doc [1] the API Controller documentation and examples need to be changed. These changes will be reflected in doc space with this PR.
[1]. https://docs.google.com/document/d/1_pvfEUzI86Fa4280iRtS16pfhEB_3FqznNbvCJKXqlo/edit
Fixes https://github.com/wso2/product-apim-tooling/issues/540
1. https://github.com/wso2/carbon-apimgt/pull/9420
2. https://github.com/wso2/product-apim-tooling/pull/535
APIM - Latest Master branch version

[Docs] Documentation changes related to the feature of resolving env-parameters at server-side while importing an API project 

---

en/docs/learn/api-security/oauth2/access-token-types/jwt-tokens.md

Adding the changes added in https://github.com/wso2/docs-apim/pull/2487 to 3.2.0 so that PRs [1] and [2] will be the same.
[1] https://github.com/wso2/docs-apim/pull/2061
[2] https://github.com/wso2/docs-apim/pull/2487

Updated the image paths

---

en/docs/streaming/extracting-data-from-static-sources-in-real-time/extracting-data-from-static-sources-in-real-time.md
en/docs/use-cases/examples/streaming_examples/CDCWithListeningMode.md
en/docs/use-cases/streaming-tutorials/creating-etl-application-via-tooling.md
en/docs/use-cases/streaming-tutorials/performing-real-time-etl-with-mysql.md
en/docs/use-cases/streaming-usecase/extracting-data-from-static-sources-in-real-time.md

Update instructions for enabling binary logs

---

en/docs/learn/analytics/customizing-analytics-dashboards.md

> Resolves https://github.com/wso2/docs-apim/issues/1838 for 3.1.0

permission to other users to create dashboards.

---

en/docs/learn/analytics/managing-dashboard-permissions.md

Update the content to provide permission to other users to create dashboards in analytics

---

en/docs/learn/analytics/viewing-api-statistics/application-analytics-dashboard.md

>Resolves issue https://github.com/wso2/docs-apim/issues/1935 for 3.2.0

Content corrected in Application analytics page 

---

en/mkdocs.yml

fixed controller and K8 operator doc paths

---

CODEOWNERS
en/CODEOWNERS

Add **CODEOWNER** file for repo

Add Code owner info

---

CODEOWNERS

Add Code owner info 

---

en/docs/assets/attachments/install-and-setup/apim200_to_apim310_gateway_artifact_migrator.sh
en/docs/assets/attachments/install-and-setup/apim210_to_apim310_gateway_artifact_migrator.sh
en/docs/assets/attachments/install-and-setup/apim220_to_apim310_gateway_artifact_migrator.sh

This PR will update artifact migrator scripts to remove Throttle Handler config from APIs
> Link(s) to product documentation …

Update artifact migrator to remove Throttle Handler config from APIs

---

en/docs/administer/key-managers/configure-wso2is-connector.md

Fix for https://github.com/wso2/docs-apim/issues/2509

Fix for port offset cmd issue

---

en/docs/install-and-setup/setup/distributed-deployment/configuring-wso2-identity-server-as-a-key-manager.md

fix for https://github.com/wso2/docs-apim/issues/2119

Fix keymanager webapp ep issue

---

en/tools/config-catalog-generator/data/configs.json
en/tools/config-catalog-generator/dist/config-catalog.md

fix docs-apim/issues/2514 correct package name
