en/docs/includes/design/create-streaming-api/create-a-streaming-api-from-an-asyncapi-definition.md
Partly fixes https://github.com/wso2/docs-apim/issues/4303
=> Partly fixes https://github.com/wso2/docs-apim/issues/4303

en/docs/install-and-setup/setup/reference/default-product-ports.md
fixes https://github.com/wso2/docs-apim/issues/4316
=> fixes https://github.com/wso2/docs-apim/issues/4316

en/docs/api-analytics/getting-started-guide.md
- fixes https://github.com/wso2/docs-apim/issues/4298
- Added the Analytics dashboard link.
=> fixes https://github.com/wso2/docs-apim/issues/4298

en/docs/deploy-and-publish/deploy-on-gateway/deploy-api/exposing-apis-via-custom-hostnames.md
fixes https://github.com/wso2/docs-apim/issues/4289
=> fixes https://github.com/wso2/docs-apim/issues/4289

en/docs/administer/logging-and-monitoring/logging/monitoring-http-access-logs.md
[3.1.0] fixes https://github.com/wso2/docs-apim/issues/4284
=> [3.1.0] fixes https://github.com/wso2/docs-apim/issues/4284

en/docs/administer/logging-and-monitoring/logging/monitoring-http-access-logs.md
fixes https://github.com/wso2/docs-apim/issues/4284
=> [3.2.0] fixes https://github.com/wso2/docs-apim/issues/4284

en/docs/administer/logging-and-monitoring/logging/monitoring-http-access-logs.md
[4.0.0] fixes https://github.com/wso2/docs-apim/issues/4284
=> [4.0.0] fixes https://github.com/wso2/docs-apim/issues/4284

en/docs/install-and-setup/setup/security/configuring-transport-level-security.md
fixes https://github.com/wso2/docs-apim/issues/4210
=> fixes https://github.com/wso2/docs-apim/issues/4210

en/docs/reference/connectors/mongodb-connector/mongodb-connector-example.md, en/docs/streaming/getting-started/getting-started-guide-overview.md, en/docs/streaming/getting-started/monitor-statistics.md, en/docs/streaming/getting-started/test-siddhi-application.md, en/docs/use-cases/streaming-usecase/use-cases.md
=> Fixing broken links - Part 3

en/docs/consume/manage-application/generate-keys/revoke-oauth2-application.md
fixes https://github.com/wso2/docs-apim/issues/4124
=> fixes https://github.com/wso2/docs-apim/issues/4124

en/docs/install-and-setup/setup/reference/product-compatibility.md
We have tested APIM 3.20 in windows 2019. hence need to update the doc accordingly.
> Link(s) to product documentation that …
=> Add windows 2019 compatibility.

en/docs/install-and-setup/setup/distributed-deployment/understanding-the-distributed-deployment-of-wso2-api-m.md
fixes https://github.com/wso2/docs-apim/issues/4006
=> fixes https://github.com/wso2/docs-apim/issues/4006

en/docs/administer/logging-and-monitoring/logging/monitoring-http-access-logs.md
fixes https://github.com/wso2/docs-apim/issues/4284
=> fixes https://github.com/wso2/docs-apim/issues/4284

en/docs/reference/connectors/file-connector/3.x/file-connector-3.x-config.md
=> Introduce new params for delete and isFileExist operations

en/docs/reference/config-catalog.md, en/tools/config-catalog-generator/data/configs.json, en/tools/config-catalog-generator/data/custom_keystore.toml, en/tools/config-catalog-generator/dist/config-catalog.md
=> Added custom keystore TOML file

en/docs/integrate/develop/creating-artifacts/creating-an-api.md
=> Fixes E1065

en/docs/install-and-setup/setup/deployment-best-practices/security-guidelines-for-production-deployment.md
=> Fixes A847

en/docs/install-and-setup/setup/single-node/configuring-an-active-active-deployment.md
=> Fixes A909

en/docs/learn/consume-api/generating-sdks/generate-sdks-in-dev-portal.md
Fixes: https://github.com/wso2/product-apim/issues/11519
- https://github.com/wso2/docs-apim/pull/3991
- https://github.com/wso2/docs-apim/pull/3998
=> [3.1.0] Updating the supported SDK types

en/docs/learn/consume-api/generating-sdks/generate-sdks-in-dev-portal.md
Fixes: https://github.com/wso2/product-apim/issues/11519
- https://github.com/wso2/docs-apim/pull/3991
- https://github.com/wso2/docs-apim/pull/3998
=> [3.0.0] Updating the supported SDK types

en/docs/install-and-setup/upgrading-wso2-api-manager/upgrading-from-1100-to-400.md, en/docs/install-and-setup/upgrading-wso2-api-manager/upgrading-from-200-to-400.md, en/docs/install-and-setup/upgrading-wso2-api-manager/upgrading-from-210-to-400.md, en/docs/install-and-setup/upgrading-wso2-api-manager/upgrading-from-220-to-400.md, en/docs/install-and-setup/upgrading-wso2-api-manager/upgrading-from-250-to-400.md, en/docs/install-and-setup/upgrading-wso2-api-manager/upgrading-from-260-to-400.md, en/docs/install-and-setup/upgrading-wso2-api-manager/upgrading-from-300-to-400.md, en/docs/install-and-setup/upgrading-wso2-api-manager/upgrading-from-310-to-400.md, en/docs/install-and-setup/upgrading-wso2-api-manager/upgrading-from-320-to-400.md
=> Fixes A893

en/docs/install-and-setup/install/installing-the-product/running-the-mi-dashboard.md, en/docs/reference/config-catalog-mi-dashboard.md
- Add MI version and additional param configs to SSO config docs added by https://github.com/wso2/docs-apim/pull/4439
=> Add MI version and additional param configs

en/docs/install-and-setup/setup/reference/common-runtime-and-configuration-artifacts.md
=> Update Fix A909

en/docs/install-and-setup/setup/deployment-best-practices/performance-test-results-mi.md
Corrects the broken image links.
=> Correct performance test result image links

en/docs/install-and-setup/setup/deployment-best-practices/performance-test-results-mi.md
=> Add missed quotes

en/docs/install-and-setup/setup/deployment-best-practices/performance-test-results-mi.md
=> Fixed broken images

en/docs/troubleshooting/error-handling-mi.md, en/mkdocs.yml
Adding an error codes page for MI.
=> Error Codes for MI

en/docs/administer/logging-and-monitoring/monitoring/monitoring-with-opentracing.md
Adding the missing configurations to enable the open tracing log tracing feature.
Fixes: https://github.com/wso2/docs-apim/issues/4492
=> [3.2.0] Adding the missing configurations to enable the open tracing log tracing feature.

en/docs/administer/logging-and-monitoring/monitoring/monitoring-with-opentracing.md
Adding the missing configurations to enable the open tracing log tracing feature.
Fixes: https://github.com/wso2/docs-apim/issues/4492
https://github.com/wso2/docs-apim/pull/4493
=> [3.1.0] Adding the missing configurations to enable the open tracing log tracing feature

en/docs/administer/logging-and-monitoring/monitoring/monitoring-with-opentracing.md
Adding the missing configurations to enable the open tracing log tracing feature.
Fixes: https://github.com/wso2/docs-apim/issues/4492
https://github.com/wso2/docs-apim/pull/4493
=> [4.0.0] Adding the missing configurations to enable the open tracing log tracing feature

en/docs/get-started/api-manager-quick-start-guide.md, en/mkdocs.yml
Changed the QSG names in the left navigation to avoid repetition.
=> Renamed QSGs in the structure

en/docs/reference/connectors/ldap-connector/ldap-server-configuration.md
Sync PR for https://github.com/wso2/docs-ei/pull/2829
=> LDAP Connector Search for >= JSON format

en/docs/includes/design/create-streaming-api/create-a-websocket-streaming-api.md
Fixes https://github.com/wso2/docs-apim/issues/3806
=> Add Deploy API link to WebSocket page

en/docs/install-and-setup/upgrading-wso2-api-manager/upgrading-from-250-to-400.md, en/docs/install-and-setup/upgrading-wso2-api-manager/upgrading-from-260-to-400.md, en/docs/install-and-setup/upgrading-wso2-api-manager/upgrading-from-300-to-400.md, en/docs/install-and-setup/upgrading-wso2-api-manager/upgrading-from-310-to-400.md, en/docs/install-and-setup/upgrading-wso2-api-manager/upgrading-from-320-to-400.md
=> GW environment name change coming to APIM 400 from an old version

en/docs/get-started/api-manager-quick-start-guide.md
review changes for https://github.com/wso2/docs-apim/pull/4546
=> review changes for https://github.com/wso2/docs-apim/pull/4546

en/docs/develop/customizations/advanced-ui-customization.md
=> Adding a note about allocating memory if npm build command fails

en/theme/material/partials/header.html
Adds the banner note pointing to latest release. Tested locally.
=> Add note to 3.2.0 banner

en/theme/material/partials/header.html
Fixes https://github.com/wso2/docs-apim/issues/4270
=> Add note to banner

en/docs/develop/customizations/advanced-ui-customization.md
=> Add UI customization section for Admin app

en/docs/getting-started/about-this-release.md, en/docs/learn/api-gateway/message-tracing.md
=> Deprecated feature - Message tracing

en/docs/learn/consume-api/generating-sdks/write-a-client-application-using-the-sdk.md
=> Update the code sample of the API SDK integration with a client application + renewable access tokens

en/docs/assets/attachments/install-and-setup/reg-index.sql
=> Add primary key to temp table for reg indexing

en/docs/api-analytics/getting-started-guide.md
=> Add endpoint info for Choreo Analytics Cloud in QSG

en/docs/reference/connectors/exporting-artifacts.md, en/docs/reference/connectors/google-spreadsheet-connector/get-credentials-for-google-spreadsheet.md, en/docs/reference/connectors/importing-connector-to-integration-studio.md, en/docs/reference/connectors/kafka-connector/kafka-connector-producer-example.md, en/mkdocs.yml
=> Kafka Connector configuration in WSO2 Integration Studio-8.0.0

en/docs/install-and-setup/setup/setting-up-databases/changing-default-databases/changing-to-oracle.md
=> Configure Oracle DB - URL parameter

en/docs/learn/api-gateway/message-mediation/adding-dynamic-endpoints.md, en/docs/learn/api-gateway/message-mediation/changing-the-default-mediation-flow-of-api-requests.md
=> Dynamic Endpoint Sample | Mediation Extensions

en/docs/api-analytics/api-analytics-architecture.md, en/docs/api-analytics/configure-alerts.md, en/docs/api-analytics/getting-started-guide.md, en/docs/api-analytics/role-based-access-control.md, en/docs/api-analytics/viewing/introduction-to-api-analytics-dashboard.md, en/docs/api-analytics/viewing/view-overview-of-api-analytics.md, en/docs/deploy-and-publish/deploy-on-gateway/choreo-connect/configure-analytics.md, en/docs/includes/analytics/configure-synapse-gateway.md, en/docs/tutorials/scenarios/scenario7-analytics.md
Update analytics portal url to choreo insights url …
=> Update analytics portal url to choreo insights url

en/docs/design/advanced-topics/enabling-cors-for-apis.md
Fix description of supported swagger extension for CORS
Related Issue: https://github.com/wso2/docs-apim/issues/2937
=> [4.0.0] Fix Description of Supported Swagger Extension for CORS

en/docs/design/advanced-topics/enabling-cors-for-apis.md
Fix description of supported swagger extension for CORS
Related Issue: https://github.com/wso2/docs-apim/issues/2937
=> Fix Description of Supported Swagger Extension for CORS

en/docs/learn/design-api/advanced-topics/enabling-cors-for-apis.md
Fix description of supported swagger extension for CORS
Related Issue: https://github.com/wso2/docs-apim/issues/2937
=> [3.2.0] Fix Description of Supported Swagger Extension for CORS

en/docs/install-and-setup/setup/mi-setup/security/using-hashicorp-secrets.md
> $subject
Fixes: https://github.com/wso2/docs-apim/issues/3652
=> Update HashiCorp vault configurations structure and typos

en/docs/learn/design-api/publish-api/publish-through-multiple-api-gateways.md
Affected Page: https://apim.docs.wso2.com/en/3.0.0/learn/design-api/publish-api/publish-through-multiple-api-gateways/#step-1-publish-an-api-via-multiple-api-gateways
Fixes https://github.com/wso2/docs-apim/issues/3355 for APIM 3.0.0.
=> [3.0.0] Update configs when API Manager publishing via multiple gateways

en/docs/learn/design-api/publish-api/publish-through-multiple-api-gateways.md
Affected Page: https://apim.docs.wso2.com/en/3.2.0/learn/design-api/publish-api/publish-through-multiple-api-gateways/#step-1-publish-an-api-via-multiple-api-gateways
Fixes https://github.com/wso2/docs-apim/issues/3355 for APIM 3.2.0.
=> [3.2.0] Update configs when API Manager publishing via multiple gateways

en/docs/learn/design-api/publish-api/publish-through-multiple-api-gateways.md
Affected Page: https://apim.docs.wso2.com/en/3.1.0/learn/design-api/publish-api/publish-through-multiple-api-gateways/#step-1-publish-an-api-via-multiple-api-gateways
Fixes https://github.com/wso2/docs-apim/issues/3355 for APIM 3.1.0.
=> [3.1.0] Update configs when API Manager publishing via multiple gateways

en/docs/deploy-and-publish/deploy-on-gateway/deploy-api/deploy-through-multiple-api-gateways.md
Affected Page: https://apim.docs.wso2.com/en/latest/deploy-and-publish/deploy-on-gateway/deploy-api/deploy-through-multiple-api-gateways/#!
Fixes https://github.com/wso2/docs-apim/issues/3355 for APIM Master docs.
=> [4.0.0] Update configs when API Manager publishing via multiple gateways

en/docs/deploy-and-publish/deploy-on-gateway/deploy-api/deploy-through-multiple-api-gateways.md
Affected Page: https://apim.docs.wso2.com/en/latest/deploy-and-publish/deploy-on-gateway/deploy-api/deploy-through-multiple-api-gateways/#!
Fixes https://github.com/wso2/docs-apim/issues/3355 for APIM Master docs.
=> [Master] Update configs when API Manager publishing via multiple gateways

en/docs/install-and-setup/setup/mi-setup/security/using-hashicorp-secrets.md
> $subject
Fixes: https://github.com/wso2/docs-apim/issues/3653
=> Add relevant docs to enable HashiCorp AppRole method

en/docs/reference/connectors/file-connector/file-connector-config.md
This is to fix https://github.com/wso2/docs-apim/issues/4437
Please merge after running on mkdocs
=> Add xml elements to file connector docs

en/docs/reference/customize-product/extending-api-manager/extending-key-management/writing-custom-grant-types.md
fix https://github.com/wso2/docs-apim/issues/4273 and https://github.com/wso2/docs-apim/issues/3065
=> Update grant handler class names in extension docs

en/docs/observe/mi-observe/working-with-monitoring-dashboard.md
Fixes https://github.com/wso2/docs-apim/issues/3553
=> Update Monitoring Dashboard docs

en/docs/learn/api-controller/importing-apis-via-dev-first-approach.md
Add a note stating the requirement to change template file before using in Dev first approach to avoid confusion.
Affected Page: https://apim.docs.wso2.com/en/3.2.0/learn/api-controller/importing-apis-via-dev-first-approach/
Fixes https://github.com/wso2/docs-apim/issues/4433 for APIM 3.2.0 Docs
=> [3.2.0] Add a note stating the requirement to change template file before using in Dev first approach

en/docs/learn/api-controller/importing-apis-via-dev-first-approach.md
Add a note stating the requirement to change template file before using in Dev first approach to avoid confusion.
Affected Page: https://apim.docs.wso2.com/en/3.1.0/learn/api-controller/importing-apis-via-dev-first-approach/
Fixes https://github.com/wso2/docs-apim/issues/4433 for APIM 3.1.0 Docs
=> [3.1.0] Add a note stating the requirement to change template file before using in Dev first approach

en/docs/install-and-setup/setup/api-controller/managing-apis-api-products/importing-apis-via-dev-first-approach.md
Add a note stating the requirement to change template file before using in Dev first approach to avoid confusion.
Affected Page: https://apim.docs.wso2.com/en/latest/install-and-setup/setup/api-controller/managing-apis-api-products/importing-apis-via-dev-first-approach/
Fixes https://github.com/wso2/docs-apim/issues/4433 for APIM Master Docs
=> [Master] Add a note stating the requirement to change template file before using in Dev first approach

en/docs/administer/managing-users-and-roles/managing-user-roles.md, en/docs/reference/customize-product/extending-api-manager/extending-key-management/writing-custom-grant-types.md
=> Remove carbon role permission addition | Fix custom grant handler class names

en/docs/install-and-setup/setup/setting-up-proxy-server-and-the-load-balancer/configuring-the-proxy-server-and-the-load-balancer.md
=> Missing configuration related to load balancer proxy settings

en/docs/install-and-setup/setup/setting-up-proxy-server-and-the-load-balancer/configuring-the-proxy-server-and-the-load-balancer.md
=> Missing configuration related to load balancer proxy settings 

en/docs/reference/connectors/file-connector/file-connector-config.md
This is to fix https://github.com/wso2/docs-apim/issues/4437
> Link(s) to product documentation that addresses the changes of …
=> Update fileConnection tag name

en/docs/install-and-setup/setup/security/configuring-transport-level-security.md
=> Add configurations to enable Passthrough transport level ciphers and TLS versions

en/docs/assets/attachments/learn/analytics/geo-location/linux/update-geolocation-data.sh
=> Creating Geo Location Data Set - update-geolocation-data.sh script  

en/docs/install-and-setup/setup/single-node/configuring-an-active-active-deployment.md
=> Remove deployment synchronization related content

en/docs/reference/vendor-extensions-catalog.md
=> Application and Application User separation is removed in 3.x versions

en/docs/install-and-setup/install-and-setup-overview.md, en/docs/install-and-setup/setup/mi-setup/observability/observability-deployment-strategy.md, en/docs/integrate/integration-overview.md, en/docs/observe/api-manager/metrics/jmx-based-monitoring.md, en/docs/observe/api-manager/monitoring-http-access-logs.md, en/docs/observe/api-manager/traces/monitoring-with-opentracing.md, en/docs/observe/micro-integrator/classic-observability-logs/configuring-log4j2-properties.md, en/docs/observe/micro-integrator/cloud-native-observability-overview.md, en/docs/observe/micro-integrator/setting-up-cloud-native-observability-in-kubernetes.md, en/docs/observe/micro-integrator/setting-up-cloud-native-observability-on-a-vm.md, en/docs/observe/observe-overview.md, en/mkdocs.yml
- fixes https://github.com/wso2/docs-apim/issues/4269
- updating observe related overviews
=> fixes https://github.com/wso2/docs-apim/issues/4269

en/docs/deploy-and-publish/deploy-on-gateway/api-gateway/overview-of-the-api-gateway.md
=> Resized images

en/mkdocs.yml
changed 4.0 versions based on master
=> changed 4.0 versions based on master

en/docs/install-and-setup/setup/mi-setup/security/using-hashicorp-secrets.md
This PR updates the doc on environment variable support in HashCorp lookup.
Related PR: https://github.com/wso2-support/micro-integrator/pull/279
=> [4.0.0] Update MI doc on hashicorp environment variable support

en/docs/develop/extending-api-manager/extending-key-management/writing-custom-grant-types.md
fix https://github.com/wso2/docs-apim/issues/3065
=> Update 3.2.0 docs on custom grant handlers based on wum updates

en/docs/observe/mi-observe/working-with-monitoring-dashboard.md
Update docs for wso2/micro-integrator#2135
=> Update dashboard document for Kubernetes environment

en/docs/install-and-setup/setup/distributed-deployment/product-profiles.md
> Fix: https://github.com/wso2/docs-apim/issues/3413
=> Fix profile optimization doc issue

en/docs/learn/analytics/managing-dashboard-permissions.md
=> Modify the documentation to refer tenant-conf.json file in registry when adding new scopes or roles to existing scopes

en/mkdocs.yml
=> updated the left menu

en/docs/observe/mi-observe/working-with-management-api.md
Add doc update on wso2/micro-integrator#2388
=> Update management api documentation

en/docs/install-and-setup/setup/mi-setup/security/using-hashicorp-secrets.md
This PR updates the doc on environment variable support in HashCorp lookup.
Related PR: https://github.com/wso2/micro-integrator/pull/2432
=> Update MI doc on hashicorp environment variable support

en/docs/tutorials/scenarios/scenario-overview.md
=> Updated the correct project path to be cloned

en/docs/deploy-and-publish/deploy-on-gateway/choreo-connect/security/tls/mutual-tls-between-gateway-and-backend.md, en/docs/deploy-and-publish/deploy-on-gateway/choreo-connect/security/tls/transport-security.md, en/mkdocs.yml
Doc for Mutual TLS Between Choreo Connect and Backend
=> Mutual TLS Between Choreo Connect and Backend

en/docs/integrate/develop/create-docker-project.md
Fixes: https://github.com/wso2/docs-apim/issues/4775
=> Fix https://github.com/wso2/docs-apim/issues/4775

en/docs/integrate/examples/file-processing/accessing_windows_share_using_vfs_transport.md
E - 1254
Follow up with https://github.com/wso2/docs-ei/pull/2856
=> Add SMB-2 support for APIM

en/docs/get-started/about-this-release.md, en/docs/observe/micro-integrator/classic-observability-logs/monitoring-mi-audit-logs.md, en/mkdocs.yml
Doc PR for https://github.com/wso2/micro-integrator/pull/2412
Issue: 
https://github.com/wso2/micro-integrator/issues/2434
https://github.com/wso2/micro-integrator/issues/2437
=> Add audit log docs for MI

en/docs/get-started/about-this-release.md, en/docs/observe/micro-integrator/classic-observability-logs/monitoring-mi-audit-logs.md, en/mkdocs.yml
- fixes https://github.com/wso2/docs-apim/issues/4784
- Rectified the issue that was causing the build break.
- Improved the content
- Fixed an incorrect link
https://github.com/wso2/docs-apim/pull/4763
https://github.com/wso2/docs-apim/pull/4783
=> fixes https://github.com/wso2/docs-apim/issues/4784

en/docs/api-analytics/getting-started-guide.md
=> Fix Step 4 - View the Analytics Dashboards section link in the QSG

en/docs/design/api-security/oauth2/grant-types/client-credentials-grant.md
fixes https://github.com/wso2/docs-apim/issues/4794
=> fixes https://github.com/wso2/docs-apim/issues/4794

en/docs/learn/analytics/analytics-event-streams-and-aggregations.md
Fixes https://github.com/wso2/docs-apim/issues/4773 for APIM 3.2.0
=> Fixes explanation of the AGG_COUNT

en/docs/learn/analytics/analyzing-apim-statistics-with-batch-analytics/introducing-the-wso2-api-manager-statistics-model.md
=> Fixes explanation of the AGG_COUNT for APIM 3.0.0 

en/docs/learn/analytics/analyzing-apim-statistics-with-batch-analytics/introducing-the-wso2-api-manager-statistics-model.md
=> Fixes explanation of the AGG_COUNT for APIM 3.1.0

en/docs/install-and-setup/setup/mi-setup/security/encrypting_plain_text.md
This PR updates the encrypting_plain_text documentation with the section 'Start server as a background job'
=> [MI] Update encrypting_plain_text documentation

en/docs/develop/product-apis/gateway-apis/gateway-v1/gateway-v1.yaml
=> Improvement for Gateway Rest API

en/docs/reference/synapse-properties/data-services/sample-queries.md
This PR updates the dynamic query section of sample-queries documentation with a note.
=> [MI] [4.0.0] Update sample-queries documentation with a note

en/docs/reference/connectors/smpp-connector/smpp-connector-config.md
Sync PR for https://github.com/wso2/docs-ei/pull/2860
=> SMPP Connector - Bulk messaging section

en/docs/get-started/api-manager-quick-start-guide.md
Fixes image issue in the QSG. 
Issue: https://github.com/wso2/docs-apim/issues/4847
=> Fix QSG image

en/docs/install-and-setup/setup/security/logins-and-passwords/maintaining-logins-and-passwords.md
Fixes https://github.com/wso2/docs-apim/issues/4850
=> Change parameter 'receiver_username' in 'Setup e-mail login' section

en/mkdocs.yml
fixes https://github.com/wso2/docs-apim/issues/4851
=> fixes https://github.com/wso2/docs-apim/issues/4851

en/docs/install-and-setup/setup/security/logins-and-passwords/working-with-encrypted-passwords.md
Fixes https://github.com/wso2/docs-apim/issues/4312
=> Fix typo for truststore parameter

en/docs/install-and-setup/setup/api-controller/advanced-topics/configuring-environment-specific-parameters.md
Fixes: https://github.com/wso2/product-apim-tooling/issues/788
Updating the documentation on the support to configure advanced endpoint parameters of an API using the params file.
- Updated the template of the params file of an API/API Product in the **Configuring Environment Specific Parameters** page along with the examples.
The use case mentioned in [1] is supported now.
[1] https://github.com/wso2/product-apim-tooling/issues/787
=> [4.0.0] Updating the documentation on the support to configure advanced endpoint parameters of an API using the params file

en/docs/deploy-and-publish/deploy-on-gateway/choreo-connect/security/tls/mutual-tls-between-gateway-and-backend.md, en/docs/deploy-and-publish/deploy-on-gateway/choreo-connect/security/tls/transport-security.md, en/mkdocs.yml
Same as https://github.com/wso2/docs-apim/pull/4771 for 4.0.0
=> [4.0.0] Mutual TLS Between Choreo Connect and Backend

en/docs/get-started/about-this-release.md
- Updated links and info based on discrepancies in release mail.
- fixes https://github.com/wso2/docs-apim/issues/4929
=> Updated About this release pg

en/docs/design/rate-limiting/advanced-topics/configuring-rate-limiting-api-gateway-cluster.md, en/docs/includes/design/redis-counter-note.md, en/docs/reference/connectors/redis-connector/redis-connector-configuration.md
- PR review and update for https://github.com/wso2/docs-apim/pull/4965 part 2
- Updated the intro and the steps further in [1].
- Updated the note. [2]
- Fixed formatting issue in [3].
https://apim.docs.wso2.com/en/4.1.0/reference/connectors/redis-connector/redis-connector-configuration/#setting-up-the-redis-environment
[1] https://apim.docs.wso2.com/en/4.1.0/design/rate-limiting/advanced-topics/configuring-rate-limiting-api-gateway-cluster/
[2]
[3]
https://github.com/wso2/docs-apim/pull/4970 - part 1
=> PR review and update for https://github.com/wso2/docs-apim/pull/4965 part 2

en/docs/learn/design-api/create-api-product/api-product-overview.md
- fixes https://github.com/wso2/docs-apim/issues/4974
- fixed note
=> fixed note

en/docs/design/create-api-product/api-product-overview.md
- fixes https://github.com/wso2/docs-apim/issues/4974
- fixed note
=> fixes https://github.com/wso2/docs-apim/issues/4974

en/docs/deploy-and-publish/deploy-on-gateway/choreo-connect/deploy-api/deploy-api-with-virtual-hosts.md, en/docs/install-and-setup/setup/api-controller/advanced-topics/using-dynamic-data-in-api-controller-projects.md, en/docs/install-and-setup/setup/api-controller/managing-apis-api-products/importing-apis-via-dev-first-approach.md, en/docs/install-and-setup/setup/api-controller/managing-apis-api-products/migrating-api-products-to-different-environments.md, en/docs/install-and-setup/setup/api-controller/managing-apis-api-products/migrating-apis-to-different-environments.md
Fixes: https://github.com/wso2/product-apim-tooling/issues/810
Modifying the apictl artifacts version
- https://github.com/wso2/carbon-apimgt/pull/10876
=> Changing the apictl artifacts version to v4.1.0

en/docs/deploy-and-publish/deploy-on-gateway/api-gateway/message-mediation/creating-and-uploading-using-integration-studio.md
- Adding changes that were introduced in [1] via the PR review in master (4.1.0) as well.
[1] https://github.com/wso2/docs-apim/pull/4933
=> PR review improvements

en/docs/design/api-monetization/monetizing-an-api.md
- fixing endpoint URL
- Fixes https://github.com/wso2/docs-apim/issues/4989
=> fixing endpoint URL

en/docs/design/api-monetization/monetizing-an-api.md
- fix for https://github.com/wso2/docs-apim/issues/4989
- updated config_endpoint
=> updated config_endpoint

en/docs/design/api-monetization/monetizing-an-api.md
- fixes https://github.com/wso2/docs-apim/issues/4989
- fixed the endpoint URLs
=> fixed the endpoint URLs

en/docs/deploy-and-publish/deploy-on-gateway/choreo-connect/getting-started/quick-start-guide/quick-start-guide-docker.md
Fixes https://github.com/wso2/product-microgateway/issues/2397
=> Fix typo MG_HOME

en/docs/reference/config-catalog.md, en/tools/config-catalog-generator/data/admin_console.control_access.toml, en/tools/config-catalog-generator/data/configs.json, en/tools/config-catalog-generator/data/servlet_access_control_filter.toml, en/tools/config-catalog-generator/data/web_app.control_access.toml, en/tools/config-catalog-generator/dist/config-catalog.md
Fixes https://github.com/wso2/docs-apim/issues/4967
=> Add tomcat configs in the config catalog

en/docs/deploy-and-publish/deploy-on-gateway/choreo-connect/concepts/apim-as-control-plane.md, en/docs/deploy-and-publish/deploy-on-gateway/choreo-connect/configure-multiple-gateways-with-choreo-connect.md, en/docs/deploy-and-publish/deploy-on-gateway/choreo-connect/getting-started/choreo-connect-overview.md, en/docs/deploy-and-publish/deploy-on-gateway/choreo-connect/getting-started/quick-start-guide/quick-start-guide-docker.md, en/docs/deploy-and-publish/deploy-on-gateway/choreo-connect/getting-started/supported-features.md
> Adds corrections to the Choreo Connect documentation.
=> Corrections for Choreo Connect documentation

en/docs/reference/synapse-properties/endpoint-properties.md
=> Adding basic auth support in http endpoint docs

en/docs/administer/logging-and-monitoring/monitoring/working-with-observability.md
=> [DOC][APIM-3.2.0] Light Weight Observerbility Feature

en/docs/deploy-and-publish/deploy-on-gateway/choreo-connect/troubleshooting/enforcer-admin-api/enforcer-v1.0.0.md, en/docs/deploy-and-publish/deploy-on-gateway/choreo-connect/troubleshooting/enforcer-admin-api/enforcer-v1.0.0.yaml, en/mkdocs.yml
Adding enforcer REST API. This REST API is used for troubleshooting purposes. Hence adding it under the troubleshooting guide.
Fixes https://github.com/wso2/product-microgateway/issues/2266
=> [CC 1.0.0] Adding enforcer rest api for troubleshooting purposes - [Master]

en/docs/deploy-and-publish/deploy-on-gateway/choreo-connect/troubleshooting/enforcer-admin-api/enforcer-v1.0.0.md, en/docs/deploy-and-publish/deploy-on-gateway/choreo-connect/troubleshooting/enforcer-admin-api/enforcer-v1.0.0.yaml, en/mkdocs.yml
Adding enforcer REST API. This REST API is used for troubleshooting purposes. Hence adding it under the troubleshooting guide.
Fixes https://github.com/wso2/product-microgateway/issues/2266
=> [CC 1.0.0] Adding enforcer rest api for troubleshooting purposes - [4.0.0]

en/docs/get-started/api-manager-quick-start-guide.md, en/docs/install-and-setup/setup/api-controller/building-jenkins-ci-cd-pipeline-for-dev-first-approach.md, en/docs/install-and-setup/setup/api-controller/cicd-using-cli.md, en/docs/install-and-setup/setup/api-controller/getting-started-with-wso2-api-controller.md, en/docs/install-and-setup/setup/api-controller/managing-apis-api-products/managing-apis-and-api-products.md, en/docs/install-and-setup/setup/api-controller/managing-applications/managing-applications.md
Add changes related to APICTL 4.0.1 release
=> Add changes related to APICTL 4.0.1 release

en/docs/deploy-and-publish/deploy-on-gateway/choreo-connect/configurations/configuration-overview.md
Add Documentation for overriding configurations via env variables. 
Related Feature PR:
https://github.com/wso2/product-microgateway/pull/2294
> Link(s) to product documentation that addresses the changes of this PR. If no doc impact, enter “N/A” plus brief explanation of why there’s …
=> [CC 1.0.0] Choreo Connect Configuration override using env variables [Master]

en/docs/deploy-and-publish/deploy-on-gateway/choreo-connect/configurations/configuration-overview.md
Add Documentation for overriding configurations via env variables. …
=> [CC 1.0.0] Choreo Connect Configuration override using env variables [4.0.0]

en/docs/deploy-and-publish/deploy-on-gateway/choreo-connect/configurations/adapter-configurations.md, en/docs/deploy-and-publish/deploy-on-gateway/choreo-connect/configurations/enforcer-configurations.md, en/docs/deploy-and-publish/deploy-on-gateway/choreo-connect/configurations/router-configurations.md, en/mkdocs.yml, en/tools/config-catalog-generator-cc/data/adapter/configs.json, en/tools/config-catalog-generator-cc/data/adapter/consul.toml, en/tools/config-catalog-generator-cc/data/enforcer/configs.json, en/tools/config-catalog-generator-cc/data/enforcer/filters.toml, en/tools/config-catalog-generator-cc/data/enforcer/management.toml, en/tools/config-catalog-generator-cc/data/router/configs.json, en/tools/config-catalog-generator-cc/data/router/upstream_health.toml, en/tools/config-catalog-generator-cc/dist/adapter-configurations.md, en/tools/config-catalog-generator-cc/dist/enforcer-configurations.md, en/tools/config-catalog-generator-cc/dist/router-configurations.md, en/tools/config-catalog-generator-cc/package-lock.json
Updating CHoreo Connect configurations related to Adatper, router and enforcer.
=> [CC 1.0.0] Updating configurations in Choreo Connect - adapter, router, enforcer [Master]

en/docs/deploy-and-publish/deploy-on-gateway/choreo-connect/configurations/adapter-configurations.md, en/docs/deploy-and-publish/deploy-on-gateway/choreo-connect/configurations/enforcer-configurations.md, en/docs/deploy-and-publish/deploy-on-gateway/choreo-connect/configurations/router-configurations.md, en/tools/config-catalog-generator-cc/data/adapter/configs.json, en/tools/config-catalog-generator-cc/data/adapter/consul.toml, en/tools/config-catalog-generator-cc/data/enforcer/configs.json, en/tools/config-catalog-generator-cc/data/enforcer/filters.toml, en/tools/config-catalog-generator-cc/data/enforcer/management.toml, en/tools/config-catalog-generator-cc/data/router/configs.json, en/tools/config-catalog-generator-cc/data/router/upstream_health.toml, en/tools/config-catalog-generator-cc/dist/adapter-configurations.md, en/tools/config-catalog-generator-cc/dist/enforcer-configurations.md, en/tools/config-catalog-generator-cc/dist/router-configurations.md, en/tools/config-catalog-generator-cc/package-lock.json
Updating CHoreo Connect configurations related to Adatper, router and enforcer.
=> [CC 1.0.0] Updating configurations in Choreo Connect - adapter, router, enforcer [4.0.0]

en/docs/deploy-and-publish/deploy-on-gateway/choreo-connect/getting-started/supported-features.md
- Changed Jager to Jaeger
- fixes https://github.com/wso2/docs-apim/issues/5049
=> Corrected typo

en/docs/deploy-and-publish/deploy-on-gateway/choreo-connect/concepts/apim-as-control-plane.md, en/docs/deploy-and-publish/deploy-on-gateway/choreo-connect/concepts/as-a-standalone-gateway.md, en/docs/deploy-and-publish/deploy-on-gateway/choreo-connect/concepts/choreo-connect-with-tenants.md, en/docs/deploy-and-publish/deploy-on-gateway/choreo-connect/concepts/event-hub.md, en/docs/deploy-and-publish/deploy-on-gateway/choreo-connect/concepts/subscription-validation.md, en/docs/deploy-and-publish/deploy-on-gateway/choreo-connect/getting-started/quick-start-guide/quick-start-guide-docker.md, en/docs/deploy-and-publish/deploy-on-gateway/choreo-connect/getting-started/quick-start-guide/quick-start-guide-kubernetes-with-apim.md, en/docs/deploy-and-publish/deploy-on-gateway/choreo-connect/getting-started/quick-start-guide/quick-start-guide-kubernetes.md, en/docs/deploy-and-publish/deploy-on-gateway/choreo-connect/getting-started/quick-start-guide/quick-start-guide-overview.md
1. Updating configurations
2. Updating concepts docs
3. Updating QSG docs
=> [CC 1.0.0] Updating CC docs covering QSG and concept docs [Master]

en/docs/deploy-and-publish/deploy-on-gateway/choreo-connect/concepts/apim-as-control-plane.md, en/docs/deploy-and-publish/deploy-on-gateway/choreo-connect/concepts/as-a-standalone-gateway.md, en/docs/deploy-and-publish/deploy-on-gateway/choreo-connect/concepts/choreo-connect-with-tenants.md, en/docs/deploy-and-publish/deploy-on-gateway/choreo-connect/concepts/event-hub.md, en/docs/deploy-and-publish/deploy-on-gateway/choreo-connect/concepts/subscription-validation.md, en/docs/deploy-and-publish/deploy-on-gateway/choreo-connect/getting-started/quick-start-guide/quick-start-guide-docker.md, en/docs/deploy-and-publish/deploy-on-gateway/choreo-connect/getting-started/quick-start-guide/quick-start-guide-kubernetes-with-apim.md, en/docs/deploy-and-publish/deploy-on-gateway/choreo-connect/getting-started/quick-start-guide/quick-start-guide-kubernetes.md, en/docs/deploy-and-publish/deploy-on-gateway/choreo-connect/getting-started/quick-start-guide/quick-start-guide-overview.md
1. Updating configurations
2. Updating concepts docs
3. Updating QSG docs
=> [CC 1.0.0] Updating CC docs covering QSG and concept docs [4.0.0]

en/docs/deploy-and-publish/deploy-on-gateway/choreo-connect/deploy-api/deploy-apis-as-immutable-gateway.md, en/mkdocs.yml
This PR add the documentation for reading the API Artifacts (Either exported or initialized using apictl) from Adapter File system and start the gateway with those mounted API artifacts.
Related Feature PR
https://github.com/wso2/product-microgateway/pull/2325 …
=> [CC 1.0.0] Read APIs from File System [master]

en/docs/deploy-and-publish/deploy-on-gateway/choreo-connect/configurations/configuration-overview.md, en/docs/deploy-and-publish/deploy-on-gateway/choreo-connect/configurations/configure-log4j2.md, en/docs/deploy-and-publish/deploy-on-gateway/choreo-connect/deploy-api/deploy-api-via-apictl.md, en/docs/deploy-and-publish/deploy-on-gateway/choreo-connect/deploy-api/deploy-api-via-apim.md, en/docs/deploy-and-publish/deploy-on-gateway/choreo-connect/deploy-api/deploy-api-with-virtual-hosts.md, en/docs/deploy-and-publish/deploy-on-gateway/choreo-connect/deploy-api/deploy-web-socket-api.md, en/docs/deploy-and-publish/deploy-on-gateway/choreo-connect/deploy-api/overview.md, en/docs/deploy-and-publish/deploy-on-gateway/choreo-connect/endpoints/advanced-endpoint-config/retry-policies.md, en/docs/deploy-and-publish/deploy-on-gateway/choreo-connect/endpoints/advanced-endpoint-config/timeout.md, en/docs/deploy-and-publish/deploy-on-gateway/choreo-connect/endpoints/defining-a-backend-security-scheme.md, en/docs/deploy-and-publish/deploy-on-gateway/choreo-connect/endpoints/failover-endpoints.md, en/docs/deploy-and-publish/deploy-on-gateway/choreo-connect/endpoints/load-balanced-endpoints.md, en/docs/deploy-and-publish/deploy-on-gateway/choreo-connect/endpoints/overriding-endpoints-for-imported-apis.md, en/docs/deploy-and-publish/deploy-on-gateway/choreo-connect/rate-limiting/distributed-throttling.md, en/docs/includes/deploy/cc-configuration-file.md, en/mkdocs.yml
- Improved CC docs - part 2
- https://github.com/wso2/docs-apim/issues/5014
=> Improved CC docs v2

en/docs/deploy-and-publish/deploy-on-gateway/choreo-connect/endpoints/resiliency/circuit-breakers.md, en/docs/deploy-and-publish/deploy-on-gateway/choreo-connect/endpoints/resiliency/retry-policies.md, en/docs/deploy-and-publish/deploy-on-gateway/choreo-connect/endpoints/resiliency/timeout.md, en/docs/deploy-and-publish/deploy-on-gateway/choreo-connect/troubleshooting/adding-debug-logs.md, en/docs/deploy-and-publish/deploy-on-gateway/choreo-connect/troubleshooting/error-handling.md, en/docs/publish/api-microgateway/internal-communication-protocol.md, en/mkdocs.yml
=> Add circuit breakers

en/docs/develop/extending-api-manager/extending-gateway/writing-custom-handlers.md
fixes https://github.com/wso2/docs-apim/issues/5024
=> fixes https://github.com/wso2/docs-apim/issues/5024

en/docs/deploy-and-publish/deploy-on-gateway/choreo-connect/troubleshooting/debug-memory.md, en/mkdocs.yml
Add Choreo Connect troubleshooting docs on heap dumps
=> [CC] Add memory troubleshhot doc

en/docs/deploy-and-publish/deploy-on-gateway/choreo-connect/configurations/configuration-overview.md
Refactor the structure of existing document for overriding configurations with environment variables.
> Link to the PR for …
=> [CC 1.0.0] Refactor the documentation for custom configurations [master]

en/docs/deploy-and-publish/deploy-on-gateway/choreo-connect/configurations/adapter-configurations.md, en/docs/deploy-and-publish/deploy-on-gateway/choreo-connect/configurations/analytics-configurations.md, en/docs/deploy-and-publish/deploy-on-gateway/choreo-connect/configurations/control-plane-configurations.md, en/docs/deploy-and-publish/deploy-on-gateway/choreo-connect/configurations/enforcer-configurations.md, en/tools/config-catalog-generator-cc/data/adapter/configs.json, en/tools/config-catalog-generator-cc/data/analytics/configs.json, en/tools/config-catalog-generator-cc/data/control-plane/configs.json, en/tools/config-catalog-generator-cc/data/control-plane/cp.toml, en/tools/config-catalog-generator-cc/data/control-plane/cp_http_client.toml, en/tools/config-catalog-generator-cc/data/enforcer/configs.json, en/tools/config-catalog-generator-cc/data/enforcer/jwt_generator.toml, en/tools/config-catalog-generator-cc/data/enforcer/metrics.toml, en/tools/config-catalog-generator-cc/data/enforcer/rest_server.toml, en/tools/config-catalog-generator-cc/data/enforcer/throttling.toml, en/tools/config-catalog-generator-cc/data/enforcer/throttling_urlgroup.toml, en/tools/config-catalog-generator-cc/dist/adapter-configurations.md, en/tools/config-catalog-generator-cc/dist/analytics-configurations.md, en/tools/config-catalog-generator-cc/dist/control-plane-configurations.md, en/tools/config-catalog-generator-cc/dist/enforcer-configurations.md
Adding missing configs of CC
Corrected the missing configs.
=> [CC 1.0.0]Adding configurations for CC [Master]

en/docs/install-and-setup/setup/mi-setup/user_stores/setting_up_a_userstore.md, en/docs/reference/config-catalog-mi.md, en/tools/config-catalog-generator-mi/data/_management-api-default-user-store.toml, en/tools/config-catalog-generator-mi/data/configs.json
Fixes https://github.com/wso2/docs-apim/issues/4960
=> Update File based User Store properties for Micro Integrator

en/docs/learn/consume-api/manage-application/advanced-topics/adding-an-application-creation-workflow.md
Close tag of ApplicationCreation in snippet …
=> Close tag of ApplicationCreation in snippet

en/docs/deploy-and-publish/deploy-on-gateway/choreo-connect/configurations/adapter-configurations.md, en/docs/deploy-and-publish/deploy-on-gateway/choreo-connect/configurations/analytics-configurations.md, en/docs/deploy-and-publish/deploy-on-gateway/choreo-connect/configurations/control-plane-configurations.md, en/docs/deploy-and-publish/deploy-on-gateway/choreo-connect/configurations/enforcer-configurations.md, en/tools/config-catalog-generator-cc/data/adapter/configs.json, en/tools/config-catalog-generator-cc/data/analytics/configs.json, en/tools/config-catalog-generator-cc/data/control-plane/configs.json, en/tools/config-catalog-generator-cc/data/control-plane/cp.toml, en/tools/config-catalog-generator-cc/data/control-plane/cp_http_client.toml, en/tools/config-catalog-generator-cc/data/enforcer/configs.json, en/tools/config-catalog-generator-cc/data/enforcer/jwt_generator.toml, en/tools/config-catalog-generator-cc/data/enforcer/metrics.toml, en/tools/config-catalog-generator-cc/data/enforcer/rest_server.toml, en/tools/config-catalog-generator-cc/data/enforcer/throttling.toml, en/tools/config-catalog-generator-cc/data/enforcer/throttling_urlgroup.toml, en/tools/config-catalog-generator-cc/dist/adapter-configurations.md, en/tools/config-catalog-generator-cc/dist/analytics-configurations.md, en/tools/config-catalog-generator-cc/dist/control-plane-configurations.md, en/tools/config-catalog-generator-cc/dist/enforcer-configurations.md
Adding missing configs of CC
Corrected the missing configs.
Master branch PR is already merged - https://github.com/wso2/docs-apim/pull/5069
=> [CC 1.0.0]Adding configurations for CC [4.0.0]

en/docs/get-started/about-this-release.md
Update release page with following M2 features,
- File based user store improvements in MI
- Viewing Data Sources in MI Dashboard
- File based user store improvements in MI
- Viewing Data Sources in MI Dashboard
=> [DO NOT MERGE] Update About this release page

en/docs/develop/product-apis/advanced-configurations.md, en/mkdocs.yml
- fixes https://github.com/wso2/docs-apim/issues/5080
=> fixes https://github.com/wso2/docs-apim/issues/5080

en/docs/install-and-setup/setup/api-controller/getting-started-with-wso2-api-controller.md
Updating the apictl distributions to apictl 4.1.0-m2
=> Updating the apictl distributions to apictl 4.1.0-m2

en/docs/administer/product-administration/monitoring/logging/monitoring-http-access-logs.md
- Fixes Wrong explanation for %T
- Related to A-1389
=> Fixes Wrong explanation for %T

en/docs/tutorials/streaming-api/create-and-publish-websocket-api.md
- fixes https://github.com/wso2/docs-apim/issues/5101
=> fixes https://github.com/wso2/docs-apim/issues/5101

en/docs/deploy-and-publish/deploy-on-gateway/choreo-connect/configurations/configuration-overview.md
Refactor the structure of existing document for overriding configurations with environment variables.
> Link to the PR for …
=> [CC 1.0.0] Refactor the documentation for custom configurations [4.0]

en/docs/deploy-and-publish/deploy-on-gateway/choreo-connect/getting-started/deploy/cc-on-kubernetes-with-api-controller.md, en/docs/deploy-and-publish/deploy-on-gateway/choreo-connect/getting-started/deploy/cc-on-kubernetes-with-apim.md, en/docs/deploy-and-publish/deploy-on-gateway/choreo-connect/getting-started/deploy/installation-prerequisites.md, en/mkdocs.yml
Adding installation prerequisites for CC
=> [CC 1.0.0]Adding installation prerequisites for CC[Master]

en/docs/deploy-and-publish/deploy-on-gateway/choreo-connect/getting-started/deploy/cc-on-kubernetes-with-api-controller.md, en/docs/deploy-and-publish/deploy-on-gateway/choreo-connect/getting-started/deploy/cc-on-kubernetes-with-apim.md, en/docs/deploy-and-publish/deploy-on-gateway/choreo-connect/getting-started/deploy/installation-prerequisites.md, en/mkdocs.yml
Adding installation prerequisites for CC
=> [CC 1.0.0]Adding installation prerequisites for CC[4.0.0]

en/docs/api-analytics/samples/publishing-analytics-events-to-external-systems.md, en/docs/deploy-and-publish/deploy-on-gateway/choreo-connect/configure-analytics.md
This PR adds the changes required for configuring Choreo COnnect with ELK.
=> [CC 1.0.0] Adding docs on configuring CC with ELK [Master]

en/docs/deploy-and-publish/deploy-on-gateway/choreo-connect/security/api-authentication/disabling-security.md
> There were some minor formatting issues in the above file .
Also document was updated to match with latest `x-wso2-disable-security` extension updates.
> `x-wso2-disable-security` extension can use in 
- API level
- Resource level 
- Operation level.
By adding this extension it will enable users to invoke API without any security restrictions.
> 
> Added above
> https://github.com/wso2/product-microgateway/pull/2502
> 
Python 3.9.8
=> [CC 1.0.0] Changed examples in disabling-security.md file

en/docs/deploy-and-publish/deploy-on-gateway/choreo-connect/security/api-authentication/disabling-security.md
> There were some minor formatting issues in the above file .
Also document was updated to match with latest `x-wso2-disable-security` extension updates.
> `x-wso2-disable-security` extension can use in 
- API level
- Resource level 
- Operation level.
By adding this extension it will enable users to invoke API without any security restrictions.
> 
> Added above
> https://github.com/wso2/product-microgateway/pull/2502
> 
Python 3.9.8
=> 4.0.0 [CC 1.0.0] Changed examples in disabling-security.md file

en/docs/integrate/develop/integration-development-kickstart.md
- PR sync for https://github.com/wso2/docs-apim/pull/5102
=> PR sync for https://github.com/wso2/docs-apim/pull/5102

en/docs/deploy-and-publish/deploy-on-gateway/choreo-connect/concepts/choreo-connect-with-tenants.md, en/docs/deploy-and-publish/deploy-on-gateway/choreo-connect/concepts/event-hub.md, en/docs/deploy-and-publish/deploy-on-gateway/choreo-connect/configure-multiple-gateways-with-choreo-connect.md, en/docs/deploy-and-publish/deploy-on-gateway/choreo-connect/getting-started/deploy/cc-on-docker-with-apim.md, en/docs/deploy-and-publish/deploy-on-gateway/choreo-connect/passing-enduser-attributes-to-the-backend-via-choreo-connect.md, en/docs/deploy-and-publish/deploy-on-gateway/choreo-connect/service-discovery/choreo-connect-and-k8s.md, en/docs/deploy-and-publish/deploy-on-gateway/choreo-connect/service-discovery/choreo-connect-and-service-discovery.md, en/docs/deploy-and-publish/deploy-on-gateway/choreo-connect/service-discovery/choreo-connect-and-service-mesh.md, en/docs/deploy-and-publish/deploy-on-gateway/choreo-connect/service-discovery/service-discovery-overview.md
Apply the configuration update related changes to the docs. 
Related PR : https://github.com/wso2/product-microgateway/pull/2354 …
=> [CC-1.0.0] Docs update due to configurations update [master]

en/docs/deploy-and-publish/deploy-on-gateway/choreo-connect/concepts/choreo-connect-with-tenants.md, en/docs/deploy-and-publish/deploy-on-gateway/choreo-connect/concepts/event-hub.md, en/docs/deploy-and-publish/deploy-on-gateway/choreo-connect/configure-multiple-gateways-with-choreo-connect.md, en/docs/deploy-and-publish/deploy-on-gateway/choreo-connect/getting-started/deploy/cc-on-docker-with-apim.md, en/docs/deploy-and-publish/deploy-on-gateway/choreo-connect/passing-enduser-attributes-to-the-backend-via-choreo-connect.md, en/docs/deploy-and-publish/deploy-on-gateway/choreo-connect/service-discovery/choreo-connect-and-k8s.md, en/docs/deploy-and-publish/deploy-on-gateway/choreo-connect/service-discovery/choreo-connect-and-service-discovery.md, en/docs/deploy-and-publish/deploy-on-gateway/choreo-connect/service-discovery/choreo-connect-and-service-mesh.md, en/docs/deploy-and-publish/deploy-on-gateway/choreo-connect/service-discovery/service-discovery-overview.md
Related PR https://github.com/wso2/docs-apim/pull/5122 …
=> [CC-1.0.0] Docs update due to configurations update [4.0.0]

en/docs/deploy-and-publish/deploy-on-gateway/choreo-connect/getting-started/deploy/cc-on-docker-with-api-controller.md, en/docs/deploy-and-publish/deploy-on-gateway/choreo-connect/getting-started/deploy/cc-on-docker-with-apim.md, en/docs/deploy-and-publish/deploy-on-gateway/choreo-connect/getting-started/deploy/cc-on-kubernetes-with-api-controller.md, en/docs/deploy-and-publish/deploy-on-gateway/choreo-connect/getting-started/deploy/cc-on-kubernetes-with-apim.md, en/docs/deploy-and-publish/deploy-on-gateway/choreo-connect/getting-started/quick-start-guide-docker-with-apim.md, en/docs/includes/deploy/cc-tryout-in-arm64-note.md
$subject
Add a note for QSG and deployment sections. …
=> [master] Choreo Connect ARM64 Ubuntu images for Tryout

en/docs/deploy-and-publish/deploy-on-gateway/choreo-connect/getting-started/deploy/cc-on-docker-with-api-controller.md, en/docs/deploy-and-publish/deploy-on-gateway/choreo-connect/getting-started/deploy/cc-on-docker-with-apim.md, en/docs/deploy-and-publish/deploy-on-gateway/choreo-connect/getting-started/deploy/cc-on-kubernetes-with-api-controller.md, en/docs/deploy-and-publish/deploy-on-gateway/choreo-connect/getting-started/deploy/cc-on-kubernetes-with-apim.md, en/docs/deploy-and-publish/deploy-on-gateway/choreo-connect/getting-started/quick-start-guide-docker-with-apim.md, en/docs/includes/deploy/cc-tryout-in-arm64-note.md
Port https://github.com/wso2/docs-apim/pull/5127 …
=> [4.0.0] Choreo Connect ARM64 Ubuntu images for Tryout

en/docs/deploy-and-publish/deploy-on-gateway/choreo-connect/getting-started/deploy/cc-on-docker-with-api-controller.md, en/docs/deploy-and-publish/deploy-on-gateway/choreo-connect/getting-started/deploy/cc-on-docker-with-apim.md, en/docs/deploy-and-publish/deploy-on-gateway/choreo-connect/getting-started/deploy/cc-on-kubernetes-with-api-controller.md, en/docs/deploy-and-publish/deploy-on-gateway/choreo-connect/getting-started/deploy/cc-on-kubernetes-with-apim.md, en/docs/deploy-and-publish/deploy-on-gateway/choreo-connect/getting-started/quick-start-guide-docker-with-apim.md, en/docs/includes/deploy/cc-tryout-in-arm64-docker-note.md, en/docs/includes/deploy/cc-tryout-in-arm64-k8s-note.md
=> [4.0.0] Fix formatting issue in ARM64 images note for Choreo Connect QSG

en/docs/deploy-and-publish/deploy-on-gateway/choreo-connect/getting-started/deploy/cc-on-docker-with-api-controller.md, en/docs/deploy-and-publish/deploy-on-gateway/choreo-connect/getting-started/deploy/cc-on-docker-with-apim.md, en/docs/deploy-and-publish/deploy-on-gateway/choreo-connect/getting-started/deploy/cc-on-kubernetes-with-api-controller.md, en/docs/deploy-and-publish/deploy-on-gateway/choreo-connect/getting-started/deploy/cc-on-kubernetes-with-apim.md, en/docs/deploy-and-publish/deploy-on-gateway/choreo-connect/getting-started/quick-start-guide-docker-with-apim.md, en/docs/includes/deploy/cc-tryout-in-arm64-docker-note.md, en/docs/includes/deploy/cc-tryout-in-arm64-k8s-note.md
Port https://github.com/wso2/docs-apim/pull/5129 …
=> Fix formatting issue in ARM64 images note for Choreo Connect QSG

en/docs/install-and-setup/setup/distributed-deployment/deploying-wso2-api-m-in-a-distributed-setup-with-km-separated.md, en/mkdocs.yml
Changes location of KM docs based on comments in https://github.com/wso2/docs-apim/pull/5011
=> Change location of KM separation doc

en/docs/integrate/examples/working-with-transactions.md
=> Add client ack note

en/docs/install-and-setup/install/installation-prerequisites.md
- fixes https://github.com/wso2/docs-apim/issues/5133
=> fixes https://github.com/wso2/docs-apim/issues/5133

en/docs/learn/api-controller/getting-started-with-wso2-api-controller.md
Update docs with apictl 3.0.2 artifacts …
=> [3.0.0] Update docs with apictl 3.0.2 artifacts

en/docs/install-and-setup/upgrading-wso2-api-manager/upgrading-from-260-to-400.md
=> Add Authorization manager properties to migration docs.

en/docs/integrate/examples/transport_examples/tcp-transport-examples.md
=> Add parameter and channel details for TCP protocol

en/docs/integrate/examples/transport_examples/tcp-transport-examples.md
=> Add TCP fixes Sync PR

en/docs/install-and-setup/setup/reference/product-compatibility.md
Related to A-836
_Mail : Is APIM 4.0 compatible with Windows Server 2019?_
=> APIM 4.0 compatibility with Windows Server 2019

en/docs/deploy-and-publish/deploy-on-gateway/choreo-connect/deploy-api/deploy-apis-as-immutable-gateway.md, en/mkdocs.yml
This PR add the documentation for reading the API Artifacts (Either exported or initialized using apictl) from Adapter File system and start the gateway with those mounted API artifacts.
Related master branch PR.
https://github.com/wso2/docs-apim/pull/4968 …
=> [CC 1.0.0] Read APIs from File System [4.0.0]

en/docs/deploy-and-publish/deploy-on-gateway/choreo-connect/troubleshooting/debug-memory.md, en/mkdocs.yml
Add Choreo Connect troubleshooting docs on heap dumps
copy of #5063 to 4.0.0
=> [4.0.0] Add memory troubleshoot doc

en/mkdocs.yml
=> [CC 1.0.0]Fixing navigation [Master]

en/mkdocs.yml
=> [CC 1.0.0]Fixing navigation [4.0.0]

en/docs/get-started/about-this-release.md, en/mkdocs.yml
Fixes https://github.com/wso2/product-apim/issues/11937 and https://github.com/wso2/docs-apim/issues/4959
=> Removed feature DAS message tracer

en/docs/deploy-and-publish/deploy-on-gateway/choreo-connect/message-transformation/interceptor-microservice/request-flow-interceptor.md, en/docs/deploy-and-publish/deploy-on-gateway/choreo-connect/message-transformation/interceptor-microservice/response-flow-interceptor.md, en/mkdocs.yml
Add description on interceptor JSON body instructions …
=> [4.0.0] Add description on interceptor JSON body instructions

en/docs/install-and-setup/setup/api-controller/managing-apis-api-products/managing-apis-and-api-products.md, en/docs/install-and-setup/setup/api-controller/managing-apis-api-products/migrating-api-products-to-different-environments.md
Fixes the task tracked in https://github.com/wso2/product-apim-tooling/issues/843
=> Add APICTL documentation related to lifecycle support to API Products

en/docs/deploy-and-publish/deploy-on-gateway/choreo-connect/deploy-api/deploy-websocket-api-in-choreo-connect.md
Include websocket api limitations for choreo-connect. …
=> [CC 1.0.0] Update websocket docs to include limitations [master]

en/docs/deploy-and-publish/deploy-on-gateway/choreo-connect/message-transformation/interceptor-microservice/request-flow-interceptor.md, en/docs/deploy-and-publish/deploy-on-gateway/choreo-connect/message-transformation/interceptor-microservice/response-flow-interceptor.md, en/mkdocs.yml
Add description on interceptor JSON body instructions
port https://github.com/wso2/docs-apim/pull/5163
> Link to the PR for …
=> [master] Add description on interceptor JSON body instructions

en/docs/deploy-and-publish/deploy-on-gateway/choreo-connect/getting-started/deploy/installation-prerequisites.md, en/docs/deploy-and-publish/deploy-on-gateway/choreo-connect/getting-started/quick-start-guide-docker-with-apim.md, en/docs/includes/deploy/cc-tryout-in-arm64-docker-note.md, en/docs/includes/deploy/cc-tryout-in-arm64-k8s-note.md
=> [4.0.0] Add resource usage for docker in QSG

en/docs/deploy-and-publish/deploy-on-gateway/choreo-connect/getting-started/deploy/installation-prerequisites.md, en/docs/deploy-and-publish/deploy-on-gateway/choreo-connect/getting-started/quick-start-guide-docker-with-apim.md
$subject - done in master - https://github.com/wso2/docs-apim/pull/5172/commits/8745865f8e32fc6c3d38471ec21215daf3159e2b
=> [4.0.0] Fix format issue

en/docs/deploy-and-publish/deploy-on-gateway/choreo-connect/getting-started/deploy/installation-prerequisites.md, en/docs/deploy-and-publish/deploy-on-gateway/choreo-connect/getting-started/quick-start-guide-docker-with-apim.md, en/docs/includes/deploy/cc-tryout-in-arm64-docker-note.md, en/docs/includes/deploy/cc-tryout-in-arm64-k8s-note.md
$subject
porting https://github.com/wso2/docs-apim/pull/5171
=> [master] Add resource usage for docker in QSG

en/docs/deploy-and-publish/deploy-on-gateway/choreo-connect/deploy-api/deploy-api-via-apictl.md, en/docs/deploy-and-publish/deploy-on-gateway/choreo-connect/getting-started/deploy/cc-as-a-standalone-gateway-on-docker.md, en/docs/deploy-and-publish/deploy-on-gateway/choreo-connect/getting-started/deploy/cc-as-a-standalone-gateway-on-kubernetes.md, en/docs/deploy-and-publish/deploy-on-gateway/choreo-connect/getting-started/deploy/cc-on-docker-with-apim-as-control-plane.md, en/docs/deploy-and-publish/deploy-on-gateway/choreo-connect/getting-started/deploy/cc-on-kubernetes-with-apim-as-control-plane.md, en/docs/deploy-and-publish/deploy-on-gateway/choreo-connect/getting-started/quick-start-guide-docker-with-apim.md, en/docs/deploy-and-publish/deploy-on-gateway/choreo-connect/message-transformation/interceptor-microservice/interceptor-microservice.md, en/docs/deploy-and-publish/deploy-on-gateway/choreo-connect/message-transformation/message-transformation-overview.md
Use web page to download the CC distribution instead of GitHub repo
=> Use web page to download the CC distribution instead of GitHub repo

en/docs/integrate/develop/generate-service-catalog-metadata.md, en/docs/tutorials/integration-tutorials/service-catalog-tutorial-for-proxy-services.md, en/docs/tutorials/integration-tutorials/service-catalog-tutorial.md
Related to https://github.com/wso2/micro-integrator/issues/2551
=> Add tip boxes related to selectively adding CApps to service catalog

en/docs/administer/key-managers/configure-wso2is-connector.md
> Update WSO2 IS connector links to latest WUM and U2 jars
=> Update WSO2 IS connector links

en/docs/install-and-setup/setup/distributed-deployment/configuring-wso2-identity-server-as-a-key-manager.md
> Update WSO2IS connector links
=> Update WSO2IS connector links

en/docs/get-started/about-this-release.md
Updates About this Release page for WSO2 API-M 4.1.0 Milestone 3.
=> About this Release updates for M3

en/docs/deploy-and-publish/deploy-on-gateway/choreo-connect/deploy-api/deploy-websocket-api-in-choreo-connect.md
Include websocket api limitations for choreo-connect. …
=> [CC 1.0.0] Update websocket docs to include limitations [4.0.0]

en/docs/learn/api-controller/getting-started-with-wso2-api-controller.md
Add latest artifacts in the Getting Started with WSO2 API Controller [1] of the APIM 3.2.0 Docs space to support 3.2.5 API Controller patch release.
[1]. https://apim.docs.wso2.com/en/3.2.0/learn/api-controller/getting-started-with-wso2-api-controller/
=> [3.2.0] Add latest API Controller artifacts for 3.2.5 patch release.

en/docs/integrate/examples/data_integration/json-with-data-service.md
$subject
Fixes wso2/micro-integrator#1522
=> Add note on DSS Json template guidelines

en/mkdocs.yml
=> [CC][master] Add transport security redirects

en/mkdocs.yml
- fixes https://github.com/wso2/docs-apim/issues/5205
=> fixes https://github.com/wso2/docs-apim/issues/5205

en/mkdocs.yml
- fixing lifecycle and version menu
=> fixing lifecycle and version menu

en/docs/reference/product-apis/publisher-apis/publisher-v2/publisher-v2.yaml
A - 1502
_Since the parameter is embedded in the YAML file, I only added the note instead of removing it_
=> Add note for the deprecated expand parameter

en/docs/learn/api-controller/getting-started-with-wso2-api-controller.md
Add latest artifacts in the Getting Started with WSO2 API Controller [1] of the APIM 3.2.0 Docs space to support 3.2.6 API Controller patch release.
[1]. https://apim.docs.wso2.com/en/3.2.0/learn/api-controller/getting-started-with-wso2-api-controller/
=> [3.2.0] Add latest API Controller artifacts for 3.2.6

en/docs/install-and-setup/setup/deployment-best-practices/basic-health-checks.md
Fixes https://github.com/wso2/docs-apim/issues/5180
=> Add health check info for web socket ports

en/docs/install-and-setup/setup/api-controller/advanced-topics/formatting-the-output-of-get-command.md
Update the **Formatting the outputs of list** [1] section in **Getting Started with WSO2 API Controller**[2] to add newly supported "jsonArray" format type.
[1] https://apim.docs.wso2.com/en/3.2.0/learn/api-controller/getting-started-with-wso2-api-controller/#formatting-the-outputs-of-list
[2] https://apim.docs.wso2.com/en/3.2.0/learn/api-controller/getting-started-with-wso2-api-controller/
Fixes https://github.com/wso2/product-apim-tooling/issues/859 …
=> [Master] Update listing formats section in APICTL

en/docs/api-analytics/getting-started-guide.md
https://github.com/wso2-enterprise/choreo/issues/10892
=> Update api analytics navigation url

en/docs/api-analytics/getting-started-guide.md
=> Revert "Update api analytics navigation url"

en/docs/api-analytics/getting-started-guide.md
https://github.com/wso2-enterprise/choreo/issues/10892
=> Update api analytics navigation url-4

en/docs/api-analytics/getting-started-guide.md
https://github.com/wso2-enterprise/choreo/issues/10892
=> update API-Analytics navigation url

en/mkdocs.yml
- fixes build break in master [1].
[1] https://wso2.org/jenkins/view/docs/job/docs/job/docs-apim/
=> fixes build break

en/docs/install-and-setup/setup/api-controller/managing-apis-api-products/managing-apis-and-api-products.md
Fixes https://github.com/wso2/product-apim-tooling/issues/866
=> Add per API logging related commands

en/docs/develop/streaming-apps/installing-siddhi-extensions.md, en/docs/install-and-setup/setup/deployment-best-practices/basic-health-checks.md, en/docs/reference/mediators/property-reference/soap-headers.md
- fixes https://github.com/wso2/docs-apim/issues/4363
=> fixes https://github.com/wso2/docs-apim/issues/4363

en/docs/google5db3f40334e06fa3.html
- Adding the Google search console verification
=> Google search console verification

en/docs/install-and-setup/setup/api-controller/getting-started-with-wso2-api-controller.md
Updating the apictl distributions to apictl 4.1.0-m4
=> Updating the apictl distributions to apictl 4.1.0-m4

en/docs/design/advanced-topics/adding-an-api-state-change-workflow-using-bps.md, en/docs/design/api-security/oauth2/grant-types/password-grant.md, en/docs/install-and-setup/setup/distributed-deployment/configuring-wso2-identity-server-as-a-key-manager.md, en/docs/troubleshooting/error-handling.md, en/docs/troubleshooting/troubleshooting-invalid-callback-error.md, en/mkdocs.yml
- partly fixes https://github.com/wso2/docs-apim/issues/5261
=> partly fixes https://github.com/wso2/docs-apim/issues/5261

en/docs/install-and-setup/upgrading-wso2-api-manager/upgrading-from-210-to-400.md
- fixes https://github.com/wso2/docs-apim/issues/5244
=> fixes https://github.com/wso2/docs-apim/issues/5244

en/docs/administer/managing-users-and-roles/managing-permissions.md, en/docs/design/endpoints/endpoint-types.md, en/docs/integrate/develop/creating-artifacts/creating-an-api.md, en/docs/tutorials/develop-an-integration-with-a-managed-api.md
As $subject, this will add required doc changes related to Top-down approach to create managed API feature
- https://github.com/wso2/docs-apim/issues/5256
=> Add doc changes related to top down API development feature

en/docs/install-and-setup/setup/api-controller/getting-started-with-wso2-api-controller.md, en/mkdocs.yml
Updating the apictl distributions to apictl 4.1.0-alpha
=> Updating the apictl distributions to apictl 4.1.0-alpha and fix doc links of apictl in mkdocs.yml

en/docs/develop/streaming-apps/http-status-codes.md
- fix related to https://github.com/wso2/docs-apim/issues/5277
=> fix related to https://github.com/wso2/docs-apim/issues/5277

en/docs/get-started/about-this-release.md
Update About this Release page for Alpha.
=> About this Release page updates

en/docs/troubleshooting/configuring-xslt-mediation-with-xalan.md
- PR sync for https://github.com/wso2/docs-apim/pull/5279
=> PR sync for https://github.com/wso2/docs-apim/pull/5279

en/docs/learn/analytics/encrypting-sensitive-data-in-apim-analytics.md
=> fixes A-1650

en/docs/reference/mediators/payloadfactory-mediator.md
This PR adds XML to EDI example to PayloadFactory Mediator documentation
Related issue: https://github.com/wso2/micro-integrator/issues/2558
=> [Master] Update payloadFactory-mediator doc with XML to EDI example

en/docs/reference/mediators/payloadfactory-mediator.md
This PR adds XML to EDI example to PayloadFactory Mediator documentation
Related issue: https://github.com/wso2/micro-integrator/issues/2558
=> [4.0.0] Update payloadFactory-mediator doc with XML to EDI example

en/docs/reference/mediators/clone-mediator.md
=> Fix: https://github.com/wso2/micro-integrator/issues/2492

en/docs/deploy-and-publish/deploy-on-gateway/choreo-connect/getting-started/deploy/cc-on-kubernetes-with-apim-as-control-plane-helm-artifacts.md
=> [4.0.0] Fix the URL of controlplane-deployment.toml in helm doc

en/docs/install-and-setup/upgrading-wso2-is-as-key-manager/upgrading-from-is-km-530-to-is-5110.md
- fixes https://github.com/wso2/docs-apim/issues/5258
=> fixes https://github.com/wso2/docs-apim/issues/5258

en/docs/install-and-setup/setup/distributed-deployment/deploying-wso2-api-m-in-a-distributed-setup-with-tm-separated.md, en/docs/reference/customize-product/extending-api-manager/extending-gateway/writing-custom-handlers.md
- fixes https://github.com/wso2/docs-apim/issues/5264
- fixes https://github.com/wso2/docs-apim/issues/5281
=> fixes #5264 and #5281

en/docs/install-and-setup/upgrading-wso2-api-manager/upgrading-from-1100-to-400.md
=> fixes A-1686

en/docs/install-and-setup/setup/distributed-deployment/deploying-wso2-api-m-in-a-distributed-setup-with-tm-separated.md, en/docs/reference/customize-product/extending-api-manager/extending-gateway/writing-custom-handlers.md
- fixes https://github.com/wso2/docs-apim/issues/5264
- fixes https://github.com/wso2/docs-apim/issues/5281
=> fixes #5264 #5281

en/docs/deploy-and-publish/deploy-on-gateway/choreo-connect/extensions/custom-filters.md
=> Fix group ID of Choreo Connect in custom filter doc

en/docs/design/endpoints/resiliency/endpoint-timeouts.md
Fixes https://github.com/wso2/docs-apim/issues/5155
=> Error Code Link fix

en/docs/design/endpoints/resiliency/endpoint-timeouts.md
Fixes https://github.com/wso2/docs-apim/issues/5155
Link not broken in master but changed to point to the specific doc section.
=> Error Code Link fix master

en/theme/material/partials/footer.html
- fixes https://github.com/wso2/docs-apim/issues/5298
=> Changed Copyrights year to 2022

en/docs/deploy-and-publish/deploy-on-gateway/api-gateway/passing-enduser-attributes-to-the-backend-via-api-gateway.md
- fixes https://github.com/wso2/docs-apim/issues/5311
=> fix #https://github.com/wso2/docs-apim/issues/5311

en/docs/deploy-and-publish/deploy-on-gateway/api-gateway/passing-enduser-attributes-to-the-backend-via-api-gateway.md
- fixes https://github.com/wso2/docs-apim/issues/5311
=> fixes https://github.com/wso2/docs-apim/issues/5311

en/docs/install-and-setup/upgrading-wso2-api-manager/upgrading-from-1100-to-400.md
- fixes A-1689
- I merged the "ALTER TABLE AM_POLICY_SUBSCRIPTION" related code based on each DB.
- Fixed formatting issues
- PR sync for https://github.com/wso2/docs-apim/pull/5305
=> fixes A-1689

en/docs/install-and-setup/upgrading-wso2-api-manager/upgrading-from-1100-to-400.md
- fixes A-1689
- I merged the "ALTER TABLE AM_POLICY_SUBSCRIPTION" related code based on each DB.
- Fixed formatting issues
=>  fixes A-1689

en/docs/install-and-setup/setup/deployment-best-practices/basic-health-checks.md
This PR adds docs changes for https://github.com/wso2/product-apim/issues/11961
=> Add websocket health check api details

en/docs/install-and-setup/install/installing-the-product/running-the-mi.md, en/docs/integrate/develop/integration-development-kickstart.md, en/mkdocs.yml
- fixes https://github.com/wso2/docs-apim/issues/4999
=> fixes https://github.com/wso2/docs-apim/issues/4999

en/docs/design/api-security/oauth2/access-token-types/jwt-tokens.md
- fixes https://github.com/wso2/docs-apim/issues/5318
=> fixes https://github.com/wso2/docs-apim/issues/5318

en/docs/design/rate-limiting/graphql-api/overview-query-limits-for-graphql.md
- fixes https://github.com/wso2/docs-apim/issues/5324
=> fixes https://github.com/wso2/docs-apim/issues/5324

en/mkdocs.yml
- fixes https://github.com/wso2/docs-apim/issues/5231
=> fixes https://github.com/wso2/docs-apim/issues/5231

en/docs/integrate/develop/advanced-development/applying-security-to-a-proxy-service.md
- fixes https://github.com/wso2/docs-apim/issues/4998
- Reviewed entire content and updated.
=> fixes https://github.com/wso2/docs-apim/issues/4998

en/docs/reference/customize-product/customizations/customizing-the-developer-portal/overriding-developer-portal-theme.md
- fixes https://github.com/wso2/docs-apim/issues/4911
=> fixes https://github.com/wso2/docs-apim/pull/5336

en/docs/design/api-documentation/add-api-documentation.md
- fixes https://github.com/wso2/docs-apim/issues/5316
=> fixes https://github.com/wso2/docs-apim/issues/5316

en/docs/reference/product-apis/overview.md
=> Update postman collection for APIM 4.0.0

en/docs/install-and-setup/upgrading-wso2-api-manager/upgrading-from-310-to-320.md
=> Update script and trigger for AM_GW_API_ARTIFACTS table

en/docs/administer/logging-and-monitoring/logging/setting-up-logging.md
=> Fix alignment issue

en/docs/install-and-setup/installation-guide/installing-the-product/installing-the-binary/installing-as-a-windows-service.md
- fixes https://github.com/wso2/docs-apim/issues/5356
=> fixes https://github.com/wso2/docs-apim/issues/5356

en/docs/reference/mediators/property-reference/generic-properties.md
Add doc for https://github.com/wso2/micro-integrator/issues/2606
Port https://github.com/wso2/docs-apim/pull/5331
=> Add doc for FORCE_COLLECT_PAYLOAD

en/theme/material/base.html
=> Updated algolia search

en/theme/material/base.html
- migrating to docsearch v3
- These changes are based on the instructions in https://docsearch.algolia.com/docs/DocSearch-v3
- Related to https://github.com/wso2/docs-apim/issues/5387
=> migrating to docsearch v3

en/theme/material/base.html
- migrating docsearch to v3
- Related to https://github.com/wso2/docs-apim/issues/5387
=> migration to v3

en/docs/administer/managing-users-and-roles/managing-user-stores/configuring-secondary-user-stores-mi.md, en/docs/install-and-setup/setup/mi-setup/user_stores/setting_up_a_userstore.md, en/docs/install-and-setup/upgrading-from-wso2-ei/upgrading-from-ei-6.1.0.md, en/docs/install-and-setup/upgrading-from-wso2-ei/upgrading-from-ei-6.1.1.md, en/docs/install-and-setup/upgrading-from-wso2-ei/upgrading-from-ei-6.2.x.md, en/docs/install-and-setup/upgrading-from-wso2-ei/upgrading-from-ei-6.3.x.md, en/docs/install-and-setup/upgrading-from-wso2-ei/upgrading-from-ei-6.4.x.md, en/docs/install-and-setup/upgrading-from-wso2-ei/upgrading-from-ei-6.5.x.md, en/docs/install-and-setup/upgrading-from-wso2-ei/upgrading-from-ei-6.6.x.md
> Add instructions to configure carbon datasource for hybrid role support.
Add steps to migrate carbon datasource in EI.
=> Add instructions to configure carbon datasource.

en/docs/administer/key-managers/configure-keycloak-connector.md
- fixes https://github.com/wso2/docs-apim/issues/5400
=> fixes https://github.com/wso2/docs-apim/issues/5400

en/docs/assets/css/theme.css, en/theme/material/base.html, en/theme/material/partials/header.html
=> Restore search

.gitignore, en/docs/assets/css/theme.css, en/theme/material/base.html, en/theme/material/partials/header.html
- Migrating docsearch to v3
- fixes https://github.com/wso2/docs-apim/issues/5395 for 4.0.0
=> Migrating docsearch to v3

en/docs/observe/micro-integrator/classic-observability-metrics/snmp-monitoring.md
=> Update SNMP enabling steps

en/docs/assets/css/theme.css, en/theme/material/partials/header.html
- fixed font and icon size of search
- fix related to https://github.com/wso2/docs-apim/issues/5395
=> reduced size of search icon and text

en/docs/assets/css/theme.css, en/mkdocs.yml, en/theme/material/partials/header.html
- fixed positioning of search
- fixed font and icon size of search
- fix related to https://github.com/wso2/docs-apim/issues/5395
=> fixed positioning of search

en/docs/install-and-setup/setup/mi-setup/transport_configurations/configuring-transports.md
$subject
Related to https://github.com/wso2/wso2-synapse/pull/1918
=> [4.1.0] Add an Info note about removing QuickFix jar in MI

en/docs/install-and-setup/install/installing-the-product/installing-mi-as-a-windows-service.md
> Fix typo in uninstall service command
=> Fixed invalid command name

en/docs/get-started/about-this-release.md
Adding changes for Beta to About this Release page.
=> Adding Beta release notes

en/docs/get-started/about-this-release.md
=> Formatting fix to About this Release

en/docs/observe/mi-observe/working-with-management-api.md
E - 1340
Related to : https://github.com/wso2/docs-ei/pull/2872
=> Add data-source resource to management api

en/docs/observe/mi-observe/working-with-management-api.md
=> Add data-source resource to management api 

en/docs/get-started/about-this-release.md
=> Add documentation to enable file based artifact synchronization in 4.0.0

en/docs/assets/js/theme.js
- fix for https://github.com/wso2/docs-apim/issues/3963
- PR sync for https://github.com/wso2/docs-apim/pull/5441
=> fixes for https://github.com/wso2/docs-apim/issues/3963

en/docs/assets/js/theme.js
- fix for https://github.com/wso2/docs-apim/issues/3963
=> fix for https://github.com/wso2/docs-apim/issues/3963

en/docs/install-and-setup/setup/api-controller/advanced-topics/using-dynamic-data-in-api-controller-projects.md
Fix a minor issue in the dynamic data update command
=> [4.0.0] Fixing a minor issue in the dynamic data update command of apictl

en/docs/integrate/examples/jms_examples/dual-channel-http-to-jms.md
> URL given for invoking the sender proxy is wrong.
=> Fix proxy invocation URL

en/docs/reference/connectors/connector-usage.md, en/docs/reference/connectors/salesforce-connectors/sf-rest-connector-config.md
> Add tokenEndpointHostname to Salesforcerest API reference
=> Update Salesforcerest API reference

en/docs/get-started/streaming-quick-start-guide.md
- fix for https://github.com/wso2/docs-apim/issues/5320
- PR sync https://github.com/wso2/docs-apim/pull/5447
=> fixes https://github.com/wso2/docs-apim/issues/5320

en/docs/tutorials/integration-tutorials/service-catalog-tutorial-for-proxy-services.md, en/docs/tutorials/integration-tutorials/service-catalog-tutorial.md
- fixes https://github.com/wso2/docs-apim/issues/5443
=> fixes https://github.com/wso2/docs-apim/issues/5443

en/docs/install-and-setup/setup/reference/product-compatibility.md
=> Updated JDK for SI

en/docs/includes/design/create-streaming-api/create-a-websocket-streaming-api.md
- fixes https://github.com/wso2/docs-apim/issues/5403
- PR sync for https://github.com/wso2/docs-apim/pull/5450
=> fixes https://github.com/wso2/docs-apim/issues/5403

en/docs/integrate/examples/message_store_processor_examples/using-message-sampling-processor.md
Fixes https://github.com/wso2/micro-integrator/issues/2642
=> Update the message processor configs.

en/docs/consume/consume-api-overview.md, en/docs/consume/invoke-apis/invoke-apis-using-tools/invoke-an-graphql-api-using-the-integrated-graphql-console.md, en/mkdocs.yml
- fix for https://github.com/wso2/docs-apim/issues/5396
- **consume-api-overview.md**
- **invoke-an-graphql-api-using-the-integrated-graphql-console.md**
- **mkdocs.yml**
=> fix for https://github.com/wso2/docs-apim/issues/5396

en/docs/consume/consume-api-overview.md, en/docs/consume/invoke-apis/invoke-apis-using-tools/invoke-an-graphql-api-using-the-integrated-graphql-console.md, en/docs/get-started/about-this-release.md, en/mkdocs.yml
- fixes https://github.com/wso2/docs-apim/issues/5396
- PR sync for https://github.com/wso2/docs-apim/pull/5462
- consume-api-overview.md
- invoke-an-graphql-api-using-the-integrated-graphql-console.md
- mkdocs.yml
=> fixes https://github.com/wso2/docs-apim/issues/5396

en/docs/install-and-setup/setup/mi-setup/performance_tuning/tuning-inbound-endpoints.md
- fixes fixes https://github.com/wso2/docs-apim/issues/5383
=> fixes fixes https://github.com/wso2/docs-apim/issues/5383

en/docs/install-and-setup/setup/mi-setup/performance_tuning/tuning-inbound-endpoints.md
- fixes https://github.com/wso2/docs-apim/issues/5383
=> fixes https://github.com/wso2/docs-apim/issues/5383

en/docs/design/api-monetization/monetizing-an-api.md
After https://github.com/wso2/product-apim/issues/12177 improvement, query API for the monetization feature has been changed. This PR adds the new configurations.
.
=> Add the new configurations for monetization feature after query api change

en/docs/assets/css/theme.css, en/docs/index.md, en/theme/material/partials/header.html
=> fixes A-1820

en/docs/get-started/about-this-release.md
=> Add develop an intgration from managed api feature  to the release page

en/docs/deploy-and-publish/deploy-on-gateway/choreo-connect/getting-started/deploy/cc-on-kubernetes-with-apim-as-control-plane.md, en/docs/deploy-and-publish/deploy-on-gateway/choreo-connect/getting-started/supported-features.md
- Updated the supported features
- Updated the APIM hostname
=> [CC 1.1.0] Update supported features

en/docs/tutorials/scenarios/scenario-overview.md
changing qunatis.com to quantis.com
=> Fix the login user names correctly

en/docs/design/api-monetization/monetizing-an-api.md
Current stripe jar is wrong and we need to point to the correct jar
=> Fix stripe jar link

en/docs/install-and-setup/setup/kubernetes-operators/k8s-api-operator/install.md
Updates the ClusterRole config with new ingress configs.
Related issue: https://github.com/wso2/k8s-api-operator/issues/610
=> [4.0.0] Update ClusterRole yaml for operator

en/docs/observe/mi-observe/working-with-management-api.md
> Add role related API details to the management API
=> Add role related API details to the management API

en/docs/deploy-and-publish/deploy-on-gateway/choreo-connect/getting-started/deploy/cc-as-a-standalone-gateway-on-kubernetes-helm-artifacts.md, en/docs/deploy-and-publish/deploy-on-gateway/choreo-connect/getting-started/deploy/cc-as-a-standalone-gateway-on-kubernetes.md, en/docs/deploy-and-publish/deploy-on-gateway/choreo-connect/getting-started/deploy/cc-on-kubernetes-with-apim-as-control-plane-helm-artifacts.md, en/docs/deploy-and-publish/deploy-on-gateway/choreo-connect/getting-started/deploy/cc-on-kubernetes-with-apim-as-control-plane.md, en/docs/includes/deploy/k8s-setup-note.md
Adding a note for Rancher users.
Fixes https://github.com/wso2/product-microgateway/issues/2627
=> [CC 1.1.0] Updating K8s docs with Rancher changes

en/docs/deploy-and-publish/deploy-on-gateway/choreo-connect/getting-started/deploy/cc-as-a-standalone-gateway-on-kubernetes-helm-artifacts.md, en/docs/deploy-and-publish/deploy-on-gateway/choreo-connect/getting-started/deploy/cc-as-a-standalone-gateway-on-kubernetes.md, en/docs/deploy-and-publish/deploy-on-gateway/choreo-connect/getting-started/deploy/cc-on-kubernetes-with-apim-as-control-plane-helm-artifacts.md, en/docs/deploy-and-publish/deploy-on-gateway/choreo-connect/getting-started/deploy/cc-on-kubernetes-with-apim-as-control-plane.md, en/docs/includes/deploy/k8s-setup-note.md
Adding a note for Rancher users.
=> [CC 1.0.0]Updating K8s docs with Rancher changes

en/docs/deploy-and-publish/deploy-on-gateway/choreo-connect/getting-started/quick-start-guide-docker-with-apim.md
=> [CC 1.1.0]Updating APIM ports in QSG

en/docs/install-and-setup/setup/deployment-overview.md
- fixed formatting issue
- PR sync for https://github.com/wso2/docs-apim/pull/5530
=> fixed formatting issue

en/docs/install-and-setup/setup/deployment-overview.md
=> Fix formatting issue

en/docs/integrate/develop/installing-wso2-integration-studio.md
=> Revert "Update installing-wso2-integration-studio.md"

en/docs/get-started/about-this-release.md
- added an entry for graphQL subscription
=> added an entry for graphQL subscription

en/docs/get-started/about-this-release.md
Updates made to improvements list.
=> Updates to About this Release

en/docs/install-and-setup/setup/api-controller/building-jenkins-ci-cd-pipeline.md, en/mkdocs.yml
Related to : https://github.com/wso2/docs-apim/pull/5428
=> Rename title of CI/CD story via API Controller doc

en/docs/get-started/about-this-release.md
Fixes to About this Release page.
=> About this Release RC 4.1.0

en/docs/observe/api-manager/monitoring-api-logs.md
Fix https://github.com/wso2/docs-apim/issues/5527
=> Change monitoring log curl command to work without curl command

en/docs/index.md
- fixes https://github.com/wso2/docs-apim/issues/5252
=> fixes https://github.com/wso2/docs-apim/issues/5252

en/docs/reference/product-apis/admin-apis/admin-v2/admin-v2.yaml, en/docs/reference/product-apis/devportal-apis/devportal-v2/devportal-v2.yaml, en/docs/reference/product-apis/overview.md, en/docs/reference/product-apis/publisher-apis/publisher-v2/publisher-v2.yaml
To update the outdated postman collections in:
- APIS Overview page
- Publisher Rest APIs page
- DevPortal Rest APIs page
- Admin Rest APIs page
Solves: https://github.com/wso2/product-apim/issues/12315
=> [4.0.0] Update postman collections

en/docs/get-started/about-this-release.md
Added improvements to the About this Release page based on feedback.
=> Improvements to About this Release page

en/docs/install-and-setup/upgrading-wso2-api-manager/320-to-410/upgrading-from-320-to-410.md, en/docs/install-and-setup/upgrading-wso2-api-manager/400-to-410/upgrading-from-400-to-410.md
=> Fixing typo issue in apim migration Doc 

en/docs/install-and-setup/upgrading-wso2-api-manager/320-to-410/upgrading-from-320-to-410.md, en/docs/install-and-setup/upgrading-wso2-api-manager/320-to-410/what-has-changed.md, en/docs/install-and-setup/upgrading-wso2-api-manager/400-to-410/upgrading-from-400-to-410.md
=> Fixing broken links at migration document

en/docs/install-and-setup/setup/kubernetes-operators/k8s-api-operator/install.md
$subject to point to the latest Operator release.
=> [4.0.0]Update API operator version

en/docs/install-and-setup/setup/api-controller/getting-started-with-wso2-api-controller.md, en/docs/install-and-setup/setup/api-controller/managing-apis-api-products/importing-apis-via-dev-first-approach.md
Updating the apictl distributions to apictl 4.1.0
=> Updating the apictl distributions to apictl 4.1.0

en/docs/install-and-setup/setup/api-controller/managing-apis-api-products/importing-apis-via-dev-first-approach.md
Updating the Sample API definition link of apictl
=> [4.0.0] Updating the Sample API definition link of apictl

en/docs/install-and-setup/upgrading-wso2-api-manager/320-to-410/upgrading-from-320-to-410.md, en/docs/install-and-setup/upgrading-wso2-api-manager/400-to-410/upgrading-from-400-to-410.md
=> Pointing the migration scripts download zip location to release  tag

en/docs/install-and-setup/setup/security/general-data-protection-regulation-gdpr-for-wso2-api-manager.md
Fixes https://github.com/wso2/docs-apim/issues/5504
=> Modify the docs related to forget-me tool 

en/docs/api-analytics/on-prem/elk-installation-guide.md
> Follow up to https://github.com/wso2/docs-apim/pull/5516.
=> Improve the document on ELK solution

en/docs/deploy-and-publish/deploy-on-gateway/choreo-connect/deploy-api/deploy-api-with-custom-hostnames.md, en/docs/deploy-and-publish/deploy-on-gateway/choreo-connect/extensions/custom-filters.md
> $subject + added a minor correction to the doc …
=> [Choreo Connect] Custom filter dependency's version upgrade

en/docs/deploy-and-publish/deploy-on-gateway/choreo-connect/deploy-api/deploy-api-with-custom-hostnames.md
=> [4.0.0][Choreo Connect] - Minor fix to mention API deployment

en/docs/deploy-and-publish/deploy-on-gateway/choreo-connect/getting-started/deploy/cc-on-kubernetes-with-apim-as-control-plane-helm-artifacts.md, en/docs/deploy-and-publish/deploy-on-gateway/choreo-connect/getting-started/deploy/cc-on-kubernetes-with-apim-as-control-plane.md
Updating docs for JWKS endpoint change. …
=> [CC 1.1.0]Update JWKS endpoints in K8s deployments

en/docs/reference/synapse-properties/message-processors/msg-sampling-processor-properties.md
=> [Sync PR]Update msg-sampling-processor-properties.md

en/docs/reference/synapse-properties/message-processors/msg-sched-forwarding-processor-properties.md
=> [Sync PR]Update msg-sched-forwarding-processor-properties.md

en/docs/reference/synapse-properties/message-processors/msg-sched-failover-forwarding-processor-properties.md
=> [Sync PR]Update msg-sched-failover-forwarding-processor-properties.md

en/docs/design/api-policies/attach-policy.md, en/docs/design/api-policies/create-policy.md, en/docs/design/api-policies/samples/create-custom-cc-policy.md
Fixing issues with policy docs.
=> Fixes to policy docs

en/docs/install-and-setup/setup/distributed-deployment/understanding-the-distributed-deployment-of-wso2-api-m.md
Fixes https://github.com/wso2/docs-apim/issues/5568
=> [Sync PR]Update understanding-the-distributed-deployment-of-wso2-api-m.md

en/docs/design/prototype-api/create-mocked-oas-api.md
=> [master] Fix img link in cc mock impl

en/docs/deploy-and-publish/deploy-on-gateway/choreo-connect/deploy-api/deploy-rest-api-with-mock-impl.md, en/docs/includes/design/add-oas-example.md
=> [master] Fix mock impl links and update example section

en/docs/deploy-and-publish/deploy-on-gateway/api-gateway/passing-enduser-attributes-to-the-backend-via-api-gateway.md, en/docs/deploy-and-publish/deploy-on-gateway/choreo-connect/passing-enduser-attributes-to-the-backend-via-choreo-connect.md
- fixes https://github.com/wso2/docs-apim/issues/5239
=> fixes https://github.com/wso2/docs-apim/issues/5239

en/docs/install-and-setup/upgrading-wso2-api-manager/320-to-410/upgrading-from-320-to-410.md
=> removed inprogress tag

en/docs/tutorials/integration-tutorials/using-the-gmail-connector.md
=> Update json-eval expression to use entire json body.

en/docs/install-and-setup/install/installation-options.md
=> Update installation options docs to point to 4.1.x branches

en/docs/tutorials/integration-tutorials/using-the-gmail-connector.md
- PR sync for https://github.com/wso2/docs-apim/pull/5483
=> PR sync for https://github.com/wso2/docs-apim/pull/5483

en/docs/tutorials/scenarios/scenario-overview.md, en/docs/tutorials/scenarios/scenario1-create-rest-api.md, en/docs/tutorials/scenarios/scenario2-access-control.md, en/docs/tutorials/scenarios/scenario8-rate-limiting.md
As $Subject, this will modify scenario docs according to 4.1.0.
=> Add 4.1.0 scenario test documentation

en/docs/get-started/about-this-release.md, en/docs/get-started/apim-architecture.md
Same PR for APIM v4 docs - https://github.com/wso2/docs-apim/pull/5593/files
> Link to the PR for changes to the training content …
=> [CC 1.0.0][APIM v4] Updating about this release and architecture docs

en/docs/deploy-and-publish/publish-on-dev-portal/third-party-api-support.md, en/docs/reference/product-apis/devportal-apis/devportal-v2/devportal-v2.yaml, en/docs/reference/product-apis/publisher-apis/publisher-v2/publisher-v2.yaml
This PR adds few notes to third party API support docs and update the API changes added from the feature.
Related issue:
=> Update Third party API docs

en/docs/install-and-setup/setup/reference/product-compatibility.md
- fixes https://github.com/wso2/docs-apim/issues/5604
=> fixes https://github.com/wso2/docs-apim/issues/5604

en/docs/install-and-setup/setup/reference/product-compatibility.md
- fixes https://github.com/wso2/docs-apim/pull/5610
=> fixes https://github.com/wso2/docs-apim/pull/5612

en/docs/includes/deploy/cc-tryout-in-arm64-docker-note.md
> $subject
> Changes image name.
> Type “Sent” when you have provided new/updated certification questions, plus four …
=> [Choreo Connect] [1.1.0] Change for multi-arch image name use for APIM in CC

en/theme/material/partials/header.html
=> Revert "Update header.html"

en/theme/material/base.html
=> enabled indexing

en/docs/google5db3f40334e06fa3.html
=> Adding google verification

en/docs/config.json
=> updated link for 4.1.0

en/docs/design/api-policies/attach-policy.md
$subject
fix https://github.com/wso2/product-microgateway/issues/2755 …
=> [4.1.0] Fix includes to call interceptor service payload

en/docs/design/api-policies/attach-policy.md
=> [master] Fix includes to call interceptor service payload

en/docs/administer/managing-users-and-roles/managing-user-stores/configure-primary-user-store/configuring-the-primary-user-store.md
Fixes https://github.com/wso2/docs-apim/issues/5507
=> [4.0.0 Sync PR]Update configuring-the-primary-user-store.md

en/docs/administer/key-managers/configure-wso2is-connector.md
Fixes https://github.com/wso2/docs-apim/issues/5431
=> [4.0.0 Sync PR]Update configure-wso2is-connector.md

en/docs/install-and-setup/setup/distributed-deployment/configuring-wso2-identity-server-as-a-key-manager.md
Fixes https://github.com/wso2/docs-apim/issues/5431
=> [4.0.0 Sync PR]Update configuring-wso2-identity-server-as-a-key-manager.md

en/docs/install-and-setup/setup/api-controller/advanced-topics/creating-custom-users-to-perform-api-controller-operations.md
Fixes: https://github.com/wso2/product-apim-tooling/issues/711
=> Adding the missing doc changes of https://github.com/wso2/docs-apim/pull/5575

en/docs/install-and-setup/setup/api-controller/advanced-topics/creating-custom-users-to-perform-api-controller-operations.md
Fixes: https://github.com/wso2/product-apim-tooling/issues/711
=> [4.1.0] Adding the missing doc changes of https://github.com/wso2/docs-apim/pull/5575

en/docs/tutorials/integrating-with-solace.md
- Fixes https://github.com/wso2/docs-apim/issues/5641
=> Add solace getting started guide and fix ambiguous content

en/docs/reference/connectors/file-connector/file-connector-config.md
Add the document changes related to the new property setAvoidPermission which is added to the file connector by https://github.com/wso2-extensions/esb-connector-file/pull/174
=> Add option to skip file permission check in SFTP operations

en/docs/deploy-and-publish/deploy-on-gateway/choreo-connect/production-deployment-guideline.md, en/docs/get-started/api-manager-quick-start-guide.md, en/docs/includes/analytics/configure-synapse-gateway.md, en/docs/includes/deploy/assign-custom-hostname.md, en/docs/install-and-setup/setup/api-controller/building-jenkins-ci-cd-pipeline.md, en/docs/install-and-setup/setup/api-controller/encrypting-secrets-with-ctl.md, en/docs/install-and-setup/setup/api-controller/getting-started-with-wso2-api-controller.md, en/docs/install-and-setup/setup/api-controller/managing-apis-api-products/managing-apis-and-api-products.md, en/docs/install-and-setup/setup/api-controller/managing-apis-api-products/migrating-api-products-to-different-environments.md, en/docs/install-and-setup/setup/api-controller/managing-apis-api-products/migrating-apis-to-different-environments.md, en/docs/install-and-setup/setup/api-controller/managing-applications/managing-applications.md
- fixes https://github.com/wso2/docs-apim/issues/5667
=> fixes https://github.com/wso2/docs-apim/issues/5667

en/docs/consume/manage-application/generate-keys/generate-api-keys.md
- fixes https://github.com/wso2/docs-apim/issues/5666
=> fixes https://github.com/wso2/docs-apim/issues/5666

en/docs/design/prototype-api/overview.md, en/docs/get-started/about-this-release.md
- fixes https://github.com/wso2/docs-apim/issues/5665
=> fixes https://github.com/wso2/docs-apim/issues/5665

en/docs/install-and-setup/setup/security/configuring-transport-level-security.md
- fixes https://github.com/wso2/docs-apim/issues/5650
=> fixes https://github.com/wso2/docs-apim/issues/5650

en/docs/tutorials/streaming-api/create-and-publish-sse-api.md
- fixes https://github.com/wso2/docs-apim/issues/5631
=> fixes https://github.com/wso2/docs-apim/issues/5631

en/docs/deploy-and-publish/deploy-on-gateway/choreo-connect/configurations/control-plane-configurations.md, en/docs/deploy-and-publish/deploy-on-gateway/choreo-connect/getting-started/deploy/cc-as-a-standalone-gateway-on-kubernetes-helm-artifacts.md, en/docs/deploy-and-publish/deploy-on-gateway/choreo-connect/getting-started/deploy/cc-on-kubernetes-with-apim-as-control-plane-helm-artifacts.md, en/tools/config-catalog-generator-cc/data/control-plane/configs.json, en/tools/config-catalog-generator-cc/data/control-plane/cp_jms.toml, en/tools/config-catalog-generator-cc/dist/control-plane-configurations.md, en/tools/config-catalog-generator-cc/dist/enforcer-configurations.md
=> [4.0.0] Update Choreo Connect helm version with 1.0.0-2

en/docs/deploy-and-publish/deploy-on-gateway/choreo-connect/configurations/control-plane-configurations.md, en/docs/deploy-and-publish/deploy-on-gateway/choreo-connect/getting-started/deploy/cc-as-a-standalone-gateway-on-kubernetes-helm-artifacts.md, en/docs/deploy-and-publish/deploy-on-gateway/choreo-connect/getting-started/deploy/cc-on-kubernetes-with-apim-as-control-plane-helm-artifacts.md, en/tools/config-catalog-generator-cc/data/control-plane/configs.json, en/tools/config-catalog-generator-cc/data/control-plane/cp_jms.toml, en/tools/config-catalog-generator-cc/dist/control-plane-configurations.md, en/tools/config-catalog-generator-cc/dist/enforcer-configurations.md
=> [4.1.0] Update Choreo Connect helm version with 1.1.0-1

en/docs/deploy-and-publish/deploy-on-gateway/choreo-connect/configurations/control-plane-configurations.md, en/docs/deploy-and-publish/deploy-on-gateway/choreo-connect/getting-started/deploy/cc-as-a-standalone-gateway-on-kubernetes-helm-artifacts.md, en/docs/deploy-and-publish/deploy-on-gateway/choreo-connect/getting-started/deploy/cc-on-kubernetes-with-apim-as-control-plane-helm-artifacts.md, en/tools/config-catalog-generator-cc/data/control-plane/configs.json, en/tools/config-catalog-generator-cc/data/control-plane/cp_jms.toml, en/tools/config-catalog-generator-cc/dist/control-plane-configurations.md, en/tools/config-catalog-generator-cc/dist/enforcer-configurations.md
port https://github.com/wso2/docs-apim/pull/5664 …
=> [master] Update Choreo Connect helm version with 1.1.0-1

en/theme/material/partials/header.html
- fixes https://github.com/wso2/docs-apim/issues/5685
This fix can be brushed up further by a UX expert.
=> fixes https://github.com/wso2/docs-apim/issues/5685

en/docs/assets/css/theme.css
=> updating algolia theme colors

en/docs/deploy-and-publish/deploy-on-gateway/choreo-connect/getting-started/quick-start-guide-docker-with-apim.md, en/docs/deploy-and-publish/deploy-on-gateway/choreo-connect/production-deployment-guideline.md, en/docs/includes/deploy/cc-tryout-in-arm64-k8s-note.md
> Updated image names to the latest supporting versions.
> Provide users the updated latest image versions.
> Type “Sent” …
=> [4.1.0] [CC] Update image names in CC K8 tryout page

en/docs/install-and-setup/upgrading-wso2-api-manager/400-to-410/upgrading-from-400-to-410.md
- fixes https://github.com/wso2/docs-apim/issues/5695
=> fixes https://github.com/wso2/docs-apim/issues/5695

.devcontainer/Dockerfile, .devcontainer/devcontainer.json
- PR sync for https://github.com/wso2/docs-apim/pull/5687
- fixes https://github.com/wso2/docs-apim/issues/5716
=> add dev container support

.devcontainer/Dockerfile, .devcontainer/devcontainer.json
- PR sync for https://github.com/wso2/docs-apim/pull/5687
- fixes https://github.com/wso2/docs-apim/issues/5716
=> add dev container support 

en/docs/use-cases/streaming-tutorials/expose-a-kafka-topic-as-a-managed-websocket-api.md
- fixes https://github.com/wso2/docs-apim/issues/5640
=> fixes https://github.com/wso2/docs-apim/issues/5640

en/docs/use-cases/examples/streaming-examples/publish-kafka-in-json-format.md
- [4.0.0] fixes https://github.com/wso2/docs-apim/issues/5626
=> [4.0.0] fixes https://github.com/wso2/docs-apim/issues/5626

en/docs/use-cases/examples/streaming-examples/publish-kafka-in-json-format.md
- fixes https://github.com/wso2/docs-apim/issues/5626
- PR sync https://github.com/wso2/docs-apim/pull/5709
=> fixes https://github.com/wso2/docs-apim/issues/5626

en/docs/deploy-and-publish/deploy-on-gateway/choreo-connect/configurations/enforcer-configurations.md, en/docs/deploy-and-publish/deploy-on-gateway/choreo-connect/getting-started/quick-start-guide-docker-with-apim.md, en/docs/deploy-and-publish/deploy-on-gateway/choreo-connect/security/api-authentication/api-authentication.md, en/docs/deploy-and-publish/deploy-on-gateway/choreo-connect/security/api-authentication/api-key-authentication.md, en/docs/deploy-and-publish/deploy-on-gateway/choreo-connect/security/api-authentication/configuring-an-external-key-manager.md, en/docs/deploy-and-publish/deploy-on-gateway/choreo-connect/security/api-authentication/disabling-security.md, en/docs/deploy-and-publish/deploy-on-gateway/choreo-connect/security/api-authentication/internal-key-authentication.md, en/docs/deploy-and-publish/deploy-on-gateway/choreo-connect/security/api-authentication/oauth2-access-tokens.md, en/docs/deploy-and-publish/deploy-on-gateway/choreo-connect/security/generate-a-test-jwt.md, en/docs/deploy-and-publish/deploy-on-gateway/choreo-connect/security/rejecting-revoked-tokens.md, en/mkdocs.yml, en/tools/config-catalog-generator-cc/data/enforcer/configs.json, en/tools/config-catalog-generator-cc/dist/enforcer-configurations.md
=> [4.1.0][CC] Update API Authentication docs

en/docs/deploy-and-publish/deploy-on-gateway/choreo-connect/getting-started/deploy/cc-as-a-standalone-gateway-on-kubernetes-helm-artifacts.md, en/docs/deploy-and-publish/deploy-on-gateway/choreo-connect/getting-started/deploy/cc-on-kubernetes-with-apim-as-control-plane-helm-artifacts.md
Add helm repo before installing APIM helm chart since to install first the wso2 repo should be updated
=> [4.0.0][CC] Add helm repo before installing APIM helm chart

en/docs/deploy-and-publish/deploy-on-gateway/choreo-connect/getting-started/deploy/cc-as-a-standalone-gateway-on-kubernetes-helm-artifacts.md, en/docs/deploy-and-publish/deploy-on-gateway/choreo-connect/getting-started/deploy/cc-on-kubernetes-with-apim-as-control-plane-helm-artifacts.md
Add helm repo before installing APIM helm chart since to install first the wso2 repo should be updated
=> [4.1.0][CC] Add helm repo before installing APIM helm chart

en/docs/deploy-and-publish/deploy-on-gateway/choreo-connect/getting-started/deploy/cc-as-a-standalone-gateway-on-kubernetes-helm-artifacts.md, en/docs/deploy-and-publish/deploy-on-gateway/choreo-connect/getting-started/deploy/cc-on-kubernetes-with-apim-as-control-plane-helm-artifacts.md
Add helm repo before installing APIM helm chart since to install first the wso2 repo should be updated
=> [master][CC] Add helm repo before installing APIM helm chart

en/docs/install-and-setup/setup/mi-setup/deployment/deployment_synchronization.md
"When you have a [clustered deployment]({{base_path}}/install-and-setup/setup/mi-setup/deployment/deploying_wso2_ei/deploying_wso2_ei),"
The link above is broken.
> Brief description of the new feature or bug fix as …
=> Broken link

en/docs/install-and-setup/setup/mi-setup/deployment/deployment_synchronization.md
- PR sync for https://github.com/wso2/docs-apim/pull/5736
=> fixed link

en/docs/reference/config-catalog.md, en/tools/config-catalog-generator/data/configs.json, en/tools/config-catalog-generator/dist/config-catalog.md
Follow up with https://github.com/wso2/docs-apim/pull/5639
=> Axis2 transport proxy configuration

en/docs/deploy-and-publish/deploy-on-gateway/choreo-connect/configurations/enforcer-configurations.md, en/docs/deploy-and-publish/deploy-on-gateway/choreo-connect/getting-started/quick-start-guide-docker-with-apim.md, en/docs/deploy-and-publish/deploy-on-gateway/choreo-connect/security/api-authentication/api-authentication.md, en/docs/deploy-and-publish/deploy-on-gateway/choreo-connect/security/api-authentication/api-key-authentication.md, en/docs/deploy-and-publish/deploy-on-gateway/choreo-connect/security/api-authentication/configuring-an-external-key-manager.md, en/docs/deploy-and-publish/deploy-on-gateway/choreo-connect/security/api-authentication/disabling-security.md, en/docs/deploy-and-publish/deploy-on-gateway/choreo-connect/security/api-authentication/internal-key-authentication.md, en/docs/deploy-and-publish/deploy-on-gateway/choreo-connect/security/api-authentication/oauth2-access-tokens.md, en/docs/deploy-and-publish/deploy-on-gateway/choreo-connect/security/generate-a-test-jwt.md, en/docs/deploy-and-publish/deploy-on-gateway/choreo-connect/security/rejecting-revoked-tokens.md, en/mkdocs.yml, en/tools/config-catalog-generator-cc/data/enforcer/configs.json, en/tools/config-catalog-generator-cc/dist/enforcer-configurations.md
All commits from https://github.com/wso2/docs-apim/pull/5656 to master
=> [master][CC] Update API Authentication docs

en/docs/deploy-and-publish/deploy-on-gateway/choreo-connect/concepts/apim-as-control-plane.md
Fixes https://github.com/wso2/docs-apim/issues/4904
=> [4.0.0] Update apim-as-control-plane.md

en/docs/deploy-and-publish/deploy-on-gateway/choreo-connect/concepts/apim-as-control-plane.md
Fixes https://github.com/wso2/docs-apim/issues/4904
=> [master-Sync PR] Update apim-as-control-plane.md

en/docs/install-and-setup/setup/reference/product-compatibility.md
Fixes https://github.com/wso2/docs-apim/issues/5176
=> [4.0.0-sync] Update product-compatibility.md

en/docs/install-and-setup/setup/reference/product-compatibility.md
Fixes https://github.com/wso2/docs-apim/issues/5176
=> [master-sync] Update product-compatibility.md

en/docs/install-and-setup/setup/security/configuring-transport-level-security.md
Fixes https://github.com/wso2/docs-apim/issues/4689
=> [4.0.0-sync]Update configuring-transport-level-security.md

en/docs/install-and-setup/setup/security/configuring-transport-level-security.md
Fixes https://github.com/wso2/docs-apim/issues/4689
=> [master-sync]Update configuring-transport-level-security.md

en/docs/install-and-setup/setup/mi-setup/transport_configurations/configuring-transports.md, en/docs/install-and-setup/setup/security/configuring-transport-level-security.md
Update the .jar file name and change all occurances.
=> Update JAR name

en/docs/design/api-security/openid-connect/obtaining-user-profile-information-with-openid-connect.md
Fixes https://github.com/wso2/docs-apim/issues/5761
=> [master-sync PR] Update obtaining-user-profile-information-with-openid-connect.md

en/docs/install-and-setup/setup/kubernetes-operators/k8s-api-operator/install.md
- PR sync for https://github.com/wso2/docs-apim/pull/5747
=> Fixed broken YAML url

en/docs/design/api-monetization/monetizing-an-api.md
Fixes https://github.com/wso2/docs-apim/issues/5746
=> [master-Sync PR] Update monetizing-an-api.md

en/docs/reference/connectors/amazons3-connector/amazons3-connector-overview.md
> Add EI 7.1.0 as supported version for S3 connector
=> Update S3 connector supported products.

en/docs/deploy-and-publish/deploy-on-gateway/api-gateway/custom-synapse-artifacts.md, en/mkdocs.yml
Fixes https://github.com/wso2/docs-apim/issues/4190 and https://github.com/wso2/docs-apim/issues/4385
=> Storing custom synapse artifacts

en/docs/install-and-setup/setup/mi-setup/transport_configurations/configuring-transports.md, en/docs/install-and-setup/setup/security/configuring-transport-level-security.md
Updates the name of the JAR file to lowercase.
=> Update JAR file name

en/docs/deploy-and-publish/deploy-on-gateway/choreo-connect/deploy-api/deploy-rest-api-with-mock-impl.md, en/docs/design/prototype-api/create-mocked-js-api.md, en/docs/design/prototype-api/create-mocked-oas-api.md, en/docs/includes/design/add-oas-example.md
https://github.com/wso2/docs-apim/pull/5759 for 4.1.0
=> [4.1.0][CC] Mock Impl - Add sample link and standalone mode steps

en/docs/deploy-and-publish/deploy-on-gateway/choreo-connect/deploy-api/deploy-rest-api-with-mock-impl.md, en/docs/design/prototype-api/create-mocked-js-api.md, en/docs/design/prototype-api/create-mocked-oas-api.md, en/docs/includes/design/add-oas-example.md
=> [master][CC] Mock Impl - Add sample link and standalone mode steps 

en/docs/api-analytics/getting-started-guide.md
> This PR is to add  the UTM source to track users who sign in to Choreo through APIM docs 
Related issue - 
=> [Master]Add UTM source to Choreo sign in

en/docs/api-analytics/getting-started-guide.md
> This PR is to add the UTM source to track users who sign in to Choreo through APIM docs
Related issue -
=> [4.0.0] Add UTM source for Choreo sign in

en/docs/api-analytics/getting-started-guide.md
> This PR is to add the UTM source to track users who sign in to Choreo through APIM docs
Related issue -
=> [4.1.0]Add UTM source for Choreo sign-in

en/docs/reference/connectors/microsoft-azure-storage-connector/microsoft-azure-storage-reference.md
Fixes https://github.com/wso2/docs-apim/issues/5023
=> [4.0.0-Sync PR] Update microsoft-azure-storage-reference.md

en/docs/install-and-setup/setup/reference/product-compatibility.md
- PR sync https://github.com/wso2/docs-apim/pull/5764
=> PR sync https://github.com/wso2/docs-apim/pull/5764

en/docs/deploy-and-publish/deploy-on-gateway/api-gateway/custom-synapse-artifacts.md, en/mkdocs.yml
Fixes https://github.com/wso2/docs-apim/issues/4190 and https://github.com/wso2/docs-apim/issues/4385
=> [4.1.0 Sync PR] Update custom synapse storage details

en/docs/deploy-and-publish/deploy-on-gateway/api-gateway/custom-synapse-artifacts.md, en/mkdocs.yml
Fixes https://github.com/wso2/docs-apim/issues/4190 and https://github.com/wso2/docs-apim/issues/4385
=> [master-Sync PR] Update custom synapse storage details

en/docs/install-and-setup/setup/security/configuring-transport-level-security.md
- fixes https://github.com/wso2/docs-apim/issues/5788
=> fixes https://github.com/wso2/docs-apim/issues/5788

en/docs/install-and-setup/setup/deployment-best-practices/tuning-performance.md
=> Configs for key validation http client

en/docs/api-analytics/samples/publishing-analytics-events-to-external-systems.md
- PR sync for https://github.com/wso2/docs-apim/pull/5791
=> Modify publishing analytics to external systems

en/docs/install-and-setup/setup/deployment-best-practices/tuning-performance.md, en/docs/reference/config-catalog.md, en/tools/config-catalog-generator/data/configs.json, en/tools/config-catalog-generator/dist/config-catalog.md
=> Adding configs for key validation http client into config catalog

en/docs/deploy-and-publish/deploy-on-gateway/choreo-connect/message-transformation/interceptor-microservice/interceptor-microservice.md, en/docs/deploy-and-publish/deploy-on-gateway/choreo-connect/message-transformation/message-transformation-overview.md
=> [4.0.0] Update interceptor open API definition link

en/docs/deploy-and-publish/deploy-on-gateway/choreo-connect/message-transformation/defining-interceptors-in-an-open-api-definition.md, en/docs/deploy-and-publish/deploy-on-gateway/choreo-connect/message-transformation/interceptor-microservice/interceptor-microservice.md, en/docs/deploy-and-publish/deploy-on-gateway/choreo-connect/message-transformation/message-transformation-overview.md
=> [4.1.0] Add sample for HTTP operation level interceptor

en/docs/deploy-and-publish/deploy-on-gateway/choreo-connect/message-transformation/defining-interceptors-in-an-open-api-definition.md, en/docs/deploy-and-publish/deploy-on-gateway/choreo-connect/message-transformation/interceptor-microservice/interceptor-microservice.md, en/docs/deploy-and-publish/deploy-on-gateway/choreo-connect/message-transformation/message-transformation-overview.md
port https://github.com/wso2/docs-apim/pull/5816
=> [master] Add sample for HTTP operation level interceptor

en/docs/deploy-and-publish/deploy-on-gateway/choreo-connect/message-transformation/defining-interceptors-in-an-open-api-definition.md
=> [master] Add sample for HTTP operation level response interceptor

en/docs/reference/customize-product/extending-api-manager/extending-gateway/writing-custom-handlers.md
Add info about `APIMgtLatencyStatsHandler` and `APIStatusHandler`, correct grammar, and organize some content in https://apim.docs.wso2.com/en/latest/reference/customize-product/extending-api-manager/extending-gateway/writing-custom-handlers/#introducing-handlers.
=> Update default list of handlers

en/docs/reference/mediators/property-reference/axis2-properties.md
> Add the documentation of the Axis2 property `enableREST`
=> Add axis2 property enableREST

en/docs/api-analytics/getting-started-guide.md, en/docs/api-analytics/role-based-access-control.md, en/docs/api-analytics/viewing/introduction-to-api-analytics-dashboard.md, en/docs/deploy-and-publish/deploy-on-gateway/choreo-connect/configure-analytics.md
> To add azure app insight events to track users who visit Choreo through APIM docs . 
Related issues - 
https://github.com/wso2-enterprise/choreo/issues/12884
=> [4.1.0] - Add Azure App Insight events to APIM docs 

en/docs/api-analytics/getting-started-guide.md, en/docs/api-analytics/role-based-access-control.md, en/docs/api-analytics/viewing/introduction-to-api-analytics-dashboard.md, en/docs/deploy-and-publish/deploy-on-gateway/choreo-connect/configure-analytics.md
> To add azure app insight events to track users who visit Choreo through APIM docs .
Related issues -
https://github.com/wso2-enterprise/choreo/issues/12884
=> [4.0.0] - Add Azure App Insight events to APIM docs

en/docs/api-analytics/getting-started-guide.md, en/docs/api-analytics/role-based-access-control.md, en/docs/api-analytics/viewing/introduction-to-api-analytics-dashboard.md, en/docs/deploy-and-publish/deploy-on-gateway/choreo-connect/configure-analytics.md
To add azure app insight events to track users who visit Choreo through APIM docs .
Related issues -
https://github.com/wso2-enterprise/choreo/issues/12884
=> [Master] - Add Azure App Insight events to APIM docs

en/docs/install-and-setup/upgrading-wso2-api-manager/upgrading-from-320-to-400.md, en/docs/reference/config-catalog.md, en/tools/config-catalog-generator/data/apim.sync_runtime_artifacts.gateway.toml, en/tools/config-catalog-generator/data/configs.json, en/tools/config-catalog-generator/dist/config-catalog.md
=> Add sync_runtime_artifacts.gateway.gateway_labels config related docs

en/docs/administer/managing-users-and-roles/managing-users-for-admin-portal.md, en/docs/reference/faq.md
Update documentation based on the following fixes.
1. https://github.com/wso2/product-apim/issues/12618
2. https://github.com/wso2/product-apim/issues/12754
=> Update docs with latest improvements sent via u2 updates

en/docs/design/rate-limiting/advanced-topics/configuring-rate-limiting-api-gateway-cluster.md
- fixes https://github.com/wso2/docs-apim/issues/5471
- Content was provided by Tharindu via a Gdoc
=> fixes https://github.com/wso2/docs-apim/issues/5471

en/docs/administer/multitenancy/managing-tenants.md, en/docs/design/rate-limiting/advanced-topics/configuring-rate-limiting-api-gateway-cluster.md
- fixes https://github.com/wso2/docs-apim/issues/5471
- Content was provided by Tharindu via a Gdoc
- PR sync for https://github.com/wso2/docs-apim/pull/5833
- fixes https://github.com/wso2/docs-apim/issues/3509
=> fixes #5471 and #3509

en/docs/administer/multitenancy/managing-tenants.md
- fixes https://github.com/wso2/docs-apim/issues/3509
=> fixes https://github.com/wso2/docs-apim/issues/3509

en/docs/deploy-and-publish/deploy-on-gateway/choreo-connect/configure-analytics.md
- Added improvements for https://github.com/wso2/docs-apim/pull/5845
=> Improvements for PR- 5845

en/docs/install-and-setup/setup/reference/product-compatibility.md
=> Update Oracle Product Compatibility

en/docs/reference/config-catalog.md, en/tools/config-catalog-generator/data/configs.json, en/tools/config-catalog-generator/dist/config-catalog.md
A - 1366
Follow-up with https://github.com/wso2/docs-apim/pull/5864
=> Add X-JWT-Assertion user claims

en/docs/administer/key-managers/configure-wso2is-connector.md
> Update doc with wso2apim-is-plugin info to update and install IS connectors.
=> Update doc with apim-is-plugin info

en/docs/streaming/migrating-from-stream-processor.md, en/mkdocs.yml
=> Add Stream Integration 4x Migration document

en/docs/learn/analytics/configuring-apim-analytics.md
- fixes https://github.com/wso2/docs-apim/issues/1290
=> fixes https://github.com/wso2/docs-apim/issues/1290

en/docs/deploy-and-publish/deploy-on-gateway/choreo-connect/configure-analytics.md
- Addressing PR review comment in https://github.com/wso2/docs-apim/pull/5855
=> Updated based on review comment

en/docs/api-analytics/getting-started-guide.md, en/docs/api-analytics/role-based-access-control.md, en/docs/api-analytics/viewing/introduction-to-api-analytics-dashboard.md, en/docs/deploy-and-publish/deploy-on-gateway/choreo-connect/configure-analytics.md
To add UTM source as custom dimenstions to APIM doc events.
Related issue - https://github.com/wso2-enterprise/choreo/issues/13197
=> [4.1.0] - Add UTM source as custom dimensions to APIM doc events

en/docs/api-analytics/getting-started-guide.md, en/docs/api-analytics/role-based-access-control.md, en/docs/api-analytics/viewing/introduction-to-api-analytics-dashboard.md, en/docs/deploy-and-publish/deploy-on-gateway/choreo-connect/configure-analytics.md
> To add UTM source as custom dimenstions to APIM doc events. 
Related issue - https://github.com/wso2-enterprise/choreo/issues/13197
=> [Master]-Add UTM source as custom dimensions to APIM doc events

en/docs/api-analytics/getting-started-guide.md, en/docs/api-analytics/role-based-access-control.md, en/docs/api-analytics/viewing/introduction-to-api-analytics-dashboard.md, en/docs/deploy-and-publish/deploy-on-gateway/choreo-connect/configure-analytics.md
> To add UTM source as custom dimenstions to APIM doc events.
Related issue - https://github.com/wso2-enterprise/choreo/issues/13197
=> [4.0.0] - Add UTM source as custom dimensions to APIM doc events

en/docs/install-and-setup/upgrading-wso2-api-manager/upgrading-from-260-to-400.md
- fixes A-1357
- As instructed, removed the following from the DB scripts.
- Verified info with Hamool Nizar in this regard.
``` 
DISPLAY_NAME VARCHAR(255) NOT NULL
METADATA BLOB NOT NULL
METADATA BYTEA NOT NULL,
```
=> fixes A-1357

en/docs/reference/connectors/kafka-connector/setting-up-kafka.md
Fixes https://github.com/wso2-enterprise/wso2-apim-internal/issues/33#issuecomment-1134182038
=> Move note above steps

en/docs/observe/micro-integrator/classic-observability-metrics/jmx-monitoring.md
Add docs to MI jmx monitoring using Jolokia
=> Add docs to MI jmx monitoring using Jolokia

en/docs/learn/consume-api/generating-sdks/generate-sdks-in-dev-portal.md, en/docs/reference/config-catalog.md, en/tools/config-catalog-generator/data/apim.sdk.toml, en/tools/config-catalog-generator/data/configs.json, en/tools/config-catalog-generator/dist/config-catalog.md
=> Fixes A-1454

en/docs/deploy-and-publish/deploy-on-gateway/choreo-connect/configure-multiple-gateways-with-choreo-connect.md
=> [4.0.0] Add gateway environment configuration for enforcer and router

en/docs/deploy-and-publish/deploy-on-gateway/choreo-connect/configure-multiple-gateways-with-choreo-connect.md
=> Fix format issue

en/docs/deploy-and-publish/deploy-on-gateway/choreo-connect/configure-multiple-gateways-with-choreo-connect.md
Port https://github.com/wso2/docs-apim/pull/5897
Port https://github.com/wso2/docs-apim/pull/5904
=> [4.1.0] Add gateway environment configuration for enforcer and router

en/docs/deploy-and-publish/deploy-on-gateway/choreo-connect/configure-multiple-gateways-with-choreo-connect.md
port https://github.com/wso2/docs-apim/pull/5905
=> [master] Add gateway environment configuration for enforcer and router

en/docs/deploy-and-publish/deploy-on-gateway/choreo-connect/configure-multiple-gateways-with-choreo-connect.md
=> [master] Fix format issue

en/docs/deploy-and-publish/deploy-on-gateway/choreo-connect/configure-multiple-gateways-with-choreo-connect.md
=> [4.1.0] Fix format issue

en/docs/install-and-setup/setup/mi-setup/deployment/kubernetes_deployment.md
=> fixes A-1576

en/docs/reference/connectors/utility-module/utility-module-config.md, en/docs/reference/connectors/utility-module/utility-module-overview.md
Some connector configurations are changed.
=> Updating the configuration of utility module (connector)

en/docs/reference/connectors/amazonsqs-connector/amazon-inbound-endpoint-1.0.x/amazonsqs-inbound-endpoint-reference-configuration.md, en/mkdocs.yml
Related fix: https://github.com/wso2-extensions/esb-inbound-amazonsqs/pull/15
> Link(s) to product documentation that addresses …
=> Update docs for AmazonSQS Inbound Endpoint v1.1.0

en/docs/design/api-security/oauth2/oauth2-scopes/scope-whitelisting.md
update scope allow listing config
=> update scope allow listing config

en/docs/learn/design-api/create-api/generate-rest-api-from-soap-backend.md
=> fixes A-343

en/docs/tutorials/integrating-with-solace.md
- fixed wrong image
- Fixed issue reported by Tharindu.
=> fixed wrong image

en/docs/install-and-setup/setup/sso/okta-as-an-external-idp-using-oidc.md
- fixes A-2118 
- fixed note on tenant config
- https://github.com/wso2/docs-apim/issues/5312
=> removed note on SP-based analytics

en/docs/install-and-setup/setup/sso/okta-as-an-external-idp-using-oidc.md
- fixes A-2118 
- fixed note on tenant config
- https://github.com/wso2/docs-apim/issues/5312
=> fixed note on tenant config

en/docs/consume/consume-api-overview.md, en/docs/consume/invoke-apis/invoke-apis-using-tools/try-out-using-postman.md, en/mkdocs.yml
- fixes A-2120
- Py sync for https://github.com/wso2/docs-apim/pull/5944
=> fixes A-2120

en/docs/learn/consume-api/generating-sdks/generate-sdks-in-dev-portal.md
- improved U2 related note
- fixes A-1454
=> improved update note

en/docs/reference/product-apis/publisher-apis/publisher-v2/publisher-v2.yaml
Reverts wso2/docs-apim#5809
Reverting to debug the REST API loading issue
=> Revert "Add missing responses - 401 and 500"

en/docs/install-and-setup/setup/setting-up-databases/changing-default-databases/changing-to-mssql.md
> Remove driver class and validation query from doc as it's not required.
=> Specifying driver class in toml is not required for Mssql

en/docs/assets/attachments/install-and-setup/apim200_to_apim300_gateway_artifact_migrator.sh, en/docs/assets/attachments/install-and-setup/apim210_to_apim300_gateway_artifact_migrator.sh, en/docs/assets/attachments/install-and-setup/apim220_to_apim300_gateway_artifact_migrator.sh
- fixes A-274
- PR sync for https://github.com/wso2/docs-apim/pull/2529
=> fixes A-274

en/docs/install-and-setup/upgrading-wso2-api-manager/320-to-410/upgrading-from-320-to-410.md
=> [DO NOT MERGE] Update 3.2.0 to 4.1.0 migration document

en/docs/reference/product-apis/admin-apis/admin-v2/admin-v2.yaml, en/docs/reference/product-apis/devportal-apis/devportal-v2/devportal-v2.yaml, en/docs/reference/product-apis/gateway-apis/gateway-v1/gateway-v1.yaml, en/docs/reference/product-apis/publisher-apis/publisher-v2/publisher-v2.yaml
This PR updates the following REST API yamls:
- admin-v2.yaml
- publisher-v2.yaml
- devportal-v2.yaml 
- gateway-v1.yaml
https://github.com/wso2/docs-apim/issues/5972
=> Update REST API yamls

en/docs/install-and-setup/upgrading-wso2-api-manager/320-to-410/upgrading-from-320-to-410.md
=> Fix APIM migration command and remove pre-validation step

en/docs/learn/api-controller/getting-started-with-wso2-api-controller.md
Adding the artifacts for apictl 3.1.5 distributions to the 3.1.0 doc space.
=> [3.1.0] Adding apictl 3.1.5 artifacts

en/docs/install-and-setup/setup/reference/product-compatibility.md
- fixes [Git issue A-114](https://github.com/wso2-enterprise/wso2-apim-internal/issues/114)
=> fixes Git issue A-114

en/docs/administer/key-managers/configure-wso2is-connector.md
=> fixes A-119

en/docs/install-and-setup/upgrading-wso2-api-manager/400-to-410/upgrading-from-400-to-410.md
=> Fixing migration doc in 4.0.0- 4.1.0

en/docs/reference/product-apis/admin-apis/admin-v2/admin-v2.yaml, en/docs/reference/product-apis/devportal-apis/devportal-v2/devportal-v2.yaml, en/docs/reference/product-apis/gateway-apis/gateway-v1/gateway-v1.yaml, en/docs/reference/product-apis/publisher-apis/publisher-v2/publisher-v2.yaml
Updated following yaml files as requested by review comments for https://github.com/wso2/carbon-apimgt/pull/11282
- admin-api.yaml
- publisher-api.yaml
- devportal-api.yaml
- gateway-api.yaml
Refer: https://github.com/wso2/carbon-apimgt/pull/11282
=> Update yaml files

en/docs/reference/product-apis/admin-apis/admin-v2/admin-v2.yaml, en/docs/reference/product-apis/devportal-apis/devportal-v2/devportal-v2.yaml, en/docs/reference/product-apis/gateway-apis/gateway-v1/gateway-v1.yaml, en/docs/reference/product-apis/publisher-apis/publisher-v2/publisher-v2.yaml
Updated following yaml files
- admin-api.yaml
- publisher-api.yaml
- devportal-api.yaml
- gateway-api.yaml
Related issues: 
Fix https://github.com/wso2/docs-apim/issues/5959
Fix https://github.com/wso2/docs-apim/issues/5954
Fix https://github.com/wso2/docs-apim/issues/5948
Fix https://github.com/wso2/docs-apim/issues/5932
> Brief description of the new feature or bug fix …
=> Update Rest API yaml files

en/docs/reference/customize-product/customizations/customize-the-api-store-and-gateway-urls-for-tenants.md
- fixes A-1230
- PR sync for https://github.com/wso2/docs-apim/pull/6003
=> fixes A-1230

en/docs/reference/customize-product/customizations/customize-the-api-store-and-gateway-urls-for-tenants.md
=> change v3 to v2

en/docs/install-and-setup/upgrading-wso2-api-manager/260-to-410/upgrading-from-260-to-410.md, en/docs/install-and-setup/upgrading-wso2-api-manager/260-to-410/what-has-changed.md, en/docs/install-and-setup/upgrading-wso2-api-manager/300-to-410/upgrading-from-300-to-410.md, en/docs/install-and-setup/upgrading-wso2-api-manager/300-to-410/what-has-changed.md, en/docs/install-and-setup/upgrading-wso2-api-manager/310-to-410/upgrading-from-310-to-410.md, en/docs/install-and-setup/upgrading-wso2-api-manager/310-to-410/what-has-changed.md, en/docs/install-and-setup/upgrading-wso2-api-manager/320-to-410/upgrading-from-320-to-410.md, en/docs/install-and-setup/upgrading-wso2-api-manager/320-to-410/what-has-changed.md, en/docs/install-and-setup/upgrading-wso2-api-manager/upgrading-guidelines.md, en/docs/install-and-setup/upgrading-wso2-is-as-key-manager/upgrading-from-is-5100-to-is-5110.md, en/docs/install-and-setup/upgrading-wso2-is-as-key-manager/upgrading-from-is-km-5100-to-is-5110.md, en/docs/install-and-setup/upgrading-wso2-is-as-key-manager/upgrading-from-is-km-570-to-is-5110.md, en/docs/install-and-setup/upgrading-wso2-is-as-key-manager/upgrading-from-is-km-590-to-is-5110.md, en/mkdocs.yml
=> [4.1.0 migration][PR 8] APIM 4.1.0 Migration doc changes

en/docs/install-and-setup/setup/kubernetes-operators/k8s-api-operator/install.md, en/docs/install-and-setup/setup/kubernetes-operators/k8s-api-operator/manage-integrations/integration-deployments.md
Improve docs to provide feature details release with K8s API operator 2.0.3
Relates to Issue : https://github.com/wso2/k8s-api-operator/issues/615
Pr's : https://github.com/wso2/k8s-api-operator/pull/613
https://github.com/wso2/k8s-api-operator/pull/614
=> Improve docs to provide feature details release with K8s API operator 2.0.3

en/docs/install-and-setup/upgrading-wso2-api-manager/260-to-410/upgrading-from-260-to-410.md, en/docs/install-and-setup/upgrading-wso2-api-manager/300-to-410/upgrading-from-300-to-410.md, en/docs/install-and-setup/upgrading-wso2-api-manager/310-to-410/upgrading-from-310-to-410.md, en/docs/install-and-setup/upgrading-wso2-api-manager/320-to-410/upgrading-from-320-to-410.md, en/docs/install-and-setup/upgrading-wso2-api-manager/400-to-410/upgrading-from-400-to-410.md
=> [4.1.0 Migration doc] Modifying pre migration validation step

en/docs/install-and-setup/upgrading-wso2-api-manager/260-to-410/upgrading-from-260-to-410.md, en/docs/install-and-setup/upgrading-wso2-api-manager/260-to-410/what-has-changed.md, en/docs/install-and-setup/upgrading-wso2-api-manager/300-to-410/upgrading-from-300-to-410.md, en/docs/install-and-setup/upgrading-wso2-api-manager/310-to-410/upgrading-from-310-to-410.md, en/docs/install-and-setup/upgrading-wso2-api-manager/upgrading-guidelines.md
=> [4.1.0 migration][PR 9] Update API-M 4.1.0 migration docs

en/docs/install-and-setup/setup/kubernetes-operators/k8s-api-operator/manage-integrations/integration-deployments.md
=> Fix doc formatting

en/docs/install-and-setup/upgrading-wso2-api-manager/300-to-410/upgrading-from-300-to-410.md
=> Change IS version in 300-410 Docs

en/docs/install-and-setup/upgrading-wso2-is-as-key-manager/upgrading-from-is-km-590-to-is-5110.md
=> Changes in IS-KM Migration Docs

en/docs/install-and-setup/upgrading-wso2-api-manager/260-to-410/upgrading-from-260-to-410.md, en/docs/install-and-setup/upgrading-wso2-api-manager/260-to-410/what-has-changed.md, en/docs/install-and-setup/upgrading-wso2-api-manager/300-to-410/upgrading-from-300-to-410.md, en/docs/install-and-setup/upgrading-wso2-api-manager/300-to-410/what-has-changed.md, en/docs/install-and-setup/upgrading-wso2-api-manager/310-to-410/upgrading-from-310-to-410.md, en/docs/install-and-setup/upgrading-wso2-api-manager/310-to-410/what-has-changed.md, en/docs/install-and-setup/upgrading-wso2-api-manager/320-to-410/upgrading-from-320-to-410.md, en/docs/install-and-setup/upgrading-wso2-api-manager/320-to-410/what-has-changed.md, en/docs/install-and-setup/upgrading-wso2-api-manager/upgrading-guidelines.md, en/docs/install-and-setup/upgrading-wso2-is-as-key-manager/upgrading-from-is-5100-to-is-5110.md, en/docs/install-and-setup/upgrading-wso2-is-as-key-manager/upgrading-from-is-km-5100-to-is-5110.md, en/docs/install-and-setup/upgrading-wso2-is-as-key-manager/upgrading-from-is-km-570-to-is-5110.md, en/docs/install-and-setup/upgrading-wso2-is-as-key-manager/upgrading-from-is-km-590-to-is-5110.md
=> [4.1.0 migration][PR 10] Fix formatting issues in IS migration docs

en/docs/observe/mi-observe/working-with-monitoring-dashboard.md
Update docs for MI Dashboard health check
=> Update monitoring dashboard documentation with health check

en/docs/install-and-setup/upgrading-wso2-api-manager/260-to-410/upgrading-from-260-to-410.md, en/docs/install-and-setup/upgrading-wso2-api-manager/300-to-410/upgrading-from-300-to-410.md, en/docs/install-and-setup/upgrading-wso2-api-manager/310-to-410/upgrading-from-310-to-410.md, en/docs/install-and-setup/upgrading-wso2-api-manager/320-to-410/upgrading-from-320-to-410.md, en/docs/install-and-setup/upgrading-wso2-api-manager/400-to-410/upgrading-from-400-to-410.md, en/docs/install-and-setup/upgrading-wso2-is-as-key-manager/upgrading-from-is-5100-to-is-5110.md, en/docs/install-and-setup/upgrading-wso2-is-as-key-manager/upgrading-from-is-km-5100-to-is-5110.md, en/docs/install-and-setup/upgrading-wso2-is-as-key-manager/upgrading-from-is-km-570-to-is-5110.md, en/docs/install-and-setup/upgrading-wso2-is-as-key-manager/upgrading-from-is-km-590-to-is-5110.md
=> Adding note for role already exist issue

en/docs/reference/mediators/validate-mediator.md
- Fixes wso2-apim-internal/issues/132
=> Fixes wso2-apim-internal/issues/132

en/docs/install-and-setup/upgrading-wso2-is-as-key-manager/upgrading-from-is-5100-to-is-5110.md, en/docs/install-and-setup/upgrading-wso2-is-as-key-manager/upgrading-from-is-km-5100-to-is-5110.md, en/docs/install-and-setup/upgrading-wso2-is-as-key-manager/upgrading-from-is-km-570-to-is-5110.md, en/docs/install-and-setup/upgrading-wso2-is-as-key-manager/upgrading-from-is-km-590-to-is-5110.md
=> [4.1.0 Migration] Fix issues in IS migration docs

en/docs/deploy-and-publish/deploy-on-gateway/choreo-connect/message-transformation/interceptor-microservice/sample-interceptor-services.md
Added a new entry for interceptor service with WSO2 Micro Integrator.
=> New interceptor example entry added

en/docs/deploy-and-publish/deploy-on-gateway/choreo-connect/endpoints/defining-endpoints-in-an-openapi-definition.md, en/docs/deploy-and-publish/deploy-on-gateway/choreo-connect/endpoints/failover-endpoints.md, en/docs/deploy-and-publish/deploy-on-gateway/choreo-connect/endpoints/load-balanced-endpoints.md
=> [CC] Production and Sandbox endpoints docs

en/docs/install-and-setup/upgrading-wso2-api-manager/260-to-410/what-has-changed.md, en/docs/install-and-setup/upgrading-wso2-api-manager/300-to-410/what-has-changed.md, en/docs/install-and-setup/upgrading-wso2-api-manager/310-to-410/what-has-changed.md, en/docs/install-and-setup/upgrading-wso2-api-manager/320-to-410/what-has-changed.md, en/docs/install-and-setup/upgrading-wso2-is-as-key-manager/upgrading-from-is-5100-to-is-5110.md, en/docs/install-and-setup/upgrading-wso2-is-as-key-manager/upgrading-from-is-km-5100-to-is-5110.md, en/docs/install-and-setup/upgrading-wso2-is-as-key-manager/upgrading-from-is-km-570-to-is-5110.md, en/docs/install-and-setup/upgrading-wso2-is-as-key-manager/upgrading-from-is-km-590-to-is-5110.md
=> Add note on zip documents and _overview documents

en/docs/install-and-setup/upgrading-wso2-api-manager/upgrading-from-200-to-400.md, en/docs/install-and-setup/upgrading-wso2-api-manager/upgrading-from-210-to-400.md, en/docs/install-and-setup/upgrading-wso2-api-manager/upgrading-from-220-to-400.md, en/docs/install-and-setup/upgrading-wso2-api-manager/upgrading-from-250-to-400.md, en/docs/install-and-setup/upgrading-wso2-api-manager/upgrading-from-260-to-400.md, en/docs/install-and-setup/upgrading-wso2-api-manager/upgrading-from-300-to-400.md, en/docs/install-and-setup/upgrading-wso2-api-manager/upgrading-from-310-to-400.md, en/docs/install-and-setup/upgrading-wso2-api-manager/upgrading-from-320-to-400.md, en/docs/install-and-setup/upgrading-wso2-is-as-key-manager/upgrading-from-is-5100-to-is-5110.md, en/docs/install-and-setup/upgrading-wso2-is-as-key-manager/upgrading-from-is-km-5100-to-is-5110.md, en/docs/install-and-setup/upgrading-wso2-is-as-key-manager/upgrading-from-is-km-520-to-is-5110.md, en/docs/install-and-setup/upgrading-wso2-is-as-key-manager/upgrading-from-is-km-530-to-is-5110.md, en/docs/install-and-setup/upgrading-wso2-is-as-key-manager/upgrading-from-is-km-550-to-is-5110.md, en/docs/install-and-setup/upgrading-wso2-is-as-key-manager/upgrading-from-is-km-560-to-is-5110.md, en/docs/install-and-setup/upgrading-wso2-is-as-key-manager/upgrading-from-is-km-570-to-is-5110.md, en/docs/install-and-setup/upgrading-wso2-is-as-key-manager/upgrading-from-is-km-590-to-is-5110.md
=> [4.0.0] Remove note to configure SymmetricKeyInternalCryptoProvider

en/docs/reference/mediators/validate-mediator.md
- fixes Git A-132 review comments
- PR sync https://github.com/wso2/docs-apim/pull/6036
- Related to https://github.com/wso2/docs-apim/pull/6030
=> fixes Git A-132 review comments

en/docs/install-and-setup/upgrading-wso2-api-manager/300-to-410/upgrading-from-300-to-410.md, en/docs/install-and-setup/upgrading-wso2-api-manager/310-to-410/upgrading-from-310-to-410.md, en/docs/install-and-setup/upgrading-wso2-api-manager/320-to-410/upgrading-from-320-to-410.md, en/docs/install-and-setup/upgrading-wso2-is-as-key-manager/upgrading-from-is-5100-to-is-5110.md, en/docs/install-and-setup/upgrading-wso2-is-as-key-manager/upgrading-from-is-km-5100-to-is-5110.md, en/docs/install-and-setup/upgrading-wso2-is-as-key-manager/upgrading-from-is-km-570-to-is-5110.md, en/docs/install-and-setup/upgrading-wso2-is-as-key-manager/upgrading-from-is-km-590-to-is-5110.md
=> [4.1.0 Migration] Fix migration docs

en/docs/install-and-setup/upgrading-wso2-api-manager/260-to-410/upgrading-from-260-to-410.md, en/docs/install-and-setup/upgrading-wso2-api-manager/260-to-410/what-has-changed.md, en/docs/install-and-setup/upgrading-wso2-api-manager/300-to-410/upgrading-from-300-to-410.md, en/docs/install-and-setup/upgrading-wso2-api-manager/300-to-410/what-has-changed.md, en/docs/install-and-setup/upgrading-wso2-api-manager/310-to-410/upgrading-from-310-to-410.md, en/docs/install-and-setup/upgrading-wso2-api-manager/310-to-410/what-has-changed.md, en/docs/install-and-setup/upgrading-wso2-api-manager/320-to-410/upgrading-from-320-to-410.md, en/docs/install-and-setup/upgrading-wso2-api-manager/320-to-410/what-has-changed.md, en/docs/install-and-setup/upgrading-wso2-is-as-key-manager/upgrading-from-is-5100-to-is-5110.md, en/docs/install-and-setup/upgrading-wso2-is-as-key-manager/upgrading-from-is-km-5100-to-is-5110.md, en/docs/install-and-setup/upgrading-wso2-is-as-key-manager/upgrading-from-is-km-570-to-is-5110.md, en/docs/install-and-setup/upgrading-wso2-is-as-key-manager/upgrading-from-is-km-590-to-is-5110.md
=> Fix migration docs

en/docs/install-and-setup/setup/security/logins-and-passwords/setting-up-recaptcha.md
This PR,
1. Adds below config to the doc. This was missing in the config list earlier.
```
parameters_in_url_enabled = true
```
2. Fixes some formatting issues in images. …
=> Fix 4.1.0 recaptcha document

en/docs/install-and-setup/setup/security/logins-and-passwords/setting-up-recaptcha.md
This PR,
1. Adds below config to the doc. This was missing in the config list earlier.
```
parameters_in_url_enabled = true
```
2. Fixes some formatting issues in images. …
=> Fix recaptcha doc

en/docs/tutorials/tutorials-overview.md, en/mkdocs.yml
The tutorials section is added back to the tutorial list
=> Revert "Hide Scenario tutorials in the Tutorials section temporarily"

en/docs/tutorials/scenarios/scenario-overview.md
Change sample apim tutrial download path for 4.0.0
=> Change sample apim tutrial download path for 4.0.0

en/docs/install-and-setup/upgrading-wso2-api-manager/310-to-410/upgrading-from-310-to-410.md
=> [4.1.0 Migration] Fix current version

en/docs/install-and-setup/upgrading-wso2-api-manager/upgrading-guidelines.md
=> [4.1.0 Migration] Add notes to migration guidelines doc

en/docs/deploy-and-publish/deploy-on-gateway/choreo-connect/deploy-api/deploy-websocket-api-in-choreo-connect.md, en/docs/includes/design/create-streaming-api/create-a-websocket-streaming-api.md
=> [CC][master] Mention that both pub and sub must be updated for Websocket APIs

en/docs/deploy-and-publish/deploy-on-gateway/choreo-connect/deploy-api/deploy-websocket-api-in-choreo-connect.md, en/docs/includes/design/create-streaming-api/create-a-websocket-streaming-api.md
=> [CC][4.1.0] Mention that both pub and sub must be updated for Websocket APIs

en/docs/install-and-setup/upgrading-wso2-api-manager/260-to-410/upgrading-from-260-to-410.md, en/docs/install-and-setup/upgrading-wso2-api-manager/300-to-410/upgrading-from-300-to-410.md, en/docs/install-and-setup/upgrading-wso2-api-manager/310-to-410/upgrading-from-310-to-410.md, en/docs/install-and-setup/upgrading-wso2-api-manager/320-to-410/upgrading-from-320-to-410.md, en/docs/install-and-setup/upgrading-wso2-api-manager/400-to-410/upgrading-from-400-to-410.md
Fix for https://github.com/wso2-enterprise/wso2-apim-internal/issues/320 …
=> Fixing DrunPreMigration windows command issue

en/docs/install-and-setup/upgrading-wso2-is-as-key-manager/upgrading-from-is-5100-to-is-5110.md, en/docs/install-and-setup/upgrading-wso2-is-as-key-manager/upgrading-from-is-km-5100-to-is-5110.md, en/docs/install-and-setup/upgrading-wso2-is-as-key-manager/upgrading-from-is-km-520-to-is-5110.md, en/docs/install-and-setup/upgrading-wso2-is-as-key-manager/upgrading-from-is-km-530-to-is-5110.md, en/docs/install-and-setup/upgrading-wso2-is-as-key-manager/upgrading-from-is-km-550-to-is-5110.md, en/docs/install-and-setup/upgrading-wso2-is-as-key-manager/upgrading-from-is-km-560-to-is-5110.md, en/docs/install-and-setup/upgrading-wso2-is-as-key-manager/upgrading-from-is-km-570-to-is-5110.md, en/docs/install-and-setup/upgrading-wso2-is-as-key-manager/upgrading-from-is-km-590-to-is-5110.md
Fixes https://github.com/wso2/docs-apim/issues/6090 …
=> Fix APIM identity migration reference issue

en/docs/install-and-setup/install/installing-the-product/installing-mi-dashboard.md, en/docs/install-and-setup/install/installing-the-product/setting-up-ibm-db2.md, en/docs/install-and-setup/install/installing-the-product/setting-up-mssql.md, en/docs/install-and-setup/install/installing-the-product/setting-up-mysql.md, en/docs/install-and-setup/install/installing-the-product/setting-up-oracle.md, en/docs/install-and-setup/install/installing-the-product/setting-up-postgresql.md, en/docs/reference/config-catalog-mi-dashboard.md, en/mkdocs.yml
Related To: https://github.com/wso2/api-manager/issues/291
=> Add docs related giving data source support to mi dashboard

en/docs/install-and-setup/upgrading-wso2-api-manager/upgrading-from-1100-to-400.md, en/docs/install-and-setup/upgrading-wso2-api-manager/upgrading-from-200-to-400.md, en/docs/install-and-setup/upgrading-wso2-api-manager/upgrading-from-210-to-400.md, en/docs/install-and-setup/upgrading-wso2-api-manager/upgrading-from-220-to-400.md, en/docs/install-and-setup/upgrading-wso2-api-manager/upgrading-from-250-to-400.md, en/docs/install-and-setup/upgrading-wso2-api-manager/upgrading-from-260-to-400.md, en/docs/install-and-setup/upgrading-wso2-api-manager/upgrading-from-300-to-400.md, en/docs/install-and-setup/upgrading-wso2-api-manager/upgrading-from-310-to-400.md, en/docs/install-and-setup/upgrading-wso2-api-manager/upgrading-from-320-to-400.md, en/docs/install-and-setup/upgrading-wso2-is-as-key-manager/upgrading-from-is-5100-to-is-5110.md, en/docs/install-and-setup/upgrading-wso2-is-as-key-manager/upgrading-from-is-km-5100-to-is-5110.md, en/docs/install-and-setup/upgrading-wso2-is-as-key-manager/upgrading-from-is-km-520-to-is-5110.md, en/docs/install-and-setup/upgrading-wso2-is-as-key-manager/upgrading-from-is-km-530-to-is-5110.md, en/docs/install-and-setup/upgrading-wso2-is-as-key-manager/upgrading-from-is-km-550-to-is-5110.md, en/docs/install-and-setup/upgrading-wso2-is-as-key-manager/upgrading-from-is-km-560-to-is-5110.md, en/docs/install-and-setup/upgrading-wso2-is-as-key-manager/upgrading-from-is-km-570-to-is-5110.md, en/docs/install-and-setup/upgrading-wso2-is-as-key-manager/upgrading-from-is-km-590-to-is-5110.md
Added the following note to IS as KM migration documentation.
Added the following section additionally into the APIM 2.6.0 migration.
> Link(s) to product documentation that addresses the changes of this PR. If no doc impact, enter “N/A” plus brief explanation of why there’s no doc …
=> Add step removal from apim identity migration client

en/docs/install-and-setup/upgrading-wso2-api-manager/260-to-410/upgrading-from-260-to-410.md, en/docs/install-and-setup/upgrading-wso2-api-manager/300-to-410/upgrading-from-300-to-410.md, en/docs/install-and-setup/upgrading-wso2-api-manager/310-to-410/upgrading-from-310-to-410.md, en/docs/install-and-setup/upgrading-wso2-api-manager/320-to-410/upgrading-from-320-to-410.md, en/docs/install-and-setup/upgrading-wso2-is-as-key-manager/upgrading-from-is-5100-to-is-5110.md, en/docs/install-and-setup/upgrading-wso2-is-as-key-manager/upgrading-from-is-km-5100-to-is-5110.md, en/docs/install-and-setup/upgrading-wso2-is-as-key-manager/upgrading-from-is-km-570-to-is-5110.md, en/docs/install-and-setup/upgrading-wso2-is-as-key-manager/upgrading-from-is-km-590-to-is-5110.md
Fixes https://github.com/wso2/docs-apim/issues/6071
1. Removed the following point and the note.
2. Added the following note to the IS as KM migration docs only.
3. Added the following to the IS as KM documentation
4. Also added the following to the APIM migration document.
> Link(s) …
=> Fix migration doc for internal admin role rename

en/docs/tutorials/create-and-publish-awslambda-api.md
Add update level info of AWS STS AssumeRole support.
=> Add update level info

en/docs/design/api-policies/attach-policy.md, en/docs/design/api-policies/create-policy.md
=> Add the policy revisioning and policy prolog related content

en/docs/deploy-and-publish/deploy-on-gateway/choreo-connect/troubleshooting/debug-memory.md, en/mkdocs.yml
=> [4.1.0] Update router debug image repository name

en/docs/deploy-and-publish/deploy-on-gateway/choreo-connect/deploy-api/deploy-apis-as-immutable-gateway.md, en/docs/deploy-and-publish/deploy-on-gateway/choreo-connect/extensions/custom-filters.md, en/docs/deploy-and-publish/deploy-on-gateway/choreo-connect/getting-started/deploy/cc-as-a-standalone-gateway-on-kubernetes-helm-artifacts.md, en/docs/deploy-and-publish/deploy-on-gateway/choreo-connect/getting-started/deploy/cc-on-kubernetes-with-apim-as-control-plane-helm-artifacts.md, en/docs/deploy-and-publish/deploy-on-gateway/choreo-connect/git-integration.md, en/docs/deploy-and-publish/deploy-on-gateway/choreo-connect/production-deployment-guideline.md, en/docs/deploy-and-publish/deploy-on-gateway/choreo-connect/troubleshooting/debug-memory.md, en/docs/design/api-security/opa-validation/custom-opa-policy-for-choreo-connect.md, en/docs/get-started/about-this-release.md, en/docs/includes/deploy/cc-prod-guide-helm-values-yaml-tip.md, en/mkdocs.yml
Port https://github.com/wso2/docs-apim/pull/6067
Port https://github.com/wso2/docs-apim/pull/6107
Port https://github.com/wso2/docs-apim/pull/6112
=> [master] Add heap dump docs for CC Router and Use placeholder for Choreo Connect version

en/docs/deploy-and-publish/deploy-on-gateway/choreo-connect/deploy-api/deploy-apis-as-immutable-gateway.md, en/docs/deploy-and-publish/deploy-on-gateway/choreo-connect/troubleshooting/debug-memory.md
Port review fixes done in https://github.com/wso2/docs-apim/pull/6110 …
=> [4.1.0] Port review fixes in #6110

en/docs/deploy-and-publish/deploy-on-gateway/choreo-connect/deploy-api/deploy-apis-as-immutable-gateway.md, en/docs/deploy-and-publish/deploy-on-gateway/choreo-connect/extensions/custom-filters.md, en/docs/deploy-and-publish/deploy-on-gateway/choreo-connect/getting-started/deploy/cc-as-a-standalone-gateway-on-kubernetes-helm-artifacts.md, en/docs/deploy-and-publish/deploy-on-gateway/choreo-connect/getting-started/deploy/cc-on-kubernetes-with-apim-as-control-plane-helm-artifacts.md, en/docs/deploy-and-publish/deploy-on-gateway/choreo-connect/getting-started/supported-features.md, en/docs/deploy-and-publish/deploy-on-gateway/choreo-connect/production-deployment-guideline.md, en/docs/deploy-and-publish/deploy-on-gateway/choreo-connect/troubleshooting/debug-memory.md, en/docs/get-started/about-this-release.md, en/docs/includes/deploy/cc-prod-guide-helm-values-yaml-tip.md, en/mkdocs.yml
Port https://github.com/wso2/docs-apim/pull/6067
Port https://github.com/wso2/docs-apim/pull/6107
Port https://github.com/wso2/docs-apim/pull/6112
=> [4.0.0] Add heap dump docs for CC Router and Use placeholder for Choreo Connect version

en/docs/reference/config-catalog.md, en/tools/config-catalog-generator/data/configs.json, en/tools/config-catalog-generator/dist/config-catalog.md
This PR adds the APIM Throttling JMS configs to config catalog.
Fixes https://github.com/wso2/docs-apim/issues/6117
=> [3.2.0] Add APIM Throttling JMS configs to config catalog

en/docs/reference/config-catalog.md, en/tools/config-catalog-generator/data/configs.json, en/tools/config-catalog-generator/dist/config-catalog.md
This PR adds the APIM Throttling JMS configs to config catalog.
Fixes https://github.com/wso2/docs-apim/issues/6117
=> Add APIM Throttling JMS configs to config catalog

en/docs/deploy-and-publish/deploy-on-gateway/choreo-connect/migration-guide-from-api-microgateway.md, en/docs/deploy-and-publish/deploy-on-gateway/choreo-connect/migration-guide-from-ballerina-api-microgateway.md, en/mkdocs.yml
mc
> Adds migration guide of Choreo Connect. 
> This document describes how to migrate from WSO2 API gateway to Choreo Connect.
> Link to the PR for changes to the training content in https://github.com/wso2/WSO2-Training, if …
=> [master] Addition of migration guide for Choreo connect

en/docs/deploy-and-publish/deploy-on-gateway/choreo-connect/migration-guide-from-api-microgateway.md, en/docs/deploy-and-publish/deploy-on-gateway/choreo-connect/migration-guide-from-ballerina-api-microgateway.md, en/mkdocs.yml
> Adds migration guide of Choreo Connect. 
> This document describes how to migrate from WSO2 API gateway to Choreo Connect.
> Link to the PR for changes to the training content in https://github.com/wso2/WSO2-Training, if …
=> [4.1.0] [CC] Addition of migration guide for Choreo Connect

en/docs/deploy-and-publish/deploy-on-gateway/choreo-connect/configurations/configure-logs-overview.md, en/docs/deploy-and-publish/deploy-on-gateway/choreo-connect/deploy-api/deploy-rest-api-in-choreo-connect.md, en/docs/deploy-and-publish/deploy-on-gateway/choreo-connect/getting-started/deploy/cc-as-a-standalone-gateway-on-docker.md, en/docs/deploy-and-publish/deploy-on-gateway/choreo-connect/getting-started/deploy/cc-deploy-overview.md, en/docs/deploy-and-publish/deploy-on-gateway/choreo-connect/getting-started/deploy/cc-on-docker-with-apim-as-control-plane.md, en/docs/deploy-and-publish/deploy-on-gateway/choreo-connect/getting-started/quick-start-guide-docker-with-apim.md, en/docs/deploy-and-publish/deploy-on-gateway/choreo-connect/git-integration.md, en/docs/deploy-and-publish/deploy-on-gateway/choreo-connect/production-deployment-guideline.md, en/mkdocs.yml
> $subject
> Guides users to use K8 deployment option instead of the docker deployment option.
> Type “Sent” when you have …
=> [4.1.0] [CC] Mention about K8 deployment option for production environments

en/docs/deploy-and-publish/deploy-on-gateway/choreo-connect/configurations/configure-logs-overview.md, en/docs/deploy-and-publish/deploy-on-gateway/choreo-connect/endpoints/defining-a-backend-security-scheme.md, en/docs/deploy-and-publish/deploy-on-gateway/choreo-connect/endpoints/failover-endpoints.md, en/docs/deploy-and-publish/deploy-on-gateway/choreo-connect/getting-started/choreo-connect-overview.md, en/docs/deploy-and-publish/deploy-on-gateway/choreo-connect/getting-started/deploy/cc-as-a-standalone-gateway-on-docker.md, en/docs/deploy-and-publish/deploy-on-gateway/choreo-connect/getting-started/deploy/cc-deploy-overview.md, en/docs/deploy-and-publish/deploy-on-gateway/choreo-connect/getting-started/deploy/cc-on-docker-with-apim-as-control-plane.md, en/docs/deploy-and-publish/deploy-on-gateway/choreo-connect/getting-started/quick-start-guide-docker-with-apim.md, en/docs/deploy-and-publish/deploy-on-gateway/choreo-connect/git-integration.md, en/docs/deploy-and-publish/deploy-on-gateway/choreo-connect/production-deployment-guideline.md, en/mkdocs.yml
> $subject
> Guides users to use K8 deployment option instead of the docker deployment option.
> Type “Sent” when you have …
=> [master] [cc] Mention about K8 deployment option for production environments

en/docs/deploy-and-publish/deploy-on-gateway/choreo-connect/configurations/configure-log4j2.md, en/docs/deploy-and-publish/deploy-on-gateway/choreo-connect/deploy-api/deploy-rest-api-in-choreo-connect.md, en/docs/deploy-and-publish/deploy-on-gateway/choreo-connect/endpoints/defining-a-backend-security-scheme.md, en/docs/deploy-and-publish/deploy-on-gateway/choreo-connect/endpoints/failover-endpoints.md, en/docs/deploy-and-publish/deploy-on-gateway/choreo-connect/getting-started/choreo-connect-overview.md, en/docs/deploy-and-publish/deploy-on-gateway/choreo-connect/getting-started/deploy/cc-as-a-standalone-gateway-on-docker.md, en/docs/deploy-and-publish/deploy-on-gateway/choreo-connect/getting-started/deploy/cc-deploy-overview.md, en/docs/deploy-and-publish/deploy-on-gateway/choreo-connect/getting-started/deploy/cc-on-docker-with-apim-as-control-plane.md, en/docs/deploy-and-publish/deploy-on-gateway/choreo-connect/getting-started/quick-start-guide-docker-with-apim.md, en/docs/deploy-and-publish/deploy-on-gateway/choreo-connect/production-deployment-guideline.md, en/mkdocs.yml
> $subject
> Guides users to use K8 deployment option instead of the docker deployment option.
> Type “Sent” when you have …
=> [4.0.0] [CC] Mention about K8 deployment option for production environments

en/docs/get-started/about-this-release.md
> This PR will introduce a new list item for Removed features and functionalities.
=> [Master] Remove Hazelcast Based Gateway Clustering

en/docs/get-started/about-this-release.md
This PR will introduce a new list item for Deprecated features and functionalities.
=> [4.1.0] Deprecate Hazelcast Based Gateway Clustering

en/docs/deploy-and-publish/deploy-on-gateway/choreo-connect/deploy-api/deploy-soap-api-passthrough.md, en/docs/deploy-and-publish/deploy-on-gateway/choreo-connect/update-choreo-connect.md, en/mkdocs.yml
This PR introduces a new section for choreo-connect docs regarding the Choreo-Connect updating.
=> [CC][4.1.0] Adding docs for Choreo Connect updating

en/docs/install-and-setup/setup/distributed-deployment/deploying-wso2-api-m-in-a-distributed-setup-with-tm-separated.md
=> Remove throttle_decision_endpoints from sample

en/docs/learn/design-api/create-api/create-a-rest-api-from-a-swagger-definition.md
=> Update swagger url

en/docs/install-and-setup/upgrading-wso2-api-manager/upgrading-from-260-to-400.md
This PR adds db scripts for creating IDN UMA tables in Oracle and DB2.
Fixes https://github.com/wso2-enterprise/wso2-apim-internal/issues/370 and fixes https://github.com/wso2/api-manager/issues/603 …
=> Add db scripts for creating IDN UMA tables in Oracle and DB2

en/docs/install-and-setup/upgrading-wso2-api-manager/upgrading-from-200-to-400.md, en/docs/install-and-setup/upgrading-wso2-api-manager/upgrading-from-210-to-400.md, en/docs/install-and-setup/upgrading-wso2-api-manager/upgrading-from-220-to-400.md, en/docs/install-and-setup/upgrading-wso2-api-manager/upgrading-from-250-to-400.md
This PR adds below changes,
[1]. update Oracle script to create AM_API_CLIENT_CERTIFICATE table only if not exists: same is fixed in 2.6.0-4.0.0 doc with https://github.com/wso2/docs-apim/pull/1228
[2]. Add primary key to AM_API_COMMENTS table: same if fixed in 2.6.0-4.0.0 doc with https://github.com/wso2/docs-apim/pull/5196 
> Brief description of the new feature or bug …
=> Update 4.0.0 migration scripts

en/docs/deploy-and-publish/deploy-on-gateway/choreo-connect/deploy-api/deploy-soap-api-passthrough.md
$subject
https://github.com/wso2/docs-apim/pull/6096
=> [4.1.0][CC] Mention update date in cc docs for soap-passthrough

en/docs/observe/mi-observe/working-with-management-api.md, en/docs/observe/micro-integrator/classic-observability-logs/monitoring-correlation-logs.md
Add configs resource docs to the working-with-management-api.md
> Fix: wso2/api-manager#191
> Fix: wso2/api-manager#263
> Fix: wso2/api-manager#266
=> Add enable Correlation Logs without a server restart docs

en/docs/administer/logging-and-monitoring/logging/setting-up-logging-per-api.md, en/mkdocs.yml
Fixes https://github.com/wso2/docs-apim/issues/6109
=> [3.2.0] - Update doc on added feature

en/docs/deploy-and-publish/deploy-on-gateway/choreo-connect/deploy-api/deploy-graphql-api-in-choreo-connect.md, en/docs/includes/deploy/cc-deploy-api-standalone-mode.md, en/mkdocs.yml
> $subject.
> Explains how to deploy and invoke GraphQL APIs using Choreo Connect
> Type “Sent” when you have provided …
=> [master] Choreo Connect graphQL documentation addition

en/docs/install-and-setup/upgrading-wso2-api-manager/upgrading-from-1100-to-400.md, en/docs/install-and-setup/upgrading-wso2-api-manager/upgrading-from-200-to-400.md, en/docs/install-and-setup/upgrading-wso2-api-manager/upgrading-from-210-to-400.md, en/docs/install-and-setup/upgrading-wso2-api-manager/upgrading-from-220-to-400.md, en/docs/install-and-setup/upgrading-wso2-api-manager/upgrading-from-250-to-400.md, en/docs/install-and-setup/upgrading-wso2-api-manager/upgrading-from-260-to-400.md, en/docs/install-and-setup/upgrading-wso2-api-manager/upgrading-from-300-to-400.md, en/docs/install-and-setup/upgrading-wso2-api-manager/upgrading-from-310-to-400.md, en/docs/install-and-setup/upgrading-wso2-api-manager/upgrading-from-320-to-400.md
Fixes https://github.com/wso2/api-manager/issues/637 in 4.0.0 doc space …
=> [4.0.0] Fix IS Doc link to usertsore migration

en/docs/deploy-and-publish/deploy-on-gateway/choreo-connect/getting-started/supported-features.md, en/docs/deploy-and-publish/deploy-on-gateway/deploying-apis-in-api-gateway-vs-choreo-connect.md
> $subject
> Updates docs mentioning Choreo Connect GraphQL API support
> Type “Sent” when you have provided new/updated …
=> [4.1.0] Update docs to mention about Choreo Connect GraphQL API support

en/docs/install-and-setup/upgrading-wso2-api-manager/260-to-410/upgrading-from-260-to-410.md, en/docs/install-and-setup/upgrading-wso2-api-manager/300-to-410/upgrading-from-300-to-410.md, en/docs/install-and-setup/upgrading-wso2-api-manager/310-to-410/upgrading-from-310-to-410.md, en/docs/install-and-setup/upgrading-wso2-api-manager/320-to-410/upgrading-from-320-to-410.md
Fixes wso2/api-manager#637 in 4.1.0 doc space …
=> [4.1.0] Fix IS Doc link to userstore migration

en/docs/install-and-setup/upgrading-wso2-api-manager/upgrading-from-200-to-400.md, en/docs/install-and-setup/upgrading-wso2-api-manager/upgrading-from-210-to-400.md, en/docs/install-and-setup/upgrading-wso2-api-manager/upgrading-from-220-to-400.md, en/docs/install-and-setup/upgrading-wso2-api-manager/upgrading-from-250-to-400.md, en/docs/install-and-setup/upgrading-wso2-api-manager/upgrading-from-260-to-400.md, en/docs/install-and-setup/upgrading-wso2-api-manager/upgrading-from-300-to-400.md, en/docs/install-and-setup/upgrading-wso2-api-manager/upgrading-from-310-to-400.md, en/docs/install-and-setup/upgrading-wso2-api-manager/upgrading-from-320-to-400.md
Fixes https://github.com/wso2/api-manager/issues/654 …
=> [4.0.0] Add note on global sequences

en/docs/install-and-setup/upgrading-wso2-api-manager/upgrading-from-320-to-400.md
> resolves https://github.com/wso2/api-manager/issues/668
=> Fixes oracle syntax issues in AM DB scripts.

en/docs/observe/mi-observe/working-with-management-api.md, en/docs/observe/mi-observe/working-with-monitoring-dashboard.md
Fixes wso2/api-manager/issues/387
Added changes related to new management api resources for registries
=> Add docs for registry resources

en/docs/reference/connectors/salesforce-connectors/sf-rest-connector-config.md
Update Salesforce REST connector docs with `getReport` operation which was added by https://github.com/wso2-extensions/esb-connector-salesforcerest/pull/55
=> Update Salesforce REST connector docs with getReport operation

en/docs/reference/mediators/ntlm-mediator.md, en/mkdocs.yml
Fixes https://github.com/wso2-enterprise/wso2-apim-internal/issues/213
=> [master] NTLM mediator docs

en/docs/reference/mediators/dss-mediator.md
Fixes https://github.com/wso2-enterprise/wso2-apim-internal/issues/143
=> [master]Update dss-mediator.md

en/docs/reference/mediators/ntlm-mediator.md, en/mkdocs.yml
Fixes https://github.com/wso2-enterprise/wso2-apim-internal/issues/213
=> NTLM mediator docs

en/docs/install-and-setup/upgrading-wso2-api-manager/upgrading-from-320-to-400.md, en/docs/install-and-setup/upgrading-wso2-api-manager/what-has-changed.md, en/mkdocs.yml
Addresses https://github.com/wso2/api-manager/issues/622 …
=> [4.0.0] Add initial changes to 4.0.0 what has changed doc

en/docs/design/create-api/create-a-graphql-api.md
Fixes https://github.com/wso2-enterprise/wso2-apim-internal/issues/286
=> [4.1.0]Update create-a-graphql-api.md

en/docs/design/create-api/create-a-graphql-api.md
Fixes https://github.com/wso2-enterprise/wso2-apim-internal/issues/286
=> [master]Update create-a-graphql-api.md

en/docs/design/create-api/create-a-graphql-api.md
Fixes https://github.com/wso2-enterprise/wso2-apim-internal/issues/286
=> [4.0.0] Update create-a-graphql-api.md

en/docs/observe/mi-observe/working-with-management-api.md
Added changes for adding binary files as registry resources
Fixes wso2/api-manager/issues/387
=> Update docs for registry resources

en/docs/install-and-setup/upgrading-wso2-api-manager/260-to-410/what-has-changed.md, en/docs/install-and-setup/upgrading-wso2-api-manager/300-to-410/what-has-changed.md, en/docs/install-and-setup/upgrading-wso2-api-manager/310-to-410/what-has-changed.md, en/docs/install-and-setup/upgrading-wso2-api-manager/320-to-410/what-has-changed.md
=> [4.1.0] 4.1.0 improvements to what has changed

en/docs/install-and-setup/upgrading-wso2-api-manager/upgrading-from-1100-to-400.md, en/docs/install-and-setup/upgrading-wso2-api-manager/upgrading-from-200-to-400.md, en/docs/install-and-setup/upgrading-wso2-api-manager/upgrading-from-210-to-400.md, en/docs/install-and-setup/upgrading-wso2-api-manager/upgrading-from-220-to-400.md, en/docs/install-and-setup/upgrading-wso2-api-manager/upgrading-from-260-to-400.md, en/docs/install-and-setup/upgrading-wso2-api-manager/upgrading-from-300-to-400.md, en/docs/install-and-setup/upgrading-wso2-api-manager/upgrading-from-310-to-400.md, en/docs/install-and-setup/upgrading-wso2-api-manager/upgrading-from-320-to-400.md, en/docs/install-and-setup/upgrading-wso2-is-as-key-manager/upgrading-from-is-5100-to-is-5110.md, en/docs/install-and-setup/upgrading-wso2-is-as-key-manager/upgrading-from-is-km-5100-to-is-5110.md, en/docs/install-and-setup/upgrading-wso2-is-as-key-manager/upgrading-from-is-km-560-to-is-5110.md, en/docs/install-and-setup/upgrading-wso2-is-as-key-manager/upgrading-from-is-km-570-to-is-5110.md, en/docs/install-and-setup/upgrading-wso2-is-as-key-manager/upgrading-from-is-km-590-to-is-5110.md
This PR 
- fixes a doc link after APIM migration doc revamp.
- fixes a spelling issue (wso2cabon.jks -> wso2carbon.jks)
> Link to …
=> [4.0.0] Fix doc link

en/docs/install-and-setup/upgrading-wso2-api-manager/260-to-410/upgrading-from-260-to-410.md
Ports https://github.com/wso2/docs-apim/pull/6129 to 4.1.0 doc space.
Fixes https://github.com/wso2/api-manager/issues/603 
> …
=> [4.1.0] Update DB scripts for creating IDN_UMA tables in Oracle and DB2

en/docs/install-and-setup/upgrading-wso2-api-manager/upgrading-from-310-to-400.md
Fixes https://github.com/wso2/api-manager/issues/609 in 3.1.0 - 4.0.0 mysql script …
=> [4.0.0] Add vhost column to AM_GW_API_DEPLOYMENTS mssql script

en/docs/install-and-setup/upgrading-wso2-api-manager/260-to-410/upgrading-from-260-to-410.md, en/docs/install-and-setup/upgrading-wso2-api-manager/300-to-410/upgrading-from-300-to-410.md, en/docs/install-and-setup/upgrading-wso2-api-manager/310-to-410/upgrading-from-310-to-410.md, en/docs/install-and-setup/upgrading-wso2-api-manager/320-to-410/upgrading-from-320-to-410.md, en/docs/install-and-setup/upgrading-wso2-api-manager/400-to-410/upgrading-from-400-to-410.md
Fixes https://github.com/wso2/api-manager/issues/654 in 4.1.0 doc space …
=> [4.1.0] Add note on global sequences 

en/docs/install-and-setup/upgrading-wso2-is-as-key-manager/upgrading-from-is-km-5100-to-is-5110.md, en/docs/install-and-setup/upgrading-wso2-is-as-key-manager/upgrading-from-is-km-520-to-is-5110.md, en/docs/install-and-setup/upgrading-wso2-is-as-key-manager/upgrading-from-is-km-530-to-is-5110.md, en/docs/install-and-setup/upgrading-wso2-is-as-key-manager/upgrading-from-is-km-550-to-is-5110.md, en/docs/install-and-setup/upgrading-wso2-is-as-key-manager/upgrading-from-is-km-560-to-is-5110.md, en/docs/install-and-setup/upgrading-wso2-is-as-key-manager/upgrading-from-is-km-570-to-is-5110.md, en/docs/install-and-setup/upgrading-wso2-is-as-key-manager/upgrading-from-is-km-590-to-is-5110.md
Adds a migration step to alter UM_TENANT table with UM_TENANT_UUID column until an official fix for https://github.com/wso2/product-is/issues/14826 is released.
**Checklist before merging this PR** …
=> [4.0.0] Update IS KM docs with UM_TENANT_UUID scripts

en/docs/install-and-setup/upgrading-from-wso2-ei/upgrading-from-ei-6.1.0.md, en/docs/install-and-setup/upgrading-from-wso2-ei/upgrading-from-ei-6.1.1.md, en/docs/install-and-setup/upgrading-from-wso2-ei/upgrading-from-ei-6.2.x.md, en/docs/install-and-setup/upgrading-from-wso2-ei/upgrading-from-ei-6.3.x.md, en/docs/install-and-setup/upgrading-from-wso2-ei/upgrading-from-ei-6.4.x.md, en/docs/install-and-setup/upgrading-from-wso2-ei/upgrading-from-ei-6.5.x.md, en/docs/install-and-setup/upgrading-from-wso2-ei/upgrading-from-ei-6.6.x.md, en/docs/install-and-setup/upgrading-from-wso2-ei/upgrading-from-ei-7.0.x.md, en/docs/install-and-setup/upgrading-from-wso2-ei/upgrading-from-ei-7.1.x.md
Fixes https://github.com/wso2-enterprise/wso2-apim-internal/issues/624
=> Update zip file name

en/docs/install-and-setup/upgrading-wso2-is-as-key-manager/upgrading-from-is-km-5100-to-is-5110.md, en/docs/install-and-setup/upgrading-wso2-is-as-key-manager/upgrading-from-is-km-520-to-is-5110.md, en/docs/install-and-setup/upgrading-wso2-is-as-key-manager/upgrading-from-is-km-530-to-is-5110.md, en/docs/install-and-setup/upgrading-wso2-is-as-key-manager/upgrading-from-is-km-550-to-is-5110.md, en/docs/install-and-setup/upgrading-wso2-is-as-key-manager/upgrading-from-is-km-560-to-is-5110.md, en/docs/install-and-setup/upgrading-wso2-is-as-key-manager/upgrading-from-is-km-570-to-is-5110.md, en/docs/install-and-setup/upgrading-wso2-is-as-key-manager/upgrading-from-is-km-590-to-is-5110.md
Reverts https://github.com/wso2/docs-apim/pull/6197 …
=> Revert #6197

en/docs/deploy-and-publish/deploy-on-gateway/choreo-connect/faq.md, en/mkdocs.yml
Add FAQs docs for choreo-connect
=> [master] [CC] Add FAQs docs for choreo-connect

en/docs/deploy-and-publish/deploy-on-gateway/choreo-connect/faq.md, en/mkdocs.yml
Add FAQs docs for choreo-connect
=> [4.0.0] [CC] Add FAQs docs for choreo-connect

en/docs/deploy-and-publish/deploy-on-gateway/choreo-connect/faq.md, en/mkdocs.yml
Add FAQs docs for choreo-connect
=> [4.1.0] [CC] Add FAQs docs for choreo-connect

en/docs/deploy-and-publish/deploy-on-gateway/choreo-connect/configurations/enforcer-configurations.md, en/docs/deploy-and-publish/deploy-on-gateway/choreo-connect/configurations/router-configurations.md, en/docs/deploy-and-publish/deploy-on-gateway/choreo-connect/getting-started/supported-features.md, en/docs/deploy-and-publish/deploy-on-gateway/choreo-connect/security/api-authentication/mutual-ssl-authentication.md, en/docs/deploy-and-publish/deploy-on-gateway/deploying-apis-in-api-gateway-vs-choreo-connect.md, en/docs/design/api-security/api-authentication/secure-apis-using-mutual-ssl.md, en/docs/includes/design/create-mtls-api.md, en/docs/includes/design/invoke-mtls-api-using-postman.md, en/docs/includes/handling-mtls-ssl-termination.md, en/mkdocs.yml, en/tools/config-catalog-generator-cc/data/enforcer/configs.json, en/tools/config-catalog-generator-cc/data/enforcer/mutual_ssl.toml, en/tools/config-catalog-generator-cc/data/router/configs.json, en/tools/config-catalog-generator-cc/data/router/downstream_tls.toml, en/tools/config-catalog-generator-cc/dist/enforcer-configurations.md, en/tools/config-catalog-generator-cc/dist/router-configurations.md
Duplicate of #5969 after fixing merge conflicts
=> [cc] [master] [duplicate of #5969] Add documentation on mutual SSL authentication for Choreo Connect

en/docs/troubleshooting/error-handling.md
Fixes https://github.com/wso2-enterprise/wso2-apim-internal/issues/552
=> [master sync] Update error-handling.md

en/docs/install-and-setup/upgrading-from-wso2-ei/upgrading-from-ei-6.1.0.md, en/docs/install-and-setup/upgrading-from-wso2-ei/upgrading-from-ei-6.1.1.md, en/docs/install-and-setup/upgrading-from-wso2-ei/upgrading-from-ei-6.2.x.md, en/docs/install-and-setup/upgrading-from-wso2-ei/upgrading-from-ei-6.3.x.md, en/docs/install-and-setup/upgrading-from-wso2-ei/upgrading-from-ei-6.4.x.md, en/docs/install-and-setup/upgrading-from-wso2-ei/upgrading-from-ei-6.5.x.md
Fixes https://github.com/wso2-enterprise/wso2-apim-internal/issues/432
=> Add note on mediators

en/docs/deploy-and-publish/deploy-on-gateway/choreo-connect/getting-started/supported-features.md, en/docs/deploy-and-publish/deploy-on-gateway/deploying-apis-in-api-gateway-vs-choreo-connect.md
> $subject
> Updates docs mentioning Choreo Connect GraphQL API support
> Type “Sent” when you have provided new/updated …
=> [master] Update docs to mention about Choreo Connect GraphQL API support

en/docs/design/api-policies/create-policy.md
Fix policy notes indentation that breaks the view.
=> Fix the notes section format issue

en/docs/administer/managing-users-and-roles/managing-user-roles.md, en/docs/design/advanced-topics/adding-an-api-state-change-workflow-using-bps.md, en/docs/design/api-versioning/enabling-notifications.md, en/docs/reference/customize-product/customizations/customizing-the-developer-portal/overriding-developer-portal-theme.md
Fixes https://github.com/wso2-enterprise/wso2-apim-internal/issues/595
=> Update tenant conf file location

en/docs/design/api-security/oauth2/grant-types/saml-extension-grant.md
Fixes https://github.com/wso2-enterprise/wso2-apim-internal/issues/459
=> [Master - sync] Update saml-extension-grant.md

en/docs/api-analytics/on-prem/elk-installation-guide.md
Update Filebeats and Logstash Configurations to be more clear with an example
> Link(s) to product documentation that addresses …
=> Update Filebeats and Logstash Configurations

en/docs/install-and-setup/upgrading-wso2-api-manager/upgrading-guidelines.md, en/docs/install-and-setup/upgrading-wso2-is-as-key-manager/upgrading-from-is-5100-to-is-5110.md, en/docs/install-and-setup/upgrading-wso2-is-as-key-manager/upgrading-from-is-km-5100-to-is-5110.md, en/docs/install-and-setup/upgrading-wso2-is-as-key-manager/upgrading-from-is-km-570-to-is-5110.md, en/docs/install-and-setup/upgrading-wso2-is-as-key-manager/upgrading-from-is-km-590-to-is-5110.md, en/mkdocs.yml
Fixes the following issues:
- https://github.com/wso2-enterprise/wso2-apim-internal/issues/683
- https://github.com/wso2-enterprise/wso2-apim-internal/issues/659
- https://github.com/wso2-enterprise/wso2-apim-internal/issues/620
=> IS as a KM fixes

en/docs/install-and-setup/setup/distributed-deployment/deploying-wso2-api-m-in-a-distributed-setup.md
This PR fixes the configurations of distributed deployment page and adds more information to the displayed configs.
=> Fix the configurations of distributed deployment page

en/docs/design/api-security/api-authentication/secure-apis-using-api-keys.md
Fixes https://github.com/wso2-enterprise/wso2-apim-internal/issues/713
=> [Sync master] Update secure-apis-using-api-keys.md

en/docs/install-and-setup/upgrading-wso2-api-manager/upgrading-process.md, en/docs/install-and-setup/upgrading-wso2-is-as-key-manager/upgrading-from-is-5100-to-is-5110.md, en/docs/install-and-setup/upgrading-wso2-is-as-key-manager/upgrading-from-is-km-5100-to-is-5110.md, en/docs/install-and-setup/upgrading-wso2-is-as-key-manager/upgrading-from-is-km-560-to-is-5110.md, en/docs/install-and-setup/upgrading-wso2-is-as-key-manager/upgrading-from-is-km-570-to-is-5110.md, en/docs/install-and-setup/upgrading-wso2-is-as-key-manager/upgrading-from-is-km-590-to-is-5110.md, en/mkdocs.yml
Syncs IS as a KM fixes made to 4.1.0 that are also relevant to 4.0.0
=> [Sync 4.0.0] IS as a KM fixes sync

en/docs/reference/connectors/amazonsqs-connector/amazonsqs-connector-config.md
Fixes https://github.com/wso2-enterprise/wso2-apim-internal/issues/722
=> [Sync master] Update amazonsqs-connector-config.md

en/docs/reference/connectors/amazonsqs-connector/amazonsqs-connector-config.md
Fixes https://github.com/wso2-enterprise/wso2-apim-internal/issues/722
=> [Sync 4.0.0] Update amazonsqs-connector-config.md

en/docs/install-and-setup/upgrading-wso2-api-manager/260-to-410/upgrading-from-260-to-410.md, en/docs/install-and-setup/upgrading-wso2-is-as-key-manager/upgrading-from-is-km-570-to-is-5110.md
This PR adds the check before index creation for MySQL APIM 2.6.0 to 4.1.0 migration scripts.
Fixes https://github.com/wso2/api-manager/issues/750
> Link(s) to product documentation that addresses the changes of this PR. If no doc impact, enter “N/A” plus brief explanation of why …
=> [4.1.0] Add check before index creation for MySQL 2.6.0 migration scripts

en/docs/reference/connectors/kafka-connector/kafka-inbound-endpoint-example.md
Add Kafka Avro inbound endpoint support.
=> Add kafka avro support for the inbound endpoint

en/docs/install-and-setup/upgrading-wso2-api-manager/300-to-410/upgrading-from-300-to-410.md, en/docs/install-and-setup/upgrading-wso2-is-as-key-manager/upgrading-from-is-km-590-to-is-5110.md
This PR adds the DB scripts for UMA tables to the 3.0.0 to 4.1.0 migration docs.
Fixes https://github.com/wso2/api-manager/issues/750
> Link(s) to product documentation that addresses the changes of this PR. If no doc impact, enter “N/A” plus brief explanation of why there’s no doc …
=> [4.1.0] Add UMA table and index creation for 3.0.0 migration scripts

en/docs/install-and-setup/setup/single-node/configuring-an-active-active-deployment.md
Sync PR that fixes https://github.com/wso2-enterprise/wso2-apim-internal/issues/727
=> [Sync PR - master] Update configuring-an-active-active-deployment.md

en/docs/install-and-setup/setup/deployment-best-practices/security-guidelines-for-production-deployment.md, en/docs/install-and-setup/setup/security/enabling-hostname-verification.md
Fixes https://github.com/wso2-enterprise/wso2-apim-internal/issues/726
=> Add strict hostname verification information

en/docs/install-and-setup/setup/deployment-best-practices/security-guidelines-for-production-deployment.md, en/docs/install-and-setup/setup/security/enabling-hostname-verification.md
Fixes https://github.com/wso2-enterprise/wso2-apim-internal/issues/726
=> [Sync master] Add strict hostname verification information

en/docs/install-and-setup/setup/distributed-deployment/deploying-wso2-api-m-in-a-distributed-setup-with-tm-separated.md, en/docs/install-and-setup/setup/distributed-deployment/deploying-wso2-api-m-in-a-distributed-setup.md
Fixed the configuration issues and improved the information on the doc page.
=> Fix the distributed deployment page for 4.1.0

en/docs/install-and-setup/upgrading-wso2-api-manager/upgrading-from-260-to-310.md, en/docs/install-and-setup/upgrading-wso2-api-manager/upgrading-from-300-to-310.md
Fixes https://github.com/wso2-enterprise/wso2-apim-internal/issues/769
=> Remove irrelavant config from analytics migration

en/docs/install-and-setup/upgrading-wso2-api-manager/upgrading-from-260-to-320.md, en/docs/install-and-setup/upgrading-wso2-api-manager/upgrading-from-310-to-320.md
Fixes https://github.com/wso2-enterprise/wso2-apim-internal/issues/769
=> Remove irrelavant config in analytics migration

en/docs/reference/synapse-properties/pull/proxy-service-add-properties-pull.md
Fixes https://github.com/wso2/docs-apim/issues/6322
=> Fix broken images in pulled content

en/docs/reference/synapse-properties/pull/proxy-service-add-properties-pull.md
Sync PR. Fixes https://github.com/wso2/docs-apim/issues/6322
=> Sync - fix broken image links in transports

en/docs/develop/customizations/customizing-login-pages-for-dev-portal-and-publisher.md
Fixes https://github.com/wso2-enterprise/wso2-apim-internal/issues/160
=> Update customizing-login-pages-for-dev-portal-and-publisher.md wuth tenant information

en/docs/administer/logging-and-monitoring/monitoring/monitoring-server-health.md
Fixes a build issue due to config format.
=> Fixes build issue

en/docs/administer/logging-and-monitoring/monitoring/monitoring-server-health.md
Fixes build break due to config issue. Escaping the character with this PR.
=> Fix build issue

en/docs/administer/logging-and-monitoring/monitoring/monitoring-server-health.md
Fixes https://github.com/wso2-enterprise/wso2-apim-internal/issues/801
=> [Sync master] Update monitoring-server-health.md

en/docs/administer/logging-and-monitoring/monitoring/monitoring-server-health.md
Fixes https://github.com/wso2-enterprise/wso2-apim-internal/issues/801
=> [Sync 4.1.0] Update monitoring-server-health.md

en/docs/administer/logging-and-monitoring/monitoring/monitoring-server-health.md
Fixes https://github.com/wso2-enterprise/wso2-apim-internal/issues/801
=> [Sync 4.0.0] Update monitoring-server-health.md

en/docs/deploy-and-publish/deploy-on-gateway/choreo-connect/configurations/enforcer-configurations.md
=> Configuration to load default trusted root certs to enforcer

en/docs/install-and-setup/upgrading-wso2-api-manager/260-to-410/upgrading-from-260-to-410.md, en/docs/install-and-setup/upgrading-wso2-api-manager/300-to-410/upgrading-from-300-to-410.md, en/docs/install-and-setup/upgrading-wso2-api-manager/310-to-410/upgrading-from-310-to-410.md, en/docs/install-and-setup/upgrading-wso2-api-manager/320-to-410/upgrading-from-320-to-410.md
Fixing : https://github.com/wso2/docs-apim/issues/6313
=> Correct database unique ID step reference in later step

en/docs/api-analytics/samples/publishing-custom-analytics-data.md, en/mkdocs.yml
This PR will introduce a new tab under `api-analytics/samples` to guide programmers to publish custom analytics data.
=> [Master] Add docs for publishing custom analytics data

en/docs/deploy-and-publish/deploy-on-gateway/choreo-connect/security/generate-a-test-jwt.md
>  Theres a typo in the configuration toml code, fixed it.
=> Fixing typo in jwtIssuer configuration

en/docs/install-and-setup/setup/api-controller/advanced-topics/configuring-environment-specific-parameters.md
Fixes https://github.com/wso2-enterprise/wso2-apim-internal/issues/800
=> [Sync master]Update configuring-environment-specific-parameters.md

en/docs/install-and-setup/setup/api-controller/advanced-topics/configuring-environment-specific-parameters.md
Fixes https://github.com/wso2-enterprise/wso2-apim-internal/issues/800
=> [Sync-4.1.0]Update configuring-environment-specific-parameters.md

en/docs/integrate/examples/data_integration/odata-service.md
Fixes https://github.com/wso2-enterprise/wso2-apim-internal/issues/919
- Edited to link the correct issue.
=> [Sync master] Update odata-service.md

en/docs/integrate/examples/rest_api_examples/securing-rest-apis.md
$subject 
Resolves https://github.com/wso2/docs-apim/issues/6059
=> [Master] Fix broken user store link

en/docs/integrate/examples/rest_api_examples/securing-rest-apis.md
Resolves https://github.com/wso2/docs-apim/issues/6059
=> [4.0.0] Fix broken user store link

en/docs/reference/connectors/utility-module/utility-module-overview.md
$subject 
Resolves https://github.com/wso2/docs-apim/issues/5911
=> [Master] Fix broken image link

en/docs/deploy-and-publish/deploy-on-gateway/choreo-connect/configurations/router-configurations.md, en/docs/deploy-and-publish/deploy-on-gateway/choreo-connect/data-compression.md, en/mkdocs.yml, en/tools/config-catalog-generator-cc/data/router/configs.json, en/tools/config-catalog-generator-cc/data/router/router_filters.toml, en/tools/config-catalog-generator-cc/dist/router-configurations.md
> $subject
> Explain and demonstrate examples relevant to the Choreo Connect compression filter
> Type “Sent” when you …
=> [4.0.0] Choreo Connect compression filter

en/docs/deploy-and-publish/deploy-on-gateway/choreo-connect/configurations/router-configurations.md, en/docs/deploy-and-publish/deploy-on-gateway/choreo-connect/data-compression.md, en/mkdocs.yml, en/tools/config-catalog-generator-cc/data/router/configs.json, en/tools/config-catalog-generator-cc/data/router/router_filters.toml, en/tools/config-catalog-generator-cc/dist/router-configurations.md
> $subject
> Explain and demonstrate examples relevant to the Choreo Connect compression filter
> Type “Sent” when you …
=> [master] Choreo Connect compression filter

en/docs/install-and-setup/upgrading-wso2-api-manager/upgrading-from-200-to-400.md, en/docs/install-and-setup/upgrading-wso2-api-manager/upgrading-from-210-to-400.md, en/docs/install-and-setup/upgrading-wso2-api-manager/upgrading-from-220-to-400.md, en/docs/install-and-setup/upgrading-wso2-api-manager/upgrading-from-250-to-400.md, en/docs/install-and-setup/upgrading-wso2-api-manager/upgrading-from-260-to-400.md, en/docs/install-and-setup/upgrading-wso2-api-manager/upgrading-from-300-to-400.md, en/docs/install-and-setup/upgrading-wso2-api-manager/upgrading-from-310-to-400.md, en/docs/install-and-setup/upgrading-wso2-api-manager/upgrading-from-320-to-400.md
Add newly added migration pre-validators to the documentation
=> [4.0.0] Add migration pre-validators to documentation

en/docs/observe/api-manager/monitoring-http-access-logs.md, en/docs/reference/config-catalog.md, en/tools/config-catalog-generator/data/configs.json, en/tools/config-catalog-generator/dist/config-catalog.md
This PR fixes the issue: https://github.com/wso2/product-apim/issues/12853
This PR updates following documents:
- https://apim.docs.wso2.com/en/latest/observe/api-manager/monitoring-http-access-logs/
- https://apim.docs.wso2.com/en/latest/reference/config-catalog/
=> Updated monitoring-http-access-logs file
