wso2/docs-apim

en/docs/WIP/json-schema-validator.md

Fixed image links json-schema-validator.md again as there were issues with the last fix.

Fixed image links json-schema-validator.md

---

en/docs/Learn/DesignAPI/AdvancedTopics/block-subscription-to-an-api.md
en/docs/Learn/DesignAPI/CreateAPI/create-a-graphql-api.md
en/mkdocs.yml

Fixed links and notes in the block-subscription-to-an-api.md file. Did this change to get rid of the following warning.
```
WARNING -  A relative path to 'Learn/RateLimiting/AdvancedTopics/block-subscription-to-an-api.md' is included in the 'nav' configuration, which is not found in the documentation files 
WARNING -  Documentation file 'Learn/DesignAPI/AdvancedTopics/block-subscription-to-an-api.md' contains a link to 'Learn/DesignAPI/AdvancedTopics/Key-Concepts_103328852.html' which is not found in the documentation files. 
WARNING -  Documentation file 'Learn/DesignAPI/AdvancedTopics/block-subscription-to-an-api.md' contains a link to 'Learn/DesignAPI/AdvancedTopics/Key-Concepts_103328852.html' which is not found in the documentation files. 
WARNING -  Documentation file …
```

Fixed links in block-subscription-to-an-api.md

---

en/docs/Learn/APIMonetization/monetizing-an-api.md
en/docs/Learn/APISecurity/Authentication/json-schema-validator.md

Made changes to get rid of the for monetizing-an-api.md and json-schema-validator.md related following warning messages that appear when running mkdocs build.
```
WARNING -  Documentation file 'Learn/APIMonetization/monetizing-an-api.md' contains a link to '../assets/img/Learn/obtain-keys.png' which is not found in the documentation files. 
WARNING -  Documentation file 'Learn/APIMonetization/monetizing-an-api.md' contains a link to '../assets/img/Learn/create-platform-account.png' which is not found in the documentation files. 
WARNING -  Documentation file 'Learn/APIMonetization/monetizing-an-api.md' contains a link to '../assets/img/Learn/developer-mode.png' which is not found in the documentation files. 
WARNING -  Documentation file 'Learn/APIMonetization/monetizing-an-api.md' …
```

Fix to avoid mkdocs build warnings for monetizing and json-schema-validator

---

en/docs/Learn/DesignAPI/AdvancedTopics/generating-server-stubs-and-client-sdks-in-the-api-publisher.md
en/mkdocs.yml

Removing SDK generation doc temporarily. Need to add it back if this feature is supported in the future.

Removing SDK generation doc temporarily

---

en/mkdocs.yml

Customizing urls for tenants is not supported yet for API Manager 3.0.0. Hence temporarily removing the page from this PR.

Hide customize-the-api-store-and-gateway-urls-for-tenants page

---

en/docs/Learn/APIController/building-a-cicd-pipeline.md
en/docs/Learn/APIController/migrating-applications-to-different-environments.md

This fix is to remove the following mkdocs warning.
```
WARNING -  Documentation file 'Learn/APIController/building-a-cicd-pipeline.md' contains a link to '../assets/img/Learn/ci-cd-pipeline-for-apis-with-wso2-apim.png' which is not found in the documentation files. 
WARNING -  Documentation file 'Learn/APIController/building-a-cicd-pipeline.md' contains a link to '../assets/img/Learn/creating-env-based-artifacts.png' which is not found in the documentation files. 
WARNING -  Documentation file 'Learn/APIController/building-a-cicd-pipeline.md' contains a link to '../assets/img/Learn/api-automation-with-openapi-swagger.png' which is not found in the documentation files. 
WARNING -  Documentation file 'Learn/APIController/migrating-applications-to-different-environments.md' contains a link …
```

Fixed mkdocs related warnings in Learn/APIController/

---

en/docs/Learn/APIGateway/MessageMediation/convert-a-json-message-to-soap-and-soap-to-json.md
en/docs/Learn/APIGateway/MessageMediation/pass-a-custom-authorization-token-to-the-backend.md
en/docs/Learn/APIGateway/api-gateways-with-dedicated-backends.md
en/docs/Learn/APIGateway/maintaining-separate-production-and-sandbox-gateways.md
en/docs/Learn/APIGateway/message-tracing.md
en/docs/Learn/APIGateway/overview-of-the-api-gateway.md
en/docs/Learn/Extensions/adding-mediation-extensions.md

Fixed the mkdocs related warning for the Learn/APIGateway files.
```
WARNING -  Documentation file 'Learn/APIGateway/api-gateways-with-dedicated-backends.md' contains a link to '../assets/img/Learn/single-endpoint.png' which is not found in the documentation files. 
WARNING -  Documentation file 'Learn/APIGateway/api-gateways-with-dedicated-backends.md' contains a link to '../assets/img/Learn/single-endpoint.png' which is not found in the documentation files. 
WARNING -  Documentation file 'Learn/APIGateway/api-gateways-with-dedicated-backends.md' contains a link to '../assets/img/Learn/dedicated-endpoint.png' which is not found in the documentation files. 
WARNING -  Documentation file 'Learn/APIGateway/api-gateways-with-dedicated-backends.md' contains a link to …
```

Fixed the mkdocs related warning for the Learn/APIGateway files

---

en/docs/Learn/Analytics/AnalyzingAPIMStatisticsWithBatchAnalytics/viewing-api-statistics.md
en/docs/Learn/Analytics/integrating-with-google-analytics.md
en/docs/Learn/Analytics/purging-analytics-data.md

Fixed the following mkdocs issues related to Learn/Analytics/
```
WARNING -  Documentation file 'Learn/Analytics/integrating-with-google-analytics.md' contains a link to '../assets/img/Learn/management-console-browse.png' which is not found in the documentation files. 
WARNING -  Documentation file 'Learn/Analytics/integrating-with-google-analytics.md' contains a link to '../assets/img/Learn/ga-config-xml.png' which is not found in the documentation files. 
WARNING -  Documentation file 'Learn/Analytics/integrating-with-google-analytics.md' contains a link to '../assets/img/Learn/enable-google-analytics.png' which is not found in the documentation files. 
WARNING -  Documentation file 'Learn/Analytics/integrating-with-google-analytics.md' contains a link to …
```

Fixed the mkdocs issues related to Learn/Analytics/

---

en/docs/SetupAndInstall/InstallationGuide/InstallingTheProduct/InstallingTheBinary/installing-on-solaris.md
en/docs/SetupAndInstall/InstallationGuide/InstallingTheProduct/InstallingTheBinary/installing-on-windows.md
en/docs/SetupAndInstall/InstallationGuide/running-the-product.md
en/mkdocs.yml

- Fixed mkdocs related warnings.
```
WARNING -  Documentation file 'SetupAndInstall/InstallationGuide/running-the-product.md' contains a link to '../assets/img/setup-and-install/running-product-mgt-console-url.png' which is not found in the documentation files. 
WARNING -  Documentation file 'SetupAndInstall/InstallationGuide/running-the-product.md' contains a link to '../assets/img/setup-and-install/running-product-publisher-url.png' which is not found in the documentation files. 
WARNING -  Documentation file 'SetupAndInstall/InstallationGuide/running-the-product.md' contains a link to '../assets/img/setup-and-install/running-product-dev-portal-url.png' which is not found in the documentation files. 
WARNING -  Documentation file …
```

Minor fixes

---

en/docs/Learn/APISecurity/APIAuthentication/secure-apis-using-mutual-ssl.md

> Remove supported keystore types for mutual SSL. Supported keystore (trust store) is not relavant to here.

Fix confusion in supported cert/keystore types for mutual SSL

---

en/docs/Learn/ConsumeAPI/Customizations/customize-the-api-store-and-gateway-urls-for-tenants.md

Just a small documentation correction, the default API store url for the APIM was _'https://<HostName>:9443/store'_, but now it is _'https://<HostName>:9443/devportal'_.

Change of api store's default url

---

en/docs/learn/api-security/oauth2/access-token-types/jwt-tokens.md

JWT already stands for JSON Web Token, so no 'token' word is needed after the abbreviation.

Use JWT without the 'token' word

---

en/docs/install-and-setup/upgrading-wso2-api-manager/upgrading-from-200-to-300.md
en/docs/install-and-setup/upgrading-wso2-api-manager/upgrading-from-210-to-300.md
en/docs/install-and-setup/upgrading-wso2-api-manager/upgrading-from-220-to-300.md
en/docs/install-and-setup/upgrading-wso2-api-manager/upgrading-from-250-to-300.md
en/docs/install-and-setup/upgrading-wso2-api-manager/upgrading-from-260-to-300.md

I have no idea where the second change in en/docs/install-and-setup/upgrading-wso2-api-manager/upgrading-from-200-to-300.md came from

Fix postgres database type in migration guide

---

en/docs/learn/analytics/default-ports-of-wso2-api-m-analytics.md

Dashboard portal port was missing in the doc. Also reworded Stream processor to APIM Analytics to avoid confusion.

Add dashboard portal port info to docs.

---

en/docs/learn/analytics/managing-dashboard-permissions.md

Adding description for analytics dashboard permission delegation to users. A flow of defined permission levels are delegated when users log in to the analytics dashboards.
Filling the permission delegation gap in the documentation

Adds description for analytics dashboard permission delegation to users.

---

en/docs/learn/api-controller/importing-apis-via-dev-first-approach.md

Fixes: https://github.com/wso2/docs-apim/issues/940
Fixes: https://github.com/wso2/product-apim-tooling/issues/225#issuecomment-605960198
Change the documentation about api_params.yaml file and describe the security parameters.
- Changed the template of api_params.yaml
- Changed the example under the template of api_params.yaml.
- Add a new description of security parameters.
- Users can see the modifications done to api_params.yaml.
- Users can have an idea on how the security parameters such as enabled, type, username and password should be set.
https://github.com/wso2/product-apim-tooling/pull/237

Modify api_params.yaml documentation with security parameters

---

en/docs/learn/api-controller/building-jenkins-ci-cd-pipeline-for-dev-first-approach.md
en/docs/learn/api-controller/ci-cd-with-wso2-api-management.md
en/docs/learn/api-controller/getting-started-with-wso2-api-controller.md

Fixes: https://github.com/wso2/docs-apim/issues/947
- Improve the documentation on CI/CD 
- Change the port numbers of dev and prod environments
- Add examples
- Add new links and clarification for documentation in https://github.com/wso2/docs-apim/blob/master/en/docs/learn/api-controller/ci-cd-with-wso2-api-management.md
- Assigned the lower port number value to dev (lower environment) and larger port value to prod (upper environment)
- Add examples for both linux/unix and mac in appropriate pages

Improve the apictl documentation on CI/CD and change port numbers for dev and prod environments for APIM 3.1.0

---

en/docs/learn/api-controller/building-jenkins-ci-cd-pipeline-for-dev-first-approach.md
en/docs/learn/api-controller/ci-cd-with-wso2-api-management.md
en/docs/learn/api-controller/getting-started-with-wso2-api-controller.md

Fixes: https://github.com/wso2/docs-apim/issues/947
- Improve the documentation on CI/CD 
- Change the port numbers of dev and prod environments
- Add examples
- Add new links and clarification for documentation in https://github.com/wso2/docs-apim/blob/3.0.0/en/docs/learn/api-controller/ci-cd-with-wso2-api-management.md
- Assigned the lower port number value to dev (lower environment) and larger port value to prod (upper environment)
- Add examples for both linux/unix and mac in appropriate pages

Improve the apictl documentation on CI/CD and change port numbers for dev and prod environments for APIM 3.0.0

---

en/docs/learn/api-controller/migrating-apis-to-different-environments.md

Fixes: https://github.com/wso2/docs-apim/issues/964
Describe and demonstrate the functionality when using "apictl export-apis" command.
- Created a new section titled "Export all the APIs of a tenant at once" in https://apim.docs.wso2.com/en/next/learn/api-controller/migrating-apis-to-different-environments/
- Added the "apictl export-apis" command with the proper flags
- Described the flags
- Provided example usages
- Provided response format and sample response
- Change some formatting on the same page 
**Preview**
A user can refer this documentation when he/she wants to migrate APIs which belong to a particular tenant to a different environment at once. (Export all the APIs belong to the currently logged in user's tenant at once)
https://github.com/wso2/product-apim-tooling/pull/261

Add documentation on "apictl export-apis" command

---

en/docs/learn/analytics/configuring-keystores-in-apim-analytics.md
en/mkdocs.yml

Adding documentation to configure keystores for different use cases in APIM Analytics.
Adding missing components to improve the docs.

Adds documentation for configuring keystores in APIM analytics.

---

en/docs/learn/api-controller/ci-cd-with-wso2-api-management.md
en/docs/learn/api-controller/getting-started-with-wso2-api-controller.md

Move Get-Keys section of apictl from getting started page to CI/CD section page.
Fixes: https://github.com/wso2/product-apim-tooling/issues/226
-  Remove Get keys section from the Getting Started page and insert them as the last step which is the step **G** in CI/CD pipeline.
- Then change the steps in descriptions of the CI/CD pipeline section with the newly entered step. 
- Insert a new info section at the end of the get-keys section to provide information about changing Token type,  HTTP request timeout and export directory.
Users can follow the steps to create CI/CD pipeline with the step of Get-keys without revisiting to Getting started page.

Move get keys section to CI/CD

---

en/docs/learn/design-api/create-api-product/api-product-overview.md

Change the examples on API Products on the page **API Product Overview**.
Since the resources in the examples are wrong, correcting the resources of "Leasing API Product" and "Credit API Product" were done.
- Changed the tables under the topics "Leasing API Product" and "Credit API Product" in the **API Product Overview** page as follows.
Users can refer to the corrected examples when creating an API Product.

Modifying the resources in the API Products examples

---

en/docs/learn/api-controller/migrating-apis-to-different-environments.md

Fixes: https://github.com/wso2/product-apim-tooling/issues/228
Add a message to the user, so that the user can import already exported APIs without getting an error because of the endpoint password is missing but the security is enabled by eliminating the contradicting situation.
Add a Warning message as below on the page **Migrating APIs to Different Environments**.
- Users can refer the documentation here when he/she wants to import an exported API with Secure Endpoint enabled and the endpoint password exposed.
- Users can refer the documentation here when he/she wants to import an exported API with Secure Endpoint enabled and the endpoint password was not exposed.

Add a Warning on expose endpoint password

---

en/docs/learn/api-controller/advanced-topics/configuring-environment-specific-parameters.md

The security field is misplaced in the example in **Configuring Environment Specific Parameters**. It will be corrected here.
Adjust the security field and indents associated with it.
The security parameters field under the test environment was moved down and the indents were adjusted for security parameters to match with other parameters as shown below.
A user can refer to this example and the security parameter setting to know how to do it successfully.

Modify the example in Configuring Environment Specific Parameters

---

en/docs/reference/ConfigCatalog.md
en/docs/reference/config-catalog.md
en/docs/wip/config-catalog.md

Add the missing underscore to the database configuration tag.
Correct the word "databaseconfiguration" as "database_configuration" under the topic **Configuration Catalog**.
Add an underscore between the words "database" and "configuration".

Add missing underscore to database configuration tag

---

en/docs/reference/ConfigCatalog.md
en/docs/reference/config-catalog.md
en/docs/wip/config-catalog.md

Add the missing underscore to the database configuration tag.
Correct the word "databaseconfiguration" as "database_configuration" under the topic **Configuration Catalog**.
Add an underscore between the words "database" and "configuration".

Add underscore to database configuration tag

---

en/docs/learn/api-controller/advanced-topics/creating-custom-users-to-perform-api-controller-operations.md

Fixing the issue of mentioning users do not need any permission when listing the APIs. (only needed apim:api_view scope)
Fixing a doc issue
Change it as a user should have either API Create/Publish/Subscriber Permission to listing apis.

APICTL list apis permissions fix in Docs

---

en/docs/learn/api-controller/advanced-topics/creating-custom-users-to-perform-api-controller-operations.md

Fixing the issue of mentioning users do not need any permission when listing the APIs. (only needed apim:api_view scope)
Fixing a doc issue
Change it as a user should have either API Create/Publish/Subscriber Permission to listing apis.

APICTL list apis permissions fix

---

en/docs/learn/api-controller/ci-cd-with-wso2-api-management.md
en/docs/learn/api-controller/getting-started-with-wso2-api-controller.md

Fixes: https://github.com/wso2/product-apim-tooling/issues/284
Fixes: https://github.com/wso2/product-apim-tooling/issues/294
Fixes documentation issues on get-keys, listing and deleting API Products in https://github.com/wso2/product-apim-tooling/issues/288
Modifying the documentation on listing APIs/API Products /Applications, generating keys for APIs/API Products and deleting APIs/API Products /Applications using API Controller.
- Restructured the documentation on listing APIs and applications by adding a new topic as **List APIs/API Products/Applications in an environment** to the page **Getting Started with WSO2 API Controller** as follows.
- Added the documentation on **Delete APIs/API Products/Applications in an environment** to the page **Getting Started with WSO2 API Controller** …

Add documentation to describe listing and deleting APIs/API Products/Applications and generating keys for APIs/API Products using the API Controller

---

en/docs/learn/api-controller/getting-started-with-wso2-api-controller.md

In documents the environment remove command and related examples are given in the format of
remove-env -e <environment_name>. But with the fix https://github.com/wso2/product-apim-tooling/pull/296/files this command structure is changed and those changes has to be reflected in Docs also
Fixes : https://github.com/wso2/product-apim-tooling/issues/297
Change command and examples as apictl **remove env <environment_name>**
MacOS Catallina 10.15.4

[Docs] Change remove environment command and related example.

---

en/docs/learn/api-controller/getting-started-with-wso2-api-controller.md

In documents the environment remove command and related examples are given in the format of
remove-env -e <environment_name>. But with the fix https://github.com/wso2/product-apim-tooling/pull/296/files this command structure is changed and those changes has to be reflected in Docs also
Fixes : https://github.com/wso2/product-apim-tooling/issues/297
Change command and examples as apictl **remove env <environment_name>**
MacOS Catallina 10.15.4

[Docs] Change examples and commands given under remove-env command 

---

en/docs/develop/customizations/customizing-the-developer-portal/advanced-customization.md

Fixing issue https://github.com/wso2/docs-apim/issues/1132
Removed the part asking the user to download the source code from the git tag and copy it to the devportal folder.
Added an additional part to ask to do the production build.

Fixing Guide issues for 3.1.0

---

en/docs/learn/api-controller/ci-cd-with-wso2-api-management.md
en/docs/learn/api-controller/getting-started-with-wso2-api-controller.md

Removing the changes related to API Products that have been done in https://github.com/wso2/docs-apim/pull/1134
Remove API Product related information from the API Controller documentation since the full feature is not completed yet.
Removed API Product related documentation content from the sections **Getting Started with WSO2 API Controller** and **CI/CD with WSO2 API Manager**.
https://github.com/wso2/docs-apim/pull/1134

Remove documentation changes related to the functionalities get-keys, list and delete API Products

---

en/docs/develop/customizations/adding-a-user-signup-workflow.md

The existing epr copy location was incorrect. Added the correct location. This change is only for EI
>Copying files to the incorrect location gives errors when trying to involve workflows in the signup process

Modified epr copy location for EI

---

en/docs/learn/api-controller/importing-apis-via-dev-first-approach.md
en/docs/learn/api-gateway/response-caching.md
en/docs/learn/api-security/api-authentication/secure-apis-using-oauth2-tokens.md
en/docs/learn/design-api/advanced-topics/enabling-cors-for-apis.md
en/docs/learn/design-api/create-api/create-a-rest-api-from-a-swagger-definition.md
en/docs/learn/rate-limiting/setting-throttling-limits.md

With the Fix related to wso2/carbon-apimgt#8485 some of the content in the docs will have to change. As it states when importing an OASDefinition through APIM Publisher Portal or using apictl tool, X-WSO2 vendor extensions are assigned as it fits the newly created API if they are defined in the OAS Definition. This PR will revise and change related topics according to the newly provided support. 
Fixes https://github.com/wso2/product-apim/issues/8036
**New table about APIM supported open API extensions is added**
**The places where the above extensions can be used are provided in the docs under the relevant topics.** 
Java 1.8_241
MacOS Catalina 10.15.4

[Docs]Support x-wso2 Swagger extensions that are already supported by Micro Gateway when importing OAS definitions.

---

en/docs/learn/api-controller/importing-apis-via-dev-first-approach.md
en/docs/learn/api-gateway/response-caching.md
en/docs/learn/api-security/api-authentication/secure-apis-using-oauth2-tokens.md
en/docs/learn/design-api/advanced-topics/enabling-cors-for-apis.md
en/docs/learn/design-api/create-api/create-a-rest-api-from-a-swagger-definition.md
en/docs/learn/rate-limiting/setting-throttling-limits.md

With the Fix related to wso2/carbon-apimgt#8485 some of the content in the docs will have to change. As it states when importing an OASDefinition through APIM Publisher Portal or using apictl tool, X-WSO2 vendor extensions are assigned as it fits the newly created API if they are defined in the OAS Definition. This PR will revise and change related topics according to the newly provided support. 
Fixes https://github.com/wso2/product-apim/issues/8036
**New table about APIM supported open API extensions is added**
**The places where the above extensions can be used are provided in the docs under the relevant topics.** 
Java 1.8_241
MacOS Catalina 10.15.4

[Docs]Support x-wso2 Swagger extensions that are already supported by Micro Gateway when importing OAS definitions.-(MasterBranch)

---

en/docs/learn/api-controller/getting-started-with-wso2-api-controller.md

Adding documentation for https://github.com/wso2/product-apim-tooling/issues/205
Add documentation content to explain the usage of the owner (-o/--owner) flag when listing application using the API Controller.
Added a tip in the page **Getting Started with WSO2 API Controller** under the section **c. List Applications in an environment**.
Users can refer this to learn about the usage of the owner flag and to identify when to use it or not.
- https://github.com/wso2/carbon-apimgt/pull/8380
- https://github.com/wso2/product-apim-tooling/pull/209

Adding documentation content to explain the usage of the owner flag when listing apps using the API Controller

---

en/docs/learn/api-controller/getting-started-with-wso2-api-controller.md

Adding documentation for https://github.com/wso2/product-apim-tooling/issues/205
Add documentation content to explain the usage of the owner (-o/--owner) flag when listing application using the API Controller.
Added a tip in the page **Getting Started with WSO2 API Controller** under the section **b. List Applications in an environment**.
Users can refer this to learn about the usage of the owner flag and to identify when to use it or not.
- https://github.com/wso2/carbon-apimgt/pull/8380
- https://github.com/wso2/product-apim-tooling/pull/209

Adding documentation content to explain the usage of the owner flag when listing apps using the API Controller [3.1.0]

---

en/docs/learn/consume-api/manage-application/sharing-applications/sharing-applications.md

changes based on review comments in https://github.com/wso2/docs-apim/pull/1296
"New react based UI's doesn't have Regenerate button."

fix for https://github.com/wso2/docs-apim/issues/1229

---

en/docs/install-and-setup/deploying-wso2-api-manager/distributed-deployment/configuring-wso2-identity-server-as-a-key-manager.md

Updating the link for prepackaged WSO2 Identity Server in APIM 3.0.0 doc space.
Adding the correct link to download the prepackaged WSO2 Identity Server.
Change the corresponding link to incorporate the above change under the topic **Configuring WSO2 Identity Server as Key Manager**

Update the link for prepackaged WSO2 Identity Server

---

en/docs/learn/api-controller/ci-cd-with-wso2-api-management.md
en/docs/learn/api-controller/getting-started-with-wso2-api-controller.md

Document changes related to https://github.com/wso2/product-apim-tooling/issues267 issue in apictl. 
Currently , --environment, --token flags are mandatory and a user has to provide either --apim or the other 4 flags (--publisher, --admin, --devportal, --registration) when adding an environment. As an improvement, it is possible to make --token flag optional by using https:localhost:9443/oauth2/token endpoint as same as we do in the UI (without using the gateway endpoint - 8243/token).
When doing this, it needs to inform the user, that when generating keys, we are going to use the https:localhost:9443/oauth2/token endpoint by default and if he/she is using a third party key manager, they need to provide that endpoint as --token endpoint, to be used in the get-keys operation.
Fixes …

[Docs]Docs Changes fix for apim-tooling #267

---

en/docs/develop/customizations/log-in-to-the-dev-portal-using-social-media.md

Here I have added Basic Claims Configurations and Role configurations, if you are not adding these configuration we will get below error after login to Developer portal using Facebook.
Error 403 : Forbidden
The server could not verify that you are authorized to access the requested resource.

Added Basic Claims Configurations and Role configurations

---

en/docs/learn/api-controller/advanced-topics/configuring-different-endpoint-types.md
en/docs/learn/api-controller/advanced-topics/configuring-environment-specific-parameters.md

The indentation of api_params.yaml was wrong in some places. Also, the **sessionTimout** field should be converted to **sessionTimeOut** in the documentation. 
Provide the correct template for api_params.yaml
- Changed the **security** field in the api_params.yaml to an object, which was earlier denoted as an array in the page **Configuring Environment Specific Parameters** under **API Controller/Advanced Topics**
- Corrected **sessionTimout** as **sessionTimeOut** in the page **Configuring Different Endpoint Types** under **API Controller/Advanced Topics**
- Changed the indentation of the example for **Dynamic Endpoints** in the page **Configuring Different Endpoint Types** under **API Controller/Advanced Topics**
Users can followup the correct examples with the correct template of …

[APIM 3.2.0] Change the indentation and update the field names of api_params.yaml

---

en/docs/learn/api-controller/advanced-topics/configuring-environment-specific-parameters.md

The indentation of api_params.yaml was wrong in some places.
Provide the correct template for api_params.yaml
- Changed the **security** field in the api_params.yaml to an object, which was earlier denoted as an array in the page **Configuring Environment Specific Parameters** under **API Controller/Advanced Topics**
Users can followup the correct examples with the correct template of api_params.yaml when importing APIs using the API Controller.

[APIM 3.1.0] Change the indentation and update the fields of api_params.yaml 

---

en/docs/learn/api-gateway/threat-protectors/xml-threat-protection-for-api-gateway.md
en/docs/learn/api-security/threat-protection/gateway-threat-protectors/xml-threat-protection-for-api-gateway.md

As a support to https://github.com/wso2/product-apim/pull/8575, updating the documentation will be done here.
Adding the property **entityExpansionLimit** to the example of xml_validator.xml
Updated the xml_validator.xml in the page **XML Threat Protection for API Gateway** under **API Security/Threat Protection**.
Can refer to the correct example file inside the API.
https://github.com/wso2/product-apim/pull/8575

Modifying the examples on xml_validator.xml with the field "entityExpansionLimit"

---

en/docs/learn/api-controller/ci-cd-with-wso2-api-management.md
en/docs/learn/api-controller/migrating-api-products-to-different-environments.md

Remove unnecessary content and the content related to API Products versioning from the documentation. 
Avoid confusion that the users may have when referring the docs.
- Removed endpoint certificates related information for API Products.
- Removed secure endpoints related information for API Products.
- Removed mentioning the versions of API Products.
Users do not need to worry about the endpoint certificates,  secure endpoints and the version of an API Product.

Modify documentation on the support for API Products from the API Controller

---

en/docs/develop/product-apis/publisher-apis/publisher-v1/publisher-v1.yaml

As the changes in PR https://github.com/wso2/docs-apim/pull/1398 have not been done in the respective `carbon-apimgt` repo, new changes to `publisher-v1.yaml` wiped-out the changes that were done in [1]. Therefore, I added the changes back.
[1] https://github.com/wso2/docs-apim/pull/1398

Redoing https://github.com/wso2/docs-apim/pull/1398

---

en/docs/learn/api-controller/getting-started-with-wso2-api-controller.md

Added the documentation on the Importing SSL certificates in the controller.
Related git issue: wso2/product-apim-tooling#417
This is to cover the doc impact of wso2/product-apim-tooling#235

Docs for Import cert for controller APIM 3.1.0

---

en/docs/learn/api-controller/getting-started-with-wso2-api-controller.md

Added the documentation on the Importing SSL certificates in controller.
Related git issue: https://github.com/wso2/product-apim-tooling/issues/417
This is to cover the doc impact of https://github.com/wso2/product-apim-tooling/issues/235

Doc changes for importing certs in controller

---

en/docs/learn/api-controller/ci-cd-with-wso2-api-management.md
en/docs/learn/api-controller/getting-started-with-wso2-api-controller.md

From APIM 3.2.0 onward ability to specify the token type of an Application as either Opaque or JWT is removed. All new Apps will only support JWT tokens. Therefore we need to remove the apictl flag set --token-type that allows setting the token type is either Opaque or JWT, as it is redundant. Therefore in order to reflect that changes on API Controller documentation, this PR will remove parts related to this flag.
Fixes doc changes related to https://github.com/wso2/product-apim-tooling/issues/440

Remove set token type related Docs

---

en/docs/install-and-setup/upgrading-wso2-api-manager/upgrading-from-200-to-320.md
en/docs/install-and-setup/upgrading-wso2-api-manager/upgrading-from-210-to-320.md
en/docs/install-and-setup/upgrading-wso2-api-manager/upgrading-from-220-to-320.md
en/docs/install-and-setup/upgrading-wso2-api-manager/upgrading-from-250-to-320.md
en/docs/install-and-setup/upgrading-wso2-api-manager/upgrading-from-260-to-320.md
en/docs/install-and-setup/upgrading-wso2-api-manager/upgrading-from-300-to-320.md
en/docs/install-and-setup/upgrading-wso2-api-manager/upgrading-from-310-to-320.md

When the DB Script for PostgreSQL has been run, the following error occurred.
The same issue is happening with MSSQL as well.
Correct the DB scripts related to AM_DB which should be run during the migration process (APIM 2.x to APIM 3.2.0 and APIM 3.x to APIM 3.2.0).
Replaced the double quotes in the particular statement with single quotes.
- https://github.com/wso2-extensions/apim-migration-resources/pull/43
- https://github.com/wso2/product-apim/issues/8668
DBs: PostgreSQL, MSSQL

Replacing double quotes with single quotes in MSSQL and PostgreSQL DB Scripts in migration docs

---

en/docs/install-and-setup/setup/security/enabling-java-security-manager.md

Removing the unnecessary warning from 3.1.0 doc space

Removing java security manager warning

---

en/docs/install-and-setup/upgrading-wso2-api-manager/upgrading-from-220-to-320.md
en/docs/install-and-setup/upgrading-wso2-api-manager/upgrading-from-250-to-320.md
en/docs/install-and-setup/upgrading-wso2-api-manager/upgrading-from-260-to-320.md

In API Manager 3.x versions, it is required to use a certificate with the RSA key size greater than 2048. When migrating from 2.x versions issues can be arisen if you do not configure your key stores properly.
Adding the missing documentation on correctly configuring key stores when migrating from 2.x versions to 3.x versions.
- As shown in the above screenshot, the content was added to the missing documentation pages listed below.
- APIM 2.2.0 to APIM 3.2.0
- APIM 2.5.0 to APIM 3.2.0
- APIM 2.6.0 to APIM 3.2.0
- Users can configure the key stores properly when migrating and the issues will not arise.
> List any other related PRs

Adding the missing content on configuring keystores in migration from 2.x versions

---

en/docs/install-and-setup/upgrading-wso2-api-manager/upgrading-from-220-to-300.md
en/docs/install-and-setup/upgrading-wso2-api-manager/upgrading-from-250-to-300.md
en/docs/install-and-setup/upgrading-wso2-api-manager/upgrading-from-260-to-300.md

In API Manager 3.x versions, it is required to use a certificate with the RSA key size greater than 2048. When migrating from 2.x versions issues can be arisen if you do not configure your key stores properly.
Adding the missing documentation on correctly configuring key stores when migrating from 2.x versions to 3.x versions.
- As shown in the above screenshot, the content was added to the missing documentation pages listed below.
- APIM 2.2.0 to APIM 3.0.0
- APIM 2.5.0 to APIM 3.0.0
- APIM 2.6.0 to APIM 3.0.0
- Users can configure the key stores properly when migrating and the issues will not arise.
> List any other related PRs

[3.0.0] Adding the missing content on configuring keystores in migration from 2.x versions

---

en/docs/install-and-setup/upgrading-wso2-api-manager/upgrading-from-220-to-310.md
en/docs/install-and-setup/upgrading-wso2-api-manager/upgrading-from-250-to-310.md
en/docs/install-and-setup/upgrading-wso2-api-manager/upgrading-from-260-to-310.md

In API Manager 3.x versions, it is required to use a certificate with the RSA key size greater than 2048. When migrating from 2.x versions issues can be arisen if you do not configure your key stores properly.
Adding the missing documentation on correctly configuring key stores when migrating from 2.x versions to 3.x versions.
- As shown in the above screenshot, the content was added to the missing documentation pages listed below.
- APIM 2.2.0 to APIM 3.1.0
- APIM 2.5.0 to APIM 3.1.0
- APIM 2.6.0 to APIM 3.1.0
- Users can configure the key stores properly when migrating and the issues will not arise.
> List any other related PRs

[3.1.0] Adding the missing content on configuring keystores in migration from 2.x versions

---

en/docs/install-and-setup/upgrading-wso2-api-manager/upgrading-from-200-to-320.md
en/docs/install-and-setup/upgrading-wso2-api-manager/upgrading-from-210-to-320.md
en/docs/install-and-setup/upgrading-wso2-api-manager/upgrading-from-220-to-320.md
en/docs/install-and-setup/upgrading-wso2-api-manager/upgrading-from-250-to-320.md
en/docs/install-and-setup/upgrading-wso2-api-manager/upgrading-from-260-to-320.md
en/docs/install-and-setup/upgrading-wso2-api-manager/upgrading-from-300-to-320.md
en/docs/install-and-setup/upgrading-wso2-api-manager/upgrading-from-310-to-320.md

Fixes: https://github.com/wso2/product-apim/issues/9088
Make the table name idn_oauth2_resource_scope lowercase in PostgreSQL scripts in migration doc content.
Convert **tc.table_name = 'IDN_OAUTH2_RESOURCE_SCOPE'** to  **tc.table_name = 'idn_oauth2_resource_scope'** in PostgreSQL migration db scripts.
PostgreSQL 12.3

Making table name IDN_OAUTH2_RESOURCE_SCOPE lowercase in PostgreSQL migration scripts

---

en/docs/learn/api-controller/getting-started-with-wso2-api-controller.md

Correcting the APICTL version in the **warn** message about adjusting the main_config.yaml as per the old configurations.
Avoid the confusions of the users which may arise because of the version in the doc, since this change has been done from 3.1.0.
Corrected the version of APICTL to 3.2.0 in the **Getting Started with WSO2 API Controller** as below.

Correcting the APICTL version in the warn message about main_config.yaml in "Getting Started with WSO2 API Controller"

---

en/docs/develop/customizations/customizing-the-developer-portal/customize-api-listing/api-category-based-grouping.md

Removing the subsection named **Add an API Category using the Admin REST API** in the page **API Category based Grouping**
Since we have the REST API docs for Admin v1 now, removing the unnecessary content related to **API Category based Grouping**.
- Earlier there was a section as below in the **API Category based Grouping** page.
- Removed it and modified the content as below asking to refer the REST API docs.
Users can refer the new Admin v1 REST API docs when creating API categories.

Removing the section on "Add an API Category using the Admin REST API"

---

en/docs/develop/extending-api-manager/saml2-sso/configuring-external-idp-through-identity-server-for-sso.md
en/mkdocs.yml

There is a broken link in [1].
Changing the broken link in [1].
- Changed **Configuring WSO2 API Manager apps as SAML 2.0 SSO service providers** to **Configuring Identity Server as IDP for SSO** in [1].
- Updated the broken link to point to [2].
- Improved the title **Configuring Identity Server as IDP for SSO** in mkdocs.yaml.
[1] https://apim.docs.wso2.com/en/next/develop/extending-api-manager/saml2-sso/configuring-external-idp-through-identity-server-for-sso/
[2] https://apim.docs.wso2.com/en/next/develop/extending-api-manager/saml2-sso/configuring-identity-server-as-idp-for-sso/

Modifying a broken link in SAML2 SSO documentation

---

en/docs/install-and-setup/setup/security/user-account-management.md

In **User Account Management** documentation, it states an error message will be shown as below.
But it is not displayed anymore. Instead, If you have configured the email sending module and if the particular locked user's email address is correct in his profile, he/she will receive an email stating that the account is locked.
Mention the correct behaviour when locking a user account.
- Removed the below content which was in the docs previously.
- Added the below content instead of the above content.

Updating the correct behaviour which happens when locking a user account

---

en/docs/install-and-setup/setup/setting-up-databases/changing-default-databases/changing-to-ibm-db2.md
en/docs/install-and-setup/setup/setting-up-databases/changing-default-databases/changing-to-mssql.md
en/docs/install-and-setup/setup/setting-up-databases/changing-default-databases/changing-to-mysql.md
en/docs/install-and-setup/setup/setting-up-databases/changing-default-databases/changing-to-oracle-rac.md
en/docs/install-and-setup/setup/setting-up-databases/changing-default-databases/changing-to-oracle.md
en/docs/install-and-setup/setup/setting-up-databases/changing-default-databases/changing-to-postgresql.md

There are some customers that have internal policies like not to use H2. They have to change the carbon database in those situations. Even this is a rare case docs should have this.
Old doc space has steps to change the WSO2CARBON_DB. Since it is missing in the new docs, those will be added in a summarized way here.
Added the content on **Changing WSO2CARBON_DB to <Database Type>** for all the databases. Below is a screenshot for MySQL.
The users who want to change the default carbon database to a particular database type of their choice can refer to this doc content.

Adding the content to change the default WSO2CARBON_DB to a particular database type

---

en/docs/learn/api-controller/getting-started-with-wso2-api-controller.md

Changing a small error in Note message at the section of  **Add an Environment** in Getting Started with WSO2 API Controller page.

Change Note message in Add an Environment section in Getting Started with WSO2 API Controller

---

en/docs/develop/product-apis/devportal-apis/devportal-v1/devportal-v1.yaml

This PR fixes the following issues
- The GET​/throttling-policies​/{policyLevel}​/{policyId} resource, the policy name(ie: Bronze) is referred by policyID
- POST​/subscriptions and POST​/subscriptions​/multiple resource payloads are consisted of read-only parameters

Fixing payload issues in rest api docs

---

en/docs/learn/design-api/advanced-topics/enabling-cors-for-apis.md

> Discription statement in the document about Swagger extension for CORS seems to say "response caching" instead of "CORS"
> Fixed the corresponding statement to reflect "CORS" instead of "response caching"

Fixed description of supported Swagger extension for CORS

---

en/docs/learn/api-controller/advanced-topics/configuring-environment-specific-parameters.md

Add documentation changes for the feature of supporting correctly import endpoint certificates and Mutual SSL certificates using the api_params.yaml file.
Fixes https://github.com/wso2/product-apim-tooling/issues/485 for the master branch in docs
**Screenshots after the changes are made.**
You can enable Mutual SSL security by importing certificates as shown in the below example api_params.yaml file.
```
environments:
- name: dev
endpoints:
production:
sandbox:
- name: production
endpoints:
production:
sandbox:
mutualSslCerts:
- tierName: Unlimited
alias: Alice
path: /home/myname/Documents/Work/certificates/alice.crt
- tierName: Gold
alias: Bob
path: /home/myname/Documents/Work/certificates/bob.crt
```
After the API is imported to the APIM (3.2.0) the mutualssl certificates will be shown …

[Docs] [Master] Doc changes for importing Mutual SSL certificates using api_params.yaml file

---

en/docs/learn/api-controller/advanced-topics/configuring-environment-specific-parameters.md

Add documentation changes for the feature of supporting correctly import endpoint certificates and Mutual SSL certificates using the api_params.yaml file.
Fixes https://github.com/wso2/product-apim-tooling/issues/485 for the 3.2.0 branch in docs
**Screenshots after the changes are made.**
You can enable Mutual SSL security by importing certificates as shown in the below example api_params.yaml file.
```
environments:
- name: dev
endpoints:
production:
sandbox:
- name: production
endpoints:
production:
sandbox:
mutualSslCerts:
- tierName: Unlimited
alias: Alice
path: /home/myname/Documents/Work/certificates/alice.crt
- tierName: Gold
alias: Bob
path: /home/myname/Documents/Work/certificates/bob.crt
```
After the API is imported to the APIM (3.2.0) the mutualssl certificates will be shown …

[Docs] [3.2.0] Doc changes for importing Mutual SSL certificates using api_params.yaml file

---

en/docs/administer/logging-and-monitoring/monitoring/working-with-observability.md

The term DB_CALL should actually be jdbc.
Fixes https://github.com/wso2/docs-apim/issues/1988

Fix incorrect wording for jdbc log filtering

---

en/docs/administer/key-managers/configure-okta-connector.md

Adding a missing Tip when configuration OKTA as key manager. 
Include a section in the documentation explaining that, a user just has to provide the authorization URL extracted from octa application as the well-known endpoint then, Click import to fill the required information (should fix, Step 2 - Configure WSO2 API Manager -> b)
Fixes https://github.com/wso2/product-apim/issues/9332 
fixes https://github.com/wso2/docs-apim/issues/2111
(For master branch)
Configuring Okta as key manager

[Docs][Master] Adding a missing Tip when configuring Okta as Keymanager

---

en/docs/learn/design-api/publish-api/publish-an-api-to-a-cloud-cluster-in-privatejet-mode.md

This PR will include:
- Adding the architecture diagram image.
- Modifying the Enabling PrivateJet Mode for Microgateways and Securing APIs deployed in cloud clusters redirecting links.
-  Adding the image with an API that is in the CREATED state.
- Adding the architecture diagram image.
- Modifying the Enabling PrivateJet Mode for Microgateways and Securing APIs deployed in cloud clusters redirecting links.
-  Adding the image with an API that is in the CREATED state.

[Doc][Master] Modify docs for publish API to a cloud cluster in private jet mode

---

en/docs/reference/config-catalog.md

Adding the multi-tenancy related configurations to the config catalog in the docs.
Fixes #1276 for the 3.2.0 branch in docs.
https://github.com/wso2/docs-apim/pull/2022

[Docs] [3.2.0] Adding multi-tenancy properties to config catalog 

---

en/docs/learn/design-api/publish-api/publish-an-api-to-a-cloud-cluster-in-privatejet-mode.md

This PR will include:
- Adding the architecture diagram image.
- Modifying the Enabling PrivateJet Mode for Microgateways and Securing APIs deployed in cloud clusters redirecting links.
- Adding the image with an API that is in the CREATED state.
- Adding the architecture diagram image.
- Modifying the Enabling PrivateJet Mode for Microgateways and Securing APIs deployed in cloud clusters redirecting links.
- Adding the image with an API that is in the CREATED state.

[Doc] [3.2.0] Modify docs for publish API to a cloud cluster in private jet mode

---

en/docs/install-and-setup/setup/reference/default-product-ports.md

Fixes https://github.com/wso2/docs-apim/issues/1429. Removes the information on ports used in other WSO2 products.

[3.2.0] Update the documentation on default ports.

---

en/docs/assets/attachments/install-and-setup/apim200_to_apim300_gateway_artifact_migrator.sh

Following change(1 to 2) was required for the script to work in Linux based environments
[1] find . -wholename './[0-9]*/synapse-configs/default/*.xml' -print0 -o -name '*.xml' -print0 | xargs -0 **sed -i -e** 's/org.wso2.carbon.apimgt.usage.publisher.APIMgtThrottleUsageHandler/org.wso2.carbon.apimgt.gateway.handlers.analytics.APIMgtThrottleUsageHandler/'
[2] find . -wholename './[0-9]*/synapse-configs/default/*.xml' -print0 -o -name '*.xml' -print0 | xargs -0 **perl -i -pe**'s/org.wso2.carbon.apimgt.usage.publisher.APIMgtThrottleUsageHandler/org.wso2.carbon.apimgt.gateway.handlers.analytics.APIMgtThrottleUsageHandler/'

Updated migration script

---

en/docs/learn/api-controller/getting-started-with-wso2-api-controller.md

Fixes: https://github.com/wso2/product-apim-tooling/issues/517
Correct the apictl set --mode command
- Modify the command "apictl set mode <mode>" to "apictl set --mode <mode>"
Users can refer the correct command to set the mode.

[3.2.0] Modifying the documentation on apictl set --mode command

---

en/docs/learn/api-controller/getting-started-with-wso2-api-controller.md

Fixes: https://github.com/wso2/product-apim-tooling/issues/517
Correct the apictl set --mode command
- Modify the command "apictl set mode <mode>" to "apictl set --mode <mode>"
Users can refer the correct command to set the mode.

[3.1.0] Modifying the documentation on apictl set --mode command

---

en/docs/learn/api-controller/getting-started-with-wso2-api-controller.md

Fixes: https://github.com/wso2/product-apim-tooling/issues/517
Correct the apictl set --mode command
- Modify the command "apictl set mode <mode>" to "apictl set --mode <mode>"
Users can refer the correct command to set the mode.

[3.0.0] Modifying the documentation on apictl set --mode command 

---

en/docs/getting-started/quick-start-guide.md
en/docs/learn/api-controller/advanced-topics/configuring-environment-specific-parameters.md
en/docs/learn/api-controller/advanced-topics/creating-custom-users-to-perform-api-controller-operations.md
en/docs/learn/api-controller/advanced-topics/using-dynamic-data-in-api-controller-projects.md
en/docs/learn/api-controller/building-jenkins-ci-cd-pipeline-for-dev-first-approach.md
en/docs/learn/api-controller/ci-cd-with-wso2-api-management.md
en/docs/learn/api-controller/getting-started-with-wso2-api-controller.md
en/docs/learn/api-controller/importing-apis-via-dev-first-approach.md
en/docs/learn/api-controller/migrating-api-products-to-different-environments.md
en/docs/learn/api-controller/migrating-apis-to-different-environments.md
en/docs/learn/api-controller/migrating-applications-to-different-environments.md

Fixes: https://github.com/wso2/product-apim-tooling/issues/516
Fixes: https://github.com/wso2/product-apim-tooling/issues/517
Fixes: https://github.com/wso2/product-apim-tooling/issues/519
Modifying the docs with the correct revamped API Controller commands and examples.
- Changed all the revamped commands in the below pages.
- Getting Started with WSO2 API Controller
- Importing APIs Via Dev First Approach
- Migrating APIs to Different Environments
- Migrating Apps to Different Environments
- CI/CD with WSO2 API Manager
- Building a Jenkins CI/CD Pipeline for Dev First Approach
- Creating Custom Users to Perform API Controller Operations
- Configuring Environment Specific Parameters
- Using Dynamic Data in API Controller Projects
- Added notes like below to all the revamped and …

Modifying the documentation with the revamped commands of the API Controller

---

en/docs/learn/api-controller/getting-started-with-wso2-api-controller.md
en/docs/learn/api-controller/migrating-api-products-to-different-environments.md

Fixes: https://github.com/wso2/product-apim-tooling/issues/519
Correct the examples of the **import api-product** API Controller command
- Changed the examples with **import-api** to "import api-product" as below.
- Corrected the flag description of add-env command.
Earlier:
Now: 
Users can refer the correct examples of the **import api-product** command.

[3.2.0] Correcting the examples of 'apictl import api-product' command

---

en/docs/learn/design-api/api-versioning/enabling-notifications.md

Fixes https://github.com/wso2/docs-apim/issues/1545. The default deployment.toml has following commented configs:
``` toml
#[apim.notification]
#from_address = "APIM.com"
#username = "APIM"
#password = "APIM+123"
#hostname = "localhost"
#port = 3025
#enable_start_tls = false
#enable_authentication = true
```
Since we have key-mappings - [1], we can use the above to enable notifications.
[1] https://github.com/wso2/product-apim/blob/v3.1.0/modules/distribution/product/src/main/resources/conf/key-mappings.json#L95-L101

[3.1.0] Modify the configuration to enable notifications

---

en/docs/install-and-setup/setup/setting-up-databases/changing-default-databases/changing-to-mysql.md

This PR adds notes about the requirement of primary keys when using group replication in MySQL and using NDB engine.
Related to https://github.com/wso2/product-apim/issues/9505

[3.2.0] Add note to support group replication

---

en/docs/administer/logging-and-monitoring/logging/masking-sensitive-information-in-logs.md
en/mkdocs.yml

This PR adds docs for masking logs in APIM 3.2.0.
As mentioned in https://github.com/wso2/product-apim/issues/9377, log masking is not enabled by default in APIM. The docs have been updated on how to manually enable log masking.
Related doc issue: https://github.com/wso2/docs-apim/issues/1606

[3.2.0] Add docs for masking logs

---

en/docs/develop/customizations/customizing-the-developer-portal/overriding-developer-portal-theme.md

Update the publisher theming documentation with `userTheme.js` details
- [Link](https://apim.docs.wso2.com/en/latest/develop/customizations/customizing-the-developer-portal/overriding-developer-portal-theme/#publisher)
-When migrating from 3.1.0, Need to copy the 
```
<API-M_HOME>/repository/deployment/server/jaggeryapps/publisher/site/public/theme/defaultTheme.js
```
content into 
```
<API-M_HOME>/repository/deployment/server/jaggeryapps/publisher/site/public/conf/userThemes.js
```
file
Don't miss the docs when changing the implementation 👨‍🎨

Update theming docs

---

en/docs/learn/design-api/api-versioning/enabling-notifications.md
en/docs/reference/config-catalog.md
en/docs/reference/configs.json
en/tools/config-catalog-generator/data/apim.notification.toml
en/tools/config-catalog-generator/data/configs.json
en/tools/config-catalog-generator/dist/config-catalog.md

This PR updates the master docs related to notification enabling. 
Configs updated referring to https://is.docs.wso2.com/en/latest/setup/configuring-email-sending/#configuring-the-email-sending-module
Related doc issue: https://github.com/wso2/docs-apim/issues/2376

[master] Update docs for notification enabling

---

en/docs/learn/api-security/oauth2/oauth2-scopes/scope-allowlisting.md

> The configurations for allowed scopes is changed as the above config have been moved to identity.xml from api-mgt.xml. The above change is done to move the implementation of allowlisting the scopes to identity component level.

Updated  config for allowed scopes

---

en/docs/learn/design-api/api-versioning/enabling-notifications.md
en/docs/reference/config-catalog.md
en/docs/reference/configs.json
en/tools/config-catalog-generator/data/apim.notification.toml
en/tools/config-catalog-generator/data/configs.json
en/tools/config-catalog-generator/dist/config-catalog.md

This PR updates the docs related to notification enabling in APIM 3.2.0.
Related doc issue: https://github.com/wso2/docs-apim/issues/2376

[3.2.0] Update docs for notification enabling

---

en/docs/install-and-setup/setting-up-databases/changing-default-databases/changing-to-mysql.md

This PR adds notes about the requirement of primary keys when using group replication in MySQL and using NDB engine.
Related to https://github.com/wso2/product-apim/issues/9505

[3.0.0] Add note to support group replication

---

en/docs/install-and-setup/setup/setting-up-databases/changing-default-databases/changing-to-mysql.md

This PR adds notes about the requirement of primary keys when using group replication in MySQL and using NDB engine.
Related to https://github.com/wso2/product-apim/issues/9505

[3.1.0] Add note to support group replication

---

en/docs/develop/customizations/customizing-the-developer-portal/advanced-customization.md

Initial two steps for building the customizations were missing in the documentation
Related 3.2.0 PR https://github.com/wso2/docs-apim/pull/2255
Update the UI customization steps for portal apps
- Doc [link](https://apim.docs.wso2.com/en/latest/develop/customizations/customizing-the-developer-portal/advanced-customization/#advanced-customization)
- Followed secure coding standards in http://wso2.com/technical-reports/wso2-secure-engineering-guidelines? yes/~no~
- Confirmed that this PR doesn't commit any keys, passwords, tokens, usernames, or other secrets? yes/~no~

Add missing initial steps when building customisations

---

en/docs/install-and-setup/setup/deployment-best-practices/security-guidelines-for-production-deployment.md

This PR adds production deployment related security guidelines for admin accounts.
Related doc issue: https://github.com/wso2/docs-apim/issues/2446

[3.2.0] Add security guidelines for admin accounts

---

en/docs/install-and-setup/setup/deployment-best-practices/security-guidelines-for-production-deployment.md

This PR adds production deployment related security guidelines for admin accounts.
Related doc issue: https://github.com/wso2/docs-apim/issues/2446

[3.1.0] Add security guidelines for admin accounts

---

en/docs/install-and-setup/setup/reference/supported-cipher-suites.md
en/mkdocs.yml

> Move supported cipher suites document under APIM doc space
Related issue - https://github.com/wso2/docs-apim/issues/2025

Move supported cipher suites document under APIM doc space

---

en/docs/administer/managing-users-and-roles/managing-user-roles.md
en/docs/learn/api-security/oauth2/oauth2-scopes/fine-grained-access-control-with-oauth-scopes.md

With the recent decision to not deprecating local scopes, this PR updates the relevant documentaion.
Fix https://github.com/wso2/docs-apim/issues/2481

Remove deprecated note for local scopes

---

en/docs/install-and-setup/setup/api-controller/advanced-topics/using-dynamic-data-in-api-controller-projects.md
en/docs/install-and-setup/setup/api-controller/building-jenkins-ci-cd-pipeline-for-dev-first-approach.md
en/docs/install-and-setup/setup/api-controller/ci-cd-with-wso2-api-management.md
en/docs/install-and-setup/setup/api-controller/getting-started-with-wso2-api-controller.md
en/docs/install-and-setup/setup/api-controller/importing-apis-via-dev-first-approach.md
en/docs/install-and-setup/setup/api-controller/migrating-api-products-to-different-environments.md
en/docs/install-and-setup/setup/api-controller/migrating-apis-to-different-environments.md

Fixes: https://github.com/wso2/product-apim-tooling/issues/544
Update the new file structure and the schema structures of APIs and API Products in the documentation.
- Updated the page **Importing APIs Via Dev First Approach**.
- Updated the page **Migrating APIs to Different Environments**.
- Updated the page **Migrating API Products (with or without dependent APIs) to Different Environments**.
- Updated the page **Using Dynamic Data in API Controller Projects**.
- Updated the APICTL and APIM version to 4.0.0 in the APICTL documentation
- Removed warnings about preserving security credentials when exporting an API, since there are no restrictions from 4.0.0 onwards.
Users can refer to the documentation to have an understanding of the new folder structure and the schema definitions …

Updating the file structure and schemas of APIs and API Products in APICTL documentation

---

en/docs/learn/api-controller/ci-cd-with-wso2-api-management.md
en/docs/learn/api-controller/getting-started-with-wso2-api-controller.md

1. Update the API controller CI/CD example API definition with new OpenAPI 3.0 definition.
2. Adding the missing keyword in the add-env example  in /learn/api-controller/getting-started-with-wso2-api-controller/ page
Fixes #1568 
**Update the API controller CI/CD example API definition with new OpenAPI 3.0 definition.**
**Update the add-env example in getting started page with a missing keyword**

[Docs][3.2.0] Fix for #1568 

---

en/docs/install-and-setup/setup/api-controller/ci-cd-with-wso2-api-management.md
en/docs/install-and-setup/setup/api-controller/getting-started-with-wso2-api-controller.md

1. Update the API controller CI/CD example API definition with new OpenAPI 3.0 definition.
2. Adding the missing keyword in the add-env example  in /learn/api-controller/getting-started-with-wso2-api-controller/ page
Fixes #1568 for master branch
**Update the API controller CI/CD example API definition with new OpenAPI 3.0 definition.**
**Update the add-env example in getting started page with a missing keyword**

[Docs][Master] Fix for #1568 (Update the API controller CI/CD example API definition with new OpenAPI 3.0 definition.)

---

en/docs/install-and-setup/setting-up-databases/changing-default-databases/changing-to-mysql.md

> Update the wrong DB names in samples. 
> Update regadmin name to shareadmin.
> Change the grants to correct DB, Grant are given to regdb even though the new databases are apim_db and shared_db.
> 
Issue : https://github.com/wso2/docs-apim/issues/1627
https://github.com/wso2/docs-apim/issues/1626
Doc page : https://apim.docs.wso2.com/en/latest/install-and-setup/setup/setting-up-databases/changing-default-databases/changing-to-mysql/#changing-to-mysql

Update the Grants with correct DBs and usernames

---

en/docs/learn/api-controller/getting-started-with-wso2-api-controller.md
en/docs/learn/api-controller/importing-apis-via-dev-first-approach.md

Fixes: https://github.com/wso2/docs-apim/issues/1886
Reducing the confusions that may arise due to https://github.com/wso2/docs-apim/pull/1891
- Made the description of change-status API command to make it less verbose
- Simplified the description on --definition flag on apictl init command with the relevant example for api.yaml
https://github.com/wso2/docs-apim/pull/1891

[3.2.0] Simplify the description of the sample API definition in APICTL docs

---

en/docs/learn/api-controller/getting-started-with-wso2-api-controller.md
en/docs/learn/api-controller/importing-apis-via-dev-first-approach.md

Fixes: https://github.com/wso2/docs-apim/issues/1886
Backporting https://github.com/wso2/docs-apim/pull/1891
- Fixed minor issues in the pages **Getting Started with WSO2 API Controller** and **Importing APIs Via Dev First Approach**.
- Added a sample api.yaml to be used as the definition for **apictl init** command.
https://github.com/wso2/docs-apim/pull/1891

[3.1.0] Add sample api.yaml to use as the definition for apictl init and fix minor issues

---

en/docs/learn/api-controller/getting-started-with-wso2-api-controller.md
en/docs/learn/api-controller/importing-apis-via-dev-first-approach.md

Fixes: https://github.com/wso2/docs-apim/issues/1886
Backporting https://github.com/wso2/docs-apim/pull/1891
- Fixed minor issues in the pages **Getting Started with WSO2 API Controller** and **Importing APIs Via Dev First Approach**.
- Added a sample api.yaml to be used as the definition for **apictl init** command.
https://github.com/wso2/docs-apim/pull/1891

[3.0.0] Add sample api.yaml to use as the definition for apictl init and fix minor issues

---

en/docs/publish/api-gateway/passing-end-user-attributes-to-the-backend/passing-enduser-attributes-to-the-backend-using-jwt.md

Fixes: https://github.com/wso2/docs-apim/issues/2499
Add content on Additional Claims to JWT
Added a note to the end of the page titled **Passing Enduser Attributes to the Backend Using JWT** as shown below.

Adding content on Additional Claims to JWT

---

en/docs/learn/api-gateway/passing-end-user-attributes-to-the-backend/passing-enduser-attributes-to-the-backend-using-jwt.md

Fixes: https://github.com/wso2/docs-apim/issues/2499
Add content on Additional Claims to JWT
Added a note to the end of the page titled **Passing Enduser Attributes to the Backend Using JWT** as shown below.

[3.0.0] Adding content on Additional Claims to JWT

---

en/docs/learn/api-gateway/passing-end-user-attributes-to-the-backend/passing-enduser-attributes-to-the-backend-using-jwt.md

Fixes: https://github.com/wso2/docs-apim/issues/2499
Add content on Additional Claims to JWT
Added a note to the end of the page titled **Passing Enduser Attributes to the Backend Using JWT** as shown below.

[3.1.0] Adding content on Additional Claims to JWT

---

en/docs/learn/api-gateway/passing-end-user-attributes-to-the-backend/passing-enduser-attributes-to-the-backend-using-jwt.md

Fixes: https://github.com/wso2/docs-apim/issues/2499
Add content on Additional Claims to JWT
Added a note to the end of the page titled **Passing Enduser Attributes to the Backend Using JWT** as shown below.

[3.2.0] Adding content on Additional Claims to JWT

---

en/docs/learn/rate-limiting/blacklisting-whitelisting.md

Fixes: https://github.com/wso2/docs-apim/issues/1200
Removing the link to Custom throttling since docs do not contain any details about it.
Remove the **Custom Throttling** link from **Blacklisting and Whitelisting Requests** page.

[3.1.0] Removing custom throttling link

---

en/docs/learn/rate-limiting/blacklisting-whitelisting.md

Fixes: https://github.com/wso2/docs-apim/issues/1200
Removing the link to Custom throttling since docs do not contain any details about it.
Remove the **Custom Throttling** link from **Blacklisting and Whitelisting Requests** page.

[3.0.0] Removing custom throttling link

---

en/docs/develop/customizations/adding-a-user-signup-workflow.md

- This PR fixes #2130
- Add a note providing steps that need to be performed when there are multiple tenants.
- Corrects "Register now" image

[3.1.0] Add required steps when enabling user signup workflow for multi tenants

---

en/docs/learn/consume-api/customizations/adding-a-user-signup-workflow.md

- This PR fixes #2130
- Add a note providing steps that need to be performed when there are multiple tenants.
- Corrects "Register now" image

[3.0.0] Add required steps when enabling user signup workflow for multi tenants 

---

en/docs/learn/consume-api/invoke-apis/invoke-apis-using-tools/invoke-an-api-using-the-integrated-api-console.md

Fixes: https://github.com/wso2/docs-apim/issues/2092
Change content with Swagger to OpenAPI specification.

[3.2.0] Change referring swagger instead of OAS

---

en/docs/learn/consume-api/invoke-apis/invoke-apis-using-tools/invoke-an-api-using-the-integrated-api-console.md

Fixes: https://github.com/wso2/docs-apim/issues/2092
Change content with Swagger to OpenAPI specification.

[3.1.0] Change referring swagger instead of OAS

---

en/docs/learn/consume-api/invoke-apis/invoke-apis-using-tools/invoke-an-api-using-the-integrated-api-console.md

Fixes: https://github.com/wso2/docs-apim/issues/2092
Change content with Swagger to OpenAPI specification.

[3.0.0] Change referring swagger instead of OAS

---

en/docs/install-and-setup/setting-up-databases/changing-default-databases/changing-to-ibm-db2.md
en/docs/install-and-setup/setting-up-databases/changing-default-databases/changing-to-mssql.md
en/docs/install-and-setup/setting-up-databases/changing-default-databases/changing-to-oracle-rac.md
en/docs/install-and-setup/setting-up-databases/changing-default-databases/changing-to-oracle.md
en/docs/install-and-setup/setting-up-databases/changing-default-databases/changing-to-postgresql.md

> regadmin user is used for shared_db. As shared_db contains registry and user db, make sense to change this as sharedadmin.
Issue : https://github.com/wso2/docs-apim/issues/2570

Change regadmin to sharedadmin

---

en/docs/install-and-setup/setup/setting-up-databases/changing-default-databases/changing-to-ibm-db2.md
en/docs/install-and-setup/setup/setting-up-databases/changing-default-databases/changing-to-mssql.md
en/docs/install-and-setup/setup/setting-up-databases/changing-default-databases/changing-to-oracle-rac.md
en/docs/install-and-setup/setup/setting-up-databases/changing-default-databases/changing-to-oracle.md
en/docs/install-and-setup/setup/setting-up-databases/changing-default-databases/changing-to-postgresql.md

> regadmin user is used for shared_db. As shared_db contains registry and user db, make sense to change this as sharedadmin.
Issue : https://github.com/wso2/docs-apim/issues/2570

Change regadmin as sharedadmin

---

en/docs/install-and-setup/setup/setting-up-databases/changing-default-databases/changing-to-ibm-db2.md
en/docs/install-and-setup/setup/setting-up-databases/changing-default-databases/changing-to-mssql.md
en/docs/install-and-setup/setup/setting-up-databases/changing-default-databases/changing-to-oracle-rac.md
en/docs/install-and-setup/setup/setting-up-databases/changing-default-databases/changing-to-oracle.md
en/docs/install-and-setup/setup/setting-up-databases/changing-default-databases/changing-to-postgresql.md

> regadmin user is used for shared_db. As shared_db contains registry and user db, make sense to change this as sharedadmin.
Issue : https://github.com/wso2/docs-apim/issues/2570

Update regadmin as sharedadmin

---

en/docs/learn/consume-api/discover-apis/search.md

Fixing issue https://github.com/wso2/docs-apim/issues/2288

Fixing - Default search in publisher and devportal is not the API name search

---

en/docs/install-and-setup/setup/distributed-deployment/synchronizing-artifacts-in-a-gateway-cluster.md

> As rsync is no longer in use, after discussion decided to remove **Artifact synchronization with rsync** section.
Issue : https://github.com/wso2/docs-apim/issues/2699

Remove Artifact synchronization with rsync section

---

en/docs/install-and-setup/setup/distributed-deployment/synchronizing-artifacts-in-a-gateway-cluster.md

> As rsync is no longer in use, after discussion decided to remove **Artifact synchronization with rsync** section.
Issue : https://github.com/wso2/docs-apim/issues/2699

Remove 'Artifact synchronization with rsync' section

---

en/docs/learn/user-account-management/change-dev-portal-password.md

- This PR fixes #2249
- Adds the documentation section for disabling "Change Password for the Developer Portal ".

[3.2.0] Add Disable Change Password for dev portal Configuration

---

en/docs/learn/api-security/oauth2/oauth2-scopes/fine-grained-access-control-with-oauth-scopes.md

Add a note on the system property to disable relo validation at scope creation.

fix docs-apim/issues/1927

---

en/docs/publish/api-gateway/mutual-ssl-between-api-gateway-and-backend.md

Fixes: https://github.com/wso2/docs-apim/issues/2313
Fixes: https://github.com/wso2/docs-apim/issues/1635
Updating the configs on enable loading dynamic MutualSSL profiles
Replaced the config which was asked to be done in axis2.xml file with the correct configurations to be done on **deployment.toml** file on the page **Mutual SSL Between API Gateway and Backend**. Refer below for the updated config.

Adding/Updating the configs on enable loading dynamic MutualSSL profiles

---

en/docs/learn/api-gateway/mutual-ssl-between-api-gateway-and-backend.md

Fixes: https://github.com/wso2/docs-apim/issues/2313
Fixes: https://github.com/wso2/docs-apim/issues/1635
Updating the configs on enable loading dynamic MutualSSL profiles
Replaced the config which was asked to be done in axis2.xml file with the correct configurations to be done on **deployment.toml** file on the page **Mutual SSL Between API Gateway and Backend**. Refer below for the updated config.

[3.2.0] Adding/Updating the configs on enable loading dynamic MutualSSL profiles

---

en/docs/learn/api-gateway/mutual-ssl-between-api-gateway-and-backend.md

Fixes: https://github.com/wso2/docs-apim/issues/2313
Fixes: https://github.com/wso2/docs-apim/issues/1635
Updating the configs on enable loading dynamic MutualSSL profiles
Replaced the config which was asked to be done in axis2.xml file with the correct configurations to be done on **deployment.toml** file on the page **Mutual SSL Between API Gateway and Backend**. Refer below for the updated config.
This will update the configs in APIM 3.0.0 docs as well since it is referring the same page here [1].
[1] https://apim.docs.wso2.com/en/3.0.0/administer/product-security/mutual-ssl-between-api-gateway-and-backend/#mutual-ssl-between-api-gateway-and-backend

[3.1.0] Adding/Updating the configs on enable loading dynamic MutualSSL profiles

---

en/mkdocs.yml

Removed Hazelcast ref in mkdocs to fix build break in 3.1.0

Removed Hazelcast ref in mkdocs

---

en/docs/administer/product-security/mutual-ssl-between-api-gateway-and-backend.md

Fixes: https://github.com/wso2/docs-apim/issues/2313
Fixes: https://github.com/wso2/docs-apim/issues/1635
Updating the configs on enable loading dynamic MutualSSL profiles
Replaced the config which was asked to be done in axis2.xml file with the correct configurations to be done on **deployment.toml** file on the page **Mutual SSL Between API Gateway and Backend**. Refer below for the updated config.

[3.0.0] Adding/Updating the configs on enable loading dynamic MutualSSL profiles

---

en/docs/learn/api-gateway/mutual-ssl-between-api-gateway-and-backend.md

https://apim.docs.wso2.com/en/latest/learn/api-gateway/mutual-ssl-between-api-gateway-and-backend/#mutual-ssl-between-api-gateway-and-backend
The examples attached to step 4 and step 5 have some inconsistencies. This PR will fix them.
Fixes https://github.com/wso2/docs-apim/issues/1336

[Docs] [3.2.0] Remove inconsistency in examples when configuring MutualSSL

---

en/docs/learn/api-gateway/mutual-ssl-between-api-gateway-and-backend.md

https://apim.docs.wso2.com/en/latest/learn/api-gateway/mutual-ssl-between-api-gateway-and-backend/#mutual-ssl-between-api-gateway-and-backend
The examples attached to step 4 and step 5 have some inconsistencies. This PR will fix them.
Fixes https://github.com/wso2/docs-apim/issues/1336

[Docs] [3.1.0] Remove inconsistency in examples when configuring MutualSSL

---

en/docs/administer/product-security/mutual-ssl-between-api-gateway-and-backend.md

https://apim.docs.wso2.com/en/3.0.0/administer/product-security/mutual-ssl-between-api-gateway-and-backend/
The examples attached to step 4 and step 5 have some inconsistencies. This PR will fix them.
Fixes https://github.com/wso2/docs-apim/issues/1336

[Docs] [3.0.0] Remove inconsistency in examples when configuring MutualSSL

---

en/docs/consume/user-account-management/change-dev-portal-password.md

- This PR fixes #2249
- Adds the documentation section for disabling "Change Password for the Developer Portal ".

[4.0.0] Add Disable Change Password for dev portal Configuration

---

en/docs/administer/product-security/logins-and-passwords/maintaining-logins-and-passwords.md

> Multi-attribute authentication not supported in dev portal from APIM side. Therefore removing from the doc.
Issue : https://github.com/wso2/docs-apim/issues/1813

Remove 'Sign in via multiple user attributes' section

---

en/docs/consume/invoke-apis/invoke-apis-using-tools/invoke-an-api-using-the-integrated-api-console.md

Fixes: https://github.com/wso2/docs-apim/issues/2764
Remove unnecessary description in the page **Invoke an API using the Integrated API Console**.
Removed the below description from the page **Invoke an API using the Integrated API Console**.
"The API Console generates interactive and consumer-focused documentation for API Contracts which are compliant with OpenAPI specification.
For more information, see the OpenAPI specification, version 2.0 and OpenAPI specification, version 3.0."
- Before removing
- After removing

Removing the unwanted description in "Invoke an API using the Integrated API Console" page

---

en/docs/learn/consume-api/invoke-apis/invoke-apis-using-tools/invoke-an-api-using-the-integrated-api-console.md

Fixes: https://github.com/wso2/docs-apim/issues/2764
Remove unnecessary description in the page **Invoke an API using the Integrated API Console**.
Removed the below description from the page **Invoke an API using the Integrated API Console**.
"The API Console generates interactive and consumer-focused documentation for API Contracts which are compliant with OpenAPI specification.
For more information, see the OpenAPI specification, version 2.0 and OpenAPI specification, version 3.0."
- Before removing
- After removing

[3.2.0] Removing the unwanted description in "Invoke an API using the Integrated API Console" page

---

en/docs/learn/consume-api/invoke-apis/invoke-apis-using-tools/invoke-an-api-using-the-integrated-api-console.md

Fixes: https://github.com/wso2/docs-apim/issues/2764
Remove unnecessary description in the page **Invoke an API using the Integrated API Console**.
Removed the below description from the page **Invoke an API using the Integrated API Console**.
"The API Console generates interactive and consumer-focused documentation for API Contracts which are compliant with OpenAPI specification.
For more information, see the OpenAPI specification, version 2.0 and OpenAPI specification, version 3.0."
- Before removing
- After removing

[3.1.0] Removing the unwanted description in "Invoke an API using the Integrated API Console" page

---

en/docs/learn/consume-api/invoke-apis/invoke-apis-using-tools/invoke-an-api-using-the-integrated-api-console.md

Fixes: https://github.com/wso2/docs-apim/issues/2764
Remove unnecessary description in the page **Invoke an API using the Integrated API Console**.
Removed the below description from the page **Invoke an API using the Integrated API Console**.
"The API Console generates interactive and consumer-focused documentation for API Contracts which are compliant with OpenAPI specification.
For more information, see the OpenAPI specification, version 2.0 and OpenAPI specification, version 3.0."
- Before removing
- After removing

[3.0.0] Removing the unwanted description in "Invoke an API using the Integrated API Console" page

---

en/docs/install-and-setup/setup/security/configuring-keystores/configuring-keystores-in-wso2-api-manager.md

Fixes: https://github.com/wso2/docs-apim/issues/1940
Adding details on setting up a new truststore from deployment.toml file.
Added an info tab with an example of a configuration to set up a new trustore from deployment.toml as shown below.

Adding details on configuring a trustore from deployment.toml

---

en/docs/install-and-setup/setup/security/configuring-keystores/configuring-keystores-in-wso2-api-manager.md

Fixes: https://github.com/wso2/docs-apim/issues/1940
Adding details on setting up a new truststore from deployment.toml file.
Added an info tab with an example of a configuration to set up a new trustore from deployment.toml as shown below.

[3.2.0] Adding details on configuring a trustore from deployment.toml

---

en/docs/install-and-setup/setup/security/configuring-keystores/configuring-keystores-in-wso2-api-manager.md

Fixes: https://github.com/wso2/docs-apim/issues/1940
Adding details on setting up a new truststore from deployment.toml file.
Added an info tab with an example of a configuration to set up a new trustore from deployment.toml as shown below.

[3.1.0] Adding details on configuring a trustore from deployment.toml

---

en/docs/administer/product-security/configuring-keystores/configuring-keystores-in-wso2-api-manager.md

Fixes: https://github.com/wso2/docs-apim/issues/1940
Adding details on setting up a new truststore from deployment.toml file.
Added an info tab with an example of a configuration to set up a new trustore from deployment.toml as shown below.

[3.0.0] Adding details on configuring a trustore from deployment.toml

---

en/docs/reference/vendor-extensions-catalog.md
en/mkdocs.yml

WSO2 API Manager utilizes the vendor extensions support in Open API specification [1], to store operations such as throttling, against each API.
These extensions are added with description and relevant examples as a catalog into the references section.
**x-auth-type
x-throttling-tier
x-wso2-auth-header
x-wso2-cors
x-wso2-production-endpoints
x-wso2-sandbox-endpoints
x-wso2-basePath
x-wso2-transports
x-scopes-bindings
x-scopes-mappings
x-wso2-soap
x-wso2-mutual-ssl**
**_The newly introduced page will be at the https://apim.docs.wso2.com/en/next/reference/reference/vendor-extensions-catalog location_**
Fixes https://github.com/wso2/docs-apim/issues/1623 for 3.2.0 branch

[Docs][3.2.0] Add Vendor extensions catalog 

---

en/docs/reference/vendor-extensions-catalog.md
en/mkdocs.yml

WSO2 API Manager utilizes the vendor extensions support in Open API specification [1], to store operations such as throttling, against each API.
These extensions are added with description and relevant examples as a catalog into the references section.
**x-auth-type
x-throttling-tier
x-wso2-auth-header
x-wso2-cors
x-wso2-production-endpoints
x-wso2-sandbox-endpoints
x-wso2-basePath
x-wso2-transports
x-scopes-bindings
x-scopes-mappings
x-wso2-soap
x-wso2-mutual-ssl**
**_The newly introduced page will be at the https://apim.docs.wso2.com/en/next/reference/reference/vendor-extensions-catalog location_**
Fixes https://github.com/wso2/docs-apim/issues/1623 for Mater branch

[Docs][Master] Add Vendor extensions catalog 

---

en/docs/reference/vendor-extensions-catalog.md
en/mkdocs.yml

WSO2 API Manager utilizes the vendor extensions support in Open API specification [1], to store operations such as throttling, against each API.
These extensions are added with description and relevant examples as a catalog into the references section.
**x-auth-type
x-throttling-tier
x-wso2-auth-header
x-wso2-cors
x-wso2-production-endpoints
x-wso2-sandbox-endpoints
x-wso2-basePath
x-wso2-transports
x-scopes-bindings
x-scopes-mappings
x-wso2-soap
x-wso2-mutual-ssl**
**_The newly introduced page will be at the https://apim.docs.wso2.com/en/next/reference/reference/vendor-extensions-catalog location_**
Fixes https://github.com/wso2/docs-apim/issues/1623 for 3.1.0 branch

[Docs][3.1.0] Add Vendor extensions catalog

---

en/docs/install-and-setup/setup/setting-up-proxy-server-and-the-load-balancer/configuring-the-proxy-server-and-the-load-balancer.md

Fixes: https://github.com/wso2/docs-apim/issues/1540
Backporting https://github.com/isharac/docs-apim/commit/3d7cbca19fd4f6a11567a9e9bdbf9ce6b8c395b6
Adding a new section named **Configure the dynamic callback origin** to the page **Configuring the Proxy Server and the Load Balancer** as shown below.

[3.1.0] Adding the section on "Configure the dynamic callback origin" in reverse proxy related documentation

---

en/docs/install-and-setup/deploying-wso2-api-manager/configuring-the-proxy-server-and-the-load-balancer.md

Fixes: https://github.com/wso2/docs-apim/issues/1540
Backporting https://github.com/isharac/docs-apim/commit/3d7cbca19fd4f6a11567a9e9bdbf9ce6b8c395b6
Adding a new section named **Configure the dynamic callback origin** to the page **Configuring the Proxy Server and the Load Balancer** as shown below.

[3.0.0] Adding the section on "Configure the dynamic callback origin" in reverse proxy related documentation

---

en/docs/install-and-setup/upgrading-wso2-api-manager/upgrading-from-200-to-320.md
en/docs/install-and-setup/upgrading-wso2-api-manager/upgrading-from-210-to-320.md
en/docs/install-and-setup/upgrading-wso2-api-manager/upgrading-from-220-to-320.md
en/docs/install-and-setup/upgrading-wso2-api-manager/upgrading-from-250-to-320.md
en/docs/install-and-setup/upgrading-wso2-api-manager/upgrading-from-260-to-320.md
en/docs/install-and-setup/upgrading-wso2-api-manager/upgrading-from-300-to-320.md
en/docs/install-and-setup/upgrading-wso2-api-manager/upgrading-from-310-to-320.md

>  As we are running the DB scripts against the backup Dbs it is not required to Turn off the Registry versioning in the old APIM version, these statements in the document might be confusing to the users.
> Remove 'Turning off registry versioning' steps for the old APIM version.
Issue : https://github.com/wso2/docs-apim/issues/1403

Update 'Turning off registry versioning' section with correct procedure

---

en/mkdocs.yml

Reverts wso2/docs-apim#2843
The path for 3.0.0 is incorrect. It should be 
{{base_path}}/administer/product-administration/managing-users-and-roles/managing-user-stores/configuring-the-authorization-manager

Revert "[3.0.0] Add authorization manager doc to mkdocs"

---

en/docs/troubleshooting/error-handling.md

Fixes https://github.com/wso2/docs-apim/issues/2861
To remove 900903 error code from error codes table which is no longer in use
Removed 900903 entry and updated the Example column of 900901 mentioning token expiration.

Remove obsolete 900903 error code from error codes table

---

en/docs/troubleshooting/error-handling.md

Fixes: https://github.com/wso2/docs-apim/issues/2861
To remove 900903 error code from error codes table which is no longer in use.
Removed 900903 entry and updated the Example column of 900901 mentioning token expiration.

[3.2.0] Remove obsolete 900903 error code from error codes table

---

en/docs/troubleshooting/error-handling.md

Fixes: https://github.com/wso2/docs-apim/issues/2861
To remove 900903 error code from error codes table which is no longer in use.
Removed 900903 entry and updated the Example column of 900901 mentioning token expiration.

[3.1.0] Remove obsolete 900903 error code from error codes table

---

en/docs/reference/vendor-extensions-catalog.md
en/mkdocs.yml

WSO2 API Manager utilizes the vendor extensions support in Open API specification [1], to store operations such as throttling, against each API.
These extensions are added with description and relevant examples as a catalog into the references section.
**x-auth-type
x-throttling-tier
x-wso2-auth-header
x-wso2-cors
x-wso2-production-endpoints
x-wso2-sandbox-endpoints
x-wso2-basePath
x-wso2-transports
x-scopes-bindings
x-scopes-mappings
x-wso2-mutual-ssl**
**_The newly introduced page will be at the https://apim.docs.wso2.com/en/next/reference/reference/vendor-extensions-catalog location_**
1. Fixes https://github.com/wso2/docs-apim/issues/1623 for 3.0.0 branch
2. Fixes #1477

[Docs][3.0.0] Add Vendor extensions catalog and Fixes 1477

---

en/docs/getting-started/about-this-release.md

This PR adds a note on the removal of the validity period for access tokens in the devportal and points to the docs of new configurations.
Fixes https://github.com/wso2/docs-apim/issues/2866

Include removal of validity period in Removed features and functionalities

---

en/docs/assets/attachments/install-and-setup/apim210_to_apim310_gateway_artifact_migrator_for_tenants.ps1
en/docs/assets/attachments/install-and-setup/apim220_to_apim310_gateway_artifact_migrator_for_tenants.ps1

As $subject, this removes the unwanted migration handlers in the migration scripts.

Remove unwanted migration replacements

---

en/docs/install-and-setup/setup/api-controller/migrating-applications-to-different-environments.md

The documentation should have the usage of the newly introduced flag (--format) when exporting an application. Also, there were some inconsistencies in the responses of exporting and importing an Application. Those will be fixed with this as well.
Update the --format flag usage when exporting an Application and fix inconsistencies of the responses of export/import Applications. 
- Introduced the --format flag as shown below.
- Updated the file structure of an exported Application as below.
- Updated the export response as below.
- Updated the import response as below.
Users can refer to the documentation to have an understanding of the new file structure of exported Applications and the usage of the --format flag.
- https://github.com/wso2/carbon-apimgt/pull/9533
- …

Updating the APICTL documentation on Applications Export/Import with --format flag and fixing inconsistencies

---

en/docs/install-and-setup/setup/api-controller/advanced-topics/configuring-environment-specific-parameters.md

The documentation should be added for the improvement done in [1]
The usage of **policies** field that can be used to specify the subscription level policies of an API should be added to the APICTL docs.
- Format of the api_params.yaml has been updated with the **policies** field as shown below.
- Sample api_params.yaml has been updated by adding an example for the field **policies**.
- An explanation has been added to specify the usage of the **policies** field.
- If **policies** parameter is set in api_params.yaml file, override the values in api.yaml file.
- If **policies** parameter is not set in api_params.yaml file, use the values in api.yaml file. (The old procedure)
https://github.com/wso2/carbon-apimgt/pull/9537
[1] https://github.com/wso2/carbon-apimgt/pull/9537

Add documentation for the support to override subscription policies of an API using the api_params.yaml

---

en/docs/install-and-setup/upgrading-wso2-api-manager/upgrading-from-1100-to-320.md
en/docs/install-and-setup/upgrading-wso2-api-manager/upgrading-from-200-to-320.md
en/docs/install-and-setup/upgrading-wso2-api-manager/upgrading-from-210-to-320.md
en/docs/install-and-setup/upgrading-wso2-api-manager/upgrading-from-220-to-320.md
en/docs/install-and-setup/upgrading-wso2-api-manager/upgrading-from-250-to-320.md
en/docs/install-and-setup/upgrading-wso2-api-manager/upgrading-from-260-to-320.md
en/docs/install-and-setup/upgrading-wso2-api-manager/upgrading-from-300-to-320.md
en/docs/install-and-setup/upgrading-wso2-api-manager/upgrading-from-310-to-320.md

Each DB script section provides DB scripts for multiple DB types, including Oracle.
In Oracle, the default behavior is we need to explicitly commit the transactions.
Therefore,  add `COMMIT; `command at the end of the script in order to explicitly commit the transactions.
This change has been added to all the Oracle DB scripts.
Update Oracle Database scripts

[3.2.0] Update Oracle migration DB scripts with COMMIT keyword

---

en/docs/install-and-setup/upgrading-wso2-api-manager/upgrading-from-1100-to-320.md
en/docs/install-and-setup/upgrading-wso2-api-manager/upgrading-from-200-to-320.md
en/docs/install-and-setup/upgrading-wso2-api-manager/upgrading-from-210-to-320.md
en/docs/install-and-setup/upgrading-wso2-api-manager/upgrading-from-220-to-320.md
en/docs/install-and-setup/upgrading-wso2-api-manager/upgrading-from-250-to-320.md
en/docs/install-and-setup/upgrading-wso2-api-manager/upgrading-from-260-to-320.md
en/docs/install-and-setup/upgrading-wso2-api-manager/upgrading-from-300-to-320.md
en/docs/install-and-setup/upgrading-wso2-api-manager/upgrading-from-310-to-320.md

Each DB script section provides DB scripts for multiple DB types, including Oracle.
In Oracle, the default behavior is we need to explicitly commit the transactions.
Therefore,  add `COMMIT; `command at the end of the script in order to explicitly commit the transactions.
This change has been added to all the Oracle DB scripts.
Update Oracle Database scripts

[Master] Update Oracle migration DB scripts with COMMIT keyword

---

en/docs/reference/product-apis/admin-apis/admin-v0.17/admin-v0.17.yaml
en/docs/reference/product-apis/admin-apis/admin-v1/admin-v1.yaml

Adding the missing examples and configuration sample in the set of REST API Resources in Admin v0.16 REST API.
Fixes https://github.com/wso2/docs-apim/issues/2924 for 3.1.0 doc space. 
https://github.com/wso2/docs-apim/pull/2951

[Master] Add requested configs in Admin v0.17 and Admin v1 REST API pages

---

en/docs/administer/logging-and-monitoring/logging/managing-log-growth.md

**Fixing problems with enabling the size based logging**
It is unnecessary to set "modulate" property to a size-based triggering policy. When the above property is set, it is trying to pass an invalid argument to a size-based triggering policy, which results in the error message above.
Therefore the step b in the section under Managing the growth of Carbon logs in the documentation[1] should be removed from the document and update according to that.
[1]. https://apim.docs.wso2.com/en/latest/administer/logging-and-monitoring/logging/managing-log-growth/#
- Fixes #2940 
For 3.2.0 Docs space

[3.2.0] Remove invalid step from Managing the growth of Carbon logs section

---

en/docs/administer/logging-and-monitoring/logging/managing-log-growth.md
en/docs/learn/analytics/configuring-apim-analytics.md

**Fixing problems with enabling the size based logging**
It is unnecessary to set "modulate" property to a size-based triggering policy. When the above property is set, it is trying to pass an invalid argument to a size-based triggering policy, which results in the error message above.
Therefore the step b in the section under Managing the growth of Carbon logs in the documentation[1] should be removed from the document and update according to that.
**Modify the documentation for APIM analytics configurations**
In [2], It says to configure 'receiver_urls' and [[apim.analytics.url_group]] both in order to specify the URLs and not required to use both the properties. Therefore it is required to add notes stating this fact.
[1]. https://apim.docs.wso2.com/en/latest/administer/logging-and-moni …

[3.1.0] Fixing #2939 and #2940 issues.

---

en/docs/administer/logging-and-monitoring/logging/managing-log-growth.md

**Fixing problems with enabling the size based logging**
It is unnecessary to set "modulate" property to a size-based triggering policy. When the above property is set, it is trying to pass an invalid argument to a size-based triggering policy, which results in the error message above.
Therefore the step b in the section under Managing the growth of Carbon logs in the documentation[1] should be removed from the document and update according to that.
[1]. https://apim.docs.wso2.com/en/latest/administer/logging-and-monitoring/logging/managing-log-growth/#
- Fixes #2940 
For Master Docs space

[Master] Remove invalid step from Managing the growth of Carbon logs section

---

en/docs/administer/product-administration/monitoring/logging/managing-log-growth.md
en/docs/learn/analytics/configuring-apim-analytics.md

**Fixing problems with enabling the size based logging**
It is unnecessary to set "modulate" property to a size-based triggering policy. When the above property is set, it is trying to pass an invalid argument to a size-based triggering policy, which results in the error message above.
Therefore the step b in the section under Managing the growth of Carbon logs in the documentation[1] should be removed from the document and update according to that.
**Modify the documentation for APIM analytics configurations**
In [2], It says to configure 'receiver_urls' and [[apim.analytics.url_group]] both in order to specify the URLs and not required to use both the properties. Therefore it is required to add notes stating this fact.
[1]. https://apim.docs.wso2.com/en/latest/administer/logging-and-moni …

[3.0.0] Fixing #2939 and #2940 issues.

---

en/docs/install-and-setup/supported-cipher-suites.md
en/mkdocs.yml

- Moved supported cipher suites document under APIM doc space. 
Adding the **Supported Cipher Suites** under `https://apim.docs.wso2.com/en/3.0.0//install-and-setup/supported-cipher-suites`
- PR sync for #2060 and #1326
https://github.com/wso2/docs-apim/pull/2465

[3.0.0] [PRSync] Move supported cipher suites document under APIM doc space

---

en/docs/design/api-security/api-authentication/secure-apis-using-mutual-ssl.md

Add missing MutualSSL Configurations related to Certificate Headers.
Fixes https://github.com/wso2/docs-apim/issues/2935 for master 
Securing APIs with Mutual SSL

[Master] Add Mutual SSL configurations

---

en/docs/learn/api-security/api-authentication/secure-apis-using-mutual-ssl.md

Add missing MutualSSL Configurations related to Certificate Headers.
Fixes https://github.com/wso2/docs-apim/issues/2935 for 3.2.0 
Securing APIs with Mutual SSL

[3.2.0] Add Mutual SSL configurations 

---

en/docs/learn/analytics/configuring-apim-analytics.md

Correcting HA setup configuration by adding notes and config examples based on HA setup type.
Fixes https://github.com/wso2/docs-apim/issues/2975 for 3.1.0

[3.1.0] Fixing HA terminology in APIM Analytics

---

en/docs/assets/css/theme.css
en/mkdocs.yml

Fixing the following issue 
The Issue with the following pic is a responsive issue where the "Permanent Link" icon drops to the second line when the text in the title takes up all the space in the first row, making the space between the title and the introduction section too much. 
When we collapse out the right-hand side menu, the issue is no longer there.<img width="1327" alt="Screen Shot 2021-01-22 at 10 28 40 PM" src="https://user-images.githubusercontent.com/3424539/105525001-72ac1800-5d06-11eb-811a-766e59dc6961.png">
The solution for this is to make the icon behave like a text element so that it will take the last word with it to the second line. I think this will fix this issue in a responsive manner.

Fixing the style issue with the title spacing

---

en/docs/develop/customizations/log-in-to-the-dev-portal-using-social-media.md

Adding missing Basic Claims configurations and Role configurations in the **Log in to the Developer Portal using Social Media** section.
PR Sync for https://github.com/wso2/docs-apim/pull/1385

[3.2.0] [PRSync] Added Basic Claims Configurations and Role configurations

---

en/docs/reference/customize-product/customizations/log-in-to-the-dev-portal-using-social-media.md

Adding missing Basic Claims configurations and Role configurations in the **Log in to the Developer Portal using Social Media** section.
PR Sync for https://github.com/wso2/docs-apim/pull/1385

[Master] [PRSync] Added Basic Claims Configurations and Role configurations

---

en/docs/learn/consume-api/customizations/log-in-to-the-dev-portal-using-social-media.md

Adding missing Basic Claims configurations and Role configurations in the **Log in to the Developer Portal using Social Media** section.
PR Sync for https://github.com/wso2/docs-apim/pull/1385

[3.0.0] [PRSync] Added Basic Claims Configurations and Role configurations

---

en/docs/learn/api-security/api-authentication/secure-apis-using-mutual-ssl.md

- Adding a note stating the flow is specifically designed for using SSL termination and MTSL with Nginx ELB. And other ELBs has to be configured accordingly.
- Add missing MutualSSL Configurations related to Certificate Headers.
Fixes https://github.com/wso2/docs-apim/issues/3007 for 3.0.0 docs space
Backporting fix for https://github.com/wso2/docs-apim/issues/2935

[3.0.0] Backporting MTSL related configs

---

en/docs/administer/managing-users-and-roles/managing-user-stores/configure-primary-user-store/configuring-a-jdbc-user-store.md

If the RDBMS primary user store is configured and when the DomainName under the [user_store.properties] in the deployement.toml file is added, the default primary user store domain name, PRIMARY, will be replaced with this new name. This will lead the user not to list the users in the carbon management console when the "ALL-USER-STORE-DOMAINS" is selected from the domains dropdown list.
Since there will be only one primary user store, there is no point in changing its name as no need to uniquely identify it. So changing the DomainName will create unwanted complexity to the deployment and even if we want to revert it back to the PRIMARY domain name it requires many DB level updates which are complicated and might lead to DB corruption. Therefore, removing the step to change the …

[Master] Remove DomainName property from JDBC user store configs

---

en/docs/administer/product-administration/managing-users-and-roles/managing-user-stores/configure-primary-user-store/configuring-a-jdbc-user-store.md

If the RDBMS primary user store is configured and when the DomainName under the [user_store.properties] in the deployement.toml file is added, the default primary user store domain name, PRIMARY, will be replaced with this new name. This will lead the user not to list the users in the carbon management console when the "ALL-USER-STORE-DOMAINS" is selected from the domains dropdown list.
Since there will be only one primary user store, there is no point in changing its name as no need to uniquely identify it. So changing the DomainName will create unwanted complexity to the deployment and even if we want to revert it back to the PRIMARY domain name it requires many DB level updates which are complicated and might lead to DB corruption. Therefore, removing the step to change the …

[3.0.0] Remove DomainName property from JDBC user store configs

---

en/docs/administer/managing-users-and-roles/managing-user-stores/configure-primary-user-store/configuring-a-jdbc-user-store.md

If the RDBMS primary user store is configured and when the DomainName under the [user_store.properties] in the deployement.toml file is added, the default primary user store domain name, PRIMARY, will be replaced with this new name. This will lead the user not to list the users in the carbon management console when the "ALL-USER-STORE-DOMAINS" is selected from the domains dropdown list.
Since there will be only one primary user store, there is no point in changing its name as no need to uniquely identify it. So changing the DomainName will create unwanted complexity to the deployment and even if we want to revert it back to the PRIMARY domain name it requires many DB level updates which are complicated and might lead to DB corruption. Therefore, removing the step to change the …

[3.2.0] Remove DomainName property from JDBC user store configs

---

en/docs/integrate/develop/advanced-development/using-swagger-for-apis.md
en/docs/integrate/examples/data_integration/swagger-data-services.md
en/docs/integrate/examples/rest_api_examples/publishing-a-swagger-api.md

> From APIM 4.0 onwards the default swagger version we expose from the
Micro integrator is swagger 3.0 (OpenApi)
Related to wso2/micro-integrator/issues/2043

Add changed related to OpenApi support.

---

en/docs/learn/api-controller/advanced-topics/configuring-environment-specific-parameters.md

Fixes: https://github.com/wso2/docs-apim/issues/3060

[3.0.0] Changing the hostName to host in api_params.yaml in APICTL certs import

---

en/docs/reference/config-catalog.md
en/tools/config-catalog-generator/data/apim.throttling.toml
en/tools/config-catalog-generator/data/configs.json
en/tools/config-catalog-generator/dist/config-catalog.md

Fixes: https://github.com/wso2/docs-apim/issues/3077
Correcting the configuration and the description of enable_unlimited_tier in the config catalog.
- Modified the enable_unlimited_tier field value to true in the **config-catalog/#api-m-throttling-configurations** as below.
- Modified the enable_unlimited_tier field default value to true and updated the description in the **config-catalog/#api-m-throttling-configurations** as below.

Correcting the default value of enable_unlimited_tier and the description in the config catalog

---

en/docs/reference/config-catalog.md
en/tools/config-catalog-generator/data/apim.throttling.toml
en/tools/config-catalog-generator/data/configs.json
en/tools/config-catalog-generator/dist/config-catalog.md

Fixes: https://github.com/wso2/docs-apim/issues/3077
Correcting the configuration and the description of enable_unlimited_tier in the config catalog.
- Modified the enable_unlimited_tier field value to true in the **config-catalog/#api-m-throttling-configurations** as below.
- Modified the enable_unlimited_tier field default value to true and updated the description in the **config-catalog/#api-m-throttling-configurations** as below.

[3.2.0] Correcting the default value of enable_unlimited_tier and the description in the config catalog

---

en/docs/develop/extending-api-manager/extending-workflows/invoking-the-api-manager-from-the-bpel-engine.md

Fixes: https://github.com/wso2/docs-apim/issues/3076
Change the old URL to the correct WorkFlowCallBackURL.
- Changed the URL and the examples in the page **Invoking the API Manager from the BPEL Engine**.

[3.2.0] Updating the WorkFlow Callback URL

---

en/docs/learn/extensions/managing-workflow-extension/invoking-the-api-manager-from-the-bpel-engine.md

Fixes: https://github.com/wso2/docs-apim/issues/3076
Change the old URL to the correct WorkFlowCallBackURL.
- Changed the URL and the examples in the page **Invoking the API Manager from the BPEL Engine**.

[3.0.0] Updating the WorkFlow Callback URL

---

en/docs/develop/extending-api-manager/extending-workflows/invoking-the-api-manager-from-the-bpel-engine.md

Fixes: https://github.com/wso2/docs-apim/issues/3076
Change the old URL to the correct WorkFlowCallBackURL.
- Changed the URL and the examples in the page **Invoking the API Manager from the BPEL Engine**.

[3.1.0] Updating the WorkFlow Callback URL

---

en/docs/reference/customize-product/extending-api-manager/extending-workflows/invoking-the-api-manager-from-the-bpel-engine.md

Fixes: https://github.com/wso2/docs-apim/issues/3076
Change the old URL to the correct WorkFlowCallBackURL.
- Changed the URL and the examples in the page **Invoking the API Manager from the BPEL Engine**.

Updating the WorkFlow Callback URL

---

en/docs/reference/customize-product/customizations/customizing-the-developer-portal/customize-api-listing/change-default-view.md
en/docs/reference/customize-product/customizations/customizing-the-developer-portal/enable-or-disable-banner.md
en/docs/reference/customize-product/customizations/customizing-the-developer-portal/enable-or-disable-footer.md
en/docs/reference/customize-product/customizations/customizing-the-developer-portal/enable-or-disable-home-page.md
en/docs/reference/customize-product/customizations/customizing-the-developer-portal/enable-or-disable-rating.md
en/docs/reference/customize-product/customizations/customizing-the-developer-portal/enable-or-disable-tag-cloud.md
en/docs/reference/customize-product/customizations/customizing-the-developer-portal/enabling-or-disabling-api-detail-tabs.md
en/docs/reference/customize-product/customizations/customizing-the-developer-portal/override-api-overview-page-per-api.md
en/docs/reference/customize-product/customizations/customizing-the-developer-portal/styling-api-details-info-section.md
en/docs/reference/customize-product/customizations/customizing-the-developer-portal/styling-api-details-left-menu.md
en/docs/reference/customize-product/customizations/customizing-the-developer-portal/styling-the-logo-and-header.md

Fixes: https://github.com/wso2/docs-apim/issues/2945
Fixing the steps and inconsistencies in the section **Customizing the Developer Portal**.
- Added a sentence on `defaultTheme.js` to almost all the pages under **Customizing the Developer Portal**, so that the user can have an idea of it. (For example, check the second paragraph of the below screenshot.)
- Restructured the steps on some pages.
- Corrected the typos and formatting.

Improve the consistency of the docs on Developer Portal Customizations

---

en/docs/administer/product-administration/disabling-anonymous-access-to-developer-portal.md

Fixes: https://github.com/wso2/docs-apim/issues/3049
Adding the warning to get the latest WUM update to have this feature similarly as shown in [1].
- Added a warning as shown below to the page **Disabling Anonymous Access to the Developer Portal**.
[1] https://apim.docs.wso2.com/en/3.0.0/install-and-setup/deploying-wso2-api-manager/distributed-deployment/product-profiles/#method-2-optimizing-while-starting-the-server

[3.0.0] Add warning to take WUM update for devportal anonymous mode

---

en/docs/develop/customizations/customizing-the-developer-portal/customize-api-listing/change-default-view.md
en/docs/develop/customizations/customizing-the-developer-portal/enable-or-disable-banner.md
en/docs/develop/customizations/customizing-the-developer-portal/enable-or-disable-footer.md
en/docs/develop/customizations/customizing-the-developer-portal/enable-or-disable-home-page.md
en/docs/develop/customizations/customizing-the-developer-portal/enable-or-disable-rating.md
en/docs/develop/customizations/customizing-the-developer-portal/enable-or-disable-tag-cloud.md
en/docs/develop/customizations/customizing-the-developer-portal/enabling-or-disabling-api-detail-tabs.md
en/docs/develop/customizations/customizing-the-developer-portal/override-api-overview-page-per-api.md
en/docs/develop/customizations/customizing-the-developer-portal/styling-api-details-info-section.md
en/docs/develop/customizations/customizing-the-developer-portal/styling-api-details-left-menu.md
en/docs/develop/customizations/customizing-the-developer-portal/styling-the-logo-and-header.md

Fixes: https://github.com/wso2/docs-apim/issues/2945
Fixing the steps and inconsistencies in the section **Customizing the Developer Portal**.
- Added a sentence on `defaultTheme.js` to almost all the pages under **Customizing the Developer Portal**, so that the user can have an idea of it. (For example, check the second paragraph of the below screenshot.)
- Restructured the steps on some pages.
- Corrected the typos and formatting.

[3.2.0] Improve the consistency of the docs on Developer Portal Customizations

---

en/docs/learn/consume-api/customizations/customizing-the-developer-portal/customize-api-listing/change-default-view.md
en/docs/learn/consume-api/customizations/customizing-the-developer-portal/enable-or-disable-banner.md
en/docs/learn/consume-api/customizations/customizing-the-developer-portal/enable-or-disable-footer.md
en/docs/learn/consume-api/customizations/customizing-the-developer-portal/enable-or-disable-home-page.md
en/docs/learn/consume-api/customizations/customizing-the-developer-portal/enable-or-disable-rating.md
en/docs/learn/consume-api/customizations/customizing-the-developer-portal/enable-or-disable-tag-cloud.md
en/docs/learn/consume-api/customizations/customizing-the-developer-portal/enabling-or-disabling-api-detail-tabs.md
en/docs/learn/consume-api/customizations/customizing-the-developer-portal/override-api-overview-page-per-api.md
en/docs/learn/consume-api/customizations/customizing-the-developer-portal/styling-api-details-info-section.md
en/docs/learn/consume-api/customizations/customizing-the-developer-portal/styling-api-details-left-menu.md
en/docs/learn/consume-api/customizations/customizing-the-developer-portal/styling-the-logo-and-header.md

Fixes: https://github.com/wso2/docs-apim/issues/2945
Fixing the steps and inconsistencies in the section **Customizing the Developer Portal**.
- Added a sentence on `defaultTheme.js` to almost all the pages under **Customizing the Developer Portal**, so that the user can have an idea of it. (For example, check the second paragraph of the below screenshot.)
- Restructured the steps on some pages.
- Corrected the typos and formatting.

[3.0.0] Improve the consistency of the docs on Developer Portal Customizations

---

en/docs/install-and-setup/setup/api-controller/encrypting-secrets-with-ctl.md
en/docs/install-and-setup/setup/mi-setup/security/encrypting_plain_text.md
en/mkdocs.yml

$subject
- Move **Encrypting Secrets with CTL** section from Managing Integrations to API Controller(Since this is a generic feature which can be used by both APIM and MI)
- Fix missing links in Encrypting Secrets with CTL section
- Update Dynamic secrets section in MI security

Update Encrypting Secrets with CTL section

---

en/docs/install-and-setup/upgrading-wso2-api-manager/upgrading-from-210-to-310.md
en/docs/install-and-setup/upgrading-wso2-api-manager/upgrading-from-220-to-310.md
en/docs/install-and-setup/upgrading-wso2-api-manager/upgrading-from-250-to-310.md
en/docs/install-and-setup/upgrading-wso2-api-manager/upgrading-from-260-to-310.md
en/docs/install-and-setup/upgrading-wso2-api-manager/upgrading-from-300-to-310.md

Fixes: https://github.com/wso2/docs-apim/issues/3114
Reflect the changes from 3.2.0 doc space in order to mention that the WorkflowCallbackService.xml should not be replaced during the migrations.
Updated the below pages with the above change.
- Upgrading API Manager from 2.1.0 to 3.1.0
- Upgrading API Manager from 2.2.0 to 3.1.0
- Upgrading API Manager from 2.5.0 to 3.1.0
- Upgrading API Manager from 2.6.0 to 3.1.0
- Upgrading API Manager from 3.0.0 to 3.1.0

[3.1.0] Mentioning WorkflowCallbackService.xml not to be replaced in migrations

---

en/docs/install-and-setup/upgrading-wso2-api-manager/upgrading-from-210-to-300.md
en/docs/install-and-setup/upgrading-wso2-api-manager/upgrading-from-220-to-300.md
en/docs/install-and-setup/upgrading-wso2-api-manager/upgrading-from-250-to-300.md
en/docs/install-and-setup/upgrading-wso2-api-manager/upgrading-from-260-to-300.md

Fixes: https://github.com/wso2/docs-apim/issues/3114
Reflect the changes from 3.2.0 doc space in order to mention that the WorkflowCallbackService.xml should not be replaced during the migrations.
Updated the below pages with the above change.
- Upgrading API Manager from 2.1.0 to 3.0.0
- Upgrading API Manager from 2.2.0 to 3.0.0
- Upgrading API Manager from 2.5.0 to 3.0.0
- Upgrading API Manager from 2.6.0 to 3.0.0

[3.0.0] Mentioning WorkflowCallbackService.xml not to be replaced in migrations

---

en/docs/install-and-setup/install/running-the-product.md

Fixes: https://github.com/wso2/docs-apim/issues/3106
Remove the unnecessary repetitive infos on configuring certs that do not have a link in it to the correct document.
- Removed the repetitive info sections under the **Accessing the Management Console**, **Accessing the API Publisher** and **Accessing the Developer Portal** as below.
- Add a new section named **Accessing the API Manager Web Portals** to precisely say about the certificates.

[3.2.0] Precisely point to the correct certificate (keystore) docs when running the product

---

en/docs/install-and-setup/install/running-the-product.md

Fixes: https://github.com/wso2/docs-apim/issues/3106
Remove the unnecessary repetitive infos on configuring certs that do not have a link in it to the correct document.
- Removed the repetitive info sections under the **Accessing the Management Console**, **Accessing the API Publisher** and **Accessing the Developer Portal** as below.
- Add a new section named **Accessing the API Manager Web Portals** to precisely say about the certificates.

Precisely point to the correct certificate (keystore) docs when running the product

---

en/docs/install-and-setup/install/running-the-product.md

Fixes: https://github.com/wso2/docs-apim/issues/3106
Remove the unnecessary repetitive infos on configuring certs that do not have a link in it to the correct document.
- Removed the repetitive info sections under the **Accessing the Management Console**, **Accessing the API Publisher** and **Accessing the Developer Portal** as below.
- Add a new section named **Accessing the API Manager Web Portals** to precisely say about the certificates.

[3.1.0] Precisely point to the correct certificate (keystore) docs when running the product

---

en/docs/install-and-setup/installation-guide/running-the-product.md

Fixes: https://github.com/wso2/docs-apim/issues/3106
Remove the unnecessary repetitive infos on configuring certs that do not have a link in it to the correct document.
- Removed the repetitive info sections under the **Accessing the Management Console**, **Accessing the API Publisher** and **Accessing the Developer Portal** as below.
- Add a new section named **Accessing the API Manager Web Portals** to precisely say about the certificates.

[3.0.0] Precisely point to the correct certificate (keystore) docs when running the product

---

en/docs/getting-started/about-this-release.md
en/docs/learn/api-security/oauth2/grant-types/implicit-grant.md

Fixes: https://github.com/wso2/docs-apim/issues/2944
Fixes: https://github.com/wso2/docs-apim/issues/3064
Tell the users that the Implicit Grant has been deprecated in APIM 3.2.0 and will be removed in future.
- Added a note under the section **Deprecated features and functionalities** in the "About this Release" as shown below.
- Added a note in the **Implicit Grant** page as shown below.

[3.2.0] Deprecating the docs on Implicit Grant in APIM 3.2.0

---

en/docs/learn/api-security/oauth2/access-token-types/jwt-tokens.md

Documentation gap for the procedure of subscription validation through KM

---

en/docs/install-and-setup/setup/mi-setup/transport_configurations/multi-https-transport.md

When enabling the dynamic SSL profiles, the "org.apache.synapse.transport.passthru.PassThroughHttpMultiSSLListener" needs to be configured as the transport receiver in the axis2.xml after disabling the default transport receiver"org.apache.synapse.transport.passthru.PassThroughHttpSSLListener".
Also, It is recommended to configure the hostname as the server when configuring custom SSL profiles. If an IP address is required to be configured as the server, the IP address needs to be mapped to a hostname in the Host file, and the hostname can be provided as the server.
Fixes: #2757
Related issue: wso2/micro-integrator#2034

Add missing information on how to enable dynamic SSL profiles correctly

---

en/docs/install-and-setup/install-and-setup-overview.md
en/docs/install-and-setup/setup/mi-setup/security/securing_management_api.md
en/docs/integrate/develop/using-wire-logs.md

Correct all links pointing to the obsolete administer-and-observe directory

---

en/docs/install-and-setup/setup/distributed-deployment/deploying-wso2-api-m-in-a-distributed-setup.md
en/docs/install-and-setup/setup/reference/common-runtime-and-configuration-artifacts.md

This PR add the artifact directories for persistence in a deployment, rather than using the parent directory.
Fixes https://github.com/wso2/docs-apim/issues/1453

[3.1.0] Define specific runtime artifact directories for persistence

---

en/docs/reference/config-catalog.md
en/tools/config-catalog-generator/data/configs.json
en/tools/config-catalog-generator/dist/config-catalog.md

Adds the missing throttling configs to the config catalog.
Fixes https://github.com/wso2/docs-apim/issues/3540

[3.2.0] Add throttling configs to the config catalog

---

en/docs/reference/config-catalog.md
en/tools/config-catalog-generator/data/configs.json
en/tools/config-catalog-generator/dist/config-catalog.md

Adds the missing throttling configs to the config catalog.
Fixes https://github.com/wso2/docs-apim/issues/3540

Add throttling configs to the config catalog

---

en/docs/index.md

This removes tutorials from the landing page - the reasoning is that scenarios are supposed to cover the same aspect and will be better from a product introduction perspective.
Also adding in Overview to this page.

Landing update

---

en/mkdocs.yml

fixing warning in mkdocs
`WARNING -  A relative path to 'design/api-security/api-authentication/securing-apis-deployed-in-cloud-clusters.md' is included in the 'nav' configuration, which is not found in the documentation files `

fixing warning in mkdocs

---

en/docs/get-started/about-this-release.md
en/docs/install-and-setup/setup/api-controller/managing-apis-api-products/importing-apis-via-dev-first-approach.md
en/docs/install-and-setup/setup/api-controller/managing-apis-api-products/managing-apis-and-api-products.md

Partially fixes https://github.com/wso2/product-apim-tooling/issues/558
Fixes: https://github.com/wso2/product-apim-tooling/issues/704
Fix the incorrect flags and examples of undeploy/get commands and add the initial content for About this Release section of APICTL.
- Modified the About this Release section of APICTL as below.
- Modified the examples of **apictl undeploy** and **apictl get apis/api-products** commands

Update the About this Release section of APICTL and corrected the examples of undeploy and get commands

---

en/docs/reference/mediators/dss-mediator.md
en/mkdocs.yml

> Data Service Call Mediator is supported by Integration Studio 8.0.0 and MI 4.0.0. This PR adds the mediator docs for the Data Service Call Mediator.
Fix: https://github.com/wso2/integration-studio/issues/765

Add dss call mediator docs

---

en/docs/index.md

- Removing the video until the new video is created.
- The current video is outdated as it refers to Micro Gateway etc. It also doesn't contain any info about the new integration story.

Removing the video on landing page

---

en/docs/get-started/about-this-release.md

Fixing the broken links in the **API Controller** section of the **About this Release** page.

Correcting the broken links to apictl docs from the About this Release page

---

en/docs/reference/mediators/property-reference/http-transport-properties.md

The property non.error.http.status.codes can be used to configure HTTP status codes that need to be considered as non-error status codes (for blocking calls)
`<property name="non.error.http.status.codes" scope="axis2" value="403" type="STRING"/>`
Related PR: wso2/wso2-axis2#201

[Master] Update documentation on non.error.http.status.code property

---

en/docs/learn/api-controller/advanced-topics/configuring-environment-specific-parameters.md

Adding the documentation on overriding policies using the api_params.yaml via apictl. 
The doc changes for for apictl 3.2.2 has been added.
- Added the policies field to the api_params.yaml template
- Added the examples
https://github.com/wso2/product-apim-tooling/pull/745

[3.2.x] Adding docs on overriding policies using the api_params.yaml via apictl

---

en/docs/install-and-setup/setup/deployment-best-practices/changing-the-default-ports-with-offset.md
en/docs/install-and-setup/setup/reference/default-product-ports.md
en/docs/install-and-setup/setup/security/configuring-transport-level-security.md

- Adding streaming integration ports
- Consolidating the link between 'Changing default ports' and the 'list of default ports' for all of the API Manager runtimes.
- Moved the section on 'disabling the HTTP transport for the API-M runtime' from the Ports documentation to https://apim.docs.wso2.com/en/latest/install-and-setup/setup/security/configuring-transport-level-security/
Fixes https://github.com/wso2/docs-apim/issues/3956

(4.0.0 branch) Updating the default ports documentation

---

en/docs/deploy-and-publish/deploy-on-gateway/api-gateway/threat-protectors/json-threat-protection-for-api-gateway.md
en/docs/deploy-and-publish/deploy-on-gateway/api-gateway/threat-protectors/regular-expression-threat-protection-for-api-gateway.md
en/docs/deploy-and-publish/deploy-on-gateway/api-gateway/threat-protectors/xml-threat-protection-for-api-gateway.md

Fixed in the following pages:
- https://apim.docs.wso2.com/en/latest/deploy-and-publish/deploy-on-gateway/api-gateway/threat-protectors/regular-expression-threat-protection-for-api-gateway/
- https://apim.docs.wso2.com/en/latest/deploy-and-publish/deploy-on-gateway/api-gateway/threat-protectors/json-threat-protection-for-api-gateway/
- https://apim.docs.wso2.com/en/latest/deploy-and-publish/deploy-on-gateway/api-gateway/threat-protectors/xml-threat-protection-for-api-gateway/

Fix image size in threat protection docs

---

en/docs/includes/analytics/configure-synapse-gateway.md

- Added absolute link because the relative link breaks when used with the include plug-in
- fixes https://github.com/wso2/docs-apim/issues/4165

fixes broken link

---

en/docs/install-and-setup/setup/setting-up-proxy-server-and-the-load-balancer/adding-a-custom-proxy-path.md

Updating proxy context path configuration documentation for API Manager 3.x base on https://github.com/wso2/product-apim/issues/11263#issuecomment-863459441
[Adding a custom Proxy Path - WSO2 API Manager Documentation 4.0.0.pdf](https://github.com/wso2/docs-apim/files/6719575/Adding.a.custom.Proxy.Path.-.WSO2.API.Manager.Documentation.4.0.0.pdf)

Updating proxy context path configuration documentation

---

en/docs/reference/product-apis/advanced-configurations.md

- Add "Configuring Allowed Origins for REST APIs" content under "Advanced Configurations" section of Product REST APIs
- Updated document content: [product-apis-advanced-configurations.pdf](https://github.com/wso2/docs-apim/files/6642231/product-apis-advanced-configurations.pdf)
Related Issue: https://github.com/wso2/docs-apim/issues/4110

Add 'Configuring Allowed Origins for REST APIs' Content

---

en/docs/develop/product-apis/advanced-configurations.md

- Add "Configuring Allowed Origins for REST APIs" content under "Advanced Configurations" section of Product REST APIs
- Updated document content: [product-apis-advanced-configurations-3.2.0.pdf](https://github.com/wso2/docs-apim/files/6642281/product-apis-advanced-configurations-3.2.0.pdf)
- master branch - https://github.com/wso2/docs-apim/pull/4196
- 4.0.0 branch - https://github.com/wso2/docs-apim/pull/4197
https://github.com/wso2/docs-apim/issues/4110

[3.2.0 branch] Add 'Configuring Allowed Origins for REST APIs' Content

---

en/docs/reference/product-apis/advanced-configurations.md

- Add "Configuring Allowed Origins for REST APIs" content under "Advanced Configurations" section of Product REST APIs
- Updated document content: [product-apis-advanced-configurations-4.0.0.pdf](https://github.com/wso2/docs-apim/files/6642241/product-apis-advanced-configurations-4.0.0.pdf)
- master branch - https://github.com/wso2/docs-apim/pull/4196
https://github.com/wso2/docs-apim/issues/4110

[4.0.0 branch] Add 'Configuring Allowed Origins for REST APIs' Content

---

en/docs/install-and-setup/install/installing-the-product/running-the-mi-dashboard.md
en/docs/reference/config-catalog-mi-dashboard.md
en/mkdocs.yml

With https://github.com/wso2/product-mi-tooling/pull/208 users can use OIDC based Single Sign-On to login to the WSO2 Monitoring Dashboard. This PR introduces the documentation related to this feature.

Add MI Dashboard SSO configuration docs

---

en/docs/reference/connectors/file-connector/3.x/file-connector-3.x-config.md

Add the document changes related to the new property `setAvoidPermission` which is added to the file connector move operation by https://github.com/wso2-extensions/esb-connector-file/pull/164.

Add option to skip file permission check in the move operation

---

en/docs/reference/connectors/kafka-connector/kafka-connector-config.md

With https://github.com/wso2-extensions/esb-connector-kafka/pull/62, for Kafka connector v3.1.2 and above, when an error occurs the error will get set to the message context. This PR update the docs with the relevant error code.

Update kafka docs with error codes

---

en/docs/develop/streaming-apps/creating-a-siddhi-application.md
en/docs/develop/streaming-apps/streaming-integrator-studio-overview.md

This PR fixes the SI Tooling URL at [1].
[1] https://apim.docs.wso2.com/en/latest/develop/streaming-apps/creating-a-siddhi-application/
Resolves https://github.com/wso2/docs-apim/issues/4562

Fix SI Tooling URL

---

en/docs/reference/connectors/amazons3-connector/amazons3-connector-example.md
en/docs/reference/connectors/amazons3-connector/amazons3-connector-reference.md

With https://github.com/wso2-extensions/esb-connector-amazons3/pull/50 the `getObject` operation of the Amazon S3 connector was improved. This doc adds the related new changes.
- Add a new parameter called `destinationFilePath` to getObject operation to download the file to the local server.
- Set the file content in the GetObjectResponse.

Update Amazon S3 connector docs with 2.0.1 release features

---

en/docs/get-started/api-manager-quick-start-guide.md
en/docs/get-started/integration-quick-start-guide.md
en/docs/get-started/streaming-quick-start-guide.md
en/docs/install-and-setup/install/installing-the-product/installing-api-m-runtime.md
en/docs/install-and-setup/install/installing-the-product/installing-mi-dashboard.md
en/docs/install-and-setup/install/installing-the-product/installing-mi.md
en/docs/install-and-setup/install/installing-the-product/installing-si-as-a-linux-service.md
en/docs/install-and-setup/install/installing-the-product/installing-si.md
en/docs/install-and-setup/setup/deployment-best-practices/security-guidelines-for-production-deployment.md
en/docs/install-and-setup/setup/security/enabling-java-security-manager.md
en/docs/streaming/getting-started/download-install-and-start-si.md

> We need to remove java 8 from QSG as we no longer recommend,

[4.0.0] remove java 8 from QSG

---

en/docs/install-and-setup/setup/api-controller/getting-started-with-wso2-api-controller.md

Affected Page:
https://apim.docs.wso2.com/en/latest/install-and-setup/setup/api-controller/getting-started-with-wso2-api-controller/
Fixes  https://github.com/wso2/docs-apim/issues/3173 for 4.0.0.
Windows 10

[4.0.0] Add missing commands related to the Windows environment

---

en/docs/install-and-setup/setup/api-controller/getting-started-with-wso2-api-controller.md

Affected Page:
https://apim.docs.wso2.com/en/latest/install-and-setup/setup/api-controller/getting-started-with-wso2-api-controller/
Fixes  https://github.com/wso2/docs-apim/issues/3173 for Master.
Windows 10

[Master] Add missing commands related to the Windows environment

---

en/docs/learn/api-controller/getting-started-with-wso2-api-controller.md

Affected Page:
https://apim.docs.wso2.com/en/3.2.0/learn/api-controller/getting-started-with-wso2-api-controller/
Fixes  https://github.com/wso2/docs-apim/issues/3173 for 3.2.0.
Windows 10

[3.2.0] Add missing commands related to the Windows environment

---

en/docs/learn/api-controller/getting-started-with-wso2-api-controller.md

Affected Page:
https://apim.docs.wso2.com/en/3.1.0/learn/api-controller/getting-started-with-wso2-api-controller/
Fixes  https://github.com/wso2/docs-apim/issues/3173 for 3.1.0.
Windows 10

[3.1.0] Add missing commands related to the Windows environment

---

en/docs/learn/api-controller/getting-started-with-wso2-api-controller.md

Affected Page:
https://apim.docs.wso2.com/en/3.0.0/learn/api-controller/getting-started-with-wso2-api-controller/
Fixes  https://github.com/wso2/docs-apim/issues/3173 for 3.0.0.
Windows 10

[3.0.0] Add missing commands related to the Windows environment

---

en/docs/install-and-setup/setup/security/configuring-transport-level-security.md

This PR removes ThriftAuthenticationService TLS configurations.
Related issue: https://github.com/wso2/docs-apim/issues/4365

[3.2.0] Remove ThriftAuthenticationService TLS config

---

en/docs/administer/product-security/configuring-transport-level-security.md

This PR removes ThriftAuthenticationService TLS configurations.
Related issue: https://github.com/wso2/docs-apim/issues/4365

[3.0.0] Remove ThriftAuthenticationService TLS config

---

en/docs/install-and-setup/setup/security/configuring-transport-level-security.md

This PR removes ThriftAuthenticationService TLS configurations.
Related issue: https://github.com/wso2/docs-apim/issues/4365

[3.1.0] Remove ThriftAuthenticationService TLS config

---

en/docs/install-and-setup/upgrading-wso2-is-as-key-manager/upgrading-from-is-km-520-to-5100.md

Fix incorrect links in "Upgrading WSO2 IS as Key Manager from 5.2.0 to 5.10.0" documentation
Related Issue: https://github.com/wso2/docs-apim/issues/3946

Fix Incorrect Links in "Upgrading WSO2 IS as Key Manager from 5.2.0 to 5.10.0" Documentation

---

en/docs/install-and-setup/setup/api-controller/managing-apis-api-products/importing-apis-via-dev-first-approach.md

Add a note stating the requirement to change template file before using in Dev first approach to avoid confusion.
Affected Page: https://apim.docs.wso2.com/en/latest/install-and-setup/setup/api-controller/managing-apis-api-products/importing-apis-via-dev-first-approach/
Fixes https://github.com/wso2/docs-apim/issues/4433 for APIM 4.0.0 Docs

[4.0.0] Add a note stating the requirement to change template file before using in Dev first approach

---

en/docs/install-and-setup/upgrading-wso2-api-manager/upgrading-from-260-to-400.md

To fix the ORA-02270: no matching unique or primary key for this column-list error when running the Oracle DB Script against the WSO2AM_DB database.
- There is a missed primary key constraint to the column: COMMENT_ID for Oracle DB in the doc [1]. 
- When analyzing with the MSSQL script in the same doc [1], we have given the primary key constraint to the column: COMMENT_ID.
- Hence adding these changes.
[1] https://apim.docs.wso2.com/en/latest/install-and-setup/upgrading-wso2-api-manager/upgrading-from-260-to-400/#step-2-upgrade-api-manager-to-400

Fix Error from executing Oracle DB Scripts: APIM 2.6.0 to 4.0.0 Migration

---

en/docs/develop/product-apis/devportal-apis/devportal-v1/devportal-v1.yaml

To fix the Postman request failure in getting SDKs
Corrected the miscorrect request path as: `GET {{basepath}}/apis/{{apiId}}/sdks/{{language}}`

[3.2.0] Fix postman test collection get request failure for SDKs

---

en/docs/administer/logging-and-monitoring/logging/monitoring-http-access-logs.md
en/docs/reference/config-catalog.md

Add configuration to this doc [1] for the change done in this PR [2].
With the existing access log valve, the application's access logs get recorded or written into the http_access.log. file. This config enables a new valve that allows logs to get written into the wso2carbon.log or any other log file and show up on the console.
```
[http_access_log]
useLogger = true
```
[1].https://apim.docs.wso2.com/en/3.2.0/administer/logging-and-monitoring/logging/monitoring-http-access-logs/#configuring-access-logs-for-the-http-servlet-transport
[2]. https://github.com/wso2/carbon-kernel/pull/2661
1. Add the new config under the relevant topic in 3.2.0 docs.
2. Add new config into configuration catalog [3].
3. Fixes #3324 for 3.2.0 documentation.
[3]. …

[3.2.0] Fixes #3324 issue

---

en/docs/reference/connectors/amazonsqs-connector/amazonsqs-connector-config.md
en/docs/reference/connectors/amazonsqs-connector/amazonsqs-connector-overview.md

With https://github.com/wso2-extensions/esb-connector-amazonsqs/pull/25 when the MI/EI server is running in an EC2 instance, the user can set the IAM role for authentication This doc adds the related new changes.
- Update the init configuration docs.

Update Amazon SQS connector docs with IAM role for authentication

---

en/docs/reference/connectors/amazonsqs-connector/amazonsqs-connector-config.md
en/docs/reference/connectors/amazonsqs-connector/amazonsqs-connector-overview.md

With https://github.com/wso2-extensions/esb-connector-amazonsqs/pull/25 when the MI/EI server is running in an EC2 instance, the user can set the IAM role for authentication This doc adds the related new changes.
- Update the init configuration docs.

[Master] Update Amazon SQS connector docs with IAM role for authentication

---

en/docs/learn/rate-limiting/introducing-throttling-use-cases.md

This PR adds the link to advanced throttling policies page from the throttling use cases page.
Fixes: https://github.com/wso2/docs-apim/issues/3285

[3.0.0] Add link to advanced throttling policies

---

en/docs/learn/rate-limiting/introducing-throttling-use-cases.md

This PR adds the link to advanced throttling policies page from the throttling use cases page.
Fixes: https://github.com/wso2/docs-apim/issues/3285

[3.1.0] Add link to advanced throttling policies

---

en/docs/install-and-setup/install/installing-the-product/running-the-api-m.md

> To update the instructions so that the bind-address can be set for Windows.
> A Windows user can successfully define a new bind-address.
> Oracle JDK 8, Windows 10 Pro

Update Windows bind-address

---

en/docs/tutorials/scenarios/scenario-overview.md

Changed docker-compose logs -d to docker-compose logs -f in order to display the log output.
The existing `docker-compose logs -d` doesn't give the log output. So updated the document with the correct command `docker-compose logs -f`.
The existing `docker-compose logs -d` command didn't give the logout. It returned the following message in the terminal.
```docker-compose logs -d
View output from containers.
Usage: logs [options] [--] [SERVICE...]
Options:
--no-color              Produce monochrome output.
-f, --follow            Follow log output.
-t, --timestamps        Show timestamps.
--tail="all"            Number of lines to show from the end of the logs
for each container.
--no-log-prefix         Don't print prefix in logs.
```

Updated the log output command

---

en/docs/observe/api-manager/monitoring-http-access-logs.md
en/docs/reference/config-catalog.md
en/tools/config-catalog-generator/data/http_access_log.toml

Add configuration to this doc [1] for the change done in this PR [2].
With the existing access log valve, the application's access logs get recorded or written into the http_access.log. file. This config enables a new valve that allows logs to get written into the wso2carbon.log or any other log file and show up on the console.
```
[http_access_log]
useLogger = true
```
[1].https://apim.docs.wso2.com/en/latest/observe/api-manager/monitoring-http-access-logs/
[2]. https://github.com/wso2/carbon-kernel/pull/2661
1. Add the new config under the relevant topic in 4.0.0 docs.
2. Add new config into configuration catalog [3].
3. Fixes #3324 for 4.0.0 documentation.
[3]. https://apim.docs.wso2.com/en/latest/reference/config-catalog/

[4.0.0] Add http_access log config and Fixes #3324 issue

---

en/docs/install-and-setup/install/installing-the-product/running-the-mi-dashboard-as-windows-service.md
en/mkdocs.yml

$subject. Running MI Dashboard as a windows service support was added recently with wso2/product-mi-tooling#225. This document will add the relevant documentation. Related to wso2/micro-integrator#2259

Add docs on running MI dashboard as a windows service

---

en/docs/reference/customize-product/customizations/advanced-ui-customization.md

Due to security concerns and for reliability it's better to use `npm ci`

Update package installation command

---

en/docs/deploy-and-publish/deploy-on-gateway/choreo-connect/configurations/enforcer-configurations.md
en/docs/deploy-and-publish/deploy-on-gateway/choreo-connect/configurations/router-configurations.md
en/tools/config-catalog-generator-cc/data/enforcer/configs.json
en/tools/config-catalog-generator-cc/data/router/configs.json
en/tools/config-catalog-generator-cc/dist/enforcer-configurations.md
en/tools/config-catalog-generator-cc/dist/router-configurations.md

Fixing typos related to configurations of CC. 
PR comments - https://github.com/wso2/docs-apim/pull/5039/files

[CC 1.0.0] Fixing typos in CC configurations [4.0.0]

---

en/docs/deploy-and-publish/deploy-on-gateway/choreo-connect/configurations/enforcer-configurations.md
en/docs/deploy-and-publish/deploy-on-gateway/choreo-connect/configurations/router-configurations.md
en/tools/config-catalog-generator-cc/data/enforcer/configs.json
en/tools/config-catalog-generator-cc/data/router/configs.json
en/tools/config-catalog-generator-cc/dist/enforcer-configurations.md
en/tools/config-catalog-generator-cc/dist/router-configurations.md

Fixing typos related to configurations of CC. 
PR comments - https://github.com/wso2/docs-apim/pull/5039/files

[CC 1.0.0] Fixing typos in CC configurations [Master]

---

en/docs/develop/product-apis/advanced-configurations.md
en/mkdocs.yml

- fixes CORS Configuration not available in APIM 3.1.0 and 3.0.0 documentation #5080

fixes https://github.com/wso2/docs-apim/issues/5080 #5081

---

en/docs/integrate/develop/integration-development-kickstart.md

> Fix broken link to the DoctorInfo-JDK11.jar file.
> Better experience for users of the documentation.

Fix broken link for DoctorInfo-JDK11.jar

---

en/docs/install-and-setup/upgrading-wso2-api-manager/upgrading-from-260-to-400.md

To fix the ORA-02270: no matching unique or primary key for this column-list error when running the Oracle DB Script against the WSO2AM_DB database.
- There is a missed primary key constraint to the column: COMMENT_ID for Oracle DB in the doc [1]. 
- When analyzing with the MSSQL script in the same doc [1], we have given the primary key constraint to the column: COMMENT_ID.
- Hence adding these changes.
[1] https://apim.docs.wso2.com/en/latest/install-and-setup/upgrading-wso2-api-manager/upgrading-from-260-to-400/#step-2-upgrade-api-manager-to-400

[4.0.0] Fix Error from executing Oracle DB Scripts: APIM 2.6.0 to 4.0.0 Migration

---

en/docs/learn/api-controller/getting-started-with-wso2-api-controller.md

Update the **Formatting the outputs of list** [1] section in **Getting Started with WSO2 API Controller**[2] to add newly supported "jsonArray" format type.
[1] https://apim.docs.wso2.com/en/3.2.0/learn/api-controller/getting-started-with-wso2-api-controller/#formatting-the-outputs-of-list
[2] https://apim.docs.wso2.com/en/3.2.0/learn/api-controller/getting-started-with-wso2-api-controller/
Fixes https://github.com/wso2/product-apim-tooling/issues/857 for 3.2.0

[3.2.0] Update listing formats section in APICTL

---

en/docs/google186eb945fa6366b0.html

- Removing Google Console ref because this uses the same refer as 4.0.0 which is incorrect. The ref should be unique.

Removing Google Console ref

---

en/docs/reference/connectors/exporting-artifacts.md
en/docs/reference/connectors/importing-connector-to-integration-studio.md

- fixes https://github.com/wso2/docs-apim/issues/5317
- {{base_path}} does not work in these instances when single sourcing content and including (pulling) pages so that it can be displayed in other pages. Therefore, the URLs had to be hardcoded it in for the images to appear.

fixes https://github.com/wso2/docs-apim/issues/5317

---

en/docs/assets/css/theme.css

- fixed font and icon size of search
- fix related to https://github.com/wso2/docs-apim/issues/5395

reduced size of search icon and text

---

en/docs/tutorials/scenarios/scenario-overview.md

- Fix the login user names correctly by changing qunatis.com to quantis.com
- PR sync for https://github.com/wso2/docs-apim/pull/5501

Fix the login user names correctly

---

en/docs/install-and-setup/setup/security/logins-and-passwords/maintaining-logins-and-passwords.md

Throttling config has to be defined before its child configurations. Otherwise, there will be failures at the startup. This has to be fixed in all the other docs including 4.0.0, 3.2.0 and rest.

Fix the config ordering issue

---

en/docs/deploy-and-publish/deploy-on-gateway/choreo-connect/troubleshooting/adding-debug-logs.md

Added the following configuration as an example to router debug logs section to log request and response headers.
```
router:
environment:
- TRAILING_ARGS=TRAILING_ARGS=--component-log-level http:debug,http2:debug,conn_handler:debug
```

Added example log configuration to log request/response headers in router

---

.devcontainer/Dockerfile
.devcontainer/devcontainer.json

With this change document writers can run the mkdoc serve without leaving the browser via github codespaces.

add dev container support

---

en/docs/reference/synapse-properties/endpoint-properties.md

Fixes https://github.com/wso2/docs-apim/issues/5250
Fixes https://github.com/wso2/docs-apim/issues/4957
This PR will update the OAuth config section of HTTP endpoints with the following,
- Password grant configs for MI OAuth HTTP endpoints.
- Expression support for OAuth Configs.
- Option to specify custom params in OAuth request body.
- Indicate how the client credentials are passed to the token endpoint with the `authMode` property.
- Option to configure the OAuth cache timeout

Update HTTP endpoint OAuth Configs

---

en/docs/install-and-setup/setup/kubernetes-operators/k8s-api-operator/install.md

The API Operator installation command contains a broken url to the YAML file that returns 404, I replaced it with the correct one which was just to replace v2.0.2 by 2.0.2
Link inside API Operator installation gives a 404
fixed the url by the one provided inside the download page of github

Fixed broken YAML url

---

en/docs/learn/api-controller/advanced-topics/configuring-environment-specific-parameters.md

Add quotes to password in api_params.yaml file and add instruction to mandate quotes if password contains special characters in https://apim.docs.wso2.com/en/3.1.0/learn/api-controller/advanced-topics/configuring-environment-specific-parameters/.

Add quotes to passwoard in api_params.yaml

---

en/docs/install-and-setup/setup/api-controller/advanced-topics/configuring-different-endpoint-security-types.md
en/docs/install-and-setup/setup/api-controller/advanced-topics/configuring-environment-specific-parameters.md

Add quotes to password in api_params.yaml file, add instruction to mandate quotes if password contains special characters and fixed environment variable syntax in https://apim.docs.wso2.com/en/4.1.0/install-and-setup/setup/api-controller/advanced-topics/using-dynamic-data-in-api-controller-projects/.

Add quotes to passwoard in params.yaml

---

en/docs/deploy-and-publish/deploy-on-gateway/choreo-connect/deploy-api/deploy-rest-api-with-mock-impl.md
en/docs/design/endpoints/endpoint-types.md
en/docs/tutorials/develop-an-integration-with-a-managed-api.md
en/mkdocs.yml

- fixes https://github.com/wso2/docs-apim/issues/5795
- Details with regard to the fix
- As the 'design/prototype-api/create-a-prototype-api.md` page has been removed, a redirection was added for it.
- Fixed the broken links.

fixes https://github.com/wso2/docs-apim/issues/5795

---

en/docs/design/create-api/create-rest-api/generate-rest-api-from-soap-backend.md
en/docs/get-started/about-this-release.md

- Added Generate REST API from SOAP Backend feature as a deprecated feature
- fixes https://github.com/wso2/docs-apim/issues/5841

added deprecated feature

---

en/docs/learn/api-controller/advanced-topics/configuring-different-endpoint-types.md
en/docs/learn/api-controller/advanced-topics/configuring-environment-specific-parameters.md
en/mkdocs.yml

Documentation on setting up `api_params` with multi endpoint configurations.
- Add documentation for configuring the four (4) main types of endpoint types using the api_params.yaml file from the API Controller.
- Update `Configuring Environment Specific Parameters` document with added configuration parameters.
Setting up the endpoints with respect to the below nine (9) user scenarios have been documented for the reference of the user.
1. HTTP/REST Endpoint - Without load balancing or failover (the usual way)
2. HTTP/REST Endpoint - With load balancing
3. HTTP/REST Endpoint - With failover
4. HTTP/SOAP Endpoint - Without load balancing or failover
5. HTTP/SOAP Endpoint - With load balancing
6. HTTP/REST Endpoint - With failover
7. Dynamic Endpoint
8. AWS Lambda - Using IAM role-supplied …

Adding documentation on configuring different endpoint types from the API Controller 3.1.0

---

en/docs/install-and-setup/setup/reference/default-product-ports.md

Docs update related to the fix for https://github.com/wso2/api-manager/issues/175

Add instructions for disabling servlet transport in docs

---

en/docs/reference/config-catalog-mi.md
en/tools/config-catalog-generator-mi/data/configs.json
en/tools/config-catalog-generator-mi/dist/config-catalog.md

The following configurations are added to the MI config catalog.
Fixes https://github.com/wso2/docs-apim/issues/6032
For non-blocking service calls through a proxy server.
```
[transport.http]
sender.proxy_username = "admin"
sender.proxy_password = "admin"
```
For secured non-blocking service calls through a proxy server.
```
[transport.http]
sender.secured_proxy_username = "admin"
sender.secured_proxy_password = "admin"
```
For blocking service calls through a proxy server.
```
[transport.blocking.http]
sender.proxy_host = "localhost"
sender.proxy_port = 8080
sender.proxy_username = "admin"
sender.proxy_password = "admin"
```

[4.1.0] Add proxy username and password configs to MI catalog

---

en/docs/reference/config-catalog-mi.md
en/tools/config-catalog-generator-mi/data/configs.json
en/tools/config-catalog-generator-mi/dist/config-catalog.md

The following configurations are added to the MI config catalog.
Fixes https://github.com/wso2/docs-apim/issues/6032
For non-blocking service calls through a proxy server.
```
[transport.http]
sender.proxy_username = "admin"
sender.proxy_password = "admin"
```
For secured non-blocking service calls through a proxy server.
```
[transport.http]
sender.secured_proxy_username = "admin"
sender.secured_proxy_password = "admin"
```
For blocking service calls through a proxy server.
```
[transport.blocking.http]
sender.proxy_host = "localhost"
sender.proxy_port = 8080
sender.proxy_username = "admin"
sender.proxy_password = "admin"
```

Add proxy username and password configs to MI catalog

---

en/docs/deploy-and-publish/deploy-on-gateway/choreo-connect/troubleshooting/debug-memory.md
en/mkdocs.yml

$subject
Related to https://github.com/wso2/product-microgateway/issues/2997
Add following fields to mkdocs.yaml file, since there are many places Choreo Connect version is used in docs (for docker images)
```yaml
choreo_connect:
version: 1.1.0
envoy_version: v1.20.2
helm_chart:
version: 1.1.0-3
git_tag: 1.1.0.3
```

[4.1.0] Add heap dump docs for CC Router

---

en/docs/deploy-and-publish/deploy-on-gateway/choreo-connect/deploy-api/deploy-apis-as-immutable-gateway.md
en/docs/deploy-and-publish/deploy-on-gateway/choreo-connect/extensions/custom-filters.md
en/docs/deploy-and-publish/deploy-on-gateway/choreo-connect/getting-started/deploy/cc-as-a-standalone-gateway-on-kubernetes-helm-artifacts.md
en/docs/deploy-and-publish/deploy-on-gateway/choreo-connect/getting-started/deploy/cc-on-kubernetes-with-apim-as-control-plane-helm-artifacts.md
en/docs/deploy-and-publish/deploy-on-gateway/choreo-connect/git-integration.md
en/docs/deploy-and-publish/deploy-on-gateway/choreo-connect/production-deployment-guideline.md
en/docs/design/api-security/opa-validation/custom-opa-policy-for-choreo-connect.md
en/docs/get-started/about-this-release.md
en/docs/includes/deploy/cc-prod-guide-helm-values-yaml-tip.md
en/mkdocs.yml

Use a placeholder for the Choreo Connect version, since it is used in many places including docker images and Helm charts versions.

[4.1.0] Use placeholder for Choreo Connect version

---

en/docs/observe/api-manager/monitoring-correlation-logs.md
en/docs/reference/product-apis/devops-apis/devops-v0/devops-v0.yaml

Document changes needed in the enabling correlation logs section
is added and the changes done in the devops API description is
added to the docs as well.
> Fix: wso2/api-manager#275
> Fix: wso2/api-manager#533

Add the doc changes for enabling correlation logs during runtime

---

.gitignore
en/docs/observe/micro-integrator/classic-observability-traces/monitoring-with-opentelemetry-mi.md
en/requirements.txt

Fixed #6146 
Add the **"Jinja-like"** statement inside  {% raw %} ....  {% endraw %} tag. Example is given below.
```
{% raw %}
{%for property in opentelemetry.properties %}
opentelemetry.properties.{{property.header}} = {{property.key}}
{% endfor %}
{% endraw %}
```

Fixed the Jinja-like statement build issue

---

en/docs/integrate/develop/creating-artifacts/data-services/creating-data-services.md

The REST methods in Generate Data Service wizard are enabled depending on the database properties. This PR will add a note about those properties.
Fixes: https://github.com/wso2/api-manager/issues/293

Add note about REST methods in Generate Data Service docs

---

en/docs/observe/micro-integrator/classic-observability-logs/monitoring-correlation-logs.md

In MI, when correlation logs are enabled using the system property, we are not allowed to disable it using the Management API.  Added a note regarding that.
Fix : #6223

Add a note on disabling correlation logs during runtime

---

en/docs/install-and-setup/upgrading-wso2-api-manager/260-to-410/upgrading-from-260-to-410.md
en/docs/install-and-setup/upgrading-wso2-api-manager/300-to-410/upgrading-from-300-to-410.md
en/docs/install-and-setup/upgrading-wso2-api-manager/310-to-410/upgrading-from-310-to-410.md
en/docs/install-and-setup/upgrading-wso2-api-manager/320-to-410/upgrading-from-320-to-410.md

Secondary user stores for tenants are populated after migration.
https://github.com/wso2/docs-apim/issues/6239
remind users to copy secondary user stores.
Note added.

Add note to copy secondary user stores for tenants after migration

---

en/docs/api-analytics/samples/publishing-custom-analytics-data.md
en/mkdocs.yml

This PR will introduce a new tab under `api-analytics/samples` to guide programmers to publish custom analytics data.

[4.0.0] Add docs for publishing custom analytics data

---

en/docs/install-and-setup/setup/distributed-deployment/deploying-wso2-api-m-in-a-distributed-setup-with-tm-separated.md

This PR fixes the issues with the distributed setup config page for TM separated deployment. 
Previous doc contained several unwanted configurations and I have added the bare minimum configurations and further explained the usecase of each config.

Fix the TM separated distributed setup configurations

---

en/docs/api-analytics/samples/publishing-custom-analytics-data.md
en/mkdocs.yml

This PR will introduce a new tab under `api-analytics/samples` to guide programmers to publish custom analytics data.

[4.1.0] Add docs for publishing custom analytics data

---

en/docs/install-and-setup/upgrading-wso2-api-manager/260-to-410/upgrading-from-260-to-410.md
en/docs/install-and-setup/upgrading-wso2-api-manager/300-to-410/upgrading-from-300-to-410.md
en/docs/install-and-setup/upgrading-wso2-api-manager/310-to-410/upgrading-from-310-to-410.md
en/docs/install-and-setup/upgrading-wso2-api-manager/320-to-410/upgrading-from-320-to-410.md
en/docs/install-and-setup/upgrading-wso2-api-manager/400-to-410/upgrading-from-400-to-410.md

Add script for missing indices in registry db.
fixing : https://github.com/wso2/docs-apim/issues/6315
- REG_RESOURCE_TAG_IND_BY_REG_TAG_ID to REG_RESOURCE_TAG
- REG_RESOURCE_PROPERTY_IND_BY_REG_PROP_ID to REG_RESOURCE_PROPERTY
https://github.com/wso2/carbon-kernel/pull/3169

[4.1.0] Add missing registry db indices to REG_RESOURCE_PROPERTY and REG_RESOURCE_TAG

---

en/docs/install-and-setup/upgrading-wso2-api-manager/upgrading-from-1100-to-400.md
en/docs/install-and-setup/upgrading-wso2-api-manager/upgrading-from-200-to-400.md
en/docs/install-and-setup/upgrading-wso2-api-manager/upgrading-from-210-to-400.md
en/docs/install-and-setup/upgrading-wso2-api-manager/upgrading-from-220-to-400.md
en/docs/install-and-setup/upgrading-wso2-api-manager/upgrading-from-250-to-400.md
en/docs/install-and-setup/upgrading-wso2-api-manager/upgrading-from-260-to-400.md
en/docs/install-and-setup/upgrading-wso2-api-manager/upgrading-from-300-to-400.md
en/docs/install-and-setup/upgrading-wso2-api-manager/upgrading-from-310-to-400.md
en/docs/install-and-setup/upgrading-wso2-api-manager/upgrading-from-320-to-400.md

Add script for missing indices in registry db.
fixing : https://github.com/wso2/docs-apim/issues/6315
- REG_RESOURCE_TAG_IND_BY_REG_TAG_ID to REG_RESOURCE_TAG
- REG_RESOURCE_PROPERTY_IND_BY_REG_PROP_ID to REG_RESOURCE_PROPERTY
https://github.com/wso2/carbon-kernel/pull/3169

Add missing registry indices db script to documentation

---

en/docs/install-and-setup/setup/api-controller/getting-started-with-wso2-api-controller.md

The --export-directory of WSO2 API Controller (apictl) stands for the location to export not only APIs but also to store API Products and Applications. This PR fixes the unclarity of the definition in the documentation.
Modifying the definition --export-directory flag of apictl
Updated the definition of `apictl set --export-directory` flag to mention about API Products and Applications as well.

Modifying the definition --export-directory flag of apictl

---

en/docs/install-and-setup/setup/api-controller/getting-started-with-wso2-api-controller.md

The --export-directory of WSO2 API Controller (apictl) stands for the location to export not only APIs but also to store API Products and Applications. This PR fixes the unclarity of the definition in the documentation.
Modifying the definition --export-directory flag of apictl
Updated the definition of `apictl set --export-directory` flag to mention about API Products and Applications as well.

[4.1.0] Modifying the definition --export-directory flag of apictl

---

en/docs/install-and-setup/setup/api-controller/getting-started-with-wso2-api-controller.md

The --export-directory of WSO2 API Controller (apictl) stands for the location to export not only APIs but also to store API Products and Applications. This PR fixes the unclarity of the definition in the documentation.
Modifying the definition --export-directory flag of apictl
Updated the definition of `apictl set --export-directory` flag to mention about API Products and Applications as well.

[4.0.0] Modifying the definition --export-directory flag of apictl

---

en/docs/learn/api-controller/getting-started-with-wso2-api-controller.md

The --export-directory of WSO2 API Controller (apictl) stands for the location to export not only APIs but also to store API Products and Applications. This PR fixes the unclarity of the definition in the documentation.
Modifying the definition --export-directory flag of apictl
Updated the definition of `apictl set --export-directory` flag to mention about API Products and Applications as well.

[3.2.0] Modifying the definition --export-directory flag of apictl

---

en/docs/get-started/api-manager-quick-start-guide.md

The QSG of API Management contains the wrong APIM and apictl versions. This PR fixes it.
Fixing the APIM and apictl versioning in QSG
Mentioned using APIM 4.1.0 and apictl 4.1.0 (or the latest one in 4.1.x family)

Fixing the APIM and apictl versioning in QSG

---

en/docs/get-started/api-manager-quick-start-guide.md

The QSG of API Management contains the wrong APIM and apictl versions. This PR fixes it.
Fixing the APIM and apictl versioning in QSG
Mentioned using APIM 4.1.0 and apictl 4.1.0 (or the latest one in 4.1.x family)

[4.1.0] Fixing the APIM and apictl versioning in QSG

---

en/docs/get-started/api-manager-quick-start-guide.md

The QSG of API Management contains the wrong apictl version. This PR fixes it.
Fixing the apictl versioning in QSG
Mentioned using apictl 4.0.0 (or the latest one in 4.0.x family)

[4.0.0] Fixing the apictl versioning in QSG

---

en/requirements.txt

$subject
Do not work with python 3 if this version of jinja2 is not specified.
Python2 ARM installation is not there for Apple M1 machines.

[4.1.0] Add jinja2 version 3.0.3 as requirement for python3

---

en/requirements.txt

port https://github.com/wso2/docs-apim/pull/6403

[4.0.0] Add jinja2 version 3.0.3 as a requirement for python3

---

en/requirements.txt

port https://github.com/wso2/docs-apim/pull/6403

[3.0.0] Add jinja2 version 3.0.3 as a requirement for python3

---

en/requirements.txt

port https://github.com/wso2/docs-apim/pull/6403

[3.1.0] Add jinja2 version 3.0.3 as a requirement for python3

---

en/docs/design/api-security/api-authentication/secure-apis-using-oauth2-tokens.md

Changed "After you have the got the required credentials" -> "After you have got the required credentials"

Wrong use of word "the"

---

en/docs/administer/managing-users-and-roles/managing-user-stores/introduction-to-userstores.md
en/docs/install-and-setup/setup/deployment-best-practices/production-deployment-guidelines.md
en/docs/install-and-setup/setup/deployment-best-practices/security-guidelines-for-production-deployment.md
en/docs/install-and-setup/setup/security/configuring-keystores/configuring-keystores-in-wso2-api-manager.md
en/docs/install-and-setup/upgrading-wso2-api-manager/upgrading-from-1100-to-320.md
en/docs/install-and-setup/upgrading-wso2-api-manager/upgrading-from-200-to-320.md
en/docs/install-and-setup/upgrading-wso2-api-manager/upgrading-from-210-to-320.md
en/docs/install-and-setup/upgrading-wso2-api-manager/upgrading-from-220-to-320.md
en/docs/install-and-setup/upgrading-wso2-api-manager/upgrading-from-250-to-320.md
en/docs/install-and-setup/upgrading-wso2-api-manager/upgrading-from-260-to-320.md
en/docs/install-and-setup/upgrading-wso2-api-manager/upgrading-from-300-to-320.md
en/docs/install-and-setup/upgrading-wso2-api-manager/upgrading-from-310-to-320.md
en/docs/install-and-setup/upgrading-wso2-api-manager/upgrading-process.md
en/docs/install-and-setup/upgrading-wso2-is-as-key-manager/upgrading-from-is-km-5100-to-is-5100.md
en/docs/install-and-setup/upgrading-wso2-is-as-key-manager/upgrading-from-is-km-520-to-5100.md
en/docs/install-and-setup/upgrading-wso2-is-as-key-manager/upgrading-from-is-km-530-to-5100.md
en/docs/install-and-setup/upgrading-wso2-is-as-key-manager/upgrading-from-is-km-550-to-5100.md
en/docs/install-and-setup/upgrading-wso2-is-as-key-manager/upgrading-from-is-km-560-to-5100.md
en/docs/install-and-setup/upgrading-wso2-is-as-key-manager/upgrading-from-is-km-570-to-5100.md
en/docs/install-and-setup/upgrading-wso2-is-as-key-manager/upgrading-from-is-km-590-to-5100.md
en/docs/learn/api-controller/advanced-topics/configuring-different-endpoint-types.md
en/docs/learn/api-gateway/message-mediation/removing-specific-request-headers-from-response.md
en/docs/learn/design-api/endpoints/certificates.md

- Fixed typos and grammar issues.
- Copied the "Step 3.1 - Configure WSO2 API-M Analytics 3.2.0" section from the Upgrading from 3.2.0 to 2.5.0 docs to older versions, because they were requesting the users to refer to the 2.5.0 docs. 
- Fixed some common spelling mistakes and grammar mistakes that were identified.

Improved the 3.2.0 migration docs

---

en/docs/install-and-setup/setup/api-controller/getting-started-with-wso2-api-controller.md
en/docs/install-and-setup/setup/api-controller/managing-apis-api-products/managing-apis-and-api-products.md
en/docs/install-and-setup/setup/api-controller/managing-apis-api-products/migrating-api-products-to-different-environments.md
en/docs/install-and-setup/setup/api-controller/managing-common-api-policies/managing-common-api-policies.md
en/docs/install-and-setup/setup/api-controller/managing-common-api-policies/migrating-common-api-policies-to-different-environments.md

Fixes: https://github.com/wso2/docs-apim/issues/6453
Fixes: https://github.com/wso2/docs-apim/issues/6457
Adding documentation on common API Policy version support and import
- Added version-related changes to the documentation for,
- `apictl get policies api` command output
-  `apictl export policy api` command flags
-  `apictl delete policy api` command flags
- Added new documentation for `apictl import policy api`
- Fixed typos and formatting issues

[4.2.0] Adding documentation on common API Policy version support and import

---

en/docs/install-and-setup/setup/api-controller/getting-started-with-wso2-api-controller.md
en/docs/install-and-setup/setup/api-controller/managing-apis-api-products/managing-apis-and-api-products.md
en/docs/install-and-setup/setup/api-controller/managing-apis-api-products/migrating-api-products-to-different-environments.md
en/docs/install-and-setup/setup/api-controller/managing-common-api-policies/managing-common-api-policies.md
en/docs/install-and-setup/setup/api-controller/managing-common-api-policies/migrating-common-api-policies-to-different-environments.md

Fixes: https://github.com/wso2/docs-apim/issues/6453
Fixes: https://github.com/wso2/docs-apim/issues/6457
Adding documentation on common API Policy version support and import
- Added version-related changes to the documentation for,
- `apictl get policies api` command output
-  `apictl export policy api` command flags
-  `apictl delete policy api` command flags
- Added new documentation for `apictl import policy api`
- Fixed typos and formatting issues

Adding documentation on common API Policy version support and import

---

en/docs/install-and-setup/upgrading-wso2-api-manager/upgrading-from-200-to-400.md
en/docs/install-and-setup/upgrading-wso2-api-manager/upgrading-from-210-to-400.md
en/docs/install-and-setup/upgrading-wso2-api-manager/upgrading-from-220-to-400.md
en/docs/install-and-setup/upgrading-wso2-api-manager/upgrading-from-250-to-400.md
en/docs/install-and-setup/upgrading-wso2-api-manager/upgrading-from-260-to-400.md
en/docs/install-and-setup/upgrading-wso2-api-manager/upgrading-from-300-to-400.md
en/docs/install-and-setup/upgrading-wso2-api-manager/upgrading-from-310-to-400.md
en/docs/install-and-setup/upgrading-wso2-api-manager/upgrading-from-320-to-400.md

In https://github.com/wso2-extensions/apim-identity-migration-resources 
- `master` now has the latest IS migration client for IS `6.0.0` to be used for APIM `4.2.0` migrations and onwards. 
- `5.x.x` branch is used for APIM `4.0.0` and `4.1.0` migrations
Therefore the doc links are pointed to the latest stable build for `5.x.x` branch.
raised by : https://github.com/wso2-enterprise/wso2-apim-internal/issues/1161

[4.0.0] Point migration docs to the latest stable IS migration client for IS 5.x.x

---

en/docs/install-and-setup/upgrading-wso2-api-manager/260-to-410/upgrading-from-260-to-410.md
en/docs/install-and-setup/upgrading-wso2-api-manager/300-to-410/upgrading-from-300-to-410.md
en/docs/install-and-setup/upgrading-wso2-api-manager/310-to-410/upgrading-from-310-to-410.md
en/docs/install-and-setup/upgrading-wso2-api-manager/320-to-410/upgrading-from-320-to-410.md
en/docs/install-and-setup/upgrading-wso2-is-as-key-manager/upgrading-from-is-5100-to-is-5110.md
en/docs/install-and-setup/upgrading-wso2-is-as-key-manager/upgrading-from-is-km-5100-to-is-5110.md
en/docs/install-and-setup/upgrading-wso2-is-as-key-manager/upgrading-from-is-km-570-to-is-5110.md
en/docs/install-and-setup/upgrading-wso2-is-as-key-manager/upgrading-from-is-km-590-to-is-5110.md

In https://github.com/wso2-extensions/apim-identity-migration-resources 
- `master` now has the latest IS migration client for IS `6.0.0` to be used for APIM `4.2.0` migrations and onwards. 
- `5.x.x` branch is used for APIM `4.0.0` and `4.1.0` migrations
Therefore the doc links are pointed to the latest stable build for `5.x.x` branch.
raised by : https://github.com/wso2-enterprise/wso2-apim-internal/issues/1161

[4.1.0] Point migration docs to the latest stable IS migration client for IS 5.x.x

---

en/docs/install-and-setup/upgrading-wso2-is-as-key-manager/upgrading-from-is-5100-to-is-5110.md
en/docs/install-and-setup/upgrading-wso2-is-as-key-manager/upgrading-from-is-km-5100-to-is-5110.md
en/docs/install-and-setup/upgrading-wso2-is-as-key-manager/upgrading-from-is-km-520-to-is-5110.md
en/docs/install-and-setup/upgrading-wso2-is-as-key-manager/upgrading-from-is-km-530-to-is-5110.md
en/docs/install-and-setup/upgrading-wso2-is-as-key-manager/upgrading-from-is-km-550-to-is-5110.md
en/docs/install-and-setup/upgrading-wso2-is-as-key-manager/upgrading-from-is-km-560-to-is-5110.md
en/docs/install-and-setup/upgrading-wso2-is-as-key-manager/upgrading-from-is-km-570-to-is-5110.md
en/docs/install-and-setup/upgrading-wso2-is-as-key-manager/upgrading-from-is-km-590-to-is-5110.md

In https://github.com/wso2-extensions/apim-identity-migration-resources 
- `master` now has the latest IS migration client for IS `6.0.0` to be used for APIM `4.2.0` migrations and onwards. 
- `5.x.x` branch is used for APIM `4.0.0` and `4.1.0` migrations
Therefore the doc links are pointed to the latest stable build for `5.x.x` branch.
raised by : https://github.com/wso2-enterprise/wso2-apim-internal/issues/1161

[4.0.0] Point IS as KM migration docs to the latest stable IS migration client for IS 5.x.x

---

en/docs/learn/analytics/configuring-alerts.md

In APIM 3.2.0, `Settings` icon in the `devportal` has been removed. In order to access alert managing page users have to click on user name and choose `Configure Alerts`. However in the documentation for configuring abnormal requests per minute alert, it was mentioned to click on the `Settings` to open the alert managing page.

[3.2.0][APIM-Analytics] Update docs for devportal alert configuration

---

en/docs/index.md

Added 4.2.0 doc link and version as the pre-release.
Fixes https://github.com/wso2/docs-apim/issues/6518

Adding 4.2.0 link

---

en/docs/assets/js/theme.js

Fixing the pre-release doc link as it is auto added.
Related to https://github.com/wso2/docs-apim/issues/6518

Updated pre-release-version-documentation-link

---

en/docs/index.md

- Hard coded 4.2.0 link as the auto link was being generated incorrectly.
Related to https://github.com/wso2/docs-apim/issues/6518

fixing 4.2.0 link

---

en/docs/tutorials/scenarios/scenario-overview.md

In the point 1 under the deployment section https://apim.docs.wso2.com/en/4.1.0/tutorials/scenarios/scenario-overview/#deployment, user needs to clone the repo. With this pr, it is changed to download from a release location

Update 4.1.0 sample scenario resource location path

---

en/docs/install-and-setup/setup/reference/product-compatibility.md
en/docs/install-and-setup/setup/setting-up-databases/changing-default-databases/changing-to-mysql.md

> Fix for the issue https://github.com/wso2/docs-apim/issues/6542

Making mandatory to add 'character set latin1' when making the APIM mysql 8 database

---

en/docs/install-and-setup/setup/reference/supported-cipher-suites.md

Updated the list of secure Cipher Suites in [1].
[1] https://apim.docs.wso2.com/en/4.1.0/install-and-setup/setup/reference/supported-cipher-suites/

fixes A1487

---

en/docs/design/endpoints/endpoint-types.md

> Link Adding Dynamic Endpoints was wrong.
> fix the link.
> I search the original linked file in history and I found a commit that rename it. https://github.com/wso2/docs-apim/commit/aac8439e16f532537893e15e688dd7eacbaa1c7a?short_path=8a7ac90#diff-8a7ac90b31ab0df21ef79aea7729afc3a6c85ede1cc4becf392ec6aacf89f111

fix "Adding Dynamic Endpoints" link in endpoint-types.md

---

en/docs/deploy-and-publish/publish-on-dev-portal/publish-to-multiple-external-api-stores.md

Resolves: https://github.com/wso2/docs-apim/issues/6426
Changing the http://localhost:9443/devportal to https://localhost:9443/devportal , to avoid occurring the following error
`Bad Request
This combination of host and port requires TLS.`
https://apim.docs.wso2.com/en/4.2.0/deploy-and-publish/publish-on-dev-portal/publish-to-multiple-external-api-stores/

Changed the details of the documentation 'Adding an API to External Stores'

---

en/docs/reference/synapse-properties/transport-parameters/vfs-transport-parameters.md

Update the VFS parameters section with `StrictHostKeyChecking` parameter introduced via https://github.com/wso2-support/wso2-commons-vfs/pull/94 for WSO2 MI 4.1.0

[4.1.0] Update VFS paramters section with StrictHostKeyChecking parameter

---

en/docs/install-and-setup/install/installing-the-product/installing-api-m-as-a-windows-service.md

- When configured according to the docs, cannot run APIM On windows as a Service with Java 17.
- Related to https://github.com/wso2/api-manager/issues/1497
- Made the relevant doc changes with updated yajsw(13.05).
- Added the `open a console with administrative privileges` in relevant places.

Change instructions to be compatible with APIM 4.2.0 and Java 17

---

en/docs/install-and-setup/install/installing-the-product/installing-mi-as-a-windows-service.md

- Update docs to include instructions for running MI as a windows service on Java 17 with YAJSW.
- Related Issues: https://github.com/wso2/api-manager/issues/1506
- Made the relevant doc changes with updated YAJSW version 13.05.
- Updated the instructions to `Windows command prompt with administrative privileges`

Update instructions to support Java 17

---

en/docs/integrate/examples/scheduled-tasks/task-scheduling-simple-trigger.md

The current XPAth is missing the `ns:return` element and as a result, no values will be logged. This PR will append `ns:return` to the expression.

Update XPath expression in the main sequence of Task Scheduling example

---

en/docs/reference/config-catalog-mi-dashboard.md

We have removed the `client_secret` parameter from MI dashboard SSO configs via https://github.com/wso2/product-mi-tooling/pull/337

Remove client_secret parameter from MI dashboard SSO configs

---

en/docs/install-and-setup/install/installing-the-product/installing-si-as-windows-service.md

- Update docs to include instructions for running SI as a windows service on Java 17 with YAJSW.
- Related Issues: https://github.com/wso2/api-manager/issues/1506
- Add new `wrapper.conf` for the Streaming Integrator.
- Remove unnecessary instructions and screenshots which were used for the APIM docs. 
- Made the relevant doc changes with updated YAJSW version 13.05.
- Updated the instructions to `Windows command prompt with administrative privileges`.

Update instructions to support SI 4.2.0 and Java 17

---

en/docs/install-and-setup/install/installing-the-product/installing-api-m-as-a-windows-service.md
en/docs/install-and-setup/install/installing-the-product/running-the-mi-dashboard-as-windows-service.md

- When configured according to the docs, cannot run MI Dashboard On windows as a Service with Java 17.
- Related to https://github.com/wso2/api-manager/issues/1506
- Also fix typo in a previous PR.
- Made the relevant doc changes with updated yajsw(13.05).
- Added the `open a console with administrative privileges` in relevant places.

Change instructions to be compatible with MI Dashboard 4.2.0 and java 17

---

en/mkdocs.yml

> To add subscription deletion workflow doc page.
> Doc creation PR - https://github.com/wso2/docs-apim/pull/6707

Subscription deletion workflow doc link [4.1.0]

---

en/docs/administer/key-managers/configure-custom-connector.md

> the link 'invoke an API' is wrong
> fix the link 'invoke an API'
> I have searched the correct page on the website, compared the URL with the one here and figured out the issue
> Improve the user experience when using the 'configure a custom key manager' documentation 
> fix 'invoke an API' link on the 'configure a custom key manager' documentation page
> https://apim.docs.wso2.com/en/latest/administer/key-managers/configure-custom-connector/
> N/A
> N/A obviously
> N/A
- Unit tests 
> N/A
- Integration tests
> N/A
- Followed secure coding standards in http://wso2.com/technical-reports/wso2-secure-engineering-guidelines? no
> N/A
> …

fix invoke an API link

---

en/docs/observe/mi-observe/working-with-management-api.md

Adding new management API to change non-user credentials using any admin user credentials. Admin user credentials can be changed by the same admin or the super admin.
Adding a new Management API
https://apim.docs.wso2.com/en/latest/observe/mi-observe/working-with-management-api/
Resolved: https://github.com/wso2/docs-apim/issues/6983

Added the documentation for 'Update Users' in MI management API

---

en/docs/observe/mi-observe/working-with-management-api.md

Adding new management API to change non-user credentials using any admin user credentials. Admin user credentials can be changed by the same admin or the super admin.
Adding a new Management API
https://apim.docs.wso2.com/en/4.0.0/observe/mi-observe/working-with-management-api/
Resolved: https://github.com/wso2/docs-apim/issues/6983

[4.0.0] Added the documentation for 'Update Users' in MI management API

---

en/docs/observe/mi-observe/working-with-management-api.md

Adding new management API to change non-user credentials using any admin user credentials. Admin user credentials can be changed by the same admin or the super admin.
Adding a new Management API
https://apim.docs.wso2.com/en/latest/observe/mi-observe/working-with-management-api/
Resolved: https://github.com/wso2/docs-apim/issues/6983

[4.2.0] Added the documentation for 'Update Users' in MI management API

---

en/docs/observe/mi-observe/working-with-management-api.md

Adding new management API to change non-user credentials using any admin user credentials. Admin user credentials can be changed by the same admin or the super admin.
Adding a new Management API
https://apim.docs.wso2.com/en/4.1.0/observe/mi-observe/working-with-management-api/
Resolved: https://github.com/wso2/docs-apim/issues/6983

[4.1.0] Added the documentation for 'Update Users' in MI management API

---

en/docs/integrate/examples/json_examples/json-examples.md
en/docs/reference/mediators/script-mediator.md

Update script mediator docs with NashornJS removal from JDK and add steps to manually copy the jars
Fixes: https://github.com/wso2/api-manager/issues/1725

Update script mediator docs with NashornJS removal

---

en/docs/install-and-setup/setup/api-controller/advanced-topics/configuring-environment-specific-parameters.md

With the PR [1] we have added the support to adding additional Properties to the params.yaml file which can be used to override the additionalProperties of the exported APIs when importing it to the new environment (Similar to overriding the production/sandbox urls using the params.yaml file).
Fixes: https://github.com/wso2/api-manager/issues/1862
[1] https://github.com/wso2-support/carbon-apimgt/pull/5924

[4.2.0] Doc changes for additionalProperties in the params.yaml

---

en/docs/install-and-setup/setup/api-controller/advanced-topics/configuring-environment-specific-parameters.md

With the PR [1] we have added the support to adding additional Properties to the params.yaml file which can be used to override the additionalProperties of the exported APIs when importing it to the new environment (Similar to overriding the production/sandbox urls using the params.yaml file).
Fixes: https://github.com/wso2/api-manager/issues/1862
[1] https://github.com/wso2-support/carbon-apimgt/pull/5923

[4.0.0] Doc changes for additionalProperties in the params.yaml

---

en/docs/install-and-setup/setup/api-controller/advanced-topics/configuring-environment-specific-parameters.md

With the PR [1] we have added the support to adding additional Properties to the params.yaml file which can be used to override the additionalProperties of the exported APIs when importing it to the new environment (Similar to overriding the production/sandbox urls using the params.yaml file).
Fixes: https://github.com/wso2/api-manager/issues/1862
[1] https://github.com/wso2/carbon-apimgt/pull/12033

Doc changes for additionalProperties in the params.yaml

---

en/docs/install-and-setup/setup/api-controller/advanced-topics/configuring-environment-specific-parameters.md

With the PR [1] we have added the support to adding additional Properties to the params.yaml file which can be used to override the additionalProperties of the exported APIs when importing it to the new environment (Similar to overriding the production/sandbox urls using the params.yaml file).
Fixes: https://github.com/wso2/api-manager/issues/1862
[1] https://github.com/wso2-support/carbon-apimgt/pull/5925

[4.1.0] Doc changes for additionalProperties in the params.yaml

---

en/docs/integrate/develop/creating-artifacts/creating-an-api.md

Add a note about the naming convention for the soap to rest feature

Add a note about the naming convention for the soap to rest feature

---

en/docs/deploy-and-publish/deploy-on-gateway/choreo-connect/configurations/enforcer-configurations.md
en/docs/deploy-and-publish/deploy-on-gateway/choreo-connect/configurations/router-configurations.md
en/docs/deploy-and-publish/deploy-on-gateway/choreo-connect/getting-started/supported-features.md
en/docs/deploy-and-publish/deploy-on-gateway/choreo-connect/security/api-authentication/mutual-ssl-authentication.md
en/docs/deploy-and-publish/deploy-on-gateway/deploying-apis-in-api-gateway-vs-choreo-connect.md
en/docs/design/api-security/api-authentication/secure-apis-using-mutual-ssl.md
en/docs/includes/design/create-mtls-api.md
en/docs/includes/design/handling-mtls-ssl-termination.md
en/docs/includes/design/invoke-mtls-api-using-postman.md
en/mkdocs.yml
en/tools/config-catalog-generator-cc/data/enforcer/configs.json
en/tools/config-catalog-generator-cc/data/enforcer/mutual_ssl.toml
en/tools/config-catalog-generator-cc/data/router/configs.json
en/tools/config-catalog-generator-cc/data/router/downstream_tls.toml
en/tools/config-catalog-generator-cc/dist/control-plane-configurations.md
en/tools/config-catalog-generator-cc/dist/enforcer-configurations.md
en/tools/config-catalog-generator-cc/dist/router-configurations.md
en/tools/config-catalog-generator-cc/package-lock.json

$subject
Backporing: https://github.com/wso2/docs-apim/pull/6225/files
https://github.com/wso2-enterprise/wso2-apim-internal/issues/2840
Existing page: https://apim.docs.wso2.com/en/4.0.0/design/api-security/api-authentication/secure-apis-using-mutual-ssl/
Updated with this PR (moved common in APIM and CC to "includes" location)

[CC 1.0.0.20] Add Mutual SSL Authentication support for CC as an update

---

en/docs/design/api-policies/attach-policy.md

- This PR adds the following doc changes related to the `API Level Policy` feature introduced via https://github.com/wso2-enterprise/wso2-apim-internal/issues/2618. It states how one can enable the API level policy feature.

Add database scripts and config details for API level policy support

---

en/docs/design/api-policies/attach-policy.md

- This PR adds the following doc changes related to the `API Level Policy` feature introduced via https://github.com/wso2-enterprise/wso2-apim-internal/issues/2618. It states how one can enable the API level policy feature.

[APIM] [4.1.0] Add database scripts and config details for API level policy support

---

en/docs/install-and-setup/setup/advance-configurations/changing-the-default-transport.md

Fixes: 
- https://github.com/wso2-enterprise/wso2-apim-internal/issues/1211

APIM 3.1.0 - Add note about additional `passthru_http` parameters

---

en/docs/reference/config-catalog-mi.md

This PR is to fix broken links on the [MI Config Catalog](https://apim.docs.wso2.com/en/latest/reference/config-catalog-mi/) page.
This will fix https://github.com/wso2-enterprise/wso2-mi-internal/issues/18.

[4.2.0] Fix broken links

---

en/docs/reference/config-catalog-mi.md

This PR is to fix broken links on the [MI Config Catalog](https://apim.docs.wso2.com/en/4.1.0/reference/config-catalog-mi/) page.
This will fix https://github.com/wso2-enterprise/wso2-mi-internal/issues/18.

[4.1.0] Fix broken links

---

en/docs/reference/config-catalog-mi.md

This PR is to fix broken links on the [MI Config Catalog](https://apim.docs.wso2.com/en/4.0.0/reference/config-catalog-mi/) page.
This will fix https://github.com/wso2-enterprise/wso2-mi-internal/issues/18.

[4.0.0] Fix broken links

---

en/docs/learn/api-controller/getting-started-with-wso2-api-controller.md

This PR adds the download links for APICTL 3.2.8 release and update the version in the APICTL docs.

[3.2.0] Update version and download links for APICTL 3.2.8

---

en/docs/assets/versions.json

This PR is to update the URLs for previous APIM doc versions on the [Versions](https://apim.docs.wso2.com/en/versions/) page.

Update URLs for previous APIM doc versions

---

en/docs/integrate/examples/file-processing/accessing_windows_share_using_vfs_transport.md

This PR is to fix a broken link on the [Accessing a Windows Share using VFS](https://apim.docs.wso2.com/en/4.1.0/integrate/examples/file-processing/accessing_windows_share_using_vfs_transport/#!) page.

Fix broken link

---

en/docs/reference/connectors/file-connector/file-connector-config.md

This PR is to update info on the `move` operator for File Connector v4.x. 
Issue reference: https://github.com/wso2-enterprise/wso2-mi-internal/issues/17

[4.2.0] Update info on the `move` operator

---

en/docs/reference/connectors/file-connector/file-connector-config.md

This PR is to update info on the `move` operator for File Connector v4.x. 
Issue reference: https://github.com/wso2-enterprise/wso2-mi-internal/issues/17

[4.1.0] Update info on the `move` operator

---

en/docs/reference/connectors/file-connector/file-connector-config.md

This PR is to update info on the `move` operator for File Connector v4.x. 
Issue reference: https://github.com/wso2-enterprise/wso2-mi-internal/issues/17

[Master] Update info on the move operator

---

en/docs/reference/config-catalog-mi.md

The following needs to updated in the https://apim.docs.wso2.com/en/latest/reference/config-catalog-mi/#https-transport-non-blocking-mode page,
The HTTP transport keystores (https://apim.docs.wso2.com/en/latest/reference/config-catalog-mi/#https-transport-non-blocking-mode)
listener.keystore.file_name --> listener.keystore.location
sender.keystore.file_name --> sender.keystore.location
listener.truststore.file_name -- > listener.truststore.location
sender.truststore.file_name --> sender.truststore.location
Management API configs (https://apim.docs.wso2.com/en/latest/reference/config-catalog-mi/#management-api-cors)
Need to have only single square bracket for the below property
[[management_api.cors]] --> [management_api.cors]
Possible Values under allowed_origins should be "any string" …

Fix misconfigurations in MI config catalog doc

---

en/docs/integrate/examples/file-processing/accessing_windows_share_using_vfs_transport.md

This PR is to remove `[port]` from the connection URI format.

[4.0.0] Update accessing_windows_share_using_vfs_transport.md

---

en/docs/integrate/examples/file-processing/accessing_windows_share_using_vfs_transport.md

This PR is to remove `[port]` from the connection URI format.

[4.1.0] Update accessing_windows_share_using_vfs_transport.md

---

en/docs/integrate/examples/file-processing/accessing_windows_share_using_vfs_transport.md

This PR is to remove `[port]` from the connection URI format.

[4.2.0] Update accessing_windows_share_using_vfs_transport.md

---

en/docs/install-and-setup/setup/deployment-best-practices/basic-health-checks.md

Add a note on health-check API for gateway to verify the deployment status of the APIs.
Related issue: https://github.com/wso2-enterprise/wso2-apim-internal/issues/4752

[4.1.0] Add a note on gateway health-check API

---

en/docs/install-and-setup/setup/deployment-best-practices/basic-health-checks.md

Add a note on health-check API for gateway to verify the deployment status of the APIs.
Related issue: https://github.com/wso2-enterprise/wso2-apim-internal/issues/4752

[4.2.0] Add a note on gateway health-check API

---

en/docs/install-and-setup/setup/deployment-best-practices/basic-health-checks.md

Add a note on health-check API for gateway to verify the deployment status of the APIs.
Related issue: https://github.com/wso2-enterprise/wso2-apim-internal/issues/4752

Add a note on gateway health-check API

---

en/docs/deploy-and-publish/deploy-on-gateway/api-gateway/scaling-the-gateway.md

This PR adds a note on potential issues user could come across when starting multiple gateway nodes with a single CP.
Related issue: https://github.com/wso2-enterprise/wso2-apim-internal/issues/4753

Add a note on gateway scaling with CP

---

en/docs/deploy-and-publish/deploy-on-gateway/choreo-connect/configurations/router-configurations.md
en/tools/config-catalog-generator-cc/data/router/configs.json
en/tools/config-catalog-generator-cc/data/router/router.toml
en/tools/config-catalog-generator-cc/dist/router-configurations.md

> $subject
The added config will be visible as follows : 
Note: Since the existing structure rendered from config.json doesn't support an additional banner view, it was added into the .md file directly. The corresponding change was not added to the same file in dist because it may cause conflicts in further modifications to config.json. Hence the contents in en/docs/deploy-and-publish/deploy-on-gateway/choreo-connect/configurations/router-configurations.md and en/tools/config-catalog-generator-cc/dist/router-configurations.md have a diff from this onwards.

Update documentation for the added config to modify the buffered payload limit in choreo connect.

---

en/docs/reference/product-apis/devportal-apis/devportal-v3/devportal-v3.yaml

When there are multiple APIs in an environment, it's possible to get details of a specific API by passing the API name as a query parameter.  The solution for this is to include the API name within the double quotes.
The relevant instructions are updated in the documentation with this PR

Updated API  Retrieve/Search instructions

---

en/docs/design/create-api/create-rest-api/generate-rest-api-from-soap-backend.md

This PR adds the limitations of the SOAP to REST feature in APIM. Changes are added to [1].
The doc after the changes look like below.
After expanding the collapsible sections, the docs look like below.
[1] https://apim.docs.wso2.com/en/4.1.0/design/create-api/create-rest-api/generate-rest-api-from-soap-backend/

[4.1.0] Add limitations of the SOAP to REST feature

---

en/docs/design/create-api/create-rest-api/generate-rest-api-from-soap-backend.md

This PR adds the limitations of the SOAP to REST feature in APIM. Changes are added to [1].
The doc after the changes look like below.
After expanding the collapsible sections, the docs look like below.
[1] https://apim.docs.wso2.com/en/latest/design/create-api/create-rest-api/generate-rest-api-from-soap-backend/

[4.2.0] Add limitations of the SOAP to REST feature

---

en/docs/deploy-and-publish/deploy-on-gateway/choreo-connect/configurations/router-configurations.md
en/tools/config-catalog-generator-cc/data/router/configs.json
en/tools/config-catalog-generator-cc/dist/router-configurations.md

Configurations related to the fix done for issue [1].
Added below new configs.
```toml
[router.downstream.tls]
minimumProtocolVersion = "TLS1_0"
maximumProtocolVersion = "TLS1_2"
ciphers = "ECDHE-ECDSA-AES128-GCM-SHA256, ECDHE-RSA-AES128-GCM-SHA256, ECDHE-ECDSA-AES128-SHA, ECDHE-RSA-AES128-SHA, AES128-GCM-SHA256, AES128-SHA, ECDHE-ECDSA-AES256-GCM-SHA384, ECDHE-RSA-AES256-GCM-SHA384, ECDHE-ECDSA-AES256-SHA, ECDHE-RSA-AES256-SHA, AES256-GCM-SHA384, AES256-SHA"
```
Each above config will specify the following.
- minimumProtocolVersion : Minimum TLS protocol version
- maximumProtocolVersion : Maximum TLS protocol version
- ciphers :  If specified, the TLS listener will only support the specified ciphers when negotiating TLS 1.0-1.2 .(this setting has no effect when negotiating TLS 1.3) …

Add downstream.tls cipher and version configs

---

en/docs/integrate/examples/json_examples/json-examples.md

Updated the syntax related to payloadFactory mediation for JSON body retrieval in Json Examples page. The expression ($.) is updated to ($) in Json Body.

Updated the expression related to Json Body Retrieval 

---

en/docs/install-and-setup/setup/security/logins-and-passwords/maintaining-logins-and-passwords.md

When creating admin password, "£" is considered as a restricted character since it causes a buffer overflow exception.
Documentation is updated with relevant details with this PR

Updated maintaining-logins-and-passwords page

---

en/docs/administer/key-managers/configure-wso2is-connector.md

Fixes related to the `Certificates` section under the Key Manager configurations of "Configure WSO2 IS as a Key Manager" documentation. Refer to the screenshot below for the fixed description.

[4.0.0] Fix certificates section under the Key Manager configurations

---

en/docs/administer/key-managers/configure-wso2is-connector.md

Fixes related to the `Certificates` section under the Key Manager configurations of "Configure WSO2 IS as a Key Manager" documentation. Refer to the screenshot below for the fixed description.

[Master] Fix certificates section under the Key Manager configurations

---

en/docs/install-and-setup/setup/setting-up-databases/changing-default-databases/changing-to-mariadb.md
en/docs/install-and-setup/setup/setting-up-databases/overview.md
en/mkdocs.yml

- Removing MariaDB from docs
- Removing as customers are still referring to our docs on how to change the default database to MariaDB

[Master] Remove MariaDB from docs 

---

en/docs/install-and-setup/setup/setting-up-databases/changing-default-databases/changing-to-mariadb.md
en/docs/install-and-setup/setup/setting-up-databases/overview.md
en/mkdocs.yml

- Removing MariaDB from docs
- Removing as customers are still referring to our docs on how to change the default database to MariaDB

[4.2.0] Remove MariaDB from docs

---

en/docs/install-and-setup/setup/setting-up-databases/changing-default-databases/changing-to-mariadb.md
en/docs/install-and-setup/setup/setting-up-databases/overview.md
en/mkdocs.yml

- Removing MariaDB from docs
- Removing as customers are still referring to our docs on how to change the default database to MariaDB

[4.1.0] Remove MariaDB from docs

---

en/docs/install-and-setup/setup/setting-up-databases/changing-default-databases/changing-to-mariadb.md
en/docs/install-and-setup/setup/setting-up-databases/overview.md
en/mkdocs.yml

- Removing MariaDB from docs
- Removing as customers are still referring to our docs on how to change the default database to MariaDB

[4.0.0] Remove MariaDB from docs

---

en/docs/reference/customize-product/customizations/customize-the-api-store-and-gateway-urls-for-tenants.md

Documentation on setting up custom URLs for Devportal has missing steps which gives different issues when accessing the portal.
Add missing steps to the document to make it worked without any issue.

Fix: Setting Up Custom URL for Devportal

---

en/docs/integrate/examples/json_examples/json-examples.md

Updated the syntax related to payloadFactory mediation for JSON body retrieval in Json Examples page. The expression `($.)` is updated to `($)` in Json Body.

[410] Updated json-examples page

---

en/docs/integrate/examples/json_examples/json-examples.md

Updated the syntax related to payloadFactory mediation for JSON body retrieval in Json Examples page. The expression `($.)` is updated to `($)` in Json Body.

[420] Updated json-examples page

---

en/docs/integrate/examples/json_examples/json-examples.md

Updated the syntax related to payloadFactory mediation for JSON body retrieval in Json Examples page. The expression `($.)` is updated to `($)` in Json Body.

Updated json-examples page

---

en/docs/administer/multitenancy/managing-tenants.md

As per API-M 3.2.0 `carbon.xml.j2` the config should change from `tenant_mgt.tenant_deletion` to `Tenant.TenantDelete`
https://github.com/wso2/docs-apim/pull/6811

[3.2.0] Fix Tenant Deletion Config Name

---

en/docs/administer/key-managers/configure-global-key-manager.md

- Add note about password and code grant usages to Global Key Manager documentation [1] added using [2]
[1] https://apim.docs.wso2.com/en/4.3.0/administer/key-managers/configure-global-key-manager/
[2] https://github.com/wso2/docs-apim/pull/7656

[4.3.0] Add Note About Password and Code Grant Usages to Global Key Manager Documentation

---

en/docs/deploy-and-publish/deploy-on-gateway/api-gateway/threat-protectors/regular-expression-threat-protection-for-api-gateway.md

Fixes https://github.com/wso2/api-manager/issues/2549
docs issue : https://github.com/wso2/docs-apim/issues/7722
Note : Could not find a fix for displaying the special chars in different color. Even ` ```text `did not work.

[4.2.0] Fix regex for JavaScript Injection

---

en/docs/deploy-and-publish/deploy-on-gateway/api-gateway/threat-protectors/regular-expression-threat-protection-for-api-gateway.md

Fixes https://github.com/wso2/api-manager/issues/2549
docs issue : https://github.com/wso2/docs-apim/issues/7722
Note : Could not find a fix for displaying the special chars in different color. Even ` ```text `did not work.

[4.1.0] Fix JS Injection regex

---

en/docs/deploy-and-publish/deploy-on-gateway/api-gateway/threat-protectors/regular-expression-threat-protection-for-api-gateway.md

Fixes indentation of regex.
Related PR : https://github.com/wso2/docs-apim/pull/7731

[4.1.0] Fix indentation of JS Injection Regex

---

en/docs/administer/key-managers/configure-wso2is-connector.md

> $Subject. When copy-pasting values directly from this doc, providing the current value (`https://localhost:9444/services` as the Issuer URL) will lead to an invalid token during token validation.

[4.3.0] Update Issuer URL in IS as a KM Docs

---

en/docs/design/api-security/oauth2/token-revocation.md

This PR removes outdated notes on token revocation regarding the JWT Grant.
Related issue: https://github.com/wso2/api-manager/issues/2647

Remove invalid doc notes on token revocation

---

en/docs/install-and-setup/setup/security/securing-api-m-web-portals.md

Doc for https://github.com/wso2/api-manager/issues/2496

Add doc for portal JWT

---

en/docs/install-and-setup/setup/api-controller/cicd-using-cli.md
en/docs/install-and-setup/setup/api-controller/getting-started-with-wso2-api-controller.md

- Fix https://github.com/wso2/docs-apim/issues/7802
- Update APICTL docs for 4.3.0 release
- Add missing flag for `apictl export api-product`

[4.3.0] Update APICTL 4.3.0 docs

---

en/docs/install-and-setup/setup/api-controller/cicd-using-cli.md
en/docs/install-and-setup/setup/api-controller/getting-started-with-wso2-api-controller.md

- Fix https://github.com/wso2/docs-apim/issues/7802
- Update APICTL docs for 4.3.0 release
- Add missing flag for `apictl export api-product`

Update APICTL 4.3.0 docs 

---

en/docs/install-and-setup/setup/distributed-deployment/configuring-wso2-identity-server-as-a-key-manager.md

This PR adds the config to disable group and role separation in IS for the IS as KM setup.
Fixes https://github.com/wso2/docs-apim/issues/7792

[4.3.0] Add config to disable group and role separation in IS

---

en/docs/install-and-setup/setup/distributed-deployment/configuring-wso2-identity-server-as-a-key-manager.md

This PR adds the config to disable group and role separation in IS for the IS as KM setup.
Fixes https://github.com/wso2/docs-apim/issues/7792

Add config to disable group and role separation in IS

---

en/docs/administer/key-managers/configure-wso2is-connector.md
en/docs/design/api-security/oauth2/grant-types/refresh-token-grant.md
en/docs/design/api-security/oauth2/token-revocation.md
en/docs/reference/config-catalog.md
en/tools/config-catalog-generator/data/apim.oauth_config.toml
en/tools/config-catalog-generator/data/apim.token.revocation.toml
en/tools/config-catalog-generator/data/configs.json

Update token revocation docs to change notifier and port

---

en/theme/material/base.html

This PR adds the connect-src content security policy for docs URL.
Related issue: https://github.com/wso2/docs-apim/pull/7939

[4.3.0] Add connect-src content security policy for docs URL

---

en/theme/material/base.html

This PR adds both HTTP and HTTPS endpoints of docs in CSP data.
Related issue: https://github.com/wso2/docs-apim/pull/7939

[4.3.0] Add both http and https docs URLs to CSP metadata

---

en/docs/install-and-setup/setup/api-governance-cli/API-Governance-CLI-Tool.md

Adding the documentation for the API Governance CLI  Tool.
Link to access the documentation: http://localhost:8000/en/4.3.0/install-and-setup/setup/api-governance-cli/API-Governance-CLI-Tool/

Adding API Governance CLI Tool documentation

---

en/docs/reference/mediators/property-reference/accessing-properties-with-xpath.md

This PR is to add the missing info on auto reloading of `file.properties`.
https://github.com/wso2/docs-apim/pull/4252

[4.2.0] Add info on auto reloading of file.properties

---

en/docs/reference/mediators/property-reference/http-transport-properties.md

This PR is to update the doc with the `NON_ERROR_HTTP_STATUS_CODES` property.
https://github.com/wso2/docs-apim/pull/4002/

[4.2.0] Update documentation on non.error.http.status.code property

---

en/docs/design/api-security/api-authentication/secure-apis-using-basic-authentication.md

This PR is raised to update information on not having throttling policies support for basic authentication type.
This fixes: https://github.com/wso2-enterprise/wso2-apim-internal/issues/6514 doc issue

Updated Information on Basic Authentication

---

en/docs/consume/manage-application/sharing-applications/sharing-applications.md

This PR is raised to remove the SAML configuration from Application sharing page.
Related internal issue : https://github.com/wso2-enterprise/wso2-apim-internal/issues/6200

Removing SAML configurations from application sharing page

---

en/docs/design/rate-limiting/setting-throttling-limits.md

[4.0.0] Add note regarding the throttling intervals

---

en/docs/design/rate-limiting/setting-throttling-limits.md

[4.1.0] Add note regarding the throttling intervals

---

en/docs/design/rate-limiting/setting-throttling-limits.md

[4.2.0] Add note regarding the throttling intervals

---

en/docs/design/rate-limiting/setting-throttling-limits.md

[4.3.0] Add note regarding the throttling intervals

---

en/docs/design/rate-limiting/setting-throttling-limits.md

Add note regarding the throttling intervals

---

en/docs/install-and-setup/setup/reference/product-compatibility.md

This PR adds the PostgreSQL 12.15 as a compatible DB version.

[4.3.0] Add PostgreSQL 12.15 to product compatibility docs

---

en/docs/install-and-setup/setup/reference/product-compatibility.md

This PR adds the PostgreSQL 12.15 as a compatible DB version.

Add PostgreSQL 12.15 to product compatibility docs

---

en/docs/design/api-security/oauth2/oauth2-scopes/fine-grained-access-control-with-oauth-scopes.md

This PR is created to add information about restricting unassigned local scopes into the doc
Related internal issue: https://github.com/wso2-enterprise/wso2-apim-internal/issues/5661

[4.3.0] Add Restrict unassigned Scope Info to the Doc

---

en/docs/design/api-security/oauth2/oauth2-scopes/fine-grained-access-control-with-oauth-scopes.md

This PR is created to add information about restricting unassigned local scopes into the doc
Related internal issue: https://github.com/wso2-enterprise/wso2-apim-internal/issues/5661

[4.1.0] Add Restrict Unassigned Scope Info to the Doc

---

en/docs/design/api-security/oauth2/oauth2-scopes/fine-grained-access-control-with-oauth-scopes.md

This PR is created to add information about restricting unassigned local scopes into the doc
Related internal issue: https://github.com/wso2-enterprise/wso2-apim-internal/issues/5661

Add restrict unassigned scope info to the doc

---

en/docs/administer/logging-and-monitoring/logging/monitoring-http-access-logs.md
en/tools/config-catalog-generator/data/http_access_log.toml

Resolves : https://github.com/wso2-enterprise/wso2-apim-internal/issues/4014

[3.2.0] Corrected `http_access_log` config

---

en/docs/observe/api-manager/monitoring-http-access-logs.md
en/tools/config-catalog-generator/data/http_access_log.toml

Resolves: https://github.com/wso2-enterprise/wso2-apim-internal/issues/4014

[4.0.0] Corrected `http_access_log` config

---

en/docs/observe/api-manager/monitoring-http-access-logs.md
en/tools/config-catalog-generator/data/http_access_log.toml

Resolves: https://github.com/wso2-enterprise/wso2-apim-internal/issues/4014

[4.1.0] Corrected `http_access_log` config

---

en/docs/observe/api-manager/monitoring-http-access-logs.md
en/tools/config-catalog-generator/data/http_access_log.toml

Resolves: https://github.com/wso2-enterprise/wso2-apim-internal/issues/4014

[4.2.0] Corrected `http_access_log` config

---

en/docs/observe/api-manager/monitoring-http-access-logs.md
en/tools/config-catalog-generator/data/http_access_log.toml

Resolves: https://github.com/wso2-enterprise/wso2-apim-internal/issues/4014

Corrected `http_access_log` config

---

en/docs/learn/api-security/oauth2/oauth2-scopes/fine-grained-access-control-with-oauth-scopes.md

Below line should be removed from APIM docs as `am_application_scope` is no longer issued by default for client-credentials grant.
```
```

[3.2.0] Remove unwanted line in `Obtaining Tokens with Scopes` document

---

en/docs/design/api-security/oauth2/oauth2-scopes/fine-grained-access-control-with-oauth-scopes.md

Below line should be removed from APIM docs as `am_application_scope` is no longer issued by default for client-credentials grant.
```
```

[4.0.0] Remove unwanted line in Obtaining Tokens with Scopes document

---

en/docs/design/api-security/oauth2/oauth2-scopes/fine-grained-access-control-with-oauth-scopes.md

Removed the below line from APIM docs as `am_application_scope` is no longer issued by default for client-credentials grant.
```
```

[4.1.0] Remove unwanted line in Obtaining Tokens with Scopes document

---

en/docs/design/api-security/oauth2/oauth2-scopes/fine-grained-access-control-with-oauth-scopes.md

Removed the below line from APIM docs as `am_application_scope` is no longer issued by default for client-credentials grant.
```
```

[4.2.0] Remove unwanted line in Obtaining Tokens with Scopes document

---

en/docs/design/api-security/oauth2/oauth2-scopes/fine-grained-access-control-with-oauth-scopes.md

Removed the below line from APIM docs as `am_application_scope` is no longer issued by default for client-credentials grant.
```
```

Remove unwanted line in Obtaining Tokens with Scopes document

---

en/docs/integrate/develop/customizations/creating-synapse-handlers.md
en/docs/reference/config-catalog.md
en/tools/config-catalog-generator/data/configs.json

[4.2.0] Updated synapse handlers configurations

---

en/docs/reference/product-apis/publisher-apis/publisher-v4/publisher-v4.yaml

This PR fixes the sample cURL command of add API specific operation policy.
```diff
- -F policyDefinitionFile=@setHeader.j2 
+ -F synapsePolicyDefinitionFile=@setHeader.j2
```
- Resolves: https://github.com/wso2-enterprise/wso2-apim-internal/issues/6872

[4.2.0] Fix sample cURL of add API specific operation policy

---

en/docs/reference/product-apis/publisher-apis/publisher-v3/publisher-v3.yaml

This PR fixes the sample cURL command of add API specific operation policy.
```
+  -F policyDefinitionFile=@setHeader.j2
-  -F synapsePolicyDefinitionFile=@setHeader.j2
```

[4.1.0] Fix sample curl of add API specific operation policy

---

en/docs/reference/product-apis/publisher-apis/publisher-v4/publisher-v4.yaml

This PR fixes the sample cURL command of add API specific operation policy.
```
-   -F policyDefinitionFile=@setHeader.j2
+   -F synapsePolicyDefinitionFile=@setHeader.j2
```

[4.3.0] Fix sample curl of add API specific operation policy

---

en/docs/reference/product-apis/publisher-apis/publisher-v4/publisher-v4.yaml

This PR fixes the sample cURL command of add API specific operation policy.
```
-  -F policyDefinitionFile=@setHeader.j2
+  -F synapsePolicyDefinitionFile=@setHeader.j2
```

[master] Fix sample curl of add API specific operation policy

---

en/docs/design/api-security/api-authentication/secure-apis-using-mutual-ssl.md
en/docs/design/api-security/api-authentication/securing-apis-using-certificate-bound-access-tokens.md

This PR adds recommendation for using HTTPS with Mutual SSL. Fixes https://github.com/wso2/docs-apim/issues/8329

[4.3.0] Add HTTPS transport change to Mutual SSL docs

---

en/docs/design/api-security/api-authentication/secure-apis-using-mutual-ssl.md
en/docs/design/api-security/api-authentication/securing-apis-using-certificate-bound-access-tokens.md

This PR adds recommendation for using HTTPS with Mutual SSL. Fixes https://github.com/wso2/docs-apim/issues/8329.

[4.1.0] Add HTTPS transport change to Mutual SSL docs

---

en/docs/deploy-and-publish/deploy-on-gateway/choreo-connect/security/api-authentication/mutual-ssl-authentication.md
en/docs/design/api-security/api-authentication/secure-apis-using-mutual-ssl.md
en/docs/design/api-security/api-authentication/securing-apis-using-certificate-bound-access-tokens.md

This PR adds recommendation for using HTTPS with Mutual SSL. Fixes https://github.com/wso2/docs-apim/issues/8329.

[4.0.0] Add HTTPS transport change to Mutual SSL docs

---

en/docs/tutorials/edit-an-api-by-modifyng-the-api-definition.md

This PR fixes an alignment issue in the Important type note section in `edit-an-api-by-modifyng-the-api-definition.md` file

[4.2.0] Fix alignment issue in note

---

en/docs/tutorials/edit-an-api-by-modifyng-the-api-definition.md

This issue fixes the numbering alignment issue in `edit-an-api-by-modifyng-the-api-definition.md` file. The page looks like below.

Fix numbering issue with alignment

---

en/docs/administer/key-managers/configure-global-key-manager.md

- Add note about password and code grant usages to Global Key Manager documentation [1] added using [2]
[1] https://apim.docs.wso2.com/en/4.0.0/administer/key-managers/configure-global-key-manager/
[2] https://github.com/wso2/docs-apim/pull/7684

[4.0.0] Add Note About Password and Code Grant Usages to Global Key Manager Documentation

---

en/docs/design/api-security/api-authentication/secure-apis-using-api-keys.md

This PR adds the doc update for the following:
1. Doc support for Lightweight API Key Generation
2. Remove API Key Subscription Validation Enabling guid from Docs
- Related PR https://github.com/wso2/carbon-apimgt/pull/12540
- Resolves https://github.com/wso2/docs-apim/issues/8387

Doc Update for Lightweight API Key Generation and Remove API Key Subscription Validation Enabling Configuration from Docs

---

en/docs/install-and-setup/setup/security/logins-and-passwords/harshicrop-vault-extension.md
en/mkdocs.yml

> This PR will introduce documentation for integrate APIM with hashicrop vault extension [1].
[1] - https://github.com/wso2-extensions/carbon-securevault-hashicorp/tree/master
The following demonstrates the rendered view

Add docs related to integration of Hashicrop Vault extension

---

en/docs/design/create-api/create-ai-api/create-an-ai-api.md

This PR adds a note to inform that MistralAI and OpenAI AI APIs related API Key should not contain the `Bearer` keyword.

Add note for AI API endpoint configuring step

---

en/docs/troubleshooting/error-handling.md

Add error code 900424

---

en/docs/install-and-setup/setup/deployment-best-practices/security-guidelines-for-production-deployment.md

> Fix: https://github.com/wso2/docs-apim/issues/8473

[4.4.0] Add allow list to expose Developer portal

---

en/docs/reference/customize-product/customizations/customizing-the-developer-portal/customize-api-listing/api-category-based-grouping.md

Fixes https://github.com/wso2/docs-apim/issues/8422 in 4.4.0 doc space

[4.4.0] Fix doc link

---

en/docs/tutorials/streaming-api/create-and-publish-websocket-api.md

Fixes #8458 in 4.3.0 doc space

[4.3.0] Fix 'Missing image in Create and Publish a WebSocket API page'

---

en/docs/includes/design/invoke-prerelease-api.md
en/docs/reference/customize-product/extending-api-manager/extending-gateway/customizing-api-template-for-gateway.md

Fixes below broken link issues in 4.4.0 doc space.
- #6838 
- https://github.com/wso2/docs-apim/issues/1906

[4.4.0] Fixes Broken Links in 4.4.0 Doc Space

---

en/docs/design/api-monetization/monetizing-an-api.md
en/docs/install-and-setup/setup/distributed-deployment/product-profiles.md
en/docs/install-and-setup/setup/setting-up-databases/changing-default-databases/changing-to-mysql.md

[4.2.0] Mention the tested MySQL Java Connector version

---

en/docs/administer/managing-users-and-roles/managing-user-stores/configure-primary-user-store/configuring-a-read-only-ldap-user-store.md
en/docs/administer/managing-users-and-roles/managing-user-stores/configure-primary-user-store/configuring-a-read-write-active-directory-user-store.md
en/docs/administer/managing-users-and-roles/managing-user-stores/configure-primary-user-store/configuring-a-read-write-ldap-user-store.md
en/docs/administer/managing-users-and-roles/managing-user-stores/configure-primary-user-store/configuring-the-primary-user-store.md

[APIM 4.2.0] Fixes primary user store related issues

---

en/docs/design/create-api/adding-custom-properties-to-apis.md
en/docs/design/create-api/change-api-thumbnail.md
en/docs/design/rate-limiting/adding-new-throttling-policies.md

1. Adding deployment.toml config to make the document clear in the Advanced rate limiting policy document.
Resolves: https://github.com/wso2/docs-apim/issues/8460
2. Removed the 'Design a new API Thumbnail' document since this feature is not available now.
Resolves: https://github.com/wso2/docs-apim/issues/8455

[Master] Fix documentation Issues

---

en/docs/design/create-api/change-api-thumbnail.md

$Subject
Resolves: https://github.com/wso2/docs-apim/issues/8455

[4.0.0] Removed the 'Design a new API Thumbnail' document since this feature is not available now.

---

en/docs/design/create-api/create-rest-api/create-a-rest-api.md

Fixes https://github.com/wso2/docs-apim/issues/8003
(cherry picked from commit 6ea417dcc4074c45610988c0bdf319e3edcc68a7)

[APIM 4.3.0] Fix Image Overlap UI Issue in Collapsible Items on Larger Screens

---

en/docs/deploy-and-publish/publish-on-dev-portal/third-party-api-support.md

[4.4.0] Add a note on limitation of Third party APIs

---

en/docs/reference/product-apis/devportal-apis/devportal-v2/devportal-v2.yaml

To add documentation changes for generating the SecuritySchema of the Swagger using real Key Manager information
Fixes doc improvements: https://github.com/wso2/api-manager/issues/3044

[4.0.0] Add doc changes for generating the SecuritySchema of the Swagger using real Key Manager information

---

en/docs/deploy-and-publish/deploy-on-gateway/api-gateway/threat-protectors/regular-expression-threat-protection-for-api-gateway.md

Fixes #7960 and #7722 in 4.4.0 doc space.

[4.4.0] Fix regex in gateway threat protection doc

---

en/docs/design/advanced-topics/enable-publisher-access-control-in-api-publisher-portal.md

(cherry picked from commit 2f33846b4a38c4c5210db1c0382a0665b62fff49)

[APIM 4.1.0] Add note about the case insensitivity of publisher access control roles

---

en/docs/reference/product-apis/publisher-apis/publisher-v3/publisher-v3.yaml

> Improve the readability of the rest api document to provide more understanding to the end user.

Improve the readability of Rest API Document

---

en/docs/design/api-security/oauth2/multiple-active-access-tokens.md
en/mkdocs.yml

[APIM 4.3.0] Add multiple-active-access-tokens documentation

---

en/docs/administer/logging-and-monitoring/monitoring/monitoring-server-health.md

[4.4.0] Fix health check docs

---

en/docs/install-and-setup/setup/advance-configurations/changing-the-default-transport.md

fixes: https://github.com/wso2-enterprise/wso2-apim-internal/issues/7553

[Doc]: Add TargetProxyHosts configuration as Trasport Sender Parameter

---

en/docs/administer/logging-and-monitoring/monitoring/monitoring-server-health.md

Fix health check docs

---

en/docs/install-and-setup/setup/api-controller/managing-apis-api-products/managing-apis-and-api-products.md

From APIM 4.0, querying by gateway labels doesn't support by the APICTL. With the revisions introduced, all API revisions can be listed along with the gateways deployed.

Remove: Label support from API Listing

---

en/docs/api-analytics/on-prem/elk-installation-guide.md

There should be a way to check the policies hit on a request to a specific API. Currently, the Analytics Event does not contain the policy data of the API.
Load API and Operation Policies of the APIs/API Products to the gateway and send the corresponding policies in the analytics event.
1. Load API Policies and Operation Policies to the gateway on the deployment.
2. Fetch Operation and API Policies related to the the resource and the method on the API invocation.
- https://github.com/wso2/carbon-apimgt/pull/12176

[Doc]: Enabling/Disabling Operation Policies in Analytics Event

---

en/docs/reference/mediators/property-reference/accessing-properties-with-xpath.md

This PR is to add the missing info on auto reloading of `file.properties`.
https://github.com/wso2/docs-apim/pull/4252

[4.1.0] Add info on auto reloading of file.properties

---

en/docs/observe/api-manager/monitoring-websocket-logs.md
en/mkdocs.yml

Docs for the feature https://github.com/wso2/api-manager/issues/3419

Add docs for websocket access logs feature

---

en/docs/administer/managing-users-and-roles/managing-user-stores/configuring-secondary-user-stores.md

This PR adds a note to indicate group related attributes are not used in read-only LDAP userstores.
Related issue: https://github.com/wso2-enterprise/wso2-apim-internal/issues/8581

[4.3.0] Add note to indicate group attributes are not used in read-only LDAP userstores

---

en/docs/administer/managing-users-and-roles/managing-user-stores/configuring-secondary-user-stores.md

This PR adds a note to indicate group related attributes are not used in read-only LDAP userstores.
Related issue: https://github.com/wso2-enterprise/wso2-apim-internal/issues/8581

[4.4.0] Add note to indicate group attributes are not used in read-only LDAP userstores

---

en/docs/administer/key-managers/configure-wso2is7-connector.md

> $Purpose. Related to https://github.com/wso2/api-manager/issues/3310

Add docs about optional role creation

---

en/docs/assets/attachments/reference/governance-v1.1-postman-collection.json
en/docs/reference/product-apis/governance-apis/governance-v1/governance-v1.md
en/docs/reference/product-apis/governance-apis/governance-v1/governance-v1.yaml
en/docs/reference/product-apis/overview.md
en/mkdocs.yml

This pull request includes updates to the documentation for the Governance API and the overall API reference structure. The most important changes are the addition of the Governance API v1 documentation and the update to the API overview page to include the new Governance API.
* [`en/docs/reference/product-apis/governance-apis/governance-v1/governance-v1.md`](diffhunk://#diff-bf94a774abaf112568a39d405de5b384de65ecfc7560e871d344ce235a377491R1-R6): Added a new documentation page for Governance API v1 with a Redoc template.
* [`en/docs/reference/product-apis/overview.md`](diffhunk://#diff-9772aa32fad308a59ad99ee3ca114c0618154183887e27d0b287985ecf02c787R28-R31): Added a link to the new Governance API v1 in the API overview table.
* [`en/docs/reference/product-apis/overview.md`](diffhunk://#dif …

Add Governance REST API Reference Docs

---

en/docs/learn/consume-api/generating-sdks/generate-sdks-in-dev-portal.md
en/docs/reference/config-catalog.md
en/tools/config-catalog-generator/data/apim.sdk.toml
en/tools/config-catalog-generator/data/configs.json

This PR removes Flash SDK from the documentation since it is no longer supported.
Related issue: https://github.com/wso2-enterprise/wso2-apim-internal/issues/8902

[3.2.0] Remove docs for Flash SDK

---

en/docs/consume/generating-sdks/generate-sdks-in-dev-portal.md
en/docs/reference/config-catalog.md
en/tools/config-catalog-generator/data/apim.sdk.toml
en/tools/config-catalog-generator/data/configs.json

This PR removes Scala and Flash SDKs from the documentation since they are no longer supported.
Related issues: https://github.com/wso2-enterprise/wso2-apim-internal/issues/9056, https://github.com/wso2-enterprise/wso2-apim-internal/issues/8902

[4.0.0] Remove docs for Scala and Flash SDK

---

en/docs/reference/product-apis/publisher-apis/publisher-v2/publisher-v2.yaml

[4.0.0] Add description to the revisions get query param

---

en/docs/reference/product-apis/publisher-apis/publisher-v3/publisher-v3.yaml

[4.1.0] Add description to the revisions get query param

---

en/docs/reference/product-apis/publisher-apis/publisher-v4/publisher-v4.yaml

[4.2.0] Add description to the revisions get query param

---

en/docs/reference/product-apis/publisher-apis/publisher-v4/publisher-v4.yaml

[4.3.0] Add description to the revisions get query param

---

en/docs/reference/product-apis/publisher-apis/publisher-v4/publisher-v4.yaml

[4.4.0] Add description to the revisions get query param

---

en/docs/reference/product-apis/publisher-apis/publisher-v4/publisher-v4.yaml

[4.5.0] Add description to the revisions get query param

---

en/docs/reference/product-apis/publisher-apis/publisher-v4/publisher-v4.yaml

Add description to the revisions get query param

---

en/docs/assets/css/theme.css
en/theme/material/partials/header.html

- Remove the WIP banner which was introduced in [1] from the APIM 4.5.0 Docs
[1] https://github.com/wso2/docs-apim/pull/9009/commits/029d5eecced1b315a52dbc9a76fe2e9640709c11

Remove WIP Banner from APIM 4.5.0 Docs

---

en/docs/install-and-setup/setup/mi-setup/brokers/configure-with-rabbitmq.md
en/docs/install-and-setup/setup/mi-setup/performance_tuning/rabbitmq_transport_tuning.md
en/docs/reference/config-catalog-mi.md
en/docs/reference/synapse-properties/transport-parameters/rabbitmq-transport-parameters.md

- Remove unused parameter `rabbitmq.server.retry.interval`
- Update connection pool size configs
Fixes: https://github.com/wso2/docs-mi/issues/1452

Update RabbitMQ config docs

---

en/docs/install-and-setup/setup/deployment-overview.md

This PR adds the deployment alternative table to deployment overview doc for component architecture changes.

Add deployment alternative table to deployment overview doc

---

en/docs/reference/config-catalog.md

To add a reference to the gateway_type configuration in the official config catalog [1].
Fixes: https://github.com/wso2/docs-apim/issues/9200

Add configuration information for gateway type

---

en/docs/reference/config-catalog.md

To add a reference to the gateway_type configuration in the official config catalog [1].
Fixes: https://github.com/wso2/docs-apim/issues/9200

[4.5.0] Add configuration information for gateway type

---

en/docs/deploy-and-publish/deploy-on-gateway/choreo-connect/configurations/adapter-configurations.md
en/docs/deploy-and-publish/deploy-on-gateway/choreo-connect/git-integration.md
en/tools/config-catalog-generator-cc/data/adapter/configs.json
en/tools/config-catalog-generator-cc/data/adapter/source_control.toml

> Authenticating the Github repository with SSH key fails when integrating Choreo Connect with Git for version controlling of API artifacts.
Related Issue - https://github.com/wso2/product-microgateway/issues/3669
> Enable Git for version controlling of API artifacts using SSH by correctly parsing the configuration for the SSH key file.
> Rename of the configuration from sshKeyFile to SSHKeyFile matching the configuration key name to the struct defined in the adapter.

Update git integration documentation

---

en/docs/install-and-setup/setup/multi-dc-deployment/configuring-multi-dc-deployment-pattern-1.md

Add note to mention database replication was done using VMs

---

en/docs/install-and-setup/setup/multi-dc-deployment/configuring-multi-dc-deployment-pattern-1.md

[4.5.0] Add note to mention database replication was done using VMs

---

en/docs/install-and-setup/setup/multi-dc-deployment/configuring-multi-dc-deployment-pattern-1.md

[4.4.0] Add note to mention database replication was done using VMs

---

en/docs/install-and-setup/setup/multi-dc-deployment/configuring-multi-dc-deployment-pattern-1.md

[4.3.0] Add note to mention database replication was done using VMs

---

en/docs/install-and-setup/setup/multi-dc-deployment/configuring-multi-dc-deployment-pattern-1.md

[4.2.0] Add note to mention database replication was done using VMs

---

en/docs/install-and-setup/install/installation-prerequisites.md

> Test compatibility of APIM 4.5.0 products on Linux ARM.
Related issue - https://github.com/wso2-enterprise/wso2-apim-internal/issues/9895
> Tested the following on a VM on Azure with Ubuntu 24.04 and arm64 CPU architecture.
- wso2update_linux_arm64 update tool
- WSO2 APIM 4.5.0 all-in-one distribution
- WSO2 APIM 4.5.0 distributed setup with ACP, Gateway and TM - profile testing
- API Microgateway 3.2.0 toolkit and runtime

Add arm compatibility to docs

---

en/docs/install-and-setup/install/installation-prerequisites.md

> Test compatibility of APIM 4.5.0 products on Linux ARM.
> Tested the following on a VM on Azure with Ubuntu 24.04 and arm64 CPU architecture.
- wso2update_linux_arm64 update tool
- WSO2 APIM 4.5.0 all-in-one distribution
- WSO2 APIM 4.5.0 distributed setup with ACP, Gateway and TM - profile testing
- API Microgateway 3.2.0 toolkit and runtime

Add arm compatibility to installation prerequisites

---

en/docs/reference/config-catalog.md
en/tools/config-catalog-generator/data/_ws-transport.toml
en/tools/config-catalog-generator/data/_wss-transport.toml
en/tools/config-catalog-generator/data/configs.json

Update config catalog with `wsSharedEventLoopPoolSize` config.
Reference: https://github.com/wso2/api-manager/issues/3889

[440] Add wsSharedEventLoopPoolSize configurations for Websocket connections

---

en/docs/reference/config-catalog.md
en/tools/config-catalog-generator/data/_ws-transport.toml
en/tools/config-catalog-generator/data/_wss-transport.toml
en/tools/config-catalog-generator/data/configs.json

Update config catalog with `wsSharedEventLoopPoolSize` config.
Reference: https://github.com/wso2/api-manager/issues/3889

[430] Add wsSharedEventLoopPoolSize configurations for Websocket connections

---

en/docs/administer/key-managers/configure-azure-ad-key-manager.md

Correct typographical and grammatical errors in the Azure AD configuration documentation.
https://github.com/wso2/docs-apim/pull/8474

[4.3.0] Fix typos in Azure AD configuration doc

---

en/docs/administer/key-managers/configure-azure-ad-key-manager.md

Correct typographical and grammatical errors in the Azure AD configuration documentation.
https://github.com/wso2/docs-apim/pull/8474

[4.2.0] Fix typos in Azure AD configuration doc

---

en/docs/install-and-setup/setup/deployment-best-practices/security-guidelines-for-production-deployment.md

[4.2.0] Update documentation of APIM for transport.https.sslHostConfig.properties

---

en/docs/install-and-setup/setup/deployment-best-practices/security-guidelines-for-production-deployment.md

[4.3.0] Update documentation of APIM for transport.https.sslHostConfig.properties

---

en/docs/install-and-setup/setup/deployment-best-practices/security-guidelines-for-production-deployment.md

[4.4.0] Update documentation of APIM for transport.https.sslHostConfig.properties

---

en/docs/install-and-setup/setup/deployment-best-practices/security-guidelines-for-production-deployment.md

[4.5.0] Update documentation of APIM for transport.https.sslHostConfig.properties

---

en/docs/install-and-setup/setup/deployment-best-practices/security-guidelines-for-production-deployment.md

Update documentation of APIM for transport.https.sslHostConfig.properties

---

en/docs/design/api-policies/attach-policy.md

Updating the API level policy enabling steps to make sure the user creates the table before enabling API level policies
Changed the steps order
Now the user will create the `AM_API_POLICY_MAPPING ` before adding the deployment.toml config when enabling API level policy feature.
https://github.com/wso2-support/carbon-apimgt/pull/7378

[4.2.0] Change the order of API level policy enabling steps

---

en/docs/install-and-setup/setup/kubernetes-deployment/kubernetes/am-pattern-1-all-in-one-ha.md
en/docs/install-and-setup/setup/kubernetes-deployment/kubernetes/am-pattern-2-all-in-one-gw.md

This update addresses the need for enhanced deployment resilience and scalability by enabling High Availability (HA) support in the Kubernetes deployment documentation for API Manager. Prior to this update, there was limited guidance on how to configure HA for both all-in-one and distributed deployment patterns. This change ensures users have clear, actionable instructions for enabling HA, improving system uptime and reliability.
- Provide clear and structured guidance on enabling High Availability for both deployment patterns (all-in-one and distributed).
- Update the documentation to reflect best practices in configuring the `highAvailability` parameter in the `values.yaml` file.
- Offer helpful configuration tips, such as hostname usage for the Key Manager, to prevent common …

Add "Enable High Availability" section to deployment patterns

---

en/docs/install-and-setup/setup/kubernetes-deployment/kubernetes/kubernetes-overview.md

This PR adds the supported RKE2 and Rancher versions to the docs.
Related issue: https://github.com/wso2-enterprise/wso2-apim-internal/issues/9652

Add supported RKE2 and Rancher versions to the docs

---

en/docs/reference/config-catalog.md
en/tools/config-catalog-generator/data/apim.oauth_config.toml
en/tools/config-catalog-generator/data/configs.json

- $subject
- Related to: https://github.com/wso2-enterprise/wso2-apim-internal/issues/9776

Add enable_revoke_token_cleanup config to config catalog

---

en/docs/governance/rule-validator/rule-validator.md

Fix typos in Rule Validator doc

---

en/docs/design/api-security/api-authentication/securing-apis-using-certificate-bound-access-tokens.md

This PR addresses missing documentation for configuring the client_certificate_header in [oauth.mutualtls] to enable JWT tokens with the client certificate thumbprint (cnf claim)
To provide clear instructions for configuring the client_certificate_header, explain how to pass the client certificate to the token endpoint, and warn users about the need to use lowercase header names to ensure correct inclusion of the cnf claim in JWT tokens.
Since both lowercase and uppercase values for the header name are accepted in the latest versions, there is no need to explicitly mention using lowercase. Instead, only update the example value to lowercase to avoid any potential issues.

Add client_certificate_header configuration

---

en/docs/design/api-security/api-authentication/securing-apis-using-certificate-bound-access-tokens.md

This PR addresses missing documentation for configuring the client_certificate_header in [oauth.mutualtls] to enable JWT tokens with the client certificate thumbprint (cnf claim) and highlights the case sensitivity issue where uppercase header names prevent proper token generation.
To provide clear instructions for configuring the client_certificate_header, explain how to pass the client certificate to the token endpoint, and warn users about the need to use lowercase header names to ensure correct inclusion of the cnf claim in JWT tokens.

[APIM-4.2.0] Add client_certificate_header config and case sensitivity warning for OAuth mutual TLS

---

en/docs/consume/manage-application/create-application.md

- https://github.com/wso2-enterprise/wso2-apim-internal/issues/9757

Fix: Missing Configuration for Default Application Creation 

---

en/docs/install-and-setup/setup/kubernetes-deployment/kubernetes/am-pattern-2-all-in-one-gw.md
en/docs/install-and-setup/setup/kubernetes-deployment/kubernetes/am-pattern-3-acp-tm-gw.md
en/docs/install-and-setup/setup/kubernetes-deployment/kubernetes/am-pattern-4-acp-tm-gw-km.md
en/docs/install-and-setup/setup/kubernetes-deployment/kubernetes/am-pattern-5-all-in-one-gw-km.md
en/docs/install-and-setup/setup/kubernetes-deployment/kubernetes/am-pattern-6-all-in-one-is-as-km.md
en/mkdocs.yml

This pull request updates the Kubernetes deployment documentation for various API Manager patterns to include high availability (HA) configurations and improve clarity. The changes introduce steps to enable replicas for scalability and HA, along with detailed configuration examples for different deployment scenarios.
* Added a new section, "Enable Replicas," to the deployment steps for Universal Gateway in multiple patterns (`am-pattern-2-all-in-one-gw.md`, `am-pattern-3-acp-tm-gw.md`, `am-pattern-4-acp-tm-gw-km.md`, `am-pattern-5-all-in-one-gw-km.md`). This includes YAML examples for configuring `replicas`, `minReplicas`, and `maxReplicas` in the `values.yaml` file. [[1]](diffhunk://#diff-d0b338c4e1f04585a806c1e146a05afac8ad140cd4e9e00d9ac05ec98eee9a31L442-R500) …

Update deployment documentation to include replica configuration

---

en/docs/administer/key-managers/configure-wso2is7-connector.md

> Add warning documentation for UserInfo endpoint configuration issue when using well-known URL auto-import in WSO2 IS 7.x Key Manager setup.
> Prevent configuration errors by clearly documenting that the auto-imported UserInfo endpoint may be incorrect and needs manual verification/correction.
> Added a warning admonition in the Key Manager Endpoints configuration section to highlight that well-known URL auto-import may set UserInfo endpoint to `/oauth2/userInfo` instead of the correct `/scim2/Me` endpoint.
> Added documentation warning for UserInfo endpoint correction when using well-known URL in WSO2 IS 7.x Key Manager configuration.
> This PR directly updates the WSO2 IS 7.x Key Manager configuration documentation to improve setup accuracy.

[APIM Docs 4.5.0] Add warning for UserInfo endpoint correction when using well-known URL in WSO2 IS 7.x config

---

en/docs/install-and-setup/setup/single-node/configuring-an-active-active-deployment.md

Remove misleading 'Step 6 - Configure Publisher with the Gateway' from the Active-Active API-M Deployment guide
Fix related to https://github.com/wso2-enterprise/wso2-apim-internal/issues/6914

[4.5.0] Fix the active-active deployment guide

---

en/docs/install-and-setup/setup/single-node/configuring-an-active-active-deployment.md

Remove misleading 'Step 6 - Configure Publisher with the Gateway' from the Active-Active API-M Deployment guide
Fix related to https://github.com/wso2-enterprise/wso2-apim-internal/issues/6914

[4.4.0] Fix the active-active deployment guide

---

en/mkdocs.yml

Fix content length guardrail typo

---

en/docs/install-and-setup/setup/single-node/configuring-an-active-active-deployment.md

Remove misleading 'Step 6 - Configure Publisher with the Gateway' from the Active-Active API-M Deployment guide
Fix related to https://github.com/wso2-enterprise/wso2-apim-internal/issues/6914

[4.3.0] Fix the active-active deployment guide

---

en/docs/install-and-setup/setup/deployment-best-practices/security-guidelines-for-production-deployment.md
en/docs/install-and-setup/setup/security/configuring-transport-level-security.md

This PR adds missing content related to enabling HTTP Strict Transport Security (HSTS).
Fixes:
https://github.com/wso2/docs-apim/issues/9198
https://github.com/wso2/docs-apim/issues/9197

[4.5.0] Add HSTS related docs

---

en/docs/install-and-setup/setup/deployment-best-practices/security-guidelines-for-production-deployment.md
en/docs/install-and-setup/setup/security/configuring-transport-level-security.md

This PR adds missing content related to enabling HTTP Strict Transport Security (HSTS).
Fixes:
https://github.com/wso2/docs-apim/issues/9198
https://github.com/wso2/docs-apim/issues/9197

[4.3.0] Add HSTS related doc

---

en/docs/deploy-and-publish/deploy-on-gateway/federated-gateways/deploy-on-aws-api-gateway.md

Fixes broken template variable from {{basepath}} to {{base_path}} in Step 3, sub step 2.
This resolves the page not found error reported by users.
Fixes issue#9381

Fix broken Auth0 Key Manager link in AWS API Gateway deployment guide To fix Issue Number # 9381

---

en/docs/learn/api-gateway/message-mediation/adding-dynamic-endpoints.md

We configure dynamic endpoints like shown in [this example](https://apim.docs.wso2.com/en/3.0.0/learn/api-gateway/message-mediation/adding-dynamic-endpoints/). When there's a trailing `/` in an endpoint, if we use a resource `/*` in the API, it would be resolved fine.
E.g, if we have an API with:
**Endpoint:** `http://example.com`
**Resource1:** `/*`
**Resource2:** `/test`
**Case1:** When calling **Resource1**, the resolved URL is: `http://example.com/`
**Case2:** But when calling **Resource2**, the resolved URL is: `http://example/com//test` (notice the two slashes), which results in a bad request.
Some customers have misinterpreted this example, and when performing **Case 2**, they've run into issues.
This PR removes the trailing `/` from the Endpoint URL, mentioned in the example. So, …

Remove trailing / in the endpoint URL

---

en/docs/install-and-setup/setup/security/logins-and-passwords/working-with-encrypted-passwords.md

This PR adds internal keystore information to encrypting passwords in config files to avoid confusion with primary keystore information.

[4.1.0] Add internal keystore information to encrypting passwords in config files

---

en/docs/install-and-setup/setup/security/logins-and-passwords/working-with-encrypted-passwords.md

This PR adds internal keystore information to encrypting passwords in config files to avoid confusion with primary keystore information.

[4.4.0] Add internal keystore information to encrypting passwords in config files

---

en/docs/install-and-setup/setup/security/logins-and-passwords/working-with-encrypted-passwords.md

This PR adds internal keystore information to encrypting passwords in config files to avoid confusion with primary keystore information.

[master] Add internal keystore information to encrypting passwords in config files

---

en/docs/administer/updating-wso2-api-manager.md

[master] Update Index Data Backup Instructions in Updating WSO2 API Manager Documentation

---

en/docs/administer/updating-wso2-api-manager.md

[4.5.0] Update Index Data Backup Instructions in Updating WSO2 API Manager Documentation

---

en/docs/administer/updating-wso2-api-manager.md

[4.3.0] Update Index Data Backup Instructions in Updating WSO2 API Manager Documentation

---

en/docs/administer/updating-wso2-api-manager.md

[4.2.0] Update Index Data Backup Instructions in Updating WSO2 API Manager Documentation

---

en/docs/administer/updating-wso2-api-manager.md

[4.0.0] Update Index Data Backup Instructions in Updating WSO2 API Manager Documentation

---

en/mkdocs.yml

Fixes misspelling **“Regualr” → “Regular”** in
* nav label (`en/mkdocs.yml`)
* page title/H1 (`custom-opa-policy-for-regular-gateway.md`)
No other changes.

docs(4.1.0): fix typo (Regular Gateway) 

---

en/docs/install-and-setup/setup/setting-up-proxy-server-and-the-load-balancer/configuring-the-proxy-server-and-the-load-balancer.md

In APIM 4.x versions, sticky sessions are not required for the gateway and the react apps.
This PR updates this section in the relevant docs.

Update sticky session details in load balanced APIM

---

en/docs/install-and-setup/install/deploying-api-manager-with-kubernetes-resources.md

> This PR updates the Kubernetes deployment documentation to use the correct Helm chart version for WSO2 API Manager 4.5.0.
> Updated git checkout command from all-in-one-4.4.0 to all-in-one-4.5.0.
Updated GitHub repository links in documentation notes to point to the 4.5.0 branch.

Update Kubernetes deployment guide to use Helm chart version 4.5.0

---

en/docs/design/api-monetization/monetizing-an-api.md

Fixes : https://github.com/wso2/docs-apim/issues/7123

[4.4.0] Fix broken links in documentations

---

en/docs/manage-apis/design/b2b-api-management/api-consumption.md

From https://github.com/wso2/api-manager/issues/4105, we changed the `logoutSessionStateAppender` to an empty value to fix the issue in the federated IDP flow.  
However, due to this fix, the B2B flow will break. To avoid this, we need to manually set the `logoutSessionStateAppender` value to `OIDC`.  
Improve the B2B documentation to handle the production scenario.  
- Remove the localhost flow, as it is no longer required.  
- Add the `settings.json` configuration in the APIM setup step.

[4.5.0] Update API consumption documentation to include logoutSessionStateAppender

---

en/docs/install-and-setup/setup/kubernetes-deployment/kubernetes/am-pattern-0-all-in-one.md
en/docs/install-and-setup/setup/kubernetes-deployment/kubernetes/am-pattern-1-all-in-one-ha.md
en/docs/install-and-setup/setup/kubernetes-deployment/kubernetes/am-pattern-2-all-in-one-gw.md
en/docs/install-and-setup/setup/kubernetes-deployment/kubernetes/am-pattern-3-acp-tm-gw.md
en/docs/install-and-setup/setup/kubernetes-deployment/kubernetes/am-pattern-4-acp-tm-gw-km.md
en/docs/install-and-setup/setup/kubernetes-deployment/kubernetes/am-pattern-5-all-in-one-gw-km.md
en/docs/install-and-setup/setup/kubernetes-deployment/kubernetes/am-pattern-6-all-in-one-is-as-km.md

This PR,
- adds a note linking the 'Configure JWKS URL' section under the 'Minimal Configuration' section in the Pattern 2 Kubernetes documentation.
- modify doc content under 'Mount Keystore and Truststore' and 'Encrypt Secrets' in pattern 2 K8 deployment.

Update content in pattern 2 K8 document

---

en/docs/index.md

> "SaaS" under deployment options in index.md should redirect to Bijira documentation instead of the Bijira webpage.
> Make "SaaS" under deployment redirect to https://wso2.com/bijira/docs/ instead of https://wso2.com/bijira/ in the 4.5.0 documentation.

Update index.md to redirect to the Bijira documentation instead of the webpage

---

en/docs/index.md

> "SaaS" under deployment options in index.md should redirect to Bijira documentation instead of the Bijira webpage as stated in #9448. 
> Make "SaaS" under deployment redirect to https://wso2.com/bijira/docs/ instead of https://wso2.com/bijira/.

Fixes #9448: Redirects to Bijira documentation instead of webpage

---

en/.spelling
en/docs/install-and-setup/setup/single-node/configuring-a-single-node.md
en/docs/install-and-setup/setup/single-node/configuring-an-active-active-deployment.md

Was demiliterized, should be demilitarized (roots de-, military,-ize,-ed), from english military and latin militaris (relating to war or armies)

Fixing spelling: Demilitarized

---

en/docs/index.md

Fixed a typo error in the homepage documentation where "spaning" was used instead of "spanning". This ensures clearer and more accurate content for users. This contribution is part of my application for the WSO2 engineering internship.
A typo ("spaning" instead of "spanning") was identified in the homepage documentation, which could confuse users.
Correct the typo to ensure accurate and professional documentation for all users.
Manually edited the Markdown file to replace "spaning" with "spanning".
This is a minor documentation fix,
This is a minor typo fix not requiring a release note.
The change is the documentation itself; no additional documentation update is needed.
No impact on training content.
This typo fix does not affect certification exams.
No marketing impact from this change. …

 Fix typo error in homepage : spaning to spanning

---

en/docs/design/endpoints/endpoint-types.md
en/docs/design/endpoints/high-availability-for-endpoints.md

- Adds documentation for the updated behavior of failover in load-balanced endpoints, including instructions to enable the fix via `deployment.toml`, while preserving backward compatibility.
- Related to: https://github.com/wso2-enterprise/wso2-apim-internal/issues/10655

Update documentation for failover fix in load-balanced endpoints

---

en/docs/install-and-setup/install/installing-the-product/installing-api-m-runtime.md

This PR addresses an issue where the WSO2 documentation for setting up JAVA_HOME on macOS is outdated, resulting in user confusion and setup failures. On macOS Catalina and later, the default shell is Zsh, which uses the .zprofile file instead of the .bash_profile file. This change resolves that problem.
Update the documentation to accurately reflect the correct file (.zprofile) for setting up environment variables on modern macOS versions.
Provide a convenient command-line method for macOS users to find the JDK path, simplifying the setup process.
I am implementing the solution by editing the documentation file to inform users to look for the .zprofile file for macOS Catalina and newer. Additionally, I am adding a simple command for users to find the JDK path, which will be more reliable …

docs: update macOS setting JAVA_HOME

---

en/docs/install-and-setup/setup/deployment-best-practices/security-guidelines-for-production-deployment.md

Add a new guideline on restricting access to java classes and java methods/native objects in scripts that are used in script mediator.
The updated section will appear as below.

Add documentation about restrict accessing to java classes and methods in script mediator for MI 4.1.0

---

en/docs/manage-apis/design/endpoints/endpoint-security/oauth-2.0.md

This PR adds documentation for a new configuration option that allows users to specify a dedicated trust store for OAuth token endpoint connections in WSO2 API Manager.
- Added a new section "Configuring a dedicated trust store for OAuth token endpoint connections" to the OAuth 2.0 endpoint security documentation
- Documented the configuration parameters and example usage
- Explained the default behavior (using existing SSL context) and when to use the separate trust store option
The new configuration allows users to specify a dedicated trust store for OAuth token endpoint SSL connections:
```toml
[apim.mediator_config.oauth.trust_store]
location = "repository/resources/security/client-truststore-oauth.jks"
type = "JKS"
password = "wso2carbon"

Add configuration for dedicated trust store in OAuth token endpoint connections

---

en/docs/mcp/create-from-api.md
en/docs/mcp/create-from-mcp-server.md
en/docs/mcp/create-from-openapi.md
en/docs/mcp/invoke-a-mcp-server-using-playground.md
en/docs/mcp/overview.md
en/docs/mcp/subscribe-to-a-mcp-server.md
en/mkdocs.yml

This pull request makes small improvements to documentation for MCP Server creation and usage, focusing on clarity, formatting, and correcting minor errors in navigation and references.
Documentation formatting and clarity:
* Updated numbered list formatting in `en/docs/mcp/create-from-api.md` and `en/docs/mcp/create-from-mcp-server.md` to use consistent indentation and bullet points for navigation steps, improving readability. [[1]](diffhunk://#diff-2dc99c4af8e86e793f4aad7b1ac0c0935b98d1185bb2a23d6dd0a7150e3e5a29L16-R17) [[2]](diffhunk://#diff-bf6e8155c4f29ca151c60df598c355fc6088da25b395c30b75bd7cc60e082aa6R11-R15)
* Added spacing and notes to the "Enter MCP Server details" steps in `en/docs/mcp/create-from-api.md`, `en/docs/mcp/create-from-mcp-server.md`, and …

Fix MCP documentation issues
