wso2/docs-apim

- en/docs/install-and-setup/setup/distributed-deployment/deploying-wso2-api-m-in-a-distributed-setup-with-tm-separated.md
Fixed the configuration issues and improved the information on the doc page.
Related PR: https://github.com/wso2/docs-apim/pull/6300
> Fix the doc issues in distributed setup with tm seperated

- en/docs/install-and-setup/setup/distributed-deployment/deploying-wso2-api-m-in-a-distributed-setup.md
Fixed the configuration issues and improved the information on the doc page.
Related PR: https://github.com/wso2/docs-apim/pull/6300
> Fix the docs of distributed setup page

- en/docs/deploy-and-publish/deploy-on-gateway/choreo-connect/faq.md
> [4.1.0] Minor formatting change to cc faq to make main topics prominent

- en/docs/deploy-and-publish/deploy-on-gateway/choreo-connect/configurations/configure-logs-router.md
- en/docs/deploy-and-publish/deploy-on-gateway/choreo-connect/troubleshooting/adding-debug-logs.md
- en/mkdocs.yml
> $subject
https://github.com/wso2/docs-apim/pull/5943
> To define method to enable Router WireLogs
> Type “Sent” when you …
> [4.0.0] Choreo Connect Router wire logs

- en/docs/deploy-and-publish/deploy-on-gateway/choreo-connect/configurations/configure-logs-router.md
> $subject
> Corrects the version and release date.
> Type “Sent” when you have provided new/updated certification …
> Minor Correction Relevant to the Choreo Connect 1.0.0 version.

- en/docs/deploy-and-publish/deploy-on-gateway/choreo-connect/endpoints/defining-a-backend-security-scheme.md
> [4.1.0] Update choreo connect backend security docs

- en/docs/deploy-and-publish/deploy-on-gateway/choreo-connect/configure-analytics.md
- en/docs/deploy-and-publish/deploy-on-gateway/choreo-connect/getting-started/choreo-connect-overview.md
- en/docs/deploy-and-publish/deploy-on-gateway/choreo-connect/observability/distributed-tracing.md
- en/docs/deploy-and-publish/deploy-on-gateway/choreo-connect/passing-enduser-attributes-to-the-backend-via-choreo-connect.md
- en/docs/deploy-and-publish/deploy-on-gateway/choreo-connect/security/enabling-cors.md
- en/docs/deploy-and-publish/deploy-on-gateway/choreo-connect/support-custom-claims-mapping.md
- en/docs/includes/deploy/cc-configuration-file.md
$subject
There are also some changes to maintain numbering when using an `includes` file.
> [4.1.0] Update choreo connect config info includes file and use in remaining locations as well

- en/docs/deploy-and-publish/deploy-on-gateway/choreo-connect/faq.md
port https://github.com/wso2/docs-apim/pull/6386
fixes https://github.com/wso2/docs-apim/issues/6407
> Link to the PR for changes …
> [cc] Minor formatting change to cc faq to make main topics prominent

- en/docs/deploy-and-publish/deploy-on-gateway/choreo-connect/rate-limiting/distributed-throttling.md
Add the suggestion given in issue. Fixes https://github.com/wso2/product-microgateway/issues/3127
> [4.1.0] Add cc rate limiting tip on multiple TMs

- en/docs/deploy-and-publish/deploy-on-gateway/choreo-connect/configurations/adapter-configurations.md
- en/docs/deploy-and-publish/deploy-on-gateway/choreo-connect/configurations/configuration-overview.md
- en/docs/deploy-and-publish/deploy-on-gateway/choreo-connect/configurations/enforcer-configurations.md
- en/docs/deploy-and-publish/deploy-on-gateway/choreo-connect/configurations/router-configurations.md
Fixes https://github.com/wso2/docs-apim/issues/6411
$subject
> [4.1.0] Organize cc config location info for all configs

- en/docs/design/rate-limiting/throttle-policy-import-export.md
- en/mkdocs.yml
https://github.com/wso2/docs-apim/issues/6078
Fixes https://github.com/wso2/api-manager/issues/243
> [Feature] Add documentation for "Throttle policy import-export support for APIM 

- en/docs/get-started/about-this-release.md
- All the new features have been added from the provided feature list.
- The rest of the content will be updated before the main release.
> Update the About the release page - For M1

- en/docs/get-started/about-this-release.md
This PR modifies the about this release page. …
> Add change to about this release page

- en/docs/design/api-security/api-authentication/secure-apis-using-oauth2-tokens.md
PR Sync for https://github.com/wso2/docs-apim/pull/6438
> PR Sync #6438

- en/docs/design/api-security/api-authentication/secure-apis-using-oauth2-tokens.md
PR Sync for https://github.com/wso2/docs-apim/pull/6438
> PR sync for #6438

- en/docs/install-and-setup/setup/distributed-deployment/configuring-wso2-identity-server-as-a-key-manager.md
Fix https://github.com/wso2/docs-apim/issues/6459
This documentation change is needed to fix https://github.com/wso2/api-manager/issues/918
> Documentation gap in Set up WSO2 Identity Server as a Key Manager

- en/docs/deploy-and-publish/deploy-on-gateway/choreo-connect/configurations/configure-logs-router.md
> fix broken link: for choreo connect router access logs

- en/docs/administer/key-managers/configure-custom-connector.md
Fix https://github.com/wso2/api-manager/issues/1014
> [Documentation] Add Azure AD Connector to the docs

- en/docs/install-and-setup/setup/distributed-deployment/deploying-wso2-api-m-in-a-distributed-setup-with-tm-separated.md
> Mismatch in the suggested hostnames
> Remove mismatch in host names

- en/docs/install-and-setup/setup/setting-up-proxy-server-and-the-load-balancer/configuring-the-proxy-server-and-the-load-balancer.md
Few documentation errors have been identified when testing distributed setup of APIM(https://github.com/wso2/api-manager/issues/957) and this PR contains the fixes for that.
> Configuring the Proxy Server and the Load Balancer

- en/docs/deploy-and-publish/deploy-on-gateway/choreo-connect/endpoints/defining-a-backend-security-scheme.md
port https://github.com/wso2/docs-apim/pull/6385
Fixes https://github.com/wso2/docs-apim/issues/6408
> [master] Update choreo connect backend security docs

- en/docs/deploy-and-publish/deploy-on-gateway/choreo-connect/endpoints/defining-a-backend-security-scheme.md
$subject
suggestion from https://github.com/wso2/docs-apim/pull/6419
> [4.1.0] Update backend sec heading

- en/docs/install-and-setup/setup/deployment-best-practices/basic-health-checks.md
Fixes https://github.com/wso2-enterprise/wso2-apim-internal/issues/372
> [Sync 4.0.0] Update basic-health-checks.md

- en/docs/install-and-setup/setup/deployment-best-practices/basic-health-checks.md
Fixes https://github.com/wso2-enterprise/wso2-apim-internal/issues/372
> [Sync 4.1.0] Update basic-health-checks.md

- en/docs/install-and-setup/setup/security/user-account-management.md
Fix https://github.com/wso2/docs-apim/issues/6510
This PR corrects the file path of the settings.json file
> Corrected settings.json file path

- en/docs/reference/connectors/redis-connector/2.4.x/redis-connector-reference.md
> Add redis sentinel configuration info.
Related to wso2/api-manager/issues/1095
> Add documentation changes for redis sentinel

- en/docs/assets/versions.json
Removed 4.2.0 from past releases list
Fixes https://github.com/wso2/docs-apim/issues/6518
> Removed 4.2.0 from past releases list

- en/docs/index.md
Updated source code link
Related to https://github.com/wso2/docs-apim/issues/6518
> Updated source code link

- en/docs/assets/js/theme.js
Disabling auto link for Pre-release
Related to https://github.com/wso2/docs-apim/issues/6518
> Disabling auto link for Pre-release

- en/docs/install-and-setup/setup/setting-up-databases/changing-default-databases/changing-to-ibm-db2.md
- en/docs/install-and-setup/setup/setting-up-databases/changing-default-databases/changing-to-mssql.md
- en/docs/install-and-setup/setup/setting-up-databases/changing-default-databases/changing-to-mysql.md
- en/docs/install-and-setup/setup/setting-up-databases/changing-default-databases/changing-to-postgresql.md
> Resolve the issue mentioned in the https://github.com/wso2/docs-apim/issues/6541
> remove unnecessary $ signs from cmds

- en/docs/install-and-setup/setup/api-controller/managing-common-api-policies/migrating-common-api-policies-to-different-environments.md
**Related PRs**
- https://github.com/wso2/docs-apim/pull/6103
> Fixed minor issues in Docs 

- en/docs/install-and-setup/setup/api-controller/managing-common-api-policies/managing-common-api-policies.md
Addresses feedback and issues with the common API policies document.
> Adding common API policy changes for Alpha

- en/docs/includes/integration/pull-content-registry-migration.md
Fixes https://github.com/wso2/docs-apim/issues/6556
Since we are using a common doc for the Migration section, all the versions mentioned in the above issue will be updated with this PR.
Add note about Datasources in EI to MI Migration docs
> Add note about Datasources in EI to MI Migration docs

- en/docs/install-and-setup/setup/api-controller/managing-rate-limiting-policies/throttle-policy-import-export.md
> Escape characters causing build issue

- en/docs/reference/connectors/microsoft-azure-storage-connector/microsoft-azure-storage-connector-example.md
Related to https://github.com/wso2/api-manager/issues/963, https://github.com/wso2-extensions/esb-connector-msazurestorage/pull/17
> Brief description of the new feature or bug fix as it will appear in the release …
> GIT-963_ListMetadata

- en/docs/install-and-setup/setup/api-controller/managing-common-api-policies/managing-common-api-policies.md
$title
- https://github.com/wso2/docs-apim/pull/6103
> Fixed typos

- en/docs/install-and-setup/supported-cipher-suites.md
Updated the list of secure Cipher Suites in [1].
[1] https://apim.docs.wso2.com/en/3.0.0/install-and-setup/supported-cipher-suites/
> fixes A1487

- en/docs/reference/connectors/iso8583-connector/iso8583-inbound-endpoint-example.md
As discussed in this issue: https://github.com/wso2-enterprise/wso2-apim-internal/issues/565 having this causes errors.
> Remove header length as it causes error

- en/docs/deploy-and-publish/deploy-on-gateway/choreo-connect/configurations/adapter-configurations.md
- en/docs/deploy-and-publish/deploy-on-gateway/choreo-connect/configurations/configuration-overview.md
- en/docs/deploy-and-publish/deploy-on-gateway/choreo-connect/configurations/enforcer-configurations.md
- en/docs/deploy-and-publish/deploy-on-gateway/choreo-connect/configurations/router-configurations.md
port https://github.com/wso2/docs-apim/pull/6394
fixes https://github.com/wso2/docs-apim/issues/6411
> [master] Organize cc config location info for all configs

- en/docs/install-and-setup/setup/distributed-deployment/configuring-wso2-identity-server-as-a-key-manager.md
Fixes https://github.com/wso2-enterprise/wso2-apim-internal/issues/1352 for 4.0.0
> [4.0.0] Fix notification_endpoint url for IS as KM configuration

- en/docs/install-and-setup/setup/distributed-deployment/configuring-wso2-identity-server-as-a-key-manager.md
Fixes https://github.com/wso2-enterprise/wso2-apim-internal/issues/1352 for 4.2.0
> [4.2.0] Fix notification_endpoint url for IS as KM configuration

- en/docs/install-and-setup/setup/distributed-deployment/configuring-wso2-identity-server-as-a-key-manager.md
Fixes https://github.com/wso2-enterprise/wso2-apim-internal/issues/1352 for master
> [Sync master] Fix notification_endpoint url for IS as KM configuration

- en/docs/install-and-setup/setup/distributed-deployment/configuring-wso2-identity-server-as-a-key-manager.md
Fixes https://github.com/wso2-enterprise/wso2-apim-internal/issues/1352 for 4.1.0
> [4.1.0] Fix notification_endpoint url for IS as KM configuration

- en/docs/deploy-and-publish/deploy-on-gateway/choreo-connect/configure-analytics.md
- en/docs/deploy-and-publish/deploy-on-gateway/choreo-connect/extensions/custom-filters.md
- en/docs/deploy-and-publish/deploy-on-gateway/choreo-connect/passing-enduser-attributes-to-the-backend-via-choreo-connect.md
- en/docs/deploy-and-publish/deploy-on-gateway/choreo-connect/production-deployment-guideline.md
- en/docs/deploy-and-publish/deploy-on-gateway/choreo-connect/support-custom-claims-mapping.md
> $subject
> Updates Enforcer's dropins folder's usage with helm artifacts.
> Type “Sent” when you have provided …
> [master] Update for cc Enforcer's dropins folder with helm artifacts

- en/docs/install-and-setup/upgrading-wso2-api-manager/upgrading-api-manager.md
> Fixed about this release link

- en/mkdocs.yml
Adding redirection for upgrading-to-log4j2
Related to https://github.com/wso2/docs-apim/issues/6429
> Adding redirection for upgrading-to-log4j2

- en/mkdocs.yml
Updated the main nav heading to "Upgrade".
Related to :
https://github.com/wso2/docs-apim/issues/6429
> Updated the main nav heading

- en/docs/install-and-setup/upgrading-wso2-api-manager/upgrading-api-manager.md
- en/mkdocs.yml
Fixes the navigation and title of upgrade doc.
> Fix nav for upgrade section

- en/docs/install-and-setup/setup/reference/supported-cipher-suites.md
> Mentioned support for TLSv1.3

- en/mkdocs.yml
Follow-up with https://github.com/wso2/docs-apim/pull/6475
> Add changes missed when resolving conflicts

- en/docs/install-and-setup/setup/distributed-deployment/product-profiles.md
Fix for : https://github.com/wso2/docs-apim/issues/6596
Note : https://github.com/wso2/docs-apim/issues/6596#issuecomment-1384954021 This has been removed. Once I get the sample output we can add this back to the docs.
> Remove related doc content when removing the deprecated profiles

- en/docs/install-and-setup/setup/api-controller/enabling-correlation-logs-with-apictl.md
- en/docs/reference/apictl/wso2-api-controller.md
- en/mkdocs.yml
Fixes: https://github.com/wso2/api-manager/issues/533
Adding the documentation for correlation logging support via apictl
Added a new section on the above topic in apictl documentation
> Adding the documentation for correlation logging support via apictl

- en/docs/install-and-setup/setup/api-controller/enabling-correlation-logs-with-apictl.md
- en/docs/reference/apictl/wso2-api-controller.md
- en/mkdocs.yml
Fixes: https://github.com/wso2/api-manager/issues/533
Adding the documentation for correlation logging support via apictl
Added a new section on the above topic in apictl documentation
> [4.2.0] Adding the documentation for correlation logging support via apictl

- en/docs/reference/k8s-operators/k8s-api-operator.md
Fixes https://github.com/wso2/docs-apim/issues/6479
> [Sync 4.0.0] Update k8s-api-operator.md

- en/docs/reference/k8s-operators/k8s-api-operator.md
Fixes https://github.com/wso2/docs-apim/issues/6479
> [Sync master] Update k8s-api-operator.md

- en/docs/reference/k8s-operators/k8s-api-operator.md
Fixes https://github.com/wso2/docs-apim/issues/6479
> [4.2.0 Sync] Update k8s-api-operator.md

- en/theme/material/partials/footer.html
> Updated Copyrights

- en/theme/material/partials/footer.html
> Updated the copyright statement

- en/docs/tutorials/streaming-api/create-and-publish-websub-api.md
Fixes https://github.com/wso2/docs-apim/issues/6586
> Update cURL command

- en/docs/design/advanced-topics/enable-publisher-access-control-in-api-publisher-portal.md
- en/docs/design/api-policies/create-policy.md
- en/docs/includes/design/invoke-prerelease-api.md
- en/docs/tutorials/integration-tutorials/service-catalog-tutorial-for-proxy-services.md
- en/docs/tutorials/integration-tutorials/service-catalog-tutorial.md
Fixes 
- https://github.com/wso2/docs-apim/issues/6535
- https://github.com/wso2/docs-apim/issues/6545
- https://github.com/wso2/docs-apim/issues/6533
- https://github.com/wso2/docs-apim/issues/6534
> Multiple fixes for 4.2.0

- en/docs/install-and-setup/setup/advance-configurations/changing-the-default-transport.md
Fixes https://github.com/wso2/docs-apim/issues/6572
> Fix "Changing the Default Transport" document doesn't have the required information

- en/docs/deploy-and-publish/deploy-on-gateway/choreo-connect/passing-enduser-attributes-to-the-backend-via-choreo-connect.md
> This is to update the docs with the new features relating to backend JWT and JWKS in choreo connect 1.2.0
issues: [1] (https://github.com/wso2/product-microgateway/issues/3140)
> This should document how the JWKS endpoint works and the changes to backend JWT to accomodate it.
> Backend JWT & JWKS docs

- en/theme/material/partials/footer.html
> Updated the link in the copyrights

- en/theme/material/partials/footer.html
> Updated Footer

- en/theme/material/partials/footer.html
> Updated the footer

- en/docs/reference/product-apis/devportal-apis/devportal-v3/devportal-v3.yaml
- en/docs/reference/product-apis/overview.md
- en/docs/reference/product-apis/publisher-apis/publisher-v4/publisher-v4.yaml
- Update the quickstart guide postman collection
> Update the postman collections of product APIs

- en/docs/deploy-and-publish/deploy-on-gateway/choreo-connect/configure-analytics.md
- en/docs/deploy-and-publish/deploy-on-gateway/choreo-connect/getting-started/choreo-connect-overview.md
- en/docs/deploy-and-publish/deploy-on-gateway/choreo-connect/observability/distributed-tracing.md
- en/docs/deploy-and-publish/deploy-on-gateway/choreo-connect/passing-enduser-attributes-to-the-backend-via-choreo-connect.md
- en/docs/deploy-and-publish/deploy-on-gateway/choreo-connect/security/enabling-cors.md
- en/docs/deploy-and-publish/deploy-on-gateway/choreo-connect/support-custom-claims-mapping.md
- en/docs/includes/deploy/cc-configuration-file.md
port https://github.com/wso2/docs-apim/pull/6384
fixes https://github.com/wso2/docs-apim/issues/6409
> [master] Update choreo connect config info and use in remaining locations as well

- en/docs/deploy-and-publish/deploy-on-gateway/choreo-connect/deploy-api/deploy-websocket-api-in-choreo-connect.md
- en/docs/deploy-and-publish/deploy-on-gateway/choreo-connect/endpoints/endpoint-types.md
- en/docs/deploy-and-publish/deploy-on-gateway/choreo-connect/update-choreo-connect.md
- en/mkdocs.yml
fixes https://github.com/wso2/docs-apim/issues/6406
port 4.0.0 related sections from https://github.com/wso2/docs-apim/pull/6382
> [4.0.0] Update choreo connet docs for endpoints, update

- en/docs/deploy-and-publish/deploy-on-gateway/choreo-connect/security/api-authentication/mutual-ssl-authentication.md
port https://github.com/wso2/docs-apim/pull/6565
> [master] Add config note to cc mtls doc

- en/docs/deploy-and-publish/deploy-on-gateway/choreo-connect/security/api-authentication/mutual-ssl-authentication.md
Add an important config note to cc mtls doc
> [4.2.0] Add config note to cc mtls doc

- en/docs/deploy-and-publish/deploy-on-gateway/choreo-connect/rate-limiting/distributed-throttling.md
Add the suggestion given in issue. Fixes https://github.com/wso2/product-microgateway/issues/3127
> [4.0.0] Add cc rate limiting tip on multiple TMs

- en/docs/deploy-and-publish/deploy-on-gateway/choreo-connect/rate-limiting/distributed-throttling.md
Add the suggestion given in issue. Fixes https://github.com/wso2/product-microgateway/issues/3127
> [master] Add cc rate limiting tip on multiple TMs

- en/docs/deploy-and-publish/deploy-on-gateway/choreo-connect/rate-limiting/distributed-throttling.md
Add the suggestion given in issue. Fixes https://github.com/wso2/product-microgateway/issues/3127
> [4.2.0] Add cc rate limiting tip on multiple TMs

- en/docs/deploy-and-publish/deploy-on-gateway/choreo-connect/configure-analytics.md
- en/docs/deploy-and-publish/deploy-on-gateway/choreo-connect/getting-started/choreo-connect-overview.md
- en/docs/deploy-and-publish/deploy-on-gateway/choreo-connect/observability/distributed-tracing.md
- en/docs/deploy-and-publish/deploy-on-gateway/choreo-connect/passing-enduser-attributes-to-the-backend-via-choreo-connect.md
- en/docs/deploy-and-publish/deploy-on-gateway/choreo-connect/security/enabling-cors.md
- en/docs/deploy-and-publish/deploy-on-gateway/choreo-connect/support-custom-claims-mapping.md
- en/docs/includes/deploy/cc-configuration-file.md
port https://github.com/wso2/docs-apim/pull/6384
fixes https://github.com/wso2/docs-apim/issues/6409
> [4.2.0] Update choreo connect config info and use in remaining locations as well

- en/docs/deploy-and-publish/deploy-on-gateway/choreo-connect/configurations/adapter-configurations.md
- en/docs/deploy-and-publish/deploy-on-gateway/choreo-connect/configurations/configuration-overview.md
- en/docs/deploy-and-publish/deploy-on-gateway/choreo-connect/configurations/enforcer-configurations.md
- en/docs/deploy-and-publish/deploy-on-gateway/choreo-connect/configurations/router-configurations.md
fixes https://github.com/wso2/docs-apim/issues/6411
port https://github.com/wso2/docs-apim/pull/6394
> [4.0.0] Organize cc config location info for all configs

- en/docs/deploy-and-publish/deploy-on-gateway/choreo-connect/configurations/adapter-configurations.md
- en/docs/deploy-and-publish/deploy-on-gateway/choreo-connect/configurations/configuration-overview.md
- en/docs/deploy-and-publish/deploy-on-gateway/choreo-connect/configurations/enforcer-configurations.md
- en/docs/deploy-and-publish/deploy-on-gateway/choreo-connect/configurations/router-configurations.md
port https://github.com/wso2/docs-apim/pull/6394
fixes https://github.com/wso2/docs-apim/issues/6411
> [4.2.0] Organize cc config location info for all configs

- en/docs/deploy-and-publish/deploy-on-gateway/choreo-connect/passing-enduser-attributes-to-the-backend-via-choreo-connect.md
> This is to update the docs with the new features relating to backend JWT and JWKS in choreo connect 1.2.0
issues: [1] (https://github.com/wso2/product-microgateway/issues/3140)
> This should document how the JWKS endpoint works and the changes to backend JWT to accomodate it.
> Backend JWT & JWKS docs (Master)

- en/docs/reference/connectors/connector-usage.md
Fixed https://github.com/wso2-enterprise/wso2-apim-internal/issues/1436
> [Sync 4.2.0] Update connector-usage.md

- en/docs/reference/connectors/connector-usage.md
Fixes https://github.com/wso2-enterprise/wso2-apim-internal/issues/1436
> [Sync 4.0.0] Update connector-usage.md

- en/docs/reference/connectors/connector-usage.md
Fixes https://github.com/wso2-enterprise/wso2-apim-internal/issues/1436
> [Sync master] Update connector-usage.md

- en/docs/design/api-monetization/monetizing-an-api.md
- fixes https://github.com/wso2/docs-apim/issues/6671
- Updated the WSO2AM Stripe plugin from org.wso2.apim.monetization.impl-1.3.1.jar to org.wso2.apim.monetization.impl-1.3.3.jar
> fixes https://github.com/wso2/docs-apim/issues/6671

- en/docs/design/api-monetization/monetizing-an-api.md
- fixes https://github.com/wso2/docs-apim/issues/6671
- Updated the WSO2AM Stripe plugin from org.wso2.apim.monetization.impl-1.3.1.jar to org.wso2.apim.monetization.impl-1.3.3.jar
> fixes https://github.com/wso2/docs-apim/pull/6672

- en/docs/deploy-and-publish/deploy-on-gateway/choreo-connect/security/api-authentication/api-key-authentication.md
PR sync for https://github.com/wso2/docs-apim/pull/6564/commits/9050dd8b2f4cb7ddd146ba6607b3a6f344f2874d
> fixed typo

- en/docs/reference/product-apis/overview.md
- en/docs/reference/product-apis/publisher-apis/publisher-v4/publisher-v4.yaml
> Update the postman collection of REST API Docs

- en/docs/deploy-and-publish/deploy-on-gateway/choreo-connect/analytics/pulbish-custom-analytics-attributes.md
- en/mkdocs.yml
> $subject
> Defines how to enable and use custom attributes with Choreo Connect analytics.
> Type “Sent” when you have …
> [master] Choreo Connect analytics data with custom attributes 

- en/docs/reference/product-apis/devportal-apis/devportal-v3/devportal-v3.yaml
- en/docs/reference/product-apis/overview.md
- en/docs/reference/product-apis/publisher-apis/publisher-v4/publisher-v4.yaml
Update the Postman collection of
- QSG REST APIs
- Dev portal REST APIs
- Admin REST APIs
Tracked in https://github.com/wso2/api-manager/issues/1076
> Updating Dev portal and Admin REST API postman collections 

- en/docs/reference/customize-product/extending-api-manager/saml2-sso/configuring-identity-server-as-idp-for-sso.md
> Relates to: https://github.com/wso2/docs-apim/issues/6664
> Add missing step in role configuration

- en/docs/reference/connectors/amazons3-connector/amazons3-connector-reference.md
Docs for https://github.com/wso2/api-manager/issues/1442
> Add host configuration to the doc

- en/docs/design/api-monetization/monetizing-an-api.md
> Updated Stripe plugin version

- en/docs/reference/product-apis/admin-apis/admin-v4/admin-v4.yaml
> Update the collection URL to pick the 4.2.0 REST APIs
> Update postman collection of admin REST APIs

- en/docs/api-analytics/on-prem/elk-installation-guide.md
Fixes https://github.com/wso2/docs-apim/issues/6683
> Update Links mentioned in the documentation related to On-Premise analytics

- en/docs/reference/customize-product/customizations/adding-internationalization.md
Fixes https://github.com/wso2/docs-apim/issues/6530
> Update doc "Adding Internationalization and Localization"

- en/docs/deploy-and-publish/deploy-on-gateway/api-gateway/passing-enduser-attributes-to-the-backend-via-api-gateway.md
>  Fix the default apim.jwt.claims_extractor_impl config value #6701

- en/docs/deploy-and-publish/deploy-on-gateway/api-gateway/passing-enduser-attributes-to-the-backend-via-api-gateway.md
> Fix the default apim.jwt.claims_extractor_impl config value

- en/mkdocs.yml
> [4.0.0] Update Choreo Connect Helm chart version

- en/mkdocs.yml
> [4.1.0] Update Choreo Connect Helm chart version

- en/docs/reference/product-apis/publisher-apis/publisher-v3/publisher-v3.yaml
This is a temporary fix only applicable **within the doc space**. The changes need to be ported to the product repository.
Fixes : 
https://github.com/wso2/api-manager/issues/1433
https://github.com/wso2-enterprise/wso2-apim-internal/issues/1829
> Check and populate null entries with appropriate values under API Documents related REST APIs

- en/docs/design/api-versioning/enabling-notifications.md
Fixes https://github.com/wso2/docs-apim/issues/6662
> [4.2.0] Add App password creation info to Enabling Notification feature

- en/docs/deploy-and-publish/deploy-on-gateway/api-gateway/passing-enduser-attributes-to-the-backend-via-api-gateway.md
Fixes https://github.com/wso2-enterprise/wso2-apim-internal/issues/1335
> [4.0.0] Update value in Backend JWT generator configs

- en/docs/reference/synapse-properties/transport-parameters/vfs-transport-parameters.md
Update the VFS parameters section with `StrictHostKeyChecking` parameter introduced via https://github.com/wso2/wso2-commons-vfs/pull/107
> Update VFS paramters section with StrictHostKeyChecking parameter

- en/docs/install-and-setup/setup/deployment-best-practices/basic-health-checks.md
> Added doc changes for Integrating Liveness API for MI
Related PRs,
https://github.com/wso2/micro-integrator/pull/2872
https://github.com/wso2/api-manager/issues/1463
> [Doc] Introduce MI with Liveness Health check API

- en/docs/install-and-setup/install-and-setup-overview.md
Fixes https://github.com/wso2/docs-apim/issues/6685
> Update the upgrading API Manager information

- en/docs/install-and-setup/install-and-setup-overview.md
> Revert "Update the upgrading API Manager information"

- en/mkdocs.yml
> Removed empty entries from mkdocs.yml

- en/docs/reference/connectors/email-connector/email-connector-config.md
Fixes https://github.com/wso2-enterprise/wso2-apim-internal/issues/1639
> Integration Studio Support for OAUTH2 authentication for Email connector

- en/docs/develop/wso2-admin-services.md
Fixes https://github.com/wso2-enterprise/wso2-apim-internal/issues/945
> Add Java client program for the admin services

- README.md
The purpose of this PR is to trigger the build in the Jenkins server
> Edit mkdocs command in README for python3

- en/docs/install-and-setup/setup/security/user-account-management.md
Fixes https://github.com/wso2/docs-apim/issues/6456
> [4.2.0] Add App password creation info to User Account Management doc

- en/docs/mi-analytics/mi-elk-installation-guide.md
Resolving the issue: https://github.com/wso2/api-manager/issues/1498
https://github.com/wso2/micro-integrator/pull/2876
> Adding Missing configurations to ELK Analytics Document for MI

- en/docs/troubleshooting/troubleshooting-websocket-api.md
Fixes https://github.com/wso2-enterprise/wso2-apim-internal/issues/2065
> Fix typo in Troubleshooting WebSocket APIs

- en/mkdocs.yml
Fix the broken image links in the build
> Update base path

- en/docs/tutorials/develop-an-integration-with-a-managed-api.md
Minor typo correction managed -> manage
> Minor typos

- en/docs/use-cases/streaming-tutorials/working-with-kafka.md
> grammatical typo

- en/docs/install-and-setup/setup/distributed-deployment/deploying-wso2-api-m-in-a-distributed-setup-with-tm-separated.md
- en/docs/install-and-setup/setup/distributed-deployment/deploying-wso2-api-m-in-a-distributed-setup.md
Fixes https://github.com/wso2/docs-apim/issues/6428
Fixes https://github.com/wso2-enterprise/wso2-apim-internal/issues/1260
> Requirement to mount Solr directory is not mentioned in distributed setup

- en/docs/integrate/examples/jms_examples/consuming-jms.md
Fix for https://github.com/wso2/docs-apim/issues/6401
> Fix broken url

- en/docs/design/api-security/oauth2/grant-types/ntlm-grant.md
Fix for https://github.com/wso2/docs-apim/issues/6745
> Add missing resource

- en/docs/tutorials/create-and-publish-a-graphql-api.md
Fix for https://github.com/wso2/docs-apim/issues/6524
> Add info to invoke graphql api by accepting the cert

- en/docs/tutorials/create-and-publish-a-graphql-api.md
> Revert "Add info to invoke graphql api by accepting the cert"

- en/docs/tutorials/create-and-publish-a-graphql-api.md
Fix for https://github.com/wso2/docs-apim/issues/6524
> Add troubleshooting info

- en/docs/consume/manage-application/advanced-topics/add-custom-attributes-to-applications.md
Fix for https://github.com/wso2/docs-apim/issues/6451
> Fix application attribute config issue

- en/docs/install-and-setup/setup/mi-setup/databases/setting-up-mysql.md
> $subject
> Git Issue: https://github.com/wso2/docs-apim/issues/6305
> Fix https://github.com/wso2/docs-apim/issues/6305

- en/docs/install-and-setup/setup/distributed-deployment/configuring-wso2-identity-server-as-a-key-manager.md
> [4.2.0] Add instructions to disable token exchange grant type for IS as KM

- en/docs/integrate/examples/endpoint_examples/mtom-swa-with-endpoints.md
> Fix https://github.com/wso2/docs-apim/issues/6482
> Add MTOM and SwA configs for axis2 blocking client

- en/docs/reference/product-apis/admin-apis/admin-v4/admin-v4.yaml
- en/docs/reference/product-apis/admin-apis/admin-v4/docs/examples/alerts/applications.yaml
- en/docs/reference/product-apis/devportal-apis/devportal-v3/devportal-v3.yaml
- en/docs/reference/product-apis/gateway-apis/gateway-v2/gateway-v2.yaml
- en/docs/reference/product-apis/publisher-apis/publisher-v4/publisher-v4.yaml
- en/docs/reference/product-apis/service-catalog-apis/service-catalog-v1/service-catalog-v1.yaml
Fix for https://github.com/wso2/docs-apim/issues/6789
> Update Rest API docs with the latest updates.

- en/docs/design/api-versioning/enabling-notifications.md
Fixes https://github.com/wso2/docs-apim/issues/6663
> [4.2.0] Change steps of the 'Enabling Notifications' document

- en/docs/administer/multitenancy/managing-tenants.md
> Git Issue: https://github.com/wso2/docs-apim/issues/6553
> [4.1.0] Fix Tenant deletion steps

- en/docs/administer/multitenancy/managing-tenants.md
> Git Issue: https://github.com/wso2/docs-apim/issues/6553
> [4.0.0] Fix Tenant deletion steps

- en/docs/administer/multitenancy/managing-tenants.md
> Git Issue: https://github.com/wso2/docs-apim/issues/6553
> [3.2.0] Fix Tenant deletion steps

- en/docs/administer/multitenancy/managing-tenants.md
> Git Issue: https://github.com/wso2/docs-apim/issues/6553
> Fix Tenant deletion steps

- en/docs/reference/config-catalog.md
- en/tools/config-catalog-generator/data/configs.json
- en/tools/config-catalog-generator/data/registry-handler.toml
- en/tools/config-catalog-generator/dist/config-catalog.md
- Fix 4.2.0 Docs for the issue: https://github.com/wso2/docs-apim/issues/6526
- Added the `deployment.toml` configurations details related to Registry Handlers to the [configuration catalog](https://apim.docs.wso2.com/en/4.2.0/reference/config-catalog/).
- Following are the screenshots taken from displaying newly added docs locally.
- Sample configs added to the docs are as follows.
```
[[registry_handler]]
class="org.wso2.carbon.registry.extensions.handlers.WSDLMediaTypeHandler"
filter_class="org.wso2.carbon.registry.core.jdbc.handlers.filters.MediaTypeMatcher"
[registry_handler.properties]
disableSymlinkCreation = "true"
myprop1= "true"
[[registry_handler.nested_property]]
enable = true
name = "schemaLocationConfiguration"
type = "xml" …
```
> [4.2.0] Add Docs for Registry Handler Configurations

- en/docs/reference/config-catalog.md
- en/tools/config-catalog-generator/data/configs.json
- en/tools/config-catalog-generator/data/registry-handler-sample
- en/tools/config-catalog-generator/dist/config-catalog.md
- Fix 3.2.0 Docs for the issue: https://github.com/wso2/docs-apim/issues/6526
- Added the `deployment.toml` configurations details related to Registry Handlers to the [configuration catalog](https://apim.docs.wso2.com/en/3.2.0/reference/config-catalog/).
- Following are the screenshots taken from displaying newly added docs locally.
- Sample configs added to the docs are as follows.
```
[[registry_handler]]
class="org.wso2.carbon.registry.extensions.handlers.WSDLMediaTypeHandler"
filter_class="org.wso2.carbon.registry.core.jdbc.handlers.filters.MediaTypeMatcher"
[registry_handler.properties]
disableSymlinkCreation = "true"
myprop1= "true"
[[registry_handler.nested_property]]
enable = true
name = "schemaLocationConfiguration"
type = "xml" …
```
> [3.2.0] Add Docs for Registry Handler Configurations

- en/docs/deploy-and-publish/publish-on-dev-portal/third-party-api-support.md
Fixes https://github.com/wso2/docs-apim/issues/6628
**Output:**
> Update Add a Third-party API doc

- en/docs/get-started/streaming-quick-start-guide.md
Fixes https://github.com/wso2/docs-apim/issues/6732
> Improve Streaming Integrator Quick Start Guide

- en/docs/reference/product-apis/publisher-apis/publisher-v3/publisher-v3.yaml
Fix for https://github.com/wso2-enterprise/wso2-apim-internal/issues/1764
Note : Updated the description **only** in the docs.
Output:
> Correct Payload Format for Using Publisher Rest API 

- en/docs/install-and-setup/setup/deployment-best-practices/production-deployment-guidelines.md
- en/docs/install-and-setup/setup/deployment-best-practices/security-guidelines-for-production-deployment.md
- en/docs/install-and-setup/setup/security/configuring-transport-level-security.md
- en/docs/install-and-setup/setup/setting-up-proxy-server-and-the-load-balancer/adding-a-custom-proxy-path.md
- en/docs/reference/faq.md
Fixes https://github.com/wso2-enterprise/wso2-apim-internal/issues/1631
Fixes https://github.com/wso2-enterprise/wso2-apim-internal/issues/2184
> Update TLS version in toml config

- en/docs/administer/key-managers/configure-wso2is-connector.md
- en/docs/install-and-setup/setup/distributed-deployment/configuring-wso2-identity-server-as-a-key-manager.md
Fixes https://github.com/wso2-enterprise/wso2-apim-internal/issues/1738
> Fix the resource access control config for keymanager-operations/dcr/register POST method 

- en/docs/administer/key-managers/configure-wso2is-connector.md
Fixes https://github.com/wso2-enterprise/wso2-apim-internal/issues/1738
> Fix the resource access control config for keymanager-operations/dcr/register POST method

- en/docs/reference/connectors/email-connector/email-connector-config.md
Fixes
- https://github.com/wso2-enterprise/wso2-apim-internal/issues/2001
> Update email connector docs with inlineImages parameter

- en/docs/install-and-setup/setup/api-controller/managing-rate-limiting-policies/migrating-rate-limiting-policies-to-different-environments.md
Fix for 
- https://github.com/wso2/docs-apim/issues/6833
> Fix formatting in Migrating Rate Limiting Policies to Different Environments

- en/docs/integrate/integration-overview.md
Fix version in https://apim.docs.wso2.com/en/4.2.0/integrate/integration-overview/
> Update 4.1.0 to 4.2.0

- en/mkdocs.yml
> To add subscription deletion workflow doc page.
> Doc creation PR - https://github.com/wso2/docs-apim/pull/6704
> Subscription deletion workflow doc link

- en/docs/use-cases/examples/streaming-examples/cdc-with-listening-mode.md
- en/docs/use-cases/streaming-tutorials/creating-etl-application-via-tooling.md
Fixes 
- https://github.com/wso2/docs-apim/issues/6831
> Add note about SQL statement

- en/docs/design/advanced-topics/control-api-visibility-and-subscription-availability-in-developer-portal.md
Fixes 
- https://github.com/wso2-enterprise/wso2-apim-internal/issues/1903
> Add missing configuration in cross tenant subscriptions doc

- en/docs/learn/design-api/advanced-topics/control-api-visibility-and-subscription-availability-in-developer-portal.md
Fixes
- https://github.com/wso2-enterprise/wso2-apim-internal/issues/1903
> [Sync PR] Add missing configuration in cross tenant subscriptions doc 

- en/docs/design/advanced-topics/control-api-visibility-and-subscription-availability-in-developer-portal.md
Fixes
- https://github.com/wso2-enterprise/wso2-apim-internal/issues/1903
> [Sync PR] Add missing configuration in cross tenant subscriptions doc

- en/docs/get-started/about-this-release.md
Fixes https://github.com/wso2/docs-apim/issues/6870
> Add deprecated/removed features in "About this release" page

- en/docs/reference/customize-product/extending-api-manager/extending-gateway/writing-custom-handlers.md
update versions in https://apim.docs.wso2.com/en/4.2.0/reference/customize-product/extending-api-manager/extending-gateway/writing-custom-handlers/
> Update versions in

- en/docs/get-started/about-this-release.md
Fixes https://github.com/wso2/docs-apim/issues/6873
> Update fixed issues and known issues links

- en/docs/integrate/develop/customizations/creating-custom-mediators.md
> customer -> custom

- en/docs/get-started/about-this-release.md
Fixes
- https://github.com/wso2/docs-apim/issues/6865
> Move the What Has Changed section to About this release page

- en/docs/getting-started/about-this-release.md
Fixes
- https://github.com/wso2/docs-apim/issues/6865
> Move the What Has Changed section to About this release page 

- en/docs/install-and-setup/setup/distributed-deployment/product-profiles.md
Address comment in 
- https://github.com/wso2/docs-apim/issues/6596#issuecomment-1441703183
> Add sample output which is seen when starting 'Gateway worker profile'.

- en/docs/reference/customize-product/customizations/customizing-the-developer-portal/customize-api-listing/change-default-view.md
Fix https://apim.docs.wso2.com/en/4.2.0/reference/customize-product/customizations/customizing-the-developer-portal/customize-api-listing/change-default-view/
> Fix change-default-view page

- en/docs/reference/customize-product/customizations/customizing-the-developer-portal/enabling-or-disabling-api-detail-tabs.md
Update https://apim.docs.wso2.com/en/4.2.0/reference/customize-product/customizations/customizing-the-developer-portal/enabling-or-disabling-api-detail-tabs/
> Update theming doc for 4.2.0

- en/docs/reference/customize-product/customizations/customizing-the-developer-portal/enable-or-disable-home-page.md
Fix https://apim.docs.wso2.com/en/4.2.0/reference/customize-product/customizations/customizing-the-developer-portal/enable-or-disable-home-page/
> Fix theming doc for 4.2.0

- en/docs/reference/customize-product/customizations/customizing-the-developer-portal/styling-the-logo-and-header.md
Fix https://apim.docs.wso2.com/en/4.2.0/reference/customize-product/customizations/customizing-the-developer-portal/styling-the-logo-and-header/
> Fix 4.2.0 theming doc

- en/docs/reference/customize-product/customizations/customizing-the-developer-portal/styling-api-details-info-section.md
Fix https://apim.docs.wso2.com/en/4.2.0/reference/customize-product/customizations/customizing-the-developer-portal/styling-api-details-info-section/
> Fix theming 4.2.0 doc

- en/docs/design/api-security/authorization/role-based-access-control-using-xacml.md
Update https://apim.docs.wso2.com/en/4.2.0/design/api-security/authorization/role-based-access-control-using-xacml/
> Update XACML doc for 4.2.0

- en/docs/get-started/about-this-release.md
Mentioning about the removed publisher, devportal profiles
Fixes https://github.com/wso2/docs-apim/issues/6895
> Mentioning about the removed publisher, devportal profiles

- en/docs/reference/connectors/salesforce-connectors/salesforcebulk-v2-connector-example.md
- en/docs/reference/connectors/salesforce-connectors/salesforcebulk-v2-reference.md
- en/mkdocs.yml
> Related to: https://github.com/wso2-enterprise/wso2-apim-internal/issues/2072
> Add salesforce bulk api v2 connector docs

- en/docs/reference/connectors/salesforce-connectors/salesforcebulk-v2-connector-example.md
- en/docs/reference/connectors/salesforce-connectors/salesforcebulk-v2-reference.md
- en/mkdocs.yml
Related to : 
- https://github.com/wso2/docs-apim/pull/6896
> Salesforce bulk api v2 connector docs

- en/docs/deploy-and-publish/deploy-on-gateway/choreo-connect/troubleshooting/debug-memory.md
Add missing parts in Docker Compose setup for debugging memory issues in Router.
> [4.1.0] Update Router debug memory steps for Docker Compose

- en/docs/deploy-and-publish/deploy-on-gateway/choreo-connect/troubleshooting/debug-memory.md
port https://github.com/wso2/docs-apim/pull/6904
> [4.0.0] Update Router debug memory steps for Docker Compose

- en/docs/deploy-and-publish/deploy-on-gateway/choreo-connect/troubleshooting/debug-memory.md
port https://github.com/wso2/docs-apim/pull/6904
> [master] Update Router debug memory steps for Docker Compose

- en/docs/deploy-and-publish/deploy-on-gateway/choreo-connect/deploy-api/deploy-api-with-custom-hostnames.md
- en/docs/deploy-and-publish/deploy-on-gateway/choreo-connect/getting-started/deploy/cc-on-kubernetes-with-apim-as-control-plane-helm-artifacts.md
- en/docs/deploy-and-publish/deploy-on-gateway/choreo-connect/getting-started/deploy/cc-on-kubernetes-with-apim-as-control-plane.md
- en/docs/deploy-and-publish/deploy-on-gateway/choreo-connect/getting-started/quick-start-guide-docker-with-apim.md
- en/docs/deploy-and-publish/deploy-on-gateway/choreo-connect/getting-started/supported-features.md
> [master] Update Choreo Connect Helm Deployment Guide

- en/docs/install-and-setup/setup/security/configuring-transport-level-security.md
Update based on the mail thread
> Update supported cipher suites in product documentations

- en/docs/install-and-setup/install/installation-options.md
> Update installation options

- en/docs/install-and-setup/setup/api-controller/advanced-topics/using-dynamic-data-in-api-controller-projects.md
- en/docs/install-and-setup/setup/api-controller/building-jenkins-ci-cd-pipeline.md
- en/docs/install-and-setup/setup/api-controller/cicd-using-cli.md
- en/docs/install-and-setup/setup/api-controller/encrypting-secrets-with-ctl.md
- en/docs/install-and-setup/setup/api-controller/getting-started-with-wso2-api-controller.md
- en/docs/install-and-setup/setup/api-controller/managing-apis-api-products/importing-apis-via-dev-first-approach.md
- en/docs/install-and-setup/setup/api-controller/managing-apis-api-products/managing-apis-and-api-products.md
- en/docs/install-and-setup/setup/api-controller/managing-apis-api-products/migrating-api-products-to-different-environments.md
- en/docs/install-and-setup/setup/api-controller/managing-apis-api-products/migrating-apis-to-different-environments.md
- en/docs/install-and-setup/setup/api-controller/managing-applications/managing-applications.md
- en/docs/install-and-setup/setup/api-controller/managing-rate-limiting-policies/migrating-rate-limiting-policies-to-different-environments.md
Add the new changes to the docs related to APIM 4.2.0 release.
> Change the controller docs for APIM 4.2.0

- en/docs/index.md
> Fix code block showing in page

- en/docs/deploy-and-publish/deploy-on-gateway/choreo-connect/configurations/configuration-overview.md
- en/docs/deploy-and-publish/deploy-on-gateway/choreo-connect/production-deployment-guideline.md
$subject
Fixes https://github.com/wso2/docs-apim/issues/6711
Fixes https://github.com/wso2/product-microgateway/issues/3155
> [4.2.0] Document `mountAs` in Choreo Connect Helm chart in Prod Guide

- en/docs/deploy-and-publish/deploy-on-gateway/choreo-connect/configurations/configuration-overview.md
- en/docs/deploy-and-publish/deploy-on-gateway/choreo-connect/production-deployment-guideline.md
port https://github.com/wso2/docs-apim/pull/6921
> [4.0.0] Document mountAs in Choreo Connect Helm chart in Prod Guide

- en/docs/deploy-and-publish/deploy-on-gateway/choreo-connect/configurations/configuration-overview.md
- en/docs/deploy-and-publish/deploy-on-gateway/choreo-connect/production-deployment-guideline.md
port https://github.com/wso2/docs-apim/pull/6921
> [4.1.0] Document mountAs in Choreo Connect Helm chart in Prod Guide

- en/docs/deploy-and-publish/deploy-on-gateway/choreo-connect/configurations/configuration-overview.md
- en/docs/deploy-and-publish/deploy-on-gateway/choreo-connect/production-deployment-guideline.md
port https://github.com/wso2/docs-apim/pull/6921
> [master] Document mountAs in Choreo Connect Helm chart in Prod Guide

- en/docs/design/api-security/oauth2/oauth2-scopes/fine-grained-access-control-with-oauth-scopes.md
Fixes 
- https://github.com/wso2-enterprise/wso2-apim-internal/issues/2332
> Remove deprecation note

- en/docs/install-and-setup/install/installing-the-product/installing-api-m-as-a-windows-service.md
Fixes https://github.com/wso2/docs-apim/issues/6958
> Fixing issue related to running as a windows service

- en/docs/install-and-setup/install/installing-the-product/installing-api-m-as-a-windows-service.md
For fixing https://github.com/wso2/docs-apim/issues/6958
> Removing redundant line

- en/docs/install-and-setup/install/installing-the-product/installing-api-m-as-a-windows-service.md
Fixes https://github.com/wso2/docs-apim/issues/6958
>  Fixing log overriding issue when running APIM as a windows service

- en/docs/reference/connectors/redis-connector/2.7.x/redis-connector-reference.md
- en/mkdocs.yml
Related: https://github.com/wso2/api-manager/issues/1690
> Add Redis connector version 2.7.0 docs

- en/docs/install-and-setup/install/installing-the-product/running-the-mi-dashboard.md
- en/docs/reference/config-catalog-mi-dashboard.md
Fixes https://github.com/wso2/docs-apim/issues/6956
> Add tested Identity Providers to MI dashboard SSO docs

- en/docs/install-and-setup/install/installing-the-product/running-the-mi-dashboard.md
- en/docs/reference/config-catalog-mi-dashboard.md
Sync PR for : https://github.com/wso2/docs-apim/pull/6973
> [Sync PR] Add tested Identity Providers to MI dashboard SSO docs

- en/docs/mi-analytics/setting-up-mi-analytics.md
> Remove unsupported cloud details

- en/docs/reference/mediators/about-mediators.md
> Correct link for script mediators in about-mediators.md

- en/docs/administer/multitenancy/introduction-to-multitenancy.md
Fixes :
- https://github.com/wso2-enterprise/wso2-apim-internal/issues/2610
> Update Multitenancy definition and modes

- en/docs/api-analytics/on-prem/datadog-installation-guide.md
- en/docs/api-analytics/on-prem/elk-installation-guide.md
> Update ELK and Datadog docs

- en/docs/administer/key-managers/configure-wso2is-connector.md
- en/docs/install-and-setup/setup/distributed-deployment/configuring-wso2-identity-server-as-a-key-manager.md
Fix for : https://github.com/wso2/docs-apim/issues/6948
> Update JAR file names

- en/docs/administer/key-managers/configure-wso2is-connector.md
- en/docs/install-and-setup/setup/distributed-deployment/configuring-wso2-identity-server-as-a-key-manager.md
Fixes : https://github.com/wso2/docs-apim/issues/6948
> [Sync PR] Update JAR file names

- en/docs/install-and-setup/setup/reference/product-compatibility.md
Fixes 
- https://github.com/wso2-enterprise/wso2-apim-internal/issues/2501
> APIM 4.2.0 and IS version compatibility

- en/docs/reference/mediators/aggregate-mediator.md
Fix for https://github.com/wso2-enterprise/wso2-apim-internal/issues/2625#issuecomment-1512645666
> Aggregate correlateOn expression

- en/docs/design/api-monetization/monetizing-an-api.md
Fixes 
- https://github.com/wso2/docs-apim/issues/7011
> Document Monetization with Elasticsearch

- en/docs/design/api-monetization/monetizing-an-api.md
Sync PR for : https://github.com/wso2/docs-apim/pull/7013
Fix for : 
- https://github.com/wso2/docs-apim/issues/7011
> [Sync PR] Document Monetization with Elasticsearch

- en/docs/install-and-setup/install/installing-the-product/running-the-mi-dashboard.md
- en/docs/reference/config-catalog-mi-dashboard.md
Add doc update on https://github.com/wso2/api-manager/issues/1525
This can be merged once the update is released.
> Link to the …
> Update docs for Asgardeo Upgrade on MI Dashboard SSO feature

- en/docs/install-and-setup/install/installing-the-product/running-the-mi-dashboard.md
- en/docs/reference/config-catalog-mi-dashboard.md
Add doc update on wso2/api-manager#1525 …
> [BackPort] [4.1.0] Update docs for Asgardeo Upgrade on MI Dashboard SSO feature

- en/docs/design/advanced-topics/validate-api-definitions-with-linters.md
- en/mkdocs.yml
Sync PR for https://github.com/wso2/docs-apim/pull/7023
> Add back API Linter Feature Documentation

- en/docs/install-and-setup/setup/distributed-deployment/understanding-the-distributed-deployment-of-wso2-api-m.md
Fixes 
- https://github.com/wso2-enterprise/wso2-apim-internal/issues/2528
> Add note on Databases used by API-M profiles

- en/docs/install-and-setup/setup/distributed-deployment/understanding-the-distributed-deployment-of-wso2-api-m.md
Fixes
- https://github.com/wso2-enterprise/wso2-apim-internal/issues/2528
> [Sync PR] Add note on Databases used by API-M profiles

- en/docs/design/api-security/oauth2/grant-types/client-credentials-grant.md
Fixes
- https://github.com/wso2-enterprise/wso2-apim-internal/issues/3041
> Remove "Set a custom validity time for the access token" section

- en/docs/install-and-setup/setup/api-controller/getting-started-with-wso2-api-controller.md
Change the artifacts to the latest in the doc for APICTL - 4.0.3
> Update download artifacts with APICTL-4.0.3 release

- en/docs/install-and-setup/setup/security/enabling-hostname-verification.md
Fixes
- https://github.com/wso2-enterprise/wso2-apim-internal/issues/2852
> Change path in configuring hostname verification doc

- en/docs/install-and-setup/setup/security/securing-api-m-web-portals.md
Documentation related to 
- https://github.com/wso2/carbon-apimgt/pull/12035
- https://github.com/wso2/apim-apps/pull/469
> Bypass Client Credentials by making PKCE Mandatory

- en/docs/integrate/develop/creating-artifacts/creating-an-api.md
Add a note about the naming convention for the soap-to-rest feature
> Add a note about the naming convention for the soap-to-rest feature

- en/docs/reference/mediators/script-mediator.md
As mentioned in : https://github.com/wso2-enterprise/wso2-apim-internal/issues/2188#issuecomment-1581835945
> Update script mediator doc

- en/docs/deploy-and-publish/deploy-on-gateway/choreo-connect/security/api-authentication/mutual-ssl-authentication.md
$subject
https://github.com/wso2/docs-apim/pull/7065
> Update release date of CC 1.0.0.20

- en/docs/install-and-setup/setup/security/securing-api-m-web-portals.md
4.0 PR related to https://github.com/wso2/docs-apim/pull/7061
> [4.0.0] Bypass Client Credentials by making PKCE Mandatory

- en/docs/reference/connectors/kafka-connector/kafka-inbound-endpoint-example.md
Add kafka inbound endpoint basic authentication parameters
Related Issue: https://github.com/wso2/api-manager/issues/1903
> Link …
> Add kafka inbound endpoint basic authentication parameters

- en/docs/reference/synapse-properties/transport-parameters/vfs-transport-parameters.md
$subject
https://github.com/wso2/wso2-synapse/pull/1814
> Update VFS docs with 'transport.vfs.UpdateLastModified' parameter

- en/docs/install-and-setup/setup/security/securing-api-m-web-portals.md
4.2 PR related to https://github.com/wso2/docs-apim/pull/7061
- Do not merge this. Will update the release date after the release of the fix.
> [4.2.0] Bypass Client Credentials by making PKCE Mandatory

- en/docs/install-and-setup/setup/security/configuring-transport-level-security.md
Fixes 
- https://github.com/wso2/docs-apim/issues/6988
> Fix broken attachment download

- en/docs/observe/api-manager/metrics/jmx-based-monitoring.md
- en/docs/reference/connectors/salesforce-connectors/sf-overview.md
Fixes
- https://github.com/wso2-enterprise/wso2-apim-internal/issues/3249
- https://github.com/wso2/docs-apim/issues/6338
> [Sync PR] Remove Service MBeans section + Fix link

- en/docs/observe/api-manager/metrics/jmx-based-monitoring.md
- en/docs/reference/connectors/salesforce-connectors/sf-overview.md
Fixes
- https://github.com/wso2-enterprise/wso2-apim-internal/issues/3249
- https://github.com/wso2/docs-apim/issues/6338
> Remove Service MBeans section + Fix link

- en/mkdocs.yml
Add redirection to fix the page not found issue for https://apim.docs.wso2.com/en/latest/api-analytics/getting-started-guide/.
> Add redirection

- en/docs/reference/mediators/data-mapper-mediator.md
> Update data-mapper-mediator.md for JDK17 nashorn jar replacement

- en/docs/install-and-setup/setup/deployment-best-practices/security-guidelines-for-production-deployment.md
Mail : Requesting a fix verification of security advisory for latest APIM products.
> Add Configure client authentication section

- en/docs/install-and-setup/setup/api-controller/managing-common-api-policies/managing-common-api-policies.md
`Managing common API Policies`
> [Sync PR]Fix link and description

- en/docs/install-and-setup/setup/api-controller/managing-common-api-policies/managing-common-api-policies.md
`Managing common API Policies`
> Fix link and description

- en/docs/integrate/examples/data_integration/odata-service.md
Fixes : 
- https://github.com/wso2-enterprise/wso2-apim-internal/issues/870
> Add note for OData Feature

- en/docs/design/api-policies/attach-policy.md
- Fix API level policy support feature released update level
- Fix typo which was added via https://github.com/wso2/docs-apim/pull/7091
> Fix API level policy support feature released update level

- en/docs/integrate/develop/creating-artifacts/creating-an-api.md
> Update SOAP to REST Limitations

- en/docs/integrate/examples/file-processing/accessing_windows_share_using_vfs_transport.md
Fixes
- https://github.com/wso2-enterprise/wso2-apim-internal/issues/3731
> SMBv2/v3 support of VFS transport

- en/docs/reference/product-apis/publisher-apis/publisher-v3/publisher-v3.yaml
> [4.1.0] Mark categories field in api as readOnly

- en/docs/install-and-setup/setup/api-controller/getting-started-with-wso2-api-controller.md
> Update APICTL 4.2.1 Artifacts in the Docs

- en/docs/install-and-setup/setup/distributed-deployment/deploying-wso2-api-m-in-a-distributed-setup-with-tm-separated.md
- en/docs/install-and-setup/setup/distributed-deployment/deploying-wso2-api-m-in-a-distributed-setup.md
> Fixes analytics link in 2 pages
> Fixes analytics link in 2 pages

- en/docs/install-and-setup/setup/deployment-best-practices/performance-test-results-mi.md
Fixes : https://github.com/wso2/docs-apim/issues/7088
> Fix Performance Test Results Images 

- en/docs/reference/product-apis/admin-apis/admin-v4/admin-v4.yaml
- en/docs/reference/product-apis/devportal-apis/devportal-v3/devportal-v3.yaml
- en/docs/reference/product-apis/publisher-apis/publisher-v4/publisher-v4.yaml
Fix for : https://github.com/wso2-enterprise/wso2-apim-internal/issues/3758
> Update Publisher REST API URL version to v4

- en/docs/reference/product-apis/admin-apis/admin-v4/admin-v4.yaml
- en/docs/reference/product-apis/devportal-apis/devportal-v3/devportal-v3.yaml
- en/docs/reference/product-apis/publisher-apis/publisher-v4/publisher-v4.yaml
Fix for : https://github.com/wso2-enterprise/wso2-apim-internal/issues/3758
> [Sync PR] Update Publisher REST API URL version to v4

- en/docs/learn/api-security/api-authentication/secure-apis-using-api-keys.md
> add doc message on passing user/app attributes for api key

- en/docs/learn/api-controller/getting-started-with-wso2-api-controller.md
Add latest api controller to docs
> Add latest api controller

- en/docs/mi-analytics/setting-up-mi-analytics.md
Fixes
- https://github.com/wso2-enterprise/wso2-apim-internal/issues/4077
> Add missing in MI Analytics configurations doc

- en/docs/install-and-setup/setup/deployment-best-practices/security-guidelines-for-production-deployment.md
Fixes:
- https://github.com/wso2-enterprise/wso2-apim-internal/issues/3397
> Update documentation of APIM for transport.https.sslHostConfig.properties

- en/docs/install-and-setup/setup/api-controller/advanced-topics/configuring-different-endpoint-security-types.md
Fixes:
- https://github.com/wso2-enterprise/wso2-apim-internal/issues/3162
> Configuring customParameters without any parameters

- en/docs/deploy-and-publish/deploy-on-gateway/api-gateway/mutual-ssl-between-api-gateway-and-backend.md
Fixes
- https://github.com/wso2/docs-apim/issues/7168
- https://github.com/wso2-enterprise/wso2-apim-internal/issues/3964
> Add note about ports for server parameter

- en/docs/reference/customize-product/customizations/advanced-ui-customization.md
Related issue: https://github.com/wso2-enterprise/wso2-apim-internal/issues/4178
> [4.1.0] Add nodejs version compatibility

- en/docs/reference/customize-product/customizations/advanced-ui-customization.md
Related issue: https://github.com/wso2-enterprise/wso2-apim-internal/issues/4178
> [4.2.0] Add nodejs version compatibility

- en/docs/reference/customize-product/customizations/advanced-ui-customization.md
Related issue: https://github.com/wso2-enterprise/wso2-apim-internal/issues/4178
> Add nodejs version compatibility

- en/docs/reference/connectors/file-connector/3.x/file-connector-3.x-config.md
This PR is to update the File Connector version.
This will fix https://github.com/wso2/docs-apim/issues/7199.
> [4.1.0] Update file-connector-3.x-config.md

- en/docs/reference/connectors/file-connector/3.x/file-connector-3.x-config.md
This PR is to update the File Connector version.
This will fix https://github.com/wso2/docs-apim/issues/7199.
> [Sync PR] Update file-connector-3.x-config.md

- en/docs/learn/api-security/openid-connect/obtaining-user-profile-information-with-openid-connect.md
Fixes
- https://github.com/wso2-enterprise/wso2-apim-internal/issues/3832
> Add Note - `Securing JWT Validation in User Info and Token Introspection Endpoints`

- en/docs/reference/config-catalog-mi.md
This PR is to fix broken links on `en/docs/reference/config-catalog-mi.md`.
This will fix https://github.com/wso2-enterprise/wso2-mi-internal/issues/18.
> [Sync Master] Fix broken links

- en/docs/install-and-setup/setup/setting-up-databases/managing-data-growth-and-improving-performance.md
Fixes: 
- https://github.com/wso2-enterprise/wso2-apim-internal/issues/4224
> Add missing information regarding token cleanup in APIM documentation

- en/docs/learn/api-controller/getting-started-with-wso2-api-controller.md
This PR updates the APICTL version, download links and adds the assets for APICTL 3.0.4 release.
> [3.0.0] Update version and download links for APICTL 3.0.4

- en/docs/get-started/apim-architecture.md
Fixes: 
- https://github.com/wso2/docs-apim/issues/6966
> Fix WSO2 Enterprise Integrator Page link

- en/docs/design/rate-limiting/advanced-topics/configuring-rate-limiting-api-gateway-cluster.md
- en/mkdocs.yml
Doc changes for the feature implementation of Improvement for BackEnd and burst related distributed throttling" [1] in apim-4.2.0.
Screenshots:
[1] https://github.com/wso2/api-manager/issues/1791
> Doc changes for redis distributed throttling improvement feature

- en/docs/design/rate-limiting/advanced-topics/configuring-rate-limiting-api-gateway-cluster.md
- en/mkdocs.yml
> Revert "Doc changes for redis distributed throttling improvement feature"

- en/docs/reference/connectors/salesforce-connectors/salesforcebulk-v2-connector-example.md
- en/docs/reference/connectors/salesforce-connectors/salesforcebulk-v2-reference.md
Update the documentation according to the PR: https://github.com/wso2-extensions/esb-connector-salesforcebulk/pull/37
> Update salesforcebulk-v2 connector docs

- en/docs/install-and-setup/setup/api-controller/managing-apis-api-products/importing-apis-via-dev-first-approach.md
Fixes https://github.com/wso2/docs-apim/issues/7228
> Update documentation for importing an API via APICTL with different preserve-provider values

- en/docs/install-and-setup/setup/api-controller/getting-started-with-wso2-api-controller.md
- en/docs/install-and-setup/setup/api-controller/managing-apis-api-products/managing-apis-and-api-products.md
- en/docs/install-and-setup/setup/api-controller/managing-applications/managing-applications.md
This PR updates the APICTL version, download links and adds the assets for APICTL 4.0.4 release.
> [4.0.0] Update version and download links for APICTL 4.0.4

- en/docs/install-and-setup/setup/api-controller/advanced-topics/configuring-different-endpoint-security-types.md
- en/docs/install-and-setup/setup/api-controller/advanced-topics/configuring-environment-specific-parameters.md
- en/mkdocs.yml
Fixes https://github.com/wso2/product-apim-tooling/issues/786
Backporting https://github.com/wso2/docs-apim/pull/4842
> Add changes to support oauth2 security via params.yaml

- en/docs/install-and-setup/setup/api-controller/getting-started-with-wso2-api-controller.md
- en/docs/install-and-setup/setup/api-controller/managing-apis-api-products/managing-apis-and-api-products.md
- en/docs/install-and-setup/setup/api-controller/managing-applications/managing-applications.md
This PR updates the APICTL version, download links and adds the assets for APICTL 4.1.1 release.
> [4.1.0] Update version and download links for APICTL 4.1.1

- en/docs/deploy-and-publish/deploy-on-gateway/choreo-connect/deploy-api/deploy-rest-to-soap-api.md
- en/docs/deploy-and-publish/deploy-on-gateway/choreo-connect/deploy-api/deploy-soap-api-passthrough.md
- en/docs/deploy-and-publish/deploy-on-gateway/choreo-connect/security/rejecting-revoked-tokens.md
- en/docs/design/api-monetization/monetizing-an-api.md
- en/docs/design/endpoints/resiliency/endpoint-timeouts.md
> This PR correct certain link in APIM latest version
> Rectifying some link in apim 4.2.0 so the user is directing to the right page

- en/docs/install-and-setup/setup/api-controller/cicd-using-cli.md
- en/docs/install-and-setup/setup/api-controller/enabling-correlation-logs-with-apictl.md
- en/docs/install-and-setup/setup/api-controller/getting-started-with-wso2-api-controller.md
- en/docs/install-and-setup/setup/api-controller/managing-apis-api-products/managing-apis-and-api-products.md
- en/docs/install-and-setup/setup/api-controller/managing-applications/managing-applications.md
This PR updates the version and download links for APICTL 4.2.2 release.
> [4.2.0] Update version and download links for APICTL 4.2.2

- en/docs/consume/generating-sdks/write-a-client-application-using-the-sdk.md
- en/docs/deploy-and-publish/deploy-on-gateway/choreo-connect/analytics/publish-custom-analytics-attributes.md
- en/docs/deploy-and-publish/deploy-on-gateway/choreo-connect/deploy-api/deploy-rest-to-soap-api.md
- en/docs/deploy-and-publish/deploy-on-gateway/choreo-connect/deploy-api/deploy-soap-api-passthrough.md
- en/docs/deploy-and-publish/deploy-on-gateway/choreo-connect/security/rejecting-revoked-tokens.md
- en/docs/design/api-monetization/monetizing-an-api.md
- en/docs/design/endpoints/resiliency/endpoint-timeouts.md
- en/docs/integrate/develop/advanced-development/applying-security-to-a-proxy-service.md
- en/docs/integrate/develop/create-integration-project.md
- en/docs/integrate/develop/creating-artifacts/creating-a-message-store.md
- en/docs/integrate/develop/creating-artifacts/creating-an-inbound-endpoint.md
- en/docs/integrate/develop/creating-artifacts/creating-scheduled-task.md
- en/docs/integrate/develop/intro-integration-development.md
- en/docs/integrate/develop/using-remote-micro-integrator.md
- en/docs/integrate/examples/protocol-switching/switching_from_https_to_jms.md
- en/docs/integrate/integration-use-case/connectors.md
Rectifying broken links of several pages that were redirecting to a page-not found page
> Correcting the broken links of several pages

- en/docs/install-and-setup/setup/setting-up-proxy-server-and-the-load-balancer/adding-a-custom-proxy-path.md
- Add documentation changes related to https://github.com/wso2/product-apim/pull/13269
- Update outdated file names
- Remove .j2 file update step
- Update webapp related file names and content
> Update custom proxy path docs

- en/docs/install-and-setup/setup/setting-up-proxy-server-and-the-load-balancer/adding-a-custom-proxy-path.md
- Add documentation changes related to https://github.com/wso2/product-apim/pull/13269
- Update outdated file names
- Remove .j2 file update step
- Update webapp related file names and content
> [4.2.0] Update custom proxy path docs

- en/docs/reference/connectors/kafka-connector/kafka-connector-config.md
This PR is to update the Kafka Connector Documentation. 
This will fix https://github.com/wso2-enterprise/wso2-mi-internal/issues/97.
> Update kafka connector page

- en/docs/design/api-security/oauth2/grant-types/password-grant.md
- en/docs/design/create-api/create-rest-api/create-a-rest-api-from-an-openapi-definition.md
- en/docs/design/lifecycle-management/customize-api-life-cycle.md
- en/docs/develop/streaming-apps/working-with-the-design-view.md
- en/docs/get-started/api-manager-quick-start-guide.md
- en/docs/includes/design/create-graphql-api.md
- en/docs/install-and-setup/setup/mi-setup/brokers/configure-with-hornetq.md
- en/docs/install-and-setup/setup/mi-setup/databases/setting-up-postgresql.md
- en/docs/install-and-setup/setup/mi-setup/transport_configurations/configuring-transports.md
- en/docs/install-and-setup/setup/security/configuring-keystores/keystore-basics/renewing-a-ca-signed-certificate-in-a-keystore.md
- en/docs/install-and-setup/setup/si-setup/supporting-different-transports.md
- en/docs/reference/connectors/utility-module/utility-module-overview.md
> This PR fixes the 404 error pages found by the tool.
> Correcting the 404 page errors

- en/docs/learn/design-api/create-api/create-a-rest-api-from-a-swagger-definition.md
> [3.1.0] Update Open API Swagger Definition URL

- en/docs/administer/managing-users-and-roles/managing-user-stores/configuring-secondary-user-stores.md
- en/docs/administer/managing-users-and-roles/managing-user-stores/configuring-the-authorization-manager.md
- en/docs/administer/multitenancy/introduction-to-multitenancy.md
- en/docs/administer/updating-wso2-api-manager.md
- en/docs/install-and-setup/install/installing-the-product/installing-api-m-runtime.md
- en/docs/install-and-setup/setup/security/configuring-keystores/keystore-basics/creating-new-keystores.md
- en/docs/install-and-setup/setup/security/logins-and-passwords/maintaining-logins-and-passwords.md
- en/docs/install-and-setup/setup/setting-up-proxy-server-and-the-load-balancer/adding-a-custom-proxy-path.md
- en/docs/reference/connectors/smpp-connector/smpp-inbound-endpoint-example.md
- en/docs/reference/connectors/twitter-connector/twitter-connector-overview.md
- en/docs/reference/customize-product/customizations/customizing-login-pages-for-dev-portal-and-publisher.md
- en/docs/reference/customize-product/customizations/customizing-user-signup-in-developer-portal.md
- en/docs/reference/customize-product/customizations/directing-the-root-context-to-the-developer-portal.md
- en/docs/reference/customize-product/extending-api-manager/extending-workflows/cleaning-up-workflow-tasks.md
- en/docs/reference/faq.md
- en/docs/reference/guides/accessing-api-manager-by-multiple-devices-simultaneously.md
- en/docs/reference/mediators/aggregate-mediator.md
- en/docs/reference/mediators/clone-mediator.md
- en/docs/reference/mediators/iterate-mediator.md
- en/docs/reference/mediators/oauth-mediator.md
- en/docs/reference/mediators/store-mediator.md
- en/docs/reference/synapse-properties/data-services/mapping-data-types.md
- en/docs/reference/wso2-api-manager-best-practices.md
> This PR correct the localhost links and other internal links that doesnt take the user to the proper link.
> Rectifying localhost links and correcting internal links

- en/docs/deploy-and-publish/deploy-on-gateway/choreo-connect/configure-analytics.md
- en/docs/deploy-and-publish/deploy-on-gateway/choreo-connect/faq.md
- en/docs/deploy-and-publish/deploy-on-gateway/choreo-connect/git-integration.md
- en/docs/deploy-and-publish/deploy-on-gateway/choreo-connect/http-2.md
- en/docs/deploy-and-publish/deploy-on-gateway/choreo-connect/migration-guide-from-ballerina-api-microgateway.md
- en/docs/deploy-and-publish/deploy-on-gateway/choreo-connect/passing-enduser-attributes-to-the-backend-via-choreo-connect.md
- en/docs/deploy-and-publish/deploy-on-gateway/choreo-connect/production-deployment-guideline.md
> [master][Choreo Connect] Fix Typos

- en/docs/deploy-and-publish/deploy-on-gateway/choreo-connect/configure-analytics.md
- en/docs/deploy-and-publish/deploy-on-gateway/choreo-connect/faq.md
- en/docs/deploy-and-publish/deploy-on-gateway/choreo-connect/migration-guide-from-ballerina-api-microgateway.md
- en/docs/deploy-and-publish/deploy-on-gateway/choreo-connect/production-deployment-guideline.md
> [4.0.0][Choreo Connect] Fix Typos

- en/docs/deploy-and-publish/deploy-on-gateway/choreo-connect/configure-analytics.md
- en/docs/deploy-and-publish/deploy-on-gateway/choreo-connect/git-integration.md
- en/docs/deploy-and-publish/deploy-on-gateway/choreo-connect/migration-guide-from-ballerina-api-microgateway.md
- en/docs/deploy-and-publish/deploy-on-gateway/choreo-connect/production-deployment-guideline.md
> [4.1.0][Choreo Connect] Fix Typos

- en/docs/deploy-and-publish/deploy-on-gateway/choreo-connect/configure-analytics.md
- en/docs/deploy-and-publish/deploy-on-gateway/choreo-connect/http-2.md
- en/docs/deploy-and-publish/deploy-on-gateway/choreo-connect/passing-enduser-attributes-to-the-backend-via-choreo-connect.md
- en/docs/deploy-and-publish/deploy-on-gateway/choreo-connect/production-deployment-guideline.md
> [4.2.0][Choreo-Connect] Fix typos

- en/docs/get-started/integration-quick-start-guide.md
This PR is to update info on the supported JDK types on the MI Quick Start Guide page.
Issue reference: https://github.com/wso2-enterprise/wso2-mi-internal/issues/132
> [4.2.0] Update info on the supported JDK types

- en/docs/get-started/integration-quick-start-guide.md
This PR is to update info on the supported JDK types on the MI Quick Start Guide page.
Issue reference: https://github.com/wso2-enterprise/wso2-mi-internal/issues/132
> [4.1.0] Update info on the supported JDK types

- en/docs/get-started/integration-quick-start-guide.md
This PR is to update info on the supported JDK types on the MI Quick Start Guide page.
Issue reference: https://github.com/wso2-enterprise/wso2-mi-internal/issues/132
> [4.0.0] Update info on the supported JDK types

- en/docs/get-started/integration-quick-start-guide.md
This PR is to update info on the supported JDK types on the MI Quick Start Guide page.
Issue reference: https://github.com/wso2-enterprise/wso2-mi-internal/issues/132
> [Master] Update info on the supported JDK types

- en/docs/install-and-setup/setup/deployment-best-practices/security-guidelines-for-production-deployment.md
Add Callback regular expression doc link.
> Add Callback regular expression doc link

- en/docs/design/api-policies/regular-gateway-policies/mapping-the-parameters-of-your-backend-urls-with-the-api-publisher-urls.md
- en/docs/design/api-policies/regular-gateway-policies/removing-specific-request-headers-from-response.md
- en/docs/design/api-security/authorization/publisher-portal-in-read-only-mode.md
- en/docs/design/api-security/authorization/role-based-access-control-using-xacml.md
- en/docs/design/api-security/configuring-api-security-audit.md
- en/docs/design/create-api/adding-custom-properties-to-apis.md
- en/docs/design/endpoints/endpoint-security/basic-auth.md
- en/docs/design/endpoints/resiliency/endpoint-timeouts.md
- en/docs/design/lifecycle-management/api-lifecycle.md
- en/docs/get-started/apim-architecture.md
- en/docs/includes/design/create-graphql-api.md
- en/docs/includes/design/invoke-prerelease-api.md
- en/docs/install-and-setup/install-and-setup-overview.md
- en/docs/integrate/integration-overview.md
> Correcting the 'page-not-found' redirection links and any other image related issues.
>  Correcting the 'page-not-found' redirection links and any other image related issues

- en/mkdocs.yml
> [4.2.0] Remove duplicate link

- en/mkdocs.yml
> [master] Remove duplicate link

- en/docs/deploy-and-publish/deploy-on-gateway/api-gateway/passing-enduser-attributes-to-the-backend-via-api-gateway.md
- en/docs/includes/deploy/backend-jwt-intro.md
This PR adds the doc update related to task [1].
1. https://github.com/wso2/api-manager/issues/1839
> [Master] Doc update for gateway JWKS endpoint support

- en/docs/consume/generating-sdks/write-a-client-application-using-the-sdk.md
- en/docs/deploy-and-publish/deploy-on-gateway/api-gateway/api-gateways-with-dedicated-backends.md
- en/docs/deploy-and-publish/deploy-on-gateway/choreo-connect/concepts/apim-as-control-plane.md
- en/docs/deploy-and-publish/deploy-on-gateway/choreo-connect/concepts/choreo-connect-analytics.md
- en/docs/deploy-and-publish/deploy-on-gateway/choreo-connect/configure-analytics.md
- en/docs/deploy-and-publish/deploy-on-gateway/choreo-connect/deploy-api/deploy-graphql-api-in-choreo-connect.md
- en/docs/deploy-and-publish/deploy-on-gateway/choreo-connect/deploy-api/deploy-rest-to-soap-api.md
- en/docs/deploy-and-publish/deploy-on-gateway/choreo-connect/deploy-api/deploy-soap-api-passthrough.md
- en/docs/deploy-and-publish/deploy-on-gateway/choreo-connect/observability/distributed-tracing.md
- en/docs/deploy-and-publish/deploy-on-gateway/choreo-connect/passing-enduser-attributes-to-the-backend-via-choreo-connect.md
- en/docs/deploy-and-publish/deploy-on-gateway/choreo-connect/security/rejecting-revoked-tokens.md
- en/docs/design/api-security/configuring-api-security-audit.md
- en/docs/design/api-security/oauth2/grant-types/kerberos-oauth2-grant.md
- en/docs/design/api-security/oauth2/grant-types/password-grant.md
- en/docs/design/rate-limiting/adding-new-throttling-policies.md
- en/docs/design/rate-limiting/enforce-throttling-and-resource-access-policies.md
- en/docs/includes/deploy/cc-configuration-file.md
> This PR rectify the  'page-not-found' redirection issues of WSO2 APIM 4.1.0
> Correcting the 'page-not-found' redirection to take the user to a proper link

- en/docs/deploy-and-publish/deploy-on-gateway/api-gateway/passing-enduser-attributes-to-the-backend-via-api-gateway.md
- en/docs/includes/deploy/backend-jwt-intro.md
This PR adds the doc update related to task [1].
1. https://github.com/wso2-enterprise/wso2-apim-internal/issues/2124
> [4.2.0] Doc update for gateway JWKS endpoint support

- en/docs/deploy-and-publish/deploy-on-gateway/api-gateway/passing-enduser-attributes-to-the-backend-via-api-gateway.md
- en/docs/includes/deploy/backend-jwt-intro.md
This PR adds the doc update related to task [1].
1. https://github.com/wso2-enterprise/wso2-apim-internal/issues/2124
> [4.1.0] Doc update for gateway JWKS endpoint support

- en/docs/reference/connectors/csv-module/csv-module-config.md
- en/mkdocs.yml
This PR is to add the CSV Module Reference page. 
This will fix https://github.com/wso2-enterprise/wso2-mi-internal/issues/104.
> [4.1.0] Add CSV Module Reference Page

- en/docs/reference/connectors/csv-module/csv-module-config.md
- en/mkdocs.yml
This PR is to add the CSV Module Reference page. 
This will fix https://github.com/wso2-enterprise/wso2-mi-internal/issues/104.
> [Sync Master] Add CSV Module Reference Page

- en/docs/deploy-and-publish/deploy-on-gateway/choreo-connect/deploy-api/deploy-rest-to-soap-api.md
- en/docs/design/api-monetization/configuring-api-monetization-category-labels.md
- en/docs/design/lifecycle-management/customize-api-life-cycle.md
- en/docs/develop/streaming-apps/exporting-siddhi-applications.md
- en/docs/develop/streaming-apps/testing-a-siddhi-application.md
- en/docs/install-and-setup/setup/kubernetes-operators/k8s-api-operator/manage-integrations/integration-deployments.md
- en/docs/install-and-setup/setup/mi-setup/brokers/configure-with-ibm-webspheremq.md
- en/docs/install-and-setup/setup/mi-setup/brokers/configure-with-jbossmq.md
- en/docs/install-and-setup/setup/mi-setup/brokers/configure-with-multiple-brokers.md
- en/docs/install-and-setup/setup/mi-setup/brokers/configure-with-wso2-mb.md
- en/docs/install-and-setup/setup/mi-setup/databases/setting-up-oracle.md
- en/docs/integrate/develop/integration-development-kickstart.md
- en/docs/integrate/examples/inbound_endpoint_examples/inbound-endpoint-mqtt-protocol.md
- en/docs/observe/api-manager/monitoring-http-access-logs.md
- en/docs/reference/connectors/email-connector/email-connector-overview.md
- en/docs/reference/connectors/servicenow-connector/servicenow-connector-config.md
- en/docs/reference/connectors/twitter-connector/twitter-connector-reference.md
- en/docs/reference/faq.md
- en/docs/reference/mediators/iterate-mediator.md
- en/docs/reference/mi-security-reference/using_keystores.md
- en/docs/reference/synapse-properties/message-processors/msg-sampling-processor-properties.md
- en/docs/reference/wso2-admin-services.md
- en/docs/use-cases/streaming-tutorials/creating-etl-application-via-tooling.md
- en/docs/use-cases/streaming-usecase/performing-etl-tasks.md
> Remove the sentence with the obsolete link
> Remove the link as directed 

- en/docs/design/rate-limiting/advanced-topics/configuring-rate-limiting-api-gateway-cluster.md
- en/mkdocs.yml
**Purpose:**
Doc changes for the feature implementation of Improvement for BackEnd and burst related distributed throttling" [1] in apim-4.2.0.
[1] https://github.com/wso2/api-manager/issues/1791
Screenshots:
> Adding redis throttling improvement related docs

- en/docs/integrate/develop/injecting-parameters.md
This PR is to update the Injecting Parameters page.
Issue Reference: https://github.com/wso2/docs-apim/issues/7336
> [4.2.0] Update injecting-parameters.md

- en/docs/integrate/develop/injecting-parameters.md
This PR is to update the Injecting Parameters page.
Issue Reference: https://github.com/wso2/docs-apim/issues/7336
> [4.1.0] Update injecting-parameters.md

- en/docs/integrate/develop/injecting-parameters.md
This PR is to update the Injecting Parameters page.
Issue Reference: https://github.com/wso2/docs-apim/issues/7336
> [Master] Update injecting-parameters.md

- en/docs/integrate/develop/injecting-parameters.md
This PR is to update the Injecting Parameters page.
Issue Reference: https://github.com/wso2/docs-apim/issues/7336
> [4.0.0] Update injecting-parameters.md

- en/docs/reference/connectors/servicenow-connector/servicenow-connector-config.md
- en/docs/reference/connectors/smpp-connector/smpp-inbound-endpoint-example.md
- en/docs/reference/customize-product/customizations/customizing-the-developer-portal/configuring-recaptcha-for-self-signup.md
- en/docs/reference/customize-product/customizations/customizing-user-signup-in-developer-portal.md
- en/docs/reference/customize-product/customizations/log-in-to-the-dev-portal-using-social-media.md
- en/docs/reference/customize-product/extending-api-manager/extending-workflows/invoking-the-api-manager-from-the-bpel-engine.md
- en/docs/reference/mediators/property-reference/accessing-properties-with-xpath.md
- en/docs/reference/synapse-properties/data-services/mapping-data-types.md
- en/docs/reference/synapse-properties/message-processors/msg-sampling-processor-properties.md
- en/docs/reference/synapse-properties/scheduled-task-properties.md
- en/docs/reference/wso2-admin-services.md
> Correct the localhost links to show as a label to the user
> [4.1.0] Correct the localhost links to show as a label to the user

- en/docs/install-and-setup/setup/mi-setup/brokers/configure-with-azureservicebus.md
- en/docs/install-and-setup/setup/mi-setup/brokers/configure-with-hornetq.md
- en/docs/install-and-setup/setup/mi-setup/brokers/configure-with-ibm-websphere-app-server.md
- en/docs/install-and-setup/setup/mi-setup/brokers/configure-with-ibm-webspheremq.md
- en/docs/install-and-setup/setup/mi-setup/brokers/configure-with-jbossmq.md
- en/docs/install-and-setup/setup/mi-setup/brokers/configure-with-msmq.md
- en/docs/install-and-setup/setup/mi-setup/brokers/configure-with-weblogic.md
- en/docs/install-and-setup/setup/mi-setup/databases/setting-up-postgresql.md
- en/docs/install-and-setup/setup/security/configuring-keystores/keystore-basics/creating-new-keystores.md
- en/docs/install-and-setup/setup/security/configuring-keystores/keystore-basics/renewing-a-ca-signed-certificate-in-a-keystore.md
- en/docs/install-and-setup/setup/setting-up-proxy-server-and-the-load-balancer/adding-a-custom-proxy-path.md
- en/docs/reference/customize-product/customizations/directing-the-root-context-to-the-developer-portal.md
- en/docs/reference/mediators/iterate-mediator.md
>Correcting the localhost links and anyother zip download links
> Correcting the localhost links and anyother zip download links

- en/docs/integrate/examples/file-processing/accessing_windows_share_using_vfs_transport.md
This PR is to remove `[port]` from the connection URI format.
> [Master] Update accessing_windows_share_using_vfs_transport.md

- en/docs/learn/api-controller/getting-started-with-wso2-api-controller.md
Fix https://github.com/wso2/api-manager/issues/2222
> Added new APICTL release

- en/docs/reference/connectors/gmail-connector/gmail-connector-config.md
> Fix a typo in gmail connector docs

- en/docs/install-and-setup/setup/deployment-best-practices/performance-test-results-mi.md
- en/docs/install-and-setup/setup/mi-setup/deployment/mi-cicd-vm.md
- en/docs/install-and-setup/setup/mi-setup/transport_configurations/configuring-transports.md
- en/docs/install-and-setup/setup/si-setup/general-data-protection-regulations.md
- en/docs/install-and-setup/setup/si-setup/supporting-different-transports.md
- en/docs/tutorials/scenarios/scenario10-notifications-webhooks.md
- en/docs/tutorials/scenarios/scenario12-message-delivery.md
- en/docs/tutorials/scenarios/scenario3-implementing-an-api.md
- en/docs/tutorials/scenarios/scenario4-user-signup-approval-flow.md
> Add more links that is corrected for apim 4.1.0
> Add more links that is corrected for apim 4.1.0

- en/docs/design/api-security/oauth2/access-token-types/jwt-tokens.md
Add following note to https://apim.docs.wso2.com/en/latest/design/api-security/oauth2/access-token-types/jwt-tokens/#secure-apis-using-jwt-self-contained-access-tokens section
> Add note to describe jwt token behaviour

- en/docs/reference/synapse-properties/transport-parameters/vfs-transport-parameters.md
$subject Related to https://github.com/wso2/api-manager/issues/2231
> [4.0.0] Remove cluster configuration from VFS Listener

- en/docs/reference/synapse-properties/transport-parameters/vfs-transport-parameters.md
$subject Related to https://github.com/wso2/api-manager/issues/2231
> [4.1.0] Remove cluster configuration from VFS Listener

- en/docs/reference/synapse-properties/transport-parameters/vfs-transport-parameters.md
$subject Related to https://github.com/wso2/api-manager/issues/2231
> [4.2.0] Remove cluster configuration from VFS Listener

- en/docs/reference/synapse-properties/transport-parameters/vfs-transport-parameters.md
$subject Related to https://github.com/wso2/api-manager/issues/2231
> Remove cluster configuration from VFS Listener

- en/docs/design/create-api/create-rest-api/create-a-rest-api-from-an-openapi-definition.md
- en/docs/get-started/overview.md
- en/docs/reference/connectors/ceridiandayforce-connector/employment-eligibility-verification/i9order.md
> Test staging 400

- en/docs/get-started/overview.md
> Change the font to caps

- en/docs/develop/streaming-apps/streaming-integrator-studio-overview.md
- en/docs/integrate/develop/creating-artifacts/creating-an-api.md
> Remove the unused page and direct the user to the upgrade action page as requested by the team
> Remove unused page and link the upgrade links to the proper page

- en/docs/get-started/overview.md
> Test staging

- en/docs/install-and-setup/setup/deployment-best-practices/performance-test-results-mi.md
- en/docs/install-and-setup/setup/mi-setup/deployment/mi-cicd-vm.md
- en/docs/install-and-setup/setup/mi-setup/transport_configurations/configuring-transports.md
- en/docs/install-and-setup/setup/si-setup/general-data-protection-regulations.md
- en/docs/install-and-setup/setup/si-setup/supporting-different-transports.md
- en/docs/tutorials/scenarios/scenario10-notifications-webhooks.md
- en/docs/tutorials/scenarios/scenario12-message-delivery.md
- en/docs/tutorials/scenarios/scenario3-implementing-an-api.md
- en/docs/tutorials/scenarios/scenario4-user-signup-approval-flow.md
> testing the staging 4.1.0

- en/docs/get-started/overview.md
> Test Staging 4.0.0

- en/docs/get-started/overview.md
> Test Staging 4.1.0

- en/docs/reference/connectors/ldap-connector/ldap-server-configuration.md
$subject
Related to https://github.com/wso2/product-ei/issues/4598
> Introduce new parameter to LDAP Connector search

- en/docs/assets/js/theme.js
- en/mkdocs.yml
> Add changes to Themes.js file

- en/docs/assets/js/theme.js
- en/docs/develop/streaming-apps/streaming-integrator-studio-overview.md
- en/docs/integrate/develop/advanced-development/applying-security-to-a-proxy-service.md
- en/docs/integrate/develop/creating-artifacts/creating-an-api.md
- en/docs/integrate/develop/integration-development-kickstart.md
- en/docs/integrate/examples/inbound_endpoint_examples/inbound-endpoint-jms-protocol.md
- en/docs/observe/micro-integrator/classic-observability-logs/configuring-log4j2-properties.md
- en/docs/reference/connectors/amazondynamodb-connector/amazondynamodb-connector-example.md
- en/docs/reference/connectors/amazonsqs-connector/amazonsqs-connector-example.md
- en/docs/reference/connectors/amazonsqs-connector/amazonsqs-inbound-endpoint-example.md
- en/docs/streaming/getting-started/monitor-statistics.md
- en/docs/use-cases/examples/streaming-examples/execution-geo-sample.md
- en/mkdocs.yml
> Correct the 'Dev assistance issues' that was resolved by the APIM team
> [4.1.0] Correct the 'Dev assistance issues' that was resolved by the APIM team

- en/docs/reference/connectors/salesforce-connectors/sf-rest-connector-config-v2.md
- en/mkdocs.yml
$subject.
Related PRs: https://github.com/wso2-extensions/esb-connector-salesforcerest/pull/57
> Add docs for Salesforce REST Connector v2.0

- en/docs/install-and-setup/setup/setting-up-databases/overview.md
> [4.1.0] Remove enable_h2_console config

- en/docs/administer/advanced-configurations.md
- en/docs/administer/role-based-access-control.md
- en/mkdocs.yml
https://github.com/wso2/api-manager/issues/1187 …
> adding role based access control

- en/docs/deploy-and-publish/deploy-on-gateway/choreo-connect/endpoints/overriding-endpoints-for-imported-apis.md
$subject in https://apim.docs.wso2.com/en/latest/deploy-and-publish/deploy-on-gateway/choreo-connect/endpoints/overriding-endpoints-for-imported-apis/#overriding-endpoints-using-environment-variables
> [4.2.0][CC] Fix API ID Hash in Overriding Endpoints Examples

- en/docs/get-started/overview.md
> Change to bold text

- en/docs/get-started/overview.md
> Add bold text to the 4.2.0

- en/docs/install-and-setup/setup/mi-setup/transport_configurations/multi-https-transport.md
Porting https://github.com/wso2/docs-ei/pull/2793
> Link(s) to product documentation that addresses the changes of this PR. If …
> Update sslprofile docs- Add xmlns:svns namespace in the parameter section

- en/docs/reference/connectors/kafka-connector/3.0.x/kafka-connector-config.md
- en/docs/reference/connectors/kafka-connector/kafka-connector-config.md
The property is added by https://github.com/wso2-extensions/esb-connector-kafka/pull/33/files …
> Add saslMechanism parameter to Kafka docs

- en/docs/reference/connectors/microsoft-azure-storage-connector/microsoft-azure-storage-configuration.md
azure-core-1.41.0.jar is missing in connector setup docs …
> Add missing in Microsoft Azure Storage Connector docs

- en/docs/integrate/develop/hot-deployment.md
Readiness prob does not depend on the the hot deployment, therefore, removing the content
> Link(s) to product documentation …
> Remove readiness probe content related to hot deployment

- en/docs/assets/js/theme.js
- en/docs/design/create-api/create-rest-api/create-a-rest-api-from-an-openapi-definition.md
- en/docs/get-started/overview.md
- en/docs/install-and-setup/install/installing-the-product/setting-up-postgresql.md
- en/docs/install-and-setup/setup/kubernetes-operators/k8s-api-operator/manage-integrations/integration-deployments.md
- en/docs/install-and-setup/setup/mi-setup/brokers/configure-with-hornetq.md
- en/docs/install-and-setup/setup/mi-setup/brokers/configure-with-jbossmq.md
- en/docs/install-and-setup/setup/mi-setup/transport_configurations/configuring-transports.md
- en/docs/install-and-setup/setup/mi-setup/user_stores/setting_up_a_userstore.md
- en/docs/install-and-setup/setup/security/configuring-keystores/keystore-basics/renewing-a-ca-signed-certificate-in-a-keystore.md
- en/docs/install-and-setup/setup/si-setup/supporting-different-transports.md
- en/docs/reference/connectors/ceridiandayforce-connector/employment-eligibility-verification/i9order.md
- en/docs/reference/connectors/iso8583-connector/iso8583-inbound-endpoint-config.md
- en/docs/reference/connectors/microsoft-azure-storage-connector/microsoft-azure-storage-reference.md
- en/docs/reference/synapse-properties/message-processors/msg-sampling-processor-properties.md
- en/docs/reference/wso2-admin-services.md
- en/mkdocs.yml
> Fixing the Apiim 4.0.0. link changes
> [4.0.0] Change the 404 link corrections in APIM

- en/docs/install-and-setup/setup/deployment-best-practices/security-guidelines-for-production-deployment.md
> Add Secure Deployment Guidelines for SI

- en/docs/install-and-setup/setup/deployment-best-practices/security-guidelines-for-production-deployment.md
> Add Secure Deployment Guidelines for SI 4.2.0

- en/docs/install-and-setup/setup/deployment-best-practices/security-guidelines-for-production-deployment.md
> Add Secure Deployment Guidelines for SI 4.1.0

- en/docs/install-and-setup/setup/security/enabling-hostname-verification.md
Add instructions for : https://github.com/wso2/carbon-mediation/pull/1692
> [4.2.0] Add docs to enable hostname verification for websockets

- en/docs/install-and-setup/setup/security/enabling-hostname-verification.md
Add instructions for : https://github.com/wso2/carbon-mediation/pull/1692
> [3.2.0] Add docs to enable hostname verification for websockets

- en/docs/assets/js/theme.js
> Maintain URL path when switching between versions

- en/mkdocs.yml
> Fix base path mkdocs.yml

- en/docs/reference/connectors/kafka-connector/kafka-inbound-endpoint-config.md
- en/docs/reference/connectors/kafka-connector/kafka-inbound-endpoint-example.md
- en/mkdocs.yml
> Add kafka inbound endpoint reference guide

- en/docs/reference/connectors/kafka-connector/kafka-inbound-endpoint-config.md
- en/docs/reference/connectors/kafka-connector/kafka-inbound-endpoint-example.md
- en/mkdocs.yml
> Add kafka inbound endpoint reference guide 

- en/docs/mi-analytics/setting-up-mi-analytics.md
This PR is to update the note on MI Analytics.
Issue Reference: https://github.com/wso2-enterprise/wso2-apim-internal/issues/5107
> [4.2.0] Update note on MI Analytics

- en/docs/mi-analytics/using-the-analytics-dashboard.md
This PR is to add the note on MI Analytics.
Issue Reference: https://github.com/wso2-enterprise/wso2-apim-internal/issues/5107
> [4.2.0] Add note on MI Analytics

- en/docs/mi-analytics/setting-up-mi-analytics.md
This PR is to update the note on MI Analytics.
Issue Reference: https://github.com/wso2-enterprise/wso2-apim-internal/issues/5107
> [Master] Update note on MI Analytics

- en/docs/mi-analytics/using-the-analytics-dashboard.md
This PR is to add a note on MI Analytics.
Issue Reference: https://github.com/wso2-enterprise/wso2-apim-internal/issues/5107
> [Master] Add note on MI Analytics

- en/docs/install-and-setup/setup/security/enabling-hostname-verification.md
Issue : https://github.com/wso2-enterprise/wso2-apim-internal/issues/5060
Add instructions for : https://github.com/wso2-support/carbon-mediation/pull/885
> [4.1.0] Add docs to enable hostname verification for websockets

- en/docs/install-and-setup/setup/security/enabling-hostname-verification.md
Issue : https://github.com/wso2-enterprise/wso2-apim-internal/issues/5197
Add instructions for : https://github.com/wso2-support/carbon-mediation/pull/894
> [4.0.0] Add docs to enable hostname verification for websockets

- en/docs/design/api-versioning/backward-compatibility.md
- en/docs/design/api-versioning/create-a-new-api-version.md
- en/docs/design/create-api-product/create-api-product.md
- en/docs/install-and-setup/setup/api-controller/cicd-using-cli.md
- en/docs/install-and-setup/setup/api-controller/enabling-correlation-logs-with-apictl.md
- en/docs/install-and-setup/setup/api-controller/getting-started-with-wso2-api-controller.md
- en/docs/install-and-setup/setup/api-controller/managing-apis-api-products/managing-apis-and-api-products.md
- en/docs/install-and-setup/setup/api-controller/managing-apis-api-products/migrating-api-products-to-different-environments.md
- en/docs/install-and-setup/setup/api-controller/managing-applications/managing-applications.md
- Add API product versioning doc changes
- Change apictl version to 4.2.3
- Update apictl download links
> [4.2.0] Update documentation for API product versioning feature

- en/docs/install-and-setup/setup/security/enabling-hostname-verification.md
Add instructions for :
https://github.com/wso2/carbon-mediation/pull/1692
> [Master] Add docs to enable hostname verification for websockets

- en/docs/design/endpoints/endpoint-security/oauth-2.0.md
https://github.com/wso2-enterprise/wso2-apim-internal/issues/5206
> [4.2.0] Correct redis config in OAuth2

- en/docs/design/endpoints/endpoint-security/oauth-2.0.md
https://github.com/wso2-enterprise/wso2-apim-internal/issues/5206
> [4.1.0] Correct redis config in OAuth2

- en/docs/design/endpoints/endpoint-security/oauth-2.0.md
https://github.com/wso2-enterprise/wso2-apim-internal/issues/5206
> [4.0.0] Correct redis config in OAuth2

- en/docs/design/endpoints/endpoint-security/oauth-2.0.md
https://github.com/wso2-enterprise/wso2-apim-internal/issues/5206
> [Master] Correct redis config in OAuth2

- en/docs/install-and-setup/setup/distributed-deployment/configuring-wso2-identity-server-as-a-key-manager.md
- en/docs/reference/product-apis/admin-apis/admin-v4/admin-v4.yaml
- en/docs/reference/product-apis/devportal-apis/devportal-v3/devportal-v3.yaml
- en/docs/reference/product-apis/publisher-apis/publisher-v4/publisher-v4.yaml
> Add note on API token generation using third-party key managers

- en/docs/install-and-setup/setup/distributed-deployment/configuring-wso2-identity-server-as-a-key-manager.md
- en/docs/reference/product-apis/admin-apis/admin-v3/admin-v3.yaml
- en/docs/reference/product-apis/devportal-apis/devportal-v2/devportal-v2.yaml
- en/docs/reference/product-apis/publisher-apis/publisher-v3/publisher-v3.yaml
> [410] Add note on API token generation using third-party key managers

- en/docs/includes/deploy/steps-to-deploy-apim-in-a-distributed-setup-with-tm-separation.md
- en/docs/install-and-setup/setup/multi-dc-deployment/multi-dc-deployment-patterns-overview.md
This PR fixes the link issues when including the distributed setup docs in the multi-dc documentation.
> [4.2.0] Fix link issues in multi-dc docs

- en/docs/includes/deploy/steps-to-deploy-apim-in-a-distributed-setup-with-tm-separation.md
- en/docs/install-and-setup/setup/multi-dc-deployment/multi-dc-deployment-patterns-overview.md
This PR fixes the link issues when including the distributed setup docs in the multi-dc documentation.
> Fix link issues in multi-dc docs

- en/docs/install-and-setup/setup/reference/product-compatibility.md
> Update product's compatibility

- en/docs/install-and-setup/setup/reference/product-compatibility.md
> Add Rocky Linux 8.7 for support matrix

- en/docs/integrate/develop/intro-integration-development.md
> [4.2.0] Fix a typo

- en/docs/integrate/develop/intro-integration-development.md
> [4.1.0] Fix a typo

- en/docs/integrate/develop/intro-integration-development.md
> [4.0.0] Fix a typo

- en/docs/reference/connectors/email-connector/email-connector-config.md
$subject
Issue reference: https://github.com/wso2/micro-integrator/issues/3073
> [4.2.0] Update email connector doc

- en/docs/reference/connectors/email-connector/email-connector-config.md
$subject
Issue reference: https://github.com/wso2/micro-integrator/issues/3073
> [Master] Update email connector doc

- en/docs/reference/connectors/email-connector/email-connector-config.md
$subject
Issue reference: https://github.com/wso2/micro-integrator/issues/3073
> [4.1.0] Update email connector doc

- en/docs/reference/connectors/email-connector/email-connector-config.md
$subject
Issue reference: https://github.com/wso2/micro-integrator/issues/3073
> [4.0.0] Update email connector doc

- en/docs/develop/product-apis/admin-apis/admin-v1/admin-v1.yaml
- en/docs/develop/product-apis/devportal-apis/devportal-v1/devportal-v1.yaml
- en/docs/develop/product-apis/publisher-apis/publisher-v1/publisher-v1.yaml
- en/docs/install-and-setup/setup/distributed-deployment/configuring-wso2-identity-server-as-a-key-manager.md
> [3.2.0] Add note on API token generation using third-party key managers

- en/docs/install-and-setup/install/installing-the-product/running-the-api-m.md
> [4.0.0]Fix broken link for change hostname section

- en/docs/install-and-setup/install/installing-the-product/running-the-api-m.md
> [4.2.0]Fix broken link for change hostname section

- en/docs/install-and-setup/install/installing-the-product/running-the-api-m.md
> [Master]Fix broken link for change hostname section

- en/docs/install-and-setup/setup/reference/product-compatibility.md
> [3.2.0] Update DB compatibility

- en/docs/install-and-setup/setup/reference/product-compatibility.md
> [4.0.0] Update DB compatibility

- en/docs/install-and-setup/setup/reference/product-compatibility.md
> [4.1.0] Update DB compatibility

- en/docs/install-and-setup/setup/reference/product-compatibility.md
> [4.2.0] Update DB compatibility

- en/docs/install-and-setup/setup/reference/product-compatibility.md
> Update DB compatibility

- en/docs/install-and-setup/setup/mi-setup/message_builders_formatters/message-builders-and-formatters.md
- Updated the code block based on the information provided in https://github.com/wso2/docs-apim/issues/7556
- Made some formatting changes.
> [https://github.com/wso2/docs-apim/issues/7556](https://github.com/wso2/docs-apim/issues/7556)
@DinithiDiaz , please check and merge.
> fixes https://github.com/wso2/docs-apim/issues/7556

- en/docs/install-and-setup/setup/advance-configurations/configuring-caching.md
> remove token cache disable info.

- en/docs/install-and-setup/setup/advance-configurations/configuring-caching.md
> update messaging for gateway token cache.

- en/docs/api-analytics/choreo-analytics/getting-started-guide.md
> Fix doc link broken issue for Role-based Access Control Doc

- en/docs/observe/api-manager/monitoring-http-access-logs.md
- Update passthrough access log docs
- Related Issues: https://github.com/wso2/api-manager/issues/2357
> [4.0.0] Update passthrough access log docs

- en/docs/reference/connectors/amazons3-connector/amazons3-connector-config.md
> [4.2.0] Add new S3 connector sdk version related jars

- en/docs/reference/connectors/amazons3-connector/amazons3-connector-config.md
> [4.1.0] Add new S3 connector sdk version related jars

- en/docs/reference/connectors/amazons3-connector/amazons3-connector-config.md
> [4.0.0] Add new S3 connector sdk version related jars

- en/docs/reference/connectors/amazons3-connector/amazons3-connector-config.md
> Add new S3 connector sdk version related jars

- en/docs/install-and-setup/setup/mi-setup/message_builders_formatters/message-builders-and-formatters.md
- fixes https://github.com/wso2/docs-apim/issues/7556
- Updated the code block based on the information provided in https://github.com/wso2/docs-apim/issues/7556
- Made some formatting changes.
> [https://github.com/wso2/docs-apim/issues/7556](https://github.com/wso2/docs-apim/issues/7556)
@DinithiDiaz , please check and merge.
> [master] fixes https://github.com/wso2/docs-apim/issues/7556

- en/docs/install-and-setup/setup/mi-setup/message_builders_formatters/message-builders-and-formatters.md
- fixes https://github.com/wso2/docs-apim/issues/7556
- Updated the code block based on the information provided in https://github.com/wso2/docs-apim/issues/7556
- Made some formatting changes.
> [https://github.com/wso2/docs-apim/issues/7556](https://github.com/wso2/docs-apim/issues/7556)
@DinithiDiaz , please check and merge.
> [4.1.0] fixes https://github.com/wso2/docs-apim/issues/7556

- en/docs/install-and-setup/setup/mi-setup/message_builders_formatters/message-builders-and-formatters.md
fixes https://github.com/wso2/docs-apim/issues/7556
- Updated the code block based on the information provided in https://github.com/wso2/docs-apim/issues/7556
- Made some formatting changes.
> [https://github.com/wso2/docs-apim/issues/7556](https://github.com/wso2/docs-apim/issues/7556)
@DinithiDiaz , please check and merge.
> [4.0.0] fixes https://github.com/wso2/docs-apim/issues/7556

- en/docs/install-and-setup/setup/reference/product-compatibility.md
This PR is raised to update the APIM 4.1.0 product compatibility with windows server 2019 version
> Updated product compatibility on Windows Server

- en/docs/reference/connectors/smpp-connector/smpp-connector-configuration.md
Update SMPP docs with new SDK
https://github.com/wso2-extensions/esb-connector-smpp/pull/32
> Update SMPP docs with new SDK

- en/docs/design/prototype-api/create-mocked-js-api.md
> [4.1.0] Add Docs to Config Prototype API Access to Java Classes and Methods

- en/docs/learn/design-api/mock-api/create-a-mock-api-with-an-inline-script.md
> [3.2.0] Add Docs to Config Prototype API Access to Java Classes and Methods

- en/theme/material/partials/footer.html
> [master] Update copyrights

- en/theme/material/partials/footer.html
> [3.0.0] Update copyrights

- en/theme/material/partials/footer.html
> [4.2.0] Update copyrights

- en/theme/material/partials/footer.html
> [4.1.0] Update copyrights

- en/theme/material/partials/footer.html
> [4.0.0] Update copyrights

- en/theme/material/partials/footer.html
> [3.2.0] Update copyrights

- en/theme/material/partials/footer.html
> [3.1.0] Update copyrights

- en/docs/install-and-setup/setup/api-controller/getting-started-with-wso2-api-controller.md
- en/docs/install-and-setup/setup/api-controller/managing-apis-api-products/managing-apis-and-api-products.md
- en/docs/install-and-setup/setup/api-controller/managing-applications/managing-applications.md
This PR updates the APICTL version, download links and adds the assets for APICTL 4.1.2 release.
> [4.1.0] Update version and download links for APICTL 4.1.2

- en/mkdocs.yml
- en/theme/material/base.html
- en/theme/material/partials/footer.html
- en/theme/material/partials/header.html
This PR fixes build issues identified in staging branch.
> Fix build issues & theme issues

- en/docs/install-and-setup/setup/api-controller/cicd-using-cli.md
- en/docs/install-and-setup/setup/api-controller/enabling-correlation-logs-with-apictl.md
- en/docs/install-and-setup/setup/api-controller/getting-started-with-wso2-api-controller.md
- en/docs/install-and-setup/setup/api-controller/managing-apis-api-products/managing-apis-and-api-products.md
- en/docs/install-and-setup/setup/api-controller/managing-apis-api-products/migrating-api-products-to-different-environments.md
- en/docs/install-and-setup/setup/api-controller/managing-applications/managing-applications.md
This PR updates the APICTL version, download links and adds the assets for APICTL 4.2.4 release.
> [4.2.0] Update version and download links for APICTL 4.2.4

- en/docs/design/prototype-api/create-mocked-js-api.md
> [Master] Add Docs to Config Prototype API Access to Java Classes and Methods

- en/docs/install-and-setup/setup/reference/product-compatibility.md
> Fix APIM compatibility matrix

- en/docs/reference/customize-product/customizations/customizing-the-developer-portal/overriding-developer-portal-theme.md
> Fix paths of userTheme.json and defaultTheme.js files
> Update Overriding Developer Portal Theme docs

- en/docs/observe/api-manager/traces/monitoring-with-opentelemetry.md
> $Subject. Related to https://github.com/wso2/api-manager/issues/2123
https://github.com/wso2/carbon-apimgt/pull/12175
> Add note about `OTEL_RESOURCE_ATTRIBUTES`

- en/docs/observe/api-manager/monitoring-http-access-logs.md
- Update passthrough access log docs
- Related Issues: https://github.com/wso2/api-manager/issues/2357
> [4.2.0] Update passthrough access log docs

- en/docs/observe/api-manager/monitoring-http-access-logs.md
- Update passthrough access log docs
- Related Issues: https://github.com/wso2/api-manager/issues/2357
> Update passthrough access log docs

- en/docs/design/api-security/api-authentication/secure-apis-using-api-keys.md
- $subject
https://github.com/wso2/api-manager/issues/2449
> [Master] Add Missing Custom Keystore Docs

- en/docs/install-and-setup/setup/advance-configurations/configuring-the-crypto-provider.md
- en/mkdocs.yml
This PR adds the "configure crypto provider" documentation.
Related issue: https://github.com/wso2/api-manager/issues/1616
> Add configuring crypto provider documentation

- en/docs/install-and-setup/setup/advance-configurations/configuring-the-crypto-provider.md
- en/mkdocs.yml
This PR adds the "configure crypto provider" documentation.
Related issue: https://github.com/wso2/api-manager/issues/1616
> [4.2.0] Add configuring crypto provider documentation

- en/docs/install-and-setup/setup/setting-up-databases/changing-default-databases/changing-to-mssql.md
> Add: Intructions to avoid concurrency issues in mssql

- en/docs/reference/config-catalog.md
> Fix passthru_http configs

- en/docs/assets/css/theme.css
- en/theme/material/partials/header.html
> [4.3.0] Add WIP banner

- en/docs/install-and-setup/setup/mi-setup/brokers/configure-with-ibm-websphere-app-server.md
> [4.3.0] Fix invalid link

- en/docs/install-and-setup/setup/mi-setup/brokers/configure-with-ibm-websphere-app-server.md
> [4.2.0] Fix invalid link

- en/docs/install-and-setup/setup/mi-setup/brokers/configure-with-ibm-websphere-app-server.md
> [4.0.0] Fix invalid link

- en/mkdocs.yml
> [4.0.0] Update base path

- en/mkdocs.yml
> [4.3.0] Update base path

- en/docs/reference/connectors/mongodb-connector/mongodb-connector-example.md
> [4.2.0] Fix download link

- en/docs/reference/connectors/mongodb-connector/mongodb-connector-example.md
> [4.1.0] Fix download link

- en/docs/reference/connectors/mongodb-connector/mongodb-connector-example.md
> [4.0.0] Fix download link

- en/docs/reference/connectors/mongodb-connector/mongodb-connector-example.md
> [master] Fix download link

- en/docs/reference/connectors/mongodb-connector/mongodb-connector-example.md
> [4.3.0] Fix download link

- en/docs/reference/synapse-properties/transport-parameters/vfs-transport-parameters.md
> [4.2.0] Update VFS documentation with new parameters

- en/docs/reference/connectors/kafka-connector/kafka-connector-overview.md
- en/docs/reference/connectors/kafka-connector/setting-up-kafka.md
- en/mkdocs.yml
$subject
Related PR https://github.com/wso2-extensions/esb-connector-kafka/pull/81
> [4.1.0] Update kafka connector documentation with 3.2.0 details

- en/docs/reference/connectors/kafka-connector/kafka-connector-overview.md
- en/docs/reference/connectors/kafka-connector/setting-up-kafka.md
- en/mkdocs.yml
$subject
Related PR https://github.com/wso2-extensions/esb-connector-kafka/pull/81
> [4.2.0] Update kafka connector documentation with 3.2.0 details

- en/docs/reference/connectors/kafka-connector/kafka-connector-overview.md
- en/docs/reference/connectors/kafka-connector/setting-up-kafka.md
- en/mkdocs.yml
$subject
Related PR https://github.com/wso2-extensions/esb-connector-kafka/pull/81
> Update kafka connector documentation with 3.2.0 details

- en/docs/reference/connectors/kafka-connector/kafka-connector-overview.md
- en/docs/reference/connectors/kafka-connector/setting-up-kafka.md
- en/mkdocs.yml
$subject
Related PR https://github.com/wso2-extensions/esb-connector-kafka/pull/81
> [4.3.0] Update kafka connector documentation with 3.2.0 details

- en/docs/administer/managing-users-and-roles/managing-user-stores/configuring-the-system-administrator.md
- en/docs/administer/managing-users-and-roles/managing-user-stores/working-with-properties-of-user-stores.md
- en/docs/develop/streaming-apps/working-with-the-design-view.md
- en/docs/install-and-setup/install/admin-product-startup-options.md
- en/docs/install-and-setup/setup/si-setup/user-management-via-the-idp-client-interface.md
- en/docs/install-and-setup/setup/si-setup/user-management.md
- en/docs/reference/customize-product/extending-api-manager/extending-workflows/configuring-workflows-in-a-cluster.md
- en/docs/reference/mediators/script-mediator.md
This PR adds admonitions to the tables in md files.
> Add admonitions to the tables

- en/docs/develop/streaming-apps/working-with-the-design-view.md
- en/docs/install-and-setup/install/admin-product-startup-options.md
- en/docs/install-and-setup/setup/setting-up-databases/working-with-the-resgistry/using-remote-registry/admin-config-and-governance-partitions-in-separate-nodes.md
- en/mkdocs.yml
> Fix admonition issues

- en/mkdocs.yml
This PR changes the base path.
> Change base path

- en/mkdocs.yml
> Revert "Change base path"

- en/docs/design/api-security/api-authentication/secure-apis-using-api-keys.md
- $subject
https://github.com/wso2/api-manager/issues/2449
> [4.2.0] Add Missing Custom Keystore Docs

- en/docs/design/api-security/api-authentication/secure-apis-using-api-keys.md
- $subject
https://github.com/wso2/api-manager/issues/2449
> [4.0.0] Add Missing Custom Keystore Docs

- en/docs/design/api-security/api-authentication/secure-apis-using-api-keys.md
- $subject
https://github.com/wso2/api-manager/issues/2449
> [4.1.0] Add Missing Custom Keystore Docs

- en/docs/administer/key-managers/configure-azure-ad-key-manager.md
- en/docs/administer/key-managers/overview.md
- en/mkdocs.yml
> This PR add doc related to configure azure ad as key manager.
> [4.3.0] Add configure azure ad as key manager doc

- en/docs/reference/connectors/amazons3-connector/amazons3-connector-reference.md
> [4.0.0] Update s3 docs with getContentAsBase64 parameter

- en/docs/index.md
This PR is to replace the MI references on the homepage.
> [4.3.0] Update MI references on homepage 

- en/docs/reference/connectors/amazons3-connector/amazons3-connector-reference.md
> [4.2.0] Update s3 docs with getContentAsBase64 parameter

- en/docs/reference/connectors/amazons3-connector/amazons3-connector-reference.md
> [4.3.0] Update s3 docs with getContentAsBase64 parameter

- en/docs/reference/connectors/amazons3-connector/amazons3-connector-reference.md
> [4.1.0] Update s3 docs with getContentAsBase64 parameter

- en/docs/reference/connectors/amazons3-connector/amazons3-connector-reference.md
> [master] Update s3 docs with getContentAsBase64 parameter

- en/docs/reference/connectors/amazons3-connector/amazons3-connector-reference.md
> Revert "[4.3.0] Update s3 docs with getContentAsBase64 parameter"

- en/docs/get-started/about-this-release.md
- en/docs/get-started/api-manager-quick-start-guide.md
- en/docs/get-started/apim-architecture.md
- en/docs/get-started/overview.md
- en/mkdocs.yml
This PR updates the main overview documentation pages for the APIM 4.3.0 alpha release.
> Update documentation for the alpha release

- en/docs/design/api-security/oauth2/oauth2-scopes/fine-grained-access-control-with-oauth-scopes.md
> add restrict unassigned scope info to the doc.

- en/docs/install-and-setup/setup/advance-configurations/configure-certificate-revocation.md
This PR contains the doc changes related to the changes introduced with the following PR,
https://github.com/wso2/wso2-synapse/pull/2152
> Cert revocation improvement doc for 4.3.0 docs

- en/docs/reference/mediators/data-mapper-mediator.md
This PR is to update the directory path.
> [4.2.0] Update data-mapper-mediator.md

- en/docs/install-and-setup/setup/reference/product-compatibility.md
> Update DB Compatibility Matrix

- en/docs/assets/css/theme.css
- en/mkdocs.yml
- en/theme/material/partials/footer.html
- en/theme/material/partials/header.html
This PR fixes https://github.com/wso2/docs-apim/issues/7773
> Fix UI version issues

- en/docs/reference/connectors/amazons3-connector/amazons3-connector-reference.md
Related issue: wso2/micro-integrator#3270 …
> Update AmazonS3 documentation

- en/docs/reference/connectors/kafka-connector/kafka-inbound-endpoint-config.md
Related Issue: https://github.com/wso2/micro-integrator/issues/3279 …
> Update Kafka Inbound Connector Doc

- en/docs/install-and-setup/setup/security/securing-api-m-web-portals.md
master pr for https://github.com/wso2/api-manager/issues/2496
> Add doc for portal JWT

- en/docs/administer/role-based-access-control.md
- en/docs/get-started/about-this-release.md
This PR updates the "About this release" page and fixes https://github.com/wso2/api-manager/issues/2620
> Fix documentation issues for APIM 4.3.0 release

- en/docs/administer/managing-users-and-roles/managing-user-roles.md
$subject
Related issue: https://github.com/wso2/api-manager/issues/2653
> [4.3.0] Add missing scope mappings

- en/docs/reference/product-apis/admin-apis/admin-v4/admin-v4.yaml
- en/docs/reference/product-apis/devops-apis/devops-v0/devops-v0.yaml
- en/docs/reference/product-apis/devportal-apis/devportal-v3/devportal-v3.yaml
- en/docs/reference/product-apis/gateway-apis/gateway-v2/gateway-v2.yaml
- en/docs/reference/product-apis/overview.md
- en/docs/reference/product-apis/publisher-apis/publisher-v4/publisher-v4.yaml
This PR updates the REST API docs for 4.3.0 release and adds new postman collections for Publisher, Devportal, and Admin REST APIs.
Related issues: https://github.com/wso2/api-manager/issues/2468, https://github.com/wso2/docs-apim/issues/6781
> [4.3.0] Update REST API definitions and postman collections

- en/docs/install-and-setup/setup/advance-configurations/configuring-the-crypto-provider.md
This PR updates the windows commands to run the FIPS scripts as the --run is taken as an argument.
> Update the windows commands for FIPS scripts

- en/docs/install-and-setup/setup/advance-configurations/configuring-the-crypto-provider.md
This PR updates the windows commands to run the FIPS scripts as the --run is taken as an argument.
> [4.2.0] Update the windows commands for FIPS scripts

- en/docs/install-and-setup/setup/advance-configurations/configuring-the-crypto-provider.md
This PR updates the windows commands to run the FIPS scripts as the --run is taken as an argument.
> [4.3.0] Update the windows commands for FIPS scripts

- en/docs/troubleshooting/utilizing-runtime-diagnostic-tool.md
- en/mkdocs.yml
$subject
Related to https://github.com/wso2/micro-integrator/issues/2985
> Include Runtime diagnostic tool guide

- en/docs/reference/product-apis/devops-apis/devops-v0/devops-v0.yaml
> [4.3.0] Update devops REST API docs

- en/docs/get-started/about-this-release.md
This PR updates the About this release page for APIM 4.3.0 RC release.
> Update about this release page

- en/docs/install-and-setup/setup/security/logins-and-passwords/working-with-encrypted-passwords.md
$subject
Related Issue: https://github.com/wso2/docs-apim/issues/7743
> [4.3.0] Fix APIM_HOME path not visible issue

- en/docs/install-and-setup/setup/security/logins-and-passwords/working-with-encrypted-passwords.md
$subject
Related Issue: https://github.com/wso2/docs-apim/issues/7743
> [master] Fix APIM_HOME path not visible issue

- en/docs/api-analytics/choreo-analytics/choreo-based-analytics-via-proxy.md
- en/mkdocs.yml
> $subject
> Refer: https://github.com/wso2-enterprise/choreo/issues/16080#issuecomment-1315193821
> [4.3.0] Add Choreo analytics with proxy docs

- en/docs/api-analytics/choreo-analytics/choreo-based-analytics-via-proxy.md
- en/mkdocs.yml
> $subject
> Refer: https://github.com/wso2-enterprise/choreo/issues/16080#issuecomment-1315193821
> [master] Add Choreo analytics with proxy docs

- en/docs/reference/customize-product/customizations/adding-internationalization.md
- en/docs/reference/customize-product/customizations/customizing-the-developer-portal/enable-or-disable-banner.md
- en/docs/reference/customize-product/customizations/customizing-the-developer-portal/enable-or-disable-footer.md
- en/docs/reference/customize-product/customizations/customizing-the-developer-portal/enable-or-disable-rating.md
- en/docs/reference/customize-product/customizations/customizing-the-developer-portal/enable-or-disable-tag-cloud.md
> $subject
> Related Issue: https://github.com/wso2/docs-apim/issues/7750
> [4.3.0] Fix path for user themes

- en/docs/reference/customize-product/customizations/adding-internationalization.md
- en/docs/reference/customize-product/customizations/customizing-the-developer-portal/enable-or-disable-banner.md
- en/docs/reference/customize-product/customizations/customizing-the-developer-portal/enable-or-disable-footer.md
- en/docs/reference/customize-product/customizations/customizing-the-developer-portal/enable-or-disable-rating.md
- en/docs/reference/customize-product/customizations/customizing-the-developer-portal/enable-or-disable-tag-cloud.md
> $subject
> Related Issue: https://github.com/wso2/docs-apim/issues/7750
> [master] Fix path for user themes

- en/docs/install-and-setup/setup/security/general-data-protection-regulation-gdpr-for-wso2-api-manager.md
> $subject
Related Issue: https://github.com/wso2/docs-apim/issues/7765
> [4.3.0] Forget-Me tool is not pre-packed with APIM

- en/docs/install-and-setup/setup/security/general-data-protection-regulation-gdpr-for-wso2-api-manager.md
> $subject
Related Issue: https://github.com/wso2/docs-apim/issues/7765
> [master] Forget-Me tool is not pre-packed with APIM

- en/docs/consume/discover-apis/marketplace-assistant.md
- en/docs/consume/invoke-apis/invoke-apis-using-tools/test-apis-with-apichat.md
Update endpoint for AI services
> Replace dev URL with prod URL for AI features

- en/docs/design/create-api/create-rest-api/expose-a-soap-service-as-a-rest-api.md
- en/docs/design/create-api/create-rest-api/generate-rest-api-from-soap-backend.md
- Fix https://github.com/wso2/docs-apim/issues/7800
> [4.3.0] Add missing step to import WSDL

- en/docs/install-and-setup/setup/distributed-deployment/configuring-wso2-identity-server-as-a-key-manager.md
This PR adds the config to disable group and role separation in IS for the IS as KM setup.
Fixes https://github.com/wso2/docs-apim/issues/7792
> [4.1.0] Add config to disable group and role separation in IS

- en/docs/install-and-setup/setup/distributed-deployment/configuring-wso2-identity-server-as-a-key-manager.md
This PR adds the config to disable group and role separation in IS for the IS as KM setup.
Fixes https://github.com/wso2/docs-apim/issues/7792
> [4.2.0] Add config to disable group and role separation in IS

- en/docs/api-analytics/on-prem/elk-installation-guide.md
This PR will add descriptive details about analytics log events
Fixes : https://github.com/wso2/docs-apim/issues/7885
https://apim.docs.wso2.com/en/latest/api-analytics/on-prem/elk-installation-guide/
> Adding details about ELK analytics log events.

- en/docs/administer/managing-users-and-roles/managing-user-stores/configuring-secondary-user-stores.md
Fixes https://github.com/wso2/docs-apim/issues/7798
> Update link in properties of user stores

- en/docs/reference/config-catalog.md
- en/tools/config-catalog-generator/data/apim.event_hub.publish.url_group.toml
- en/tools/config-catalog-generator/data/apim.event_hub.toml
- en/tools/config-catalog-generator/data/configs.json
This PR adds the event hub configurations to the config catalog.
Fixes https://github.com/wso2/docs-apim/issues/7517
> [4.3.0] Add event hub configurations to the config catalog

- en/docs/reference/config-catalog.md
- en/tools/config-catalog-generator/data/apim.event_hub.publish.url_group.toml
- en/tools/config-catalog-generator/data/apim.event_hub.toml
- en/tools/config-catalog-generator/data/configs.json
This PR adds the event hub configurations to the config catalog.
Fixes https://github.com/wso2/docs-apim/issues/7517
> Add event hub configurations to the config catalog

- en/docs/observe/api-manager/monitoring-api-logs.md
Fixes https://github.com/wso2/docs-apim/issues/7848
> [4.3.0] Update api logs docs to support resource level api logging

- en/docs/observe/api-manager/monitoring-api-logs.md
Fixes https://github.com/wso2/docs-apim/issues/7848
> update api logs docs to support resource level api logging

- en/docs/administer/key-managers/configure-wso2is-connector.md
- en/docs/administer/key-managers/configure-wso2is7-connector.md
- en/docs/administer/key-managers/overview.md
- en/mkdocs.yml
> Add docs for 'Configure WSO2 IS 7 as a Key Manager'

- en/docs/reference/config-catalog.md
- en/tools/config-catalog-generator/data/apimgt.mutual_ssl.toml
- en/tools/config-catalog-generator/data/configs.json
- en/tools/config-catalog-generator/data/security_audit.toml
- Fix https://github.com/wso2/docs-apim/issues/7874
> [4.3.0] Add MTLS and security audit configurations to config catalog

- en/docs/reference/config-catalog.md
- en/tools/config-catalog-generator/data/apimgt.mutual_ssl.toml
- en/tools/config-catalog-generator/data/configs.json
- en/tools/config-catalog-generator/data/security_audit.toml
- Fix https://github.com/wso2/docs-apim/issues/7874
> Add MTLS and security audit configurations to config catalog

- en/docs/get-started/about-this-release.md
- en/docs/get-started/apim-architecture.md
- en/docs/get-started/overview.md
- en/docs/index.md
- en/docs/install-and-setup/upgrading-wso2-api-manager/upgrading-api-manager.md
- en/mkdocs.yml
This PR updates the getting started content including the home page and upgrading API Manager pages for APIM 4.3.0 release.
> [4.3.0] Update documentation for APIM 4.3.0 release

- en/docs/get-started/about-this-release.md
- en/docs/get-started/apim-architecture.md
- en/docs/get-started/overview.md
- en/docs/index.md
- en/docs/install-and-setup/upgrading-wso2-api-manager/upgrading-api-manager.md
- en/mkdocs.yml
This PR updates the getting started content including the home page and upgrading API Manager pages for APIM 4.3.0 release.
> Update documentation for APIM 4.3.0 release

- en/docs/administer/key-managers/configure-wso2is-connector.md
- en/docs/administer/key-managers/configure-wso2is7-connector.md
> Fix broken links in WSO2 IS & IS7 Connector docs

- en/docs/assets/versions.json
This PR updates versions for latest release APIM 4.3.0
> Update versions for latest release APIM 4.3.0

- en/docs/install-and-setup/setup/mi-setup/message_builders_formatters/message-builders-and-formatters.md
This PR is to update the default Content-Type parameter for the requests.
Issue Reference: https://github.com/wso2-enterprise/wso2-mi-internal/issues/666
> [4.2.0] Update the default Content-Type parameter for the requests

- en/docs/install-and-setup/setup/mi-setup/message_builders_formatters/message-builders-and-formatters.md
This PR is to update the default Content-Type parameter for the requests.
Issue Reference: https://github.com/wso2-enterprise/wso2-mi-internal/issues/666
> [4.1.0] Update the default Content-Type parameter for the requests

- en/docs/install-and-setup/setup/mi-setup/message_builders_formatters/message-builders-and-formatters.md
This PR is to update the default Content-Type parameter for the requests.
Issue Reference: https://github.com/wso2-enterprise/wso2-mi-internal/issues/666
> [4.0.0] Update the default Content-Type parameter for the requests

- en/docs/streaming/migrating-from-stream-processor.md
This PR fixes the document link to SP(Stream Processor) in APIM docs.
Fixes https://github.com/wso2/docs-apim/issues/7917
> [4.3.0] Fix SP documentation link

- en/docs/streaming/migrating-from-stream-processor.md
This PR fixes the document link to SP(Stream Processor) in APIM docs.
Fixes https://github.com/wso2/docs-apim/issues/7917
> Fix SP documentation link

- en/docs/install-and-setup/setup/api-controller/getting-started-with-wso2-api-controller.md
- Fix https://github.com/wso2/docs-apim/issues/7838
> [4.3.0] Update APICTL download links

- en/docs/install-and-setup/setup/api-controller/getting-started-with-wso2-api-controller.md
- Fix https://github.com/wso2/docs-apim/issues/7838
> Update APICTL download links

- en/docs/administer/key-managers/configure-global-key-manager.md
- Fix https://github.com/wso2/docs-apim/issues/7820
> [4.3.0] Update global key manager docs

- en/docs/administer/key-managers/configure-wso2is-connector.md
- en/docs/design/api-security/oauth2/grant-types/refresh-token-grant.md
- en/docs/design/api-security/oauth2/token-revocation.md
- en/docs/reference/config-catalog.md
- en/tools/config-catalog-generator/data/apim.oauth_config.toml
- en/tools/config-catalog-generator/data/apim.token.revocation.toml
- en/tools/config-catalog-generator/data/configs.json
> [4.0.0] Update token revocation docs to change notifier and port

- en/docs/administer/key-managers/configure-wso2is-connector.md
- en/docs/design/api-security/oauth2/grant-types/refresh-token-grant.md
- en/docs/design/api-security/oauth2/token-revocation.md
- en/docs/reference/config-catalog.md
- en/tools/config-catalog-generator/data/apim.oauth_config.toml
- en/tools/config-catalog-generator/data/apim.token.revocation.toml
- en/tools/config-catalog-generator/data/configs.json
> [4.1.0] Update token revocation docs to change notifier and port

- en/docs/administer/key-managers/configure-wso2is-connector.md
- en/docs/design/api-security/oauth2/grant-types/refresh-token-grant.md
- en/docs/design/api-security/oauth2/token-revocation.md
- en/docs/reference/config-catalog.md
- en/tools/config-catalog-generator/data/apim.oauth_config.toml
- en/tools/config-catalog-generator/data/apim.token.revocation.toml
- en/tools/config-catalog-generator/data/configs.json
> [4.2.0] Update token revocation docs to change notifier and port

- en/docs/administer/key-managers/configure-wso2is-connector.md
- en/docs/design/api-security/oauth2/grant-types/refresh-token-grant.md
- en/docs/design/api-security/oauth2/token-revocation.md
- en/docs/reference/config-catalog.md
- en/tools/config-catalog-generator/data/apim.oauth_config.toml
- en/tools/config-catalog-generator/data/apim.token.revocation.toml
- en/tools/config-catalog-generator/data/configs.json
> [4.3.0] Update token revocation docs to change notifier and port

- en/docs/administer/key-managers/configure-global-key-manager.md
- Fix https://github.com/wso2/docs-apim/issues/7820
> Update global key manager docs

- en/docs/reference/product-apis/admin-apis/admin-v4/admin-v4.md
- en/docs/reference/product-apis/devops-apis/devops-v0/devops-v0.md
- en/docs/reference/product-apis/devportal-apis/devportal-v3/devportal-v3.md
- en/docs/reference/product-apis/gateway-apis/gateway-v2/gateway-v2.md
- en/docs/reference/product-apis/publisher-apis/publisher-v4/publisher-v4.md
- en/docs/reference/product-apis/service-catalog-apis/service-catalog-v1/service-catalog-v1.md
This updates the API doc rendering script.
Related issue: https://github.com/wso2/api-manager/issues/2833
> [4.3.0] Update rendering of API docs

- en/docs/reference/product-apis/admin-apis/admin-v4/admin-v4.md
- en/docs/reference/product-apis/devops-apis/devops-v0/devops-v0.md
- en/docs/reference/product-apis/devportal-apis/devportal-v3/devportal-v3.md
- en/docs/reference/product-apis/gateway-apis/gateway-v2/gateway-v2.md
- en/docs/reference/product-apis/publisher-apis/publisher-v4/publisher-v4.md
- en/docs/reference/product-apis/service-catalog-apis/service-catalog-v1/service-catalog-v1.md
Update redocly to the latest version.
Related issue: https://github.com/wso2/api-manager/issues/2833
> [4.3.0] Update redocly version for API doc generation

- en/docs/reference/product-apis/admin-apis/admin-v4/admin-v4.md
- en/docs/reference/product-apis/devops-apis/devops-v0/devops-v0.md
- en/docs/reference/product-apis/devportal-apis/devportal-v3/devportal-v3.md
- en/docs/reference/product-apis/gateway-apis/gateway-v2/gateway-v2.md
- en/docs/reference/product-apis/publisher-apis/publisher-v4/publisher-v4.md
- en/docs/reference/product-apis/service-catalog-apis/service-catalog-v1/service-catalog-v1.md
> Revert "[4.3.0] Update redocly version for API doc generation"

- en/docs/reference/config-catalog.md
- en/tools/config-catalog-generator/data/apim.ai.toml
- en/tools/config-catalog-generator/data/apim.analytics.toml
- en/tools/config-catalog-generator/data/apim.key_manager.toml
- en/tools/config-catalog-generator/data/configs.json
This PR adds the following `deployment.toml` config to config catalogue:
```toml
[apim.ai]
enable = true
token = ""
endpoint = ""
```
> [Master] Add AI config to catalogue

- en/docs/reference/config-catalog.md
- en/tools/config-catalog-generator/data/apim.ai.toml
- en/tools/config-catalog-generator/data/apim.analytics.toml
- en/tools/config-catalog-generator/data/apim.key_manager.toml
- en/tools/config-catalog-generator/data/configs.json
This PR adds the following `deployment.toml` config to config catalogue:
```toml
[apim.ai]
enable = true
token = ""
endpoint = ""
```
> [4.3.0] Add AI config to catalogue

- en/docs/reference/product-apis/admin-apis/admin-v4/admin-v4.md
- en/docs/reference/product-apis/devops-apis/devops-v0/devops-v0.md
- en/docs/reference/product-apis/devportal-apis/devportal-v3/devportal-v3.md
- en/docs/reference/product-apis/gateway-apis/gateway-v2/gateway-v2.md
- en/docs/reference/product-apis/publisher-apis/publisher-v4/publisher-v4.md
- en/docs/reference/product-apis/service-catalog-apis/service-catalog-v1/service-catalog-v1.md
- en/theme/material/base.html
This PR updates the redocly yaml file path to relative path.
Related issue: https://github.com/wso2/api-manager/issues/2833
> [4.3.0] Update redocly yaml file path to relative path

- en/docs/reference/product-apis/admin-apis/admin-v4/admin-v4.md
- en/docs/reference/product-apis/devops-apis/devops-v0/devops-v0.md
- en/docs/reference/product-apis/devportal-apis/devportal-v3/devportal-v3.md
- en/docs/reference/product-apis/gateway-apis/gateway-v2/gateway-v2.md
- en/docs/reference/product-apis/publisher-apis/publisher-v4/publisher-v4.md
- en/docs/reference/product-apis/service-catalog-apis/service-catalog-v1/service-catalog-v1.md
This PR updates the redocly yaml file path to relative path.
Fixes https://github.com/wso2/api-manager/issues/2833
> Update redocly yaml file path to relative path

- en/mkdocs.yml
- Update `base_path` and `site_url` in `mkdocs.yml` by changing the URL from https://apim.docs.wso2.com/en/**latest** to https://apim.docs.wso2.com/en/**4.2.0**
> Update base_path and site_url in mkdocs.yml

- en/docs/administer/managing-users-and-roles/managing-user-stores/configuring-secondary-user-stores.md
Fixes https://github.com/wso2/docs-apim/issues/7798
> [4.3.0] Update link in properties of user stores

- en/docs/learn/api-security/oauth2/multiple-active-access-tokens.md
- en/mkdocs.yml
Adding docs to cover the new features to support multiple active access tokens
[1] https://github.com/wso2/api-manager/issues/1819
[2] https://github.com/wso2-enterprise/wso2-apim-internal/issues/5083
> [3.2.0] Add multiple active access tokens docs

- en/docs/install-and-setup/setup/distributed-deployment/configuring-apim-as-a-gateway.md
> Changing apk qsg url

- en/docs/get-started/about-this-release.md
Adding APK doc link to about release section
> Adding APK doc link to about release section

- en/docs/reference/synapse-properties/transport-parameters/vfs-transport-parameters.md
$subject
https://github.com/wso2/docs-mi/pull/182
> [4.2.0] Update vfs-transport-parameters.md

- en/docs/consume/discover-apis/marketplace-assistant.md
- en/docs/consume/invoke-apis/invoke-apis-using-tools/test-apis-with-apichat.md
- Resolves https://github.com/wso2/api-manager/issues/2835
This PR updates the endpoint of `apim.ai` config.
> Update endpoint of apim.ai config

- en/docs/get-started/about-this-release.md
This PR adds the feature doc links to about this release page content.
> Add feature doc links to about this release page content

- en/docs/install-and-setup/setup/api-controller/getting-started-with-wso2-api-controller.md
$subject
Fix https://github.com/wso2/api-manager/issues/2307
> Added a tip to save Client Secret value when token hashing is enabled

- en/docs/consume/discover-apis/marketplace-assistant.md
- en/docs/consume/invoke-apis/invoke-apis-using-tools/test-apis-with-apichat.md
- Resolves https://github.com/wso2/api-manager/issues/2835
This PR updates the endpoint of `apim.ai` config.
> [4.3.0] Update endpoint of apim.ai config

- en/docs/learn/api-security/oauth2/token-persistence.md
$subject
Related to https://github.com/wso2-enterprise/wso2-apim-internal/issues/6183
Related to https://github.com/wso2-enterprise/wso2-apim-internal/issues/6192
> Update token persistent doc to reflect flow and config correctly

- en/docs/install-and-setup/setup/mi-setup/deployment/deploying-micro-integrator-with-helm.md
$subject
**Related PR**
https://github.com/wso2/docs-apim/pull/7979
> [4.1.0] Update deploying-micro-integrator-with-helm.md

- en/docs/api-analytics/on-prem/elk-installation-guide.md
This PR will add descriptive details about analytics log events
Fixes : https://github.com/wso2/docs-apim/issues/7885
https://apim.docs.wso2.com/en/latest/api-analytics/on-prem/elk-installation-guide/
> [4.2.0] Adding details about ELK analytics log events

- en/docs/api-analytics/on-prem/elk-installation-guide.md
This PR will add descriptive details about analytics log events
Fixes : https://github.com/wso2/docs-apim/issues/7885
https://apim.docs.wso2.com/en/latest/api-analytics/on-prem/elk-installation-guide/
> [4.3.0] Adding details about ELK analytics log events

- en/docs/reference/connectors/ldap-connector/ldap-server-configuration.md
$subject
Issue reference: https://github.com/wso2-enterprise/wso2-mi-internal/issues/737
> [4.2.0] Update providerUrl description

- en/docs/install-and-setup/setup/api-controller/cicd-using-cli.md
- en/docs/install-and-setup/setup/api-controller/enabling-correlation-logs-with-apictl.md
- en/docs/install-and-setup/setup/api-controller/getting-started-with-wso2-api-controller.md
- en/docs/install-and-setup/setup/api-controller/managing-apis-api-products/managing-apis-and-api-products.md
- en/docs/install-and-setup/setup/api-controller/managing-apis-api-products/migrating-api-products-to-different-environments.md
- en/docs/install-and-setup/setup/api-controller/managing-apis-api-products/migrating-apis-to-different-environments.md
- en/docs/install-and-setup/setup/api-controller/managing-applications/managing-applications.md
- en/docs/install-and-setup/setup/api-controller/managing-applications/migrating-applications-to-different-environments.md
- en/docs/install-and-setup/setup/api-controller/managing-common-api-policies/migrating-common-api-policies-to-different-environments.md
Doc changes related to https://github.com/wso2/api-manager/issues/2754 and add the changes for the APICTL 4.2.5 release.
> Add changes to support PAT in APICTL

- en/docs/install-and-setup/setup/api-controller/getting-started-with-wso2-api-controller.md
- en/docs/install-and-setup/setup/api-controller/managing-apis-api-products/migrating-api-products-to-different-environments.md
- en/docs/install-and-setup/setup/api-controller/managing-apis-api-products/migrating-apis-to-different-environments.md
- en/docs/install-and-setup/setup/api-controller/managing-applications/migrating-applications-to-different-environments.md
- en/docs/install-and-setup/setup/api-controller/managing-common-api-policies/migrating-common-api-policies-to-different-environments.md
Add changes related to https://github.com/wso2/api-manager/issues/2754
> Add changes related to PAT support in APICTL

- en/docs/troubleshooting/error-handling-mi.md
This PR is to add the error code 601000 to the docs.
Issue reference: https://github.com/wso2-enterprise/wso2-mi-internal/issues/777
> [4.2.0] Add error code 601000

- en/docs/troubleshooting/error-handling-mi.md
This PR is to add the error code 601000 to the docs.
Issue reference: https://github.com/wso2-enterprise/wso2-mi-internal/issues/777
> [4.1.0] Add error code 601000

- en/docs/troubleshooting/error-handling-mi.md
This PR is to add the error code 601000 to the docs.
Issue reference: https://github.com/wso2-enterprise/wso2-mi-internal/issues/777
> [4.0.0] Add error code 601000

- en/docs/deploy-and-publish/deploy-on-gateway/choreo-connect/configurations/enforcer-configurations.md
- en/tools/config-catalog-generator-cc/data/enforcer/configs.json
- en/tools/config-catalog-generator-cc/data/enforcer/throttling_local_throttler_distributed.toml
- en/tools/config-catalog-generator-cc/data/enforcer/throttling_local_throttler_distributed_properties.toml
- en/tools/config-catalog-generator-cc/dist/enforcer-configurations.md
- Add new configurations related to CC backend throughput rate limiting and subscription level burst rate limiting features
- Related Issues : https://github.com/wso2/product-microgateway/issues/3525
> [4.0.0] Add configurations for distributed throttling configurations

- en/docs/administer/logging-and-monitoring/monitoring/working-with-observability.md
This PR is created to update the details in lightweight observability section under working with observability section.
this fixes https://github.com/wso2-enterprise/wso2-apim-internal/issues/4471  doc issue.
> Updated details in Lightweight Observability

- en/docs/reference/config-catalog.md
- en/tools/config-catalog-generator/data/configs.json
- en/tools/config-catalog-generator/data/transport-headers.toml
> Add docs for TransportHeaderHandler

- en/docs/reference/config-catalog.md
- en/tools/config-catalog-generator/data/configs.json
- en/tools/config-catalog-generator/data/transport-headers.toml
> [4.3.0] Add docs for TransportHeaderHandler

- .gitignore
- en/docs/reference/config-catalog.md
- en/tools/config-catalog-generator/data/configs.json
- en/tools/config-catalog-generator/data/transport-headers.toml
> [4.2.0] Add docs for TransportHeaderHandler

- .gitignore
- en/docs/reference/config-catalog.md
- en/tools/config-catalog-generator/data/configs.json
- en/tools/config-catalog-generator/data/transport-headers.toml
> [4.1.0] Add docs for TransportHeaderHandler

- .gitignore
- en/docs/reference/config-catalog.md
- en/tools/config-catalog-generator/data/configs.json
- en/tools/config-catalog-generator/data/transport-headers.toml
> [4.0.0] Add docs for TransportHeaderHandler

- en/docs/install-and-setup/install/installation-prerequisites.md
This PR is to update the minimum recommended core count.
This will fix:
- https://github.com/wso2-enterprise/wso2-mi-internal/issues/112
- https://github.com/wso2-enterprise/wso2-mi-internal/issues/770
> [4.2.0] Update the minimum recommended core count

- en/docs/administer/key-managers/configure-wso2is7-connector.md
- en/docs/install-and-setup/setup/reference/product-compatibility.md
> - $Subject.
> - Remove configurations related to legacy mode, since that's only necessary for scope based authorization.
> - Update product compatibility table with IS 7
> Add warning about IS7 scope incompatibility

- en/docs/mi-analytics/mi-elk-installation-guide.md
$subject
This will fix: https://github.com/wso2/docs-mi/issues/85
> [4.2.0] Update log4j2 path in ELK doc

- en/docs/install-and-setup/setup/setting-up-databases/changing-default-databases/changing-to-mysql.md
This PR is raised to update the information on daylight saving time changes when changing db configurations.
> Updated Information on Daylight Saving Time Change

- en/docs/design/api-security/oauth2/grant-types/client-credentials-grant.md
This PR is raised to update the token endpoint in format sections. 
This fixes https://github.com/wso2-enterprise/wso2-apim-internal/issues/4304 doc  issue
> Updated the Token Endpoint

- en/docs/design/api-security/oauth2/grant-types/client-credentials-grant.md
This PR is raised to update the token endpoint in format sections.
This fixes https://github.com/wso2-enterprise/wso2-apim-internal/issues/4304 doc issue
> Updated token endpoint

- en/docs/reference/synapse-properties/endpoint-properties.md
$subject
https://github.com/wso2/docs-mi/pull/107
**Issue reference:**
https://github.com/wso2/docs-mi/issues/108
> [4.2.0] Update the `synapse.timeout_handler_interval` property

- en/docs/reference/synapse-properties/endpoint-properties.md
$subject
https://github.com/wso2/docs-mi/pull/107
**Issue reference:**
https://github.com/wso2/docs-mi/issues/108
> [4.1.0] Update the `synapse.timeout_handler_interval` property

- en/docs/troubleshooting/error-handling-mi.md
$subject
**Issue reference:** https://github.com/wso2-enterprise/wso2-mi-internal/issues/831
> [4.0.0] Update error-handling-mi.md

- en/docs/troubleshooting/error-handling-mi.md
$subject
**Issue reference:** https://github.com/wso2-enterprise/wso2-mi-internal/issues/831
> [4.1.0] Update error-handling-mi.md

- en/docs/troubleshooting/error-handling-mi.md
$subject
**Issue reference:** https://github.com/wso2-enterprise/wso2-mi-internal/issues/831
> [4.2.0] Update error-handling-mi.md

- en/docs/install-and-setup/setup/reference/product-compatibility.md
> Update compatibility matrix to include ubuntu 22.04

- en/docs/reference/synapse-properties/endpoint-properties.md
$subject
https://github.com/wso2/docs-mi/pull/107
**Issue reference:**
https://github.com/wso2/docs-mi/issues/108
> [4.0.0] Update the `synapse.timeout_handler_interval` property

- en/docs/install-and-setup/setup/deployment-best-practices/changing-the-hostname.md
This issue is created to add docs for changes in hostnames.
Related issue : https://github.com/wso2-enterprise/wso2-apim-internal/issues/6263
> Adding docs for Custom Hostnames

- en/docs/reference/config-catalog.md
- en/tools/config-catalog-generator/data/_http-passthrough-transport-blocking.toml
- en/tools/config-catalog-generator/data/configs.json
This PR was raised to update the documentation on transport blocking mode configurations
Related Internal : https://github.com/wso2/docs-apim/issues/7857
> Updated the Docs for Transport Blocking Mode Configurations

- en/docs/install-and-setup/setup/security/configuring-keystores/configuring-keystores-in-wso2-api-manager.md
This is raised to update the Configuring Keystore page with custom keystores details.
Related Internal Issue : https://github.com/wso2-enterprise/wso2-apim-internal/issues/6577
> Updated Configuring Keystores Doc

- en/docs/integrate/examples/file-processing/accessing_windows_share_using_vfs_transport.md
This PR is to update the URI format on the `Access a Windows Share Using VFS` page.
Issue reference: https://github.com/wso2-enterprise/wso2-mi-internal/issues/449
> [4.2.0] Update the URI format

- en/docs/integrate/examples/file-processing/accessing_windows_share_using_vfs_transport.md
This PR is to update the URI format on the `Access a Windows Share Using VFS` page.
Issue reference: https://github.com/wso2-enterprise/wso2-mi-internal/issues/449
> [4.1.0] Update the URI format 

- en/docs/reference/connectors/file-connector/file-connector-config.md
$subject
Issue reference: https://github.com/wso2-enterprise/wso2-mi-internal/issues/698
> [4.2.0] Update the file connector doc with retry configs

- en/docs/integrate/develop/customizations/creating-synapse-handlers.md
$subject
**Issue reference:** https://github.com/wso2/docs-mi/issues/258
> [4.2.0] Update toml config in Synapse Handlers

- en/docs/integrate/develop/customizations/creating-synapse-handlers.md
$subject
**Issue reference:** https://github.com/wso2/docs-mi/issues/258
> [4.0.0] Update toml config in Synapse Handlers

- en/docs/integrate/develop/customizations/creating-synapse-handlers.md
$subject
**Issue reference:** https://github.com/wso2/docs-mi/issues/258
> [4.1.0] Update toml config in Synapse Handlers

- en/docs/reference/connectors/amazonlambda-connector/amazonlambda-connector-config.md
$subject
**Issue reference:** https://github.com/wso2-enterprise/wso2-mi-internal/issues/721
> [4.2.0] Update amazonlambda-connector-config.md

- en/docs/reference/connectors/amazonlambda-connector/amazonlambda-connector-config.md
$subject
**Issue reference:** https://github.com/wso2-enterprise/wso2-mi-internal/issues/721
> [4.1.0] Update amazonlambda-connector-config.md

- en/docs/reference/connectors/amazonlambda-connector/amazonlambda-connector-config.md
$subject
**Issue reference:** https://github.com/wso2-enterprise/wso2-mi-internal/issues/721
> [4.0.0] Update amazonlambda-connector-config.md

- en/docs/install-and-setup/setup/security/configuring-keystores/configuring-keystores-in-wso2-api-manager.md
This PR is raised to update the details in keystore configurations.
Related internal issue: https://github.com/wso2-enterprise/wso2-apim-internal/issues/6563
> Updated the Details on Keystore Configurations

- en/docs/install-and-setup/setup/reference/product-compatibility.md
> Update Database compatibility to include oracle 19c
> Update database compatibility

- en/docs/reference/product-apis/admin-apis/admin-v4/admin-v4.yaml
To add doc changes for deny policy filtering.
Add docs for: https://github.com/wso2/api-manager/issues/2878
> Add doc changes for deny policy filtering

- en/docs/develop/product-apis/admin-apis/admin-v1/admin-v1.yaml
To add doc changes for deny policy filtering.
Add docs for: https://github.com/wso2/api-manager/issues/2878
> [3.2.0] Add doc changes for deny policy filtering

- en/docs/reference/product-apis/admin-apis/admin-v4/admin-v4.yaml
To add doc changes for deny policy filtering.
Add docs for: https://github.com/wso2/api-manager/issues/2878
> [4.3.0] Add doc changes for deny policy filtering

- en/docs/design/advanced-topics/api-governance-cli-tool.md
- en/mkdocs.yml
> Adding a zip file to download the tool.
Issue: https://github.com/wso2-enterprise/wso2-apim-internal/issues/5585
> [4.1.0] Improvement to API Governance CLI Tool Doc

- en/docs/design/advanced-topics/api-governance-cli-tool.md
- en/mkdocs.yml
>  changing the document added place.
Issue: https://github.com/wso2-enterprise/wso2-apim-internal/issues/5585
> Improvement to API Governance CLI Tool Doc

- en/docs/design/advanced-topics/api-governance-cli-tool.md
- en/mkdocs.yml
> Adding a zip file to download the tool.
Issue: https://github.com/wso2-enterprise/wso2-apim-internal/issues/5585
> [4.2.0] Improvement to API Governance CLI Tool Doc

- en/docs/install-and-setup/setup/security/configuring-keystores/configuring-keystores-in-wso2-api-manager.md
This PR is raised to update the details in keystore configurations.
Related internal issue: https://github.com/wso2-enterprise/wso2-apim-internal/issues/6563
> Updated the Details on Keystores Configurations

- en/docs/api-analytics/choreo-analytics/getting-started-guide.md
- en/docs/get-started/apim-architecture.md
- en/docs/install-and-setup/setup/single-node/configuring-an-active-active-deployment.md
- en/docs/tutorials/scenarios/scenario7-analytics.md
Fixes https://github.com/wso2/docs-apim/issues/8024
> Fixing broken links related to analytics

- en/docs/includes/design/create-graphql-api.md
Fixing https://github.com/wso2/docs-apim/issues/8023
> Fix Broken Links in Create a GraphQL API Page

- en/mkdocs.yml
> [4.0.0]Hide MG to CC migration docs

- en/mkdocs.yml
> [4.1.0]Hide MG to CC migration docs

- en/mkdocs.yml
> [4.2.0]Hide MG to CC migration docs

- en/docs/design/create-api/create-rest-api/generate-rest-api-from-soap-backend.md
This PR is raised to add the limitations of SOAP to REST Feature
Related Internal issue : https://github.com/wso2-enterprise/wso2-apim-internal/issues/4909
> [4.3.0] Add Limitation of SOAP to REST Feature

- en/docs/design/create-api/create-rest-api/generate-rest-api-from-soap-backend.md
This PR is raised to add the limitations of SOAP to REST Feature
Related Internal issue : https://github.com/wso2-enterprise/wso2-apim-internal/issues/4909
> [master] Add Limitation of SOAP to REST Feature

- en/docs/install-and-setup/setup/setting-up-databases/managing-data-growth-and-improving-performance.md
This update added the missing information regarding token cleanup in APIM documentation.
Resolves:https://github.com/wso2-enterprise/wso2-apim-internal/issues/4224
> [3.2.0] Add missing information regarding token cleanup in APIM documentation

- en/docs/consume/manage-application/advanced-topics/adding-an-application-creation-workflow.md
> [4.0.0] Add Missing "/" in Approval Workflow Executor configuration

- en/docs/consume/manage-application/advanced-topics/adding-an-application-creation-workflow.md
> [4.1.0] Add Missing "/" in Approval Workflow Executor configuration 

- en/docs/consume/manage-application/advanced-topics/adding-an-application-creation-workflow.md
> [4.2.0] Add Missing "/" in Approval Workflow Executor configuration

- en/docs/consume/manage-application/advanced-topics/adding-an-application-creation-workflow.md
> [4.3.0] Add Missing "/" in Approval Workflow Executor configuration

- en/docs/consume/manage-application/advanced-topics/adding-an-application-creation-workflow.md
> Add Missing "/" in Approval Workflow Executor configuration

- en/docs/administer/managing-users-and-roles/managing-user-roles.md
- en/docs/design/advanced-topics/adding-an-api-state-change-workflow-using-bps.md
- en/docs/design/api-monetization/configuring-api-monetization-category-labels.md
- en/docs/design/api-security/api-authentication/secure-apis-using-oauth2-tokens.md
- en/docs/install-and-setup/setup/security/user-account-management.md
> [4.2.0] Move tenant-conf.json configuration steps to Admin UI

- en/docs/administer/managing-users-and-roles/managing-user-roles.md
- en/docs/design/advanced-topics/adding-an-api-state-change-workflow-using-bps.md
- en/docs/design/api-monetization/configuring-api-monetization-category-labels.md
- en/docs/design/api-security/api-authentication/secure-apis-using-oauth2-tokens.md
- en/docs/install-and-setup/setup/security/user-account-management.md
> [4.3.0] Move tenant-conf.json configuration steps to Admin UI

- en/docs/administer/managing-users-and-roles/managing-user-roles.md
- en/docs/design/advanced-topics/adding-an-api-state-change-workflow-using-bps.md
- en/docs/design/api-monetization/configuring-api-monetization-category-labels.md
- en/docs/design/api-security/api-authentication/secure-apis-using-oauth2-tokens.md
- en/docs/install-and-setup/setup/security/user-account-management.md
> Move tenant-conf.json configuration steps to Admin UI

- en/docs/install-and-setup/setup/distributed-deployment/synchronizing-artifacts-in-a-gateway-cluster.md
This PR is raised to update details on migrating from file based mechanism to inbuilt artifact synchronization.
Related internal issue: https://github.com/wso2-enterprise/wso2-apim-internal/issues/6481
> Updated Information on Inbuilt Artifact Synchronization

- en/docs/install-and-setup/install/deploying-api-manager-with-kubernetes-or-openshift-resources.md
> [4.0.0] Update Helm Chart versions

- en/docs/install-and-setup/install/deploying-api-manager-with-kubernetes-or-openshift-resources.md
> [4.1.0] Update Helm Chart versions

- en/docs/install-and-setup/install/deploying-api-manager-with-kubernetes-or-openshift-resources.md
> [4.2.0] Update Helm Chart versions

- en/docs/learn/api-gateway/api-gateways-with-dedicated-backends.md
> [310] Fix default sequence path
