en/docs/learn/api-gateway/api-gateways-with-dedicated-backends.md
=> [320] Fix default sequence path

en/docs/deploy-and-publish/deploy-on-gateway/api-gateway/api-gateways-with-dedicated-backends.md
=> [400] Fix default sequence path

en/docs/deploy-and-publish/deploy-on-gateway/api-gateway/api-gateways-with-dedicated-backends.md
=> [410] Fix default sequence path

en/docs/deploy-and-publish/deploy-on-gateway/api-gateway/api-gateways-with-dedicated-backends.md
=> Fix default sequence path

en/docs/install-and-setup/setup/setting-up-databases/changing-default-databases/changing-to-ibm-db2.md, en/docs/install-and-setup/setup/setting-up-databases/changing-default-databases/changing-to-mssql.md, en/docs/install-and-setup/setup/setting-up-databases/changing-default-databases/changing-to-mysql.md, en/docs/install-and-setup/setup/setting-up-databases/changing-default-databases/changing-to-oracle-rac.md, en/docs/install-and-setup/setup/setting-up-databases/changing-default-databases/changing-to-oracle.md, en/docs/install-and-setup/setup/setting-up-databases/changing-default-databases/changing-to-postgresql.md
This PR is raised to update the details about daylight saving time shift. 
=> [3.2.0] Update documentation on daylight saving time shift

en/docs/install-and-setup/setup/distributed-deployment/configuring-wso2-identity-server-as-a-key-manager.md
=> [3.2.0] Add a note to update WSO2 IS

en/docs/install-and-setup/setup/distributed-deployment/configuring-wso2-identity-server-as-a-key-manager.md
=> [4.0.0] Add a note to update WSO2 IS

en/docs/install-and-setup/setup/distributed-deployment/configuring-wso2-identity-server-as-a-key-manager.md
=> [4.1.0] Add a note to update WSO2 IS

en/docs/install-and-setup/setup/distributed-deployment/configuring-wso2-identity-server-as-a-key-manager.md
=> [4.2.0] Add a note to update WSO2 IS

en/docs/install-and-setup/setup/distributed-deployment/configuring-wso2-identity-server-as-a-key-manager.md
=> [4.3.0] Add a note to update WSO2 IS

en/docs/install-and-setup/setup/setting-up-databases/changing-default-databases/changing-to-ibm-db2.md, en/docs/install-and-setup/setup/setting-up-databases/changing-default-databases/changing-to-mssql.md, en/docs/install-and-setup/setup/setting-up-databases/changing-default-databases/changing-to-mysql.md, en/docs/install-and-setup/setup/setting-up-databases/changing-default-databases/changing-to-oracle-rac.md, en/docs/install-and-setup/setup/setting-up-databases/changing-default-databases/changing-to-oracle.md, en/docs/install-and-setup/setup/setting-up-databases/changing-default-databases/changing-to-postgresql.md
=> [master] Update documentation on daylight saving time shift

en/docs/install-and-setup/setup/mi-setup/configuring_proxy_servers.md
Resolves : https://github.com/wso2-enterprise/wso2-apim-internal/issues/3389
=> [4.0.0] Linked secured HTTPS proxy profile configs to the documentation

en/docs/install-and-setup/setup/mi-setup/configuring_proxy_servers.md
Resolves: https://github.com/wso2-enterprise/wso2-apim-internal/issues/3389
=> [4.1.0] Linked secured HTTPS proxy profile configs to the documentation

en/docs/install-and-setup/setup/mi-setup/configuring_proxy_servers.md
Resolves: https://github.com/wso2-enterprise/wso2-apim-internal/issues/3389
=> [4.2.0] Linked secured HTTPS proxy profile configs to the documentation

en/docs/install-and-setup/setup/setting-up-databases/changing-default-databases/changing-to-ibm-db2.md, en/docs/install-and-setup/setup/setting-up-databases/changing-default-databases/changing-to-mssql.md, en/docs/install-and-setup/setup/setting-up-databases/changing-default-databases/changing-to-mysql.md, en/docs/install-and-setup/setup/setting-up-databases/changing-default-databases/changing-to-oracle-rac.md, en/docs/install-and-setup/setup/setting-up-databases/changing-default-databases/changing-to-oracle.md, en/docs/install-and-setup/setup/setting-up-databases/changing-default-databases/changing-to-postgresql.md
=> [3.1.0] Update documentation on daylight saving time shift

en/docs/install-and-setup/setting-up-databases/changing-default-databases/changing-to-ibm-db2.md, en/docs/install-and-setup/setting-up-databases/changing-default-databases/changing-to-mssql.md, en/docs/install-and-setup/setting-up-databases/changing-default-databases/changing-to-mysql.md, en/docs/install-and-setup/setting-up-databases/changing-default-databases/changing-to-oracle-rac.md, en/docs/install-and-setup/setting-up-databases/changing-default-databases/changing-to-oracle.md, en/docs/install-and-setup/setting-up-databases/changing-default-databases/changing-to-postgresql.md
=> [3.0.0] Update documentation on daylight saving time shift

en/docs/install-and-setup/setup/setting-up-databases/changing-default-databases/changing-to-ibm-db2.md, en/docs/install-and-setup/setup/setting-up-databases/changing-default-databases/changing-to-mssql.md, en/docs/install-and-setup/setup/setting-up-databases/changing-default-databases/changing-to-mysql.md, en/docs/install-and-setup/setup/setting-up-databases/changing-default-databases/changing-to-oracle-rac.md, en/docs/install-and-setup/setup/setting-up-databases/changing-default-databases/changing-to-oracle.md, en/docs/install-and-setup/setup/setting-up-databases/changing-default-databases/changing-to-postgresql.md
=> [4.0.0] Update documentation on daylight saving time shift

en/docs/install-and-setup/setup/setting-up-databases/changing-default-databases/changing-to-ibm-db2.md, en/docs/install-and-setup/setup/setting-up-databases/changing-default-databases/changing-to-mssql.md, en/docs/install-and-setup/setup/setting-up-databases/changing-default-databases/changing-to-mysql.md, en/docs/install-and-setup/setup/setting-up-databases/changing-default-databases/changing-to-oracle-rac.md, en/docs/install-and-setup/setup/setting-up-databases/changing-default-databases/changing-to-oracle.md, en/docs/install-and-setup/setup/setting-up-databases/changing-default-databases/changing-to-postgresql.md
=> [4.1.0] Update documentation on daylight saving time shift

en/docs/install-and-setup/setup/setting-up-databases/changing-default-databases/changing-to-ibm-db2.md, en/docs/install-and-setup/setup/setting-up-databases/changing-default-databases/changing-to-mssql.md, en/docs/install-and-setup/setup/setting-up-databases/changing-default-databases/changing-to-mysql.md, en/docs/install-and-setup/setup/setting-up-databases/changing-default-databases/changing-to-oracle-rac.md, en/docs/install-and-setup/setup/setting-up-databases/changing-default-databases/changing-to-oracle.md, en/docs/install-and-setup/setup/setting-up-databases/changing-default-databases/changing-to-postgresql.md
=> [4.3.0] Update documentation on daylight saving time shift

en/docs/reference/config-catalog.md, en/tools/config-catalog-generator/data/_http-passthrough-transport.toml, en/tools/config-catalog-generator/data/configs.json
This PR is raised to update th passthru_http congurations in config catalog.
Related internal issue : https://github.com/wso2-enterprise/wso2-apim-internal/issues/5509
=> [4.1.0] Update passthru_https config in Config Catalog

en/docs/reference/customize-product/customizations/modify-workflow-approval-task-limit.md, en/mkdocs.yml
=> [4.0.0] Add steps to modify workflow approval task limit

en/docs/reference/customize-product/customizations/modify-workflow-approval-task-limit.md, en/mkdocs.yml
=> [4.1.0] Add steps to modify workflow approval task limit

en/docs/reference/customize-product/customizations/modify-workflow-approval-task-limit.md, en/mkdocs.yml
=> [4.2.0] Add steps to modify workflow approval task limit

en/docs/reference/customize-product/customizations/modify-workflow-approval-task-limit.md, en/mkdocs.yml
=> [4.3.0] Add steps to modify workflow approval task limit

en/docs/reference/customize-product/customizations/modify-workflow-approval-task-limit.md, en/mkdocs.yml
=> Add steps to modify workflow approval task limit

en/docs/reference/config-catalog.md, en/tools/config-catalog-generator/data/_http-passthrough-transport.toml, en/tools/config-catalog-generator/data/configs.json
This PR is raised to update th passthru_http congurations in config catalog.
Related internal issue : https://github.com/wso2-enterprise/wso2-apim-internal/issues/5509
=> [4.3.0] Update passthru_https Config in Config Catalog

en/docs/tutorials/create-and-publish-awslambda-api.md
=> [4.0.0] Add missing AWSLambda configs

en/docs/install-and-setup/setup/deployment-best-practices/changing-the-hostname.md
=> [4.0.0] Fix listener.wsdl_epr_prefix path

en/docs/install-and-setup/setup/deployment-best-practices/changing-the-hostname.md
=> [4.2.0] Fix listener.wsdl_epr_prefix path

en/docs/install-and-setup/setup/deployment-best-practices/changing-the-hostname.md
=> [4.1.0] Fix listener.wsdl_epr_prefix path

en/docs/administer/logging-and-monitoring/logging/configuring-logging.md
=> [4.0.0] Update Documentation on wirelogs

en/docs/reference/product-apis/gateway-apis/gateway-v2/gateway-v2.yaml
=> [4.1.0] Remove Authorization header from server-startup-healthcheck

en/docs/reference/product-apis/gateway-apis/gateway-v2/gateway-v2.yaml
=> [4.2.0] Remove Authorization header from server-startup-healthcheck

en/docs/reference/product-apis/gateway-apis/gateway-v2/gateway-v2.yaml
=> [4.3.0] Remove Authorization header from server-startup-healthcheck

en/docs/reference/product-apis/gateway-apis/gateway-v2/gateway-v2.yaml
=> Remove Authorization header from server-startup-healthcheck

en/docs/install-and-setup/setup/reference/product-compatibility.md
=> [4.2.0] Add Ubuntu 22.04 to compatibility matrix

en/docs/install-and-setup/setup/reference/product-compatibility.md
=> Add Ubuntu 22.04 to compatibility matrix

en/docs/administer/logging-and-monitoring/logging/setting-up-logging.md
=> [3.2.0] Update docs on Wirelogs

en/docs/administer/logging-and-monitoring/logging/configuring-logging.md
=> [4.1.0] Update Docs on Wirelogs

en/docs/administer/logging-and-monitoring/logging/configuring-logging.md
=> [4.2.0 ] Update docs on Wirelogs

en/docs/administer/logging-and-monitoring/logging/configuring-logging.md
=> [4.3.0] Update Docs on Wirelogs

en/docs/administer/logging-and-monitoring/logging/configuring-logging.md
=> [master Update Docs on Wirelogs

en/docs/troubleshooting/error-handling.md
=> [4.0.0] Add error code 900424

en/docs/troubleshooting/error-handling.md
=> [4.1.0] Add error code 900424

en/docs/troubleshooting/error-handling.md
=> [4.2.0] Add error code 900424

en/docs/troubleshooting/error-handling.md
=> [4.3.0] Add error code 900424

en/docs/integrate/develop/customizations/creating-synapse-handlers.md, en/docs/reference/config-catalog.md, en/tools/config-catalog-generator/data/configs.json
=> [4.0.0] Updated synapse handlers configurations

en/docs/design/advanced-topics/enabling-cors-for-apis.md
=> [4.0.0] Remove Enabling CORS for OAuth Token related Endpoints

en/docs/design/advanced-topics/enabling-cors-for-apis.md
=> [4.1.0] Remove Enabling CORS for OAuth Token related Endpoints

en/docs/design/advanced-topics/enabling-cors-for-apis.md
=> [4.2.0] Remove Enabling CORS for OAuth Token related Endpoints

en/docs/design/advanced-topics/enabling-cors-for-apis.md
=> [4.3.0] Remove Enabling CORS for OAuth Token related Endpoints

en/docs/design/advanced-topics/enabling-cors-for-apis.md
=> Remove Enabling CORS for OAuth Token related Endpoints

en/docs/integrate/develop/customizations/creating-synapse-handlers.md, en/docs/reference/config-catalog.md, en/tools/config-catalog-generator/data/configs.json
=> [4.1.0] Updated synapse handlers configurations

en/docs/reference/config-catalog.md, en/tools/config-catalog-generator/data/configs.json
=> [4.3.0] Updated synapse handlers configurations

en/docs/reference/config-catalog.md, en/tools/config-catalog-generator/data/configs.json
=> [master] Updated synapse handlers configurations

en/docs/install-and-setup/setup/advance-configurations/configuring-caching.md
=> [4.0.0] Fix default config for apim.cache.publisher_roles.enable

en/docs/install-and-setup/setup/advance-configurations/configuring-caching.md
=> [4.1.0] Fix default config for apim.cache.publisher_roles.enable

en/docs/install-and-setup/setup/advance-configurations/configuring-caching.md
=> [4.2.0] Fix default config for apim.cache.publisher_roles.enable

en/docs/install-and-setup/setup/advance-configurations/configuring-caching.md
=> [4.3.0] Fix default config for apim.cache.publisher_roles.enable

en/docs/install-and-setup/setup/advance-configurations/configuring-caching.md
=> Fix default config for apim.cache.publisher_roles.enable

en/docs/install-and-setup/setup/deployment-best-practices/changing-the-hostname.md
=> Note on changes of hostname after the initial server startup

en/docs/install-and-setup/setup/deployment-best-practices/changing-the-hostname.md
=> [4.0.0] Note on changes of hostname after the initial server startup

en/docs/install-and-setup/setup/deployment-best-practices/changing-the-hostname.md
=> [4.1.0] Note on changes of hostname after the initial server startup

en/docs/install-and-setup/setup/deployment-best-practices/changing-the-hostname.md
=> [4.2.0] Note on changes of hostname after the initial server startup

en/docs/install-and-setup/setup/deployment-best-practices/changing-the-hostname.md
=> [4.3.0] Note on changes of hostname after the initial server startup

en/docs/install-and-setup/setup/setting-up-databases/changing-default-databases/changing-to-mysql.md
This PR is raised to update AM_DB tables for Mysql group replication
=> [4.0.0] Update am_db tables for mysql group replication

en/docs/install-and-setup/setup/setting-up-databases/changing-default-databases/changing-to-mysql.md
This PR is raised to update AM_DB tables for Mysql group replication
=> [4.2.0] Update am_db tables for mysql group replication

en/docs/install-and-setup/setup/setting-up-databases/changing-default-databases/changing-to-mysql.md
This PR is raised to update AM_DB tables for Mysql group replication
=> [4.3.0] Update am_db tables for mysql group replication

en/docs/install-and-setup/setup/setting-up-databases/changing-default-databases/changing-to-mysql.md
This PR is raised to update AM_DB tables for Mysql group replication
=> [master] Update am_db Tables for Mysql Group Replication

en/docs/install-and-setup/setup/single-node/configuring-an-active-active-deployment.md
=> [4.2.0] Adding throttle_decision_endpoint_config

en/docs/reference/customize-product/customizations/advanced-ui-customization.md
=> Update advanced UI customization steps

en/docs/reference/customize-product/customizations/advanced-ui-customization.md
=> [4.3.0] Update advanced UI customization steps

en/docs/install-and-setup/setup/single-node/configuring-an-active-active-deployment.md
=> [3.2.0] Adding throttle_decision_endpoint_config

en/docs/reference/customize-product/customizations/advanced-ui-customization.md
=> [4.2.0] Update advanced UI customization steps

en/docs/install-and-setup/setup/single-node/configuring-an-active-active-deployment.md
=> [4.0.0] Adding throttle_decision_endpoint_config

en/docs/install-and-setup/setup/single-node/configuring-an-active-active-deployment.md
=> [4.1.0] Adding throttle_decision_endpoint_config

en/docs/install-and-setup/setup/single-node/configuring-an-active-active-deployment.md
This PR is created to fix the numbering order in rate limiting section in active-active deployment
=> [4.2.0] Fixing numbering order

en/docs/install-and-setup/setup/single-node/configuring-an-active-active-deployment.md
=> [4.3.0] Adding throttle_decision_endpoint_config

en/docs/install-and-setup/setup/single-node/configuring-an-active-active-deployment.md
=> [master] Adding throttle_decision_endpoint_config

en/docs/reference/mediators/property-reference/accessing-properties-with-xpath.md
This PR is raised to update the xpath properties
=> [4.0.0 ] Updated xpath properties

en/docs/reference/mediators/property-reference/accessing-properties-with-xpath.md
This PR is raised to update the xpath properties
=> [4.1.0] Updated xpath properties

en/docs/reference/mediators/property-reference/accessing-properties-with-xpath.md
This PR is raised to update the xpath properties
=> [4.2.0] Updated xpath properties

README.md, en/docs/get-started/api-manager-quick-start-guide.md
=> 4.0.0 Notes add

README.md, en/docs/get-started/api-manager-quick-start-guide.md
=> 4.1.0 Notes add

README.md, en/docs/get-started/api-manager-quick-start-guide.md
=> 4.2.0 notes add

README.md, en/docs/get-started/api-manager-quick-start-guide.md
=> 4.3.0 improvements notes add

README.md, en/docs/get-started/api-manager-quick-start-guide.md
=> 4.3.0 notes add

en/docs/design/endpoints/resiliency/endpoint-timeouts.md
=> [4.1.0] Update details on Retries Before Suspension

en/docs/design/endpoints/resiliency/endpoint-timeouts.md
=> [4.0.0] Update details on Retries Before Suspension

en/docs/design/endpoints/resiliency/endpoint-timeouts.md, en/docs/install-and-setup/setup/distributed-deployment/configuring-wso2-identity-server-as-a-key-manager.md
=> [4.2.0] Update Details on Retries Before Suspension

en/docs/design/endpoints/resiliency/endpoint-timeouts.md
=> [master] Update details on Retries Before Suspension

en/docs/design/endpoints/resiliency/endpoint-timeouts.md
=> [4.3.0] Update details on Retries Before Suspension

en/docs/reference/product-apis/publisher-apis/publisher-v4/publisher-v4.yaml
$subject
Related backend PR: https://github.com/wso2/carbon-apimgt/pull/12467
Git issue: https://github.com/wso2/api-manager/issues/2923
=> Add REST API doccumentation for Change subscription business plan REST API

en/docs/install-and-setup/setup/security/logins-and-passwords/maintaining-logins-and-passwords.md
This PR is raised to update docs on maintaining-logins-and-passwords
=> [4.3.0] Updated docs on maintaining-logins-and-passwords

en/docs/install-and-setup/setup/security/logins-and-passwords/maintaining-logins-and-passwords.md
This PR is raised to update docs on maintaining-logins-and-passwords
=> [master] Updated docs on maintaining-logins-and-passwords

en/docs/observe/api-manager/monitoring-correlation-logs.md
This PR is raised updated information on BlackListedThreads feature
=> [4.1.0] Updated information on BlackListedThreads Feature

en/docs/observe/api-manager/monitoring-correlation-logs.md
This PR is raised updated information on BlackListedThreads feature
=> [4.2.0] Updated information on BlackListedThreads Feature

en/docs/observe/api-manager/monitoring-correlation-logs.md
This PR is raised updated information on BlackListedThreads feature
=> [4.3.0] Updated information on BlackListedThreads Feature

en/docs/observe/api-manager/monitoring-correlation-logs.md
This PR is raised updated information on BlackListedThreads feature
=> [master] Updated information on BlackListedThreads Feature

en/docs/tutorials/edit-an-api-by-modifyng-the-api-definition.md
This PR is raised update OpenAPI support versions
=> [master] Updated OpenAPI support versions

en/docs/learn/design-api/api-documentation/add-api-documentation.md
This PR is raised to update the allowed file types for API documentation.
=> [3.2.0] Updated file Types for API Documentation

en/docs/install-and-setup/setup/deployment-best-practices/tuning-performance.md
=> [4.1.0] Updated information on database cleaning

en/docs/install-and-setup/setup/deployment-best-practices/tuning-performance.md
=> [4.0.0] Updated information on database cleaning

en/docs/install-and-setup/setup/deployment-best-practices/tuning-performance.md
=> [master] Updated information on database cleaning

en/docs/install-and-setup/setup/deployment-best-practices/tuning-performance.md
=> [4.2.0] Updated information on database cleaning

en/docs/install-and-setup/setup/deployment-best-practices/tuning-performance.md
=> [4.3.0] Updated information on database cleaning

en/docs/design/api-documentation/add-api-documentation.md
This PR is raised to update the allowed file types for API documentation.
=> [master] Updated file types for api documentation

en/docs/design/api-documentation/add-api-documentation.md
This PR is raised to update the allowed file types for API documentation.
=> [4.3.0] Updated file types for api documentation

en/docs/design/api-documentation/add-api-documentation.md
This PR is raised to update the allowed file types for API documentation.
=> [4.1.0] Updated file types for api documentation

en/docs/install-and-setup/setup/reference/product-compatibility.md
This PR is raised to update support versions of PostgreSQL
=> [4.0.0]Adding PostgreSQL support versions

en/docs/install-and-setup/setup/reference/product-compatibility.md
This PR is raised to update support versions of PostgreSQL
=> [4.2.0] Adding PostgreSQL support versions

en/docs/install-and-setup/setup/multi-dc-deployment/configuring-multi-dc-deployment-pattern-1.md
This PR is raised to update data publisher details for multi DC deployment.
=> [4.3.0] Update Data Publisher Details for Multi DC deployment

en/docs/administer/key-managers/configure-wso2is-connector.md
This PR is raised update the userInfo endpoint in IS as Key Manager configurations. 
Fix: https://github.com/wso2/docs-apim/issues/8340
=> [4.3.0] Updated the UserInfo endpoint

en/docs/administer/key-managers/configure-wso2is-connector.md
This PR is raised update the userInfo endpoint in IS as Key Manager configurations.
https://github.com/wso2/docs-apim/issues/8340
=> [4.2.0] Updated the UserInfo endpoint

en/docs/administer/key-managers/configure-wso2is-connector.md
This PR is raised update the userInfo endpoint in IS as Key Manager configurations.
https://github.com/wso2/docs-apim/issues/8340
=> [4.1.0] Updated the UserInfo endpoint

en/docs/administer/key-managers/configure-wso2is-connector.md
This PR is raised update the userInfo endpoint in IS as Key Manager configurations.
https://github.com/wso2/docs-apim/issues/8340
=> [4.0.0] Updated userInfo endpoint in IS as KM configurations

en/docs/install-and-setup/setup/sso/configuring-identity-server-as-external-idp-using-oidc.md
=> [APIM 4.2.0] Improve 'Configuring Identity Server as External IDP using OIDC' doc

en/docs/administer/key-managers/configure-wso2is-connector.md, en/docs/administer/key-managers/configure-wso2is7-connector.md, en/docs/administer/key-managers/overview.md, en/docs/install-and-setup/setup/distributed-deployment/configuring-wso2-identity-server-as-a-key-manager.md, en/docs/install-and-setup/setup/reference/product-compatibility.md, en/mkdocs.yml
> $Subject. Related to https://github.com/wso2/api-manager/issues/2937
=> Add docs about RBAC with IS7

en/docs/administer/key-managers/configure-wso2is7-connector.md
=> Update authorize endpoint in IS7 KM docs

en/docs/install-and-setup/setup/security/logins-and-passwords/maintaining-logins-and-passwords.md
=> [3.1.0] Remove password recovery using chpasswd.sh

en/docs/administer/product-security/logins-and-passwords/maintaining-logins-and-passwords.md
=> [3.0.0] Remove password recovery using chpasswd.sh

en/docs/install-and-setup/setup/security/logins-and-passwords/maintaining-logins-and-passwords.md, en/docs/reference/faq.md
=> [4.0.0] Remove password recovery using chpasswd.sh

en/docs/install-and-setup/setup/security/logins-and-passwords/maintaining-logins-and-passwords.md, en/docs/reference/faq.md
=> [4.1.0] Remove password recovery using chpasswd.sh

en/docs/install-and-setup/setup/security/logins-and-passwords/maintaining-logins-and-passwords.md, en/docs/reference/faq.md
=> [4.2.0] Remove password recovery using chpasswd.sh

en/docs/install-and-setup/setup/security/logins-and-passwords/maintaining-logins-and-passwords.md, en/docs/reference/faq.md
=> [4.3.0] Remove password recovery using chpasswd.sh

en/docs/install-and-setup/setup/security/logins-and-passwords/maintaining-logins-and-passwords.md, en/docs/reference/faq.md
=> Remove password recovery using chpasswd.sh

en/docs/deploy-and-publish/deploy-on-gateway/choreo-connect/security/api-authentication/mutual-ssl-authentication.md, en/docs/design/api-security/api-authentication/secure-apis-using-mutual-ssl.md, en/docs/design/api-security/api-authentication/securing-apis-using-certificate-bound-access-tokens.md
This PR adds recommendation for using HTTPS with Mutual SSL. Fixes https://github.com/wso2/docs-apim/issues/8329.
=> Add recommendation for using HTTPS with Mutual SSL

en/docs/design/api-security/api-authentication/secure-apis-using-mutual-ssl.md, en/docs/design/api-security/api-authentication/securing-apis-using-certificate-bound-access-tokens.md
This PR adds recommendation for using HTTPS with Mutual SSL. Fixes https://github.com/wso2/docs-apim/issues/8329
=> [master] Add HTTPS transport change to Mutual SSL docs

en/docs/reference/connectors/amazons3-connector/amazons3-connector-reference.md
$subject
Fixes https://github.com/wso2/docs-mi/issues/122.
=> [4.2.0] Update amazons3-connector-reference.md

en/docs/reference/connectors/amazons3-connector/amazons3-connector-reference.md
$subject
Fixes https://github.com/wso2/docs-mi/issues/122.
=> [4.0.0] Update amazons3-connector-reference.md

en/docs/integrate/examples/file-processing/accessing_windows_share_using_vfs_transport.md
This PR is to update the URI format on the `Access a Windows Share Using VFS` page.
Issue reference: https://github.com/wso2-enterprise/wso2-mi-internal/issues/449
=> [master] Update the URI format

en/docs/reference/connectors/file-connector/file-connector-config.md, en/docs/reference/synapse-properties/transport-parameters/vfs-transport-parameters.md
$subject
This will fix https://github.com/wso2/docs-mi/issues/116.
=> [4.2.0] Add note for username and password

en/docs/reference/connectors/file-connector/file-connector-config.md, en/docs/reference/synapse-properties/transport-parameters/vfs-transport-parameters.md
$subject
This will fix https://github.com/wso2/docs-mi/issues/116.
=> [4.1.0] Add note for username and password

en/docs/reference/connectors/file-connector/file-connector-config.md, en/docs/reference/synapse-properties/transport-parameters/vfs-transport-parameters.md
$subject
This will fix https://github.com/wso2/docs-mi/issues/116.
=> [4.0.0] Add note for username and password

en/docs/administer/logging-and-monitoring/logging/monitoring-http-access-logs.md
Fixes related to https://github.com/wso2/api-manager/issues/3091
=> Update passthrough access logs doc

en/docs/tutorials/edit-an-api-by-modifyng-the-api-definition.md
=> Adding important note to swagger edit doc

en/docs/tutorials/edit-an-api-by-modifyng-the-api-definition.md
=> [4.2.0] Adding important note to swagger edit doc 

en/docs/consume/discover-apis/marketplace-assistant.md
> This document role based access control support for marketplace assistant related to https://github.com/wso2-enterprise/apim-ai-deployments/pull/125
=> Documenting RBAC for marketplace assistant 4.3.0

en/docs/consume/discover-apis/marketplace-assistant.md
> This document role based access control support for marketplace assistant related to https://github.com/wso2-enterprise/apim-ai-deployments/pull/125
=> Documenting RBAC for marketplace assistant

en/docs/reference/config-catalog-mi.md
$subject
Issue reference: https://github.com/wso2/docs-mi/issues/944
=> [4.2.0] Remove PKCS12 from the possible values

en/docs/reference/config-catalog-mi.md
$subject
Issue reference: https://github.com/wso2/docs-mi/issues/944
=> [4.1.0] Remove PKCS12 from the possible values

en/docs/reference/config-catalog-mi.md
$subject
Issue reference: https://github.com/wso2/docs-mi/issues/944
=> [4.0.0] Remove PKCS12 from the possible values

en/docs/install-and-setup/setup/api-controller/getting-started-with-wso2-api-controller.md
=> Add artifacts for APICTL 4.1.4

en/docs/install-and-setup/setup/multi-dc-deployment/multi-dc-deployment-patterns-overview.md
This PR adds the doc update for the Multi DC replication for PostgreSQL done on,
- https://github.com/wso2/carbon-apimgt/pull/12525
=> Doc update for Multi DC Replication for PostgreSQL

en/docs/consume/discover-apis/search.md
Improve the docs to indicate improvements done under https://github.com/wso2/api-manager/issues/3103
=> Improve Unified Search Docs

en/docs/administer/key-managers/configure-global-key-manager.md
- Add note about password and code grant usages to Global Key Manager documentation added using [1]
[1] https://github.com/wso2/docs-apim/pull/7635
=> Add Note About Password and Code Grant Usages to Global Key Manager Documentation

en/mkdocs.yml
This PR modifies mkdocs.yml for new branch 4.4.0
=> Modify mkdocs.yml for new branch 4.4.0

en/docs/assets/css/theme.css, en/theme/material/partials/header.html
This PR adds the WIP banner to APIM 4.4.0 docs.
=> Add WIP banner for 4.4.0 docs

en/docs/install-and-setup/setup/mi-setup/databases/setting-up-postgresql.md
$subject
This will fix https://github.com/wso2/docs-mi/issues/857.
=> [4.2.0] Add note on non-public schemas in PostgreSQL

en/docs/install-and-setup/setup/mi-setup/databases/setting-up-postgresql.md
$subject
This will fix https://github.com/wso2/docs-mi/issues/857.
=> [4.1.0] Add note on non-public schemas in PostgreSQL

en/docs/administer/key-managers/configure-wso2is-connector.md, en/docs/administer/key-managers/configure-wso2is7-connector.md, en/docs/administer/key-managers/overview.md, en/docs/install-and-setup/setup/distributed-deployment/configuring-wso2-identity-server-as-a-key-manager.md, en/docs/install-and-setup/setup/reference/product-compatibility.md, en/mkdocs.yml
> $Subject. Cherry picking commits from https://github.com/wso2/docs-apim/pull/8425
https://github.com/wso2/docs-apim/pull/8425
=> [Master] Add IS7 Connector docs

en/docs/administer/key-managers/configure-wso2is-connector.md, en/docs/administer/key-managers/configure-wso2is7-connector.md, en/docs/administer/key-managers/overview.md, en/docs/install-and-setup/setup/distributed-deployment/configuring-wso2-identity-server-as-a-key-manager.md, en/docs/install-and-setup/setup/reference/product-compatibility.md, en/mkdocs.yml
> $Subject. Cherry picked from the 4.3.0 branch.
- https://github.com/wso2/docs-apim/pull/7893
- https://github.com/wso2/docs-apim/pull/7903
- https://github.com/wso2/docs-apim/pull/8009
- https://github.com/wso2/docs-apim/pull/8347
- https://github.com/wso2/docs-apim/pull/8349
=> Add IS7 Connector docs

en/docs/reference/mediators/aggregate-mediator.md, en/docs/reference/mediators/clone-mediator.md, en/docs/reference/mediators/iterate-mediator.md, en/docs/reference/mediators/store-mediator.md
This PR updates the old EIP references to direct to the updated content in the latest MI documentation.
=> [4.2.0] Update EIP references

en/docs/reference/mediators/aggregate-mediator.md, en/docs/reference/mediators/clone-mediator.md, en/docs/reference/mediators/store-mediator.md
This PR updates the old EIP references to direct to the updated content in the latest MI documentation.
=> [4.1.0] Update EIP references

en/docs/reference/mediators/aggregate-mediator.md, en/docs/reference/mediators/clone-mediator.md, en/docs/reference/mediators/iterate-mediator.md, en/docs/reference/mediators/store-mediator.md
This PR updates the old EIP references to direct to the updated content in the latest MI documentation.
=> [4.0.0] Update EIP references

en/docs/install-and-setup/setup/api-controller/managing-common-api-policies/migrating-common-api-policies-to-different-environments.md
- Resolves: https://github.com/wso2/docs-apim/issues/8441
=> Add version to API Policy export command

en/docs/install-and-setup/setup/api-controller/managing-common-api-policies/migrating-common-api-policies-to-different-environments.md
- Resolves: https://github.com/wso2/docs-apim/issues/8441
=> [4.4.0] Add version to API Policy export command

en/docs/observe/micro-integrator/setting-up-cloud-native-observability-in-kubernetes.md, en/docs/observe/micro-integrator/setting-up-cloud-native-observability-on-a-vm.md
$subject
This will fix https://github.com/wso2/docs-mi/issues/1001.
https://github.com/wso2/docs-mi/pull/886
=> [4.2.0] Update Tracing configs

en/docs/install-and-setup/setup/api-controller/managing-rate-limiting-policies/migrating-rate-limiting-policies-to-different-environments.md, en/docs/install-and-setup/setup/api-controller/managing-rate-limiting-policies/throttle-policy-import-export.md
- Resolves: https://github.com/wso2/docs-apim/issues/8446
=> [4.4.0] Fix throttle policy export/import related doc issues

en/docs/install-and-setup/setup/api-controller/managing-rate-limiting-policies/migrating-rate-limiting-policies-to-different-environments.md, en/docs/install-and-setup/setup/api-controller/managing-rate-limiting-policies/throttle-policy-import-export.md
- Resolves: https://github.com/wso2/docs-apim/issues/8446
=> Fix throttle policy export/import related doc issues

en/docs/install-and-setup/setup/security/logins-and-passwords/harshicrop-vault-extension.md, en/mkdocs.yml
> This PR will introduce documentation for integrate APIM with hashicrop vault extension [1].
[1] - https://github.com/wso2-extensions/carbon-securevault-hashicorp/tree/master
The following demonstrates the rendered view
=> Add docs related to integration of Hashicrop Vault extension

en/docs/api-analytics/on-prem/elk-installation-guide.md
- Fix https://github.com/wso2/docs-apim/issues/8434
=> Fix missing ELK configurations

en/docs/design/create-api/adding-custom-properties-to-apis.md
- $Subject
- Fix https://github.com/wso2/docs-apim/issues/8476
- Made the first step consistent with other documentation pages
- Fix incorrect doc URLs
=> Fix issues in custom property docs

en/docs/design/create-api/adding-custom-properties-to-apis.md
- $Subject
- Fix https://github.com/wso2/docs-apim/issues/8476
- Made the first step consistent with other documentation pages
- Fix incorrect doc URLs
=> [4.4.0] Fix issues in custom property docs

en/docs/design/create-api/adding-custom-properties-to-apis.md
- $Subject
- Fix https://github.com/wso2/docs-apim/issues/8476
- Made the first step consistent with other documentation pages
- Fix incorrect doc URLs
=> [4.3.0] Fix issues in custom property docs

en/docs/tutorials/create-and-publish-a-sequencebackend-api.md
-  $Subject
- Fix following note
- Related issues: https://github.com/wso2/docs-apim/issues/8481
=> Fix indentation issue in sequence as a backend doc

en/docs/consume/manage-application/advanced-topics/changing-the-owner-of-an-application.md
- Resolves: https://github.com/wso2/docs-apim/issues/8482
=> Fix application owner change related doc issue

en/docs/consume/manage-application/advanced-topics/changing-the-owner-of-an-application.md
- Resolves: https://github.com/wso2/docs-apim/issues/8482
=> [4.4.0] Fix application owner change related doc issue

en/docs/includes/design/create-publish-api.md
- Resolves https://github.com/wso2/docs-apim/issues/8478
=> Fix unclear steps related to securing APIs with API Keys

en/docs/design/create-api/adding-custom-properties-to-apis.md
- $Subject
- Fix https://github.com/wso2/docs-apim/issues/8475
=> [4.4.0] Fix additional properties element in the REST API request body

en/docs/design/create-api/adding-custom-properties-to-apis.md
- $Subject
- Fix https://github.com/wso2/docs-apim/issues/8475
=> Fix additional properties element in the REST API request body

en/docs/includes/design/create-publish-api.md
- Resolves https://github.com/wso2/docs-apim/issues/8478
=> [4.4.0] Fix unclear steps related to securing APIs with API Keys

en/docs/design/api-monetization/monetizing-an-api.md, en/docs/reference/product-apis/admin-apis/admin-v4/admin-v4.yaml, en/docs/reference/product-apis/devportal-apis/devportal-v3/devportal-v3.yaml, en/docs/reference/product-apis/publisher-apis/publisher-v4/publisher-v4.yaml
$subject
https://github.com/wso2/docs-apim/issues/8505
=> Update Product API Definitions and Versions

en/docs/design/api-monetization/monetizing-an-api.md, en/docs/reference/product-apis/admin-apis/admin-v4/admin-v4.yaml, en/docs/reference/product-apis/devportal-apis/devportal-v3/devportal-v3.yaml, en/docs/reference/product-apis/publisher-apis/publisher-v4/publisher-v4.yaml
=> [Master] Update Product Api Definitions

en/docs/get-started/about-this-release.md
This PR updates the About this Release section of the docs for 4.4.0 release.
=> [4.4.0] Update about this release doc for 4.4.0

en/docs/get-started/about-this-release.md
Update about this release doc for 4.4.0
=> Update about this release doc for 4.4.0

en/docs/learn/rate-limiting/introducing-throttling-use-cases.md
=> [3.2.0] Add Note Regarding Throttling Slippage

en/docs/install-and-setup/setup/sso/okta-as-an-external-idp-using-saml.md
Update step 2 in the prerequisite section to mention "latest WSO2 API Manager distribution" instead of "API Manager 4.1.0".
=> Update to mention "latest distribution" instead of "API Manager 4.1.0"

en/docs/troubleshooting/error-handling.md
> https://github.com/wso2-enterprise/wso2-apim-internal/issues/6456
=> Add error code 900424

en/docs/install-and-setup/install/deploying-api-manager-with-kubernetes-or-openshift-resources.md, en/docs/install-and-setup/setup/api-controller/managing-apis-api-products/migrating-apis-to-different-environments.md
> [Update k8s docs for APIM 4.4.0 release](https://github.com/wso2/docs-apim/commit/ba8f1f0bd16df2b9277262b043873bcbe57292fc)
> [Fix APIM version references](https://github.com/wso2/docs-apim/commit/71afd874e055c0836e498313e8d412e41ab0b7c7)
Fix: https://github.com/wso2/docs-apim/issues/8515
=> Update 4.4.0 docs

en/docs/install-and-setup/install/deploying-api-manager-with-kubernetes-or-openshift-resources.md, en/docs/install-and-setup/setup/api-controller/managing-apis-api-products/migrating-apis-to-different-environments.md
> [Update k8s docs for APIM 4.4.0 release](https://github.com/wso2/docs-apim/commit/95271802e7fcdddf2dafa1aecabffede9c73faa6)
> [Fix APIM version references](https://github.com/wso2/docs-apim/commit/1a34e04f52b5fa5726dac8060ba3e43a9f342f0e)
> Fix https://github.com/wso2/docs-apim/issues/8515
=> [4.4.0] Update 4.4.0 docs

en/docs/install-and-setup/install/deploying-api-manager-with-kubernetes-or-openshift-resources.md
=> Refactor k8s setup instructions

en/docs/install-and-setup/setup/deployment-best-practices/security-guidelines-for-production-deployment.md
> Fix: https://github.com/wso2/docs-apim/issues/8473
=> [4.2.0] Add allow list to expose Developer portal

en/docs/install-and-setup/setup/deployment-best-practices/security-guidelines-for-production-deployment.md
> Fix: https://github.com/wso2/docs-apim/issues/8473
=> [4.3.0] Add allow list to expose Developer portal

en/docs/install-and-setup/setup/deployment-best-practices/security-guidelines-for-production-deployment.md
> Fix: https://github.com/wso2/docs-apim/issues/8473
=> Add allow list to expose Developer portal

en/docs/install-and-setup/install/installing-the-product/installing-in-containers/installing-si-using-kubernetes.md, en/docs/install-and-setup/setup/api-controller/advanced-topics/configuring-git-integration.md, en/docs/install-and-setup/setup/api-controller/advanced-topics/using-dynamic-data-in-api-controller-projects.md, en/docs/install-and-setup/setup/api-controller/building-jenkins-ci-cd-pipeline.md, en/docs/install-and-setup/setup/api-controller/cicd-using-cli.md, en/docs/install-and-setup/setup/mi-setup/transport_configurations/configuring-transports.md, en/docs/install-and-setup/setup/security/configuring-transport-level-security.md, en/docs/install-and-setup/setup/security/enabling-java-security-manager.md
Fixes https://github.com/wso2/docs-apim/issues/8517 in 4.4.0 doc space
=> [4.4.0] Remove $ from commands

en/docs/install-and-setup/setup/api-controller/advanced-topics/configuring-git-integration.md, en/docs/install-and-setup/setup/api-controller/advanced-topics/using-dynamic-data-in-api-controller-projects.md, en/docs/install-and-setup/setup/api-controller/building-jenkins-ci-cd-pipeline.md, en/docs/install-and-setup/setup/api-controller/cicd-using-cli.md, en/docs/install-and-setup/setup/mi-setup/transport_configurations/configuring-transports.md, en/docs/install-and-setup/setup/security/configuring-transport-level-security.md, en/docs/install-and-setup/setup/security/enabling-java-security-manager.md
Fixes https://github.com/wso2/docs-apim/issues/8517
=> Remove $ from commands

en/docs/reference/customize-product/customizations/customizing-the-developer-portal/customize-api-listing/api-category-based-grouping.md
Fixes https://github.com/wso2/docs-apim/issues/8422
=> Fix doc link

en/docs/reference/customize-product/customizations/customizing-the-developer-portal/customize-api-listing/api-category-based-grouping.md
Fixes #8422 in 4.3.0 doc space
=> [4.3.0] Fix doc link

en/docs/reference/customize-product/customizations/customizing-the-developer-portal/enabling-or-disabling-self-signup.md
Fixes https://github.com/wso2/docs-apim/issues/7814
=> [4.3.0] Add a reason for adding the role

en/docs/administer/managing-users-and-roles/managing-user-stores/configuring-secondary-user-stores.md, en/docs/reference/customize-product/customizations/customizing-the-developer-portal/enabling-or-disabling-self-signup.md
Fixes https://github.com/wso2/docs-apim/issues/7814
=> Add a reason for adding the role

en/docs/design/api-policies/create-policy.md, en/docs/install-and-setup/setup/api-controller/managing-common-api-policies/managing-common-api-policies.md, en/docs/install-and-setup/setup/api-controller/managing-common-api-policies/migrating-common-api-policies-to-different-environments.md
- Resolves: https://github.com/wso2/docs-apim/issues/8479
=> [4.4.0] Fix APICTL related API policy example commands

en/docs/design/api-policies/create-policy.md, en/docs/install-and-setup/setup/api-controller/managing-common-api-policies/managing-common-api-policies.md, en/docs/install-and-setup/setup/api-controller/managing-common-api-policies/migrating-common-api-policies-to-different-environments.md
- Resolves: https://github.com/wso2/docs-apim/issues/8479
=> Fix APICTL related API policy example commands

en/docs/reference/customize-product/customizations/customizing-the-developer-portal/enabling-or-disabling-self-signup.md
- Resolves https://github.com/wso2/docs-apim/issues/7814
=> [4.4.0] Add reason for subscriber role in Self Sign Up Config

en/docs/install-and-setup/setup/distributed-deployment/understanding-the-distributed-deployment-of-wso2-api-m.md
=> Update APIM profile documentation

en/docs/install-and-setup/setup/distributed-deployment/understanding-the-distributed-deployment-of-wso2-api-m.md
=> [4.4.0] Update APIM profile documentation

en/docs/install-and-setup/setup/distributed-deployment/understanding-the-distributed-deployment-of-wso2-api-m.md
=> [4.3.0] Update APIM profile documentation

en/docs/install-and-setup/setup/distributed-deployment/understanding-the-distributed-deployment-of-wso2-api-m.md
=> [4.2.0] Update APIM profile documentation

en/docs/install-and-setup/setup/distributed-deployment/understanding-the-distributed-deployment-of-wso2-api-m.md
=> [4.1.0] Update APIM profile documentation

en/docs/install-and-setup/setup/distributed-deployment/understanding-the-distributed-deployment-of-wso2-api-m.md
=> [4.0.0] Update APIM profile documentation

en/docs/get-started/about-this-release.md
$Subject
Resolves : https://github.com/wso2/docs-apim/issues/8321
=> [4.0.0] Update Release Note

en/docs/get-started/about-this-release.md
$Subject
Resolves : https://github.com/wso2/docs-apim/issues/8321
=> [4.1.0] Update the release note

en/docs/get-started/about-this-release.md
$Subject
Resolves : https://github.com/wso2/docs-apim/issues/8321
=> [4.2.0] Update the release note 

en/docs/get-started/about-this-release.md
$Subject
Resolves : https://github.com/wso2/docs-apim/issues/8321
=> [4.3.0] Update the release note

en/docs/install-and-setup/install-and-setup-overview.md
> Fix: https://github.com/wso2/docs-apim/issues/8067
=> [4.3.0] Fix APIM migration references

en/theme/material/partials/header.html
=> [4.4.0] Remove WIP banner

en/docs/install-and-setup/setup/setting-up-proxy-server-and-the-load-balancer/adding-a-custom-proxy-path.md
=> Update the SSL certificate key size in custom proxy path document

en/docs/install-and-setup/setup/setting-up-proxy-server-and-the-load-balancer/adding-a-custom-proxy-path.md
=> [4.4.0]Update the SSL certificate key size in custom proxy path document

en/docs/install-and-setup/setup/setting-up-proxy-server-and-the-load-balancer/adding-a-custom-proxy-path.md
=> [4.3.0]Update the SSL certificate key size in custom proxy path document

en/docs/install-and-setup/setup/setting-up-proxy-server-and-the-load-balancer/adding-a-custom-proxy-path.md
=> [4.2.0]Update the SSL certificate key size in custom proxy path document

en/docs/install-and-setup/setup/setting-up-proxy-server-and-the-load-balancer/adding-a-custom-proxy-path.md
=> [4.1.0]Update the SSL certificate key size in custom proxy path document

en/docs/install-and-setup/setup/setting-up-proxy-server-and-the-load-balancer/adding-a-custom-proxy-path.md
=> [4.0.0]Update the SSL certificate key size in custom proxy path document

en/docs/install-and-setup/setup/distributed-deployment/deploying-wso2-api-m-in-a-distributed-setup.md
=> [4.0.0] Add heartbeat configs

en/docs/install-and-setup/setup/distributed-deployment/deploying-wso2-api-m-in-a-distributed-setup.md
=> [4.1.0] Add heartbeat configs

en/docs/install-and-setup/setup/distributed-deployment/deploying-wso2-api-m-in-a-distributed-setup.md
=> [4.2.0] Add heartbeat configs

en/docs/install-and-setup/setup/distributed-deployment/deploying-wso2-api-m-in-a-distributed-setup.md
=> [4.3.0] Add heartbeat configs

en/docs/install-and-setup/setup/distributed-deployment/deploying-wso2-api-m-in-a-distributed-setup.md
=> [4.4.0] Add heartbeat configs

en/docs/install-and-setup/setup/distributed-deployment/deploying-wso2-api-m-in-a-distributed-setup.md
=> Add heartbeat configs

en/docs/tutorials/streaming-api/create-and-publish-websocket-api.md
=> [4.4.0] Fix 'Missing image in Create and Publish a WebSocket API page'

en/docs/tutorials/streaming-api/create-and-publish-websocket-api.md
=> Fix 'Missing image in Create and Publish a WebSocket API page'

en/docs/includes/design/invoke-prerelease-api.md
Fixes https://github.com/wso2/docs-apim/issues/6838 in 4.2.0
=> [4.2.0] Fix broken doc links to includes/design/invoke-prerelease-api.md

en/docs/reference/product-apis/overview.md
$Subject
Resolves: https://github.com/wso2/docs-apim/issues/8411
=> [4.2.0] Removed sample postman collection that is not working in the RESTful API document

en/docs/reference/product-apis/overview.md
$Subject
Resolves: https://github.com/wso2/docs-apim/issues/8411
=> [4.0.0] Removed sample postman collection that is not working in the RESTful API document

en/docs/reference/product-apis/overview.md
$Subject
Resolves: https://github.com/wso2/docs-apim/issues/8411
=> [4.1.0] Removed sample postman collection that is not working in the RESTful API document

en/docs/assets/postman-collections/AdminAPI.postman_collection.json, en/docs/assets/postman-collections/DevOpsAPI.postman_collection.json, en/docs/assets/postman-collections/DevPortalAPI.postman_collection.json, en/docs/assets/postman-collections/PublisherAPI.postman_collection.json, en/docs/assets/postman-collections/QuickStart.postman_collection.json, en/docs/reference/product-apis/admin-apis/admin-v4/admin-v4.yaml, en/docs/reference/product-apis/devops-apis/devops-v0/devops-v0.yaml, en/docs/reference/product-apis/devportal-apis/devportal-v3/devportal-v3.yaml, en/docs/reference/product-apis/gateway-apis/gateway-v2/gateway-v2.yaml, en/docs/reference/product-apis/overview.md, en/docs/reference/product-apis/publisher-apis/publisher-v4/publisher-v4.yaml, en/docs/reference/product-apis/service-catalog-apis/service-catalog-v1/service-catalog-v1.yaml
Fixes https://github.com/wso2/docs-apim/issues/8505
Fixes https://github.com/wso2/docs-apim/issues/8497
As discussed offline we have removed `Run in Postman` option and added an option to download the collection scripts directly.
=> [4.4.0] Update Postman Collections

en/docs/assets/postman-collections/AdminAPI.postman_collection.json, en/docs/assets/postman-collections/DevOpsAPI.postman_collection.json, en/docs/assets/postman-collections/DevPortalAPI.postman_collection.json, en/docs/assets/postman-collections/PublisherAPI.postman_collection.json, en/docs/assets/postman-collections/QuickStart.postman_collection.json, en/docs/reference/product-apis/admin-apis/admin-v4/admin-v4.yaml, en/docs/reference/product-apis/devops-apis/devops-v0/devops-v0.yaml, en/docs/reference/product-apis/devportal-apis/devportal-v3/devportal-v3.yaml, en/docs/reference/product-apis/gateway-apis/gateway-v2/gateway-v2.yaml, en/docs/reference/product-apis/overview.md, en/docs/reference/product-apis/publisher-apis/publisher-v4/publisher-v4.yaml, en/docs/reference/product-apis/service-catalog-apis/service-catalog-v1/service-catalog-v1.yaml
As discussed offline, we have removed Run in Postman option and added an option to download the collection scripts directly.
=> [Master] Update Postman Collections

en/docs/design/api-monetization/monetizing-an-api.md, en/docs/install-and-setup/setup/distributed-deployment/product-profiles.md, en/docs/install-and-setup/setup/setting-up-databases/changing-default-databases/changing-to-mysql.md
=> Mention the tested MySQL Java Connector version

en/docs/design/api-monetization/monetizing-an-api.md, en/docs/install-and-setup/setup/distributed-deployment/product-profiles.md, en/docs/install-and-setup/setup/setting-up-databases/changing-default-databases/changing-to-mysql.md
=> [4.4.0] Mention the tested MySQL Java Connector version

en/docs/design/api-monetization/monetizing-an-api.md, en/docs/install-and-setup/setup/distributed-deployment/product-profiles.md, en/docs/install-and-setup/setup/setting-up-databases/changing-default-databases/changing-to-mysql.md
=> [4.3.0] Mention the tested MySQL Java Connector version

en/docs/design/api-monetization/monetizing-an-api.md, en/docs/install-and-setup/setup/distributed-deployment/product-profiles.md, en/docs/install-and-setup/setup/setting-up-databases/changing-default-databases/changing-to-mysql.md
=> [4.1.0] Mention the tested MySQL Java Connector version

en/docs/design/api-monetization/monetizing-an-api.md, en/docs/install-and-setup/setup/distributed-deployment/product-profiles.md, en/docs/install-and-setup/setup/setting-up-databases/changing-default-databases/changing-to-mysql.md
=> [4.0.0] Mention the tested MySQL Java Connector version

en/docs/administer/managing-users-and-roles/managing-user-stores/configure-primary-user-store/configuring-a-read-only-ldap-user-store.md, en/docs/administer/managing-users-and-roles/managing-user-stores/configure-primary-user-store/configuring-a-read-write-active-directory-user-store.md, en/docs/administer/managing-users-and-roles/managing-user-stores/configure-primary-user-store/configuring-a-read-write-ldap-user-store.md, en/docs/administer/managing-users-and-roles/managing-user-stores/configure-primary-user-store/configuring-the-primary-user-store.md
=> [APIM 4.4.0] Fixes primary user store related issues

.github/CODEOWNERS, CODEOWNERS
=> Add CODEOWNERS

en/docs/reference/customize-product/customizations/overriding-the-publisher-portal-theme.md
$Subject
Resolves: https://github.com/wso2/docs-apim/issues/8407
=> Corrected file location in Overriding the Publisher Portal Theme document

en/docs/reference/customize-product/customizations/overriding-the-publisher-portal-theme.md
$Subject
Resolves: https://github.com/wso2/docs-apim/issues/8407
=> [4.2.0] Corrected file location in Overriding the Publisher Portal Theme document

en/docs/reference/customize-product/customizations/overriding-the-publisher-portal-theme.md
$Subject
Resolves: https://github.com/wso2/docs-apim/issues/8407
=> [4.4.0] Corrected file location in Overriding the Publisher Portal Theme document

en/docs/administer/managing-users-and-roles/managing-user-stores/configure-primary-user-store/configuring-a-read-write-ldap-user-store.md, en/docs/administer/managing-users-and-roles/managing-user-stores/configure-primary-user-store/configuring-the-primary-user-store.md
Relates to https://github.com/wso2/docs-apim/pull/8601
=> [APIM 4.4.0] Fix typo in Primary userstore doc

en/docs/administer/managing-users-and-roles/managing-user-stores/configure-primary-user-store/configuring-a-read-only-ldap-user-store.md, en/docs/administer/managing-users-and-roles/managing-user-stores/configure-primary-user-store/configuring-a-read-write-active-directory-user-store.md, en/docs/administer/managing-users-and-roles/managing-user-stores/configure-primary-user-store/configuring-a-read-write-ldap-user-store.md, en/docs/administer/managing-users-and-roles/managing-user-stores/configure-primary-user-store/configuring-the-primary-user-store.md
=> [APIM 4.3.0] Fixes primary user store related issues

en/docs/administer/managing-users-and-roles/managing-user-stores/configure-primary-user-store/configuring-the-primary-user-store.md
Relates to https://github.com/wso2/docs-apim/issues/8439
=> [APIM 4.4.0] Fix broken doc links

en/docs/administer/managing-users-and-roles/managing-user-stores/configure-primary-user-store/configuring-a-read-only-ldap-user-store.md, en/docs/administer/managing-users-and-roles/managing-user-stores/configure-primary-user-store/configuring-a-read-write-active-directory-user-store.md, en/docs/administer/managing-users-and-roles/managing-user-stores/configure-primary-user-store/configuring-a-read-write-ldap-user-store.md, en/docs/administer/managing-users-and-roles/managing-user-stores/configure-primary-user-store/configuring-the-primary-user-store.md
=> Fixes primary user store related issues

en/docs/deploy-and-publish/deploy-on-gateway/api-gateway/passing-enduser-attributes-to-the-backend-via-api-gateway.md
=> Fix imports in Custom JWT Generator code 

en/docs/deploy-and-publish/deploy-on-gateway/api-gateway/passing-enduser-attributes-to-the-backend-via-api-gateway.md
Fixes https://github.com/wso2/docs-apim/issues/8542 in 4.4.0 doc space.
=> [4.4.0] Fix imports in Custom JWT Generator code

en/docs/deploy-and-publish/deploy-on-gateway/api-gateway/passing-enduser-attributes-to-the-backend-via-api-gateway.md
Fixes #8542 in 4.3.0 doc space.
=> [4.3.0] Fix imports in Custom JWT Generator code

en/docs/administer/managing-users-and-roles/managing-user-stores/configure-primary-user-store/configuring-a-read-only-ldap-user-store.md, en/docs/administer/managing-users-and-roles/managing-user-stores/configure-primary-user-store/configuring-a-read-write-active-directory-user-store.md, en/docs/administer/managing-users-and-roles/managing-user-stores/configure-primary-user-store/configuring-a-read-write-ldap-user-store.md, en/docs/administer/managing-users-and-roles/managing-user-stores/configure-primary-user-store/configuring-the-primary-user-store.md
=> [APIM 4.0.0] Fixes primary user store related issues

en/docs/administer/managing-users-and-roles/managing-user-stores/configure-primary-user-store/configuring-a-read-only-ldap-user-store.md, en/docs/administer/managing-users-and-roles/managing-user-stores/configure-primary-user-store/configuring-a-read-write-active-directory-user-store.md, en/docs/administer/managing-users-and-roles/managing-user-stores/configure-primary-user-store/configuring-a-read-write-ldap-user-store.md, en/docs/administer/managing-users-and-roles/managing-user-stores/configure-primary-user-store/configuring-the-primary-user-store.md
=> [APIM 4.1.0] Fixes primary user store related issues

en/docs/assets/versions.json
=> Add 4.4.0 to docs

en/docs/install-and-setup/setup/mi-setup/observability/observability-with-grafana-overview.md
> Fix: https://github.com/wso2/docs-apim/issues/8287
=> Fix MI Observability title

en/docs/design/api-monetization/monetizing-an-api.md
> Fix: https://github.com/wso2/docs-apim/issues/8480
=> Fix hostname and port references

en/docs/reference/customize-product/customizations/overriding-the-publisher-portal-theme.md, en/mkdocs.yml
1. Corrected file location in Overriding the Publisher Portal Theme document.
Resolves : https://github.com/wso2/docs-apim/issues/8407
2. Added missing document for "Monitor Integration Transaction Counts"
Resolves: https://github.com/wso2/docs-apim/issues/8322
=> [4.3.0] Fix Documentation Issues

en/docs/administer/managing-users-and-roles/managing-user-stores/configure-primary-user-store/configuring-a-read-only-ldap-user-store.md, en/docs/administer/managing-users-and-roles/managing-user-stores/configure-primary-user-store/configuring-a-read-write-ldap-user-store.md
Fixes https://github.com/wso2/docs-apim/issues/8602
=> Fix doc issues related to Configuring a Read-Only LDAP User Stores

en/docs/get-started/api-manager-quick-start-guide.md
=> Update Quick Start Guide

en/docs/design/create-api/create-rest-api/create-a-rest-api.md
Fixes https://github.com/wso2/docs-apim/issues/8003
=> Fix Image Overlap UI Issue in Collapsible Items on Larger Screens

en/docs/reference/config-catalog.md, en/tools/config-catalog-generator/data/_http-passthrough-transport-blocking.toml, en/tools/config-catalog-generator/data/_http-passthrough-transport.toml, en/tools/config-catalog-generator/data/configs.json
- Resolves https://github.com/wso2/docs-apim/issues/7857
=> Fix HTTP/S Pass-through Transport blocking mode configurations

en/docs/reference/config-catalog.md, en/tools/config-catalog-generator/data/_http-passthrough-transport-blocking.toml, en/tools/config-catalog-generator/data/_http-passthrough-transport.toml, en/tools/config-catalog-generator/data/configs.json
- Resolves https://github.com/wso2/docs-apim/issues/7857
=> [4.4.0] Fix HTTP/S Pass-through Transport blocking mode configurations

en/docs/reference/config-catalog.md, en/tools/config-catalog-generator/data/_http-passthrough-transport-blocking.toml, en/tools/config-catalog-generator/data/configs.json
- Resolves https://github.com/wso2/docs-apim/issues/7857
=> [4.3.0] Fix HTTP/S Pass-through Transport blocking mode configurations

en/docs/install-and-setup/setup/deployment-best-practices/tuning-performance.md
=> Add case sensitive DB indexes

en/docs/install-and-setup/setup/deployment-best-practices/tuning-performance.md
=> [320] Add case sensitive DB indexes

en/docs/install-and-setup/setup/deployment-best-practices/tuning-performance.md
=> [400] Add case sensitive DB indexes

en/docs/install-and-setup/setup/deployment-best-practices/tuning-performance.md
=> [410] Add case sensitive DB indexes

en/docs/install-and-setup/setup/deployment-best-practices/tuning-performance.md
=> [420] Add case sensitive DB indexes

en/docs/install-and-setup/setup/deployment-best-practices/tuning-performance.md
=> [440] Add case sensitive DB indexes

en/docs/design/api-security/oauth2/grant-types/password-grant.md
$Subject
Resolves: https://github.com/wso2/docs-apim/issues/8459
=> Update response in password grant document

en/docs/design/api-security/oauth2/grant-types/password-grant.md, en/docs/design/create-api/adding-custom-properties-to-apis.md, en/docs/design/create-api/change-api-thumbnail.md, en/docs/design/rate-limiting/adding-new-throttling-policies.md
1. Added a missing step in the Password Grant Documentation.
Resolves: https://github.com/wso2/docs-apim/issues/8459
2. Adding deployment.toml config to make the document clear in the Advanced rate limiting policy document.
Resolves: https://github.com/wso2/docs-apim/issues/8460
3. Removed the 'Design a new API Thumbnail' document since this feature is not available now.
Resolves: https://github.com/wso2/docs-apim/issues/8455
=> [4.4.0] Fix documentation Issues

en/docs/administer/managing-users-and-roles/managing-user-roles.md
$Subject
Resolves: https://github.com/wso2/docs-apim/issues/8375
=> Updated the role scope mapping table 

en/docs/administer/managing-users-and-roles/managing-user-roles.md
$Subject
Resolves: https://github.com/wso2/docs-apim/issues/8375
=> [4.4.0] Updated the role scope mapping table

en/docs/administer/managing-users-and-roles/managing-user-roles.md
$Subject
Resolves: https://github.com/wso2/docs-apim/issues/8375
=> [4.3.0] Updated the role scope mapping table 

en/docs/tutorials/edit-an-api-by-modifyng-the-api-definition.md
=> [4.0.0] Cannot edit vendor extensions

en/docs/tutorials/edit-an-api-by-modifyng-the-api-definition.md
=> [4.1.0] Cannot edit vendor extensions

en/docs/tutorials/edit-an-api-by-modifyng-the-api-definition.md
=> [4.2.0] Cannot edit vendor extensions

en/docs/tutorials/edit-an-api-by-modifyng-the-api-definition.md
=> [4.3.0] Cannot edit vendor extensions

en/docs/tutorials/edit-an-api-by-modifyng-the-api-definition.md
=> [4.4.0] Cannot edit vendor extensions

en/docs/tutorials/edit-an-api-by-modifyng-the-api-definition.md
=> Cannot edit vendor extensions

en/docs/design/create-api/create-rest-api/create-a-rest-api.md
Fixes https://github.com/wso2/docs-apim/issues/8003
=> [APIM 4.4.0] Fix Image Overlap UI Issue in Collapsible Items on Larger Screens

en/docs/administer/managing-users-and-roles/managing-user-stores/configure-primary-user-store/configuring-a-read-only-ldap-user-store.md, en/docs/administer/managing-users-and-roles/managing-user-stores/configure-primary-user-store/configuring-a-read-write-ldap-user-store.md
Fixes https://github.com/wso2/docs-apim/issues/8602
=> [APIM 4.4.0] Fix doc issues related to Configuring a Read-Only LDAP User Stores

en/docs/deploy-and-publish/publish-on-dev-portal/third-party-api-support.md
=> Add a note on limitation of Third party APIs

en/docs/deploy-and-publish/publish-on-dev-portal/third-party-api-support.md
=> [4.3.0] Add a note on limitation of Third party APIs

en/docs/deploy-and-publish/publish-on-dev-portal/third-party-api-support.md
=> [4.2.0] Add a note on limitation of Third party APIs

en/docs/deploy-and-publish/publish-on-dev-portal/third-party-api-support.md
=> [4.1.0] Add a note on limitation of Third party APIs

en/docs/reference/product-apis/publisher-apis/publisher-v2/publisher-v2.yaml
=> [4.0.0] Add AWS Lambda endpoint configs

en/docs/reference/product-apis/publisher-apis/publisher-v3/publisher-v3.yaml
=> [4.1.0] Add AWS Lambda endpoint configs

en/docs/administer/key-managers/configure-wso2is-connector.md
Fixes https://github.com/wso2/docs-apim/issues/8340
=> Update userInfo endpoint in "IS configured as a KM" doc

en/docs/administer/key-managers/configure-wso2is-connector.md
https://github.com/wso2/docs-apim/issues/8340
(cherry picked from commit 87eaaa84a319007a14a1982b6fb96f12c596339c)
=> [4.4.0] Update userInfo endpoint in "IS configured as a KM" doc

en/docs/get-started/api-manager-quick-start-guide.md
- Related to https://github.com/wso2/docs-apim/pull/8711
=> [4.4.0] Update quick start guide

en/docs/integrate/develop/customizations/creating-custom-task-scheduling.md
This is to fix https://github.com/wso2/docs-mi/issues/1085
> Link(s) to product documentation that addresses the changes of …
=> Update backend service

en/docs/learn/consume-api/invoke-apis/invoke-apis-using-tools/invoke-an-api-using-the-integrated-api-console.md
=> [3.0.0] Note about limits of swagger try out

en/docs/learn/consume-api/invoke-apis/invoke-apis-using-tools/invoke-an-api-using-the-integrated-api-console.md
=> [3.1.0] Note about limits of swagger try out

en/docs/learn/consume-api/invoke-apis/invoke-apis-using-tools/invoke-an-api-using-the-integrated-api-console.md
=> [3.2.0] Note about limits of swagger try out

en/docs/consume/invoke-apis/invoke-apis-using-tools/invoke-an-api-using-the-integrated-api-console.md
=> [4.0.0] Note about limits of swagger try out

en/docs/consume/invoke-apis/invoke-apis-using-tools/invoke-an-api-using-the-integrated-api-console.md
=> [4.1.0] Note about limits of swagger try out

en/docs/consume/invoke-apis/invoke-apis-using-tools/invoke-an-api-using-the-integrated-api-console.md
=> [4.2.0] Note about limits of swagger try out

en/docs/consume/invoke-apis/invoke-apis-using-tools/invoke-an-api-using-the-integrated-api-console.md
=> [4.3.0] Note about limits of swagger try out

en/docs/consume/invoke-apis/invoke-apis-using-tools/invoke-an-api-using-the-integrated-api-console.md
=> [4.4.0] Note about limits of swagger try out

en/docs/consume/invoke-apis/invoke-apis-using-tools/invoke-an-api-using-the-integrated-api-console.md
=> Note about limits of swagger try out

en/docs/reference/config-catalog.md, en/tools/config-catalog-generator/data/apim.sync_runtime_artifacts.gateway.toml, en/tools/config-catalog-generator/data/configs.json
=> Update Gateway runtime artifact configs

en/docs/reference/config-catalog.md, en/tools/config-catalog-generator/data/apim.sync_runtime_artifacts.gateway.toml, en/tools/config-catalog-generator/data/configs.json
=> [4.1.0] Update Gateway runtime artifact configs

en/docs/reference/config-catalog.md, en/tools/config-catalog-generator/data/apim.sync_runtime_artifacts.gateway.toml, en/tools/config-catalog-generator/data/configs.json
=> [4.2.0] Update Gateway runtime artifact configs

en/docs/reference/config-catalog.md, en/tools/config-catalog-generator/data/apim.sync_runtime_artifacts.gateway.toml, en/tools/config-catalog-generator/data/configs.json
=> [4.3.0] Update Gateway runtime artifact configs

en/docs/reference/config-catalog.md, en/tools/config-catalog-generator/data/apim.sync_runtime_artifacts.gateway.toml, en/tools/config-catalog-generator/data/configs.json
=> [4.4.0] Update Gateway runtime artifact configs

en/docs/observe/api-manager/monitoring-http-access-logs.md
=> Remove unsupported access log patterns

en/docs/observe/api-manager/monitoring-http-access-logs.md
=> [4.4.0] Remove unsupported access log patterns

en/docs/observe/api-manager/monitoring-http-access-logs.md
=> [4.3.0] Remove unsupported access log patterns

en/docs/observe/api-manager/monitoring-http-access-logs.md
=> [4.2.0] Remove unsupported access log patterns

en/docs/observe/api-manager/monitoring-http-access-logs.md
=> [4.1.0] Remove unsupported access log patterns

en/docs/observe/api-manager/monitoring-http-access-logs.md
=> [4.0.0] Remove unsupported access log patterns

en/docs/includes/deploy/steps-to-deploy-apim-in-a-distributed-setup-with-km-separation.md
=> [4.4.0] Fix config issues in km profile docs

en/docs/deploy-and-publish/deploy-on-gateway/api-gateway/passing-enduser-attributes-to-the-backend-via-api-gateway.md
=> [4.0.0] Remove apim.jwt.convert_dialect config

en/docs/deploy-and-publish/deploy-on-gateway/api-gateway/passing-enduser-attributes-to-the-backend-via-api-gateway.md
=> [4.1.0] Remove apim.jwt.convert_dialect config

en/docs/deploy-and-publish/deploy-on-gateway/api-gateway/passing-enduser-attributes-to-the-backend-via-api-gateway.md
=> [4.3.0] Remove apim.jwt.convert_dialect config

en/docs/deploy-and-publish/deploy-on-gateway/api-gateway/passing-enduser-attributes-to-the-backend-via-api-gateway.md
=> [4.4.0] Remove apim.jwt.convert_dialect config

en/docs/deploy-and-publish/deploy-on-gateway/api-gateway/passing-enduser-attributes-to-the-backend-via-api-gateway.md
=> Remove apim.jwt.convert_dialect config

en/docs/includes/design/additional-api-key.md, en/docs/includes/design/create-publish-api.md, en/docs/includes/design/generate-api-key.md, en/docs/includes/design/invoke-mtls-api-using-postman.md
=> Fix image links

en/docs/api-analytics/on-prem/datadog-installation-guide.md, en/mkdocs.yml
- Resolves https://github.com/wso2/docs-apim/issues/7965
=> Fix Datadog Configuration

en/docs/api-analytics/on-prem/datadog-installation-guide.md
- Resolves https://github.com/wso2/docs-apim/issues/7965
=> [4.4.0] Fix Datadog Configuration

en/docs/api-analytics/on-prem/datadog-installation-guide.md
- Resolves https://github.com/wso2/docs-apim/issues/7965
=> [4.2.0] Fix Datadog Configuration

en/docs/troubleshooting/utilizing-runtime-diagnostic-tool.md, en/mkdocs.yml
- Resolves https://github.com/wso2/docs-apim/issues/8768
=> [4.4.0] Include Runtime diagnostic tool guide

en/docs/includes/deploy/steps-to-deploy-apim-in-a-distributed-setup-with-km-separation.md
=> Fix config issues in km profile docs

en/docs/administer/managing-users-and-roles/managing-user-stores/writing-a-custom-user-store-manager.md
Fixes #7986 in 4.4.0 doc space
=> [4.4.0] Fix logger in sample code

en/docs/reference/customize-product/extending-api-manager/extending-key-management/extending-scope-validation.md
=> [4.0.0] Fix configs for extending scope validation

en/docs/reference/customize-product/extending-api-manager/extending-key-management/extending-scope-validation.md
=> [4.1.0] Fix configs for extending scope validation

en/docs/reference/customize-product/extending-api-manager/extending-key-management/extending-scope-validation.md
=> [4.2.0] Fix configs for extending scope validation

en/docs/reference/customize-product/extending-api-manager/extending-key-management/extending-scope-validation.md
=> [4.3.0] Fix configs for extending scope validation

en/docs/reference/customize-product/extending-api-manager/extending-key-management/extending-scope-validation.md
=> [4.4.0] Fix configs for extending scope validation

en/docs/reference/customize-product/extending-api-manager/extending-key-management/extending-scope-validation.md
=> Fix configs for extending scope validation

en/docs/install-and-setup/setup/distributed-deployment/configuring-wso2-identity-server-as-a-key-manager.md
=> [4.1.0] Add keystore configuring steps

en/docs/reference/product-apis/publisher-apis/publisher-v2/publisher-v2.yaml
=> [4.0.0] Update apiId-Q description

en/docs/reference/product-apis/publisher-apis/publisher-v3/publisher-v3.yaml
=> [4.1.0] Update apiId-Q description

en/docs/reference/product-apis/publisher-apis/publisher-v4/publisher-v4.yaml
=> [4.2.0] Update apiId-Q description

en/docs/reference/product-apis/publisher-apis/publisher-v4/publisher-v4.yaml
=> [4.3.0] Update apiId-Q description

en/docs/reference/product-apis/publisher-apis/publisher-v4/publisher-v4.yaml
=> [4.4.0] Update apiId-Q description

en/docs/reference/product-apis/publisher-apis/publisher-v4/publisher-v4.yaml
=> Update apiId-Q description

en/docs/reference/product-apis/devportal-apis/devportal-v3/devportal-v3.yaml
To add documentation changes for generating the SecuritySchema of the Swagger using real Key Manager information
Fixes doc improvements: https://github.com/wso2/api-manager/issues/3044
=> Add doc changes for generating the SecuritySchema of the Swagger using real Key Manager information

en/docs/install-and-setup/setup/setting-up-databases/managing-data-growth-and-improving-performance.md
Fixes https://github.com/wso2/docs-apim/issues/7959 for APIM 4.0.0
=> [APIM 4.0.0] Add Missing registry cleanup DB scripts

en/docs/install-and-setup/setup/setting-up-databases/managing-data-growth-and-improving-performance.md
Fixes https://github.com/wso2/docs-apim/issues/7959 for APIM 4.2.0
=> [APIM 4.2.0] Add Missing registry cleanup DB scripts

en/docs/design/api-policies/create-policy.md
=> Add not supported sequence warning

en/docs/install-and-setup/setup/setting-up-databases/managing-data-growth-and-improving-performance.md
Fixes https://github.com/wso2/docs-apim/issues/7959 for APIM 4.1.0
=> [APIM 4.1.0] Add Missing registry cleanup DB scripts

en/docs/design/api-policies/create-policy.md
=> [4.4.0] Add not supported sequence warning

en/docs/design/api-policies/create-policy.md
=> [4.3.0] Add not supported sequence warning

en/docs/design/api-policies/create-policy.md
=> [4.2.0] Add not supported sequence warning

en/docs/design/api-policies/create-policy.md
=> [4.1.0] Add not supported sequence warning

en/docs/reference/customize-product/extending-api-manager/saml2-sso/configuring-identity-server-as-idp-for-sso.md
=> Add note before configuring saml sso

en/docs/reference/customize-product/extending-api-manager/saml2-sso/configuring-identity-server-as-idp-for-sso.md
=> [APIM 4.4.0] Add note before configuring saml sso

en/docs/reference/customize-product/extending-api-manager/saml2-sso/configuring-identity-server-as-idp-for-sso.md
=> [APIM 4.3.0] Add note before configuring saml sso

en/docs/reference/customize-product/extending-api-manager/saml2-sso/configuring-identity-server-as-idp-for-sso.md
=> [APIM 4.2.0] Add note before configuring saml sso

en/docs/reference/customize-product/extending-api-manager/saml2-sso/configuring-identity-server-as-idp-for-sso.md
=> [APIM 4.1.0] Add note before configuring saml sso

en/docs/reference/customize-product/extending-api-manager/saml2-sso/configuring-identity-server-as-idp-for-sso.md
=> [APIM 4.0.0] Add note before configuring saml sso

en/docs/develop/extending-api-manager/saml2-sso/configuring-identity-server-as-idp-for-sso.md
=> [APIM 3.2.0] Add note before configuring saml sso

en/docs/deploy-and-publish/deploy-on-gateway/api-gateway/threat-protectors/regular-expression-threat-protection-for-api-gateway.md
Fixes https://github.com/wso2/docs-apim/issues/7960 and https://github.com/wso2/docs-apim/issues/7722 in 4.4.0 doc space.
=> Fix regex in gateway threat protection doc

en/docs/deploy-and-publish/deploy-on-gateway/api-gateway/threat-protectors/regular-expression-threat-protection-for-api-gateway.md
Fixes https://github.com/wso2/docs-apim/issues/7960 and https://github.com/wso2/docs-apim/issues/7722 in 4.3.0 doc space.
=> [4.3.0] Fix regex in gateway threat protection doc

en/docs/deploy-and-publish/deploy-on-gateway/api-gateway/threat-protectors/regular-expression-threat-protection-for-api-gateway.md
Fixes #7722 in 4.2.0 doc space.
Other related PR : https://github.com/wso2/docs-apim/pull/7730
=> [4.2.0] Fix regex for XPath Injection

en/docs/design/api-security/api-request-response-schema-validation/json-schema-validator.md
- Fixes https://github.com/wso2/docs-apim/issues/7964
- Updates the Petstore schema URL as it had to been moved to a new location in OpenAPI-Specification repo.
=> [4.4.0] Add note on additionalProperties

en/docs/install-and-setup/setup/reference/product-compatibility.md, en/docs/reference/guides/message-flow-in-the-api-manager-gateway.md
01. Fix the broken link in mediation-extensions document.
Resolves: https://github.com/wso2/docs-apim/issues/8278
=> [Master] Fix Documentation Issues

en/mkdocs.yml
=> [4.3.0] Add regex for search configurations

en/mkdocs.yml
=> [4.4.0] Add regex for search configurations

en/mkdocs.yml
=> Add regex for search configurations

en/mkdocs.yml
=> [4.2.0] Add regex for search configurations

en/mkdocs.yml
=> [4.1.0] Add regex for search configurations

en/mkdocs.yml
=> [4.0.0] Add regex for search configurations

en/mkdocs.yml
=> [3.0.0] Add regex for search configurations

en/mkdocs.yml
=> [3.2.0] Add regex for search configurations

en/docs/design/advanced-topics/enable-publisher-access-control-in-api-publisher-portal.md
(cherry picked from commit 2f33846b4a38c4c5210db1c0382a0665b62fff49)
=> [APIM 4.4.0] Add note about the case insensitivity of publisher access control roles

en/docs/design/advanced-topics/enable-publisher-access-control-in-api-publisher-portal.md
=> Add note about the case insensitivity of publisher access control roles

en/docs/design/advanced-topics/enable-publisher-access-control-in-api-publisher-portal.md
(cherry picked from commit 2f33846b4a38c4c5210db1c0382a0665b62fff49)
=> [APIM 4.3.0] Add note about the case insensitivity of publisher access control roles

en/docs/design/advanced-topics/enable-publisher-access-control-in-api-publisher-portal.md
(cherry picked from commit 2f33846b4a38c4c5210db1c0382a0665b62fff49)
=> [APIM 4.2.0] Add note about the case insensitivity of publisher access control roles

en/docs/design/advanced-topics/enable-publisher-access-control-in-api-publisher-portal.md
=> [APIM 4.0.0] Add note about the case insensitivity of publisher access control roles

en/docs/design/create-api/create-streaming-api/create-a-sse-streaming-api.md, en/docs/design/create-api/create-streaming-api/create-a-streaming-api-from-an-asyncapi-definition.md, en/docs/design/create-api/create-streaming-api/create-a-websocket-streaming-api.md, en/docs/design/create-api/create-streaming-api/create-a-websub-streaming-api.md, en/docs/design/create-api/create-streaming-api/streaming-api-overview.md, en/docs/design/create-api/create-streaming-api/test-a-websub-api.md, en/docs/includes/design/stream-more-links.md, en/docs/integrate/develop/working-with-service-catalog.md, en/docs/tutorials/streaming-api/create-and-publish-sse-api.md, en/docs/tutorials/streaming-api/create-and-publish-websocket-api.md, en/docs/tutorials/streaming-api/create-and-publish-websub-api.md, en/docs/use-cases/streaming-usecase/exposing-stream-as-managed-api-in-service-catalog.md, en/mkdocs.yml
Fixes https://github.com/wso2/docs-apim/issues/8817
=> [APIM 4.4.0] Fix broken links related to SI and MI

en/docs/reference/product-apis/publisher-apis/publisher-v3/publisher-v3.yaml
>  Fix description for endpoint config
=> Fix description for endpoint config

en/docs/install-and-setup/setup/reference/product-compatibility.md
=> [3.2.0] Update product compatibility matrix

en/docs/install-and-setup/setup/reference/product-compatibility.md
=> [4.0.0] Update product compatibility matrix

en/docs/install-and-setup/setup/reference/product-compatibility.md
=> [4.1.0] Update product compatibility matrix

en/docs/install-and-setup/setup/reference/product-compatibility.md
=> [4.2.0] Update product compatibility matrix

en/docs/design/api-security/oauth2/multiple-active-access-tokens.md, en/mkdocs.yml
=> Add multiple-active-access-tokens documentation

en/docs/design/api-security/oauth2/multiple-active-access-tokens.md, en/mkdocs.yml
=> [APIM 4.4.0] Add multiple-active-access-tokens documentation

en/docs/design/api-security/oauth2/multiple-active-access-tokens.md, en/mkdocs.yml
=> [APIM 4.2.0] Add multiple-active-access-tokens documentation

en/docs/design/api-security/oauth2/multiple-active-access-tokens.md, en/mkdocs.yml
=> [APIM 4.0.0] Add multiple-active-access-tokens documentation

en/docs/design/api-security/oauth2/multiple-active-access-tokens.md, en/mkdocs.yml
=> [APIM 4.1.0] Add multiple-active-access-tokens documentation

en/docs/administer/multitenancy/configuring-the-tenant-loading-policy.md
Fixes https://github.com/wso2/docs-apim/issues/8081
=> Add documentation for on-demand loading

en/docs/install-and-setup/install/installing-the-product/installing-api-m-as-a-windows-service.md
=> [4.0.0] Add logs to avoid log overwriting

en/docs/administer/multitenancy/configuring-the-tenant-loading-policy.md
Fixes https://github.com/wso2/docs-apim/issues/8081
=> [APIM 4.0.0] Add documentation for on-demand loading

en/docs/administer/multitenancy/configuring-the-tenant-loading-policy.md
Fixes https://github.com/wso2/docs-apim/issues/8081
=> [APIM 4.3.0] On demand loading fix 4.3.0

en/docs/install-and-setup/install/installation-options.md
Fixes https://github.com/wso2/docs-apim/issues/7941
=> [APIM 4.3.0] Installation doc update 4.3.0

en/docs/install-and-setup/setup/security/logins-and-passwords/working-with-encrypted-passwords.md
=> Remove vault-lookup example

en/docs/reference/customize-product/customizations/customizing-the-developer-portal/enabling-or-disabling-self-signup.md
=> Add EnableEmailNotification parameter

en/docs/install-and-setup/setup/mi-setup/brokers/configure-with-weblogic.md
Fixes https://github.com/wso2/docs-mi/issues/961
=> Update Web Logic server setup guide for WSO2 MI

en/docs/install-and-setup/setup/distributed-deployment/configuring-wso2-identity-server-as-a-key-manager.md
=> Add instructions to disable token exchange grant type for IS as KM

en/docs/reference/product-apis/devportal-apis/devportal-v3/devportal-v3.yaml
=> Update description on using groupId

en/docs/tutorials/integrating-with-solace.md
=> [4.1.0] Note on Solace not supporting

en/docs/tutorials/integrating-with-solace.md
=> [4.2.0] Note on Solace not supporting

en/docs/tutorials/integrating-with-solace.md
=> [4.3.0] Note on Solace not supporting

en/docs/tutorials/integrating-with-solace.md
=> [4.4.0] Note on Solace not supporting

en/docs/tutorials/integrating-with-solace.md
=> Note on Solace not supporting

en/docs/install-and-setup/install/installation-options.md
Fixes https://github.com/wso2/docs-apim/issues/7941
=> [APIM 4.4.0] Update installation options doc

en/docs/install-and-setup/install/installation-options.md
Fixes https://github.com/wso2/docs-apim/issues/7941
=> Update installation options doc

en/docs/install-and-setup/install/installation-options.md
Fixes https://github.com/wso2/docs-apim/issues/7941
=> [APIM 4.3.0] Update installation options doc

en/docs/learn/tutorials/edit-an-api-by-modifyng-the-api-definition.md
=> Note on advanced swagger validation

en/docs/reference/guides/message-flow-in-the-api-manager-gateway.md
01. Fix the broken link in mediation-extensions document.
Resolves: https://github.com/wso2/docs-apim/issues/8278
=> [4.2.0] Fix Documentation Issues

en/docs/design/rate-limiting/introducing-throttling-use-cases.md
=> Add note regarding throttling slippage

en/docs/install-and-setup/setup/deployment-best-practices/performance-tests-results.md
Updated the specs according to [1]
[1] https://aws.amazon.com/ec2/instance-types/c5/
=> Fix instances' specs in performance tests

en/docs/administer/key-managers/configure-global-key-manager.md
=> Limitations in global key manager

en/docs/install-and-setup/setup/setting-up-databases/changing-default-databases/changing-to-mysql.md
=> Add primary keys in MB_STORE_DB

en/docs/reference/mediators/enrich-mediator.md
$subject
Fixes https://github.com/wso2/docs-mi/issues/1142.
=> [4.2.0] Update property name

en/docs/reference/mediators/enrich-mediator.md
$subject
Fixes https://github.com/wso2/docs-mi/issues/1142.
=> [4.1.0] Update property name

en/docs/reference/mediators/enrich-mediator.md
$subject
Fixes https://github.com/wso2/docs-mi/issues/1142.
=> [4.0.0] Update property name

en/docs/administer/logging-and-monitoring/monitoring/monitoring-server-health.md
=> [4.3.0] Fix health check docs

en/docs/integrate/develop/generate-docker-image.md
This PR is to fix the missing link.
=> [4.2.0] Fix missing link

en/docs/get-started/integration-quick-start-guide.md
This PR is to fix a formatting issue.
This will fix https://github.com/wso2/docs-apim/issues/7449.
=> [4.0.0] Fix formatting

en/docs/install-and-setup/setup/setting-up-proxy-server-and-the-load-balancer/configuring-the-proxy-server-and-the-load-balancer.md
Fixed a spelling error in the documentation where "ngnix.conf" was incorrectly spelled as "nginx.conf" This commit ensures consistency and accuracy in the software's name.
> Brief description of the new feature or …
=> Fix typos in documentation

en/docs/integrate/develop/generate-docker-image.md
This PR is to fix the missing link.
=> [4.1.0] Fix missing link

en/docs/integrate/develop/generate-docker-image.md
This PR is to fix the missing link.
=> [4.0.0] Fix missing link

en/docs/install-and-setup/setup/reference/product-compatibility.md
=> Add note on WSO2 product reliability on the tested JDK

en/docs/install-and-setup/setup/reference/product-compatibility.md
=> Remove unnecessary example

en/docs/administer/logging-and-monitoring/monitoring/monitoring-server-health.md
=> Add missing health-check config

en/docs/consume/discover-apis/marketplace-assistant.md, en/docs/install-and-setup/setup/api-controller/ai-related-operations-with-apictl.md, en/mkdocs.yml
Adding changes from [1] to 4.4.0 branch.
1. https://github.com/wso2/docs-apim/pull/7988
=> [4.4.0] Add FAQ and AI-related APICTL commands for Marketplace Assistant

en/docs/consume/discover-apis/marketplace-assistant.md, en/docs/install-and-setup/setup/api-controller/ai-related-operations-with-apictl.md
- Minor formatting fixes and restructuring to https://github.com/wso2/docs-apim/pull/7988
=> Minor fixes for Marketplace Assistant related docs

en/docs/design/api-security/api-authentication/secure-apis-using-mutual-ssl.md
- $subject
- Related issues: https://github.com/wso2/api-manager/issues/873
=> [4.0.0] Add certificate chain validation configuration to MutualSSL docs

en/docs/deploy-and-publish/deploy-on-gateway/api-gateway/api-gateways-with-dedicated-backends.md
Fixes: https://github.com/wso2/docs-apim/issues/8979
=> Fix duplicate path in redirect url

en/docs/install-and-setup/setup/mi-setup/message_builders_formatters/message-relay.md
This PR is to add the missing content.
Fixes https://github.com/wso2/docs-mi/issues/904.
=> [4.2.0] Update message-relay.md

en/docs/install-and-setup/setup/mi-setup/message_builders_formatters/message-relay.md
This PR is to add the missing content.
Fixes https://github.com/wso2/docs-mi/issues/904.
=> [4.1.0] Update message-relay.md

en/docs/install-and-setup/setup/mi-setup/message_builders_formatters/message-relay.md
This PR is to add the missing content.
Fixes https://github.com/wso2/docs-mi/issues/904.
=> [4.0.0] Update message-relay.md

en/docs/observe/api-manager/monitoring-websocket-logs.md, en/mkdocs.yml
Docs for the feature introduced via [1]
[1] https://github.com/wso2-enterprise/wso2-apim-internal/issues/7559
=> Add docs for the feature of websocket access logs

en/docs/reference/synapse-properties/transport-parameters/rabbitmq-transport-parameters.md
This PR is to add RabbitMQ publisher confirms support.
Fixes https://github.com/wso2/docs-mi/issues/1204.
=> [4.2.0] Update rabbitmq-transport-parameters.md

en/docs/reference/synapse-properties/transport-parameters/rabbitmq-transport-parameters.md
This PR is to add RabbitMQ publisher confirms support.
Fixes https://github.com/wso2/docs-mi/issues/1204.
=> [4.0.0] Update rabbitmq-transport-parameters.md

en/docs/integrate/develop/customizations/creating-synapse-handlers.md
This PR is to fix a formatting issue.
=> [4.1.0] Fix formatting

en/docs/reference/mediators/xslt-mediator.md
This PR is to add a note on optimizing the XSLT mediator.
Fixes https://github.com/wso2/docs-mi/issues/1217.
=> [4.2.0] Update xslt-mediator.md

en/docs/reference/mediators/xslt-mediator.md
This PR is to add a note on optimizing the XSLT mediator.
Fixes https://github.com/wso2/docs-mi/issues/1217.
=> [4.1.0] Update xslt-mediator.md

en/docs/reference/mediators/xslt-mediator.md
This PR is to add a note on optimizing the XSLT mediator.
Fixes https://github.com/wso2/docs-mi/issues/1217.
=> [4.0.0] Update xslt-mediator.md

en/docs/deploy-and-publish/deploy-on-gateway/choreo-connect/message-transformation/interceptor-microservice/interceptor-microservice.md, en/docs/deploy-and-publish/deploy-on-gateway/choreo-connect/message-transformation/interceptor-microservice/request-flow-interceptor.md
Add documentation for path rewrite feature.
=> Add documentation for path rewrite

en/docs/assets/css/theme.css, en/mkdocs.yml, en/theme/material/partials/header.html
- This PR will prepare the APIM 4.5.0 doc space by changing the version number in the relevant space
- This PR will also add the WIP banner
=> Prepare APIM 4.5.0 Doc Space

en/docs/install-and-setup/setup/mi-setup/brokers/configure-with-rabbitmq.md
$subject
Ports: https://github.com/wso2/docs-mi/pull/1081
=> Add rabbitMQ proxy level throttling

en/docs/deploy-and-publish/deploy-on-gateway/federated-gateways/deploy-on-aws-api-gateway.md, en/mkdocs.yml
- Adds initial docs for federated gateway support
=> Add docs for Federated Gateways

en/docs/administer/multiple-gateways/configure-gateway-visibility.md, en/docs/administer/multiple-gateways/configure-gateway.md
=> Firx formatting issues

en/docs/administer/multiple-gateways/configure-gateway.md, en/docs/deploy-and-publish/deploy-on-gateway/deploy-api/deploy-through-multiple-api-gateways.md
=> Fix non-rendered images

en/docs/administer/multiple-gateways/configure-gateway.md
=> Fix image loading issue

en/docs/design/lifecycle-management/customize-api-life-cycle.md
=> Remove extending lifecycle doc reference

en/docs/reference/mediators/iterate-mediator.md
$subject to fix https://github.com/wso2/docs-mi/issues/1398
> Link(s) to product documentation that addresses the changes of …
=> Add iterate mediator clonning info

en/docs/reference/mediators/iterate-mediator.md
$subject to fix https://github.com/wso2/docs-mi/issues/1398 …
=> Add iterate mediator clonning info 

en/docs/install-and-setup/setup/mi-setup/brokers/configure-with-rabbitmq.md
$subject
Issue reference: https://github.com/wso2/docs-mi/issues/1346
=> [4.1.0] Add RabbitMQ throttling parameters

en/docs/administer/key-managers/configure-wso2is7-connector.md
$Subject - porting https://github.com/wso2/docs-apim/pull/9003 to 4.5.0
=> Add docs about optional role creation

en/docs/reference/governance/wso2-api-management-guidelines.md, en/docs/reference/governance/wso2-rest-api-design-guidelines.md, en/mkdocs.yml
> Adding reference documentation to describe the default governance rulesets.
=> Add reference documentation for the default governance rulesets

en/docs/design/b2b-api-management/setup-identity-server.md
Config to resolve https://github.com/wso2/api-manager/issues/3761
=> Add config to keymanager config

en/docs/install-and-setup/setup/api-controller/getting-started-with-wso2-api-controller.md
Add build artefacts for APICTL 4.4.1
https://github.com/wso2-enterprise/wso2-apim-internal/issues/8632
=> Add artifacts for APICTL 4.4.1

en/docs/reference/governance/owasp-top-10.md, en/mkdocs.yml
> Adding reference documentation to describe the OWASP Top 10 ruleset.
=> AddAdd reference documentation for the OWASP Top 10 ruleset

en/docs/reference/apictl/wso2-api-controller.md
> Add a deprecation message for MI commands and a reference to the MI CLI docs.
=> Add deprecation message for mi commands

en/docs/administer/ai-vendors/claude-as-a-custom-vendor.md
=> Improve wording on claude doc

en/docs/reference/faq.md
=> [3.2.0] Remove Openshift and Mesos from the docs

en/docs/reference/faq.md
=> [4.0.0] Remove Openshift and Mesos from the docs

en/docs/reference/faq.md
=> [4.1.0] Remove Openshift and Mesos from the docs

en/docs/reference/faq.md
=> [4.2.0] Remove Openshift and Mesos from the docs

en/docs/reference/faq.md
=> [4.3.0] Remove Openshift and Mesos from the docs

en/docs/reference/faq.md
=> [4.4.0] Remove Openshift and Mesos from the docs

README.md, en/docs/get-started/about-this-release.md, en/docs/includes/compatibility-matrix.md
- This PR updates the About this Release section of the docs for 4.5.0 release
=> [4.5.0] Update about this release doc for 4.5.0

en/docs/get-started/about-this-release.md
- Remove unnecessary topics from "About this Release" page
=> Remove Unnecessary Topics from "About this Release" Page

en/docs/reference/product-apis/overview.md
- Add Governance API to REST API Overview description
=> Add Governance API to REST API Overview Description

en/docs/assets/versions.json
=> Add 4.5.0 doc links

en/docs/deploy-and-publish/deploy-on-gateway/federated-gateways/deploy-on-aws-api-gateway.md
=> [4.5.0] Add note on Lambda Invoke Role

en/docs/index.md
This PR fixes the following broken links in the home page.
1. Deploy on Kubernetes
2. SaaS
=> Fix broken links in home page

en/docs/index.md
This PR adds the bijira link to saas in homepage
=> Add bijira link to saas in homepage

en/docs/install-and-setup/setup/api-controller/getting-started-with-wso2-api-controller.md
=> Update APICTL 4.1.5 artifacts

en/docs/get-started/about-this-release.md
=> Fix 404 page issue for Multi-Model Routing Support for AI APIs

en/docs/install-and-setup/setup/api-controller/managing-apis-api-products/migrating-apis-to-different-environments.md, en/docs/reference/product-apis/publisher-apis/publisher-v4/publisher-v4.yaml
=> [4.3.0] Document preserveCredentials parameter in REST API and --preserve-credentials flag in APICTL

en/docs/install-and-setup/setup/api-controller/cicd-using-cli.md, en/docs/install-and-setup/setup/api-controller/enabling-correlation-logs-with-apictl.md, en/docs/install-and-setup/setup/api-controller/getting-started-with-wso2-api-controller.md, en/docs/install-and-setup/setup/api-controller/managing-apis-api-products/managing-apis-and-api-products.md, en/docs/install-and-setup/setup/api-controller/managing-applications/managing-applications.md
=> Add changes for APICTL 4.2.6 release

en/docs/reference/mediators/property-reference/http-transport-properties.md
- Update description of HTTP transport property FORCE_SC_ACCEPTED
=> Update description of HTTP transport property FORCE_SC_ACCEPTED

en/docs/reference/product-apis/devportal-apis/devportal-v3/devportal-v3.yaml
=> Updated docs for DevPortal REST APIs

en/docs/reference/connectors/file-connector/file-connector-config.md
$subject
Issue - https://github.com/wso2-enterprise/wso2-mi-internal/issues/1609
=> Add SMB  configurations to File Connector

en/docs/install-and-setup/setup/mi-setup/brokers/configure-with-rabbitmq.md, en/docs/install-and-setup/setup/mi-setup/performance_tuning/rabbitmq_transport_tuning.md, en/docs/reference/config-catalog-mi.md, en/docs/reference/synapse-properties/transport-parameters/rabbitmq-transport-parameters.md
Update RabbitMQ sender and listener config catalog docs
Fixes: https://github.com/wso2/docs-mi/issues/1503
=> Update RabbitMQ sender and listener config catalog docs

en/docs/install-and-setup/setup/api-controller/managing-apis-api-products/importing-apis-via-dev-first-approach.md, en/docs/install-and-setup/setup/api-controller/managing-apis-api-products/migrating-apis-to-different-environments.md, en/docs/reference/customize-product/customizations/implementing-a-custom-validation-engine.md, en/mkdocs.yml
=> Improve Governance related docs

en/docs/install-and-setup/setup/multi-dc-deployment/configuring-multi-dc-deployment-pattern-1.md
This PR adds the refined file structure to the Multi-DC docs with PostgreSQL files.
=> [4.4.0] Add Multi-DC Related Updates to the Doc Space

en/docs/governance/api-governance-admin-capabilities.md
This pull request updates the documentation for API governance capabilities in WSO2 API Manager. The changes primarily focus on improving the accuracy and consistency of references and instructions.
=> Fix Governance Broken Links

en/docs/get-started/api-manager-quick-start-guide.md
=> Updated quickstart guide helm deployment guide link

en/docs/install-and-setup/setup/security/configuring-keystores/configuring-keystores-in-wso2-api-manager.md
This is raised to update the Configuring Keystore page with custom keystores details.
=> Update configuring keystores doc with custom keystore

en/docs/reference/connectors/csv-module/csv-module-config.md
=> Add note about required opencsv jar for MI CSV Module 2.x.x

en/docs/reference/connectors/file-connector/file-connector-config.md
=> Update access mask config

en/docs/reference/connectors/file-connector/file-connector-config.md
=> [4.1.0]Update the default value of diskShareAccessMask  of SMB config to MAXIMUM_ALLOWED

en/docs/reference/connectors/salesforce-connectors/sf-inbound-endpoint-reference-configuration.md
Add configs related to https://github.com/wso2/product-micro-integrator/issues/4098
=> Update SF inbound endpoint configs

en/docs/install-and-setup/setup/deployment-best-practices/security-guidelines-for-production-deployment.md
=> [4.5.0] Update security guidelines for Try-It tool

en/docs/install-and-setup/setup/deployment-best-practices/security-guidelines-for-production-deployment.md
=> [3.2.0] Update security guidelines for Try-It tool

en/docs/install-and-setup/setup/deployment-best-practices/security-guidelines-for-production-deployment.md
=> [4.0.0] Update security guidelines for Try-It tool

en/docs/install-and-setup/setup/deployment-best-practices/security-guidelines-for-production-deployment.md
=> [4.1.0] Update security guidelines for Try-It tool

en/docs/install-and-setup/setup/deployment-best-practices/security-guidelines-for-production-deployment.md
=> [4.2.0] Update security guidelines for Try-It tool

en/docs/install-and-setup/setup/deployment-best-practices/security-guidelines-for-production-deployment.md
=> [4.3.0] Update security guidelines for Try-It tool

en/docs/install-and-setup/setup/deployment-best-practices/security-guidelines-for-production-deployment.md
=> [4.4.0] Update security guidelines for Try-It tool

en/docs/install-and-setup/setup/deployment-best-practices/security-guidelines-for-production-deployment.md
=> Update security guidelines for Try-It tool

en/docs/reference/connectors/file-connector/file-connector-config.md
=> Update file connector version

en/docs/install-and-setup/setup/multi-dc-deployment/configuring-multi-dc-deployment-pattern-1.md
Refactor supported database section in multi-dc documentation.
=> [4.4.0] Refactor supported database section in multi-dc docs

en/docs/install-and-setup/setup/multi-dc-deployment/configuring-multi-dc-deployment-pattern-1.md
Refactor supported database section in multi-dc documentation.
=> [4.5.0] Refactor supported database section in multi-dc docs

en/docs/install-and-setup/setup/multi-dc-deployment/configuring-multi-dc-deployment-pattern-1.md
Refactor supported database section in multi-dc documentation.
=> Refactor supported database section in multi-dc docs

en/docs/reference/config-catalog.md, en/tools/config-catalog-generator/data/configs.json, en/tools/config-catalog-generator/data/synapse_properties.toml
Documents configuration `ws.transport.subprotocol.negotiate config` in 3.2.0 doc space.
=> Document ws.transport.subprotocol.negotiate config

en/docs/install-and-setup/setup/api-controller/getting-started-with-wso2-api-controller.md, en/docs/install-and-setup/setup/api-controller/managing-apis-api-products/managing-apis-and-api-products.md, en/docs/install-and-setup/setup/api-controller/managing-apis-api-products/migrating-apis-to-different-environments.md, en/docs/install-and-setup/setup/api-controller/managing-applications/managing-applications.md, en/docs/reference/product-apis/publisher-apis/publisher-v3/publisher-v3.yaml
Updating the resources related to apictl new version
Updated the download links
N/A
https://github.com/wso2/product-apim-tooling/pull/1292
=> Update resources for apictl 4.1.6 release

en/docs/manage-apis/deploy-and-publish/deploy-on-gateway/federated-gateways/deploy-on-aws-api-gateway.md
$subject
Related samples-apim PR : https://github.com/wso2/samples-apim/pull/149
=> [4.5.0] Improve docs on adding security to AWS API

en/docs/assets/attachments/reference/quick-start-postman-collection.json, en/docs/reference/product-apis/overview.md
- Modify the REST API Quick Start Guide (QSG) to support APIM 4.5.0
=> Modify REST API QSG to Support APIM 4.5.0

en/docs/design/api-security/oauth2/token-persistence.md, en/docs/install-and-setup/setup/deployment-best-practices/performance-test-results-token-persistence.md
=> add token persistence optimization for 4.4.0

en/docs/assets/attachments/reference/admin-v4_postman_collection.json, en/docs/assets/attachments/reference/devportal-v3_postman_collection.json, en/docs/assets/attachments/reference/publisher-v4_postman_collection.json, en/docs/assets/attachments/reference/quick-start-postman-collection.json, en/docs/reference/product-apis/admin-apis/admin-v4/admin-v4.yaml, en/docs/reference/product-apis/devportal-apis/devportal-v3/devportal-v3.yaml, en/docs/reference/product-apis/overview.md, en/docs/reference/product-apis/publisher-apis/publisher-v4/publisher-v4.yaml
=> Fix postman collections

en/docs/install-and-setup/setup/kubernetes-deployment/kubernetes/am-pattern-0-all-in-one.md, en/docs/install-and-setup/setup/kubernetes-deployment/kubernetes/am-pattern-1-all-in-one-ha.md, en/docs/install-and-setup/setup/kubernetes-deployment/kubernetes/am-pattern-2-all-in-one-gw.md, en/docs/install-and-setup/setup/kubernetes-deployment/kubernetes/am-pattern-3-acp-tm-gw.md, en/docs/install-and-setup/setup/kubernetes-deployment/kubernetes/am-pattern-4-acp-tm-gw-km.md, en/docs/install-and-setup/setup/kubernetes-deployment/kubernetes/am-pattern-5-all-in-one-gw-km.md, en/docs/install-and-setup/setup/kubernetes-deployment/openshift/openshift-deployment-overview.md
Add helm chart version to the helm command
=> 4.5.0 k8s docs

en/tools/config-catalog-generator/data/apim.toml, en/tools/config-catalog-generator/data/configs.json
Add missing file changes for PR: https://github.com/wso2/docs-apim/pull/9202
=> Add configuration information for gateway type

en/tools/config-catalog-generator/data/apim.toml, en/tools/config-catalog-generator/data/configs.json
Add missing file changes for PR: https://github.com/wso2/docs-apim/pull/9202
=> [APIM-4.5.0] Add configuration information for gateway type

en/docs/deploy-and-publish/deploy-on-gateway/api-gateway/scaling-the-gateway.md
=> Improve traffic manager recomondations

en/docs/install-and-setup/install-and-setup-overview.md, en/docs/install-and-setup/install/installation-prerequisites.md
Remove Mariadb entries from the doc
=> Remove mariadb entries

en/docs/install-and-setup/setup/deployment-overview.md, en/docs/install-and-setup/setup/kubernetes-deployment/kubernetes/am-pattern-0-all-in-one.md, en/docs/install-and-setup/setup/kubernetes-deployment/kubernetes/am-pattern-1-all-in-one-ha.md, en/docs/install-and-setup/setup/kubernetes-deployment/kubernetes/am-pattern-2-all-in-one-gw.md, en/docs/install-and-setup/setup/kubernetes-deployment/kubernetes/am-pattern-3-acp-tm-gw.md, en/docs/install-and-setup/setup/kubernetes-deployment/kubernetes/am-pattern-4-acp-tm-gw-km.md, en/docs/install-and-setup/setup/kubernetes-deployment/kubernetes/am-pattern-5-all-in-one-gw-km.md, en/docs/install-and-setup/setup/kubernetes-deployment/openshift/openshift-deployment-overview.md
This pull request updates the deployment patterns in the documentation to reflect changes in component descriptions and improves the visual presentation of images. The most important changes include updates to the "Components" field for two deployment patterns and adjustments to image widths for consistency.
* Updated the "Components" field in **Pattern 2** to reflect a shift from "API Control Plane" to "All-in-one" for a simpler description of the deployment setup. (`en/docs/install-and-setup/setup/deployment-overview.md`)
* Updated the "Components" field in **Pattern 5** similarly, changing "API Control Plane" to "All-in-one" for consistency with other patterns. (`en/docs/install-and-setup/setup/deployment-overview.md`)
* Adjusted the image width for **Pattern 5** from 100% to 60% to …
=> 4.5.0 docs - change overview

en/docs/reference/config-catalog.md, en/tools/config-catalog-generator/data/_ws-transport.toml, en/tools/config-catalog-generator/data/_wss-transport.toml, en/tools/config-catalog-generator/data/configs.json
Update config catalog with `wsSharedEventLoopPoolSize` config.
Reference: https://github.com/wso2/api-manager/issues/3889
=> [320] Add wsSharedEventLoopPoolSize configurations for Websocket connections

en/docs/reference/faq.md
> $subject
References: https://github.com/wso2/api-manager/issues/3881
=> Update FAQ with -DincludeTokenInfoInMsgCtx config

en/docs/reference/faq.md
> $subject
References: https://github.com/wso2/api-manager/issues/3881
=> [3.2.0] Update FAQ with -DincludeTokenInfoInMsgCtx config

en/docs/reference/faq.md
> $subject
References: https://github.com/wso2/api-manager/issues/3881
=> [4.4.0] Update FAQ with -DincludeTokenInfoInMsgCtx config

en/docs/install-and-setup/setup/deployment-overview.md, en/docs/install-and-setup/setup/distributed-deployment/deploying-wso2-api-m-in-a-simple-scalable-setup.md, en/docs/install-and-setup/setup/kubernetes-deployment/kubernetes/am-pattern-0-all-in-one.md, en/docs/install-and-setup/setup/kubernetes-deployment/kubernetes/am-pattern-1-all-in-one-ha.md, en/docs/install-and-setup/setup/kubernetes-deployment/kubernetes/am-pattern-2-all-in-one-gw.md, en/docs/install-and-setup/setup/kubernetes-deployment/kubernetes/am-pattern-3-acp-tm-gw.md, en/docs/install-and-setup/setup/kubernetes-deployment/kubernetes/am-pattern-4-acp-tm-gw-km.md, en/docs/install-and-setup/setup/kubernetes-deployment/kubernetes/am-pattern-5-all-in-one-gw-km.md, en/docs/install-and-setup/setup/kubernetes-deployment/kubernetes/kubernetes-overview.md, en/docs/install-and-setup/setup/kubernetes-deployment/openshift/openshift-deployment-overview.md, en/docs/install-and-setup/setup/single-node/all-in-one-deployment-overview.md, en/docs/install-and-setup/setup/single-node/deployment-overview.md, en/mkdocs.yml
Migrate k8s deployment docs to master branch
=> Migrate k8s deployment docs to master branch

en/docs/install-and-setup/setup/kubernetes-deployment/kubernetes/am-pattern-1-all-in-one-ha.md, en/docs/install-and-setup/setup/kubernetes-deployment/kubernetes/am-pattern-2-all-in-one-gw.md, en/docs/install-and-setup/setup/kubernetes-deployment/kubernetes/am-pattern-3-acp-tm-gw.md, en/docs/install-and-setup/setup/kubernetes-deployment/kubernetes/am-pattern-4-acp-tm-gw-km.md, en/docs/install-and-setup/setup/kubernetes-deployment/kubernetes/am-pattern-5-all-in-one-gw-km.md
Add USER argument to Dockerfile examples in deployment patterns
=> Add USER argument to Dockerfile in deployment patterns

en/docs/manage-apis/design/api-security/oauth2/token-revocation.md
To add the $subject information to the Token Revocation page
=> [4.5.0] Add Revoking tokens with third party Key Managers to the docs

en/docs/design/api-security/oauth2/token-revocation.md
To add the $subject information to the Token Revocation page
=> Add Revoking tokens with third party Key Managers to the docs

en/docs/install-and-setup/install/installation-options.md
=> Updating installation options links to 4.5.0

en/docs/reference/config-catalog.md, en/tools/config-catalog-generator/data/authentication_policy.toml, en/tools/config-catalog-generator/data/configs.json
- $subject
- Related to: https://github.com/wso2-enterprise/wso2-apim-internal/issues/9829
=> [4.0.0] Introduce legacy authentication enabling config

en/docs/design/api-monetization/monetizing-an-api.md
> Add instruction on proxy configurations for monetization.
=> Add instruction on proxy configurations for monetization

en/docs/install-and-setup/setup/api-controller/getting-started-with-wso2-api-controller.md
=> Fix APICTL download links

en/docs/consume/manage-application/create-application.md
fixes: https://github.com/wso2-enterprise/wso2-apim-internal/issues/9757
=> Fix: Missing Configuration for Disabling Default Applications

en/docs/reference/config-catalog.md, en/tools/config-catalog-generator/data/apim.oauth_config.toml, en/tools/config-catalog-generator/data/configs.json
$subject
- https://github.com/wso2-enterprise/wso2-apim-internal/issues/9775
=> [4.4.0] Add enable_revoke_token_cleanup configuration to config-catalog

en/docs/ai-gateway/ai-vendor-management/custom-ai-vendors/onboarding-anthropic-claude.md, en/docs/assets/attachments/admin/custom-ai-vendors/add-anthropic-claude/claude-api.yaml
This PR updates the Anthropic Claude API definition provided in our documentation with a community-released OpenAPI 3.0.0 schema. Also it includes a note to indicate the same as Claude does not expose an API definition officially.
=> [4.5.0] Update Anthropic Claude API Definition

en/docs/reference/config-catalog.md, en/tools/config-catalog-generator/data/apim.oauth_config.toml, en/tools/config-catalog-generator/data/configs.json
$subject
- https://github.com/wso2-enterprise/wso2-apim-internal/issues/9774
=> [4.5.0] Add enable_revoke_token_cleanup configuration to config-catalog

en/docs/tutorials/tutorials-overview.md, en/mkdocs.yml
Fixes https://github.com/wso2/docs-apim/issues/9365
=> Refactor tutorials overview page

en/docs/tutorials/tutorials-overview.md
Fixes related to https://github.com/wso2/docs-apim/issues/9365
=> Correct doc link

en/docs/consume/generating-sdks/generate-sdks-in-dev-portal.md, en/docs/reference/customize-product/extending-api-manager/extending-gateway/writing-custom-handlers.md, en/docs/reference/customize-product/extending-api-manager/extending-workflows/customizing-a-workflow-extension.md, en/docs/reference/product-apis/devportal-apis/devportal-v3/devportal-v3.yaml, en/docs/reference/product-apis/publisher-apis/publisher-v4/publisher-v4.yaml
Fixes: 
https://github.com/wso2-enterprise/wso2-apim-internal/issues/9367
https://github.com/wso2-enterprise/wso2-apim-internal/issues/2608
https://github.com/wso2-enterprise/wso2-apim-internal/issues/9305
https://github.com/wso2-enterprise/wso2-apim-internal/issues/9347
https://github.com/wso2-enterprise/wso2-apim-internal/issues/8943
=> Fix minor Doc Issues

en/docs/ai-gateway/ai-guardrails/safety-categories/overview.md
Fix minor issue in AI guardrails documentation
=> Fix minor issue in AI guardrails documentation

en/docs/administer/managing-users-and-roles/managing-user-stores/configure-primary-user-store/configuring-a-read-write-active-directory-user-store.md, en/docs/design/api-security/oauth2/encrypting-oauth2-tokens.md, en/docs/install-and-setup/setup/advance-configurations/changing-the-default-transport.md, en/docs/reference/customize-product/extending-api-manager/extending-workflows/customizing-a-workflow-extension.md
Fixes the below doc issues:
https://github.com/wso2-enterprise/wso2-apim-internal/issues/3014
https://github.com/wso2-enterprise/wso2-apim-internal/issues/10177
https://github.com/wso2-enterprise/wso2-apim-internal/issues/8943
=> Fix missing doc content

en/docs/install-and-setup/setup/kubernetes-deployment/kubernetes/am-pattern-2-all-in-one-gw.md, en/docs/install-and-setup/setup/kubernetes-deployment/kubernetes/am-pattern-3-acp-tm-gw.md, en/docs/install-and-setup/setup/kubernetes-deployment/kubernetes/am-pattern-4-acp-tm-gw-km.md, en/docs/install-and-setup/setup/kubernetes-deployment/kubernetes/am-pattern-5-all-in-one-gw-km.md, en/docs/install-and-setup/setup/kubernetes-deployment/openshift/openshift-deployment-overview.md
Correct gateway helm chart name
=> 4.5.0 fix gateway name

en/docs/ai-gateway/ai-guardrails/aws-bedrock-guardrail.md, en/docs/ai-gateway/ai-guardrails/azure-content-safety.md, en/docs/ai-gateway/ai-guardrails/overview.md, en/docs/ai-gateway/ai-guardrails/regex-pii-masking.md, en/docs/ai-gateway/ai-guardrails/semantic-prompt-guardrail.md, en/mkdocs.yml
Add documentation for the following guardrails
- PII Masking with Regex
- Semantic Prompt Guardrail
- Azure Content Safety Content Moderation
- AWS Bedrock Guardrail
=> Add documentation for guardrail integrations

en/docs/ai-gateway/ai-guardrails/overview.md, en/docs/ai-gateway/prompt-management/overview.md
Fix the grid of guardrails view
=> Fix aesthetics of the guardrail cards

en/docs/deploy-and-publish/deploy-on-gateway/choreo-connect/message-transformation/interceptor-microservice/request-flow-interceptor.md
Clarifies the update is available as an U2 update and date in a standardised format.
=> Fix grammatical errors

en/docs/manage-apis/deploy-and-publish/deploy-on-gateway/federated-gateways/configure-custom-gateway-agent.md
Tries a fix for https://github.com/wso2/docs-apim/issues/9482
Replaced base_path placeholder with exact value to narrowdown the issue
=> [4.5.0] Try fix2 for artifact download issue in chrome

en/docs/ai-gateway/ai-guardrails/aws-bedrock-guardrail.md, en/docs/ai-gateway/ai-guardrails/azure-content-safety.md, en/docs/ai-gateway/ai-guardrails/content-length-guardrail.md, en/docs/ai-gateway/ai-guardrails/json-schema-guardrail.md, en/docs/ai-gateway/ai-guardrails/overview.md, en/docs/ai-gateway/ai-guardrails/regex-guardrail.md, en/docs/ai-gateway/ai-guardrails/regex-pii-masking.md, en/docs/ai-gateway/ai-guardrails/semantic-prompt-guardrail.md, en/docs/ai-gateway/ai-guardrails/sentence-count-guardrail.md, en/docs/ai-gateway/ai-guardrails/url-guardrail.md, en/docs/ai-gateway/ai-guardrails/word-count-guardrail.md, en/docs/ai-gateway/prompt-management/prompt-decorator.md, en/docs/ai-gateway/prompt-management/prompt-template.md
This PR updates the Guardrail and Prompt Management policy documentation to include the corresponding policy artifacts released on GitHub.
=> Update guardrail policies with github release artifacts

en/docs/reference/mediators/header-mediator.md
=> Modify header mdediator doc for soap headers

en/docs/assets/css/theme.css, en/mkdocs.yml, en/theme/material/partials/header.html
This PR bumps the doc version to 4.6.0 and Add WIP banner.
=> Bump doc version to 4.6.0 and Add WIP banner

en/docs/install-and-setup/setup/api-controller/cicd-using-cli.md, en/docs/install-and-setup/setup/api-controller/enabling-correlation-logs-with-apictl.md, en/docs/install-and-setup/setup/api-controller/getting-started-with-wso2-api-controller.md, en/docs/install-and-setup/setup/api-controller/managing-apis-api-products/managing-apis-and-api-products.md, en/docs/install-and-setup/setup/api-controller/managing-apis-api-products/migrating-apis-to-different-environments.md, en/docs/install-and-setup/setup/api-controller/managing-applications/managing-applications.md, en/docs/reference/product-apis/publisher-apis/publisher-v4/publisher-v4.yaml
Updating the resources related to apictl new version
Updated the download links
N/A
https://github.com/wso2/product-apim-tooling/pulls?q=is%3Apr+label%3A4.2.7+is%3Aclosed
=> Update resources for apictl v4.2.7 release

en/docs/develop/product-apis/admin-apis/admin-v0.17/admin-v0.17.yaml
This fix updates the description of the 412 status code in REST Api docs as it was reported to be less descriptive.
=> Remove 412 error code from Change Application Owner in admin rest api

en/docs/install-and-setup/setup/deployment-best-practices/backup-recovery.md
This PR adds missing doc on backup and recovery.
=> Add backup and recovery docs

en/docs/install-and-setup/setup/deployment-best-practices/changing-the-hostname.md
=> Add missing note on configuring internal hostname

en/docs/manage-apis/deploy-and-publish/deploy-on-gateway/api-gateway/api-gateways-with-dedicated-backends.md, en/docs/manage-apis/deploy-and-publish/deploy-on-gateway/federated-gateways/configure-custom-gateway-agent.md
Fixes : https://github.com/wso2/docs-apim/issues/8979
=> [4.5.0] Fix broken links in documentation.

en/docs/deploy-and-publish/deploy-on-gateway/api-gateway/api-gateways-with-dedicated-backends.md, en/docs/design/api-monetization/monetizing-an-api.md, en/docs/governance/governance-concept.md
Fixes: https://github.com/wso2/docs-apim/issues/8979
=> [4.6.0] Fix broken links in documentation

en/docs/administer/logging-and-monitoring/monitoring/monitoring-tcp-based-messages.md, en/docs/governance/governance-concept.md, en/docs/includes/design/create-graphql-api.md, en/docs/install-and-setup/setup/security/configuring-transport-level-security.md, en/docs/manage-apis/deploy-and-publish/deploy-on-gateway/federated-gateways/deploy-on-aws-api-gateway.md, en/docs/manage-apis/design/api-monetization/monetizing-an-api.md, en/docs/tutorials/create-distributed-setup-using-the-enterprise-package.md
Fixes:
https://github.com/wso2/docs-apim/issues/9482
https://github.com/wso2/docs-apim/issues/9578
https://github.com/wso2/docs-apim/issues/9381
=> [4.5.0] Fix broken links

.github/ISSUE_TEMPLATE/bug.yml, .github/ISSUE_TEMPLATE/improvement.yml, .github/ISSUE_TEMPLATE/question_form.yml
> This PR modifies the issue templates for bug, improvement and question type issues in the docs-apim repo.
=> Modify the issue templates

en/docs/manage-apis/deploy-and-publish/deploy-on-gateway/federated-gateways/deploy-on-aws-api-gateway.md, en/docs/tutorials/create-distributed-setup-using-the-enterprise-package.md
Testing the Fix done for broken URLs in 4.5.0
=> Testing the fix for broken links in 4.5.0

en/docs/manage-apis/deploy-and-publish/deploy-on-gateway/federated-gateways/deploy-on-aws-api-gateway.md
=> [4.5.0] Changed basepath variable to base_path

en/docs/ai-gateway/semantic-caching.md, en/mkdocs.yml
Related Issues:
- https://github.com/wso2/api-manager/issues/4098
=> Add Semantic cache doc

en/docs/design/advanced-topics/enable-publisher-access-control-in-api-publisher-portal.md
=> Update note on role validation for publisher access control

en/docs/design/advanced-topics/enable-publisher-access-control-in-api-publisher-portal.md
=> Update note on role validation case sensitivity

en/docs/design/advanced-topics/enable-publisher-access-control-in-api-publisher-portal.md
=> Update role validation instructions for publisher access

en/docs/reference/config-catalog.md, en/tools/config-catalog-generator/data/configs.json
This PR adds missing configs on jwt configurations.
=> Add missing configs to config catalog

en/docs/reference/config-catalog.md, en/tools/config-catalog-generator/data/configs.json, en/tools/config-catalog-generator/data/databridge.toml
This PR adds missing config to the configuration catalog on configuring binary databridge receiver and agent.
=> Add missing databridge configs to config catalog

en/docs/reference/mediators/clone-mediator.md
=> Fix typo and syntax in clone mediator docs

.github/workflows/claude_runner.yml, .github/workflows/queue_runner.yml
Changed 'AI-Agent' to 'wso2-engineering-bot' to trigger
=> Changed @AI-Agent to @wso2-engineering-bot

en/docs/design/advanced-topics/enabling-cors-for-apis.md
https://github.com/wso2/docs-apim/issues/9778
=> add a note to clarify behaviour with api level CORS

en/docs/reference/config-catalog.md, en/tools/config-catalog-generator/data/apim.devportal.toml, en/tools/config-catalog-generator/data/apim.mcp.toml, en/tools/config-catalog-generator/data/configs.json
=> Fix configs for MCP

en/docs/includes/deploy/steps-to-deploy-apim-in-a-distributed-setup-with-km-separation.md, en/docs/includes/deploy/steps-to-deploy-apim-in-a-distributed-setup-with-tm-separation.md, en/docs/install-and-setup/setup/distributed-deployment/deploying-wso2-api-m-in-a-simple-scalable-setup.md, en/docs/reference/config-catalog.md, en/tools/config-catalog-generator/data/apim.gateway_notification.toml, en/tools/config-catalog-generator/data/configs.json
This PR will add gateway notification config to config.jason
Related PR - https://github.com/wso2/docs-apim/pull/9641
Related issue - https://github.com/wso2/api-manager/issues/3925
=> [4.6.0] Add gateway notification config to config.jason

en/docs/install-and-setup/setup/api-controller/getting-started-with-wso2-api-controller.md
=> Update download links for apictl to version 4.0.5

en/docs/install-and-setup/setup/api-controller/managing-apis-api-products/migrating-apis-to-different-environments.md, en/docs/reference/product-apis/publisher-apis/publisher-v2/publisher-v2.yaml
Related to https://github.com/wso2-enterprise/wso2-apim-internal/issues/10789
Ports https://github.com/wso2/docs-apim/pull/9154
=> [APIM 4.0.0] Document preserveCredentials parameter in REST API and --preserve-credentials flag in APICTL

en/docs/design/rate-limiting/advanced-topics/distributed-throttling.md, en/mkdocs.yml
=> [4.0.0] Add docs for distributed throttling counter feature 

en/docs/manage-apis/design/rate-limiting/advanced-topics/distributed-throttling.md
=> [Master]Change redis doc link for distributed throttling counter feature

en/docs/consume/manage-application/advanced-topics/adding-an-application-key-generation-workflow.md, en/docs/install-and-setup/setup/api-controller/managing-apis-api-products/migrating-api-products-to-different-environments.md, en/docs/reference/product-apis/admin-apis/admin-v4/admin-v4.yaml, en/docs/reference/product-apis/devportal-apis/devportal-v3/devportal-v3.yaml, en/docs/reference/product-apis/gateway-apis/gateway-v2/gateway-v2.yaml, en/docs/reference/product-apis/publisher-apis/publisher-v4/publisher-v4.yaml, en/docs/reference/product-apis/service-catalog-apis/service-catalog-v1/service-catalog-v1.yaml
Fix: spelling mistakes [4.2.0]
Applied all spelling fixes from 4.6.0 plus additional fixes unique to 4.2.0:
From 4.6.0:
- "recieve" → "receive" (4 instances)
- "seperate" → "separate" (4 instances)
- "successfull" → "successful" (4 instances)
Additional fixes unique to 4.5.0:
- "seperated" → "separated" (6 instances)
- "retrive" → "retrieve" (1 instance)
- "passowrd" → "password" (5 instances)
- "cliet_id" → "client_id" (5 instances)
- "transfered" → "transferred" (5 instances)
- "existance" → "existence" (1 instance)
- "paramter" → "parameter" (2 instances)
- "retreive" → "retrieve" (1 instance)
Files modified:
- en/docs/install-and-setup/setup/api-controller/managing-apis-api-products/migrating-api-products-to-different-environments.md
- …
=> Fix: Spelling mistakes [4.2.0]

en/docs/install-and-setup/setup/security/configuring-transport-level-security.md
Resolving the issue: https://github.com/wso2/docs-apim/issues/9916
=> [4.5.0] Update the cipher list and outdated links

en/docs/manage-apis/deploy-and-publish/federated-gateways/kong/kong-kubernetes/deploy-on-kong-gateway-in-kubernetes.md, en/docs/manage-apis/deploy-and-publish/federated-gateways/kong/kong-kubernetes/discover-apis-on-kong-gateway-in-kubernetes.md
This PR addresses the added PR comments on https://github.com/wso2/docs-apim/pull/9703
=> Address added PR comments

en/docs/reference/config-catalog.md, en/tools/config-catalog-generator/data/apim.mediator_config.oauth.trust_store.toml, en/tools/config-catalog-generator/data/configs.json
=> Add apim.mediator_config.oauth.trust_store configs to config catalog

en/docs/install-and-setup/setup/deployment-best-practices/security-guidelines-for-production-deployment.md
Adds guidelines for script mediator in documentation
=> [4.6.0] Add script mediator section for security guidelines

en/docs/install-and-setup/setup/deployment-best-practices/security-guidelines-for-production-deployment.md
Adds guidelines for script mediator in documentation
=> [4.5.0] Add script mediator section for security guidelines

en/docs/install-and-setup/setup/deployment-best-practices/security-guidelines-for-production-deployment.md
Adds guidelines for script mediator in documentation
=> [4.3.0] Adds guidelines for script mediator

en/docs/ai-gateway/ai-guardrails/regex-guardrail.md, en/docs/ai-gateway/prompt-management/prompt-template.md
> This pull request makes minor corrections to documentation for the Regex Guardrail and Prompt Template features. The changes fixes the errors encountered when testing Regex Guardrail and Prompt Template features using the samples given in the documentation.
Documentation corrections:
* Updated the example regex pattern in the Regex Guardrail documentation by removing unnecessary escape characters `\\` for the pipe symbol `|` that denotes the `OR`.
*  Replace the character U+2013 "–" in 3–5 with ASCII character U+002d "-" 3-5.
* Rename the same prompt template to customer-support-template to avoid duplicates.
Fixes : [wso2/api-manager/issues#4408](https://github.com/wso2/api-manager/issues/4408)
=> Fix AI guardrail doc issues

en/docs/install-and-setup/setup/deployment-best-practices/security-guidelines-for-production-deployment.md
Add guidelines for script mediator
=> [3.2.0] Add guidelines for script mediator

en/docs/install-and-setup/setup/deployment-best-practices/security-guidelines-for-production-deployment.md
Adds guidelines for script mediator
=> [4.0.0] Add guidelines for script mediator

en/docs/install-and-setup/setup/deployment-best-practices/security-guidelines-for-production-deployment.md, en/docs/manage-apis/design/api-policies/create-policy.md
=> Add script access control section to policies

en/docs/design/api-policies/create-policy.md, en/docs/install-and-setup/setup/deployment-best-practices/security-guidelines-for-production-deployment.md
=> [4.4.0] Add script access control section to policies

en/docs/design/api-policies/create-policy.md, en/docs/install-and-setup/setup/deployment-best-practices/security-guidelines-for-production-deployment.md
=> [4.3.0] Add script access control section to policies

en/docs/deploy-and-publish/deploy-on-gateway/api-gateway/message-mediation/changing-the-default-mediation-flow-of-api-requests.md, en/docs/install-and-setup/setup/deployment-best-practices/security-guidelines-for-production-deployment.md
=> [4.0.0] Add script access control section to policies

en/docs/design/api-policies/create-policy.md, en/docs/install-and-setup/setup/deployment-best-practices/security-guidelines-for-production-deployment.md
=> [4.2.0] Add script access control section to policies

en/docs/design/api-policies/create-policy.md, en/docs/install-and-setup/setup/deployment-best-practices/security-guidelines-for-production-deployment.md
=> [4.1.0] Add script access control section to policies
